package com.shiviishiv7.helloenglish.QuestionSource;

import java.util.HashMap;
import java.util.Map;

public class AnswerNegativeData {
    public static Map<String,String> getData(int state){
        switch (state){
            case 1:return One();
            case 2:return Two();
            case 3:return Three();
            case 4:return Four();
            case 5:return Five();
            case 6:return Six();
            case 7:return Seven();
            case 8:return Eight();
            case 9:return Nine();
            case 10:return Ten();
            case 11:return Eleven();
            case 12:return Twelve();

            default:return One();
        }

    }
    private static Map<String, String> Twelve() {
        HashMap<String,String> map = new HashMap<>();
        map.put("I  will have been not abusing ", " मैं गाली नहीं दे रहा होगा ");
        map.put("I  will have been not advising ", " मैं सलाह नहीं दे रहा होगा ");
        map.put("I  will have been not answering ", " मैं जवाब नहीं दे रहा होगा ");
        map.put("I  will have been not arising ", " मैं नहीं उठ रहा होगा ");
        map.put("I  will have been not arriving ", " मैं नहीं आ रहा होगा ");
        map.put("I  will have been not asking ", " मैं नहीं पूछ रहा होगा ");
        map.put("I  will have been not awaking ", " मैं जाग नहीं रहा होगा ");
        map.put("I  will have been not undefined", " मैं अपरिभाषित नहीं होता");
        map.put("I  will have been not bearing ", " मैं असर नहीं कर रहा होगा ");
        map.put("I  will have been not beating ", " मैं पिटाई नहीं कर रहा होगा ");
        map.put("I  will have been not becoming ", " मैं नहीं बन रहा होगा ");
        map.put("I  will have been not begging ", " मैं भीख नहीं माँगता ");
        map.put("I  will have been not beginning ", " मैं शुरुआत नहीं कर रहा होगा ");
        map.put("I  will have been not binding ", " मैं बाध्यकारी नहीं होता ");
        map.put("I  will have been not biting ", " मैं काट नहीं रहा होगा ");
        map.put("I  will have been not blessing ", " मैं आशीष नहीं रहा होता ");
        map.put("I  will have been not blowing ", " मैं उड़ नहीं रहा होगा ");
        map.put("I  will have been not breaking ", " मैं तोड़ नहीं रहा होगा ");
        map.put("I  will have been not bringing ", " मैं नहीं ला रहा हूँ ");
        map.put("I  will have been not building ", " मैं निर्माण नहीं कर रहा होगा ");
        map.put("I  will have been not burning ", " मैं जल नहीं रहा होगा ");
        map.put("I  will have been not buying ", " मैं खरीद नहीं रहा होगा ");
        map.put("I  will have been not calling ", " मैं फोन नहीं कर रहा होगा ");
        map.put("I  will have been not carrying ", " मैं नहीं ले जाऊंगा ");
        map.put("I  will have been not catching ", " मैं पकड़ नहीं रहा होगा ");
        map.put("I  will have been not cheating ", " मैं धोखा नहीं दे रहा होगा ");
        map.put("I  will have been not choosing ", " मैं नहीं चुन रहा होगा ");
        map.put("I  will have been not cleaning ", " मैं सफाई नहीं कर रहा होगा ");
        map.put("I  will have been not climbing ", " मैं चढ़ नहीं रहा होगा ");
        map.put("I  will have been not closing ", " मैं बंद नहीं हो रहा होगा ");
        map.put("I  will have been not coming ", " मैं नहीं आ रहा होगा ");
        map.put("I  will have been not cooking ", " मैं खाना नहीं बना रहा होगा ");
        map.put("I  will have been not creeping ", " मैं रेंग नहीं रहा होगा ");
        map.put("I  will have been not crying ", " मैं रो नहीं रहा होगा ");
        map.put("I  will have been not cutting ", " मैं काट नहीं रहा होगा ");
        map.put("I  will have been not dancing ", " मैं नाचता नहीं रहा होगा ");
        map.put("I  will have been not dealing ", " मैं काम नहीं कर रहा होगा ");
        map.put("I  will have been not dying ", " मैं मर नहीं रहा होगा ");
        map.put("I  will have been not digging ", " मैं खुदाई नहीं कर रहा होगा ");
        map.put("I  will have been not drawing ", " मैं ड्राइंग नहीं कर रहा होगा ");
        map.put("I  will have been not drinking ", " मैं शराब नहीं पी रहा होगा ");
        map.put("I  will have been not driving ", " मैं गाड़ी नहीं चला रहा होगा ");
        map.put("I  will have been not dropping ", " मैं नहीं छोड़ रहा होगा ");
        map.put("I  will have been not drying ", " मैं सूख नहीं रहा होगा ");
        map.put("I  will have been not eating ", " मैं नहीं खा रहा होगा ");
        map.put("I  will have been not electing ", " मैं चुनाव नहीं कर रहा होता ");
        map.put("I  will have been not entering ", " मैं प्रवेश नहीं कर रहा हूँ ");
        map.put("I  will have been not falling ", " मैं गिर नहीं रहा होगा ");
        map.put("I  will have been not feeding ", " मैं खिला नहीं रहा होगा ");
        map.put("I  will have been not feeling ", " मैं महसूस नहीं कर रहा होगा ");
        map.put("I  will have been not fighting ", " मैं लड़ नहीं रहा होगा ");
        map.put("I  will have been not finding ", " मुझे नहीं मिल रहा होगा ");
        map.put("I  will have been not fleeing ", " मैं भाग नहीं रहा होगा ");
        map.put("I  will have been not flying ", " मैं उड़ नहीं रहा होगा ");
        map.put("I  will have been not forgetting ", " मैं नहीं भूलूंगा ");
        map.put("I  will have been not frying ", " मैं फ्राइंग नहीं कर रहा होगा ");
        map.put("I  will have been not getting ", " मुझे नहीं मिल रहा होगा ");
        map.put("I  will have been not giving ", " मैं नहीं दे रहा होगा ");
        map.put("I  will have been not going ", " मैं नहीं जा रहा होगा ");
        map.put("I  will have been not growing ", " मैं नहीं बढ़ रहा होगा ");
        map.put("I  will have been not hanging ", " मैं लटका नहीं रहा होगा ");
        map.put("I  will have been not hearing ", " मैं सुन नहीं रहा होगा ");
        map.put("I  will have been not helping ", " मैं मदद नहीं कर रहा होगा ");
        map.put("I  will have been not hiding ", " मैं छिप नहीं रहा होगा ");
        map.put("I  will have been not hitting ", " मैं मार नहीं रहा होगा ");
        map.put("I  will have been not holding ", " मैं पकड़ नहीं रहा होगा ");
        map.put("I  will have been not hoping ", " मैं उम्मीद नहीं कर रहा होगा ");
        map.put("I  will have been not hurting ", " मैं चोट नहीं पहुँचाता रहा होगा ");
        map.put("I  will have been not jumping ", " मैं कूद नहीं रहा होगा ");
        map.put("I  will have been not keeping ", " मैं नहीं रख रहा होगा ");
        map.put("I  will have been not killing ", " मैं नहीं मार रहा होगा ");
        map.put("I  will have been not knowing ", " मुझे नहीं पता होगा ");
        map.put("I  will have been not laughing ", " मैं हँस नहीं रहा होगा ");
        map.put("I  will have been not leading ", " मैं अग्रणी नहीं रहा होगा ");
        map.put("I  will have been not leaping ", " मैं छलांग नहीं लगा रहा होगा ");
        map.put("I  will have been not learning ", " मैं नहीं सीख रहा हूँ ");
        map.put("I  will have been not leaving ", " मैं नहीं जा रहा होगा ");
        map.put("I  will have been not lending ", " मैं उधार नहीं दे रहा होगा ");
        map.put("I  will have been not living ", " मैं नहीं रह रहा होगा ");
        map.put("I  will have been not looking ", " मैं नहीं देख रहा होगा ");
        map.put("I  will have been not losing ", " मैं हार नहीं रहा होगा ");
        map.put("I  will have been not loving ", " मैं प्यार नहीं करता ");
        map.put("I  will have been not making ", " मैं नहीं बना रहा होगा ");
        map.put("I  will have been not marrying ", " मैं शादी नहीं कर रहा होगा ");
        map.put("I  will have been not meeting ", " मैं मुलाकात नहीं कर रहा हूँ ");
        map.put("I  will have been not mistaking ", " मैं गलती नहीं कर रहा होगा ");
        map.put("I  will have been not opening ", " मैं नहीं खुल रहा होगा ");
        map.put("I  will have been not paying ", " मैं भुगतान नहीं कर रहा हूँ ");
        map.put("I  will have been not playing ", " मैं नहीं खेल रहा होगा ");
        map.put("I  will have been not putting ", " मैं नहीं डाल रहा होगा ");
        map.put("I  will have been not quarrelling ", " मैं झगड़ा नहीं कर रहा होगा ");
        map.put("I  will have been not raining ", " बारिश नहीं हो रही होगी ");
        map.put("I  will have been not reaching ", " मैं नहीं पहुँच रहा हूँ ");
        map.put("I  will have been not reading ", " मैं नहीं पढ़ रहा होगा ");
        map.put("I  will have been not remembering ", " मुझे याद नहीं होगा ");
        map.put("I  will have been not riding ", " मैं सवारी नहीं कर रहा होगा ");
        map.put("I  will have been not ringing ", " मैं बज नहीं रहा होगा ");
        map.put("I  will have been not rising ", " मैं नहीं उठ रहा होगा ");
        map.put("I  will have been not running ", " मैं दौड़ नहीं रहा होगा ");
        map.put("I  will have been not saying ", " मैं यह नहीं कह रहा होता ");
        map.put("I  will have been not seeing ", " मैं नहीं देख रहा होता ");
        map.put("I  will have been not selling ", " मैं नहीं बेच रहा होगा ");
        map.put("I  will have been not sending ", " मैं नहीं भेज रहा होगा ");
        map.put("I  will have been not shaking ", " मैं हिल नहीं रहा होगा ");
        map.put("I  will have been not shining ", " मैं चमक नहीं रहा होगा ");
        map.put("I  will have been not shooting ", " मैं शूटिंग नहीं कर रहा होगा ");
        map.put("I  will have been not showing ", " मैं नहीं दिखा रहा होगा ");

        return map;
    }
    private static Map<String, String> Eleven() {
        HashMap<String,String>map = new HashMap<>();
        map.put("I  will have not abused ", " मैंने गाली नहीं दी होगी ");
        map.put("I  will have not advised ", " मैंने सलाह नहीं दी होगी ");
        map.put("I  will have not answered ", " मैंने जवाब नहीं दिया होगा ");
        map.put("I  will have not arisen ", " मैं पैदा नहीं हुआ होगा ");
        map.put("I  will have not arrived ", " मैं नहीं आया होगा ");
        map.put("I  will have not asked ", " मैंने नहीं पूछा होगा ");
        map.put("I  will have not awoken ", " मैं जाग नहीं जाऊंगा ");
        map.put("I  will have not undefined", " मैंने अपरिभाषित नहीं किया होगा");
        map.put("I  will have not borne ", " मैं पैदा नहीं हुआ होगा ");
        map.put("I  will have not beaten ", " मैंने पीटा नहीं होगा ");
        map.put("I  will have not become ", " मैं नहीं बन जाऊंगा ");
        map.put("I  will have not begged ", " मैंने भीख नहीं मांगी होगी ");
        map.put("I  will have not begun ", " मैंने शुरू नहीं किया होगा ");
        map.put("I  will have not bound ", " मैंने बाउंड नहीं किया होगा ");
        map.put("I  will have not bitten ", " मैंने काट नहीं लिया होगा ");
        map.put("I  will have not blessed ", " मैंने आशीर्वाद नहीं दिया होगा ");
        map.put("I  will have not blown ", " मैंने नहीं उड़ाया होगा ");
        map.put("I  will have not broken ", " मैं टूटा नहीं होगा ");
        map.put("I  will have not brought ", " मैं नहीं लाऊंगा ");
        map.put("I  will have not built ", " मैंने नहीं बनाया होगा ");
        map.put("I  will have not burnt ", " मैं जलाया नहीं होगा ");
        map.put("I  will have not bought ", " मैंने नहीं खरीदा होगा ");
        map.put("I  will have not called ", " मैंने फोन नहीं किया होगा ");
        map.put("I  will have not carried ", " मैं नहीं ले जाऊंगा ");
        map.put("I  will have not caught ", " मैंने पकड़ा नहीं होगा ");
        map.put("I  will have not cheated ", " मैंने धोखा नहीं दिया होगा ");
        map.put("I  will have not chosen ", " मैंने नहीं चुना होगा ");
        map.put("I  will have not cleaned ", " मैंने साफ नहीं किया होगा ");
        map.put("I  will have not climbed ", " मैं नहीं चढ़ जाऊंगा ");
        map.put("I  will have not closed ", " मैंने बंद नहीं किया होगा ");
        map.put("I  will have not come ", " मैं नहीं आऊंगा ");
        map.put("I  will have not cooked ", " मैंने पकाया नहीं होगा ");
        map.put("I  will have not crept ", " मैं crept नहीं होगा ");
        map.put("I  will have not cried ", " मैं रोया नहीं होगा ");
        map.put("I  will have not cut ", " मैंने कट नहीं किया होगा ");
        map.put("I  will have not danced ", " मैंने नृत्य नहीं किया होगा ");
        map.put("I  will have not dealt ", " मैंने निपटाया नहीं होगा ");
        map.put("I  will have not died ", " मैं नहीं मरूंगा ");
        map.put("I  will have not dug ", " मैंने खोदा नहीं होगा ");
        map.put("I  will have not drawn ", " मैंने ड्रॉ नहीं किया होगा ");
        map.put("I  will have not drunk ", " मैं नशे में नहीं रहूंगा ");
        map.put("I  will have not driven ", " मैंने ड्राइव नहीं किया होगा ");
        map.put("I  will have not dropped ", " मैं नहीं गिराऊंगा ");
        map.put("I  will have not dried ", " मैं सूख नहीं पाऊंगा ");
        map.put("I  will have not eaten ", " मैंने नहीं खाया होगा ");
        map.put("I  will have not elected ", " मैं निर्वाचित नहीं होऊंगा ");
        map.put("I  will have not entered ", " मैंने प्रवेश नहीं किया होगा ");
        map.put("I  will have not fallen ", " मैं नहीं गिरूंगा ");
        map.put("I  will have not fed ", " मैंने खिलाया नहीं होगा ");
        map.put("I  will have not felt ", " मैंने महसूस नहीं किया होगा ");
        map.put("I  will have not fought ", " मैं नहीं लड़ा होता ");
        map.put("I  will have not found ", " मुझे नहीं मिला होगा ");
        map.put("I  will have not fled ", " मैं भाग नहीं जाऊंगा ");
        map.put("I  will have not flown ", " मैं उड़ नहीं जाऊंगा ");
        map.put("I  will have not forgotten ", " मैं नहीं भूलूंगा ");
        map.put("I  will have not fried ", " मैंने तला नहीं होगा ");
        map.put("I  will have not got ", " मुझे नहीं मिला होगा ");
        map.put("I  will have not given ", " मैंने नहीं दिया होगा ");
        map.put("I  will have not gone ", " मैं नहीं गया होता ");
        map.put("I  will have not grown ", " मैं नहीं उगाऊंगा ");
        map.put("I  will have not hanged ", " मैंने फांसी नहीं लगाई होगी ");
        map.put("I  will have not hung ", " मैंने लटका नहीं दिया होगा ");
        map.put("I  will have not heard ", " मैंने नहीं सुना होगा ");
        map.put("I  will have not helped ", " मैंने मदद नहीं की होगी ");
        map.put("I  will have not hidden ", " मैं छिप नहीं पाऊंगा ");
        map.put("I  will have not hit ", " मैं हिट नहीं करूंगा ");
        map.put("I  will have not held ", " मैंने आयोजित नहीं किया होगा ");
        map.put("I  will have not hoped ", " मुझे उम्मीद नहीं होगी ");
        map.put("I  will have not hurt ", " मुझे चोट नहीं लगी होगी ");
        map.put("I  will have not jumped ", " मैं कूद नहीं पाऊंगा ");
        map.put("I  will have not kept ", " मैंने नहीं रखा होगा ");
        map.put("I  will have not killed ", " मैं नहीं मारा होगा ");
        map.put("I  will have not known ", " मुझे पता नहीं होगा ");
        map.put("I  will have not laughed ", " मैं हँसा नहीं होता ");
        map.put("I  will have not led ", " मैंने नेतृत्व नहीं किया होगा ");
        map.put("I  will have not leapt ", " मैं छलांग नहीं लगाऊंगा ");
        map.put("I  will have not learnt ", " मैंने नहीं सीखा होगा ");
        map.put("I  will have not left ", " मैंने नहीं छोड़ा होगा ");
        map.put("I  will have not lent ", " मैंने उधार नहीं दिया होगा ");
        map.put("I  will have not lived ", " मैं नहीं रहूंगा ");
        map.put("I  will have not looked ", " मैंने नहीं देखा होगा ");
        map.put("I  will have not lost ", " मैं नहीं हारूंगा ");
        map.put("I  will have not loved ", " मैंने प्यार नहीं किया होगा ");
        map.put("I  will have not made ", " मैंने नहीं बनाया होगा ");
        map.put("I  will have not married ", " मैंने शादी नहीं की होगी ");
        map.put("I  will have not met ", " मैं नहीं मिला होता ");
        map.put("I  will have not mistaken ", " मैंने गलती नहीं की होगी ");
        map.put("I  will have not opened ", " मैंने नहीं खोला होगा ");
        map.put("I  will have not paid ", " मैंने भुगतान नहीं किया होगा ");
        map.put("I  will have not played ", " मैं नहीं खेलूंगा ");
        map.put("I  will have not put ", " मैंने नहीं रखा होगा ");
        map.put("I  will have not quarrelled ", " मैं झगड़ा नहीं करूंगा ");
        map.put("I  will have not rained ", " बारिश नहीं हुई होगी ");
        map.put("I  will have not reached ", " मैं नहीं पहुँचूँगा ");
        map.put("I  will have not read ", " मैंने पढ़ा नहीं होगा ");
        map.put("I  will have not remembered ", " मुझे याद नहीं होगा ");
        map.put("I  will have not ridden ", " मैंने सवारी नहीं की होगी ");
        map.put("I  will have not rung ", " मैंने रिंग नहीं की होगी ");
        map.put("I  will have not risen ", " मैं नहीं उठ जाऊंगा ");
        map.put("I  will have not run ", " मैं नहीं दौड़ूंगा ");
        map.put("I  will have not said ", " मैंने नहीं कहा होगा ");
        map.put("I  will have not seen ", " मैंने नहीं देखा होगा ");
        map.put("I  will have not sold ", " मैंने बेचा नहीं होगा ");
        map.put("I  will have not sent ", " मैंने नहीं भेजा होगा ");
        map.put("I  will have not shaken ", " मैं हिल नहीं जाऊंगा ");
        map.put("I  will have not shone ", " मैं चमक नहीं पाऊंगा ");
        map.put("I  will have not shot ", " मैंने गोली नहीं मारी होगी ");
        map.put("I  will have not shown ", " मैंने नहीं दिखाया होगा ");

        return map;
    }
    private static Map<String, String> Ten() {
        HashMap<String,String>map = new HashMap<>();
        map.put("I  will be not abusing ", " मैं गाली नहीं दूंगा ");
        map.put("I  will be not advising ", " मैं सलाह नहीं दूंगा ");
        map.put("I  will be not answering ", " मैं जवाब नहीं दूंगा ");
        map.put("I  will be not arising ", " मैं नहीं उठ रहा हूँ ");
        map.put("I  will be not arriving ", " मैं नहीं आऊंगा ");
        map.put("I  will be not asking ", " मैं नहीं पूछूंगा ");
        map.put("I  will be not awaking ", " मैं जाग नहीं रहा हूँ ");
        map.put("I  will be not bearing ", " मैं असर नहीं करूंगा ");
        map.put("I  will be not beating ", " मैं पिटाई नहीं करूंगा ");
        map.put("I  will be not becoming ", " मैं नहीं बन रहा हूँ ");
        map.put("I  will be not begging ", " मैं भीख नहीं माँगता हूँ ");
        map.put("I  will be not beginning ", " मैं शुरुआत नहीं करूंगा ");
        map.put("I  will be not binding ", " मैं बाध्यकारी नहीं रहूंगा ");
        map.put("I  will be not biting ", " मैं काट नहीं पाऊंगा ");
        map.put("I  will be not blessing ", " मैं आशीष नहीं रहूँगा ");
        map.put("I  will be not blowing ", " मैं नहीं उड़ूंगा ");
        map.put("I  will be not breaking ", " मैं नहीं टूटूंगा ");
        map.put("I  will be not bringing ", " मैं नहीं लाऊंगा ");
        map.put("I  will be not building ", " मैं निर्माण नहीं करूंगा ");
        map.put("I  will be not burning ", " मैं नहीं जलूंगा ");
        map.put("I  will be not buying ", " मैं नहीं खरीदूंगा ");
        map.put("I  will be not calling ", " मैं फोन नहीं करूंगा ");
        map.put("I  will be not carrying ", " मैं नहीं ले जाऊंगा ");
        map.put("I  will be not catching ", " मैं पकड़ नहीं पाऊंगा ");
        map.put("I  will be not cheating ", " मैं धोखा नहीं दूंगा ");
        map.put("I  will be not choosing ", " मैं नहीं चुनूंगा ");
        map.put("I  will be not cleaning ", " मैं सफाई नहीं करूंगा ");
        map.put("I  will be not climbing ", " मैं नहीं चलूंगा ");
        map.put("I  will be not closing ", " मैं बंद नहीं करूंगा ");
        map.put("I  will be not coming ", " मैं नहीं आऊंगा ");
        map.put("I  will be not cooking ", " मैं खाना नहीं बना रहा हूँ ");
        map.put("I  will be not creeping ", " मैं रेंग नहीं पाऊंगा ");
        map.put("I  will be not crying ", " मैं रो नहीं रहा हूँ ");
        map.put("I  will be not cutting ", " मैं नहीं काटूंगा ");
        map.put("I  will be not dancing ", " मैं नाचता नहीं रहूंगा ");
        map.put("I  will be not dealing ", " मैं काम नहीं करूंगा ");
        map.put("I  will be not dying ", " मैं मर नहीं जाऊंगा ");
        map.put("I  will be not digging ", " मैं खुदाई नहीं करूंगा ");
        map.put("I  will be not drawing ", " मैं ड्राइंग नहीं करूंगा ");
        map.put("I  will be not drinking ", " मैं नहीं पीऊंगा ");
        map.put("I  will be not driving ", " मैं गाड़ी नहीं चला रहा हूँ ");
        map.put("I  will be not dropping ", " मैं नहीं छोड़ूंगा ");
        map.put("I  will be not drying ", " मैं सूख नहीं रहा हूँ ");
        map.put("I  will be not eating ", " मैं नहीं खाऊंगा ");
        map.put("I  will be not electing ", " मैं चुनाव नहीं करूंगा ");
        map.put("I  will be not entering ", " मैं प्रवेश नहीं करूंगा ");
        map.put("I  will be not falling ", " मैं नहीं गिर रहा हूँ ");
        map.put("I  will be not feeding ", " मैं नहीं खिलाऊंगा ");
        map.put("I  will be not feeling ", " मैं महसूस नहीं करूंगा ");
        map.put("I  will be not fighting ", " मैं नहीं लड़ूंगा ");
        map.put("I  will be not finding ", " मुझे नहीं मिल रहा है ");
        map.put("I  will be not fleeing ", " मैं भाग नहीं जाऊंगा ");
        map.put("I  will be not flying ", " मैं नहीं उड़ूंगा ");
        map.put("I  will be not forgetting ", " मैं नहीं भूलूंगा ");
        map.put("I  will be not frying ", " मैं फ्राइंग नहीं करूंगा ");
        map.put("I  will be not getting ", " मुझे नहीं मिल रहा होगा ");
        map.put("I  will be not giving ", " मैं नहीं दे रहा हूँ ");
        map.put("I  will be not going ", " मैं नहीं जाऊंगा ");
        map.put("I  will be not growing ", " मैं नहीं बढ़ रहा हूँ ");
        map.put("I  will be not hanging ", " मैं लटका नहीं रहूंगा ");
        map.put("I  will be not hearing ", " मैं नहीं सुनूंगा ");
        map.put("I  will be not helping ", " मैं मदद नहीं करूंगा ");
        map.put("I  will be not hiding ", " मैं छिपाऊंगा नहीं ");
        map.put("I  will be not hitting ", " मैं नहीं मारूंगा ");
        map.put("I  will be not holding ", " मैं पकड़ नहीं पाऊंगा ");
        map.put("I  will be not hoping ", " मैं उम्मीद नहीं कर रहा हूँ ");
        map.put("I  will be not hurting ", " मैं चोट नहीं पहुँचाऊंगा ");
        map.put("I  will be not jumping ", " मैं कूद नहीं रहा हूँ ");
        map.put("I  will be not keeping ", " मैं नहीं रखूंगा ");
        map.put("I  will be not killing ", " मैं नहीं मारूंगा ");
        map.put("I  will be not knowing ", " मुझे पता नहीं होगा ");
        map.put("I  will be not laughing ", " मैं हँस नहीं रहा हूँ ");
        map.put("I  will be not leading ", " मैं अग्रणी नहीं रहूंगा ");
        map.put("I  will be not leaping ", " मैं छलांग नहीं लगाऊंगा ");
        map.put("I  will be not learning ", " मैं नहीं सीख रहा हूँ ");
        map.put("I  will be not leaving ", " मैं नहीं छोड़ूंगा ");
        map.put("I  will be not lending ", " मैं उधार नहीं दूंगा ");
        map.put("I  will be not living ", " मैं नहीं रहूंगा ");
        map.put("I  will be not looking ", " मैं नहीं देख रहा हूँ ");
        map.put("I  will be not losing ", " मैं हार नहीं पाऊंगा ");
        map.put("I  will be not loving ", " मैं प्यार नहीं करूंगा ");
        map.put("I  will be not making ", " मैं नहीं बना रहा हूँ ");
        map.put("I  will be not marrying ", " मैं शादी नहीं करूंगा ");
        map.put("I  will be not meeting ", " मैं नहीं मिल रहा हूँ ");
        map.put("I  will be not mistaking ", " मैं गलती नहीं करूंगा ");
        map.put("I  will be not opening ", " मैं नहीं खोलूंगा ");
        map.put("I  will be not paying ", " मैं भुगतान नहीं करूंगा ");
        map.put("I  will be not playing ", " मैं नहीं खेलूंगा ");
        map.put("I  will be not putting ", " मैं नहीं डालूंगा ");
        map.put("I  will be not quarrelling ", " मैं झगड़ा नहीं करूंगा ");
        map.put("I  will be not raining ", " बारिश नहीं होगी ");
        map.put("I  will be not reaching ", " मैं नहीं पहुँच रहा हूँ ");
        map.put("I  will be not reading ", " मैं नहीं पढ़ूंगा ");
        map.put("I  will be not remembering ", " मुझे याद नहीं होगा ");
        map.put("I  will be not riding ", " मैं सवारी नहीं करूंगा ");
        map.put("I  will be not ringing ", " मैं नहीं बज रहा हूँ ");
        map.put("I  will be not rising ", " मैं नहीं उठ रहा हूँ ");
        map.put("I  will be not running ", " मैं नहीं दौड़ूंगा ");
        map.put("I  will be not saying ", " मैं नहीं कहूंगा ");
        map.put("I  will be not seeing ", " मैं नहीं देख रहा हूँ ");
        map.put("I  will be not selling ", " मैं नहीं बेचूंगा ");
        map.put("I  will be not sending ", " मैं नहीं भेजूंगा ");
        map.put("I  will be not shaking ", " मैं हिल नहीं जाऊंगा ");
        map.put("I  will be not shining ", " मैं चमक नहीं रहा हूँ ");
        map.put("I  will be not shooting ", " मैं शूटिंग नहीं करूंगा ");
        map.put("I  will be not showing ", " मैं नहीं दिखाऊंगा ");
        map.put("I  will be not shutting ", " मैं बंद नहीं करूंगा ");

        return map;
    }
    private static Map<String, String> Nine() {
        HashMap<String,String>map = new HashMap<>();
        map.put("I  will not abuse ", " मैं गाली नहीं दूंगा ");
        map.put("I  will not advise", " मैं सलाह नहीं दूंगा");
        map.put("I  will not answer ", " मैं जवाब नहीं दूंगा ");
        map.put("I  will not arise ", " मैं नहीं उठूंगा ");
        map.put("I  will not arrive ", " मैं नहीं आऊंगा ");
        map.put("I  will not ask ", " मैं नहीं पूछूंगा ");
        map.put("I  will not awake ", " मैं जाग नहीं जाऊंगा ");

        map.put("I  will be not undefined", " मैं अपरिभाषित नहीं रहूंगा");
        map.put("I  will not bear ", " मैं सहन नहीं करूंगा ");
        map.put("I  will not beat ", " मैं हरा नहीं पाऊंगा ");
        map.put("I  will not become ", " मैं नहीं बनूंगा ");
        map.put("I  will not beg ", " मैं भीख नहीं माँगता ");
        map.put("I  will not begin ", " मैं शुरू नहीं करूंगा ");
        map.put("I  will not bind ", " मैं बाँध नहीं लूँगा ");
        map.put("I  will not bite", " मैं काटूंगा नहीं");
        map.put("I  will not bless", " मैं आशीष नहीं दूँगा");
        map.put("I  will not break ", " मैं नहीं टूटूंगा ");
        map.put("I  will not bring ", " मैं नहीं लाऊंगा ");
        map.put("I  will not build ", " मैं निर्माण नहीं करूंगा ");
        map.put("I  will not burn ", " मैं नहीं जलाऊंगा ");
        map.put("I  will not buy ", " मैं नहीं खरीदूंगा ");
        map.put("I  will not call ", " मैं फोन नहीं करूंगा ");
        map.put("I  will not carry ", " मैं नहीं ले जाऊंगा ");
        map.put("I  will not catch ", " मैं पकड़ नहीं पाऊंगा ");
        map.put("I  will not cheat ", " मैं धोखा नहीं दूँगा ");
        map.put("I  will not choose ", " मैं नहीं चुनूंगा ");
        map.put("I  will not clean ", " मैं साफ नहीं करूंगा ");
        map.put("I  will not climb  ", " मैं नहीं चलूंगा  ");
        map.put("I  will not close ", " मैं बंद नहीं करूंगा ");
        map.put("I  will not come ", " मैं नहीं आऊंगा ");
        map.put("I  will not cook ", " मैं खाना नहीं बनाऊंगा ");
        map.put("I  will not creep ", " मैं रेंगना नहीं करूंगा ");
        map.put("I  will not cry ", " मैं रोऊंगा नहीं ");
        map.put("I  will not cut ", " मैं नहीं काटूंगा ");
        map.put("I  will not dance ", " मैं डांस नहीं करूंगा ");
        map.put("I  will not deal ", " मैं सौदा नहीं करूंगा ");
        map.put("I  will not die ", " मैं नहीं मरूंगा ");
        map.put("I  will not dig ", " मैं खुदाई नहीं करूंगा ");
        map.put("I  will not draw ", " मैं ड्रॉ नहीं करूंगा ");
        map.put("I  will not drive ", " मैं ड्राइव नहीं करूंगा ");
        map.put("I  will not drop ", " मैं नहीं छोड़ूंगा ");
        map.put("I  will not dry ", " मैं सूख नहीं जाऊंगा ");
        map.put("I  will not eat ", " मैं नहीं खाऊंगा ");
        map.put("I  will not elect", " मैं चुनाव नहीं करूंगा");
        map.put("I  will not enter ", " मैं प्रवेश नहीं करूंगा ");
        map.put("I  will not fall ", " मैं नहीं गिरूंगा ");
        map.put("I  will not feed ", " मैं नहीं खिलाऊंगा ");
        map.put("I  will not feel  ", " मैं महसूस नहीं करूंगा  ");
        map.put("I  will not fight ", " मैं नहीं लड़ूंगा ");
        map.put("I  will not find ", " मुझे नहीं मिलेगा ");
        map.put("I  will not flee ", " मैं भाग नहीं जाऊंगा ");
        map.put("I  will not fly  ", " मैं नहीं उड़ूंगा  ");
        map.put("I  will not forget ", " मैं नहीं भूलूंगा ");
        map.put("I  will not fry ", " मैं फ्राई नहीं करूंगा ");
        map.put("I  will not get  ", " मुझे नहीं मिलेगा  ");
        map.put("I  will not give ", " मैं नहीं दूँगा ");
        map.put("I  will not go ", " मैं नहीं जाऊंगा ");
        map.put("I  will not grow", " मैं नहीं बढ़ूंगा");
        map.put("I  will not hang ", " मैं लटका नहीं जाऊंगा ");
        map.put("I  will not hear ", " मैं नहीं सुनूंगा ");
        map.put("I  will not help ", " मैं मदद नहीं करूंगा ");
        map.put("I  will not hide ", " मैं नहीं छिपाऊंगा ");
        map.put("I  will not hit ", " मैं नहीं मारूंगा ");
        map.put("I  will not hold ", " मैं पकड़ नहीं पाऊंगा ");
        map.put("I  will not hope ", " मैं उम्मीद नहीं करूंगा ");
        map.put("I  will not hurt ", " मैं चोट नहीं पहुँचाऊंगा ");
        map.put("I  will not jump ", " मैं कूद नहीं पाऊंगा ");
        map.put("I  will not keep ", " मैं नहीं रखूंगा ");
        map.put("I  will not kill ", " मैं नहीं मारूंगा ");
        map.put("I  will not know ", " मुझे पता नहीं चलेगा ");
        map.put("I  will not laugh ", " मैं हंसूंगा नहीं ");
        map.put("I  will not lead ", " मैं नेतृत्व नहीं करूंगा ");
        map.put("I  will not leap ", " मैं छलांग नहीं लगाऊंगा ");
        map.put("I  will not learn ", " मैं नहीं सीखूंगा ");
        map.put("I  will not leave ", " मैं नहीं छोड़ूँगा ");
        map.put("I  will not lend ", " मैं उधार नहीं दूंगा ");
        map.put("I  will not live ", " मैं नहीं रहूँगा ");
        map.put("I  will not look ", " मैं नहीं देखूंगा ");
        map.put("I  will not lose ", " मैं नहीं हारूंगा ");
        map.put("I  will not make ", " मैं नहीं बनाऊंगा ");
        map.put("I  will not marry ", " मैं शादी नहीं करूंगा ");
        map.put("I  will not meet ", " मैं नहीं मिलूंगा ");
        map.put("I  will not mistake ", " मैं गलती नहीं करूंगा ");
        map.put("I  will not open ", " मैं नहीं खुलूंगा ");
        map.put("I  will not pay  ", " मैं भुगतान नहीं करूंगा  ");
        map.put("I  will not play ", " मैं नहीं खेलूंगा ");
        map.put("I  will not put ", " मैं नहीं डालूंगा ");
        map.put("I  will not quarrel ", " मैं झगड़ा नहीं करूंगा ");
        map.put("I  will not rain ", " मैं बारिश नहीं करूँगा ");
        map.put("I  will not reach ", " मैं नहीं पहुँचूँगा ");
        map.put("I  will not read", " मैं नहीं पढ़ूंगा");
        map.put("I  will not remember  ", " मुझे याद नहीं होगा  ");
        map.put("I  will not ride ", " मैं सवारी नहीं करूंगा ");
        map.put("I  will not ring ", " मैं रिंग नहीं करूंगा ");
        map.put("I  will not rise  ", " मैं नहीं उठूंगा  ");
        map.put("I  will not run  ", " मैं नहीं दौड़ूंगा  ");
        map.put("I  will not say ", " मैं नहीं कहूंगा ");
        map.put("I  will not see ", " मैं नहीं देखूंगा ");
        map.put("I  will not sell ", " मैं नहीं बेचूंगा ");
        map.put("I  will not send ", " मैं नहीं भेजूंगा ");
        map.put("I  will not shake ", " मैं हिलाऊंगा नहीं ");
        map.put("I  will not shine ", " मैं चमक नहीं पाऊंगा ");
        map.put("I  will not shoot ", " मैं शूट नहीं करूंगा ");
        map.put("I  will not shut  ", " मैं बंद नहीं करूंगा  ");
        map.put("I  will not speak ", " मैं नहीं बोलूंगा ");
        map.put("I  will not swim ", " मैं तैर नहीं पाऊंगा ");
        map.put("I  will not teach ", " मैं नहीं सिखाऊंगा ");
        map.put("I  will not win ", " मैं नहीं जीतूंगा ");

        return map;
    }
    private static Map<String, String> Eight() {
        HashMap<String,String>map = new HashMap<>();
        map.put("I  had been  not abusing ", " मैं गाली नहीं दे रहा था ");
        map.put("I  had been  not advising ", " मैं सलाह नहीं दे रहा था ");
        map.put("I  had been  not answering ", " मैं जवाब नहीं दे रहा था ");
        map.put("I  had been  not arising ", " मैं नहीं उठ रहा था ");
        map.put("I  had been  not arriving ", " मैं नहीं आ रहा था ");
        map.put("I  had been  not asking ", " मैं नहीं पूछ रहा था ");
        map.put("I  had been  not awaking ", " मैं जाग नहीं रहा था ");
        map.put("I  had been  not undefined", " मैं अपरिभाषित नहीं था");
        map.put("I  had been  not bearing ", " मैं असर नहीं कर रहा था ");
        map.put("I  had been  not beating ", " मैं पिटाई नहीं कर रहा था ");
        map.put("I  had been  not becoming ", " मैं नहीं बन रहा था ");
        map.put("I  had been  not begging ", " मैं भीख नहीं मांग रहा था ");
        map.put("I  had been  not beginning ", " मैं शुरुआत नहीं कर रहा था ");
        map.put("I  had been  not binding ", " मैं बाध्यकारी नहीं था ");
        map.put("I  had been  not biting ", " मैं काट नहीं रहा था ");
        map.put("I  had been  not blessing ", " मैं आशीर्वाद नहीं दे रहा था ");
        map.put("I  had been  not blowing ", " मैं उड़ नहीं रहा था ");
        map.put("I  had been  not breaking ", " मैं नहीं तोड़ रहा था ");
        map.put("I  had been  not bringing ", " मैं नहीं ला रहा था ");
        map.put("I  had been  not building ", " मैं निर्माण नहीं कर रहा था ");
        map.put("I  had been  not burning ", " मैं जल नहीं रहा था ");
        map.put("I  had been  not buying ", " मैं खरीद नहीं रहा था ");
        map.put("I  had been  not calling ", " मैं फोन नहीं कर रहा था ");
        map.put("I  had been  not carrying ", " मैं नहीं ले जा रहा था ");
        map.put("I  had been  not catching ", " मैं पकड़ नहीं रहा था ");
        map.put("I  had been  not cheating ", " मैं धोखा नहीं दे रहा था ");
        map.put("I  had been  not choosing ", " मैं नहीं चुन रहा था ");
        map.put("I  had been  not cleaning ", " मैं सफाई नहीं कर रहा था ");
        map.put("I  had been  not climbing ", " मैं चढ़ नहीं रहा था ");
        map.put("I  had been  not closing ", " मैं बंद नहीं हो रहा था ");
        map.put("I  had been  not coming ", " मैं नहीं आ रहा था ");
        map.put("I  had been  not cooking ", " मैं खाना नहीं बना रहा था ");
        map.put("I  had been  not creeping ", " मैं रेंग नहीं रहा था ");
        map.put("I  had been  not crying ", " मैं रो नहीं रहा था ");
        map.put("I  had been  not cutting ", " मैं काट नहीं रहा था ");
        map.put("I  had been  not dancing ", " मैं नाच नहीं रहा था ");
        map.put("I  had been  not dealing ", " मैं काम नहीं कर रहा था ");
        map.put("I  had been  not dying ", " मैं मर नहीं रहा था ");
        map.put("I  had been  not digging ", " मैं खुदाई नहीं कर रहा था ");
        map.put("I  had been  not drawing ", " मैं ड्राइंग नहीं कर रहा था ");
        map.put("I  had been  not drinking ", " मैं शराब नहीं पी रहा था ");
        map.put("I  had been  not driving ", " मैं गाड़ी नहीं चला रहा था ");
        map.put("I  had been  not dropping ", " मैं नहीं गिर रहा था ");
        map.put("I  had been  not drying ", " मैं सूख नहीं रहा था ");
        map.put("I  had been  not eating ", " मैं नहीं खा रहा था ");
        map.put("I  had been  not electing ", " मैं चुनाव नहीं कर रहा था ");
        map.put("I  had been  not entering ", " मैं प्रवेश नहीं कर रहा था ");
        map.put("I  had been  not falling ", " मैं गिर नहीं रहा था ");
        map.put("I  had been  not feeding ", " मैं खिला नहीं रहा था ");
        map.put("I  had been  not feeling ", " मैं महसूस नहीं कर रहा था ");
        map.put("I  had been  not fighting ", " मैं लड़ नहीं रहा था ");
        map.put("I  had been  not finding ", " मुझे नहीं मिल रहा था ");
        map.put("I  had been  not fleeing ", " मैं भाग नहीं रहा था ");
        map.put("I  had been  not flying ", " मैं उड़ नहीं रहा था ");
        map.put("I  had been  not forgetting ", " मैं भूल नहीं रहा था ");
        map.put("I  had been  not frying ", " मैं फ्राइंग नहीं कर रहा था ");
        map.put("I  had been  not getting ", " मुझे नहीं मिल रहा था ");
        map.put("I  had been  not giving ", " मैं नहीं दे रहा था ");
        map.put("I  had been  not going ", " मैं नहीं जा रहा था ");
        map.put("I  had been  not growing ", " मैं नहीं बढ़ रहा था ");
        map.put("I  had been  not hanging ", " मैं लटक नहीं रहा था ");
        map.put("I  had been  not hearing ", " मैं सुन नहीं रहा था ");
        map.put("I  had been  not helping ", " मैं मदद नहीं कर रहा था ");
        map.put("I  had been  not hiding ", " मैं छिपा नहीं रहा था ");
        map.put("I  had been  not hitting ", " मैं नहीं मार रहा था ");
        map.put("I  had been  not holding ", " मैं पकड़ नहीं रहा था ");
        map.put("I  had been  not hoping ", " मैं उम्मीद नहीं कर रहा था ");
        map.put("I  had been  not hurting ", " मैं चोट नहीं पहुंचा रहा था ");
        map.put("I  had been  not jumping ", " मैं कूद नहीं रहा था ");
        map.put("I  had been  not keeping ", " मैं नहीं रख रहा था ");
        map.put("I  had been  not killing ", " मैं नहीं मार रहा था ");
        map.put("I  had been  not knowing ", " मैं नहीं जानता था ");
        map.put("I  had been  not laughing ", " मैं हँस नहीं रहा था ");
        map.put("I  had been  not leading ", " मैं अगुवाई नहीं कर रहा था ");
        map.put("I  had been  not leaping ", " मैं छलांग नहीं लगा रहा था ");
        map.put("I  had been  not learning ", " मैं नहीं सीख रहा था ");
        map.put("I  had been  not leaving ", " मैं नहीं जा रहा था ");
        map.put("I  had been  not lending ", " मैं उधार नहीं दे रहा था ");
        map.put("I  had been  not living ", " मैं नहीं रह रहा था ");
        map.put("I  had been  not looking ", " मैं नहीं देख रहा था ");
        map.put("I  had been  not losing ", " मैं हार नहीं रहा था ");
        map.put("I  had been  not loving ", " मैं प्यार नहीं कर रहा था ");
        map.put("I  had been  not making ", " मैं नहीं बना रहा था ");
        map.put("I  had been  not marrying ", " मैं शादी नहीं कर रहा था ");
        map.put("I  had been  not meeting ", " मैं मुलाकात नहीं कर रहा था ");
        map.put("I  had been  not mistaking ", " मैं गलती नहीं कर रहा था ");
        map.put("I  had been  not opening ", " मैं नहीं खोल रहा था ");
        map.put("I  had been  not paying ", " मैं भुगतान नहीं कर रहा था ");
        map.put("I  had been  not playing ", " मैं नहीं खेल रहा था ");
        map.put("I  had been  not putting ", " मैं नहीं डाल रहा था ");
        map.put("I  had been  not quarrelling ", " मैं झगड़ा नहीं कर रहा था ");
        map.put("I  had been  not raining ", " मैं बारिश नहीं कर रहा था ");
        map.put("I  had been  not reaching ", " मैं नहीं पहुँच रहा था ");
        map.put("I  had been  not reading ", " मैं नहीं पढ़ रहा था ");
        map.put("I  had been  not remembering ", " मुझे याद नहीं था ");
        map.put("I  had been  not riding ", " मैं सवारी नहीं कर रहा था ");
        map.put("I  had been  not ringing ", " मैं नहीं बज रहा था ");
        map.put("I  had been  not rising ", " मैं उठ नहीं रहा था ");
        map.put("I  had been  not running ", " मैं दौड़ नहीं रहा था ");
        map.put("I  had been  not saying ", " मैं यह नहीं कह रहा था ");
        map.put("I  had been  not seeing ", " मैं नहीं देख रहा था ");
        map.put("I  had been  not selling ", " मैं नहीं बेच रहा था ");
        map.put("I  had been  not sending ", " मैं नहीं भेज रहा था ");
        map.put("I  had been  not shaking ", " मैं हिल नहीं रहा था ");
        map.put("I  had been  not shining ", " मैं चमक नहीं रहा था ");
        map.put("I  had been  not shooting ", " मैं शूटिंग नहीं कर रहा था ");
        map.put("I  had been  not showing ", " मैं नहीं दिखा रहा था ");
        map.put("I  had been  not shutting ", " मैं बंद नहीं कर रहा था ");
        map.put("I  had been  not taking ", " मैं नहीं ले रहा था ");
        map.put("I  had been  not teaching ", " मैं पढ़ा नहीं रहा था ");

        return map;
    }
    private static Map<String, String> Seven() {
        HashMap<String,String>map = new HashMap<>();
        map.put("I  had  not abused ", " मैंने गाली नहीं दी थी ");
        map.put("I  had  not advised ", " मैंने सलाह नहीं दी थी ");
        map.put("I  had  not answered ", " मैंने जवाब नहीं दिया था ");
        map.put("I  had  not arisen ", " मैं पैदा नहीं हुआ था ");
        map.put("I  had  not arrived ", " मैं नहीं आया था ");
        map.put("I  had  not asked ", " मैंने नहीं पूछा था ");
        map.put("I  had  not awoken ", " मैं जाग नहीं पाया था ");
        map.put("I  had  not undefined", " मैंने अपरिभाषित नहीं किया था");
        map.put("I  had  not borne ", " मैंने जन्म नहीं लिया था ");
        map.put("I  had  not beaten ", " मैंने पीटा नहीं था ");
        map.put("I  had  not become ", " मैं नहीं बन पाया था ");
        map.put("I  had  not begged ", " मैंने भीख नहीं मांगी थी ");
        map.put("I  had  not begun ", " मैंने शुरू नहीं किया था ");
        map.put("I  had  not bound ", " मैंने बाउंड नहीं किया था ");
        map.put("I  had  not bitten ", " मैंने काट नहीं लिया था ");
        map.put("I  had  not blessed ", " मैंने आशीष नहीं दी थी ");
        map.put("I  had  not broken ", " मैं नहीं टूटा था ");
        map.put("I  had  not blown ", " मैंने नहीं उड़ाया था ");
        map.put("I  had  not brought ", " मैं नहीं लाया था ");
        map.put("I  had  not built ", " मैंने नहीं बनाया था ");
        map.put("I  had  not burnt ", " मैंने जलाया नहीं था ");
        map.put("I  had  not bought ", " मैंने नहीं खरीदा था ");
        map.put("I  had  not called ", " मैंने फोन नहीं किया था ");
        map.put("I  had  not carried ", " मैंने नहीं किया था ");
        map.put("I  had  not caught ", " मैंने पकड़ा नहीं था ");
        map.put("I  had  not cheated ", " मैंने धोखा नहीं दिया था ");
        map.put("I  had  not chosen ", " मैंने नहीं चुना था ");
        map.put("I  had  not cleaned ", " मैंने साफ नहीं किया था ");
        map.put("I  had  not climbed ", " मैं चढ़ नहीं पाया था ");
        map.put("I  had  not closed ", " मैंने बंद नहीं किया था ");
        map.put("I  had  not come ", " मैं नहीं आया था ");
        map.put("I  had  not cooked ", " मैंने खाना नहीं बनाया था ");
        map.put("I  had  not crept ", " मैंने क्रेप नहीं किया था ");
        map.put("I  had  not cried ", " मैं रोया नहीं था ");
        map.put("I  had  not cut ", " मैंने नहीं काटा था ");
        map.put("I  had  not danced ", " मैंने नृत्य नहीं किया था ");
        map.put("I  had  not dealt ", " मैंने निपटा नहीं था ");
        map.put("I  had  not died ", " मैं नहीं मरा था ");
        map.put("I  had  not dug ", " मैंने खोदा नहीं था ");
        map.put("I  had  not drawn ", " मैंने ड्रॉ नहीं किया था ");
        map.put("I  had  not drunk ", " मैंने शराब नहीं पी थी ");
        map.put("I  had  not driven ", " मैंने ड्राइव नहीं किया था ");
        map.put("I  had  not dropped ", " मैंने नहीं गिराया था ");
        map.put("I  had  not dried ", " मैं सूख नहीं गया था ");
        map.put("I  had  not eaten ", " मैंने नहीं खाया था ");
        map.put("I  had  not elected ", " मैं निर्वाचित नहीं हुआ था ");
        map.put("I  had  not entered ", " मैंने प्रवेश नहीं किया था ");
        map.put("I  had  not fallen ", " मैं नहीं गिरा था ");
        map.put("I  had  not fed ", " मैंने नहीं खिलाया था ");
        map.put("I  had  not felt ", " मैंने महसूस नहीं किया था ");
        map.put("I  had  not fought ", " मैंने लड़ाई नहीं की थी ");
        map.put("I  had  not found ", " मुझे नहीं मिला था ");
        map.put("I  had  not fled ", " मैं भाग नहीं गया था ");
        map.put("I  had  not flown ", " मैं उड़ नहीं गया था ");
        map.put("I  had  not forgotten ", " मैं नहीं भूला था ");
        map.put("I  had  not fried ", " मैंने तला नहीं था ");
        map.put("I  had  not got ", " मुझे नहीं मिला था ");
        map.put("I  had  not given ", " मैंने नहीं दिया था ");
        map.put("I  had  not gone ", " मैं नहीं गया था ");
        map.put("I  had  not grown ", " मैं बड़ा नहीं हुआ था ");
        map.put("I  had  not hanged ", " मैंने फांसी नहीं लगाई थी ");
        map.put("I  had  not hung ", " मैंने लटका नहीं दिया था ");
        map.put("I  had  not heard ", " मैंने नहीं सुना था ");
        map.put("I  had  not helped ", " मैंने मदद नहीं की थी ");
        map.put("I  had  not hidden ", " मैंने छिपाया नहीं था ");
        map.put("I  had  not hit ", " मैंने नहीं मारा था ");
        map.put("I  had  not held ", " मैंने आयोजित नहीं किया था ");
        map.put("I  had  not hoped ", " मुझे उम्मीद नहीं थी ");
        map.put("I  had  not hurt ", " मुझे चोट नहीं पहुंची थी ");
        map.put("I  had  not jumped ", " मैं कूद नहीं पाया था ");
        map.put("I  had  not kept ", " मैंने नहीं रखा था ");
        map.put("I  had  not killed ", " मैंने नहीं मारा था ");
        map.put("I  had  not known ", " मुझे पता नहीं था ");
        map.put("I  had  not laughed ", " मैं हँसा नहीं था ");
        map.put("I  had  not led ", " मैंने नेतृत्व नहीं किया था ");
        map.put("I  had  not leapt ", " मैंने छलांग नहीं लगाई थी ");
        map.put("I  had  not learnt ", " मैंने नहीं सीखा था ");
        map.put("I  had  not left ", " मैंने नहीं छोड़ा था ");
        map.put("I  had  not lent ", " मैंने उधार नहीं दिया था ");
        map.put("I  had  not lived ", " मैं नहीं रहता था ");
        map.put("I  had  not looked ", " मैंने नहीं देखा था ");
        map.put("I  had  not lost ", " मैं नहीं हारा था ");
        map.put("I  had  not loved ", " मैंने प्यार नहीं किया था ");
        map.put("I  had  not made ", " मैंने नहीं बनाया था ");
        map.put("I  had  not married ", " मैंने शादी नहीं की थी ");
        map.put("I  had  not met ", " मैं नहीं मिला था ");
        map.put("I  had  not mistaken ", " मैंने गलती नहीं की थी ");
        map.put("I  had  not opened ", " मैंने नहीं खोला था ");
        map.put("I  had  not paid ", " मैंने भुगतान नहीं किया था ");
        map.put("I  had  not played ", " मैंने नहीं खेला था ");
        map.put("I  had  not put ", " मैंने नहीं रखा था ");
        map.put("I  had  not quarrelled ", " मैंने झगड़ा नहीं किया था ");
        map.put("I  had  not rained ", " मैंने बारिश नहीं की थी ");
        map.put("I  had  not reached ", " मैं नहीं पहुँचा था ");
        map.put("I  had  not read ", " मैंने पढ़ा नहीं था ");
        map.put("I  had  not remembered ", " मुझे याद नहीं था ");
        map.put("I  had  not ridden ", " मैंने सवारी नहीं की थी ");
        map.put("I  had  not rung ", " मैंने नहीं बजाया था ");
        map.put("I  had  not risen ", " मैं नहीं उठ पाया था ");
        map.put("I  had  not run ", " मैं भाग नहीं पाया था ");
        map.put("I  had  not said ", " मैंने नहीं कहा था ");
        map.put("I  had  not seen ", " मैंने नहीं देखा था ");
        map.put("I  had  not sold ", " मैंने बेचा नहीं था ");
        map.put("I  had  not sent ", " मैंने नहीं भेजा था ");
        map.put("I  had  not shaken ", " मैं हिल नहीं गया था ");
        map.put("I  had  not shone ", " मैं चमक नहीं पाया था ");
        map.put("I  had  not shot ", " मैंने गोली नहीं मारी थी ");
        map.put("I  had  not shown ", " मैंने नहीं दिखाया था ");
        map.put("I  had  not shut ", " मैंने बंद नहीं किया था ");

        return map;
    }
    private static Map<String, String> Six() {
        HashMap<String,String>map = new HashMap<>();
        map.put("I  was  not abusing ", " मैं गाली नहीं दे रहा था ");
        map.put("I  was  not advising ", " मैं सलाह नहीं दे रहा था ");
        map.put("I  was  not answering ", " मैं जवाब नहीं दे रहा था ");
        map.put("I  was  not arising ", " मैं नहीं उठ रहा था ");
        map.put("I  was  not arriving ", " मैं नहीं आ रहा था ");
        map.put("I  was  not asking ", " मैं नहीं पूछ रहा था ");
        map.put("I  was  not awaking ", " मैं जाग नहीं रहा था ");
        map.put("I  was  not undefined", " मैं अपरिभाषित नहीं था");
        map.put("I  was  not bearing ", " मैं असर नहीं कर रहा था ");
        map.put("I  was  not beating ", " मैं पिटाई नहीं कर रहा था ");
        map.put("I  was  not becoming ", " मैं नहीं बन रहा था ");
        map.put("I  was  not begging ", " मैं भीख नहीं मांग रहा था ");
        map.put("I  was  not beginning ", " मैं शुरुआत नहीं कर रहा था ");
        map.put("I  was  not binding ", " मैं बाध्यकारी नहीं था ");
        map.put("I  was  not biting ", " मैं काट नहीं रहा था ");
        map.put("I  was  not blessing ", " मैं आशीष नहीं था ");
        map.put("I  was  not blowing ", " मैं उड़ नहीं रहा था ");
        map.put("I  was  not breaking ", " मैं नहीं तोड़ रहा था ");
        map.put("I  was  not bringing ", " मैं नहीं ला रहा था ");
        map.put("I  was  not building ", " मैं निर्माण नहीं कर रहा था ");
        map.put("I  was  not burning ", " मैं जल नहीं रहा था ");
        map.put("I  was  not buying ", " मैं नहीं खरीद रहा था ");
        map.put("I  was  not calling ", " मैं फोन नहीं कर रहा था ");
        map.put("I  was  not carrying ", " मैं नहीं ले जा रहा था ");
        map.put("I  was  not catching ", " मैं पकड़ नहीं रहा था ");
        map.put("I  was  not cheating ", " मैं धोखा नहीं दे रहा था ");
        map.put("I  was  not choosing ", " मैं नहीं चुन रहा था ");
        map.put("I  was  not cleaning ", " मैं सफाई नहीं कर रहा था ");
        map.put("I  was  not climbing ", " मैं चढ़ नहीं रहा था ");
        map.put("I  was  not closing ", " मैं बंद नहीं हो रहा था ");
        map.put("I  was  not coming ", " मैं नहीं आ रहा था ");
        map.put("I  was  not cooking ", " मैं खाना नहीं बना रहा था ");
        map.put("I  was  not creeping ", " मैं रेंग नहीं रहा था ");
        map.put("I  was  not crying ", " मैं रो नहीं रहा था ");
        map.put("I  was  not cutting ", " मैं काट नहीं रहा था ");
        map.put("I  was  not dancing ", " मैं नाच नहीं रहा था ");
        map.put("I  was  not dealing ", " मैं काम नहीं कर रहा था ");
        map.put("I  was  not dying ", " मैं मर नहीं रहा था ");
        map.put("I  was  not digging ", " मैं खुदाई नहीं कर रहा था ");
        map.put("I  was  not drawing ", " मैं ड्राइंग नहीं कर रहा था ");
        map.put("I  was  not drinking ", " मैं नहीं पी रहा था ");
        map.put("I  was  not driving ", " मैं गाड़ी नहीं चला रहा था ");
        map.put("I  was  not dropping ", " मैं नहीं गिर रहा था ");
        map.put("I  was  not drying ", " मैं सूख नहीं रहा था ");
        map.put("I  was  not eating ", " मैं नहीं खा रहा था ");
        map.put("I  was  not electing ", " मैं चुनाव नहीं कर रहा था ");
        map.put("I  was  not entering ", " मैं प्रवेश नहीं कर रहा था ");
        map.put("I  was  not falling ", " मैं गिर नहीं रहा था ");
        map.put("I  was  not feeding ", " मैं खिला नहीं रहा था ");
        map.put("I  was  not feeling ", " मैं महसूस नहीं कर रहा था ");
        map.put("I  was  not fighting ", " मैं लड़ नहीं रहा था ");
        map.put("I  was  not finding ", " मुझे नहीं मिल रहा था ");
        map.put("I  was  not fleeing ", " मैं भाग नहीं रहा था ");
        map.put("I  was  not flying ", " मैं उड़ नहीं रहा था ");
        map.put("I  was  not forgetting ", " मैं भूल नहीं रहा था ");
        map.put("I  was  not frying ", " मैं तलने वाला नहीं था ");
        map.put("I  was  not getting ", " मुझे नहीं मिल रहा था ");
        map.put("I  was  not giving ", " मैं नहीं दे रहा था ");
        map.put("I  was  not going ", " मैं नहीं जा रहा था ");
        map.put("I  was  not growing ", " मैं नहीं बढ़ रहा था ");
        map.put("I  was  not hanging ", " मैं लटक नहीं रहा था ");
        map.put("I  was  not hearing ", " मैं सुन नहीं रहा था ");
        map.put("I  was  not helping ", " मैं मदद नहीं कर रहा था ");
        map.put("I  was  not hiding ", " मैं छिपा नहीं रहा था ");
        map.put("I  was  not hitting ", " मैं नहीं मार रहा था ");
        map.put("I  was  not holding ", " मैं पकड़ नहीं रहा था ");
        map.put("I  was  not hoping ", " मैं उम्मीद नहीं कर रहा था ");
        map.put("I  was  not hurting ", " मैं चोट नहीं पहुंचा रहा था ");
        map.put("I  was  not jumping ", " मैं कूद नहीं रहा था ");
        map.put("I  was  not keeping ", " मैं नहीं रख रहा था ");
        map.put("I  was  not killing ", " मैं नहीं मार रहा था ");
        map.put("I  was  not knowing ", " मुझे पता नहीं था ");
        map.put("I  was  not laughing ", " मैं हँस नहीं रहा था ");
        map.put("I  was  not leading ", " मैं अग्रणी नहीं था ");
        map.put("I  was  not leaping ", " मैं छलांग नहीं लगा रहा था ");
        map.put("I  was  not learning ", " मैं नहीं सीख रहा था ");
        map.put("I  was  not leaving ", " मैं नहीं जा रहा था ");
        map.put("I  was  not lending ", " मैं उधार नहीं दे रहा था ");
        map.put("I  was  not living ", " मैं नहीं रह रहा था ");
        map.put("I  was  not looking ", " मैं नहीं देख रहा था ");
        map.put("I  was  not losing ", " मैं हार नहीं रहा था ");
        map.put("I  was  not loving ", " मैं प्यार नहीं कर रहा था ");
        map.put("I  was  not making ", " मैं नहीं बना रहा था ");
        map.put("I  was  not marrying ", " मैं शादी नहीं कर रहा था ");
        map.put("I  was  not meeting ", " मैं नहीं मिल रहा था ");
        map.put("I  was  not mistaking ", " मैं गलती नहीं कर रहा था ");
        map.put("I  was  not opening ", " मैं नहीं खोल रहा था ");
        map.put("I  was  not paying ", " मैं भुगतान नहीं कर रहा था ");
        map.put("I  was  not playing ", " मैं नहीं खेल रहा था ");
        map.put("I  was  not putting ", " मैं नहीं डाल रहा था ");
        map.put("I  was  not quarrelling ", " मैं झगड़ा नहीं कर रहा था ");
        map.put("I  was  not raining ", " बारिश नहीं हो रही थी ");
        map.put("I  was  not reaching ", " मैं नहीं पहुँच रहा था ");
        map.put("I  was  not reading ", " मैं नहीं पढ़ रहा था ");
        map.put("I  was  not remembering ", " मुझे याद नहीं था ");
        map.put("I  was  not riding ", " मैं सवारी नहीं कर रहा था ");
        map.put("I  was  not ringing ", " मैं नहीं बज रहा था ");
        map.put("I  was  not rising ", " मैं उठ नहीं रहा था ");
        map.put("I  was  not running ", " मैं भाग नहीं रहा था ");
        map.put("I  was  not saying ", " मैं नहीं कह रहा था ");
        map.put("I  was  not seeing ", " मैं नहीं देख रहा था ");
        map.put("I  was  not selling ", " मैं नहीं बेच रहा था ");
        map.put("I  was  not sending ", " मैं नहीं भेज रहा था ");
        map.put("I  was  not shaking ", " मैं हिल नहीं रहा था ");
        map.put("I  was  not shining ", " मैं चमक नहीं रहा था ");
        map.put("I  was  not shooting ", " मैं शूटिंग नहीं कर रहा था ");
        map.put("I  was  not showing ", " मैं नहीं दिखा रहा था ");
        map.put("I  was  not shutting ", " मैं बंद नहीं कर रहा था ");
        map.put("I  was  not writing ", " मैं नहीं लिख रहा था ");
        map.put("I  did  not wash ", " मैंने नहीं धोया ");

        return map;
    }
    private static Map<String, String> Five() {
        HashMap<String,String>map = new HashMap<>();
        map.put("I  did  not abuse ", " मैंने गाली नहीं दी ");
        map.put("I  did  not advise", " मैंने सलाह नहीं दी");
        map.put("I  did  not answer ", " मैंने जवाब नहीं दिया ");
        map.put("I  did  not arise ", " मैं नहीं उठ पाया ");
        map.put("I  did  not arrive ", " मैं नहीं आया ");
        map.put("I  did  not ask ", " मैंने नहीं पूछा ");
        map.put("I  did  not awake ", " मैं जाग नहीं पाया ");
        map.put("I  did  not beat ", " मैंने हराया नहीं ");
        map.put("I  did  not become ", " मैं नहीं बन पाया ");
        map.put("I  did  not beg ", " मैंने भीख नहीं मांगी ");
        map.put("I  did  not begin ", " मैंने शुरू नहीं किया ");
        map.put("I  did  not bind ", " मैंने बाँध नहीं किया ");
        map.put("I  did  not bite", " मैंने काट नहीं लिया");
        map.put("I  did  not bless", " मैंने आशीर्वाद नहीं दिया");
        map.put("I  did  not blow ", " मैंने नहीं उड़ाया ");
        map.put("I  did  not break ", " मैं नहीं टूटा ");
        map.put("I  did  not bring ", " मैं नहीं लाया ");
        map.put("I  did  not build ", " मैंने निर्माण नहीं किया ");
        map.put("I  did  not burn ", " मैंने जलाया नहीं ");
        map.put("I  did  not buy ", " मैंने नहीं खरीदा ");
        map.put("I  did  not call ", " मैंने फोन नहीं किया ");
        map.put("I  did  not carry ", " मैं नहीं ले गया ");
        map.put("I  did  not catch ", " मैंने पकड़ नहीं लिया ");
        map.put("I  did  not cheat ", " मैंने धोखा नहीं दिया ");
        map.put("I  did  not choose ", " मैंने नहीं चुना ");
        map.put("I  did  not clean ", " मैंने साफ नहीं किया ");
        map.put("I  did  not climb  ", " मैं नहीं चढ़ पाया  ");
        map.put("I  did  not close ", " मैंने बंद नहीं किया ");
        map.put("I  did  not come ", " मैं नहीं आया ");
        map.put("I  did  not cook ", " मैंने खाना नहीं बनाया ");
        map.put("I  did  not creep ", " मैं रेंगना नहीं था ");
        map.put("I  did  not cut ", " मैंने कटौती नहीं की ");
        map.put("I  did  not dance ", " मैंने नृत्य नहीं किया ");
        map.put("I  did  not deal ", " मैंने सौदा नहीं किया ");
        map.put("I  did  not die ", " मैं नहीं मरा ");
        map.put("I  did  not dig ", " मैंने खोदा नहीं ");
        map.put("I  did  not draw ", " मैंने ड्रॉ नहीं किया ");
        map.put("I  did  not drive ", " मैंने ड्राइव नहीं किया ");
        map.put("I  did  not drop ", " मैं नहीं गिरा ");
        map.put("I  did  not dry ", " मैं सूखा नहीं था ");
        map.put("I  did  not eat ", " मैंने नहीं खाया ");
        map.put("I  did  not elect", " मैंने चुनाव नहीं किया");
        map.put("I  did  not enter ", " मैंने प्रवेश नहीं किया ");
        map.put("I  did  not fall ", " मैं नहीं गिरा ");
        map.put("I  did  not feed ", " मैंने खाना नहीं खाया ");
        map.put("I  did  not feel  ", " मुझे महसूस नहीं हुआ  ");
        map.put("I  did  not fight ", " मैंने लड़ाई नहीं की ");
        map.put("I  did  not find ", " मुझे नहीं मिला ");
        map.put("I  did  not flee ", " मैं भाग नहीं गया ");
        map.put("I  did  not fly  ", " मैं उड़ नहीं पाया  ");
        map.put("I  did  not fry ", " मैंने फ्राई नहीं किया ");
        map.put("I  did  not get  ", " मुझे नहीं मिला  ");
        map.put("I  did  not give ", " मैंने नहीं दिया ");
        map.put("I  did  not go ", " मैं नहीं गया ");
        map.put("I  did  not grow", " मैं विकसित नहीं हुआ");
        map.put("I  did  not hang ", " मैं लटका नहीं था ");
        map.put("I  did  not hear ", " मैंने नहीं सुना ");
        map.put("I  did  not help ", " मैंने मदद नहीं की ");
        map.put("I  did  not hide ", " मैंने छिपाया नहीं ");
        map.put("I  did  not hit ", " मैंने नहीं मारा ");
        map.put("I  did  not hold ", " मैंने पकड़ नहीं लिया ");
        map.put("I  did  not hope ", " मुझे उम्मीद नहीं थी ");
        map.put("I  did  not hurt ", " मैंने चोट नहीं पहुंचाई ");
        map.put("I  did  not jump ", " मैं कूद नहीं पाया ");
        map.put("I  did  not keep ", " मैंने नहीं रखा ");
        map.put("I  did  not kill ", " मैंने नहीं मारा ");
        map.put("I  did  not know ", " मुझे नहीं पता था ");
        map.put("I  did  not laugh ", " मैं हँसा नहीं ");
        map.put("I  did  not lead ", " मैंने नेतृत्व नहीं किया ");
        map.put("I  did  not leap ", " मैंने छलांग नहीं लगाई ");
        map.put("I  did  not learn ", " मैंने नहीं सीखा ");
        map.put("I  did  not leave ", " मैंने नहीं छोड़ा ");
        map.put("I  did  not live ", " मैं नहीं जीता ");
        map.put("I  did  not look ", " मैंने नहीं देखा ");
        map.put("I  did  not lose ", " मैं नहीं हारा ");
        map.put("I  did  not love ", " मुझे प्यार नहीं था ");
        map.put("I  did  not make ", " मैंने नहीं बनाया ");
        map.put("I  did  not marry ", " मैंने शादी नहीं की ");
        map.put("I  did  not meet ", " मैं नहीं मिला ");
        map.put("I  did  not mistake ", " मैंने गलती नहीं की ");
        map.put("I  did  not open ", " मैंने नहीं खोला ");
        map.put("I  did  not pay  ", " मैंने भुगतान नहीं किया  ");
        map.put("I  did  not play ", " मैंने नहीं खेला ");
        map.put("I  did  not put ", " मैंने नहीं डाला ");
        map.put("I  did  not quarrel ", " मैंने झगड़ा नहीं किया ");
        map.put("I  did  not rain ", " मैंने बारिश नहीं की ");
        map.put("I  did  not reach ", " मैं नहीं पहुँचा ");
        map.put("I  did  not read", " मैंने पढ़ा नहीं");
        map.put("I  did  not remember  ", " मुझे याद नहीं था  ");
        map.put("I  did  not ride ", " मैंने सवारी नहीं की ");
        map.put("I  did  not ring ", " मैंने रिंग नहीं की ");
        map.put("I  did  not rise  ", " मैं नहीं उठ पाया  ");
        map.put("I  did  not say ", " मैंने नहीं कहा ");
        map.put("I  did  not see ", " मैंने नहीं देखा ");
        map.put("I  did  not sell ", " मैंने नहीं बेचा ");
        map.put("I  did  not send ", " मैंने नहीं भेजा ");
        map.put("I  did  not shake ", " मैंने हिला नहीं दिया ");
        map.put("I  did  not shine ", " मैं चमक नहीं पाया ");
        map.put("I  did  not shoot ", " मैंने शूट नहीं किया ");
        map.put("I  did  not show ", " मैंने नहीं दिखाया ");
        map.put("I  did  not shut  ", " मैंने बंद नहीं किया  ");
        map.put("I  did  not stand", " मैं खड़ा नहीं था");
        map.put("I  did  not understand ", " मुझे समझ नहीं आया ");

        return map;
    }
    private static Map<String, String> Four() {
        HashMap<String,String>map = new HashMap<>();
        map.put("I  have been not abusing ", " मैं गाली नहीं दे रहा हूं ");
        map.put("I  have been not advising ", " मैं सलाह नहीं दे रहा हूं ");
        map.put("I  have been not answering ", " मैं जवाब नहीं दे रहा हूं ");
        map.put("I  have been not arising ", " मैं नहीं उठ रहा हूँ ");
        map.put("I  have been not arriving ", " मैं नहीं आ रहा हूँ ");
        map.put("I  have been not asking ", " मैं नहीं पूछ रहा हूँ ");
        map.put("I  have been not awaking ", " मैं जाग नहीं रहा हूँ ");
        map.put("I  have been not undefined", " मुझे अपरिभाषित नहीं किया गया है");
        map.put("I  have been not bearing ", " मैं असर नहीं कर रहा हूँ ");
        map.put("I  have been not beating ", " मैं पिटाई नहीं कर रहा हूँ ");
        map.put("I  have been not becoming ", " मैं नहीं बन रहा हूँ ");
        map.put("I  have been not begging ", " मैं भीख नहीं मांग रहा हूँ ");
        map.put("I  have been not beginning ", " मैं शुरुआत नहीं कर रहा हूँ ");
        map.put("I  have been not binding ", " मैं बाइंडिंग नहीं कर रहा हूँ ");
        map.put("I  have been not biting ", " मैं काट नहीं रहा हूँ ");
        map.put("I  have been not blessing ", " मैं आशीष नहीं रहा हूँ ");
        map.put("I  have been not blowing ", " मैं उड़ नहीं रहा हूँ ");
        map.put("I  have been not breaking ", " मैं नहीं तोड़ रहा हूँ ");
        map.put("I  have been not bringing ", " मैं नहीं ला रहा हूँ ");
        map.put("I  have been not building ", " मैं निर्माण नहीं कर रहा हूँ ");
        map.put("I  have been not burning ", " मैं जल नहीं रहा हूँ ");
        map.put("I  have been not buying ", " मैं खरीद नहीं रहा हूँ ");
        map.put("I  have been not calling ", " मैं फोन नहीं कर रहा हूँ ");
        map.put("I  have been not carrying ", " मैं नहीं ले जा रहा हूँ ");
        map.put("I  have been not catching ", " मैं पकड़ नहीं रहा हूँ ");
        map.put("I  have been not cheating ", " मैं धोखा नहीं दे रहा हूँ ");
        map.put("I  have been not choosing ", " मैं नहीं चुन रहा हूं ");
        map.put("I  have been not cleaning ", " मैं सफाई नहीं कर रहा हूँ ");
        map.put("I  have been not climbing ", " मैं चढ़ नहीं रहा हूँ ");
        map.put("I  have been not closing ", " मैं बंद नहीं हो रहा हूँ ");
        map.put("I  have been not coming ", " मैं नहीं आ रहा हूँ ");
        map.put("I  have been not cooking ", " मैं खाना नहीं बना रहा हूँ ");
        map.put("I  have been not creeping ", " मैं रेंग नहीं रहा ");
        map.put("I  have been not crying ", " मैं रो नहीं रहा हूँ ");
        map.put("I  have been not cutting ", " मैं काट नहीं रहा हूँ ");
        map.put("I  have been not dancing ", " मैं नाच नहीं रहा हूँ ");
        map.put("I  have been not dealing ", " मैं काम नहीं कर रहा हूं ");
        map.put("I  have been not dying ", " मैं मर नहीं रहा हूँ ");
        map.put("I  have been not digging ", " मैं खुदाई नहीं कर रहा हूँ ");
        map.put("I  have been not doing ", " मैं नहीं कर रहा हूँ ");
        map.put("I  have been not drawing ", " मैं ड्राइंग नहीं कर रहा हूं ");
        map.put("I  have been not drinking ", " मैं शराब नहीं पी रहा हूँ ");
        map.put("I  have been not driving ", " मैं गाड़ी नहीं चला रहा हूँ ");
        map.put("I  have been not dropping ", " मैं नहीं गिरा रहा हूँ ");
        map.put("I  have been not drying ", " मैं सूख नहीं रहा हूं ");
        map.put("I  have been not eating ", " मैं नहीं खा रहा हूँ ");
        map.put("I  have been not electing ", " मैं चुनाव नहीं कर रहा हूँ ");
        map.put("I  have been not entering ", " मैं प्रवेश नहीं कर रहा हूँ ");
        map.put("I  have been not falling ", " मैं गिर नहीं रहा हूँ ");
        map.put("I  have been not feeding ", " मैं खिला नहीं रहा हूँ ");
        map.put("I  have been not feeling ", " मैं महसूस नहीं कर रहा हूँ ");
        map.put("I  have been not fighting ", " मैं लड़ नहीं रहा हूँ ");
        map.put("I  have been not finding ", " मुझे नहीं मिल रहा है ");
        map.put("I  have been not fleeing ", " मैं भाग नहीं रहा हूँ ");
        map.put("I  have been not flying ", " मैं उड़ नहीं रहा हूँ ");
        map.put("I  have been not forgetting ", " मैं भूल नहीं रहा हूँ ");
        map.put("I  have been not frying ", " मैं फ्राइंग नहीं कर रहा हूं ");
        map.put("I  have been not getting ", " मुझे नहीं मिल रहा है ");
        map.put("I  have been not giving ", " मैं नहीं दे रहा हूँ ");
        map.put("I  have been not going ", " मैं नहीं जा रहा हूँ ");
        map.put("I  have been not growing ", " मैं नहीं बढ़ रहा हूँ ");
        map.put("I  have been not hanging ", " मैं लटक नहीं रहा हूँ ");
        map.put("I  have been not hearing ", " मैं सुन नहीं रहा हूँ ");
        map.put("I  have been not helping ", " मैं मदद नहीं कर रहा हूँ ");
        map.put("I  have been not hiding ", " मैं छिपा नहीं रहा ");
        map.put("I  have been not hitting ", " मैं नहीं मार रहा हूँ ");
        map.put("I  have been not holding ", " मैं पकड़ नहीं रहा हूँ ");
        map.put("I  have been not hoping ", " मैं उम्मीद नहीं कर रहा था ");
        map.put("I  have been not hurting ", " मैं चोट नहीं पहुँचा रहा हूँ ");
        map.put("I  have been not jumping ", " मैं कूद नहीं रहा हूँ ");
        map.put("I  have been not keeping ", " मैं नहीं रख रहा हूँ ");
        map.put("I  have been not killing ", " मैं नहीं मार रहा हूँ ");
        map.put("I  have been not knowing ", " मैं नहीं जानता ");
        map.put("I  have been not laughing ", " मैं हँस नहीं रहा हूँ ");
        map.put("I  have been not leading ", " मैं अगुवाई नहीं कर रहा हूँ ");
        map.put("I  have been not leaping ", " मैं छलांग नहीं लगा रहा हूँ ");
        map.put("I  have been not learning ", " मैं नहीं सीख रहा हूँ ");
        map.put("I  have been not leaving ", " मैं नहीं जा रहा हूँ ");
        map.put("I  have been not lending ", " मैं उधार नहीं दे रहा हूँ ");
        map.put("I  have been not living ", " मैं नहीं रह रहा हूँ ");
        map.put("I  have been not looking ", " मैं नहीं देख रहा हूँ ");
        map.put("I  have been not losing ", " मैं हार नहीं रहा हूँ ");
        map.put("I  have been not loving ", " मैं प्यार नहीं कर रहा हूँ ");
        map.put("I  have been not making ", " मैं नहीं बना रहा ");
        map.put("I  have been not marrying ", " मैं शादी नहीं कर रहा हूँ ");
        map.put("I  have been not meeting ", " मैं मुलाकात नहीं कर रहा हूँ ");
        map.put("I  have been not mistaking ", " मैं गलती नहीं कर रहा हूँ ");
        map.put("I  have been not opening ", " मैं नहीं खोल रहा हूँ ");
        map.put("I  have been not paying ", " मैं भुगतान नहीं कर रहा हूँ ");
        map.put("I  have been not playing ", " मैं नहीं खेल रहा हूँ ");
        map.put("I  have been not putting ", " मैं नहीं डाल रहा हूँ ");
        map.put("I  have been not quarrelling ", " मैं झगड़ा नहीं कर रहा हूँ ");
        map.put("I  have been not raining ", " बारिश नहीं हो रही है ");
        map.put("I  have been not reaching ", " मैं नहीं पहुँच रहा हूँ ");
        map.put("I  have been not reading ", " मैं नहीं पढ़ रहा हूँ ");
        map.put("I  have been not remembering ", " मुझे याद नहीं आ रहा है ");
        map.put("I  have been not riding ", " मैं सवारी नहीं कर रहा हूँ ");
        map.put("I  have been not ringing ", " मैं नहीं बज रहा हूँ ");
        map.put("I  have been not rising ", " मैं उठ नहीं रहा हूँ ");
        map.put("I  have been not running ", " मैं दौड़ नहीं रहा हूँ ");
        map.put("I  have been not saying ", " मैं यह नहीं कह रहा हूँ ");
        map.put("I  have been not seeing ", " मैं नहीं देख रहा हूँ ");
        map.put("I  have been not selling ", " मैं नहीं बेच रहा हूँ ");
        map.put("I  have been not sending ", " मैं नहीं भेज रहा हूँ ");
        map.put("I  have been not shaking ", " मैं हिल नहीं रहा हूँ ");
        map.put("I  have been not shining ", " मैं चमक नहीं रहा हूँ ");
        map.put("I  have been not shooting ", " मैं शूटिंग नहीं कर रहा हूं ");
        map.put("I  have been not showing ", " मैं नहीं दिखा रहा हूँ ");
        map.put("I  have been not shutting ", " मैं बंद नहीं कर रहा हूँ ");
        map.put("I  have been not standing ", " मैं खड़ा नहीं हुआ ");
        map.put("I  have been not talking ", " मैं बात नहीं कर रहा हूँ ");
        map.put("I  have been not trying ", " मैं कोशिश नहीं कर रहा हूँ ");

        return map;
    }
    private static Map<String, String> Three() {
        HashMap<String,String>map = new HashMap<>();
        map.put("I  have not abused ", " मैंने गाली नहीं दी है ");
        map.put("I  have not advised ", " मैंने सलाह नहीं दी ");
        map.put("I  have not answered ", " मैंने जवाब नहीं दिया ");
        map.put("I  have not arisen ", " मैं पैदा नहीं हुआ हूँ ");
        map.put("I  have not arrived ", " मैं नहीं आया ");
        map.put("I  have not asked ", " मैंने नहीं पूछा ");
        map.put("I  have not awoken ", " मैं जाग नहीं पाया हूँ ");
        map.put("I  have not undefined", " मैंने अपरिभाषित नहीं किया है");
        map.put("I  have not borne ", " मैंने जन्म नहीं लिया है ");
        map.put("I  have not beaten ", " मैंने पीटा नहीं है ");
        map.put("I  have not become ", " मैं नहीं बन गया ");
        map.put("I  have not begged ", " मैंने भीख नहीं मांगी है ");
        map.put("I  have not begun ", " मैंने शुरू नहीं किया है ");
        map.put("I  have not bound ", " मैंने बाउंड नहीं किया है ");
        map.put("I  have not bitten ", " मैंने काटा नहीं है ");
        map.put("I  have not blessed ", " मैंने आशीष नहीं दी ");
        map.put("I  have not blown ", " मैंने नहीं उड़ाया है ");
        map.put("I  have not broken ", " मैंने नहीं तोड़ा है ");
        map.put("I  have not brought ", " मैं नहीं लाया हूँ ");
        map.put("I  have not built ", " मैंने नहीं बनाया है ");
        map.put("I  have not burnt ", " मैंने जलाया नहीं है ");
        map.put("I  have not bought ", " मैंने नहीं खरीदा है ");
        map.put("I  have not called ", " मैंने फोन नहीं किया ");
        map.put("I  have not carried ", " मैंने नहीं किया है ");
        map.put("I  have not caught ", " मैंने पकड़ा नहीं है ");
        map.put("I  have not cheated ", " मैंने धोखा नहीं दिया है ");
        map.put("I  have not chosen ", " मैंने नहीं चुना है ");
        map.put("I  have not cleaned ", " मैंने साफ नहीं किया है ");
        map.put("I  have not climbed ", " मैं चढ़ नहीं पाया ");
        map.put("I  have not closed ", " मैंने बंद नहीं किया है ");
        map.put("I  have not come ", " मैं नहीं आया ");
        map.put("I  have not cooked ", " मैंने खाना नहीं बनाया है ");
        map.put("I  have not crept ", " मैंने क्रेप नहीं किया है ");
        map.put("I  have not cried ", " मैं रोया नहीं ");
        map.put("I  have not cut ", " मैंने कट नहीं किया है ");
        map.put("I  have not danced ", " मैंने नृत्य नहीं किया है ");
        map.put("I  have not dealt ", " मैंने निपटा नहीं है ");
        map.put("I  have not died ", " मैं नहीं मरा हूँ ");
        map.put("I  have not dug ", " मैंने खोदा नहीं है ");
        map.put("I  have not done ", " मैंने नहीं किया ");
        map.put("I  have not drawn ", " मैंने ड्रॉ नहीं किया है ");
        map.put("I  have not drunk ", " मैंने शराब नहीं पी है ");
        map.put("I  have not driven ", " मैंने ड्राइव नहीं किया है ");
        map.put("I  have not dropped ", " मैंने नहीं गिराया है ");
        map.put("I  have not dried ", " मैंने नहीं सुखाया है ");
        map.put("I  have not eaten ", " मैंने नहीं खाया है ");
        map.put("I  have not elected ", " मैंने निर्वाचित नहीं किया है ");
        map.put("I  have not entered ", " मैंने प्रवेश नहीं किया है ");
        map.put("I  have not fallen ", " मैं गिर नहीं गया ");
        map.put("I  have not fed ", " मैंने खिलाया नहीं है ");
        map.put("I  have not felt ", " मैंने महसूस नहीं किया ");
        map.put("I  have not fought ", " मैंने लड़ाई नहीं की है ");
        map.put("I  have not found ", " मुझे नहीं मिला ");
        map.put("I  have not fled ", " मैं भाग नहीं गया ");
        map.put("I  have not flown ", " मैंने उड़ान नहीं भरी है ");
        map.put("I  have not forgotten ", " मैं नहीं भूला ");
        map.put("I  have not fried ", " मैंने तला नहीं है ");
        map.put("I  have not got ", " मुझे नहीं मिला है ");
        map.put("I  have not given ", " मैंने नहीं दिया है ");
        map.put("I  have not gone ", " मैं नहीं गया ");
        map.put("I  have not grown ", " मैं बड़ा नहीं हुआ ");
        map.put("I  have not hanged ", " मैंने फांसी नहीं लगाई है ");
        map.put("I  have not hung ", " मैंने लटका नहीं दिया है ");
        map.put("I  have not heard ", " मैंने नहीं सुना ");
        map.put("I  have not helped ", " मैंने मदद नहीं की ");
        map.put("I  have not hidden ", " मैंने छिपाया नहीं है ");
        map.put("I  have not hit ", " मैंने हिट नहीं किया है ");
        map.put("I  have not held ", " मैंने आयोजित नहीं किया है ");
        map.put("I  have not hoped ", " मुझे उम्मीद नहीं है ");
        map.put("I  have not hurt ", " मैंने चोट नहीं पहुंचाई है ");
        map.put("I  have not jumped ", " मैं कूद नहीं पाया ");
        map.put("I  have not kept ", " मैंने नहीं रखा है ");
        map.put("I  have not killed ", " मैंने नहीं मारा है ");
        map.put("I  have not known ", " मुझे पता नहीं है ");
        map.put("I  have not laughed ", " मैं हँसा नहीं हूँ ");
        map.put("I  have not led ", " मैंने नेतृत्व नहीं किया है ");
        map.put("I  have not leapt ", " मैंने छलांग नहीं लगाई है ");
        map.put("I  have not learnt ", " मैंने नहीं सीखा ");
        map.put("I  have not left ", " मैंने नहीं छोड़ा है ");
        map.put("I  have not lent ", " मैंने उधार नहीं दिया है ");
        map.put("I  have not lived ", " मैं नहीं रहता ");
        map.put("I  have not looked ", " मैंने नहीं देखा ");
        map.put("I  have not lost ", " मैं नहीं हारा ");
        map.put("I  have not loved ", " मैंने प्यार नहीं किया ");
        map.put("I  have not made ", " मैंने नहीं बनाया है ");
        map.put("I  have not married ", " मैंने शादी नहीं की है ");
        map.put("I  have not met ", " मैं नहीं मिला ");
        map.put("I  have not mistaken ", " मैंने गलत नहीं किया है ");
        map.put("I  have not opened ", " मैंने नहीं खोला है ");
        map.put("I  have not paid ", " मैंने भुगतान नहीं किया है ");
        map.put("I  have not played ", " मैंने नहीं खेला है ");
        map.put("I  have not put ", " मैंने नहीं रखा है ");
        map.put("I  have not quarrelled ", " मैंने झगड़ा नहीं किया है ");
        map.put("I  have not rained ", " मैंने बारिश नहीं की ");
        map.put("I  have not reached ", " मैं नहीं पहुँचा हूँ ");
        map.put("I  have not read ", " मैंने पढ़ा नहीं ");
        map.put("I  have not remembered ", " मुझे याद नहीं आया ");
        map.put("I  have not ridden ", " मैंने सवारी नहीं की है ");
        map.put("I  have not rung ", " मैंने नहीं बजाया है ");
        map.put("I  have not risen ", " मैं उठ नहीं पाया ");
        map.put("I  have not run ", " मैं भाग नहीं पाया ");
        map.put("I  have not said ", " मैंने नहीं कहा है ");
        map.put("I  have not seen ", " मैंने नहीं देखा ");
        map.put("I  have not sold ", " मैंने बेचा नहीं है ");
        map.put("I  have not sent ", " मैंने नहीं भेजा है ");
        map.put("I  have not shaken ", " मैं हिल नहीं गया ");
        map.put("I  have not shone ", " मैं चमक नहीं पाया ");
        map.put("I  have not shot ", " मैंने गोली नहीं मारी है ");
        map.put("I  have not shown ", " मैंने नहीं दिखाया है ");
        map.put("I  have not shut ", " मैंने बंद नहीं किया है ");
        map.put("I  have not told ", " मैंने नहीं बताया है ");

        return map;
    }
    private static Map<String, String> Two() {
        HashMap<String,String>map = new HashMap<>();
        map.put("I am not abusing ", " मैं गाली नहीं दे रहा हूँ ");
        map.put("I am not advising ", " मैं सलाह नहीं दे रहा हूँ ");
        map.put("I am not answering ", " मैं जवाब नहीं दे रहा हूँ ");
        map.put("I am not arising ", " मैं नहीं उठ रहा हूँ ");
        map.put("I am not arriving ", " मैं नहीं आ रहा हूँ ");
        map.put("I am not asking ", " मैं नहीं पूछ रहा हूँ ");
        map.put("I am not awaking ", " मैं जाग नहीं रहा हूँ ");
        map.put("I am not undefined", " मैं अपरिभाषित नहीं हूँ");
        map.put("I am not bearing ", " मैं असर नहीं कर रहा हूँ ");
        map.put("I am not beating ", " मैं पिटाई नहीं कर रहा हूँ ");
        map.put("I am not becoming ", " मैं नहीं बन रहा हूँ ");
        map.put("I am not begging ", " मैं भीख नहीं मांग रहा हूँ ");
        map.put("I am not beginning ", " मैं शुरुआत नहीं कर रहा हूँ ");
        map.put("I am not binding ", " मैं बाध्यकारी नहीं हूँ ");
        map.put("I am not biting ", " मैं काट नहीं रहा हूँ ");
        map.put("I am not blessing ", " मैं आशीष नहीं हूँ ");
        map.put("I am not blowing ", " मैं उड़ नहीं रहा हूँ ");
        map.put("I am not breaking ", " मैं नहीं तोड़ रहा हूँ ");
        map.put("I am not bringing ", " मैं नहीं ला रहा हूँ ");
        map.put("I am not building ", " मैं निर्माण नहीं कर रहा हूँ ");
        map.put("I am not burning ", " मैं जल नहीं रहा हूँ ");
        map.put("I am not buying ", " मैं नहीं खरीद रहा हूँ ");
        map.put("I am not calling ", " मैं कॉल नहीं कर रहा हूँ ");
        map.put("I am not carrying ", " मैं नहीं ले जा रहा हूँ ");
        map.put("I am not catching ", " मैं पकड़ नहीं रहा हूँ ");
        map.put("I am not cheating ", " मैं धोखा नहीं दे रहा हूँ ");
        map.put("I am not choosing ", " मैं नहीं चुन रहा हूँ ");
        map.put("I am not cleaning ", " मैं सफाई नहीं कर रहा हूँ ");
        map.put("I am not climbing ", " मैं चढ़ नहीं रहा हूँ ");
        map.put("I am not closing ", " मैं बंद नहीं कर रहा हूँ ");
        map.put("I am not coming ", " मैं नहीं आ रहा हूँ ");
        map.put("I am not cooking ", " मैं खाना नहीं बना रहा हूँ ");
        map.put("I am not creeping ", " मैं रेंग नहीं रहा हूँ ");
        map.put("I am not crying ", " मैं रो नहीं रहा ");
        map.put("I am not cutting ", " मैं काट नहीं रहा हूँ ");
        map.put("I am not dancing ", " मैं नाच नहीं रहा हूँ ");
        map.put("I am not dealing ", " मैं काम नहीं कर रहा हूँ ");
        map.put("I am not dying ", " मैं मर नहीं रहा हूँ ");
        map.put("I am not digging ", " मैं खुदाई नहीं कर रहा हूँ ");
        map.put("I am not doing ", " मैं नहीं कर रहा हूँ ");
        map.put("I am not drawing ", " मैं ड्राइंग नहीं कर रहा हूँ ");
        map.put("I do not dream ", " मैं सपने नहीं देखता ");
        map.put("I am not dreaming ", " मैं सपना नहीं देख रहा हूँ ");

        map.put("I am not drinking ", " मैं नहीं पी रहा हूँ ");
        map.put("I am not driving ", " मैं गाड़ी नहीं चला रहा हूँ ");
        map.put("I am not dropping ", " मैं नहीं गिर रहा हूँ ");
        map.put("I am not drying ", " मैं सूख नहीं रहा हूँ ");
        map.put("I am not eating ", " मैं नहीं खा रहा हूँ ");
        map.put("I am not electing ", " मैं चुनाव नहीं कर रहा हूँ ");
        map.put("I am not entering ", " मैं प्रवेश नहीं कर रहा हूँ ");
        map.put("I am not falling ", " मैं गिर नहीं रहा हूँ ");
        map.put("I am not feeding ", " मैं नहीं खिला रहा हूँ ");
        map.put("I am not feeling ", " मैं महसूस नहीं कर रहा हूँ ");
        map.put("I am not fighting ", " मैं लड़ाई नहीं कर रहा हूँ ");
        map.put("I am not finding ", " मुझे नहीं मिल रहा है ");
        map.put("I am not fleeing ", " मैं भाग नहीं रहा हूँ ");
        map.put("I am not flying ", " मैं उड़ नहीं रहा हूँ ");
        map.put("I am not forgetting ", " मैं नहीं भूल रहा हूँ ");
        map.put("I am not frying ", " मैं फ्राइंग नहीं कर रहा हूँ ");
        map.put("I am not getting ", " मुझे नहीं मिल रहा है ");
        map.put("I am not giving ", " मैं नहीं दे रहा हूँ ");
        map.put("I am not going ", " मैं नहीं जा रहा हूँ ");
        map.put("I am not growing ", " मैं नहीं बढ़ रहा हूँ ");
        map.put("I am not hanging ", " मैं लटक नहीं रहा हूँ ");
        map.put("I am not hearing ", " मैं नहीं सुन रहा हूँ ");
        map.put("I am not helping ", " मैं मदद नहीं कर रहा हूँ ");
        map.put("I am not hiding ", " मैं छिपा नहीं रहा ");
        map.put("I am not hitting ", " मैं नहीं मार रहा हूँ ");
        map.put("I am not holding ", " मैं पकड़ नहीं रहा हूँ ");
        map.put("I am not hoping ", " मैं उम्मीद नहीं कर रहा हूँ ");
        map.put("I am not hurting ", " मैं चोट नहीं पहुँचा रहा हूँ ");
        map.put("I am not jumping ", " मैं कूद नहीं रहा हूँ ");
        map.put("I am not keeping ", " मैं नहीं रख रहा हूँ ");
        map.put("I am not killing ", " मैं नहीं मार रहा हूँ ");
        map.put("I am not knowing ", " मैं नहीं जानता ");
        map.put("I am not laughing ", " मैं हँस नहीं रहा हूँ ");
        map.put("I am not leading ", " मैं अग्रणी नहीं हूं ");
        map.put("I am not leaping ", " मैं छलांग नहीं लगा रहा हूँ ");
        map.put("I am not learning ", " मैं नहीं सीख रहा हूँ ");
        map.put("I am not leaving ", " मैं नहीं जा रहा हूँ ");
        map.put("I am not lending ", " मैं उधार नहीं दे रहा हूँ ");
        map.put("I am not living ", " मैं नहीं जी रहा ");
        map.put("I am not looking ", " मैं नहीं देख रहा हूँ ");
        map.put("I am not losing ", " मैं हार नहीं रहा हूँ ");
        map.put("I am not loving ", " मैं प्यार नहीं कर रहा हूँ ");
        map.put("I am not making ", " मैं नहीं बना रहा हूँ ");
        map.put("I am not marrying ", " मैं शादी नहीं कर रहा हूँ ");
        map.put("I am not meeting ", " मैं नहीं मिल रहा हूँ ");
        map.put("I am not mistaking ", " मैं गलती नहीं कर रहा हूँ ");
        map.put("I am not opening ", " मैं नहीं खोल रहा हूँ ");
        map.put("I am not paying ", " मैं भुगतान नहीं कर रहा हूँ ");
        map.put("I am not playing ", " मैं नहीं खेल रहा हूँ ");
        map.put("I am not putting ", " मैं नहीं डाल रहा हूँ ");
        map.put("I am not quarrelling ", " मैं झगड़ा नहीं कर रहा हूँ ");
        map.put("I am not raining ", " मैं बारिश नहीं कर रहा हूँ ");
        map.put("I am not reaching ", " मैं नहीं पहुँच रहा हूँ ");
        map.put("I am not reading ", " मैं नहीं पढ़ रहा हूँ ");
        map.put("I am not remembering ", " मुझे याद नहीं है ");
        map.put("I am not riding ", " मैं सवारी नहीं कर रहा हूँ ");
        map.put("I am not ringing ", " मैं नहीं बज रहा हूँ ");
        map.put("I am not rising ", " मैं उठ नहीं रहा हूँ ");
        map.put("I am not running ", " मैं भाग नहीं रहा हूँ ");
        map.put("I am not saying ", " मैं नहीं कह रहा ");
        map.put("I am not seeing ", " मैं नहीं देख रहा हूँ ");
        map.put("I am not selling ", " मैं नहीं बेच रहा हूँ ");
        map.put("I am not sending ", " मैं नहीं भेज रहा हूँ ");
        map.put("I am not shaking ", " मैं हिल नहीं रहा हूँ ");
        map.put("I am not shining ", " मैं चमक नहीं रहा हूँ ");
        map.put("I am not shooting ", " मैं शूटिंग नहीं कर रहा हूँ ");
        map.put("I am not showing ", " मैं नहीं दिखा रहा हूँ ");
        map.put("I am not shutting ", " मैं बंद नहीं कर रहा हूँ ");
        map.put("I am not starting ", " मैं शुरू नहीं कर रहा हूँ ");
        map.put("I am not throwing ", " मैं नहीं फेंक रहा हूँ ");
        map.put("I am not washing ", " मैं नहीं धो रहा हूँ ");


        return map;
    }

    private static Map<String, String> One() {
        HashMap<String,String>map = new HashMap<>();
        map.put("I do not abuse ", " मैं गाली नहीं देता ");
        map.put("I do not advise", " मैं सलाह नहीं देता");
        map.put("I do not answer ", " मैं जवाब नहीं देता ");
        map.put("I do not arise ", " मैं नहीं उठता ");
        map.put("I do not arrive ", " मैं नहीं आता ");
        map.put("I do not ask ", " मैं नहीं पूछता ");
        map.put("I do not awake ", " मैं नहीं जागता ");

        map.put("I do not bear ", " मैं सहन नहीं करता ");
        map.put("I do not beat ", " मैं हरा नहीं करता ");
        map.put("I do not become ", " मैं नहीं बनता ");
        map.put("I do not beg ", " मैं भीख नहीं मांगता ");
        map.put("I do not begin ", " मैं शुरू नहीं करता ");
        map.put("I do not bind ", " मैं बाँध नहीं करता ");
        map.put("I do not bite", " मैं काटता नहीं");
        map.put("I do not bless", " मैं आशीष नहीं देता");
        map.put("I do not blow ", " मैं नहीं उड़ाता ");
        map.put("I do not break ", " मैं नहीं टूटता ");
        map.put("I do not bring ", " मैं नहीं लाता ");
        map.put("I do not build ", " मैं निर्माण नहीं करता ");
        map.put("I do not burn ", " मैं जलता नहीं ");
        map.put("I do not buy ", " मैं नहीं खरीदता ");
        map.put("I do not call ", " मैं कॉल नहीं करता ");
        map.put("I do not carry ", " मैं नहीं ले जाता ");
        map.put("I do not catch ", " मैं नहीं पकड़ता ");
        map.put("I do not choose ", " मैं नहीं चुनता ");
        map.put("I do not clean ", " मैं साफ नहीं करता ");
        map.put("I do not climb  ", " मैं नहीं चढ़ता  ");
        map.put("I do not close ", " मैं बंद नहीं करता ");
        map.put("I do not come ", " मैं नहीं आता ");
        map.put("I do not cook ", " मैं खाना नहीं बनाती ");
        map.put("I do not creep ", " मैं रेंगना नहीं करता ");
        map.put("I do not cry ", " मैं रोता नहीं ");
        map.put("I do not cut ", " मैं कट नहीं करता ");
        map.put("I do not dance ", " मैं नाचता नहीं हूँ ");
        map.put("I do not deal ", " मैं सौदा नहीं करता ");
        map.put("I do not die ", " मैं नहीं मरता ");
        map.put("I do not dig ", " मैं खुदाई नहीं करता ");
        map.put("I do not do ", " मैं नहीं करता ");

        map.put("I do not draw ", " मैं आकर्षित नहीं करता ");
        map.put("I do not drive ", " मैं ड्राइव नहीं करता ");
        map.put("I do not drop ", " मैं नहीं छोड़ता ");
        map.put("I do not dry ", " मैं सूखा नहीं ");
        map.put("I do not eat ", " मैं नहीं खाता ");
        map.put("I do not elect", " मैं चुनाव नहीं करता");
        map.put("I do not fall ", " मैं नहीं गिरता ");
        map.put("I do not feed ", " मैं नहीं खिलाता ");
        map.put("I do not feel  ", " मुझे नहीं लगता  ");
        map.put("I do not fight ", " मैं नहीं लड़ता ");
        map.put("I do not find ", " मुझे नहीं मिला ");
        map.put("I do not flee ", " मैं पलायन नहीं करता ");
        map.put("I do not fly  ", " मैं नहीं उड़ता  ");
        map.put("I do not forget ", " मैं नहीं भूलता ");
        map.put("I do not fry ", " मैं फ्राई नहीं करता ");
        map.put("I do not get  ", " मुझे नहीं मिला  ");
        map.put("I do not give ", " मैं नहीं देता ");
        map.put("I do not go ", " मैं नहीं जाता ");
        map.put("I do not grow", " मैं नहीं बढ़ता");
        map.put("I do not hang ", " मैं लटका नहीं ");
        map.put("I do not hear ", " मैं नहीं सुनता ");
        map.put("I do not help ", " मैं मदद नहीं करता ");
        map.put("I do not hide ", " मैं छिपता नहीं ");
        map.put("I do not hit ", " मैं हिट नहीं करता ");
        map.put("I do not hold ", " मुझे पकड़ नहीं है ");
        map.put("I do not hope ", " मुझे उम्मीद नहीं है ");
        map.put("I do not hurt ", " मुझे चोट नहीं पहुंची ");
        map.put("I do not jump ", " मैं नहीं कूदता ");
        map.put("I do not kill ", " मैं नहीं मारता ");
        map.put("I do not know ", " मुझे नहीं पता ");
        map.put("I do not laugh ", " मैं हँसता नहीं हूँ ");
        map.put("I do not lead ", " मैं नेतृत्व नहीं करता ");
        map.put("I do not leap ", " मैं छलांग नहीं लगाता ");
        map.put("I do not learn ", " मैं नहीं सीखता ");
        map.put("I do not leave ", " मैं नहीं छोड़ता ");
        map.put("I do not lend ", " मैं उधार नहीं देता ");
        map.put("I do not live ", " मैं नहीं रहता ");
        map.put("I do not look ", " मैं नहीं देखता ");
        map.put("I do not lose ", " मैं नहीं हारता ");
        map.put("I do not love ", " मुझे प्यार नहीं है ");
        map.put("I do not make ", " मैं नहीं बनाता ");
        map.put("I do not marry ", " मैं शादी नहीं करता ");
        map.put("I do not meet ", " मैं नहीं मिलता ");
        map.put("I do not mistake ", " मुझे गलती नहीं है ");
        map.put("I do not open ", " मैं नहीं खोलता ");
        map.put("I do not pay  ", " मैं भुगतान नहीं करता  ");
        map.put("I do not play ", " मैं नहीं खेलता ");
        map.put("I do not put ", " मैं नहीं डालता ");
        map.put("I do not rain ", " मैं बारिश नहीं करता ");
        map.put("I do not reach ", " मैं नहीं पहुँचता ");
        map.put("I do not read", " मैं नहीं पढ़ता");
        map.put("I do not remember  ", " मुझे याद नहीं  ");
        map.put("I do not ride ", " मैं सवारी नहीं करता ");
        map.put("I do not ring ", " मैं रिंग नहीं करता ");
        map.put("I do not rise  ", " मैं नहीं उठता  ");
        map.put("I do not run  ", " मैं नहीं दौड़ता  ");
        map.put("I do not say ", " मैं नहीं कहता ");
        map.put("I do not see ", " मैं नहीं देखता ");
        map.put("I do not sell ", " मैं नहीं बेचता ");
        map.put("I do not send ", " मैं नहीं भेजता ");
        map.put("I do not shake ", " मैं हिला नहीं ");
        map.put("I do not shine ", " मैं चमक नहीं रहा ");
        map.put("I do not shoot ", " मैं शूट नहीं करता ");
        map.put("I do not show ", " मैं नहीं दिखाता ");
        map.put("I do not shut  ", " मैं बंद नहीं करता  ");

        return map;
    }
}
