package com.shiviishiv7.helloenglish.QuestionSource;

import java.util.HashMap;
import java.util.Map;

public class How {
    public static Map<String,String> How(int state){
        switch (state){
            case 1:return One();
            case 2:return Two();
            case 3:return Three();
            case 4:return Four();
            case 5:return Five();
            case 6:return Six();
            case 7:return Seven();
            case 8:return Eight();
            case 9:return Nine();
            case 10:return Ten();
            case 11:return Eleven();
            case 12:return Twelve();

            default:return One();
        }

    }
    static Map<String,String> One(){
        HashMap<String,String>map = new HashMap<>();
        map.put("How do I abuse ", "मैं गाली कैसे दूँ ");
        map.put("How do I advise", "मैं कैसे सलाह दूँ");
        map.put("How do I answer ", "मैं कैसे जवाब दूं ");
        map.put("How do I arise ", "मैं कैसे उठ सकता हूँ ");
        map.put("How do I arrive ", "मैं कैसे पहुँचूँ ");
        map.put("How do I ask ", "मैं कैसे पूछूँ ");
        map.put("How do I awake ", "मैं कैसे जाग सकता हूँ ");
        map.put("How do I \r", "मैं कैसे करूँ \r");
        map.put("How do I bear ", "मैं कैसे सहन करूँ ");
        map.put("How do I beat ", "मैं कैसे हराऊं ");
        map.put("How do I become ", "मैं कैसे बन सकता हूँ ");
        map.put("How do I beg ", "मैं कैसे भीख माँगता हूँ ");
        map.put("How do I begin ", "मैं कैसे शुरू करूँ ");
        map.put("How do I bind ", "मैं कैसे बाँध सकता हूँ ");
        map.put("How do I bite", "मैं कैसे काटूं");
        map.put("How do I bless", "मैं कैसे आशीष दूं");
        map.put("How do I blow ", "मैं कैसे उड़ाऊं ");
        map.put("How do I break ", "मैं कैसे तोड़ूं ");
        map.put("How do I bring ", "मैं कैसे लाऊं ");
        map.put("How do I build ", "मैं कैसे बनाऊं ");
        map.put("How do I burn ", "मैं कैसे जलाऊं ");
        map.put("How do I buy ", "मैं कैसे खरीदूं ");
        map.put("How do I call ", "मैं कैसे कॉल करूँ ");
        map.put("How do I carry ", "मैं कैसे ले जाऊं ");
        map.put("How do I catch ", "मैं कैसे पकड़ सकता हूँ ");
        map.put("How do I choose ", "मैं कैसे चुनूं ");
        map.put("How do I clean ", "मैं कैसे साफ करूँ ");
        map.put("How do I climb  ", "मैं कैसे चढ़ सकता हूँ  ");
        map.put("How do I close ", "मैं कैसे बंद करूँ ");
        map.put("How do I come ", "मैं कैसे आऊं ");
        map.put("How do I cook ", "मैं कैसे खाना बनाती हूँ ");
        map.put("How do I creep ", "मैं कैसे रेंगूं ");
        map.put("How do I cry ", "मैं कैसे रोऊं ");
        map.put("How do I cut ", "मैं कैसे काटूं ");
        map.put("How do I dance ", "मैं कैसे नृत्य करूँ ");
        map.put("How do I deal ", "मैं कैसे सौदा करूँ ");
        map.put("How do I die ", "मैं कैसे मर सकता हूँ ");
        map.put("How do I dig ", "मैं कैसे खोदूं ");
        map.put("How do I do ", "मैं कैसे करूँ ");
        map.put("How  did I  do ", "मैंने कैसे किया ");
        map.put("How  was I  doing ", "मैं कैसे कर रहा था ");
        map.put("How  had I  done ", "मैंने कैसे किया था ");
        map.put("How  had I been  doing ", "मैं कैसे कर रहा था ");
        map.put("How  will I do ", "मैं कैसे करूँगा ");
        map.put("How  will I be doing ", "मैं कैसे कर रहा हूँ ");
        map.put("How  will I have done ", "मैंने कैसे किया होगा ");
        map.put("How  will I have been doing ", "मैं कैसे कर रहा हूँ ");
        map.put("How do I draw ", "मैं कैसे आकर्षित करूं ");
        map.put("How do I drive ", "मैं कैसे चलाऊं ");
        map.put("How do I drop ", "मैं कैसे छोड़ूं ");
        map.put("How do I dry ", "मैं कैसे सुखाऊं ");
        map.put("How do I eat ", "मैं कैसे खाऊं ");
        map.put("How do I elect", "मैं कैसे चुनाव करूं");
        map.put("How do I fall ", "मैं कैसे गिरूं ");
        map.put("How do I feed ", "मैं कैसे खिलाऊं ");
        map.put("How do I feel  ", "मैं कैसा महसूस करता हूँ  ");
        map.put("How do I fight ", "मैं कैसे लड़ूं ");
        map.put("How do I find ", "मैं कैसे ढूंढूं ");
        map.put("How do I flee ", "मैं कैसे भाग सकता हूँ ");
        map.put("How do I fly  ", "मैं कैसे उड़ूँ  ");
        map.put("How do I forget ", "मैं कैसे भूल सकता हूँ ");
        map.put("How do I fry ", "मैं कैसे भूनूं ");
        map.put("How do I get  ", "मुझे कैसे मिलेगा  ");
        map.put("How do I give ", "मैं कैसे दे सकता हूँ ");
        map.put("How do I go ", "मैं कैसे जाऊं ");
        map.put("How do I grow", "मैं कैसे बढ़ूँ");
        map.put("How do I hang ", "मैं कैसे लटकाऊं ");
        map.put("How do I hear ", "मैं कैसे सुन सकता हूँ ");
        map.put("How do I help ", "मैं कैसे मदद करूँ ");
        map.put("How do I hide ", "मैं कैसे छिपाऊं ");
        map.put("How do I hit ", "मैं कैसे मारूं ");
        map.put("How do I hold ", "मैं कैसे पकड़ सकता हूँ ");
        map.put("How do I hope ", "मैं कैसे आशा करता हूँ ");
        map.put("How do I hurt ", "मैं कैसे चोट पहुँचाऊँ ");
        map.put("How do I jump ", "मैं कैसे कूदूं ");
        map.put("How do I kill ", "मैं कैसे मार सकता हूँ ");
        map.put("How do I know ", "मुझे कैसे पता चलेगा ");
        map.put("How do I laugh ", "मैं कैसे हँसता हूँ ");
        map.put("How do I lead ", "मैं कैसे नेतृत्व करूँ ");
        map.put("How do I leap ", "मैं कैसे छलांग लगाऊं ");
        map.put("How do I learn ", "मैं कैसे सीखूं ");
        map.put("How do I leave ", "मैं कैसे छोड़ूँ ");
        map.put("How do I lend ", "मैं कैसे उधार दे सकता हूँ ");
        map.put("How do I live ", "मैं कैसे रहूँ ");
        map.put("How do I look ", "मैं कैसे देखूं ");
        map.put("How do I lose ", "मैं कैसे हारूं ");
        map.put("How do I love ", "मैं कैसे प्यार करता हूँ ");
        map.put("How do I make ", "मैं कैसे बनाऊं ");
        map.put("How do I marry ", "मैं शादी कैसे करूँ ");
        map.put("How do I meet ", "मैं कैसे मिलूँ ");
        map.put("How do I mistake ", "मैं गलती कैसे करूँ ");
        map.put("How do I open ", "मैं कैसे खोलूं ");
        map.put("How do I pay  ", "मैं भुगतान कैसे करूं  ");
        map.put("How do I play ", "मैं कैसे खेलूं ");
        map.put("How do I put ", "मैं कैसे रखूं ");
        map.put("How do I rain ", "मैं बारिश कैसे करूँ ");
        map.put("How do I reach ", "मैं कैसे पहुँचूँ ");
        map.put("How do I read", "मैं कैसे पढ़ूँ");
        map.put("How do I remember  ", "मुझे कैसे याद है  ");
        map.put("How do I ride ", "मैं कैसे सवारी करूँ ");
        map.put("How do I ring ", "मैं कैसे रिंग करूँ ");
        map.put("How do I rise  ", "मैं कैसे उठूं  ");
        map.put("How do I run  ", "मैं कैसे दौड़ूँ  ");
        map.put("How do I say ", "मैं कैसे कहूँ ");

        return map;
    }
    static Map<String,String> Two(){
        HashMap<String,String>map = new HashMap<>();
        map.put("How am I abusing ", "मैं कैसे गाली दे रहा हूँ ");
        map.put("How am I advising ", "मैं कैसे सलाह दे रहा हूँ ");
        map.put("How am I answering ", "मैं कैसे जवाब दे रहा हूँ ");
        map.put("How am I arising ", "मैं कैसे उठ रहा हूँ ");
        map.put("How am I arriving ", "मैं कैसे आ रहा हूँ ");
        map.put("How am I asking ", "मैं कैसे पूछ रहा हूँ ");
        map.put("How am I awaking ", "मैं कैसे जाग रहा हूँ ");
        map.put("How am I undefined", "मैं अपरिभाषित कैसे हूँ");
        map.put("How am I bearing ", "मैं कैसे असर कर रहा हूँ ");
        map.put("How am I beating ", "मैं कैसे पिटाई कर रहा हूँ ");
        map.put("How am I becoming ", "मैं कैसे बन रहा हूँ ");
        map.put("How am I begging ", "मैं कैसे भीख माँग रहा हूँ ");
        map.put("How am I beginning ", "मैं कैसे शुरू कर रहा हूँ ");
        map.put("How am I binding ", "मैं कैसे बाध्यकारी हूँ ");
        map.put("How am I biting ", "मैं कैसे काट रहा हूँ ");
        map.put("How am I blessing ", "मैं कैसे आशीर्वाद दे रहा हूँ ");
        map.put("How am I blowing ", "मैं कैसे उड़ रहा हूँ ");
        map.put("How am I breaking ", "मैं कैसे तोड़ रहा हूँ ");
        map.put("How am I bringing ", "मैं कैसे ला रहा हूँ ");
        map.put("How am I building ", "मैं कैसे निर्माण कर रहा हूँ ");
        map.put("How am I burning ", "मैं कैसे जल रहा हूँ ");
        map.put("How am I buying ", "मैं कैसे खरीद रहा हूँ ");
        map.put("How am I calling ", "मैं कैसे कॉल कर रहा हूँ ");
        map.put("How am I carrying ", "मैं कैसे ले जा रहा हूँ ");
        map.put("How am I catching ", "मैं कैसे पकड़ रहा हूँ ");
        map.put("How am I cheating ", "मैं कैसे धोखा दे रहा हूँ ");
        map.put("How am I choosing ", "मैं कैसे चुन रहा हूँ ");
        map.put("How am I cleaning ", "मैं कैसे सफाई कर रहा हूँ ");
        map.put("How am I climbing ", "मैं कैसे चढ़ रहा हूँ ");
        map.put("How am I closing ", "मैं कैसे बंद कर रहा हूँ ");
        map.put("How am I coming ", "मैं कैसे आ रहा हूँ ");
        map.put("How am I cooking ", "मैं कैसे खाना बना रहा हूँ ");
        map.put("How am I creeping ", "मैं कैसे रेंग रहा हूँ ");
        map.put("How am I crying ", "मैं कैसे रो रहा हूँ ");
        map.put("How am I cutting ", "मैं कैसे काट रहा हूँ ");
        map.put("How am I dancing ", "मैं कैसे नाच रहा हूँ ");
        map.put("How am I dealing ", "मैं कैसे काम कर रहा हूँ ");
        map.put("How am I dying ", "मैं कैसे मर रहा हूँ ");
        map.put("How am I digging ", "मैं कैसे खुदाई कर रहा हूँ ");
        map.put("How am I doing ", "मैं कैसे कर रहा हूँ ");
        map.put("How am I drawing ", "मैं कैसे आकर्षित कर रहा हूँ ");
        map.put("How do I dream ", "मैं कैसे सपना देखूं ");
        map.put("How  have I dreamt ", "मैंने कैसे सपना देखा है ");
        map.put("How  did I  dream ", "मैंने कैसे सपना देखा ");
        map.put("How  was I  dreaming ", "मैं कैसे सपना देख रहा था ");
        map.put("How am I dreaming ", "मैं कैसे सपना देख रहा हूँ ");
        map.put("How  had I  dreamt ", "मैंने कैसे सपना देखा था ");
        map.put("How  have I been dreaming ", "मैं कैसे सपना देख रहा हूँ ");
        map.put("How  had I been  dreaming ", "मैं कैसे सपना देख रहा था ");
        map.put("How  will I be dreaming ", "मैं कैसे सपने देख रहा हूँ ");
        map.put("How  will I have dreamt ", "मैंने कैसे सपना देखा होगा ");
        map.put("How  will I have been dreaming ", "मैं कैसे सपना देख रहा हूँ ");
        map.put("How am I drinking ", "मैं कैसे पी रहा हूँ ");
        map.put("How am I driving ", "मैं कैसे चला रहा हूँ ");
        map.put("How am I dropping ", "मैं कैसे गिर रहा हूँ ");
        map.put("How am I drying ", "मैं कैसे सूख रहा हूँ ");
        map.put("How am I eating ", "मैं कैसे खा रहा हूँ ");
        map.put("How am I electing ", "मैं कैसे चुनाव कर रहा हूँ ");
        map.put("How am I entering ", "मैं कैसे प्रवेश कर रहा हूँ ");
        map.put("How am I falling ", "मैं कैसे गिर रहा हूँ ");
        map.put("How am I feeding ", "मैं कैसे खिला रहा हूँ ");
        map.put("How am I feeling ", "मैं कैसा महसूस कर रहा हूँ ");
        map.put("How am I fighting ", "मैं कैसे लड़ रहा हूँ ");
        map.put("How am I finding ", "मैं कैसे खोज रहा हूँ ");
        map.put("How am I fleeing ", "मैं कैसे भाग रहा हूँ ");
        map.put("How am I flying ", "मैं कैसे उड़ रहा हूँ ");
        map.put("How am I forgetting ", "मैं कैसे भूल रहा हूँ ");
        map.put("How am I frying ", "मैं कैसे फ्राइंग कर रहा हूँ ");
        map.put("How am I getting ", "मुझे कैसे मिल रहा है ");
        map.put("How am I giving ", "मैं कैसे दे रहा हूँ ");
        map.put("How am I going ", "मैं कैसे जा रहा हूँ ");
        map.put("How am I growing ", "मैं कैसे बढ़ रहा हूँ ");
        map.put("How am I hanging ", "मैं कैसे लटक रहा हूँ ");
        map.put("How am I hearing ", "मैं कैसे सुन रहा हूँ ");
        map.put("How am I helping ", "मैं कैसे मदद कर रहा हूँ ");
        map.put("How am I hiding ", "मैं कैसे छिपा रहा हूँ ");
        map.put("How am I hitting ", "मैं कैसे मार रहा हूँ ");
        map.put("How am I holding ", "मैं कैसे पकड़ रहा हूँ ");
        map.put("How am I hoping ", "मैं कैसे उम्मीद कर रहा हूँ ");
        map.put("How am I hurting ", "मैं कैसे चोट पहुँचा रहा हूँ ");
        map.put("How am I jumping ", "मैं कैसे कूद रहा हूँ ");
        map.put("How am I keeping ", "मैं कैसे रख रहा हूँ ");
        map.put("How am I killing ", "मैं कैसे मार रहा हूँ ");
        map.put("How am I knowing ", "मैं कैसे जान रहा हूँ ");
        map.put("How am I laughing ", "मैं कैसे हँस रहा हूँ ");
        map.put("How am I leading ", "मैं कैसे नेतृत्व कर रहा हूँ ");
        map.put("How am I leaping ", "मैं कैसे छलांग लगा रहा हूँ ");
        map.put("How am I learning ", "मैं कैसे सीख रहा हूँ ");
        map.put("How am I leaving ", "मैं कैसे जा रहा हूँ ");
        map.put("How am I lending ", "मैं कैसे उधार दे रहा हूँ ");
        map.put("How am I living ", "मैं कैसे रह रहा हूँ ");
        map.put("How am I looking ", "मैं कैसे देख रहा हूँ ");
        map.put("How am I losing ", "मैं कैसे हार रहा हूँ ");
        map.put("How am I loving ", "मैं कैसे प्यार कर रहा हूँ ");
        map.put("How am I making ", "मैं कैसे बना रहा हूँ ");
        map.put("How am I marrying ", "मैं शादी कैसे कर रहा हूँ ");
        map.put("How am I meeting ", "मैं कैसे मिल रहा हूँ ");
        map.put("How am I mistaking ", "मैं कैसे गलत कर रहा हूँ ");
        map.put("How am I opening ", "मैं कैसे खोल रहा हूँ ");
        map.put("How am I paying ", "मैं कैसे भुगतान कर रहा हूँ ");
        map.put("How am I playing ", "मैं कैसे खेल रहा हूँ ");
        map.put("How am I putting ", "मैं कैसे डाल रहा हूँ ");
        map.put("How am I quarrelling ", "मैं कैसे झगड़ा कर रहा हूँ ");
        map.put("How am I raining ", "मैं बारिश कैसे कर रहा हूँ ");
        map.put("How am I reaching ", "मैं कैसे पहुँच रहा हूँ ");
        map.put("How am I reading ", "मैं कैसे पढ़ रहा हूँ ");
        map.put("How am I remembering ", "मैं कैसे याद कर रहा हूँ ");
        map.put("How am I riding ", "मैं कैसे सवारी कर रहा हूँ ");
        map.put("How am I ringing ", "मैं कैसे बज रहा हूँ ");
        map.put("How am I rising ", "मैं कैसे उठ रहा हूँ ");
        map.put("How am I running ", "मैं कैसे चल रहा हूँ ");
        map.put("How am I saying ", "मैं कैसे कह रहा हूँ ");

        return map;
    }
    static Map<String,String> Three(){
        HashMap<String,String>map = new HashMap<>();
        map.put("How  have I abused ", "मैंने गाली कैसे दी ");
        map.put("How  have I advised ", "मैंने कैसे सलाह दी है ");
        map.put("How  have I answered ", "मैंने कैसे उत्तर दिया है ");
        map.put("How  have I arisen ", "मैं कैसे पैदा हुआ हूँ ");
        map.put("How  have I arrived ", "मैं कैसे आया हूँ ");
        map.put("How  have I asked ", "मैंने कैसे पूछा है ");
        map.put("How  have I awoken ", "मैं कैसे जाग गया ");
        map.put("How  have I undefined", "मैंने अपरिभाषित कैसे किया है");
        map.put("How  have I borne ", "मैंने कैसे जन्म लिया है ");
        map.put("How  have I beaten ", "मैंने कैसे पीटा है ");
        map.put("How  have I become ", "मैं कैसे बन गया ");
        map.put("How  have I begged ", "मैंने कैसे भीख माँगी ");
        map.put("How  have I begun ", "मैंने कैसे शुरू किया है ");
        map.put("How  have I bound ", "मैंने कैसे बाध्य किया है ");
        map.put("How  have I bitten ", "मैंने कैसे काट लिया है ");
        map.put("How  have I blessed ", "मैंने कैसे आशीर्वाद दिया है ");
        map.put("How  have I blown ", "मैंने कैसे उड़ा दिया है ");
        map.put("How  have I broken ", "मैं कैसे टूट गया ");
        map.put("How  have I brought ", "मैं कैसे लाया हूँ ");
        map.put("How  have I built ", "मैंने कैसे बनाया है ");
        map.put("How  have I burnt ", "मैंने कैसे जलाया है ");
        map.put("How  have I bought ", "मैंने कैसे खरीदा है ");
        map.put("How  have I called ", "मैंने कैसे कॉल किया है ");
        map.put("How  have I carried ", "मैंने कैसे किया है ");
        map.put("How  have I caught ", "मैंने कैसे पकड़ा है ");
        map.put("How  have I cheated ", "मैंने कैसे धोखा दिया है ");
        map.put("How  have I chosen ", "मैंने कैसे चुना है ");
        map.put("How  have I cleaned ", "मैंने कैसे साफ किया है ");
        map.put("How  have I climbed ", "मैं कैसे चढ़ गया ");
        map.put("How  have I closed ", "मैंने कैसे बंद किया है ");
        map.put("How  have I come ", "मैं कैसे आया हूँ ");
        map.put("How  have I cooked ", "मैंने कैसे पकाया है ");
        map.put("How  have I crept ", "मैंने कैसे क्रेप किया है ");
        map.put("How  have I cried ", "मैं कैसे रोया हूँ ");
        map.put("How  have I cut ", "मैंने कैसे कट किया है ");
        map.put("How  have I danced ", "मैंने कैसे नृत्य किया है ");
        map.put("How  have I dealt ", "मैंने कैसे निपटा है ");
        map.put("How  have I died ", "मैं कैसे मर गया ");
        map.put("How  have I dug ", "मैंने कैसे खोदा है ");
        map.put("How  have I done ", "मैंने कैसे किया ");
        map.put("How  have I drawn ", "मैंने कैसे खींचा है ");
        map.put("How  have I drunk ", "मैंने कैसे पिया है ");
        map.put("How  have I driven ", "मैंने कैसे चलाया है ");
        map.put("How  have I dropped ", "मैंने कैसे गिरा दिया है ");
        map.put("How  have I dried ", "मैं कैसे सूख गया ");
        map.put("How  have I eaten ", "मैंने कैसे खाया है ");
        map.put("How  have I elected ", "मैंने कैसे चुना है ");
        map.put("How  have I entered ", "मैंने कैसे प्रवेश किया ");
        map.put("How  have I fallen ", "मैं कैसे गिर गया ");
        map.put("How  have I fed ", "मैंने कैसे खिलाया है ");
        map.put("How  have I felt ", "मैंने कैसा महसूस किया है ");
        map.put("How  have I fought ", "मैंने कैसे लड़ाई लड़ी है ");
        map.put("How  have I found ", "मैंने कैसे पाया ");
        map.put("How  have I fled ", "मैं कैसे भाग गया ");
        map.put("How  have I flown ", "मैं कैसे उड़ गया ");
        map.put("How  have I forgotten ", "मैं कैसे भूल गया ");
        map.put("How  have I fried ", "मैंने कैसे तला है ");
        map.put("How  have I got ", "मुझे कैसे मिला ");
        map.put("How  have I given ", "मैंने कैसे दिया है ");
        map.put("How  have I gone ", "मैं कैसे गया ");
        map.put("How  have I grown ", "मैं कैसे बड़ा हो गया हूँ ");
        map.put("How  have I hanged ", "मैंने कैसे फांसी लगा ली है ");
        map.put("How  have I hung ", "मैंने कैसे लटका दिया है ");
        map.put("How  have I heard ", "मैंने कैसे सुना ");
        map.put("How  have I helped ", "मैंने कैसे मदद की है ");
        map.put("How  have I hidden ", "मैंने कैसे छिपाया है ");
        map.put("How  have I hit ", "मैंने कैसे मारा है ");
        map.put("How  have I held ", "मैंने कैसे आयोजित किया है ");
        map.put("How  have I hoped ", "मैंने कैसे आशा की है ");
        map.put("How  have I hurt ", "मैंने कैसे चोट पहुंचाई है ");
        map.put("How  have I jumped ", "मैं कैसे कूद गया हूँ ");
        map.put("How  have I kept ", "मैंने कैसे रखा है ");
        map.put("How  have I killed ", "मैंने कैसे मार डाला है ");
        map.put("How  have I known ", "मुझे कैसे पता है ");
        map.put("How  have I laughed ", "मैं कैसे हँसा हूँ ");
        map.put("How  have I led ", "मैंने कैसे नेतृत्व किया है ");
        map.put("How  have I leapt ", "मैंने कैसे छलांग लगाई है ");
        map.put("How  have I learnt ", "मैंने कैसे सीखा ");
        map.put("How  have I left ", "मैंने कैसे छोड़ा है ");
        map.put("How  have I lent ", "मैंने कैसे उधार दिया है ");
        map.put("How  have I lived ", "मैं कैसे रहता हूँ ");
        map.put("How  have I looked ", "मैंने कैसे देखा है ");
        map.put("How  have I lost ", "मैं कैसे हार गया हूँ ");
        map.put("How  have I loved ", "मैंने कैसे प्यार किया ");
        map.put("How  have I made ", "मैंने कैसे बनाया है ");
        map.put("How  have I married ", "मैंने शादी कैसे की ");
        map.put("How  have I met ", "मैं कैसे मिला हूँ ");
        map.put("How  have I mistaken ", "मैंने कैसे गलत किया है ");
        map.put("How  have I opened ", "मैंने कैसे खोला है ");
        map.put("How  have I paid ", "मैंने भुगतान कैसे किया है ");
        map.put("How  have I played ", "मैंने कैसे खेला है ");
        map.put("How  have I put ", "मैंने कैसे रखा है ");
        map.put("How  have I quarrelled ", "मैंने झगड़ा कैसे किया ");
        map.put("How  have I rained ", "मैंने बारिश कैसे की ");
        map.put("How  have I reached ", "मैं कैसे पहुँचा हूँ ");
        map.put("How  have I read ", "मैंने कैसे पढ़ा है ");
        map.put("How  have I remembered ", "मुझे कैसे याद आया ");
        map.put("How  have I ridden ", "मैंने कैसे सवारी की है ");
        map.put("How  have I rung ", "मैंने कैसे बजाया है ");
        map.put("How  have I risen ", "मैं कैसे उठ गया ");
        map.put("How  have I run ", "मैं कैसे चला सकता हूँ ");

        return map;
    }
    static Map<String,String> Four(){
        HashMap<String,String>map = new HashMap<>();
        map.put("How  have I been beating ", "मैं कैसे पिटाई कर रहा हूँ ");
        map.put("How  have I been abusing ", "मैं कैसे गाली दे रहा हूं ");
        map.put("How  have I been advising ", "मैं कैसे सलाह दे रहा हूं ");
        map.put("How  have I been answering ", "मैं कैसे जवाब दे रहा हूं ");
        map.put("How  have I been arising ", "मैं कैसे उठ रहा हूँ ");
        map.put("How  have I been arriving ", "मैं कैसे आ रहा हूँ ");
        map.put("How  have I been asking ", "मैं कैसे पूछ रहा हूँ ");
        map.put("How  have I been awaking ", "मैं कैसे जाग रहा हूँ ");
        map.put("How  have I been undefined", "मुझे अपरिभाषित कैसे किया गया है");
        map.put("How  have I been bearing ", "मैं कैसे असर कर रहा हूँ ");
        map.put("How  have I been becoming ", "मैं कैसे बन रहा हूँ ");
        map.put("How  have I been begging ", "मैं कैसे भीख माँग रहा हूँ ");
        map.put("How  have I been beginning ", "मैं कैसे शुरुआत कर रहा हूँ ");
        map.put("How  have I been binding ", "मैं बाइंडिंग कैसे कर रहा हूँ ");
        map.put("How  have I been biting ", "मैं कैसे काट रहा हूँ ");
        map.put("How  have I been blessing ", "मैं कैसे आशीष रहा हूँ ");
        map.put("How  have I been blowing ", "मैं कैसे उड़ रहा हूँ ");
        map.put("How  have I been breaking ", "मैं कैसे तोड़ रहा हूँ ");
        map.put("How  have I been bringing ", "मैं कैसे ला रहा हूँ ");
        map.put("How  have I been building ", "मैं कैसे निर्माण कर रहा हूँ ");
        map.put("How  have I been burning ", "मैं कैसे जल रहा हूँ ");
        map.put("How  have I been buying ", "मैं कैसे खरीद रहा हूँ ");
        map.put("How  have I been calling ", "मैं कैसे कॉल कर रहा हूँ ");
        map.put("How  have I been carrying ", "मैं कैसे ले जा रहा हूँ ");
        map.put("How  have I been catching ", "मैं कैसे पकड़ रहा हूँ ");
        map.put("How  have I been cheating ", "मैं कैसे धोखा दे रहा हूँ ");
        map.put("How  have I been choosing ", "मैं कैसे चुन रहा हूं ");
        map.put("How  have I been cleaning ", "मैं कैसे सफाई कर रहा हूँ ");
        map.put("How  have I been climbing ", "मैं कैसे चढ़ रहा हूँ ");
        map.put("How  have I been closing ", "मैं कैसे बंद कर रहा हूँ ");
        map.put("How  have I been coming ", "मैं कैसे आ रहा हूँ ");
        map.put("How  have I been cooking ", "मैं कैसे खाना बना रहा हूँ ");
        map.put("How  have I been creeping ", "मैं कैसे रेंग रहा हूँ ");
        map.put("How  have I been crying ", "मैं कैसे रो रहा हूँ ");
        map.put("How  have I been cutting ", "मैं कैसे काट रहा हूँ ");
        map.put("How  have I been dancing ", "मैं कैसे नाच रहा हूँ ");
        map.put("How  have I been dealing ", "मैं कैसे काम कर रहा हूं ");
        map.put("How  have I been dying ", "मैं कैसे मर रहा हूँ ");
        map.put("How  have I been digging ", "मैं कैसे खुदाई कर रहा हूँ ");
        map.put("How  have I been doing ", "मैं कैसे कर रहा हूँ ");
        map.put("How  have I been drawing ", "मैं कैसे ड्राइंग कर रहा हूं ");
        map.put("How  have I been drinking ", "मैं कैसे पी रहा हूँ ");
        map.put("How  have I been driving ", "मैं कैसे गाड़ी चला रहा हूँ ");
        map.put("How  have I been dropping ", "मैं कैसे गिर रहा हूँ ");
        map.put("How  have I been drying ", "मैं कैसे सूख रहा हूँ ");
        map.put("How  have I been eating ", "मैं कैसे खा रहा हूँ ");
        map.put("How  have I been electing ", "मैं कैसे चुनाव कर रहा हूँ ");
        map.put("How  have I been entering ", "मैं कैसे प्रवेश कर रहा हूँ ");
        map.put("How  have I been falling ", "मैं कैसे गिर रहा हूँ ");
        map.put("How  have I been feeding ", "मैं कैसे खिला रहा हूँ ");
        map.put("How  have I been feeling ", "मैं कैसा महसूस कर रहा हूँ ");
        map.put("How  have I been fighting ", "मैं कैसे लड़ रहा हूँ ");
        map.put("How  have I been finding ", "मैं कैसे खोज रहा हूं ");
        map.put("How  have I been fleeing ", "मैं कैसे भाग रहा हूँ ");
        map.put("How  have I been flying ", "मैं कैसे उड़ रहा हूँ ");
        map.put("How  have I been forgetting ", "मैं कैसे भूल रहा हूँ ");
        map.put("How  have I been frying ", "मैं कैसे तलने गया हूँ ");
        map.put("How  have I been getting ", "मुझे कैसे मिल रहा है ");
        map.put("How  have I been giving ", "मैं कैसे दे रहा हूँ ");
        map.put("How  have I been going ", "मैं कैसे जा रहा हूँ ");
        map.put("How  have I been growing ", "मैं कैसे बढ़ रहा हूँ ");
        map.put("How  have I been hanging ", "मैं कैसे लटक रहा हूँ ");
        map.put("How  have I been hearing ", "मैं कैसे सुन रहा हूँ ");
        map.put("How  have I been helping ", "मैं कैसे मदद कर रहा हूं ");
        map.put("How  have I been hiding ", "मैं कैसे छिपा रहा हूँ ");
        map.put("How  have I been hitting ", "मैं कैसे मार रहा हूँ ");
        map.put("How  have I been holding ", "मैं कैसे पकड़ रहा हूँ ");
        map.put("How  have I been hoping ", "मैं कैसे उम्मीद कर रहा था ");
        map.put("How  have I been hurting ", "मैं कैसे चोट पहुँचा रहा हूँ ");
        map.put("How  have I been jumping ", "मैं कैसे कूद रहा हूँ ");
        map.put("How  have I been keeping ", "मैं कैसे रख रहा हूँ ");
        map.put("How  have I been killing ", "मैं कैसे मार रहा हूँ ");
        map.put("How  have I been knowing ", "मैं कैसे जान रहा हूँ ");
        map.put("How  have I been laughing ", "मैं कैसे हँस रहा हूँ ");
        map.put("How  have I been leading ", "मैं कैसे नेतृत्व कर रहा हूं ");
        map.put("How  have I been leaping ", "मैं कैसे छलांग लगा रहा हूँ ");
        map.put("How  have I been learning ", "मैं कैसे सीख रहा हूँ ");
        map.put("How  have I been leaving ", "मैं कैसे जा रहा हूँ ");
        map.put("How  have I been lending ", "मैं कैसे उधार दे रहा हूँ ");
        map.put("How  have I been living ", "मैं कैसे रह रहा हूँ ");
        map.put("How  have I been looking ", "मैं कैसे देख रहा हूँ ");
        map.put("How  have I been losing ", "मैं कैसे हार रहा हूँ ");
        map.put("How  have I been loving ", "मैं कैसे प्यार कर रहा हूँ ");
        map.put("How  have I been making ", "मैं कैसे बना रहा हूँ ");
        map.put("How  have I been marrying ", "मैं शादी कैसे कर रहा हूँ ");
        map.put("How  have I been meeting ", "मैं कैसे मिल रहा हूँ ");
        map.put("How  have I been mistaking ", "मैं कैसे गलत कर रहा हूँ ");
        map.put("How  have I been opening ", "मैं कैसे खोल रहा हूँ ");
        map.put("How  have I been paying ", "मैं कैसे भुगतान कर रहा हूँ ");
        map.put("How  have I been playing ", "मैं कैसे खेल रहा हूँ ");
        map.put("How  have I been putting ", "मैं कैसे लगा रहा हूँ ");
        map.put("How  have I been quarrelling ", "मैं झगड़ा कैसे कर रहा हूँ ");
        map.put("How  have I been raining ", "बारिश कैसे हो रही है ");
        map.put("How  have I been reaching ", "मैं कैसे पहुँच रहा हूँ ");
        map.put("How  have I been reading ", "मैं कैसे पढ़ रहा हूँ ");
        map.put("How  have I been remembering ", "मुझे कैसे याद आ रहा है ");
        map.put("How  have I been riding ", "मैं कैसे सवारी कर रहा हूँ ");
        map.put("How  have I been ringing ", "मैं कैसे बज रहा हूँ ");
        map.put("How  have I been rising ", "मैं कैसे उठ रहा हूँ ");
        map.put("How  have I been running ", "मैं कैसे चल रहा हूँ ");

        return map;
    }
    static Map<String,String> Five(){
        HashMap<String,String>map = new HashMap<>();
        map.put("How  did I  abuse ", "मैंने गाली कैसे दी ");
        map.put("How  did I  advise", "मैंने कैसे सलाह दी");
        map.put("How  did I  answer ", "मैंने कैसे जवाब दिया ");
        map.put("How  did I  arise ", "मैं कैसे उठ गया ");
        map.put("How  did I  arrive ", "मैं कैसे आया ");
        map.put("How  did I  ask ", "मैंने कैसे पूछा ");
        map.put("How  did I  awake ", "मैं कैसे जाग गया ");

        map.put("How  did I  beat ", "मैंने कैसे हराया ");
        map.put("How  did I  become ", "मैं कैसे बन गया ");
        map.put("How  did I  beg ", "मैं कैसे भीख माँगती हूँ ");
        map.put("How  did I  begin ", "मैंने कैसे शुरू किया ");
        map.put("How  did I  bind ", "मैंने कैसे बाँध लिया ");
        map.put("How  did I  bite", "मैंने कैसे काट लिया");
        map.put("How  did I  bless", "मैंने कैसे आशीर्वाद दिया");
        map.put("How  did I  blow ", "मैंने कैसे उड़ा दिया ");
        map.put("How  did I  break ", "मैंने कैसे तोड़ा ");
        map.put("How  did I  bring ", "मैं कैसे लाया ");
        map.put("How  did I  build ", "मैंने कैसे बनाया ");
        map.put("How  did I  burn ", "मैंने कैसे जला दिया ");
        map.put("How  did I  buy ", "मैंने कैसे खरीदा ");
        map.put("How  did I  call ", "मैंने फोन कैसे किया ");
        map.put("How  did I  carry ", "मैं कैसे ले गया ");
        map.put("How  did I  catch ", "मैंने कैसे पकड़ लिया ");
        map.put("How  did I  cheat ", "मैंने धोखा कैसे दिया ");
        map.put("How  did I  choose ", "मैंने कैसे चुना ");
        map.put("How  did I  clean ", "मैंने कैसे साफ किया ");
        map.put("How  did I  climb  ", "मैं कैसे चढ़ गया  ");
        map.put("How  did I  close ", "मैंने कैसे बंद किया ");
        map.put("How  did I  come ", "मैं कैसे आया ");
        map.put("How  did I  cook ", "मैंने कैसे खाना बनाया ");
        map.put("How  did I  creep ", "मैं कैसे रेंगना था ");
        map.put("How  did I  cut ", "मैंने कैसे कट किया ");
        map.put("How  did I  dance ", "मैंने कैसे नृत्य किया ");
        map.put("How  did I  deal ", "मैंने कैसे सौदा किया ");
        map.put("How  did I  die ", "मैं कैसे मर गया ");
        map.put("How  did I  dig ", "मैंने कैसे खोदा ");
        map.put("How  did I  draw ", "मैंने कैसे आकर्षित किया ");
        map.put("How  did I  drive ", "मैंने ड्राइव कैसे किया ");
        map.put("How  did I  drop ", "मैंने कैसे छोड़ा ");
        map.put("How  did I  dry ", "मैंने कैसे सुखाया ");
        map.put("How  did I  eat ", "मैंने कैसे खाया ");
        map.put("How  did I  elect", "मैंने कैसे चुनाव किया");
        map.put("How  did I  enter ", "मैंने कैसे प्रवेश किया ");
        map.put("How  did I  fall ", "मैं कैसे गिर गया ");
        map.put("How  did I  feed ", "मैंने कैसे खाना खाया ");
        map.put("How  did I  feel  ", "मैंने कैसा महसूस किया  ");
        map.put("How  did I  fight ", "मैंने कैसे लड़ाई की ");
        map.put("How  did I  find ", "मुझे कैसे मिला ");
        map.put("How  did I  flee ", "मैं कैसे भाग गया ");
        map.put("How  did I  fly  ", "मैं कैसे उड़ गया  ");
        map.put("How  did I  fry ", "मैंने फ्राई कैसे किया ");
        map.put("How  did I  get  ", "मुझे कैसे मिला  ");
        map.put("How  did I  give ", "मैंने कैसे दिया ");
        map.put("How  did I  go ", "मैं कैसे गया ");
        map.put("How  did I  grow", "मैं कैसे विकसित हुआ");
        map.put("How  did I  hang ", "मैंने कैसे लटका दिया ");
        map.put("How  did I  hear ", "मैंने कैसे सुना ");
        map.put("How  did I  help ", "मैंने कैसे मदद की ");
        map.put("How  did I  hide ", "मैंने कैसे छिपाया ");
        map.put("How  did I  hit ", "मैंने कैसे मारा ");
        map.put("How  did I  hold ", "मैंने कैसे पकड़ लिया ");
        map.put("How  did I  hope ", "मुझे कैसे उम्मीद थी ");
        map.put("How  did I  hurt ", "मैंने कैसे चोट पहुंचाई ");
        map.put("How  did I  jump ", "मैं कैसे कूद गया ");
        map.put("How  did I  keep ", "मैंने कैसे रखा ");
        map.put("How  did I  kill ", "मैंने कैसे मार डाला ");
        map.put("How  did I  know ", "मुझे कैसे पता था ");
        map.put("How  did I  laugh ", "मैं कैसे हँसा ");
        map.put("How  did I  lead ", "मैंने नेतृत्व कैसे किया ");
        map.put("How  did I  leap ", "मैंने छलांग कैसे लगाई ");
        map.put("How  did I  learn ", "मैंने कैसे सीखा ");
        map.put("How  did I  leave ", "मैंने कैसे छोड़ा ");
        map.put("How  did I  live ", "मैं कैसे रहता था ");
        map.put("How  did I  look ", "मैं कैसे दिख रहा था ");
        map.put("How  did I  lose ", "मैं कैसे हार गया ");
        map.put("How  did I  love ", "मैं कैसे प्यार करता था ");
        map.put("How  did I  make ", "मैंने कैसे बनाया ");
        map.put("How  did I  marry ", "मैंने शादी कैसे की ");
        map.put("How  did I  meet ", "मैं कैसे मिला ");
        map.put("How  did I  mistake ", "मैंने गलती कैसे की ");
        map.put("How  did I  open ", "मैंने कैसे खोला ");
        map.put("How  did I  pay  ", "मैंने भुगतान कैसे किया  ");
        map.put("How  did I  play ", "मैंने कैसे खेला ");
        map.put("How  did I  put ", "मैंने कैसे रखा ");
        map.put("How  did I  quarrel ", "मैंने झगड़ा कैसे किया ");
        map.put("How  did I  rain ", "मैंने बारिश कैसे की ");
        map.put("How  did I  reach ", "मैं कैसे पहुँचा ");
        map.put("How  did I  read", "मैंने कैसे पढ़ा");
        map.put("How  did I  remember  ", "मुझे कैसे याद आया  ");
        map.put("How  did I  ride ", "मैंने सवारी कैसे की ");
        map.put("How  did I  ring ", "मैंने कैसे रिंग किया ");
        map.put("How  did I  rise  ", "मैं कैसे उठ गया  ");

        return map;
    }
    static Map<String,String> Six(){
        HashMap<String,String>map = new HashMap<>();
        map.put("How  was I  abusing ", "मैं कैसे गाली दे रहा था ");
        map.put("How  was I  advising ", "मैं कैसे सलाह दे रहा था ");
        map.put("How  was I  answering ", "मैं कैसे जवाब दे रहा था ");
        map.put("How  was I  arising ", "मैं कैसे उठ रहा था ");
        map.put("How  was I  arriving ", "मैं कैसे आ रहा था ");
        map.put("How  was I  asking ", "मैं कैसे पूछ रहा था ");
        map.put("How  was I  awaking ", "मैं कैसे जाग रहा था ");
        map.put("How  was I  undefined", "मैं अपरिभाषित कैसे था");
        map.put("How  was I  bearing ", "मैं कैसे असर कर रहा था ");
        map.put("How  was I  beating ", "मैं कैसे पिटाई कर रहा था ");
        map.put("How  was I  becoming ", "मैं कैसे बन रहा था ");
        map.put("How  was I  begging ", "मैं कैसे भीख माँग रहा था ");
        map.put("How  was I  beginning ", "मैं कैसे शुरू कर रहा था ");
        map.put("How  was I  binding ", "मैं कैसे बाध्यकारी था ");
        map.put("How  was I  biting ", "मैं कैसे काट रहा था ");
        map.put("How  was I  blessing ", "मैं कैसे आशीष दे रहा था ");
        map.put("How  was I  blowing ", "मैं कैसे उड़ रहा था ");
        map.put("How  was I  breaking ", "मैं कैसे तोड़ रहा था ");
        map.put("How  was I  bringing ", "मैं कैसे ला रहा था ");
        map.put("How  was I  building ", "मैं कैसे निर्माण कर रहा था ");
        map.put("How  was I  burning ", "मैं कैसे जल रहा था ");
        map.put("How  was I  buying ", "मैं कैसे खरीद रहा था ");
        map.put("How  was I  calling ", "मैं कैसे कॉल कर रहा था ");
        map.put("How  was I  carrying ", "मैं कैसे ले जा रहा था ");
        map.put("How  was I  catching ", "मैं कैसे पकड़ रहा था ");
        map.put("How  was I  cheating ", "मैं कैसे धोखा दे रहा था ");
        map.put("How  was I  choosing ", "मैं कैसे चुन रहा था ");
        map.put("How  was I  cleaning ", "मैं कैसे सफाई कर रहा था ");
        map.put("How  was I  climbing ", "मैं कैसे चढ़ रहा था ");
        map.put("How  was I  closing ", "मैं कैसे बंद कर रहा था ");
        map.put("How  was I  coming ", "मैं कैसे आ रहा था ");
        map.put("How  was I  cooking ", "मैं कैसे खाना बना रहा था ");
        map.put("How  was I  creeping ", "मैं कैसे रेंग रहा था ");
        map.put("How  was I  crying ", "मैं कैसे रो रहा था ");
        map.put("How  was I  cutting ", "मैं कैसे काट रहा था ");
        map.put("How  was I  dancing ", "मैं कैसे नाच रहा था ");
        map.put("How  was I  dealing ", "मैं कैसे काम कर रहा था ");
        map.put("How  was I  dying ", "मैं कैसे मर रहा था ");
        map.put("How  was I  digging ", "मैं कैसे खुदाई कर रहा था ");
        map.put("How  was I  drawing ", "मैं कैसे आकर्षित कर रहा था ");
        map.put("How  was I  drinking ", "मैं कैसे पी रहा था ");
        map.put("How  was I  driving ", "मैं कैसे चला रहा था ");
        map.put("How  was I  dropping ", "मैं कैसे गिर रहा था ");
        map.put("How  was I  drying ", "मैं कैसे सूख रहा था ");
        map.put("How  was I  eating ", "मैं कैसे खा रहा था ");
        map.put("How  was I  electing ", "मैं कैसे चुनाव कर रहा था ");
        map.put("How  was I  entering ", "मैं कैसे प्रवेश कर रहा था ");
        map.put("How  was I  falling ", "मैं कैसे गिर रहा था ");
        map.put("How  was I  feeding ", "मैं कैसे खिला रहा था ");
        map.put("How  was I  feeling ", "मैं कैसा महसूस कर रहा था ");
        map.put("How  was I  fighting ", "मैं कैसे लड़ रहा था ");
        map.put("How  was I  finding ", "मैं कैसे खोज रहा था ");
        map.put("How  was I  fleeing ", "मैं कैसे भाग रहा था ");
        map.put("How  was I  flying ", "मैं कैसे उड़ रहा था ");
        map.put("How  was I  forgetting ", "मैं कैसे भूल रहा था ");
        map.put("How  was I  frying ", "मैं कैसे फ्राइंग कर रहा था ");
        map.put("How  was I  getting ", "मैं कैसे मिल रहा था ");
        map.put("How  was I  giving ", "मैं कैसे दे रहा था ");
        map.put("How  was I  going ", "मैं कैसे जा रहा था ");
        map.put("How  was I  growing ", "मैं कैसे बढ़ रहा था ");
        map.put("How  was I  hanging ", "मैं कैसे लटक रहा था ");
        map.put("How  was I  hearing ", "मैं कैसे सुन रहा था ");
        map.put("How  was I  helping ", "मैं कैसे मदद कर रहा था ");
        map.put("How  was I  hiding ", "मैं कैसे छिपा रहा था ");
        map.put("How  was I  hitting ", "मैं कैसे मार रहा था ");
        map.put("How  was I  holding ", "मैं कैसे पकड़ रहा था ");
        map.put("How  was I  hoping ", "मैं कैसे उम्मीद कर रहा था ");
        map.put("How  was I  hurting ", "मैं कैसे चोट पहुँचा रहा था ");
        map.put("How  was I  jumping ", "मैं कैसे कूद रहा था ");
        map.put("How  was I  keeping ", "मैं कैसे रख रहा था ");
        map.put("How  was I  killing ", "मैं कैसे मार रहा था ");
        map.put("How  was I  knowing ", "मैं कैसे जान रहा था ");
        map.put("How  was I  laughing ", "मैं कैसे हँस रहा था ");
        map.put("How  was I  leading ", "मैं कैसे नेतृत्व कर रहा था ");
        map.put("How  was I  leaping ", "मैं कैसे छलांग लगा रहा था ");
        map.put("How  was I  learning ", "मैं कैसे सीख रहा था ");
        map.put("How  was I  leaving ", "मैं कैसे जा रहा था ");
        map.put("How  was I  lending ", "मैं कैसे उधार दे रहा था ");
        map.put("How  was I  living ", "मैं कैसे रह रहा था ");
        map.put("How  was I  looking ", "मैं कैसे देख रहा था ");
        map.put("How  was I  losing ", "मैं कैसे हार रहा था ");
        map.put("How  was I  loving ", "मैं कैसे प्यार कर रहा था ");
        map.put("How  was I  making ", "मैं कैसे बना रहा था ");
        map.put("How  was I  marrying ", "मैं शादी कैसे कर रहा था ");
        map.put("How  was I  meeting ", "मैं कैसे मिल रहा था ");
        map.put("How  was I  mistaking ", "मैं कैसे गलत कर रहा था ");
        map.put("How  was I  opening ", "मैं कैसे खोल रहा था ");
        map.put("How  was I  paying ", "मैं कैसे भुगतान कर रहा था ");
        map.put("How  was I  playing ", "मैं कैसे खेल रहा था ");
        map.put("How  was I  putting ", "मैं कैसे डाल रहा था ");
        map.put("How  was I  quarrelling ", "मैं कैसे झगड़ा कर रहा था ");
        map.put("How  was I  raining ", "मैं बारिश कैसे कर रहा था ");
        map.put("How  was I  reaching ", "मैं कैसे पहुँच रहा था ");
        map.put("How  was I  reading ", "मैं कैसे पढ़ रहा था ");
        map.put("How  was I  remembering ", "मैं कैसे याद कर रहा था ");
        map.put("How  was I  riding ", "मैं कैसे सवारी कर रहा था ");
        map.put("How  was I  ringing ", "मैं कैसे बज रहा था ");
        map.put("How  was I  rising ", "मैं कैसे उठ रहा था ");
        map.put("How  was I  running ", "मैं कैसे चल रहा था ");

        return map;
    }
    static Map<String,String> Seven(){
        HashMap<String,String>map = new HashMap<>();
        map.put("How  had I  abused ", "मैंने कैसे गाली दी थी ");
        map.put("How  had I  advised ", "मैंने कैसे सलाह दी थी ");
        map.put("How  had I  answered ", "मैंने कैसे जवाब दिया था ");
        map.put("How  had I  arisen ", "मैं कैसे पैदा हुआ था ");
        map.put("How  had I  arrived ", "मैं कैसे आया था ");
        map.put("How  had I  asked ", "मैंने कैसे पूछा था ");
        map.put("How  had I  awoken ", "मैं कैसे जाग गया था ");
        map.put("How  had I  undefined", "मैंने अपरिभाषित कैसे किया था");
        map.put("How  had I  borne ", "मैंने कैसे जन्म लिया था ");
        map.put("How  had I  beaten ", "मैंने कैसे पीटा था ");
        map.put("How  had I  become ", "मैं कैसे बन गया था ");
        map.put("How  had I  begged ", "मैंने कैसे भीख माँगी थी ");
        map.put("How  had I  begun ", "मैंने कैसे शुरू किया था ");
        map.put("How  had I  bound ", "मैंने कैसे बाध्य किया था ");
        map.put("How  had I  bitten ", "मैंने कैसे काट लिया था ");
        map.put("How  had I  blessed ", "मैंने कैसे आशीर्वाद दिया था ");
        map.put("How  had I  blown ", "मैंने कैसे उड़ा दिया था ");
        map.put("How  had I  broken ", "मैं कैसे टूट गया था ");
        map.put("How  had I  brought ", "मैं कैसे लाया था ");
        map.put("How  had I  built ", "मैंने कैसे बनाया था ");
        map.put("How  had I  burnt ", "मैंने कैसे जलाया था ");
        map.put("How  had I  bought ", "मैंने कैसे खरीदा था ");
        map.put("How  had I  called ", "मैंने कैसे फोन किया था ");
        map.put("How  had I  carried ", "मैंने कैसे किया था ");
        map.put("How  had I  caught ", "मैंने कैसे पकड़ा था ");
        map.put("How  had I  cheated ", "मैंने कैसे धोखा दिया था ");
        map.put("How  had I  chosen ", "मैंने कैसे चुना था ");
        map.put("How  had I  cleaned ", "मैंने कैसे साफ किया था ");
        map.put("How  had I  climbed ", "मैं कैसे चढ़ गया था ");
        map.put("How  had I  closed ", "मैंने कैसे बंद किया था ");
        map.put("How  had I  come ", "मैं कैसे आया था ");
        map.put("How  had I  cooked ", "मैंने कैसे पकाया था ");
        map.put("How  had I  crept ", "मैंने कैसे क्रेप किया था ");
        map.put("How  had I  cried ", "मैं कैसे रोया था ");
        map.put("How  had I  cut ", "मैंने कैसे कट किया था ");
        map.put("How  had I  danced ", "मैंने कैसे नृत्य किया था ");
        map.put("How  had I  dealt ", "मैंने कैसे निपटा था ");
        map.put("How  had I  died ", "मैं कैसे मर गया था ");
        map.put("How  had I  dug ", "मैंने कैसे खोदा था ");
        map.put("How  had I  drawn ", "मैंने कैसे खींचा था ");
        map.put("How  had I  drunk ", "मैंने कैसे पिया था ");
        map.put("How  had I  driven ", "मैंने कैसे चलाया था ");
        map.put("How  had I  dropped ", "मैंने कैसे गिरा दिया था ");
        map.put("How  had I  dried ", "मैं कैसे सूख गया था ");
        map.put("How  had I  eaten ", "मैंने कैसे खाया था ");
        map.put("How  had I  elected ", "मैंने कैसे चुना था ");
        map.put("How  had I  entered ", "मैंने कैसे प्रवेश किया था ");
        map.put("How  had I  fallen ", "मैं कैसे गिर गया था ");
        map.put("How  had I  fed ", "मैंने कैसे खिलाया था ");
        map.put("How  had I  felt ", "मैंने कैसा महसूस किया था ");
        map.put("How  had I  fought ", "मैंने कैसे लड़ाई लड़ी थी ");
        map.put("How  had I  found ", "मुझे कैसे मिला था ");
        map.put("How  had I  fled ", "मैं कैसे भाग गया था ");
        map.put("How  had I  flown ", "मैं कैसे उड़ गया था ");
        map.put("How  had I  forgotten ", "मैं कैसे भूल गया था ");
        map.put("How  had I  fried ", "मैंने कैसे तला था ");
        map.put("How  had I  got ", "मुझे कैसे मिला था ");
        map.put("How  had I  given ", "मैंने कैसे दिया था ");
        map.put("How  had I  gone ", "मैं कैसे गया था ");
        map.put("How  had I  grown ", "मैं कैसे बड़ा हो गया था ");
        map.put("How  had I  hanged ", "मैंने फांसी कैसे लगाई थी ");
        map.put("How  had I  hung ", "मैंने कैसे लटका दिया था ");
        map.put("How  had I  heard ", "मैंने कैसे सुना था ");
        map.put("How  had I  helped ", "मैंने कैसे मदद की थी ");
        map.put("How  had I  hidden ", "मैंने कैसे छिपाया था ");
        map.put("How  had I  hit ", "मैंने कैसे मारा था ");
        map.put("How  had I  held ", "मैंने कैसे आयोजित किया था ");
        map.put("How  had I  hoped ", "मैंने कैसे आशा की थी ");
        map.put("How  had I  hurt ", "मुझे कैसे चोट लगी थी ");
        map.put("How  had I  jumped ", "मैं कैसे कूद गया था ");
        map.put("How  had I  kept ", "मैंने कैसे रखा था ");
        map.put("How  had I  killed ", "मैंने कैसे मारा था ");
        map.put("How  had I  known ", "मुझे कैसे पता था ");
        map.put("How  had I  laughed ", "मैं कैसे हँसा था ");
        map.put("How  had I  led ", "मैंने कैसे नेतृत्व किया था ");
        map.put("How  had I  leapt ", "मैंने कैसे छलांग लगाई थी ");
        map.put("How  had I  learnt ", "मैंने कैसे सीखा था ");
        map.put("How  had I  left ", "मैंने कैसे छोड़ा था ");
        map.put("How  had I  lent ", "मैंने कैसे उधार दिया था ");
        map.put("How  had I  lived ", "मैं कैसे रहता था ");
        map.put("How  had I  looked ", "मैंने कैसे देखा था ");
        map.put("How  had I  lost ", "मैं कैसे हार गया था ");
        map.put("How  had I  loved ", "मैं कैसे प्यार करता था ");
        map.put("How  had I  made ", "मैंने कैसे बनाया था ");
        map.put("How  had I  married ", "मैंने शादी कैसे की थी ");
        map.put("How  had I  met ", "मैं कैसे मिला था ");
        map.put("How  had I  mistaken ", "मैंने कैसे गलती की थी ");
        map.put("How  had I  opened ", "मैंने कैसे खोला था ");
        map.put("How  had I  paid ", "मैंने भुगतान कैसे किया था ");
        map.put("How  had I  played ", "मैंने कैसे खेला था ");
        map.put("How  had I  put ", "मैंने कैसे रखा था ");
        map.put("How  had I  quarrelled ", "मैंने झगड़ा कैसे किया था ");
        map.put("How  had I  rained ", "मैंने बारिश कैसे की थी ");
        map.put("How  had I  reached ", "मैं कैसे पहुँचा था ");
        map.put("How  had I  read ", "मैंने कैसे पढ़ा था ");
        map.put("How  had I  remembered ", "मुझे कैसे याद आया ");
        map.put("How  had I  ridden ", "मैंने कैसे सवारी की थी ");
        map.put("How  had I  rung ", "मैंने कैसे बजाया था ");
        map.put("How  had I  risen ", "मैं कैसे उठ गया था ");
        map.put("How  had I  run ", "मैं कैसे चला था ");

        return map;
    }
    static Map<String,String> Eight(){
        HashMap<String,String>map = new HashMap<>();
        map.put("How  had I been  abusing ", "मैं कैसे गाली दे रहा था ");
        map.put("How  had I been  advising ", "मैं कैसे सलाह दे रहा था ");
        map.put("How  had I been  answering ", "मैं कैसे जवाब दे रहा था ");
        map.put("How  had I been  arising ", "मैं कैसे उठ रहा था ");
        map.put("How  had I been  arriving ", "मैं कैसे आ रहा था ");
        map.put("How  had I been  asking ", "मैं कैसे पूछ रहा था ");
        map.put("How  had I been  awaking ", "मैं कैसे जाग रहा था ");
        map.put("How  had I been  undefined", "मैं अपरिभाषित कैसे हो गया था");
        map.put("How  had I been  bearing ", "मैं कैसे असर कर रहा था ");
        map.put("How  had I been  beating ", "मैं कैसे पिटाई कर रहा था ");
        map.put("How  had I been  becoming ", "मैं कैसे बन रहा था ");
        map.put("How  had I been  begging ", "मैं कैसे भीख माँग रहा था ");
        map.put("How  had I been  beginning ", "मैं कैसे शुरुआत कर रहा था ");
        map.put("How  had I been  binding ", "मैं बाध्यकारी कैसे था ");
        map.put("How  had I been  biting ", "मैं कैसे काट रहा था ");
        map.put("How  had I been  blessing ", "मैं कैसे आशीष रहा था ");
        map.put("How  had I been  blowing ", "मैं कैसे उड़ रहा था ");
        map.put("How  had I been  breaking ", "मैं कैसे तोड़ रहा था ");
        map.put("How  had I been  bringing ", "मैं कैसे ला रहा था ");
        map.put("How  had I been  building ", "मैं कैसे निर्माण कर रहा था ");
        map.put("How  had I been  burning ", "मैं कैसे जल रहा था ");
        map.put("How  had I been  buying ", "मैं कैसे खरीद रहा था ");
        map.put("How  had I been  calling ", "मैं कैसे कॉल कर रहा था ");
        map.put("How  had I been  carrying ", "मैं कैसे ले जा रहा था ");
        map.put("How  had I been  catching ", "मैं कैसे पकड़ रहा था ");
        map.put("How  had I been  cheating ", "मैं कैसे धोखा दे रहा था ");
        map.put("How  had I been  choosing ", "मैं कैसे चुन रहा था ");
        map.put("How  had I been  cleaning ", "मैं कैसे सफाई कर रहा था ");
        map.put("How  had I been  climbing ", "मैं कैसे चढ़ रहा था ");
        map.put("How  had I been  closing ", "मैं कैसे बंद कर रहा था ");
        map.put("How  had I been  coming ", "मैं कैसे आ रहा था ");
        map.put("How  had I been  cooking ", "मैं कैसे खाना बना रहा था ");
        map.put("How  had I been  creeping ", "मैं कैसे रेंग रहा था ");
        map.put("How  had I been  crying ", "मैं कैसे रो रहा था ");
        map.put("How  had I been  cutting ", "मैं कैसे काट रहा था ");
        map.put("How  had I been  dancing ", "मैं कैसे नाच रहा था ");
        map.put("How  had I been  dealing ", "मैं कैसे काम कर रहा था ");
        map.put("How  had I been  dying ", "मैं कैसे मर रहा था ");
        map.put("How  had I been  digging ", "मैं कैसे खुदाई कर रहा था ");
        map.put("How  had I been  drawing ", "मैं कैसे ड्राइंग कर रहा था ");
        map.put("How  had I been  drinking ", "मैं कैसे पी रहा था ");
        map.put("How  had I been  driving ", "मैं कैसे गाड़ी चला रहा था ");
        map.put("How  had I been  dropping ", "मैं कैसे गिर रहा था ");
        map.put("How  had I been  drying ", "मैं कैसे सूख रहा था ");
        map.put("How  had I been  eating ", "मैं कैसे खा रहा था ");
        map.put("How  had I been  electing ", "मैं कैसे चुनाव कर रहा था ");
        map.put("How  had I been  entering ", "मैं कैसे प्रवेश कर रहा था ");
        map.put("How  had I been  falling ", "मैं कैसे गिर रहा था ");
        map.put("How  had I been  feeding ", "मैं कैसे खिला रहा था ");
        map.put("How  had I been  feeling ", "मैं कैसा महसूस कर रहा था ");
        map.put("How  had I been  fighting ", "मैं कैसे लड़ रहा था ");
        map.put("How  had I been  finding ", "मैं कैसे खोज रहा था ");
        map.put("How  had I been  fleeing ", "मैं कैसे भाग रहा था ");
        map.put("How  had I been  flying ", "मैं कैसे उड़ रहा था ");
        map.put("How  had I been  forgetting ", "मैं कैसे भूल गया था ");
        map.put("How  had I been  frying ", "मैं कैसे तलने गया था ");
        map.put("How  had I been  getting ", "मुझे कैसे मिल रहा था ");
        map.put("How  had I been  giving ", "मैं कैसे दे रहा था ");
        map.put("How  had I been  going ", "मैं कैसे जा रहा था ");
        map.put("How  had I been  growing ", "मैं कैसे बढ़ रहा था ");
        map.put("How  had I been  hanging ", "मैं कैसे लटक रहा था ");
        map.put("How  had I been  hearing ", "मैं कैसे सुन रहा था ");
        map.put("How  had I been  helping ", "मैं कैसे मदद कर रहा था ");
        map.put("How  had I been  hiding ", "मैं कैसे छिपा रहा था ");
        map.put("How  had I been  hitting ", "मैं कैसे मार रहा था ");
        map.put("How  had I been  holding ", "मैं कैसे पकड़ रहा था ");
        map.put("How  had I been  hoping ", "मैं कैसे उम्मीद कर रहा था ");
        map.put("How  had I been  hurting ", "मैं कैसे चोट पहुँचा रहा था ");
        map.put("How  had I been  jumping ", "मैं कैसे कूद रहा था ");
        map.put("How  had I been  keeping ", "मैं कैसे रख रहा था ");
        map.put("How  had I been  killing ", "मैं कैसे मार रहा था ");
        map.put("How  had I been  knowing ", "मैं कैसे जान रहा था ");
        map.put("How  had I been  laughing ", "मैं कैसे हँस रहा था ");
        map.put("How  had I been  leading ", "मैं कैसे नेतृत्व कर रहा था ");
        map.put("How  had I been  leaping ", "मैं कैसे छलांग लगा रहा था ");
        map.put("How  had I been  learning ", "मैं कैसे सीख रहा था ");
        map.put("How  had I been  leaving ", "मैं कैसे जा रहा था ");
        map.put("How  had I been  lending ", "मैं कैसे उधार दे रहा था ");
        map.put("How  had I been  living ", "मैं कैसे रह रहा था ");
        map.put("How  had I been  looking ", "मैं कैसे देख रहा था ");
        map.put("How  had I been  losing ", "मैं कैसे हार रहा था ");
        map.put("How  had I been  loving ", "मैं कैसे प्यार कर रहा था ");
        map.put("How  had I been  making ", "मैं कैसे बना रहा था ");
        map.put("How  had I been  marrying ", "मैं शादी कैसे कर रहा था ");
        map.put("How  had I been  meeting ", "मैं कैसे मिल रहा था ");
        map.put("How  had I been  mistaking ", "मैं कैसे गलत कर रहा था ");
        map.put("How  had I been  opening ", "मैं कैसे खोल रहा था ");
        map.put("How  had I been  paying ", "मैं कैसे भुगतान कर रहा था ");
        map.put("How  had I been  playing ", "मैं कैसे खेल रहा था ");
        map.put("How  had I been  putting ", "मैं कैसे लगा रहा था ");
        map.put("How  had I been  quarrelling ", "मैं झगड़ा कैसे कर रहा था ");
        map.put("How  had I been  raining ", "मैं बारिश कैसे कर रहा था ");
        map.put("How  had I been  reaching ", "मैं कैसे पहुँच रहा था ");
        map.put("How  had I been  reading ", "मैं कैसे पढ़ रहा था ");
        map.put("How  had I been  remembering ", "मैं कैसे याद कर रहा था ");
        map.put("How  had I been  riding ", "मैं कैसे सवारी कर रहा था ");
        map.put("How  had I been  ringing ", "मैं कैसे बज रहा था ");
        map.put("How  had I been  rising ", "मैं कैसे उठ रहा था ");
        map.put("How  had I been  running ", "मैं कैसे दौड़ रहा था ");
        return map;
    }
    static Map<String,String> Nine(){
        HashMap<String,String>map = new HashMap<>();
        map.put("How  will I abuse ", "मैं कैसे गाली दूँगा ");
        map.put("How  will I advise", "मैं कैसे सलाह दूँगा");
        map.put("How  will I answer ", "मैं कैसे जवाब दूँगा ");
        map.put("How  will I arise ", "मैं कैसे उठूँगा ");
        map.put("How  will I arrive ", "मैं कैसे पहुँचूँगा ");
        map.put("How  will I ask ", "मैं कैसे पूछूँगा ");
        map.put("How  will I awake ", "मैं कैसे जाग जाऊंगा ");
        map.put("How  will I \r", "मैं कैसे करूँगा \r");
        map.put("How  will I be undefined", "मैं अपरिभाषित कैसे रहूँगा");
        map.put("How  will I bear ", "मैं कैसे सहन करूंगा ");
        map.put("How  will I beat ", "मैं कैसे हराऊंगा ");
        map.put("How  will I become ", "मैं कैसे बन जाऊंगा ");
        map.put("How  will I beg ", "मैं कैसे भीख माँगता हूँ ");
        map.put("How  will I begin ", "मैं कैसे शुरू करूँगा ");
        map.put("How  will I bind ", "मैं कैसे बाँध लूँगा ");
        map.put("How  will I bite", "मैं कैसे काटूंगा");
        map.put("How  will I bless", "मैं कैसे आशीष दूँगा");
        map.put("How  will I break ", "मैं कैसे टूटूंगा ");
        map.put("How  will I bring ", "मैं कैसे लाऊंगा ");
        map.put("How  will I build ", "मैं कैसे बनाउंगा ");
        map.put("How  will I burn ", "मैं कैसे जलाऊंगा ");
        map.put("How  will I buy ", "मैं कैसे खरीदूँगा ");
        map.put("How  will I call ", "मैं कैसे कॉल करूँगा ");
        map.put("How  will I carry ", "मैं कैसे ले जाऊंगा ");
        map.put("How  will I catch ", "मैं कैसे पकड़ूँगा ");
        map.put("How  will I cheat ", "मैं कैसे धोखा दूँगा ");
        map.put("How  will I choose ", "मैं कैसे चुनूंगा ");
        map.put("How  will I clean ", "मैं कैसे साफ करूँगा ");
        map.put("How  will I climb  ", "मैं कैसे चढ़ जाऊंगा  ");
        map.put("How  will I close ", "मैं कैसे बंद करूँगा ");
        map.put("How  will I come ", "मैं कैसे आऊँगा ");
        map.put("How  will I cook ", "मैं कैसे पकाऊंगा ");
        map.put("How  will I creep ", "मैं कैसे रेंगूँगा ");
        map.put("How  will I cry ", "मैं कैसे रोऊंगा ");
        map.put("How  will I cut ", "मैं कैसे काटूंगा ");
        map.put("How  will I dance ", "मैं कैसे नृत्य करूँगा ");
        map.put("How  will I deal ", "मैं कैसे निपटूंगा ");
        map.put("How  will I die ", "मैं कैसे मरूंगा ");
        map.put("How  will I dig ", "मैं कैसे खोदूँगा ");
        map.put("How  will I draw ", "मैं कैसे आकर्षित करूँगा ");
        map.put("How  will I drive ", "मैं कैसे चलाऊंगा ");
        map.put("How  will I drop ", "मैं कैसे छोड़ूँगा ");
        map.put("How  will I dry ", "मैं कैसे सुखाऊंगा ");
        map.put("How  will I eat ", "मैं कैसे खाऊंगा ");
        map.put("How  will I elect", "मैं कैसे चुनाव करूंगा");
        map.put("How  will I enter ", "मैं कैसे प्रवेश करूँगा ");
        map.put("How  will I fall ", "मैं कैसे गिरूंगा ");
        map.put("How  will I feed ", "मैं कैसे खिलाऊंगा ");
        map.put("How  will I feel  ", "मैं कैसा महसूस करूँगा  ");
        map.put("How  will I fight ", "मैं कैसे लड़ूंगा ");
        map.put("How  will I find ", "मुझे कैसे मिलेगा ");
        map.put("How  will I flee ", "मैं कैसे भागोंगा ");
        map.put("How  will I fly  ", "मैं कैसे उड़ूँगा  ");
        map.put("How  will I forget ", "मैं कैसे भूल जाऊंगा ");
        map.put("How  will I fry ", "मैं कैसे भूनूंगा ");
        map.put("How  will I get  ", "मुझे कैसे मिलेगा  ");
        map.put("How  will I give ", "मैं कैसे दूँगा ");
        map.put("How  will I go ", "मैं कैसे जाऊँगा ");
        map.put("How  will I grow", "मैं कैसे बढ़ूंगा");
        map.put("How  will I hang ", "मैं कैसे लटकाऊंगा ");
        map.put("How  will I hear ", "मैं कैसे सुनूंगा ");
        map.put("How  will I help ", "मैं कैसे मदद करूँगा ");
        map.put("How  will I hide ", "मैं कैसे छिपाऊंगा ");
        map.put("How  will I hit ", "मैं कैसे मारूंगा ");
        map.put("How  will I hold ", "मैं कैसे पकड़ लूंगा ");
        map.put("How  will I hope ", "मैं कैसे आशा करूँगा ");
        map.put("How  will I hurt ", "मैं कैसे चोट पहुँचूँगा ");
        map.put("How  will I keep ", "मैं कैसे रखूँगा ");
        map.put("How  will I jump ", "मैं कैसे कूदूँगा ");
        map.put("How  will I kill ", "मैं कैसे मारूंगा ");
        map.put("How  will I know ", "मुझे कैसे पता चलेगा ");
        map.put("How  will I laugh ", "मैं कैसे हंसूंगा ");
        map.put("How  will I lead ", "मैं कैसे नेतृत्व करूंगा ");
        map.put("How  will I leap ", "मैं कैसे छलांग लगाऊंगा ");
        map.put("How  will I learn ", "मैं कैसे सीखूंगा ");
        map.put("How  will I leave ", "मैं कैसे छोड़ूँगा ");
        map.put("How  will I lend ", "मैं कैसे उधार दूँगा ");
        map.put("How  will I live ", "मैं कैसे रहूँगा ");
        map.put("How  will I look ", "मैं कैसे देखूँगा ");
        map.put("How  will I lose ", "मैं कैसे हारूंगा ");
        map.put("How  will I make ", "मैं कैसे बनाऊँगा ");
        map.put("How  will I marry ", "मैं शादी कैसे करूँगा ");
        map.put("How  will I meet ", "मैं कैसे मिलूंगा ");
        map.put("How  will I mistake ", "मैं कैसे गलती करूँगा ");
        map.put("How  will I open ", "मैं कैसे खोलूंगा ");
        map.put("How  will I pay  ", "मैं कैसे भुगतान करूँगा  ");
        map.put("How  will I play ", "मैं कैसे खेलूंगा ");
        map.put("How  will I put ", "मैं कैसे रखूँगा ");
        map.put("How  will I quarrel ", "मैं झगड़ा कैसे करूँगा ");
        map.put("How  will I rain ", "मैं बारिश कैसे करूँगा ");
        map.put("How  will I reach ", "मैं कैसे पहुँचूँगा ");
        map.put("How  will I read", "मैं कैसे पढ़ूँगा");
        map.put("How  will I remember  ", "मैं कैसे याद रखूँगा  ");
        map.put("How  will I ride ", "मैं कैसे सवारी करूँगा ");
        map.put("How  will I ring ", "मैं कैसे रिंग करूंगा ");
        map.put("How  will I rise  ", "मैं कैसे उठूंगा  ");
        map.put("How  will I run  ", "मैं कैसे दौड़ूँगा  ");

        return map;
    }
    static Map<String,String> Ten(){
        HashMap<String,String>map = new HashMap<>();
        map.put("How  will I be abusing ", "मैं कैसे गाली दे रहा हूँ ");
        map.put("How  will I be advising ", "मैं कैसे सलाह दूँगा ");
        map.put("How  will I be answering ", "मैं कैसे जवाब दूंगा ");
        map.put("How  will I be arising ", "मैं कैसे उठ रहा हूँ ");
        map.put("How  will I be arriving ", "मैं कैसे पहुँचूँगा ");
        map.put("How  will I be asking ", "मैं कैसे पूछूँगा ");
        map.put("How  will I be awaking ", "मैं कैसे जाग जाऊंगा ");
        map.put("How  will I be bearing ", "मैं कैसे असर करूंगा ");
        map.put("How  will I be beating ", "मैं कैसे पिटाई करूँगा ");
        map.put("How  will I be becoming ", "मैं कैसे बन जाऊंगा ");
        map.put("How  will I be begging ", "मैं कैसे भीख माँगता हूँ ");
        map.put("How  will I be beginning ", "मैं कैसे शुरुआत करूँगा ");
        map.put("How  will I be binding ", "मैं बाध्यकारी कैसे रहूँगा ");
        map.put("How  will I be biting ", "मैं कैसे काट रहा हूँ ");
        map.put("How  will I be blessing ", "मैं आशीष कैसे रहूँगा ");
        map.put("How  will I be blowing ", "मैं कैसे उड़ा रहा हूँ ");
        map.put("How  will I be breaking ", "मैं कैसे टूट जाऊंगा ");
        map.put("How  will I be bringing ", "मैं कैसे लाऊंगा ");
        map.put("How  will I be building ", "मैं कैसे निर्माण करूंगा ");
        map.put("How  will I be burning ", "मैं कैसे जल रहा हूँ ");
        map.put("How  will I be buying ", "मैं कैसे खरीदूंगा ");
        map.put("How  will I be calling ", "मैं कैसे कॉल करूँगा ");
        map.put("How  will I be carrying ", "मैं कैसे ले जाऊंगा ");
        map.put("How  will I be catching ", "मैं कैसे पकड़ लूंगा ");
        map.put("How  will I be cheating ", "मैं धोखा कैसे दूँगा ");
        map.put("How  will I be choosing ", "मैं कैसे चुनूंगा ");
        map.put("How  will I be cleaning ", "मैं सफाई कैसे करूँगा ");
        map.put("How  will I be climbing ", "मैं कैसे चढ़ जाऊंगा ");
        map.put("How  will I be closing ", "मैं कैसे बंद हो जाऊंगा ");
        map.put("How  will I be coming ", "मैं कैसे आऊंगा ");
        map.put("How  will I be cooking ", "मैं कैसे खाना बना रहा हूँ ");
        map.put("How  will I be creeping ", "मैं कैसे रेंगूँगा ");
        map.put("How  will I be crying ", "मैं कैसे रो रहा हूँ ");
        map.put("How  will I be cutting ", "मैं कैसे काटूंगा ");
        map.put("How  will I be dancing ", "मैं कैसे नाचता रहूँगा ");
        map.put("How  will I be dealing ", "मैं कैसे निपटूंगा ");
        map.put("How  will I be dying ", "मैं कैसे मर जाऊंगा ");
        map.put("How  will I be digging ", "मैं कैसे खुदाई करूँगा ");
        map.put("How  will I be drawing ", "मैं कैसे ड्राइंग करूँगा ");
        map.put("How  will I be drinking ", "मैं कैसे पी रहा हूँ ");
        map.put("How  will I be driving ", "मैं कैसे चला रहा हूँ ");
        map.put("How  will I be dropping ", "मैं कैसे छोड़ रहा हूँ ");
        map.put("How  will I be drying ", "मैं कैसे सूख जाऊंगा ");
        map.put("How  will I be eating ", "मैं कैसे खाऊंगा ");
        map.put("How  will I be electing ", "मैं कैसे चुनाव करूंगा ");
        map.put("How  will I be entering ", "मैं कैसे प्रवेश करूँगा ");
        map.put("How  will I be falling ", "मैं कैसे गिर रहा हूँ ");
        map.put("How  will I be feeding ", "मैं कैसे खिलाऊंगा ");
        map.put("How  will I be feeling ", "मैं कैसा महसूस कर रहा हूँ ");
        map.put("How  will I be fighting ", "मैं कैसे लड़ूंगा ");
        map.put("How  will I be finding ", "मैं कैसे खोजूंगा ");
        map.put("How  will I be fleeing ", "मैं कैसे भाग जाऊंगा ");
        map.put("How  will I be flying ", "मैं कैसे उड़ूंगा ");
        map.put("How  will I be forgetting ", "मैं कैसे भूल जाऊंगा ");
        map.put("How  will I be frying ", "मैं कैसे तलने जाऊंगा ");
        map.put("How  will I be getting ", "मुझे कैसे मिल रहा होगा ");
        map.put("How  will I be giving ", "मैं कैसे दे रहा हूँ ");
        map.put("How  will I be going ", "मैं कैसे जाऊंगा ");
        map.put("How  will I be growing ", "मैं कैसे बढ़ रहा हूँ ");
        map.put("How  will I be hanging ", "मैं कैसे लटकाऊंगा ");
        map.put("How  will I be hearing ", "मैं कैसे सुन रहा हूँ ");
        map.put("How  will I be helping ", "मैं कैसे मदद करूँगा ");
        map.put("How  will I be hiding ", "मैं कैसे छिपाऊंगा ");
        map.put("How  will I be hitting ", "मैं कैसे मार रहा हूँ ");
        map.put("How  will I be holding ", "मैं कैसे पकड़ लूंगा ");
        map.put("How  will I be hoping ", "मैं कैसे उम्मीद कर रहा हूँ ");
        map.put("How  will I be hurting ", "मैं कैसे चोट पहुँचाऊंगा ");
        map.put("How  will I be jumping ", "मैं कैसे कूद जाऊंगा ");
        map.put("How  will I be keeping ", "मैं कैसे रखूँगा ");
        map.put("How  will I be killing ", "मैं कैसे मार रहा हूँ ");
        map.put("How  will I be knowing ", "मुझे कैसे पता चलेगा ");
        map.put("How  will I be laughing ", "मैं कैसे हँस रहा हूँ ");
        map.put("How  will I be leading ", "मैं कैसे अग्रणी रहूंगा ");
        map.put("How  will I be leaping ", "मैं कैसे छलांग लगाऊंगा ");
        map.put("How  will I be learning ", "मैं कैसे सीख रहा हूँ ");
        map.put("How  will I be leaving ", "मैं कैसे छोड़ूँगा ");
        map.put("How  will I be lending ", "मैं कैसे उधार दे रहा हूँ ");
        map.put("How  will I be living ", "मैं कैसे रहूँगा ");
        map.put("How  will I be looking ", "मैं कैसे देख रहा हूँ ");
        map.put("How  will I be losing ", "मैं कैसे हारूंगा ");
        map.put("How  will I be loving ", "मैं कैसे प्यार करूंगा ");
        map.put("How  will I be making ", "मैं कैसे बना रहा हूँ ");
        map.put("How  will I be marrying ", "मैं शादी कैसे करूँगा ");
        map.put("How  will I be meeting ", "मैं कैसे मिल रहा हूँ ");
        map.put("How  will I be mistaking ", "मैं कैसे गलत हो जाऊंगा ");
        map.put("How  will I be opening ", "मैं कैसे खोलूंगा ");
        map.put("How  will I be paying ", "मैं कैसे भुगतान करूँगा ");
        map.put("How  will I be playing ", "मैं कैसे खेलूंगा ");
        map.put("How  will I be putting ", "मैं कैसे डालूंगा ");
        map.put("How  will I be quarrelling ", "मैं झगड़ा कैसे करूँगा ");
        map.put("How  will I be raining ", "मैं बारिश कैसे करूँगा ");
        map.put("How  will I be reaching ", "मैं कैसे पहुँचूँगा ");
        map.put("How  will I be reading ", "मैं कैसे पढ़ूँगा ");
        map.put("How  will I be remembering ", "मैं कैसे याद रखूँगा ");
        map.put("How  will I be riding ", "मैं कैसे सवारी करूँगा ");
        map.put("How  will I be ringing ", "मैं कैसे बज रहा हूँ ");
        map.put("How  will I be rising ", "मैं कैसे उठ रहा हूँ ");
        map.put("How  will I be running ", "मैं कैसे दौड़ूंगा ");

        return map;
    }
    static Map<String,String> Eleven(){
        HashMap<String,String>map = new HashMap<>();
        map.put("How  will I have abused ", "मैं कैसे गाली दूँगा ");
        map.put("How  will I have advised ", "मैंने कैसे सलाह दी होगी ");
        map.put("How  will I have answered ", "मैंने कैसे जवाब दिया होगा ");
        map.put("How  will I have arisen ", "मैं कैसे उठ जाऊंगा ");
        map.put("How  will I have arrived ", "मैं कैसे पहुँचूँगा ");
        map.put("How  will I have asked ", "मैंने कैसे पूछा होगा ");
        map.put("How  will I have awoken ", "मैं कैसे जाग जाऊंगा ");
        map.put("How  will I have undefined", "मैं अपरिभाषित कैसे होऊंगा");
        map.put("How  will I have borne ", "मैं कैसे पैदा होऊंगा ");
        map.put("How  will I have beaten ", "मैं कैसे पीटा जाऊंगा ");
        map.put("How  will I have become ", "मैं कैसे बन जाऊंगा ");
        map.put("How  will I have begged ", "मैं कैसे भीख माँगता हूँ ");
        map.put("How  will I have begun ", "मैं कैसे शुरू करूँगा ");
        map.put("How  will I have bound ", "मैं कैसे बाध्य होऊंगा ");
        map.put("How  will I have bitten ", "मैंने कैसे काट लिया होगा ");
        map.put("How  will I have blessed ", "मैं कैसे आशीष पाऊंगा ");
        map.put("How  will I have blown ", "मैं कैसे उड़ा जाऊंगा ");
        map.put("How  will I have broken ", "मैं कैसे टूट जाऊंगा ");
        map.put("How  will I have brought ", "मैं कैसे लाऊंगा ");
        map.put("How  will I have built ", "मैंने कैसे बनाया होगा ");
        map.put("How  will I have burnt ", "मैं कैसे जल जाऊंगा ");
        map.put("How  will I have bought ", "मैंने कैसे खरीदा होगा ");
        map.put("How  will I have called ", "मैंने कैसे कॉल किया होगा ");
        map.put("How  will I have carried ", "मैं कैसे ले जाऊंगा ");
        map.put("How  will I have caught ", "मैं कैसे पकड़ लूँगा ");
        map.put("How  will I have cheated ", "मैंने धोखा कैसे दिया होगा ");
        map.put("How  will I have chosen ", "मैंने कैसे चुना होगा ");
        map.put("How  will I have cleaned ", "मैं कैसे साफ करूँगा ");
        map.put("How  will I have climbed ", "मैं कैसे चढ़ जाऊंगा ");
        map.put("How  will I have closed ", "मैं कैसे बंद हो जाऊंगा ");
        map.put("How  will I have come ", "मैं कैसे आऊँगा ");
        map.put("How  will I have cooked ", "मैं कैसे पकाऊंगा ");
        map.put("How  will I have crept ", "मेरे पास crept कैसे होगा ");
        map.put("How  will I have cried ", "मैं कैसे रोया होगा ");
        map.put("How  will I have cut ", "मैं कैसे कट जाऊंगा ");
        map.put("How  will I have danced ", "मैं कैसे नृत्य करूँगा ");
        map.put("How  will I have dealt ", "मैं कैसे निपटूंगा ");
        map.put("How  will I have died ", "मैं कैसे मर जाऊंगा ");
        map.put("How  will I have dug ", "मैंने कैसे खोदा होगा ");
        map.put("How  will I have drawn ", "मैं कैसे ड्रॉ करूँगा ");
        map.put("How  will I have drunk ", "मैं कैसे नशे में हूँ ");
        map.put("How  will I have driven ", "मैं कैसे चलाऊंगा ");
        map.put("How  will I have dropped ", "मैं कैसे गिरा जाऊंगा ");
        map.put("How  will I have dried ", "मैं कैसे सूख जाऊंगा ");
        map.put("How  will I have eaten ", "मैंने कैसे खाया होगा ");
        map.put("How  will I have elected ", "मैं कैसे चुनूंगा ");
        map.put("How  will I have entered ", "मैं कैसे प्रवेश करूँगा ");
        map.put("How  will I have fallen ", "मैं कैसे गिर जाऊंगा ");
        map.put("How  will I have fed ", "मैंने कैसे खिलाया होगा ");
        map.put("How  will I have felt ", "मैंने कैसा महसूस किया होगा ");
        map.put("How  will I have fought ", "मैं कैसे लड़ा जाऊंगा ");
        map.put("How  will I have found ", "मुझे कैसे मिल जाएगा ");
        map.put("How  will I have fled ", "मैं कैसे भाग जाऊंगा ");
        map.put("How  will I have flown ", "मैं कैसे उड़ जाऊंगा ");
        map.put("How  will I have forgotten ", "मैं कैसे भूल जाऊंगा ");
        map.put("How  will I have fried ", "मैं कैसे फ्राई करूँगा ");
        map.put("How  will I have got ", "मुझे कैसे मिला होगा ");
        map.put("How  will I have given ", "मैंने कैसे दिया होगा ");
        map.put("How  will I have gone ", "मैं कैसे चला जाऊंगा ");
        map.put("How  will I have grown ", "मैं कैसे बड़ा हो जाऊंगा ");
        map.put("How  will I have hanged ", "मैं कैसे फांसी लगाऊंगा ");
        map.put("How  will I have hung ", "मैं कैसे लटकाऊंगा ");
        map.put("How  will I have heard ", "मैंने कैसे सुना होगा ");
        map.put("How  will I have helped ", "मैं कैसे मदद करूँगा ");
        map.put("How  will I have hidden ", "मैं कैसे छिपाऊंगा ");
        map.put("How  will I have hit ", "मैं कैसे मारा जाऊंगा ");
        map.put("How  will I have held ", "मैं कैसे आयोजित करूंगा ");
        map.put("How  will I have hoped ", "मैं कैसे उम्मीद करूंगा ");
        map.put("How  will I have hurt ", "मुझे कैसे चोट लगी होगी ");
        map.put("How  will I have jumped ", "मैं कैसे कूद जाऊंगा ");
        map.put("How  will I have kept ", "मैं कैसे रखूँगा ");
        map.put("How  will I have killed ", "मैं कैसे मार डालूंगा ");
        map.put("How  will I have known ", "मुझे कैसे पता चलेगा ");
        map.put("How  will I have laughed ", "मैं कैसे हँसा होगा ");
        map.put("How  will I have led ", "मैं कैसे नेतृत्व करूंगा ");
        map.put("How  will I have leapt ", "मैं कैसे छलांग लगाऊंगा ");
        map.put("How  will I have learnt ", "मैंने कैसे सीखा होगा ");
        map.put("How  will I have left ", "मैं कैसे छोड़ जाऊंगा ");
        map.put("How  will I have lent ", "मैं कैसे उधार दूंगा ");
        map.put("How  will I have lived ", "मैं कैसे रहूँगा ");
        map.put("How  will I have looked ", "मैंने कैसे देखा होगा ");
        map.put("How  will I have lost ", "मैं कैसे हार जाऊंगा ");
        map.put("How  will I have loved ", "मैं कैसे प्यार करूंगा ");
        map.put("How  will I have made ", "मैंने कैसे बनाया होगा ");
        map.put("How  will I have married ", "मैं शादी कैसे करूँगा ");
        map.put("How  will I have met ", "मैं कैसे मिलूँगा ");
        map.put("How  will I have mistaken ", "मेरी गलती कैसे होगी ");
        map.put("How  will I have opened ", "मैं कैसे खोलूंगा ");
        map.put("How  will I have paid ", "मैंने भुगतान कैसे किया होगा ");
        map.put("How  will I have played ", "मैं कैसे खेलूंगा ");
        map.put("How  will I have put ", "मैं कैसे रखूँगा ");
        map.put("How  will I have quarrelled ", "मैं झगड़ा कैसे करूँगा ");
        map.put("How  will I have rained ", "मैं बारिश कैसे करूँगा ");
        map.put("How  will I have reached ", "मैं कैसे पहुँचूँगा ");
        map.put("How  will I have read ", "मैं कैसे पढ़ूँगा ");
        map.put("How  will I have remembered ", "मुझे कैसे याद होगा ");
        map.put("How  will I have ridden ", "मैं कैसे सवार हो जाऊंगा ");
        map.put("How  will I have rung ", "मैं कैसे रुंगा ");
        map.put("How  will I have risen ", "मैं कैसे उठ जाऊंगा ");
        map.put("How  will I have run ", "मैं कैसे दौड़ूंगा ");

        return map;
    }
    static Map<String,String> Twelve(){
        HashMap<String,String>map = new HashMap<>();
        map.put("How  will I have been abusing ", "मैं कैसे गाली दे रहा हूँ ");
        map.put("How  will I have been advising ", "मैं कैसे सलाह दे रहा हूँ ");
        map.put("How  will I have been answering ", "मैं कैसे जवाब दे रहा हूँ ");
        map.put("How  will I have been arising ", "मैं कैसे उठ रहा हूँ ");
        map.put("How  will I have been arriving ", "मैं कैसे आ रहा हूँ ");
        map.put("How  will I have been asking ", "मैं कैसे पूछ रहा हूँ ");
        map.put("How  will I have been awaking ", "मैं कैसे जाग रहा हूँ ");
        map.put("How  will I have been undefined", "मैं अपरिभाषित कैसे हो जाऊंगा");
        map.put("How  will I have been bearing ", "मैं कैसे असर कर रहा हूँ ");
        map.put("How  will I have been beating ", "मैं कैसे पिटाई कर रहा हूँ ");
        map.put("How  will I have been becoming ", "मैं कैसे बन रहा हूँ ");
        map.put("How  will I have been begging ", "मैं भीख कैसे माँगता हूँ ");
        map.put("How  will I have been beginning ", "मैं कैसे शुरुआत कर रहा हूँ ");
        map.put("How  will I have been binding ", "मैं बाइंडिंग कैसे कर रहा हूँ ");
        map.put("How  will I have been biting ", "मैं कैसे काट रहा हूँ ");
        map.put("How  will I have been blessing ", "मैं कैसे आशीष रहा हूँ ");
        map.put("How  will I have been blowing ", "मैं कैसे उड़ रहा हूँ ");
        map.put("How  will I have been breaking ", "मैं कैसे टूट रहा हूँ ");
        map.put("How  will I have been bringing ", "मैं कैसे ला रहा हूँ ");
        map.put("How  will I have been building ", "मैं कैसे निर्माण कर रहा हूँ ");
        map.put("How  will I have been burning ", "मैं कैसे जल रहा हूँ ");
        map.put("How  will I have been buying ", "मैं कैसे खरीद रहा हूँ ");
        map.put("How  will I have been calling ", "मैं कैसे कॉल कर रहा हूँ ");
        map.put("How  will I have been carrying ", "मैं कैसे ले जाऊंगा ");
        map.put("How  will I have been catching ", "मैं कैसे पकड़ रहा हूँ ");
        map.put("How  will I have been cheating ", "मैं कैसे धोखा दे रहा हूँ ");
        map.put("How  will I have been choosing ", "मैं कैसे चुन रहा हूँ ");
        map.put("How  will I have been cleaning ", "मैं कैसे सफाई कर रहा हूँ ");
        map.put("How  will I have been climbing ", "मैं कैसे चढ़ रहा हूँ ");
        map.put("How  will I have been closing ", "मैं कैसे बंद हो रहा हूँ ");
        map.put("How  will I have been coming ", "मैं कैसे आ रहा हूँ ");
        map.put("How  will I have been cooking ", "मैं कैसे खाना बना रहा हूँ ");
        map.put("How  will I have been creeping ", "मैं कैसे रेंग रहा हूँ ");
        map.put("How  will I have been crying ", "मैं कैसे रो रहा हूँ ");
        map.put("How  will I have been cutting ", "मैं कैसे काट रहा हूँ ");
        map.put("How  will I have been dancing ", "मैं कैसे नाचता रहा हूँ ");
        map.put("How  will I have been dealing ", "मैं कैसे काम कर रहा हूँ ");
        map.put("How  will I have been dying ", "मैं कैसे मर रहा हूँ ");
        map.put("How  will I have been digging ", "मैं कैसे खुदाई कर रहा हूँ ");
        map.put("How  will I have been drawing ", "मैं कैसे ड्राइंग कर रहा हूँ ");
        map.put("How  will I have been drinking ", "मैं कैसे पी रहा हूँ ");
        map.put("How  will I have been driving ", "मैं कैसे गाड़ी चला रहा हूँ ");
        map.put("How  will I have been dropping ", "मैं कैसे गिर रहा हूँ ");
        map.put("How  will I have been drying ", "मैं कैसे सूख रहा हूँ ");
        map.put("How  will I have been eating ", "मैं कैसे खा रहा हूँ ");
        map.put("How  will I have been electing ", "मैं कैसे चुनाव कर रहा हूँ ");
        map.put("How  will I have been entering ", "मैं कैसे प्रवेश कर रहा हूँ ");
        map.put("How  will I have been falling ", "मैं कैसे गिर रहा हूँ ");
        map.put("How  will I have been feeding ", "मैं कैसे खिला रहा हूँ ");
        map.put("How  will I have been feeling ", "मैं कैसा महसूस कर रहा हूँ ");
        map.put("How  will I have been fighting ", "मैं कैसे लड़ रहा हूँ ");
        map.put("How  will I have been finding ", "मैं कैसे खोज रहा हूँ ");
        map.put("How  will I have been fleeing ", "मैं कैसे भाग रहा हूँ ");
        map.put("How  will I have been flying ", "मैं कैसे उड़ रहा हूँ ");
        map.put("How  will I have been forgetting ", "मैं कैसे भूल गया होता ");
        map.put("How  will I have been frying ", "मैं कैसे तलने गया होता ");
        map.put("How  will I have been getting ", "मुझे कैसे मिल रहा होगा ");
        map.put("How  will I have been giving ", "मैं कैसे दे रहा हूँ ");
        map.put("How  will I have been going ", "मैं कैसे जा रहा हूँ ");
        map.put("How  will I have been growing ", "मैं कैसे बढ़ रहा हूँ ");
        map.put("How  will I have been hanging ", "मैं कैसे लटक रहा हूँ ");
        map.put("How  will I have been hearing ", "मैं कैसे सुन रहा हूँ ");
        map.put("How  will I have been helping ", "मैं कैसे मदद कर रहा हूँ ");
        map.put("How  will I have been hiding ", "मैं कैसे छिपाऊंगा ");
        map.put("How  will I have been hitting ", "मैं कैसे मार रहा हूँ ");
        map.put("How  will I have been holding ", "मैं कैसे पकड़ रहा हूँ ");
        map.put("How  will I have been hoping ", "मैं कैसे उम्मीद कर रहा था ");
        map.put("How  will I have been hurting ", "मैं कैसे चोट पहुँचाऊंगा ");
        map.put("How  will I have been jumping ", "मैं कैसे कूद रहा हूँ ");
        map.put("How  will I have been keeping ", "मैं कैसे रखूँगा ");
        map.put("How  will I have been killing ", "मैं कैसे मार रहा हूँ ");
        map.put("How  will I have been knowing ", "मुझे कैसे पता चल रहा होगा ");
        map.put("How  will I have been laughing ", "मैं कैसे हँस रहा हूँ ");
        map.put("How  will I have been leading ", "मैं कैसे नेतृत्व कर रहा हूँ ");
        map.put("How  will I have been leaping ", "मैं कैसे छलांग लगा रहा हूँ ");
        map.put("How  will I have been learning ", "मैं कैसे सीख रहा हूँ ");
        map.put("How  will I have been leaving ", "मैं कैसे जा रहा हूँ ");
        map.put("How  will I have been lending ", "मैं कैसे उधार दे रहा हूँ ");
        map.put("How  will I have been living ", "मैं कैसे रह रहा हूँ ");
        map.put("How  will I have been looking ", "मैं कैसे देख रहा हूँ ");
        map.put("How  will I have been losing ", "मैं कैसे हार रहा हूँ ");
        map.put("How  will I have been loving ", "मैं कैसे प्यार कर रहा हूँ ");
        map.put("How  will I have been making ", "मैं कैसे बना रहा हूँ ");
        map.put("How  will I have been marrying ", "मैं शादी कैसे कर रहा हूँ ");
        map.put("How  will I have been meeting ", "मैं कैसे मिल रहा हूँ ");
        map.put("How  will I have been mistaking ", "मैं कैसे गलत कर रहा हूँ ");
        map.put("How  will I have been opening ", "मैं कैसे खुल रहा हूँ ");
        map.put("How  will I have been paying ", "मैं कैसे भुगतान कर रहा हूँ ");
        map.put("How  will I have been playing ", "मैं कैसे खेलूंगा ");
        map.put("How  will I have been putting ", "मैं कैसे डालूंगा ");
        map.put("How  will I have been quarrelling ", "मैं झगड़ा कैसे कर रहा हूँ ");
        map.put("How  will I have been raining ", "मैं बारिश कैसे कर रहा हूँ ");
        map.put("How  will I have been reaching ", "मैं कैसे पहुँच रहा हूँ ");
        map.put("How  will I have been reading ", "मैं कैसे पढ़ रहा हूँ ");
        map.put("How  will I have been remembering ", "मैं कैसे याद रखूँगा ");
        map.put("How  will I have been riding ", "मैं कैसे सवारी कर रहा हूँ ");
        map.put("How  will I have been ringing ", "मैं कैसे बज रहा हूँ ");
        map.put("How  will I have been rising ", "मैं कैसे उठ रहा हूँ ");
        map.put("How  will I have been running ", "मैं कैसे दौड़ रहा हूँ ");

        return map;
    }


}
