package com.shiviishiv7.helloenglish.QuestionSource;

import java.util.HashMap;
import java.util.Map;

public class QuestionType2 {
    public static Map<String,String> getData(int state){
        switch (state){
            case 1:return One();
            case 2:return Two();
            case 3:return Three();
            case 4:return Four();
            case 5:return Five();
            case 6:return Six();
            case 7:return Seven();
            case 8:return Eight();
            case 9:return Nine();
            case 10:return Ten();
            case 11:return Eleven();
            case 12:return Twelve();

            default:return One();
        }

    }
    private static Map<String, String> Twelve() {
        HashMap<String,String>map = new HashMap<>();
        map.put("Will I have been closing ", "  क्या मैं बंद हो रहा हूँ ");
        map.put("Will I have been coming ", "  क्या मैं आ रहा हूँ ");
        map.put("Will I have been cooking ", "  क्या मैं खाना बना रहा होता ");
        map.put("Will I have been creeping ", "  क्या मैं रेंग रहा होता ");
        map.put("Will I have been crying ", "  क्या मैं रो रहा होता ");
        map.put("Will I have been cutting ", "  क्या मैं काट रहा हूँ ");
        map.put("Will I have been abusing ", "  क्या मैं गाली दे रहा हूँ ");
        map.put("Will I have been dancing ", "  क्या मैं नाच रहा होता ");
        map.put("Will I have been dealing ", "  क्या मैं काम कर रहा हूँ ");
        map.put("Will I have been dying ", "  क्या मैं मर रहा हूँ ");
        map.put("Will I have been digging ", "  क्या मैं खुदाई कर रहा हूँ ");
        map.put("Will I have been drawing ", "  क्या मैं ड्राइंग कर रहा हूँ ");
        map.put("Will I have been drinking ", "  क्या मैं पी रहा होता ");
        map.put("Will I have been driving ", "  क्या मैं गाड़ी चला रहा होता ");
        map.put("Will I have been dropping ", "  क्या मैं गिर रहा हूँ ");
        map.put("Will I have been drying ", "  क्या मैं सूख रहा होगा ");
        map.put("Will I have been eating ", "  क्या मैं खा रहा होता ");
        map.put("Will I have been electing ", "  क्या मैं चुनाव कर रहा हूँ ");
        map.put("Will I have been advising ", "  क्या मैं सलाह दे रहा हूँ ");
        map.put("Will I have been undefined", "  क्या मुझे अपरिभाषित किया गया होगा");
        map.put("Will I have been entering ", "  क्या मैं प्रवेश कर रहा हूँ ");
        map.put("Will I have been falling ", "  क्या मैं गिर रहा हूँ ");
        map.put("Will I have been feeding ", "  क्या मैं खिला रहा हूँ ");
        map.put("Will I have been feeling ", "  क्या मैं महसूस कर रहा हूँ ");
        map.put("Will I have been fighting ", "  क्या मैं लड़ रहा होता ");
        map.put("Will I have been finding ", "  क्या मुझे मिल रहा होगा ");
        map.put("Will I have been fleeing ", "  क्या मैं भाग रहा होता ");
        map.put("Will I have been flying ", "  क्या मैं उड़ रहा हूँ ");
        map.put("Will I have been forgetting ", "  क्या मैं भूल गया होता ");
        map.put("Will I have been answering ", "  क्या मैं जवाब दे रहा हूँ ");
        map.put("Will I have been frying ", "  क्या मैं तलने गया होता ");
        map.put("Will I have been getting ", "  क्या मुझे मिल रहा होगा ");
        map.put("Will I have been giving ", "  क्या मैं दे रहा हूँ ");
        map.put("Will I have been going ", "  क्या मैं जा रहा हूँ ");
        map.put("Will I have been growing ", "  क्या मैं बढ़ रहा हूँ ");
        map.put("Will I have been hanging ", "  क्या मैं लटक रहा होता ");
        map.put("Will I have been hearing ", "  क्या मैं सुन रहा होता ");
        map.put("Will I have been helping ", "  क्या मैं मदद कर रहा हूँ ");
        map.put("Will I have been hiding ", "  क्या मैं छिपा रहा हूँ ");
        map.put("Will I have been hitting ", "  क्या मैं मार रहा हूँ ");
        map.put("Will I have been holding ", "  क्या मैं पकड़ रहा होगा ");
        map.put("Will I have been arising ", "  क्या मैं उठ रहा हूँ ");
        map.put("Will I have been hoping ", "  क्या मैं उम्मीद कर रहा था ");
        map.put("Will I have been hurting ", "  क्या मैं चोट पहुँचा रहा हूँ ");
        map.put("Will I have been jumping ", "  क्या मैं कूद रहा होगा ");
        map.put("Will I have been keeping ", "  क्या मैं रख रहा होता ");
        map.put("Will I have been killing ", "  क्या मैं मार रहा हूँ ");
        map.put("Will I have been knowing ", "  क्या मुझे पता चल गया होगा ");
        map.put("Will I have been laughing ", "  क्या मैं हँस रहा हूँ ");
        map.put("Will I have been leading ", "  क्या मैं अग्रणी रहा होगा ");
        map.put("Will I have been leaping ", "  क्या मैं छलांग लगा रहा हूँ ");
        map.put("Will I have been learning ", "  क्या मैं सीख रहा हूँ ");
        map.put("Will I have been leaving ", "  क्या मैं जा रहा हूँ ");
        map.put("Will I have been arriving ", "  क्या मैं आ रहा हूँ ");
        map.put("Will I have been lending ", "  क्या मैं उधार दे रहा हूँ ");
        map.put("Will I have been asking ", "  क्या मैं पूछ रहा हूँ ");
        map.put("Will I have been living ", "  क्या मैं जी रहा होता ");
        map.put("Will I have been looking ", "  क्या मैं देख रहा हूँ ");
        map.put("Will I have been losing ", "  क्या मैं हार गया होता ");
        map.put("Will I have been loving ", "  क्या मैं प्यार कर रहा हूँ ");
        map.put("Will I have been making ", "  क्या मैं बना रहा हूँ ");
        map.put("Will I have been awaking ", "  क्या मैं जाग रहा होता ");
        map.put("Will I have been marrying ", "  क्या मैं शादी कर रहा हूँ ");
        map.put("Will I have been meeting ", "  क्या मैं मिल रहा होता ");
        map.put("Will I have been mistaking ", "  क्या मैं गलती कर रहा हूँ ");
        map.put("Will I have been opening ", "  क्या मैं खोल रहा हूँ ");
        map.put("Will I have been paying ", "  क्या मैं भुगतान कर रहा हूँ ");
        map.put("Will I have been playing ", "  क्या मैं खेल रहा होता ");
        map.put("Will I have been putting ", "  क्या मैं डाल रहा होता ");
        map.put("Will I have been quarrelling ", "  क्या मैं झगड़ा कर रहा हूँ ");
        map.put("Will I have been raining ", "  क्या मेरी बारिश हो रही होगी ");
        map.put("Will I have been reaching ", "  क्या मैं पहुँच रहा हूँ ");
        map.put("Will I have been reading ", "  क्या मैं पढ़ रहा होता ");
        map.put("Will I have been bearing ", "  क्या मैं असर कर रहा हूँ ");
        map.put("Will I have been remembering ", "  क्या मुझे याद आ रहा होगा ");
        map.put("Will I have been riding ", "  क्या मैं सवारी कर रहा हूँ ");
        map.put("Will I have been ringing ", "  क्या मैं बज रहा हूँ ");
        map.put("Will I have been rising ", "  क्या मैं उठ रहा हूँ ");
        map.put("Will I have been running ", "  क्या मैं दौड़ रहा हूँ ");
        map.put("Will I have been beating ", "  क्या मैं पिटाई कर रहा हूँ ");
        map.put("Will I have been saying ", "  क्या मैं कह रहा होता ");
        map.put("Will I have been seeing ", "  क्या मैं देख रहा होता ");
        map.put("Will I have been selling ", "  क्या मैं बेच रहा हूँ ");
        map.put("Will I have been sending ", "  क्या मैं भेज रहा हूँ ");
        map.put("Will I have been becoming ", "  क्या मैं बन रहा हूँ ");
        map.put("Will I have been begging ", "  क्या मैं भीख माँग रहा हूँ ");
        map.put("Will I have been beginning ", "  क्या मैं शुरुआत कर रहा हूँ ");
        map.put("Will I have been binding ", "  क्या मैं बाध्यकारी रहा हूँ ");
        map.put("Will I have been biting ", "  क्या मैं काट रहा हूँ ");
        map.put("Will I have been blessing ", "  क्या मैं आशीष रहा होता ");
        map.put("Will I have been blowing ", "  क्या मैं उड़ रहा हूँ ");
        map.put("Will I have been breaking ", "  क्या मैं तोड़ रहा हूँ ");
        map.put("Will I have been bringing ", "  क्या मैं ला रहा हूँ ");
        map.put("Will I have been building ", "  क्या मैं निर्माण कर रहा हूँ ");
        map.put("Will I have been burning ", "  क्या मैं जल रहा हूँ ");
        map.put("Will I have been buying ", "  क्या मैं खरीद रहा हूँ ");
        map.put("Will I have been calling ", "  क्या मैं कॉल कर रहा हूँ ");
        map.put("Will I have been carrying ", "  क्या मैं ले जा रहा हूँ ");
        map.put("Will I have been catching ", "  क्या मैं पकड़ रहा हूँ ");
        map.put("Will I have been cheating ", "  क्या मैं धोखा दे रहा हूँ ");
        map.put("Will I have been choosing ", "  क्या मैं चुन रहा हूँ ");
        map.put("Will I have been cleaning ", "  क्या मैं सफाई कर रहा हूँ ");
        map.put("Will I have been climbing ", "  क्या मैं चढ़ रहा होता ");

        return map;
    }
    private static Map<String, String> Eleven() {
        HashMap<String,String>map = new HashMap<>();
        map.put("Will I have closed ", "  क्या मैंने बंद कर दिया होगा ");
        map.put("Will I have come ", "  क्या मैं आ गया हूँ ");
        map.put("Will I have cooked ", "  क्या मैंने पकाया होगा ");
        map.put("Will I have crept ", "  क्या मेरे पास क्रेप्ट होगा ");
        map.put("Will I have cried ", "  क्या मैं रोया होता ");
        map.put("Will I have cut ", "  क्या मैंने कट किया होगा ");
        map.put("Will I have abused ", "  क्या मैंने गाली दी होगी ");
        map.put("Will I have danced ", "  क्या मैंने नृत्य किया होगा ");
        map.put("Will I have dealt ", "  क्या मैंने निपटाया होगा ");
        map.put("Will I have died ", "  क्या मैं मर जाऊंगा ");
        map.put("Will I have dug ", "  क्या मैंने खोदा होगा ");
        map.put("Will I have drawn ", "  क्या मैंने ड्रॉ किया होगा ");
        map.put("Will I have drunk ", "  क्या मैं नशे में हूँ ");
        map.put("Will I have driven ", "  क्या मैंने ड्राइव किया होगा ");
        map.put("Will I have dropped ", "  क्या मैंने गिरा दिया होगा ");
        map.put("Will I have advised ", "  क्या मैंने सलाह दी होगी ");
        map.put("Will I have dried ", "  क्या मैं सूख जाऊंगा ");
        map.put("Will I have eaten ", "  क्या मैंने खा लिया होगा ");
        map.put("Will I have elected ", "  क्या मैं निर्वाचित हो जाऊंगा ");
        map.put("Will I have undefined", "  क्या मैं अपरिभाषित हो जाऊंगा");
        map.put("Will I have entered ", "  क्या मैं प्रवेश कर चुका हूँ ");
        map.put("Will I have fallen ", "  क्या मैं गिर जाऊंगा ");
        map.put("Will I have fed ", "  क्या मैंने खिलाया होगा ");
        map.put("Will I have felt ", "  क्या मैंने महसूस किया होगा ");
        map.put("Will I have fought ", "  क्या मैं लड़ा होता ");
        map.put("Will I have found ", "  क्या मुझे मिल गया होगा ");
        map.put("Will I have answered ", "  क्या मैंने जवाब दिया होगा ");
        map.put("Will I have fled ", "  क्या मैं भाग जाऊंगा ");
        map.put("Will I have flown ", "  क्या मैं उड़ जाऊंगा ");
        map.put("Will I have forgotten ", "  क्या मैं भूल जाऊंगा ");
        map.put("Will I have fried ", "  क्या मैंने फ्राई किया होगा ");
        map.put("Will I have got ", "  क्या मुझे मिल गया होगा ");
        map.put("Will I have given ", "  क्या मैंने दिया होगा ");
        map.put("Will I have gone ", "  क्या मैं चला जाऊंगा ");
        map.put("Will I have grown ", "  क्या मैं बड़ा हो जाऊंगा ");
        map.put("Will I have hanged ", "  क्या मैंने फांसी लगा ली होगी ");
        map.put("Will I have hung ", "  क्या मैंने लटका दिया होगा ");
        map.put("Will I have arisen ", "  क्या मैं उठ जाऊंगा ");
        map.put("Will I have heard ", "  क्या मैंने सुना होगा ");
        map.put("Will I have helped ", "  क्या मैंने मदद की होगी ");
        map.put("Will I have hidden ", "  क्या मैं छिपाऊंगा ");
        map.put("Will I have hit ", "  क्या मैंने मारा होगा ");
        map.put("Will I have held ", "  क्या मैंने आयोजित किया होगा ");
        map.put("Will I have hoped ", "  क्या मुझे उम्मीद होगी ");
        map.put("Will I have hurt ", "  क्या मुझे चोट लगी होगी ");
        map.put("Will I have kept ", "  क्या मैंने रखा होगा ");
        map.put("Will I have killed ", "  क्या मैंने मार डाला होगा ");
        map.put("Will I have known ", "  क्या मुझे पता होगा ");
        map.put("Will I have arrived ", "  क्या मैं आ गया हूँ ");
        map.put("Will I have laughed ", "  क्या मैं हँसा होगा ");
        map.put("Will I have led ", "  क्या मैंने नेतृत्व किया होगा ");
        map.put("Will I have leapt ", "  क्या मैंने छलांग लगाई होगी ");
        map.put("Will I have learnt ", "  क्या मैंने सीखा होगा ");
        map.put("Will I have left ", "  क्या मैंने छोड़ा होगा ");
        map.put("Will I have lent ", "  क्या मैंने उधार दिया होगा ");
        map.put("Will I have asked ", "  क्या मैंने पूछा होगा ");
        map.put("Will I have lived ", "  क्या मैं जीवित रहूंगा ");
        map.put("Will I have looked ", "  क्या मैंने देखा होगा ");
        map.put("Will I have lost ", "  क्या मैं हार जाऊंगा ");
        map.put("Will I have awoken ", "  क्या मैं जाग जाऊंगा ");
        map.put("Will I have loved ", "  क्या मैंने प्यार किया होगा ");
        map.put("Will I have made ", "  क्या मैंने बनाया होगा ");
        map.put("Will I have married ", "  क्या मैंने शादी कर ली होगी ");
        map.put("Will I have met ", "  क्या मैं मिल गया होता ");
        map.put("Will I have mistaken ", "  क्या मैंने गलत किया होगा ");
        map.put("Will I have opened ", "  क्या मैंने खोला होगा ");
        map.put("Will I have paid ", "  क्या मैंने भुगतान किया होगा ");
        map.put("Will I have played ", "  क्या मैंने खेला होगा ");
        map.put("Will I have put ", "  क्या मैंने रखा होगा ");
        map.put("Will I have quarrelled ", "  क्या मैंने झगड़ा किया होगा ");
        map.put("Will I have rained ", "  क्या मेरी बारिश होगी ");
        map.put("Will I have reached ", "  क्या मैं पहुँच जाऊंगा ");
        map.put("Will I have read ", "  क्या मैंने पढ़ा होगा ");
        map.put("Will I have borne ", "  क्या मैंने जन्म लिया होगा ");
        map.put("Will I have remembered ", "  क्या मुझे याद होगा ");
        map.put("Will I have ridden ", "  क्या मैंने सवारी की होगी ");
        map.put("Will I have rung ", "  क्या मैंने रिंग किया होगा ");
        map.put("Will I have risen ", "  क्या मैं उठ जाऊंगा ");
        map.put("Will I have run ", "  क्या मैं दौड़ूंगा ");
        map.put("Will I have beaten ", "  क्या मैंने पीटा होगा ");
        map.put("Will I have said ", "  क्या मैंने कहा होगा ");
        map.put("Will I have seen ", "  क्या मैंने देखा होगा ");
        map.put("Will I have sold ", "  क्या मैंने बेचा होगा ");
        map.put("Will I have sent ", "  क्या मैंने भेजा होगा ");
        map.put("Will I have become ", "  क्या मैं बन जाऊंगा ");
        map.put("Will I have begged ", "  क्या मैं भीख माँगता हूँ ");
        map.put("Will I have begun ", "  क्या मैंने शुरू किया होगा ");
        map.put("Will I have bound ", "  क्या मैं बाध्य हो जाऊंगा ");
        map.put("Will I have bitten ", "  क्या मैंने काट लिया होगा ");
        map.put("Will I have blessed ", "  क्या मैंने आशीर्वाद दिया होगा ");
        map.put("Will I have blown ", "  क्या मैंने उड़ा दिया होगा ");
        map.put("Will I have broken ", "  क्या मैं टूट गया होगा ");
        map.put("Will I have brought ", "  क्या मैं लाऊंगा ");
        map.put("Will I have built ", "  क्या मैंने बनाया होगा ");
        map.put("Will I have burnt ", "  क्या मैंने जला दिया होगा ");
        map.put("Will I have bought ", "  क्या मैंने खरीदा होगा ");
        map.put("Will I have called ", "  क्या मैंने फोन किया होगा ");
        map.put("Will I have carried ", "  क्या मैं ले जाऊंगा ");
        map.put("Will I have caught ", "  क्या मैंने पकड़ लिया होगा ");
        map.put("Will I have cheated ", "  क्या मैंने धोखा दिया होगा ");
        map.put("Will I have chosen ", "  क्या मैंने चुना होगा ");
        map.put("Will I have cleaned ", "  क्या मैंने साफ कर लिया होगा ");
        map.put("Will I have climbed ", "  क्या मैं चढ़ जाऊंगा ");
        map.put("Will I have jumped ", "  क्या मैं कूद जाऊंगा ");

        return map;
    }
    private static Map<String, String> Ten() {
        HashMap<String,String>map = new HashMap<>();
        map.put("Will I be closing ", "  क्या मैं बंद हो जाऊंगा ");
        map.put("Will I be coming ", "  क्या मैं आ रहा हूँ ");
        map.put("Will I be cooking ", "  क्या मैं खाना बना रहा हूँ ");
        map.put("Will I be creeping ", "  क्या मैं रेंग रहा हूँ ");
        map.put("Will I be crying ", "  क्या मैं रो रहा हूँ ");
        map.put("Will I be cutting ", "  क्या मैं काट रहा हूँ ");
        map.put("Will I be abusing ", "  क्या मैं गाली दे रहा हूँ ");
        map.put("Will I be dancing ", "  क्या मैं नाचता रहूंगा ");
        map.put("Will I be dealing ", "  क्या मैं काम कर रहा हूँ ");
        map.put("Will I be dying ", "  क्या मैं मर जाऊंगा ");
        map.put("Will I be digging ", "  क्या मैं खुदाई करूंगा ");
        map.put("Will I be drawing ", "  क्या मैं ड्राइंग करूंगा ");
        map.put("Will I be drinking ", "  क्या मैं पी रहा हूँ ");
        map.put("Will I be driving ", "  क्या मैं गाड़ी चला रहा हूँ ");
        map.put("Will I be dropping ", "  क्या मैं छोड़ रहा हूँ ");
        map.put("Will I be advising ", "  क्या मैं सलाह दूंगा ");
        map.put("Will I be drying ", "  क्या मैं सूख जाऊंगा ");
        map.put("Will I be eating ", "  क्या मैं खा रहा हूँ ");
        map.put("Will I be electing ", "  क्या मैं चुनाव करूंगा ");
        map.put("Will I be entering ", "  क्या मैं प्रवेश करूंगा ");
        map.put("Will I be falling ", "  क्या मैं गिर रहा हूँ ");
        map.put("Will I be feeding ", "  क्या मैं खिला रहा हूँ ");
        map.put("Will I be feeling ", "  क्या मैं महसूस कर रहा हूँ ");
        map.put("Will I be fighting ", "  क्या मैं लड़ रहा हूँ ");
        map.put("Will I be finding ", "  क्या मुझे मिल रहा होगा ");
        map.put("Will I be answering ", "  क्या मैं जवाब दे रहा हूँ ");
        map.put("Will I be fleeing ", "  क्या मैं भाग जाऊंगा ");
        map.put("Will I be flying ", "  क्या मैं उड़ जाऊंगा ");
        map.put("Will I be forgetting ", "  क्या मैं भूल जाऊंगा ");
        map.put("Will I be frying ", "  क्या मैं तलने जाऊंगा ");
        map.put("Will I be getting ", "  क्या मुझे मिल रहा होगा ");
        map.put("Will I be giving ", "  क्या मैं दे रहा हूँ ");
        map.put("Will I be going ", "  क्या मैं जा रहा हूँ ");
        map.put("Will I be growing ", "  क्या मैं बढ़ रहा हूँ ");
        map.put("Will I be hanging ", "  क्या मैं लटक रहा हूँ ");
        map.put("Will I be arising ", "  क्या मैं उठ रहा हूँ ");
        map.put("Will I be hearing ", "  क्या मैं सुन रहा हूँ ");
        map.put("Will I be helping ", "  क्या मैं मदद कर रहा हूँ ");
        map.put("Will I be hiding ", "  क्या मैं छिपाऊंगा ");
        map.put("Will I be hitting ", "  क्या मैं मार रहा हूँ ");
        map.put("Will I be holding ", "  क्या मैं पकड़ रहा हूँ ");
        map.put("Will I be hoping ", "  क्या मैं उम्मीद कर रहा हूँ ");
        map.put("Will I be hurting ", "  क्या मैं चोट पहुँचाऊंगा ");
        map.put("Will I be jumping ", "  क्या मैं कूद रहा हूँ ");
        map.put("Will I be keeping ", "  क्या मैं रखूंगा ");
        map.put("Will I be killing ", "  क्या मैं मार रहा हूँ ");
        map.put("Will I be knowing ", "  क्या मुझे पता चल जाएगा ");
        map.put("Will I be arriving ", "  क्या मैं आ रहा हूँ ");
        map.put("Will I be laughing ", "  क्या मैं हँस रहा हूँ ");
        map.put("Will I be leading ", "  क्या मैं अग्रणी रहूंगा ");
        map.put("Will I be leaping ", "  क्या मैं छलांग लगाऊंगा ");
        map.put("Will I be learning ", "  क्या मैं सीख रहा हूँ ");
        map.put("Will I be leaving ", "  क्या मैं जा रहा हूँ ");
        map.put("Will I be lending ", "  क्या मैं उधार दे रहा हूँ ");
        map.put("Will I be asking ", "  क्या मैं पूछ रहा हूँ ");
        map.put("Will I be living ", "  क्या मैं जीवित रहूंगा ");
        map.put("Will I be looking ", "  क्या मैं देख रहा हूँ ");
        map.put("Will I be losing ", "  क्या मैं हार जाऊंगा ");
        map.put("Will I be awaking ", "  क्या मैं जाग रहा हूँ ");
        map.put("Will I be loving ", "  क्या मैं प्यार करूंगा ");
        map.put("Will I be making ", "  क्या मैं बना रहा हूँ ");
        map.put("Will I be marrying ", "  क्या मैं शादी करूंगा ");
        map.put("Will I be meeting ", "  क्या मैं मिल जाऊंगा ");
        map.put("Will I be mistaking ", "  क्या मैं गलत हो जाऊंगा ");
        map.put("Will I be opening ", "  क्या मैं खुल रहा हूँ ");
        map.put("Will I be paying ", "  क्या मैं भुगतान कर रहा हूँ ");
        map.put("Will I be playing ", "  क्या मैं खेलूंगा ");
        map.put("Will I be putting ", "  क्या मैं डालूंगा ");
        map.put("Will I be quarrelling ", "  क्या मैं झगड़ा करूंगा ");
        map.put("Will I be raining ", "  क्या मैं बारिश कर रहा हूँ ");
        map.put("Will I be reaching ", "  क्या मैं पहुंच जाऊंगा ");
        map.put("Will I be reading ", "  क्या मैं पढ़ रहा हूँ ");
        map.put("Will I be bearing ", "  क्या मैं असर करूंगा ");
        map.put("Will I be remembering ", "  क्या मैं याद रखूंगा ");
        map.put("Will I be riding ", "  क्या मैं सवारी कर रहा हूँ ");
        map.put("Will I be ringing ", "  क्या मैं बज रहा हूँ ");
        map.put("Will I be rising ", "  क्या मैं उठ रहा हूँ ");
        map.put("Will I be running ", "  क्या मैं दौड़ रहा हूँ ");
        map.put("Will I be beating ", "  क्या मैं धड़क रहा हूँ ");
        map.put("Will I be saying ", "  क्या मैं कह रहा हूँ ");
        map.put("Will I be seeing ", "  क्या मैं देख रहा हूँ ");
        map.put("Will I be selling ", "  क्या मैं बेच रहा हूँ ");
        map.put("Will I be sending ", "  क्या मैं भेजूंगा ");
        map.put("Will I be becoming ", "  क्या मैं बन जाऊंगा ");
        map.put("Will I be begging ", "  क्या मैं भीख माँगता हूँ ");
        map.put("Will I be beginning ", "  क्या मैं शुरुआत करूंगा ");
        map.put("Will I be binding ", "  क्या मैं बाध्यकारी रहूंगा ");
        map.put("Will I be biting ", "  क्या मैं काट रहा हूँ ");
        map.put("Will I be blessing ", "  क्या मैं आशीष बनूंगा ");
        map.put("Will I be blowing ", "  क्या मैं उड़ रहा हूँ ");
        map.put("Will I be breaking ", "  क्या मैं तोड़ रहा हूँ ");
        map.put("Will I be bringing ", "  क्या मैं लाऊंगा ");
        map.put("Will I be building ", "  क्या मैं निर्माण करूंगा ");
        map.put("Will I be burning ", "  क्या मैं जल रहा हूँ ");
        map.put("Will I be buying ", "  क्या मैं खरीद रहा हूँ ");
        map.put("Will I be calling ", "  क्या मैं कॉल कर रहा हूँ ");
        map.put("Will I be carrying ", "  क्या मैं ले जाऊंगा ");
        map.put("Will I be catching ", "  क्या मैं पकड़ रहा हूँ ");
        map.put("Will I be cheating ", "  क्या मैं धोखा दे रहा हूँ ");
        map.put("Will I be choosing ", "  क्या मैं चुन रहा हूँ ");
        map.put("Will I be cleaning ", "  क्या मैं सफाई करूँगा ");
        map.put("Will I be climbing ", "  क्या मैं चढ़ जाऊंगा ");

        return map;
    }
    private static Map<String, String> Nine() {
        HashMap<String,String>map = new HashMap<>();
        map.put("Will I close ", "  क्या मैं बंद करूँगा ");
        map.put("Will I come ", "  क्या मैं आऊंगा ");
        map.put("Will I cook ", "  क्या मैं खाना बनाऊंगा ");
        map.put("Will I creep ", "  क्या मैं रेंगूंगा ");
        map.put("Will I cry ", "  क्या मैं रोऊंगा ");
        map.put("Will I cut ", "  क्या मैं कट जाऊंगा ");
        map.put("Will I abuse ", "  क्या मैं गाली दूंगा ");
        map.put("Will I dance ", "  क्या मैं नाचता हूँ ");
        map.put("Will I deal ", "  क्या मैं सौदा करूंगा ");
        map.put("Will I die ", "  क्या मैं मर जाऊंगा ");
        map.put("Will I dig ", "  क्या मैं खोदूँगा ");
        map.put("Will I draw ", "  क्या मैं आकर्षित करूंगा ");
        map.put("Will I drive ", "  क्या मैं ड्राइव करूंगा ");
        map.put("Will I drop ", "  क्या मैं छोड़ दूँगा ");
        map.put("Will I advise", "  क्या मैं सलाह दूंगा");
        map.put("Will I dry ", "  क्या मैं सूख जाऊंगा ");
        map.put("Will I eat ", "  क्या मैं खाऊंगा ");
        map.put("Will I elect", "  क्या मैं चुनाव करूंगा");
        map.put("Will I be undefined", "  क्या मैं अपरिभाषित हो जाऊंगा");
        map.put("Will I enter ", "  क्या मैं प्रवेश करूंगा ");
        map.put("Will I fall ", "  क्या मैं गिर जाऊंगा ");
        map.put("Will I feed ", "  क्या मैं खिलाऊंगा ");
        map.put("Will I feel  ", "  क्या मैं महसूस करूंगा  ");
        map.put("Will I fight ", "  क्या मैं लड़ूंगा ");
        map.put("Will I answer ", "  क्या मैं जवाब दूंगा ");
        map.put("Will I find ", "  क्या मुझे मिल जाएगा ");
        map.put("Will I flee ", "  क्या मैं भाग जाऊंगा ");
        map.put("Will I fly  ", "  क्या मैं उड़ जाऊंगा  ");
        map.put("Will I forget ", "  क्या मैं भूल जाऊंगा ");
        map.put("Will I fry ", "  क्या मैं भूनूंगा ");
        map.put("Will I get  ", "  क्या मुझे मिलेगा  ");
        map.put("Will I give ", "  क्या मैं दे दूँगा ");
        map.put("Will I go ", "  क्या मैं जाऊंगा ");
        map.put("Will I grow", "  क्या मैं बढ़ूंगा");
        map.put("Will I hang ", "  क्या मैं लटकाऊंगा ");
        map.put("Will I arise ", "  क्या मैं उठूंगा ");
        map.put("Will I hear ", "  क्या मैं सुनूंगा ");
        map.put("Will I help ", "  क्या मैं मदद करूंगा ");
        map.put("Will I hide ", "  क्या मैं छिपाऊंगा ");
        map.put("Will I hit ", "  क्या मैं मारूंगा ");
        map.put("Will I hold ", "  क्या मैं पकड़ लूंगा ");
        map.put("Will I hope ", "  क्या मुझे उम्मीद है ");
        map.put("Will I hurt ", "  क्या मुझे चोट लगी होगी ");
        map.put("Will I jump ", "  क्या मैं कूदूंगा ");
        map.put("Will I keep ", "  क्या मैं रखूंगा ");
        map.put("Will I kill ", "  क्या मैं मार डालूंगा ");
        map.put("Will I know ", "  क्या मुझे पता चलेगा ");
        map.put("Will I arrive ", "  क्या मैं आऊंगा ");
        map.put("Will I laugh ", "  क्या मैं हंसूंगा ");
        map.put("Will I lead ", "  क्या मैं नेतृत्व करूंगा ");
        map.put("Will I leap ", "  क्या मैं छलांग लगाऊंगा ");
        map.put("Will I learn ", "  क्या मैं सीखूंगा ");
        map.put("Will I leave ", "  क्या मैं छोड़ दूँगा ");
        map.put("Will I lend ", "  क्या मैं उधार दूंगा ");
        map.put("Will I ask ", "  क्या मैं पूछूंगा ");
        map.put("Will I live ", "  क्या मैं जीवित रहूंगा ");
        map.put("Will I look ", "  क्या मैं देखूंगा ");
        map.put("Will I lose ", "  क्या मैं हार जाऊंगा ");
        map.put("Will I awake ", "  क्या मैं जाग जाऊंगा ");
        map.put("Will I make ", "  क्या मैं बनाऊंगा ");
        map.put("Will I marry ", "  क्या मैं शादी करूंगा ");
        map.put("Will I meet ", "  क्या मैं मिलूंगा ");
        map.put("Will I mistake ", "  क्या मैं गलती करूंगा ");
        map.put("Will I open ", "  क्या मैं खोलूंगा ");
        map.put("Will I pay  ", "  क्या मैं भुगतान करूंगा  ");
        map.put("Will I play ", "  क्या मैं खेलूंगा ");
        map.put("Will I put ", "  क्या मैं रखूंगा ");
        map.put("Will I quarrel ", "  क्या मैं झगड़ा करूंगा ");
        map.put("Will I rain ", "  क्या मैं बारिश करूंगा ");
        map.put("Will I reach ", "  क्या मैं पहुंच जाऊंगा ");
        map.put("Will I read", "  क्या मैं पढ़ूंगा");
        map.put("Will I bear ", "  क्या मैं सहन करूंगा ");
        map.put("Will I remember  ", "  क्या मुझे याद होगा  ");
        map.put("Will I ride ", "  क्या मैं सवारी करूंगा ");
        map.put("Will I ring ", "  क्या मैं रिंग करूंगा ");
        map.put("Will I rise  ", "  क्या मैं उठूंगा  ");
        map.put("Will I run  ", "  क्या मैं दौड़ूंगा  ");
        map.put("Will I beat ", "  क्या मैं हरा दूंगा ");
        map.put("Will I say ", "  क्या मैं कहूँगा ");
        map.put("Will I see ", "  क्या मैं देखूंगा ");
        map.put("Will I sell ", "  क्या मैं बेचूंगा ");
        map.put("Will I send ", "  क्या मैं भेजूंगा ");
        map.put("Will I become ", "  क्या मैं बन जाऊंगा ");
        map.put("Will I beg ", "  क्या मैं भीख मांगूंगा ");
        map.put("Will I begin ", "  क्या मैं शुरू करूंगा ");
        map.put("Will I start ", "  क्या मैं शुरू करूंगा ");
        map.put("Will I bind ", "  क्या मैं बाँध लूँगा ");
        map.put("Will I bite", "  क्या मैं काटूंगा");
        map.put("Will I bless", "  क्या मैं आशीर्वाद दूंगा");
        map.put("Will I break ", "  क्या मैं टूट जाऊंगा ");
        map.put("Will I bring ", "  क्या मैं लाऊंगा ");
        map.put("Will I build ", "  क्या मैं निर्माण करूंगा ");
        map.put("Will I burn ", "  क्या मैं जलाऊंगा ");
        map.put("Will I buy ", "  क्या मैं खरीदूंगा ");
        map.put("Will I call ", "  क्या मैं फोन करूंगा ");
        map.put("Will I carry ", "  क्या मैं ले जाऊंगा ");
        map.put("Will I catch ", "  क्या मैं पकड़ लूंगा ");
        map.put("Will I cheat ", "  क्या मैं धोखा दूंगा ");
        map.put("Will I choose ", "  क्या मैं चुनूंगा ");
        map.put("Will I clean ", "  क्या मैं साफ करूँगा ");
        map.put("Will I climb  ", "  क्या मैं चढ़ जाऊंगा  ");

        return map;
    }
    private static Map<String, String> Eight() {
        HashMap<String,String>map = new HashMap<>();
        map.put("Had I been  closing ", "  क्या मैं बंद कर रहा था ");
        map.put("Had I been  coming ", "  मैं आ रहा था ");
        map.put("Had I been  cooking ", "  क्या मैं खाना बना रहा था ");
        map.put("Had I been  creeping ", "  क्या मैं रेंग रहा था ");
        map.put("Had I been  crying ", "  क्या मैं रो रहा था ");
        map.put("Had I been  cutting ", "  मैं काट रहा था ");
        map.put("Had I been  abusing ", "  क्या मैं गाली दे रहा था ");
        map.put("Had I been  dancing ", "  क्या मैं नाच रहा था ");
        map.put("Had I been  dealing ", "  क्या मैं काम कर रहा था ");
        map.put("Had I been  dying ", "  क्या मैं मर रहा था ");
        map.put("Had I been  digging ", "  क्या मैं खुदाई कर रहा था ");
        map.put("Had I been  drawing ", "  क्या मैं ड्राइंग कर रहा था ");
        map.put("Had I been  drinking ", "  क्या मैं पी रहा था ");
        map.put("Had I been  driving ", "  क्या मैं गाड़ी चला रहा था ");
        map.put("Had I been  dropping ", "  क्या मैं गिर रहा था ");
        map.put("Had I been  advising ", "  क्या मैं सलाह दे रहा था ");
        map.put("Had I been  drying ", "  क्या मैं सूख रहा था ");
        map.put("Had I been  eating ", "  क्या मैं खा रहा था ");
        map.put("Had I been  electing ", "  क्या मैं चुनाव कर रहा था ");
        map.put("Had I been  undefined", "  क्या मैं अपरिभाषित हो गया था");
        map.put("Had I been  entering ", "  क्या मैं प्रवेश कर रहा था ");
        map.put("Had I been  falling ", "  क्या मैं गिर रहा था ");
        map.put("Had I been  feeding ", "  क्या मैं खिला रहा था ");
        map.put("Had I been  feeling ", "  क्या मैं महसूस कर रहा था ");
        map.put("Had I been  answering ", "  क्या मैं जवाब दे रहा था ");
        map.put("Had I been  fighting ", "  क्या मैं लड़ रहा था ");
        map.put("Had I been  finding ", "  क्या मुझे मिल रहा था ");
        map.put("Had I been  fleeing ", "  क्या मैं भाग रहा था ");
        map.put("Had I been  flying ", "  क्या मैं उड़ रहा था ");
        map.put("Had I been  forgetting ", "  क्या मैं भूल रहा था ");
        map.put("Had I been  frying ", "  क्या मैं तलने गया था ");
        map.put("Had I been  getting ", "  मैं मिल रहा था ");
        map.put("Had I been  giving ", "  मैं दे रहा था ");
        map.put("Had I been  going ", "  मैं जा रहा था ");
        map.put("Had I been  growing ", "  क्या मैं बढ़ रहा था ");
        map.put("Had I been  hanging ", "  क्या मैं लटक रहा था ");
        map.put("Had I been  arising ", "  क्या मैं उठ रहा था ");
        map.put("Had I been  hearing ", "  क्या मैं सुन रहा था ");
        map.put("Had I been  helping ", "  क्या मैं मदद कर रहा था ");
        map.put("Had I been  hiding ", "  क्या मैं छिपा रहा था ");
        map.put("Had I been  hitting ", "  क्या मैं मार रहा था ");
        map.put("Had I been  holding ", "  क्या मैं पकड़ रहा था ");
        map.put("Had I been  hoping ", "  क्या मैं उम्मीद कर रहा था ");
        map.put("Had I been  hurting ", "  क्या मैं चोट पहुँचा रहा था ");
        map.put("Had I been  jumping ", "  क्या मैं कूद रहा था ");
        map.put("Had I been  keeping ", "  मैं रख रहा था ");
        map.put("Had I been  killing ", "  क्या मैं मार रहा था ");
        map.put("Had I been  knowing ", "  क्या मैं जान रहा था ");
        map.put("Had I been  arriving ", "  क्या मैं आ रहा था ");
        map.put("Had I been  laughing ", "  क्या मैं हँस रहा था ");
        map.put("Had I been  leading ", "  क्या मैं नेतृत्व कर रहा था ");
        map.put("Had I been  leaping ", "  क्या मैं छलांग लगा रहा था ");
        map.put("Had I been  learning ", "  क्या मैं सीख रहा था ");
        map.put("Had I been  leaving ", "  क्या मैं जा रहा था ");
        map.put("Had I been  lending ", "  क्या मैं उधार दे रहा था ");
        map.put("Had I been  asking ", "  क्या मैं पूछ रहा था ");
        map.put("Had I been  living ", "  क्या मैं जी रहा था ");
        map.put("Had I been  looking ", "  क्या मैं देख रहा था ");
        map.put("Had I been  losing ", "  क्या मैं हार रहा था ");
        map.put("Had I been  awaking ", "  क्या मैं जाग रहा था ");
        map.put("Had I been  loving ", "  क्या मैं प्यार कर रहा था ");
        map.put("Had I been  making ", "  मैं बना रहा था ");
        map.put("Had I been  marrying ", "  क्या मैं शादी कर रहा था ");
        map.put("Had I been  meeting ", "  क्या मैं मिल रहा था ");
        map.put("Had I been  mistaking ", "  क्या मैं गलती कर रहा था ");
        map.put("Had I been  opening ", "  क्या मैं खोल रहा था ");
        map.put("Had I been  paying ", "  क्या मैं भुगतान कर रहा था ");
        map.put("Had I been  playing ", "  क्या मैं खेल रहा था ");
        map.put("Had I been  putting ", "  मैं डाल रहा था ");
        map.put("Had I been  quarrelling ", "  क्या मैं झगड़ा कर रहा था ");
        map.put("Had I been  raining ", "  बारिश हो रही थी ");
        map.put("Had I been  reaching ", "  मैं पहुँच रहा था ");
        map.put("Had I been  reading ", "  क्या मैं पढ़ रहा था ");
        map.put("Had I been  bearing ", "  क्या मैं असर कर रहा था ");
        map.put("Had I been  remembering ", "  क्या मुझे याद आ रहा था ");
        map.put("Had I been  riding ", "  क्या मैं सवारी कर रहा था ");
        map.put("Had I been  ringing ", "  क्या मैं बज रहा था ");
        map.put("Had I been  rising ", "  क्या मैं उठ रहा था ");
        map.put("Had I been  running ", "  क्या मैं दौड़ रहा था ");
        map.put("Had I been  beating ", "  क्या मैं पिटाई कर रहा था ");
        map.put("Had I been  saying ", "  क्या मैं कह रहा था ");
        map.put("Had I been  seeing ", "  क्या मैं देख रहा था ");
        map.put("Had I been  selling ", "  मैं बेच रहा था ");
        map.put("Had I been  sending ", "  मैं भेज रहा था ");
        map.put("Had I been  becoming ", "  क्या मैं बन रहा था ");
        map.put("Had I been  begging ", "  मैं भीख माँग रहा था ");
        map.put("Had I been  beginning ", "  क्या मैं शुरुआत कर रहा था ");
        map.put("Had I been  starting ", "  क्या मैं शुरू कर रहा था ");
        map.put("Had I been  binding ", "  क्या मैं बाध्यकारी था ");
        map.put("Had I been  biting ", "  क्या मैं काट रहा था ");
        map.put("Had I been  blessing ", "  क्या मैं आशीर्वाद दे रहा था ");
        map.put("Had I been  blowing ", "  क्या मैं उड़ रहा था ");
        map.put("Had I been  breaking ", "  क्या मैं तोड़ रहा था ");
        map.put("Had I been  bringing ", "  मैं ला रहा था ");
        map.put("Had I been  building ", "  क्या मैं निर्माण कर रहा था ");
        map.put("Had I been  burning ", "  क्या मैं जल रहा था ");
        map.put("Had I been  buying ", "  मैं खरीद रहा था ");
        map.put("Had I been  calling ", "  क्या मैं फोन कर रहा था ");
        map.put("Had I been  carrying ", "  मैं ले जा रहा था ");
        map.put("Had I been  catching ", "  क्या मैं पकड़ रहा था ");
        map.put("Had I been  cheating ", "  क्या मैं धोखा दे रहा था ");
        map.put("Had I been  choosing ", "  मैं चुन रहा था ");
        map.put("Had I been  cleaning ", "  क्या मैं सफाई कर रहा था ");
        map.put("Had I been  climbing ", "  क्या मैं चढ़ रहा था ");

        return map;
    }
    private static Map<String, String> Seven() {
        HashMap<String,String>map = new HashMap<>();
        map.put("Had I  closed ", "  मैंने बंद कर दिया था ");
        map.put("Had I  come ", "  मैं आया था ");
        map.put("Had I  cooked ", "  मैंने पकाया था ");
        map.put("Had I  crept ", "  मैंने क्रेप किया था ");
        map.put("Had I  cried ", "  क्या मैं रोया था ");
        map.put("Had I  cut ", "  मैंने काट दिया था ");
        map.put("Had I  abused ", "  मैंने गाली दी थी ");
        map.put("Had I  danced ", "  मैंने नृत्य किया था ");
        map.put("Had I  dealt ", "  मैंने निपटाया था ");
        map.put("Had I  died ", "  अगर मैं मर गया था ");
        map.put("Had I  dug ", "  मैंने खोदा था ");
        map.put("Had I  drawn ", "  मैंने खींचा था ");
        map.put("Had I  drunk ", "  मैंने पिया था ");
        map.put("Had I  driven ", "  मैंने चलाया था ");
        map.put("Had I  dropped ", "  मैंने गिरा दिया था ");
        map.put("Had I  advised ", "  मैंने सलाह दी थी ");
        map.put("Had I  dried ", "  क्या मैं सूख गया था ");
        map.put("Had I  eaten ", "  मैंने खाया था ");
        map.put("Had I  elected ", "  क्या मैंने चुना था ");
        map.put("Had I  undefined", "  मैंने अपरिभाषित किया था");
        map.put("Had I  entered ", "  मैंने प्रवेश किया था ");
        map.put("Had I  fallen ", "  मैं गिर गया था ");
        map.put("Had I  fed ", "  मैंने खिलाया था ");
        map.put("Had I  felt ", "  मैंने महसूस किया था ");
        map.put("Had I  answered ", "  मैंने जवाब दिया था ");
        map.put("Had I  fought ", "  मैंने लड़ाई लड़ी थी ");
        map.put("Had I  found ", "  मैंने पाया था ");
        map.put("Had I  fled ", "  अगर मैं भाग गया था ");
        map.put("Had I  flown ", "  मैंने उड़ान भरी थी ");
        map.put("Had I  forgotten ", "  मैं भूल गया था ");
        map.put("Had I  fried ", "  मैंने फ्राई किया था ");
        map.put("Had I  got ", "  मुझे मिल गया था ");
        map.put("Had I  given ", "  मैंने दिया था ");
        map.put("Had I  gone ", "  मैं गया था ");
        map.put("Had I  grown ", "  मैं बड़ा हो गया था ");
        map.put("Had I  hanged ", "  मैंने फांसी लगा ली थी ");
        map.put("Had I  hung ", "  मैंने लटका दिया था ");
        map.put("Had I  arisen ", "  अगर मैं पैदा हुआ था ");
        map.put("Had I  heard ", "  मैंने सुना था ");
        map.put("Had I  helped ", "  मैंने मदद की थी ");
        map.put("Had I  hidden ", "  मैंने छुपाया था ");
        map.put("Had I  hit ", "  मैंने मारा था ");
        map.put("Had I  held ", "  मैंने आयोजित किया था ");
        map.put("Had I  hoped ", "  मैंने आशा की थी ");
        map.put("Had I  hurt ", "  मैंने चोट पहुंचाई थी ");
        map.put("Had I  jumped ", "  मैं कूद गया था ");
        map.put("Had I  kept ", "  मैंने रखा था ");
        map.put("Had I  killed ", "  मैंने मार डाला था ");
        map.put("Had I  known ", "  मुझे पता था ");
        map.put("Had I  arrived ", "  मैं आ गया था ");
        map.put("Had I  laughed ", "  क्या मैं हँसा था ");
        map.put("Had I  led ", "  मैंने नेतृत्व किया था ");
        map.put("Had I  leapt ", "  मैंने छलांग लगाई थी ");
        map.put("Had I  learnt ", "  मैंने सीखा था ");
        map.put("Had I  left ", "  मैंने छोड़ा था ");
        map.put("Had I  lent ", "  मैंने उधार दिया था ");
        map.put("Had I  asked ", "  मैंने पूछा था ");
        map.put("Had I  lived ", "  मैं रहता था ");
        map.put("Had I  looked ", "  मैंने देखा था ");
        map.put("Had I  lost ", "  क्या मैं हार गया था ");
        map.put("Had I  awoken ", "  क्या मैं जाग गया था ");
        map.put("Had I  loved ", "  क्या मैं प्यार करता था ");
        map.put("Had I  made ", "  मैंने बनाया था ");
        map.put("Had I  married ", "  मैंने शादी की थी ");
        map.put("Had I  met ", "  मैं मिला था ");
        map.put("Had I  mistaken ", "  क्या मैंने गलत किया था ");
        map.put("Had I  opened ", "  मैंने खोला था ");
        map.put("Had I  paid ", "  मैंने भुगतान किया था ");
        map.put("Had I  played ", "  मैंने खेला था ");
        map.put("Had I  put ", "  मैंने रखा था ");
        map.put("Had I  quarrelled ", "  मैंने झगड़ा किया था ");
        map.put("Had I  rained ", "  अगर मैंने बारिश की थी ");
        map.put("Had I  reached ", "  मैं पहुँच गया था ");
        map.put("Had I  read ", "  मैंने पढ़ा था ");
        map.put("Had I  borne ", "  मैंने जन्म लिया था ");
        map.put("Had I  remembered ", "  मुझे याद आया था ");
        map.put("Had I  ridden ", "  मैंने सवारी की थी ");
        map.put("Had I  rung ", "  मैंने बजाया था ");
        map.put("Had I  risen ", "  मैं उठ गया था ");
        map.put("Had I  run ", "  मैंने दौड़ा था ");
        map.put("Had I  beaten ", "  मैंने पीटा था ");
        map.put("Had I  said ", "  मैंने कहा था ");
        map.put("Had I  seen ", "  मैंने देखा था ");
        map.put("Had I  sold ", "  मैंने बेचा था ");
        map.put("Had I  sent ", "  मैंने भेजा था ");
        map.put("Had I  shaken ", "  मैंने हिला दिया था ");
        map.put("Had I  become ", "  मैं बन गया था ");
        map.put("Had I  begged ", "  मैंने भीख माँगी थी ");
        map.put("Had I  begun ", "  मैंने शुरू किया था ");
        map.put("Had I  bound ", "  मैंने बाध्य किया था ");
        map.put("Had I  bitten ", "  मैंने काट लिया था ");
        map.put("Had I  blessed ", "  मैंने आशीर्वाद दिया था ");
        map.put("Had I  blown ", "  मैंने उड़ा दिया था ");
        map.put("Had I  broken ", "  क्या मैं टूट गया था ");
        map.put("Had I  brought ", "  मैं लाया था ");
        map.put("Had I  built ", "  मैंने बनाया था ");
        map.put("Had I  burnt ", "  मैंने जला दिया था ");
        map.put("Had I  bought ", "  मैंने खरीदा था ");
        map.put("Had I  called ", "  मैंने फोन किया था ");
        map.put("Had I  carried ", "  मैंने किया था ");
        map.put("Had I  caught ", "  मैंने पकड़ा था ");
        map.put("Had I  cheated ", "  मैंने धोखा दिया था ");
        map.put("Had I  chosen ", "  मैंने चुना था ");
        map.put("Had I  cleaned ", "  मैंने साफ किया था ");
        map.put("Had I  climbed ", "  अगर मैं चढ़ गया था ");

        return map;
    }
    private static Map<String, String> Six() {
        HashMap<String,String>map = new HashMap<>();
        map.put("Was I  abusing ", "  क्या मैं गाली दे रहा था ");
        map.put("Was I  coming ", "  क्या मैं आ रहा था ");
        map.put("Was I  cooking ", "  क्या मैं खाना बना रहा था ");
        map.put("Was I  creeping ", "  क्या मैं रेंग रहा था ");
        map.put("Was I  crying ", "  क्या मैं रो रहा था ");
        map.put("Was I  cutting ", "  क्या मैं काट रहा था ");
        map.put("Was I  dancing ", "  क्या मैं नाच रहा था ");
        map.put("Was I  dealing ", "  क्या मैं काम कर रहा था ");
        map.put("Was I  dying ", "  क्या मैं मर रहा था ");
        map.put("Was I  digging ", "  क्या मैं खुदाई कर रहा था ");
        map.put("Was I  drawing ", "  क्या मैं ड्राइंग कर रहा था ");
        map.put("Was I  drinking ", "  क्या मैं पी रहा था ");
        map.put("Was I  driving ", "  क्या मैं गाड़ी चला रहा था ");
        map.put("Was I  advising ", "  क्या मैं सलाह दे रहा था ");
        map.put("Was I  dropping ", "  क्या मैं गिर रहा था ");
        map.put("Was I  drying ", "  क्या मैं सूख रहा था ");
        map.put("Was I  eating ", "  क्या मैं खा रहा था ");
        map.put("Was I  electing ", "  क्या मैं चुनाव कर रहा था ");
        map.put("Was I  undefined", "  क्या मैं अपरिभाषित था");
        map.put("Was I  entering ", "  क्या मैं प्रवेश कर रहा था ");
        map.put("Was I  falling ", "  क्या मैं गिर रहा था ");
        map.put("Was I  feeding ", "  क्या मैं खिला रहा था ");
        map.put("Was I  answering ", "  क्या मैं जवाब दे रहा था ");
        map.put("Was I  feeling ", "  क्या मैं महसूस कर रहा था ");
        map.put("Was I  fighting ", "  क्या मैं लड़ रहा था ");
        map.put("Was I  finding ", "  क्या मैं खोज रहा था ");
        map.put("Was I  fleeing ", "  क्या मैं भाग रहा था ");
        map.put("Was I  flying ", "  क्या मैं उड़ रहा था ");
        map.put("Was I  forgetting ", "  क्या मैं भूल रहा था ");
        map.put("Was I  frying ", "  क्या मैं तलने गया था ");
        map.put("Was I  getting ", "  क्या मुझे मिल रहा था ");
        map.put("Was I  giving ", "  मैं दे रहा था ");
        map.put("Was I  going ", "  क्या मैं जा रहा था ");
        map.put("Was I  growing ", "  क्या मैं बढ़ रहा था ");
        map.put("Was I  hanging ", "  क्या मैं लटक रहा था ");
        map.put("Was I  arising ", "  क्या मैं उठ रहा था ");
        map.put("Was I  hearing ", "  क्या मैं सुन रहा था ");
        map.put("Was I  helping ", "  क्या मैं मदद कर रहा था ");
        map.put("Was I  hiding ", "  क्या मैं छिपा रहा था ");
        map.put("Was I  hitting ", "  क्या मैं मार रहा था ");
        map.put("Was I  holding ", "  क्या मैं पकड़ रहा था ");
        map.put("Was I  hoping ", "  क्या मैं उम्मीद कर रहा था ");
        map.put("Was I  hurting ", "  क्या मैं चोट पहुँचा रहा था ");
        map.put("Was I  jumping ", "  क्या मैं कूद रहा था ");
        map.put("Was I  keeping ", "  मैं रख रहा था ");
        map.put("Was I  killing ", "  क्या मैं मार रहा था ");
        map.put("Was I  knowing ", "  क्या मैं जान रहा था ");
        map.put("Was I  arriving ", "  क्या मैं आ रहा था ");
        map.put("Was I  laughing ", "  क्या मैं हँस रहा था ");
        map.put("Was I  leading ", "  क्या मैं अग्रणी था ");
        map.put("Was I  leaping ", "  क्या मैं छलांग लगा रहा था ");
        map.put("Was I  learning ", "  क्या मैं सीख रहा था ");
        map.put("Was I  leaving ", "  क्या मैं जा रहा था ");
        map.put("Was I  lending ", "  क्या मैं उधार दे रहा था ");
        map.put("Was I  asking ", "  क्या मैं पूछ रहा था ");
        map.put("Was I  living ", "  क्या मैं जी रहा था ");
        map.put("Was I  looking ", "  क्या मैं देख रहा था ");
        map.put("Was I  losing ", "  क्या मैं हार रहा था ");
        map.put("Was I  awaking ", "  क्या मैं जाग रहा था ");
        map.put("Was I  loving ", "  क्या मैं प्यार कर रहा था ");
        map.put("Was I  making ", "  मैं बना रहा था ");
        map.put("Was I  marrying ", "  क्या मैं शादी कर रहा था ");
        map.put("Was I  meeting ", "  क्या मैं मिल रहा था ");
        map.put("Was I  mistaking ", "  क्या मैं गलती कर रहा था ");
        map.put("Was I  opening ", "  क्या मैं खोल रहा था ");
        map.put("Was I  paying ", "  क्या मैं भुगतान कर रहा था ");
        map.put("Was I  playing ", "  क्या मैं खेल रहा था ");
        map.put("Was I  putting ", "  क्या मैं डाल रहा था ");
        map.put("Was I  quarrelling ", "  क्या मैं झगड़ा कर रहा था ");
        map.put("Was I  raining ", "  क्या मैं बारिश कर रहा था ");
        map.put("Was I  bearing ", "  क्या मैं असर कर रहा था ");
        map.put("Was I  reaching ", "  क्या मैं पहुंच रहा था ");
        map.put("Was I  reading ", "  क्या मैं पढ़ रहा था ");
        map.put("Was I  remembering ", "  क्या मैं याद कर रहा था ");
        map.put("Was I  riding ", "  क्या मैं सवारी कर रहा था ");
        map.put("Was I  ringing ", "  क्या मैं बज रहा था ");
        map.put("Was I  beating ", "  क्या मैं पिटाई कर रहा था ");
        map.put("Was I  rising ", "  क्या मैं उठ रहा था ");
        map.put("Was I  running ", "  क्या मैं दौड़ रहा था ");
        map.put("Was I  saying ", "  क्या मैं कह रहा था ");
        map.put("Was I  seeing ", "  क्या मैं देख रहा था ");
        map.put("Was I  selling ", "  क्या मैं बेच रहा था ");
        map.put("Was I  sending ", "  क्या मैं भेज रहा था ");
        map.put("Was I  becoming ", "  क्या मैं बन रहा था ");
        map.put("Was I  shaking ", "  मैं हिल रहा था ");
        map.put("Was I  begging ", "  मैं भीख माँग रहा था ");
        map.put("Was I  beginning ", "  क्या मैं शुरुआत कर रहा था ");
        map.put("Was I  binding ", "  क्या मैं बाध्यकारी था ");
        map.put("Was I  biting ", "  क्या मैं काट रहा था ");
        map.put("Was I  blessing ", "  क्या मैं आशीर्वाद दे रहा था ");
        map.put("Was I  blowing ", "  क्या मैं उड़ रहा था ");
        map.put("Was I  breaking ", "  क्या मैं तोड़ रहा था ");
        map.put("Was I  bringing ", "  मैं ला रहा था ");
        map.put("Was I  building ", "  क्या मैं निर्माण कर रहा था ");
        map.put("Was I  burning ", "  क्या मैं जल रहा था ");
        map.put("Was I  buying ", "  क्या मैं खरीद रहा था ");
        map.put("Was I  calling ", "  क्या मैं बुला रहा था ");
        map.put("Was I  carrying ", "  क्या मैं ले जा रहा था ");
        map.put("Was I  catching ", "  क्या मैं पकड़ रहा था ");
        map.put("Was I  cheating ", "  क्या मैं धोखा दे रहा था ");
        map.put("Was I  choosing ", "  क्या मैं चुन रहा था ");
        map.put("Was I  cleaning ", "  क्या मैं सफाई कर रहा था ");
        map.put("Was I  climbing ", "  क्या मैं चढ़ रहा था ");
        map.put("Was I  closing ", "  क्या मैं बंद कर रहा था ");

        return map;
    }
    private static Map<String, String> Five() {
        HashMap<String,String>map = new HashMap<>();
        map.put("Did I  abuse ", "  क्या मैंने गाली दी ");
        map.put("Did I  come ", "  क्या मैं आया था ");
        map.put("Did I  cook ", "  क्या मैंने खाना बनाया ");
        map.put("Did I  creep ", "  क्या मैं रेंगना था ");
        map.put("Did I  cut ", "  क्या मैंने काट दिया ");
        map.put("Did I  dance ", "  क्या मैंने नृत्य किया ");
        map.put("Did I  deal ", "  क्या मैंने सौदा किया ");
        map.put("Did I  die ", "  क्या मैं मर गया ");
        map.put("Did I  dig ", "  क्या मैंने खोदा ");
        map.put("Did I  draw ", "  क्या मैंने आकर्षित किया ");
        map.put("Did I  advise", "  क्या मैंने सलाह दी थी");
        map.put("Did I  drive ", "  क्या मैंने ड्राइव किया ");
        map.put("Did I  drop ", "  क्या मैंने छोड़ दिया ");
        map.put("Did I  dry ", "  क्या मैंने सुखाया ");
        map.put("Did I  eat ", "  क्या मैंने खाया ");
        map.put("Did I  elect", "  क्या मैंने चुनाव किया");
        map.put("Did I  answer ", "  क्या मैंने जवाब दिया ");
        map.put("Did I  enter ", "  क्या मैंने प्रवेश किया ");
        map.put("Did I  fall ", "  क्या मैं गिर गया ");
        map.put("Did I  feed ", "  क्या मैंने खाना खिलाया ");
        map.put("Did I  feel  ", "  क्या मुझे लगता है  ");
        map.put("Did I  fight ", "  क्या मैंने लड़ाई लड़ी ");
        map.put("Did I  find ", "  क्या मुझे मिला ");
        map.put("Did I  flee ", "  क्या मैं भाग गया ");
        map.put("Did I  fly  ", "  क्या मैंने उड़ान भरी  ");
        map.put("Did I  fry ", "  क्या मैंने फ्राई किया ");
        map.put("Did I  get  ", "  क्या मुझे मिला  ");
        map.put("Did I  arise ", "  क्या मैं उठ गया ");
        map.put("Did I  give ", "  क्या मैंने दिया था ");
        map.put("Did I  go ", "  क्या मैं गया ");
        map.put("Did I  grow", "  क्या मैं बढ़ता था");
        map.put("Did I  hang ", "  क्या मैंने लटका दिया ");
        map.put("Did I  hear ", "  क्या मैंने सुना ");
        map.put("Did I  help ", "  क्या मैंने मदद की ");
        map.put("Did I  hide ", "  क्या मैंने छिपाया ");
        map.put("Did I  hit ", "  क्या मैंने मारा ");
        map.put("Did I  hold ", "  क्या मैंने पकड़ लिया था ");
        map.put("Did I  hope ", "  क्या मुझे उम्मीद थी ");
        map.put("Did I  arrive ", "  क्या मैं आया ");
        map.put("Did I  hurt ", "  क्या मैंने चोट पहुंचाई ");
        map.put("Did I  jump ", "  क्या मैं कूद गया ");
        map.put("Did I  keep ", "  क्या मैंने रखा था ");
        map.put("Did I  kill ", "  क्या मैंने मार डाला ");
        map.put("Did I  know ", "  क्या मुझे पता था ");
        map.put("Did I  laugh ", "  क्या मैं हँसा था ");
        map.put("Did I  lead ", "  क्या मैंने नेतृत्व किया ");
        map.put("Did I  leap ", "  क्या मैंने छलांग लगाई ");
        map.put("Did I  learn ", "  क्या मैंने सीखा ");
        map.put("Did I  leave ", "  क्या मैंने छोड़ा ");
        map.put("Did I  ask ", "  क्या मैंने पूछा ");
        map.put("Did I  live ", "  क्या मैं रहता था ");
        map.put("Did I  awake ", "  क्या मैं जाग गया ");
        map.put("Did I  look ", "  क्या मैंने देखा ");
        map.put("Did I  lose ", "  क्या मैं हार गया ");
        map.put("Did I  love ", "  क्या मुझे प्यार था ");
        map.put("Did I  make ", "  क्या मैंने बनाया ");
        map.put("Did I  marry ", "  क्या मैंने शादी की ");
        map.put("Did I  meet ", "  क्या मैं मिला ");
        map.put("Did I  mistake ", "  क्या मैंने गलती की ");
        map.put("Did I  open ", "  क्या मैंने खोला ");
        map.put("Did I  pay  ", "  क्या मैंने भुगतान किया  ");
        map.put("Did I  play ", "  क्या मैं खेलता था ");
        map.put("Did I  put ", "  क्या मैंने रखा था ");
        map.put("Did I  quarrel ", "  क्या मैंने झगड़ा किया ");
        map.put("Did I  rain ", "  क्या मैंने बारिश की ");
        map.put("Did I  reach ", "  क्या मैं पहुँच गया ");
        map.put("Did I  read", "  क्या मैंने पढ़ा");
        map.put("Did I  remember  ", "  क्या मुझे याद आया  ");
        map.put("Did I  ride ", "  क्या मैंने सवारी की ");
        map.put("Did I  ring ", "  क्या मैंने रिंग की थी ");
        map.put("Did I  beat ", "  क्या मैंने हराया ");
        map.put("Did I  rise  ", "  क्या मैं उठ गया  ");
        map.put("Did I  say ", "  क्या मैंने कहा था ");
        map.put("Did I  see ", "  क्या मैंने देखा ");
        map.put("Did I  sell ", "  क्या मैंने बेच दिया ");
        map.put("Did I  send ", "  क्या मैंने भेजा था ");
        map.put("Did I  become ", "  क्या मैं बन गया ");
        map.put("Did I  shake ", "  क्या मैंने हिला दिया ");
        map.put("Did I  beg ", "  क्या मैंने भीख माँगी ");
        map.put("Did I  begin ", "  क्या मैंने शुरू किया था ");
        map.put("Did I  bind ", "  क्या मैंने बाँध दिया था ");
        map.put("Did I  bite", "  क्या मैंने काट लिया");
        map.put("Did I  bless", "  क्या मैंने आशीर्वाद दिया");
        map.put("Did I  blow ", "  क्या मैंने उड़ा दिया ");
        map.put("Did I  break ", "  क्या मैंने तोड़ दिया ");
        map.put("Did I  bring ", "  क्या मैं लाया था ");
        map.put("Did I  build ", "  क्या मैंने निर्माण किया था ");
        map.put("Did I  burn ", "  क्या मैंने जला दिया था ");
        map.put("Did I  buy ", "  क्या मैंने खरीदा ");
        map.put("Did I  call ", "  क्या मैंने फोन किया ");
        map.put("Did I  carry ", "  क्या मैं ले गया था ");
        map.put("Did I  catch ", "  क्या मैंने पकड़ लिया ");
        map.put("Did I  cheat ", "  क्या मैंने धोखा दिया ");
        map.put("Did I  choose ", "  क्या मैंने चुना ");
        map.put("Did I  clean ", "  क्या मैंने साफ किया ");
        map.put("Did I  climb  ", "  क्या मैं चढ़ गया  ");
        map.put("Did I  close ", "  क्या मैंने बंद किया ");

        return map;
    }
    private static Map<String, String> Four() {
        HashMap<String,String>map = new HashMap<>();
        map.put("Have I been abusing ", "  क्या मैं गाली दे रहा हूं ");
        map.put("Have I been coming ", "  क्या मैं आ रहा हूँ ");
        map.put("Have I been cooking ", "  क्या मैं खाना बना रहा हूँ ");
        map.put("Have I been creeping ", "  क्या मैं रेंग रहा हूँ ");
        map.put("Have I been crying ", "  क्या मैं रो रहा हूँ ");
        map.put("Have I been cutting ", "  क्या मैं काट रहा हूँ ");
        map.put("Have I been dancing ", "  क्या मैं नाच रहा हूँ ");
        map.put("Have I been dealing ", "  क्या मैं काम कर रहा हूं ");
        map.put("Have I been dying ", "  क्या मैं मर रहा हूँ ");
        map.put("Have I been digging ", "  क्या मैं खुदाई कर रहा हूँ ");
        map.put("Have I been doing ", "  क्या मैं कर रहा हूँ ");
        map.put("Have I been drawing ", "  क्या मैं ड्राइंग कर रहा हूं ");
        map.put("Have I been advising ", "  क्या मैं सलाह दे रहा हूं ");
        map.put("Have I been drinking ", "  क्या मैं पी रहा हूँ ");
        map.put("Have I been driving ", "  क्या मैं गाड़ी चला रहा हूँ ");
        map.put("Have I been dropping ", "  क्या मैं गिर रहा हूँ ");
        map.put("Have I been drying ", "  क्या मैं सूख रहा हूं ");
        map.put("Have I been eating ", "  क्या मैं खा रहा हूँ ");
        map.put("Have I been electing ", "  क्या मैं चुनाव कर रहा हूँ ");
        map.put("Have I been undefined", "  क्या मुझे अपरिभाषित किया गया है");
        map.put("Have I been answering ", "  क्या मैं जवाब दे रहा हूं ");
        map.put("Have I been entering ", "  क्या मैं प्रवेश कर रहा हूँ ");
        map.put("Have I been falling ", "  क्या मैं गिर रहा हूँ ");
        map.put("Have I been feeding ", "  क्या मैं खिला रहा हूँ ");
        map.put("Have I been feeling ", "  क्या मैं महसूस कर रहा हूँ ");
        map.put("Have I been fighting ", "  क्या मैं लड़ रहा हूँ ");
        map.put("Have I been finding ", "  क्या मुझे मिल रहा है ");
        map.put("Have I been fleeing ", "  क्या मैं भाग रहा हूँ ");
        map.put("Have I been flying ", "  क्या मैं उड़ रहा हूँ ");
        map.put("Have I been forgetting ", "  क्या मैं भूल रहा हूँ ");
        map.put("Have I been frying ", "  क्या मैं फ्राइंग कर रहा हूँ ");
        map.put("Have I been getting ", "  क्या मुझे मिल रहा है ");
        map.put("Have I been arising ", "  क्या मैं उठ रहा हूँ ");
        map.put("Have I been giving ", "  क्या मैं दे रहा हूँ ");
        map.put("Have I been going ", "  क्या मैं जा रहा हूँ ");
        map.put("Have I been growing ", "  क्या मैं बढ़ रहा हूँ ");
        map.put("Have I been hanging ", "  क्या मैं लटक रहा हूँ ");
        map.put("Have I been hearing ", "  क्या मैं सुन रहा हूँ ");
        map.put("Have I been helping ", "  क्या मैं मदद कर रहा हूं ");
        map.put("Have I been hiding ", "  क्या मैं छिपा रहा हूँ ");
        map.put("Have I been hitting ", "  क्या मैं मार रहा हूँ ");
        map.put("Have I been holding ", "  क्या मैं पकड़ रहा हूँ ");
        map.put("Have I been hoping ", "  क्या मैं उम्मीद कर रहा था ");
        map.put("Have I been arriving ", "  क्या मैं आ रहा हूँ ");
        map.put("Have I been hurting ", "  क्या मैं चोट पहुँचा रहा हूँ ");
        map.put("Have I been jumping ", "  क्या मैं कूद रहा हूँ ");
        map.put("Have I been keeping ", "  क्या मैं रख रहा हूँ ");
        map.put("Have I been killing ", "  क्या मैं मार रहा हूँ ");
        map.put("Have I been knowing ", "  क्या मैं जान रहा हूँ ");
        map.put("Have I been laughing ", "  क्या मैं हँस रहा हूँ ");
        map.put("Have I been leading ", "  क्या मैं अग्रणी रहा हूँ ");
        map.put("Have I been leaping ", "  क्या मैं छलांग लगा रहा हूँ ");
        map.put("Have I been learning ", "  क्या मैं सीख रहा हूँ ");
        map.put("Have I been leaving ", "  क्या मैं जा रहा हूँ ");
        map.put("Have I been asking ", "  क्या मैं पूछ रहा हूँ ");
        map.put("Have I been lending ", "  क्या मैं उधार दे रहा हूँ ");
        map.put("Have I been living ", "  क्या मैं जी रहा हूँ ");
        map.put("Have I been awaking ", "  क्या मैं जाग रहा हूँ ");
        map.put("Have I been looking ", "  क्या मैं देख रहा था ");
        map.put("Have I been losing ", "  क्या मैं हार रहा हूँ ");
        map.put("Have I been loving ", "  क्या मैं प्यार कर रहा हूँ ");
        map.put("Have I been making ", "  क्या मैं बना रहा हूँ ");
        map.put("Have I been marrying ", "  क्या मैं शादी कर रहा हूँ ");
        map.put("Have I been meeting ", "  क्या मैं मिल रहा हूँ ");
        map.put("Have I been mistaking ", "  क्या मैं गलत कर रहा हूँ ");
        map.put("Have I been opening ", "  क्या मैं खोल रहा हूँ ");
        map.put("Have I been paying ", "  क्या मैं भुगतान कर रहा हूँ ");
        map.put("Have I been playing ", "  क्या मैं खेल रहा हूँ ");
        map.put("Have I been putting ", "  क्या मैं डाल रहा हूँ ");
        map.put("Have I been quarrelling ", "  क्या मैं झगड़ा कर रहा हूँ ");
        map.put("Have I been raining ", "  क्या मुझे बारिश हो रही है ");
        map.put("Have I been bearing ", "  क्या मैं असर कर रहा हूँ ");
        map.put("Have I been reaching ", "  क्या मैं पहुँच रहा हूँ ");
        map.put("Have I been reading ", "  क्या मैं पढ़ रहा हूँ ");
        map.put("Have I been remembering ", "  क्या मुझे याद आ रहा है ");
        map.put("Have I been riding ", "  क्या मैं सवारी कर रहा हूँ ");
        map.put("Have I been ringing ", "  क्या मैं बज रहा हूँ ");
        map.put("Have I been beating ", "  क्या मैं पिटाई कर रहा हूँ ");
        map.put("Have I been rising ", "  क्या मैं उठ रहा हूँ ");
        map.put("Have I been running ", "  क्या मैं दौड़ रहा हूँ ");
        map.put("Have I been saying ", "  क्या मैं कह रहा हूँ ");
        map.put("Have I been seeing ", "  क्या मैं देख रहा हूँ ");
        map.put("Have I been selling ", "  क्या मैं बेच रहा हूँ ");
        map.put("Have I been sending ", "  क्या मैं भेज रहा हूँ ");
        map.put("Have I been becoming ", "  क्या मैं बन रहा हूँ ");
        map.put("Have I been shaking ", "  क्या मैं हिल रहा हूँ ");
        map.put("Have I been begging ", "  क्या मैं भीख माँग रहा हूँ ");
        map.put("Have I been beginning ", "  क्या मैं शुरुआत कर रहा हूँ ");
        map.put("Have I been biting ", "  क्या मैं काट रहा हूँ ");
        map.put("Have I been blessing ", "  क्या मैं आशीष रहा हूँ ");
        map.put("Have I been blowing ", "  क्या मैं उड़ रहा हूँ ");
        map.put("Have I been breaking ", "  क्या मैं तोड़ रहा हूँ ");
        map.put("Have I been bringing ", "  क्या मैं ला रहा हूँ ");
        map.put("Have I been building ", "  क्या मैं निर्माण कर रहा हूँ ");
        map.put("Have I been burning ", "  क्या मैं जल रहा हूँ ");
        map.put("Have I been buying ", "  क्या मैं खरीद रहा हूँ ");
        map.put("Have I been calling ", "  क्या मैं फोन कर रहा हूँ ");
        map.put("Have I been carrying ", "  क्या मैं ले जा रहा हूँ ");
        map.put("Have I been catching ", "  क्या मैं पकड़ रहा हूँ ");
        map.put("Have I been cheating ", "  क्या मैं धोखा दे रहा हूँ ");
        map.put("Have I been choosing ", "  क्या मैं चुन रहा हूं ");
        map.put("Have I been cleaning ", "  क्या मैं सफाई कर रहा हूँ ");
        map.put("Have I been climbing ", "  क्या मैं चढ़ रहा हूँ ");
        map.put("Have I been closing ", "  क्या मैं बंद कर रहा हूँ ");

        return map;
    }
    private static Map<String, String> Three() {
        HashMap<String,String>map = new HashMap<>();
        map.put("Have I abused ", "  क्या मैंने गाली दी है ");
        map.put("Have I come ", "  क्या मैं आया हूँ ");
        map.put("Have I cooked ", "  मैंने खाना बनाया है ");
        map.put("Have I crept ", "  क्या मैंने क्रेप किया है ");
        map.put("Have I cried ", "  क्या मैंने रोया है ");
        map.put("Have I cut ", "  मैंने काट दिया है ");
        map.put("Have I danced ", "  क्या मैंने नृत्य किया है ");
        map.put("Have I dealt ", "  क्या मैंने निपटाया है ");
        map.put("Have I died ", "  क्या मैं मर गया ");
        map.put("Have I dug ", "  क्या मैंने खोदा है ");
        map.put("Have I done ", "  मैंने किया है ");
        map.put("Have I drawn ", "  क्या मैंने खींचा है ");
        map.put("Have I advised ", "  क्या मैंने सलाह दी है ");
        map.put("Have I drunk ", "  क्या मैंने पिया है ");
        map.put("Have I driven ", "  क्या मैंने चलाया है ");
        map.put("Have I dropped ", "  क्या मैंने गिरा दिया है ");
        map.put("Have I dried ", "  क्या मैंने सूख लिया है ");
        map.put("Have I eaten ", "  क्या मैंने खा लिया है ");
        map.put("Have I elected ", "  क्या मैंने चुना है ");
        map.put("Have I undefined", "  क्या मैंने अपरिभाषित किया है");
        map.put("Have I answered ", "  क्या मैंने जवाब दिया है ");
        map.put("Have I entered ", "  क्या मैंने प्रवेश किया है ");
        map.put("Have I fallen ", "  मैं गिर गया हूँ ");
        map.put("Have I fed ", "  क्या मैंने खिलाया है ");
        map.put("Have I felt ", "  क्या मैंने महसूस किया है ");
        map.put("Have I fought ", "  क्या मैंने लड़ाई लड़ी है ");
        map.put("Have I found ", "  क्या मैंने पाया है ");
        map.put("Have I fled ", "  क्या मैं भाग गया ");
        map.put("Have I flown ", "  क्या मैंने उड़ान भरी है ");
        map.put("Have I forgotten ", "  क्या मैं भूल गया हूँ ");
        map.put("Have I fried ", "  क्या मैंने फ्राई किया है ");
        map.put("Have I arisen ", "  क्या मैं पैदा हुआ हूँ ");
        map.put("Have I got ", "  मुझे मिल गया है ");
        map.put("Have I given ", "  क्या मैंने दिया है ");
        map.put("Have I gone ", "  मैं गया हूँ ");
        map.put("Have I grown ", "  क्या मैं बड़ा हो गया हूँ ");
        map.put("Have I hanged ", "  क्या मैंने फांसी लगा ली है ");
        map.put("Have I hung ", "  क्या मैंने लटका दिया है ");
        map.put("Have I heard ", "  क्या मैंने सुना है ");
        map.put("Have I helped ", "  क्या मैंने मदद की है ");
        map.put("Have I hidden ", "  क्या मैंने छुपाया है ");
        map.put("Have I hit ", "  क्या मैंने मारा है ");
        map.put("Have I held ", "  क्या मैंने आयोजित किया है ");
        map.put("Have I arrived ", "  मैं आ गया हूँ ");
        map.put("Have I hoped ", "  क्या मैंने आशा की है ");
        map.put("Have I hurt ", "  क्या मुझे चोट लगी है ");
        map.put("Have I jumped ", "  क्या मैं कूद गया ");
        map.put("Have I kept ", "  क्या मैंने रखा है ");
        map.put("Have I killed ", "  क्या मैंने मार डाला है ");
        map.put("Have I known ", "  क्या मुझे पता है ");
        map.put("Have I laughed ", "  क्या मैं हँसा हूँ ");
        map.put("Have I led ", "  क्या मैंने नेतृत्व किया है ");
        map.put("Have I leapt ", "  क्या मैंने छलांग लगाई है ");
        map.put("Have I learnt ", "  क्या मैंने सीखा है ");
        map.put("Have I left ", "  क्या मैंने छोड़ा है ");
        map.put("Have I lent ", "  क्या मैंने उधार दिया है ");
        map.put("Have I asked ", "  क्या मैंने पूछा है ");
        map.put("Have I lived ", "  क्या मैं रहता हूँ ");
        map.put("Have I awoken ", "  क्या मैं जाग गया हूँ ");
        map.put("Have I looked ", "  मैंने देखा है ");
        map.put("Have I lost ", "  क्या मैंने खो दिया है ");
        map.put("Have I loved ", "  क्या मैंने प्यार किया है ");
        map.put("Have I made ", "  क्या मैंने बनाया है ");
        map.put("Have I married ", "  क्या मैंने शादी की है ");
        map.put("Have I met ", "  क्या मैं मिला हूँ ");
        map.put("Have I mistaken ", "  क्या मैंने गलत किया है ");
        map.put("Have I opened ", "  क्या मैंने खोला है ");
        map.put("Have I paid ", "  क्या मैंने भुगतान किया है ");
        map.put("Have I played ", "  क्या मैंने खेला है ");
        map.put("Have I put ", "  क्या मैंने रखा है ");
        map.put("Have I quarrelled ", "  क्या मैंने झगड़ा किया है ");
        map.put("Have I rained ", "  क्या मैंने बारिश की है ");
        map.put("Have I borne ", "  क्या मैंने जन्म लिया है ");
        map.put("Have I reached ", "  मैं पहुँच गया हूँ ");
        map.put("Have I read ", "  क्या मैंने पढ़ा है ");
        map.put("Have I remembered ", "  क्या मुझे याद आया ");
        map.put("Have I ridden ", "  क्या मैंने सवारी की है ");
        map.put("Have I rung ", "  क्या मैंने बजाया है ");
        map.put("Have I beaten ", "  क्या मैंने पीटा है ");
        map.put("Have I risen ", "  क्या मैं उठ गया हूँ ");
        map.put("Have I run ", "  क्या मैंने दौड़ा है ");
        map.put("Have I said ", "  क्या मैंने कहा है ");
        map.put("Have I seen ", "  क्या मैंने देखा है ");
        map.put("Have I sold ", "  क्या मैंने बेचा है ");
        map.put("Have I sent ", "  क्या मैंने भेजा है ");
        map.put("Have I become ", "  मैं बन गया हूँ ");
        map.put("Have I shaken ", "  क्या मैंने हिला दिया है ");
        map.put("Have I begged ", "  मैंने भीख माँगी है ");
        map.put("Have I begun ", "  क्या मैंने शुरू किया है ");
        map.put("Have I bound ", "  क्या मैंने बाध्य किया है ");
        map.put("Have I bitten ", "  क्या मैंने काट लिया है ");
        map.put("Have I blessed ", "  क्या मैंने आशीर्वाद दिया है ");
        map.put("Have I blown ", "  क्या मैंने उड़ा दिया है ");
        map.put("Have I broken ", "  क्या मैंने तोड़ दिया है ");
        map.put("Have I brought ", "  मैं लाया हूँ ");
        map.put("Have I built ", "  मैंने बनाया है ");
        map.put("Have I burnt ", "  क्या मैंने जला दिया है ");
        map.put("Have I bought ", "  क्या मैंने खरीदा है ");
        map.put("Have I called ", "  क्या मैंने फोन किया है ");
        map.put("Have I carried ", "  क्या मैंने किया है ");
        map.put("Have I caught ", "  क्या मैंने पकड़ लिया है ");
        map.put("Have I cheated ", "  क्या मैंने धोखा दिया है ");
        map.put("Have I chosen ", "  क्या मैंने चुना है ");
        map.put("Have I cleaned ", "  क्या मैंने साफ किया है ");
        map.put("Have I climbed ", "  क्या मैं चढ़ गया हूँ ");
        map.put("Have I closed ", "  क्या मैंने बंद कर दिया है ");

        return map;
    }
    private static Map<String, String> Two() {
        HashMap<String,String>map = new HashMap<>();
        map.put("Am I abusing ", " क्या मैं गाली दे रहा हूँ ");
        map.put("Am I coming ", " क्या मैं आ रहा हूँ ");
        map.put("Am I cooking ", " क्या मैं खाना बना रहा हूँ ");
        map.put("Am I creeping ", " क्या मैं रेंग रहा हूँ ");
        map.put("Am I crying ", " क्या मैं रो रहा हूँ ");
        map.put("Am I cutting ", " क्या मैं काट रहा हूँ ");
        map.put("Am I dancing ", " क्या मैं नाच रहा हूँ ");
        map.put("Am I dealing ", " क्या मैं काम कर रहा हूँ ");
        map.put("Am I dying ", " क्या मैं मर रहा हूँ ");
        map.put("Am I digging ", " क्या मैं खुदाई कर रहा हूँ ");
        map.put("Am I doing ", " क्या मैं कर रहा हूँ ");
        map.put("Am I drawing ", " क्या मैं ड्राइंग कर रहा हूँ ");
        map.put("Am I advising ", " क्या मैं सलाह दे रहा हूँ ");
        map.put("Am I dreaming ", " क्या मैं सपना देख रहा हूँ ");

        map.put("Am I drinking ", " क्या मैं पी रहा हूँ ");
        map.put("Am I driving ", " क्या मैं गाड़ी चला रहा हूँ ");
        map.put("Am I dropping ", " क्या मैं गिर रहा हूँ ");
        map.put("Am I drying ", " क्या मैं सूख रहा हूँ ");
        map.put("Am I eating ", " क्या मैं खा रहा हूँ ");
        map.put("Am I electing ", " क्या मैं चुनाव कर रहा हूँ ");
        map.put("Am I undefined", " क्या मैं अपरिभाषित हूँ");
        map.put("Am I answering ", " क्या मैं जवाब दे रहा हूँ ");
        map.put("Am I entering ", " क्या मैं प्रवेश कर रहा हूँ ");
        map.put("Am I falling ", " क्या मैं गिर रहा हूँ ");
        map.put("Am I feeding ", " क्या मैं खिला रहा हूँ ");
        map.put("Am I feeling ", " क्या मैं महसूस कर रहा हूँ ");
        map.put("Am I fighting ", " क्या मैं लड़ रहा हूँ ");
        map.put("Am I finding ", " क्या मैं खोज रहा हूँ ");
        map.put("Am I fleeing ", " क्या मैं भाग रहा हूँ ");
        map.put("Am I flying ", " क्या मैं उड़ रहा हूँ ");
        map.put("Am I forgetting ", " क्या मैं भूल रहा हूँ ");
        map.put("Am I frying ", " क्या मैं तलने वाला हूँ ");
        map.put("Am I arising ", " क्या मैं उठ रहा हूँ ");
        map.put("Am I getting ", " क्या मुझे मिल रहा है ");
        map.put("Am I giving ", " क्या मैं दे रहा हूँ ");
        map.put("Am I going ", " क्या मैं जा रहा हूँ ");
        map.put("Am I growing ", " क्या मैं बढ़ रहा हूँ ");
        map.put("Am I hanging ", " क्या मैं लटक रहा हूँ ");
        map.put("Am I hearing ", " क्या मैं सुन रहा हूँ ");
        map.put("Am I helping ", " क्या मैं मदद कर रहा हूँ ");
        map.put("Am I hiding ", " क्या मैं छुपा रहा हूँ ");
        map.put("Am I hitting ", " क्या मैं मार रहा हूँ ");
        map.put("Am I holding ", " क्या मैं पकड़ रहा हूँ ");
        map.put("Am I arriving ", " क्या मैं आ रहा हूँ ");
        map.put("Am I hoping ", " क्या मैं उम्मीद कर रहा हूँ ");
        map.put("Am I hurting ", " क्या मैं चोट पहुँचा रहा हूँ ");
        map.put("Am I jumping ", " क्या मैं कूद रहा हूँ ");
        map.put("Am I keeping ", " क्या मैं रख रहा हूँ ");
        map.put("Am I killing ", " क्या मैं मार रहा हूँ ");
        map.put("Am I knowing ", " क्या मैं जान रहा हूँ ");
        map.put("Am I laughing ", " क्या मैं हँस रहा हूँ ");
        map.put("Am I leading ", " क्या मैं अग्रणी हूँ ");
        map.put("Am I leaping ", " क्या मैं छलांग लगा रहा हूँ ");
        map.put("Am I learning ", " क्या मैं सीख रहा हूँ ");
        map.put("Am I leaving ", " क्या मैं जा रहा हूँ ");
        map.put("Am I asking ", " क्या मैं पूछ रहा हूँ ");
        map.put("Am I lending ", " क्या मैं उधार दे रहा हूँ ");
        map.put("Am I living ", " क्या मैं जी रहा हूँ ");
        map.put("Am I awaking ", " क्या मैं जाग रहा हूँ ");
        map.put("Am I looking ", " क्या मैं देख रहा हूँ ");
        map.put("Am I losing ", " क्या मैं हार रहा हूँ ");
        map.put("Am I loving ", " क्या मैं प्यार कर रहा हूँ ");
        map.put("Am I making ", " क्या मैं बना रहा हूँ ");
        map.put("Am I marrying ", " क्या मैं शादी कर रहा हूँ ");
        map.put("Am I meeting ", " क्या मैं मिल रहा हूँ ");
        map.put("Am I mistaking ", " क्या मैं गलती कर रहा हूँ ");
        map.put("Am I opening ", " क्या मैं खोल रहा हूँ ");
        map.put("Am I paying ", " क्या मैं भुगतान कर रहा हूँ ");
        map.put("Am I playing ", " क्या मैं खेल रहा हूँ ");
        map.put("Am I putting ", " क्या मैं डाल रहा हूँ ");
        map.put("Am I quarrelling ", " क्या मैं झगड़ा कर रहा हूँ ");
        map.put("Am I raining ", " क्या मैं बारिश कर रहा हूँ ");
        map.put("Am I bearing ", " क्या मैं असर कर रहा हूँ ");
        map.put("Am I reaching ", " क्या मैं पहुँच रहा हूँ ");
        map.put("Am I reading ", " क्या मैं पढ़ रहा हूँ ");
        map.put("Am I remembering ", " क्या मुझे याद है ");
        map.put("Am I riding ", " क्या मैं सवारी कर रहा हूँ ");
        map.put("Am I ringing ", " क्या मैं बज रहा हूँ ");
        map.put("Am I beating ", " क्या मैं पिटाई कर रहा हूँ ");
        map.put("Am I rising ", " क्या मैं उठ रहा हूँ ");
        map.put("Am I running ", " क्या मैं दौड़ रहा हूँ ");
        map.put("Am I saying ", " क्या मैं कह रहा हूँ ");
        map.put("Am I seeing ", " क्या मैं देख रहा हूँ ");
        map.put("Am I selling ", " क्या मैं बेच रहा हूँ ");
        map.put("Am I becoming ", " क्या मैं बन रहा हूँ ");
        map.put("Am I sending ", " क्या मैं भेज रहा हूँ ");
        map.put("Am I shaking ", " क्या मैं हिल रहा हूँ ");
        map.put("Am I begging ", " मैं भीख माँग रहा हूँ ");
        map.put("Am I beginning ", " क्या मैं शुरुआत कर रहा हूँ ");
        map.put("Am I biting ", " क्या मैं काट रहा हूँ ");
        map.put("Am I blessing ", " क्या मैं आशीर्वाद दे रहा हूँ ");
        map.put("Am I blowing ", " क्या मैं उड़ रहा हूँ ");
        map.put("Am I breaking ", " क्या मैं तोड़ रहा हूँ ");
        map.put("Am I bringing ", " क्या मैं ला रहा हूँ ");
        map.put("Am I building ", " क्या मैं निर्माण कर रहा हूँ ");
        map.put("Am I burning ", " क्या मैं जल रहा हूँ ");
        map.put("Am I buying ", " क्या मैं खरीद रहा हूँ ");
        map.put("Am I calling ", " क्या मैं कॉल कर रहा हूँ ");
        map.put("Am I carrying ", " क्या मैं ले जा रहा हूँ ");
        map.put("Am I catching ", " क्या मैं पकड़ रहा हूँ ");
        map.put("Am I cheating ", " क्या मैं धोखा दे रहा हूँ ");
        map.put("Am I choosing ", " क्या मैं चुन रहा हूँ ");
        map.put("Am I cleaning ", " क्या मैं सफाई कर रहा हूँ ");
        map.put("Am I climbing ", " क्या मैं चढ़ रहा हूँ ");
        map.put("Am I closing ", " क्या मैं बंद कर रहा हूँ ");
        return map;
    }

    private static Map<String, String> One() {
        HashMap<String,String>map = new HashMap<>();
        map.put("Do I abuse ", " क्या मैं गाली देता हूँ ");
        map.put("Do I come ", " क्या मैं आता हूँ ");
        map.put("Do I cook ", " क्या मैं खाना बनाती हूँ ");
        map.put("Do I creep ", " क्या मैं रेंगता हूँ ");
        map.put("Do I cry ", " क्या मैं रोता हूँ ");
        map.put("Do I cut ", " क्या मैं काटता हूँ ");
        map.put("Do I dance ", " क्या मैं नृत्य करता हूँ ");
        map.put("Do I deal ", " क्या मैं सौदा करता हूँ ");
        map.put("Do I die ", " क्या मैं मर जाऊं ");
        map.put("Do I dig ", " क्या मैं खोदता हूँ ");
        map.put("Do I draw ", " क्या मैं आकर्षित करता हूँ ");
        map.put("Do I advise", " क्या मैं सलाह देता हूँ");
        map.put("Do I drive ", " क्या मैं ड्राइव करता हूँ ");
        map.put("Do I drop ", " क्या मैं छोड़ता हूँ ");
        map.put("Do I dry ", " क्या मैं सुखाता हूँ ");
        map.put("Do I eat ", " क्या मैं खाता हूँ ");
        map.put("Do I elect", " क्या मैं चुनाव करता हूँ");
        map.put("Do I answer ", " क्या मैं जवाब देता हूँ ");
        map.put("Do I fall ", " क्या मैं गिरता हूँ ");
        map.put("Do I feed ", " क्या मैं खिलाता हूँ ");
        map.put("Do I feel  ", " क्या मुझे लगता है  ");
        map.put("Do I fight ", " क्या मैं लड़ता हूँ ");
        map.put("Do I find ", " क्या मुझे मिल रहा है ");
        map.put("Do I flee ", " क्या मैं भागता हूँ ");
        map.put("Do I fly  ", " क्या मैं उड़ता हूँ  ");
        map.put("Do I forget ", " क्या मैं भूल जाऊं ");
        map.put("Do I fry ", " क्या मैं भूनता हूँ ");
        map.put("Do I arise ", " क्या मैं उठता हूँ ");
        map.put("Do I get  ", " क्या मुझे मिलता है  ");
        map.put("Do I give ", " क्या मैं देता हूँ ");
        map.put("Do I go ", " क्या मैं जाऊं ");
        map.put("Do I grow", " क्या मैं बढ़ता हूँ");
        map.put("Do I hang ", " क्या मैं लटका देता हूँ ");
        map.put("Do I hear ", " क्या मैं सुनता हूँ ");
        map.put("Do I help ", " क्या मैं मदद करता हूँ ");
        map.put("Do I hide ", " क्या मैं छिपाता हूँ ");
        map.put("Do I hit ", " क्या मैं हिट करता हूँ ");
        map.put("Do I hold ", " क्या मैं पकड़ता हूँ ");
        map.put("Do I arrive ", " क्या मैं आता हूँ ");
        map.put("Do I hope ", " क्या मुझे उम्मीद है ");
        map.put("Do I hurt ", " क्या मुझे चोट लगी है ");
        map.put("Do I jump ", " क्या मैं कूदता हूँ ");
        map.put("Do I kill ", " क्या मैं मारता हूँ ");
        map.put("Do I know ", " क्या मुझे पता है ");
        map.put("Do I laugh ", " क्या मैं हंसता हूँ ");
        map.put("Do I lead ", " क्या मैं नेतृत्व करता हूँ ");
        map.put("Do I leap ", " क्या मैं छलांग लगाता हूँ ");
        map.put("Do I learn ", " क्या मैं सीखता हूँ ");
        map.put("Do I leave ", " क्या मैं छोड़ता हूँ ");
        map.put("Do I ask ", " क्या मैं पूछता हूँ ");
        map.put("Do I lend ", " क्या मैं उधार देता हूँ ");
        map.put("Do I live ", " क्या मैं रहता हूँ ");
        map.put("Do I awake ", " क्या मैं जागता हूँ ");
        map.put("Do I look ", " क्या मैं देखता हूँ ");
        map.put("Do I lose ", " क्या मैं हारता हूँ ");
        map.put("Do I love ", " क्या मैं प्यार करता हूँ ");
        map.put("Do I make ", " क्या मैं बना सकता हूँ ");
        map.put("Do I marry ", " क्या मैं शादी करता हूँ ");
        map.put("Do I meet ", " क्या मैं मिलूँ ");
        map.put("Do I mistake ", " क्या मैं गलती करता हूँ ");
        map.put("Do I open ", " क्या मैं खोलता हूँ ");
        map.put("Do I pay  ", " क्या मैं भुगतान करता हूँ  ");
        map.put("Do I play ", " क्या मैं खेलता हूँ ");
        map.put("Do I put ", " क्या मैं डालता हूँ ");
        map.put("Do I rain ", " क्या मैं बारिश करता हूँ ");
        map.put("Do I bear ", " क्या मैं सहन करता हूँ ");
        map.put("Do I reach ", " क्या मैं पहुँचता हूँ ");
        map.put("Do I read", " क्या मैं पढ़ता हूँ");
        map.put("Do I remember  ", " क्या मुझे याद है  ");
        map.put("Do I ride ", " क्या मैं सवारी करता हूँ ");
        map.put("Do I ring ", " क्या मैं रिंग करता हूँ ");
        map.put("Do I beat ", " क्या मैं हराता हूँ ");
        map.put("Do I rise  ", " क्या मैं उठता हूँ  ");
        map.put("Do I run  ", " क्या मैं दौड़ता हूँ  ");
        map.put("Do I say ", " क्या मैं कहता हूँ ");
        map.put("Do I see ", " क्या मैं देख रहा हूँ ");
        map.put("Do I sell ", " क्या मैं बेचता हूँ ");
        map.put("Do I send ", " क्या मैं भेजूँ ");
        map.put("Do I become ", " क्या मैं बन जाऊं ");
        map.put("Do I shake ", " क्या मैं हिलाता हूँ ");
        map.put("Do I beg ", " क्या मैं भीख मांगता हूँ ");
        map.put("Do I begin ", " क्या मैं शुरू करता हूँ ");
        map.put("Do I bind ", " क्या मैं बाँधता हूँ ");
        map.put("Do I bite", " क्या मैं काटता हूँ");
        map.put("Do I bless", " क्या मैं आशीर्वाद देता हूँ");
        map.put("Do I blow ", " क्या मैं उड़ाता हूँ ");
        map.put("Do I break ", " क्या मैं तोड़ता हूँ ");
        map.put("Do I bring ", " क्या मैं लाता हूँ ");
        map.put("Do I build ", " क्या मैं निर्माण करता हूँ ");
        map.put("Do I burn ", " क्या मैं जलाता हूँ ");
        map.put("Do I buy ", " क्या मैं खरीदता हूँ ");
        map.put("Do I call ", " क्या मैं कॉल करता हूँ ");
        map.put("Do I carry ", " क्या मैं ले जाता हूँ ");
        map.put("Do I catch ", " क्या मैं पकड़ता हूँ ");
        map.put("Do I choose ", " क्या मैं चुनता हूँ ");
        map.put("Do I clean ", " क्या मैं साफ करता हूँ ");
        map.put("Do I climb  ", " क्या मैं चढ़ता हूँ  ");
        map.put("Do I close ", " क्या मैं बंद करता हूँ ");

        return map;
    }
}
