package com.shiviishiv7.helloenglish.QuestionSource;


import java.util.HashMap;
import java.util.Map;

public class When {
    static public Map<String,String> When(int state){
        switch (state){
            case 1:return One();
            case 2:return Two();
            case 3:return Three();
            case 4:return Four();
            case 5:return Five();
            case 6:return Six();
            case 7:return Seven();
            case 8:return Eight();
            case 9:return Nine();
            case 10:return Ten();
            case 11:return Eleven();
            case 12:return Twelve();

            default:return One();
        }

    }
    static Map<String,String> One(){
        HashMap<String,String>map = new HashMap<>();
        map.put("When do I abuse ", "मैं कब गाली दूं ");
        map.put("When do I advise", "मैं कब सलाह दूँ");
        map.put("When do I answer ", "मैं कब जवाब दूँ ");
        map.put("When do I arise ", "मैं कब उठता हूँ ");
        map.put("When do I arrive ", "मैं कब आऊं ");
        map.put("When do I ask ", "मैं कब पूछूँ ");
        map.put("When do I awake ", "मैं कब जाग सकता हूँ ");

        map.put("When do I bear ", "मैं कब सहन करूँ ");
        map.put("When do I beat ", "मैं कब हराऊं ");
        map.put("When do I become ", "मैं कब बन जाऊं ");
        map.put("When do I beg ", "मैं कब भीख माँगता हूँ ");
        map.put("When do I begin ", "मैं कब शुरू करूँ ");
        map.put("When do I bind ", "मैं कब बाँध सकता हूँ ");
        map.put("When do I bite", "मैं कब काटूं");
        map.put("When do I bless", "मैं कब आशीष देता हूँ");
        map.put("When do I blow ", "मैं कब उड़ाऊं ");
        map.put("When do I break ", "मैं कब तोड़ूँ ");
        map.put("When do I bring ", "मैं कब लाऊं ");
        map.put("When do I build ", "मैं कब निर्माण करूँ ");
        map.put("When do I burn ", "मैं कब जलाता हूँ ");
        map.put("When do I buy ", "मैं कब खरीदूं ");
        map.put("When do I call ", "मैं कब कॉल करूँ ");
        map.put("When do I carry ", "मैं कब ले जाऊं ");
        map.put("When do I catch ", "मैं कब पकड़ूं ");
        map.put("When do I choose ", "मैं कब चुनूं ");
        map.put("When do I clean ", "मैं कब साफ करूँ ");
        map.put("When do I climb  ", "मैं कब चढ़ूँ  ");
        map.put("When do I close ", "मैं कब बंद करूँ ");
        map.put("When do I come ", "मैं कब आऊं ");
        map.put("When do I cook ", "मैं कब खाना बनाती हूँ ");
        map.put("When do I creep ", "मैं कब रेंगता हूँ ");
        map.put("When do I cry ", "मैं कब रोता हूँ ");
        map.put("When do I cut ", "मैं कब काटूं ");
        map.put("When do I dance ", "मैं कब नाचता हूँ ");
        map.put("When do I deal ", "मैं कब सौदा करूँ ");
        map.put("When do I die ", "मैं कब मरूँ ");
        map.put("When do I dig ", "मैं कब खोदूँ ");
        map.put("When do I do ", "मैं कब करूँ ");
        map.put("When  did I  do ", "मैंने कब किया ");
        map.put("When  was I  doing ", "मैं कब कर रहा था ");
        map.put("When  will I do ", "मैं कब करूँगा ");
        map.put("When  had I  done ", "मैंने कब किया था ");
        map.put("When  will I be doing ", "मैं कब कर रहा हूँ ");
        map.put("When  will I have been doing ", "मैं कब कर रहा हूँ ");
        map.put("When do I draw ", "मैं कब आकर्षित करूँ ");
        map.put("When  had I been  doing ", "मैं कब कर रहा था ");
        map.put("When  will I have done ", "मैंने कब किया होगा ");
        map.put("When do I drive ", "मैं कब ड्राइव करूँ ");
        map.put("When do I drop ", "मैं कब छोड़ूँ ");
        map.put("When do I dry ", "मैं कब सुखाऊं ");
        map.put("When do I eat ", "मैं कब खाऊं ");
        map.put("When do I elect", "मैं कब चुनाव करूँ");
        map.put("When do I fall ", "मैं कब गिरता हूँ ");
        map.put("When do I feed ", "मैं कब खिलाऊं ");
        map.put("When do I feel  ", "मुझे कब लगता है  ");
        map.put("When do I fight ", "मैं कब लड़ूं ");
        map.put("When do I find ", "मुझे कब मिलेगा ");
        map.put("When do I flee ", "मैं कब भागता हूँ ");
        map.put("When do I fly  ", "मैं कब उड़ूँ  ");
        map.put("When do I forget ", "मैं कब भूलूं ");
        map.put("When do I fry ", "मैं कब भूनूं ");
        map.put("When do I get  ", "मुझे कब मिलेगा  ");
        map.put("When do I give ", "मैं कब देता हूँ ");
        map.put("When do I go ", "मैं कब जाऊँ ");
        map.put("When do I grow", "मैं कब उगता हूँ");
        map.put("When do I hang ", "मैं कब लटकाऊं ");
        map.put("When do I hear ", "मैं कब सुनता हूँ ");
        map.put("When do I help ", "मैं कब मदद करूँ ");
        map.put("When do I hide ", "मैं कब छिपाऊं ");
        map.put("When do I hit ", "मैं कब मारूं ");
        map.put("When do I hold ", "मैं कब पकड़ सकता हूँ ");
        map.put("When do I hope ", "मुझे कब उम्मीद है ");
        map.put("When do I hurt ", "मुझे कब चोट लगी है ");
        map.put("When do I jump ", "मैं कब कूदता हूँ ");
        map.put("When do I kill ", "मैं कब मारूं ");
        map.put("When do I know ", "मुझे कब पता है ");
        map.put("When do I laugh ", "मैं कब हँसता हूँ ");
        map.put("When do I lead ", "मैं कब नेतृत्व करूँ ");
        map.put("When do I leap ", "मैं कब छलांग लगाऊं ");
        map.put("When do I learn ", "मैं कब सीखता हूँ ");
        map.put("When do I leave ", "मैं कब छोड़ूँ ");
        map.put("When do I lend ", "मैं कब उधार दे सकता हूँ ");
        map.put("When do I live ", "मैं कब रहूँ ");
        map.put("When do I look ", "मैं कब देखूं ");
        map.put("When do I lose ", "मैं कब हारूं ");
        map.put("When do I love ", "मैं कब प्यार करता हूँ ");
        map.put("When do I make ", "मैं कब बनाऊँ ");
        map.put("When do I marry ", "मैं शादी कब करूँ ");
        map.put("When do I meet ", "मैं कब मिलूँ ");
        map.put("When do I mistake ", "मैं कब गलती करूँ ");
        map.put("When do I open ", "मैं कब खोलूं ");
        map.put("When do I pay  ", "मैं कब भुगतान करूँ  ");
        map.put("When do I play ", "मैं कब खेलूँ ");
        map.put("When do I put ", "मैं कब रखूँ ");
        map.put("When do I rain ", "मैं बारिश कब करूँ ");
        map.put("When do I reach ", "मैं कब पहुँचूँ ");
        map.put("When do I read", "मैं कब पढ़ूँ");
        map.put("When do I remember  ", "मुझे कब याद है  ");
        map.put("When do I ride ", "मैं कब सवारी करूँ ");
        map.put("When do I ring ", "मैं कब रिंग करूँ ");
        map.put("When do I rise  ", "मैं कब उठूँ  ");
        map.put("When do I run  ", "मैं कब दौड़ूँ  ");
        map.put("When do I say ", "मैं कब कहूँ ");
        map.put("When do I see ", "मैं कब देखूं ");
        map.put("When do I sell ", "मैं कब बेचूँ ");
        map.put("When do I send ", "मैं कब भेजूं ");
        map.put("When do I shake ", "मैं कब हिला सकता हूँ ");
        map.put("When do I shine ", "मैं कब चमकता हूँ ");
        map.put("When do I shoot ", "मैं कब शूट करूँ ");
        map.put("When do I show ", "मैं कब दिखाऊं ");
        map.put("When do I shut  ", "मैं कब बंद करूँ  ");
        map.put("When do I sing ", "मैं कब गाऊं ");
        map.put("When do I sink ", "मैं कब डूबता हूँ ");
        map.put("When do I sleep ", "मैं कब सोता हूँ ");
        map.put("When do I smell ", "मुझे कब सूंघना है ");
        map.put("When do I speak ", "मैं कब बोलूं ");
        map.put("When do I spoil", "मैं कब खराब करूँ");
        map.put("When do I steal ", "मैं कब चोरी करूँ ");
        map.put("When do I write ", "मैं कब लिखूं ");

        return map;
    }
    static Map<String,String> Two(){
        HashMap<String,String>map = new HashMap<>();
        map.put("When am I binding ", "मैं कब बाध्यकारी हूँ ");
        map.put("When am I abusing ", "मैं कब गाली दे रहा हूँ ");
        map.put("When am I advising ", "मैं कब सलाह दे रहा हूँ ");
        map.put("When am I answering ", "मैं कब जवाब दे रहा हूँ ");
        map.put("When am I arising ", "मैं कब उठ रहा हूँ ");
        map.put("When am I arriving ", "मैं कब आ रहा हूँ ");
        map.put("When am I asking ", "मैं कब पूछ रहा हूँ ");
        map.put("When am I awaking ", "मैं कब जाग रहा हूँ ");
        map.put("When am I undefined", "मैं कब अपरिभाषित हूँ");
        map.put("When am I bearing ", "मैं कब असर कर रहा हूँ ");
        map.put("When am I beating ", "मैं कब पिटाई कर रहा हूँ ");
        map.put("When am I becoming ", "मैं कब बन रहा हूँ ");
        map.put("When am I begging ", "मैं कब भीख माँग रहा हूँ ");
        map.put("When am I beginning ", "मैं कब शुरू कर रहा हूँ ");
        map.put("When am I biting ", "मैं कब काट रहा हूँ ");
        map.put("When am I blessing ", "मैं कब आशीष दे रहा हूँ ");
        map.put("When am I blowing ", "मैं कब उड़ रहा हूँ ");
        map.put("When am I breaking ", "मैं कब तोड़ रहा हूँ ");
        map.put("When am I bringing ", "मैं कब ला रहा हूँ ");
        map.put("When am I building ", "मैं कब निर्माण कर रहा हूँ ");
        map.put("When am I burning ", "मैं कब जल रहा हूँ ");
        map.put("When am I buying ", "मैं कब खरीद रहा हूँ ");
        map.put("When am I calling ", "मैं कब कॉल कर रहा हूँ ");
        map.put("When am I carrying ", "मैं कब ले जा रहा हूँ ");
        map.put("When am I catching ", "मैं कब पकड़ रहा हूँ ");
        map.put("When am I cheating ", "मैं कब धोखा दे रहा हूँ ");
        map.put("When am I choosing ", "मैं कब चुन रहा हूँ ");
        map.put("When am I cleaning ", "मैं कब सफाई कर रहा हूँ ");
        map.put("When am I climbing ", "मैं कब चढ़ रहा हूँ ");
        map.put("When am I closing ", "मैं कब बंद कर रहा हूँ ");
        map.put("When am I coming ", "मैं कब आ रहा हूँ ");
        map.put("When am I cooking ", "मैं कब खाना बना रहा हूँ ");
        map.put("When am I creeping ", "मैं कब रेंग रहा हूँ ");
        map.put("When am I crying ", "मैं कब रो रहा हूँ ");
        map.put("When am I cutting ", "मैं कब काट रहा हूँ ");
        map.put("When am I dancing ", "मैं कब नाच रहा हूँ ");
        map.put("When am I dealing ", "मैं कब काम कर रहा हूँ ");
        map.put("When am I dying ", "मैं कब मर रहा हूँ ");
        map.put("When am I digging ", "मैं कब खुदाई कर रहा हूँ ");
        map.put("When am I doing ", "मैं कब कर रहा हूँ ");
        map.put("When am I drawing ", "मैं कब ड्राइंग कर रहा हूँ ");
        map.put("When do I dream ", "मैं कब सपना देखता हूँ ");
        map.put("When  have I dreamt ", "मैंने कब सपना देखा है ");
        map.put("When  have I been dreaming ", "मैं कब सपना देख रहा था ");
        map.put("When am I dreaming ", "मैं कब सपना देख रहा हूँ ");
        map.put("When  did I  dream ", "मैंने कब सपना देखा ");
        map.put("When  was I  dreaming ", "मैं कब सपना देख रहा था ");
        map.put("When  had I  dreamt ", "मैंने कब सपना देखा था ");
        map.put("When  had I been  dreaming ", "मैं कब सपना देख रहा था ");
        map.put("When  will I be dreaming ", "मैं कब सपना देख रहा हूँ ");
        map.put("When  will I have dreamt ", "मैंने कब सपना देखा होगा ");
        map.put("When  will I have been dreaming ", "मैं कब सपना देख रहा हूँ ");
        map.put("When am I drinking ", "मैं कब पी रहा हूँ ");
        map.put("When am I driving ", "मैं कब गाड़ी चला रहा हूँ ");
        map.put("When am I dropping ", "मैं कब छोड़ रहा हूँ ");
        map.put("When am I drying ", "मैं कब सुखा रहा हूँ ");
        map.put("When am I electing ", "मैं कब चुनाव कर रहा हूँ ");
        map.put("When am I eating ", "मैं कब खा रहा हूँ ");
        map.put("When am I entering ", "मैं कब प्रवेश कर रहा हूँ ");
        map.put("When am I falling ", "मैं कब गिर रहा हूँ ");
        map.put("When am I feeding ", "मैं कब खिला रहा हूँ ");
        map.put("When am I feeling ", "मैं कब महसूस कर रहा हूँ ");
        map.put("When am I fighting ", "मैं कब लड़ रहा हूँ ");
        map.put("When am I finding ", "मुझे कब मिल रहा है ");
        map.put("When am I fleeing ", "मैं कब भाग रहा हूँ ");
        map.put("When am I flying ", "मैं कब उड़ रहा हूँ ");
        map.put("When am I forgetting ", "मैं कब भूल रहा हूँ ");
        map.put("When am I frying ", "मैं कब तलने वाला हूँ ");
        map.put("When am I getting ", "मुझे कब मिल रहा है ");
        map.put("When am I giving ", "मैं कब दे रहा हूँ ");
        map.put("When am I going ", "मैं कब जा रहा हूँ ");
        map.put("When am I growing ", "मैं कब बढ़ रहा हूँ ");
        map.put("When am I hanging ", "मैं कब लटक रहा हूँ ");
        map.put("When am I hearing ", "मैं कब सुन रहा हूँ ");
        map.put("When am I helping ", "मैं कब मदद कर रहा हूँ ");
        map.put("When am I hiding ", "मैं कब छिपा रहा हूँ ");
        map.put("When am I hitting ", "मैं कब मार रहा हूँ ");
        map.put("When am I holding ", "मैं कब पकड़ रहा हूँ ");
        map.put("When am I hoping ", "मैं कब उम्मीद कर रहा हूँ ");
        map.put("When am I hurting ", "मैं कब चोट पहुँचा रहा हूँ ");
        map.put("When am I jumping ", "मैं कब कूद रहा हूँ ");
        map.put("When am I keeping ", "मैं कब रख रहा हूँ ");
        map.put("When am I killing ", "मैं कब मार रहा हूँ ");
        map.put("When am I knowing ", "मैं कब जान रहा हूँ ");
        map.put("When am I laughing ", "मैं कब हँस रहा हूँ ");
        map.put("When am I leading ", "मैं कब नेतृत्व कर रहा हूँ ");
        map.put("When am I leaping ", "मैं कब छलांग लगा रहा हूँ ");
        map.put("When am I learning ", "मैं कब सीख रहा हूँ ");
        map.put("When am I leaving ", "मैं कब जा रहा हूँ ");
        map.put("When am I lending ", "मैं कब उधार दे रहा हूँ ");
        map.put("When am I living ", "मैं कब रह रहा हूँ ");
        map.put("When am I looking ", "मैं कब देख रहा हूँ ");
        map.put("When am I losing ", "मैं कब हार रहा हूँ ");
        map.put("When am I loving ", "मैं कब प्यार कर रहा हूँ ");
        map.put("When am I making ", "मैं कब बना रहा हूँ ");
        map.put("When am I marrying ", "मैं कब शादी कर रहा हूँ ");
        map.put("When am I meeting ", "मैं कब मिल रहा हूँ ");
        map.put("When am I mistaking ", "मैं कब गलत कर रहा हूँ ");
        map.put("When am I opening ", "मैं कब खोल रहा हूँ ");
        map.put("When am I paying ", "मैं कब भुगतान कर रहा हूँ ");
        map.put("When am I playing ", "मैं कब खेल रहा हूँ ");
        map.put("When am I putting ", "मैं कब डाल रहा हूँ ");
        map.put("When am I quarrelling ", "मैं कब झगड़ा कर रहा हूँ ");
        map.put("When am I raining ", "बारिश कब हो रही है ");
        map.put("When am I reaching ", "मैं कब पहुँच रहा हूँ ");
        map.put("When am I reading ", "मैं कब पढ़ रहा हूँ ");
        map.put("When am I remembering ", "मुझे कब याद आ रहा है ");
        map.put("When am I riding ", "मैं कब सवारी कर रहा हूँ ");
        map.put("When am I ringing ", "मैं कब बज रहा हूँ ");
        map.put("When am I rising ", "मैं कब उठ रहा हूँ ");
        map.put("When am I running ", "मैं कब दौड़ रहा हूँ ");
        map.put("When am I saying ", "मैं कब कह रहा हूँ ");
        map.put("When am I seeing ", "मैं कब देख रहा हूँ ");
        map.put("When am I selling ", "मैं कब बेच रहा हूँ ");
        map.put("When am I sending ", "मैं कब भेज रहा हूँ ");
        map.put("When am I shaking ", "मैं कब हिल रहा हूँ ");
        map.put("When am I shining ", "मैं कब चमक रहा हूँ ");
        map.put("When am I shooting ", "मैं कब शूटिंग कर रहा हूँ ");
        map.put("When am I showing ", "मैं कब दिखा रहा हूँ ");
        map.put("When am I shutting ", "मैं कब बंद कर रहा हूँ ");
        map.put("When am I singing ", "मैं कब गा रहा हूँ ");
        map.put("When am I sinking ", "मैं कब डूब रहा हूँ ");
        map.put("When am I sleeping ", "मैं कब सो रहा हूँ ");
        map.put("When am I smelling ", "मैं कब सूँघ रहा हूँ ");
        map.put("When am I speaking ", "मैं कब बोल रहा हूँ ");
        map.put("When am I stealing ", "मैं कब चोरी कर रहा हूँ ");
        map.put("When am I teaching ", "मैं कब पढ़ा रहा हूँ ");
        map.put("When am I washing ", "मैं कब धो रहा हूँ ");
        map.put("When am I writing ", "मैं कब लिख रहा हूँ ");

        return map;
    }
    static Map<String,String> Three(){
        HashMap<String,String>map = new HashMap<>();
        map.put("When  have I abused ", "मैंने कब गाली दी है ");
        map.put("When  have I advised ", "मैंने कब सलाह दी है ");
        map.put("When  have I answered ", "मैंने कब जवाब दिया है ");
        map.put("When  have I arisen ", "मैं कब पैदा हुआ हूँ ");
        map.put("When  have I arrived ", "मैं कब आ गया ");
        map.put("When  have I asked ", "मैंने कब पूछा है ");
        map.put("When  have I awoken ", "मैं कब जाग गया हूँ ");
        map.put("When  have I undefined", "मैंने कब अपरिभाषित किया है");
        map.put("When  have I borne ", "मैंने कब जन्म लिया है ");
        map.put("When  have I beaten ", "मैंने कब पीटा है ");
        map.put("When  have I become ", "मैं कब बन गया हूँ ");
        map.put("When  have I begged ", "मैंने कब भीख माँगी है ");
        map.put("When  have I begun ", "मैंने कब शुरू किया है ");
        map.put("When  have I bound ", "मैंने कब बाध्य किया है ");
        map.put("When  have I bitten ", "मैंने कब काट लिया है ");
        map.put("When  have I blessed ", "मैंने कब आशीर्वाद दिया है ");
        map.put("When  have I blown ", "मैंने कब उड़ा दिया है ");
        map.put("When  have I broken ", "मैं कब टूटा हूँ ");
        map.put("When  have I brought ", "मैं कब लाया हूँ ");
        map.put("When  have I built ", "मैंने कब बनाया है ");
        map.put("When  have I burnt ", "मैंने कब जलाया है ");
        map.put("When  have I bought ", "मैंने कब खरीदा है ");
        map.put("When  have I called ", "मैंने कब फोन किया है ");
        map.put("When  have I carried ", "मैंने कब किया है ");
        map.put("When  have I caught ", "मैंने कब पकड़ा है ");
        map.put("When  have I cheated ", "मैंने कब धोखा दिया है ");
        map.put("When  have I chosen ", "मैंने कब चुना है ");
        map.put("When  have I cleaned ", "मैंने कब साफ किया है ");
        map.put("When  have I climbed ", "मैं कब चढ़ गया ");
        map.put("When  have I closed ", "मैंने कब बंद किया है ");
        map.put("When  have I come ", "मैं कब आया हूँ ");
        map.put("When  have I cooked ", "मैंने कब पकाया है ");
        map.put("When  have I crept ", "मैंने कब क्रेप किया है ");
        map.put("When  have I cried ", "मैं कब रोया हूँ ");
        map.put("When  have I cut ", "मैंने कब काट दिया है ");
        map.put("When  have I danced ", "मैंने कब नृत्य किया है ");
        map.put("When  have I dealt ", "मैंने कब निपटा है ");
        map.put("When  have I died ", "मैं कब मर चुका हूँ ");
        map.put("When  have I dug ", "मैंने कब खोदा है ");
        map.put("When  have I done ", "मैंने कब किया है ");
        map.put("When  have I drawn ", "मैंने कब खींचा है ");
        map.put("When  have I drunk ", "मैंने कब पिया है ");
        map.put("When  have I driven ", "मैंने कब चलाया है ");
        map.put("When  have I dropped ", "मैंने कब गिरा दिया है ");
        map.put("When  have I dried ", "मैं कब सूख चुका हूँ ");
        map.put("When  have I eaten ", "मैंने कब खाया है ");
        map.put("When  have I elected ", "मैंने कब चुना है ");
        map.put("When  have I entered ", "मैंने कब प्रवेश किया है ");
        map.put("When  have I fallen ", "मैं कब गिर गया हूँ ");
        map.put("When  have I fed ", "मैंने कब खिलाया है ");
        map.put("When  have I felt ", "मैंने कब महसूस किया है ");
        map.put("When  have I fought ", "मैंने कब लड़ाई लड़ी है ");
        map.put("When  have I found ", "मैंने कब पाया है ");
        map.put("When  have I fled ", "मैं कब भाग गया ");
        map.put("When  have I flown ", "मैं कब उड़ गया हूँ ");
        map.put("When  have I forgotten ", "मैं कब भूल गया ");
        map.put("When  have I fried ", "मैंने कब फ्राई किया है ");
        map.put("When  have I got ", "मुझे कब मिला है ");
        map.put("When  have I given ", "मैंने कब दिया है ");
        map.put("When  have I gone ", "मैं कब गया हूँ ");
        map.put("When  have I grown ", "मैं कब बड़ा हो गया हूँ ");
        map.put("When  have I hanged ", "मैंने कब फांसी दी है ");
        map.put("When  have I hung ", "मैंने कब लटका दिया है ");
        map.put("When  have I heard ", "मैंने कब सुना है ");
        map.put("When  have I helped ", "मैंने कब मदद की है ");
        map.put("When  have I hidden ", "मैंने कब छिपाया है ");
        map.put("When  have I hit ", "मैंने कब मारा है ");
        map.put("When  have I held ", "मैंने कब आयोजित किया है ");
        map.put("When  have I hoped ", "मैंने कब उम्मीद की है ");
        map.put("When  have I hurt ", "मुझे कब चोट लगी है ");
        map.put("When  have I jumped ", "मैं कब कूद गया ");
        map.put("When  have I kept ", "मैंने कब रखा है ");
        map.put("When  have I killed ", "मैंने कब मार डाला है ");
        map.put("When  have I known ", "मुझे कब पता है ");
        map.put("When  have I laughed ", "मैं कब हँसा हूँ ");
        map.put("When  have I led ", "मैंने कब नेतृत्व किया है ");
        map.put("When  have I leapt ", "मैंने कब छलांग लगाई है ");
        map.put("When  have I learnt ", "मैंने कब सीखा ");
        map.put("When  have I left ", "मैंने कब छोड़ा है ");
        map.put("When  have I lent ", "मैंने कब उधार दिया है ");
        map.put("When  have I lived ", "मैं कब रहता हूँ ");
        map.put("When  have I looked ", "मैंने कब देखा है ");
        map.put("When  have I lost ", "मैं कब हार गया ");
        map.put("When  have I loved ", "मैंने कब प्यार किया है ");
        map.put("When  have I made ", "मैंने कब बनाया है ");
        map.put("When  have I married ", "मैंने शादी कब की है ");
        map.put("When  have I met ", "मैं कब मिला हूँ ");
        map.put("When  have I mistaken ", "मैंने कब गलत किया है ");
        map.put("When  have I opened ", "मैंने कब खोला है ");
        map.put("When  have I paid ", "मैंने कब भुगतान किया है ");
        map.put("When  have I played ", "मैंने कब खेला है ");
        map.put("When  have I put ", "मैंने कब रखा है ");
        map.put("When  have I quarrelled ", "मैंने कब झगड़ा किया है ");
        map.put("When  have I rained ", "मैंने कब बारिश की है ");
        map.put("When  have I reached ", "मैं कब पहुँच गया हूँ ");
        map.put("When  have I read ", "मैंने कब पढ़ा है ");
        map.put("When  have I remembered ", "मुझे कब याद आया ");
        map.put("When  have I ridden ", "मैंने कब सवारी की है ");
        map.put("When  have I rung ", "मैंने कब बजाया है ");
        map.put("When  have I risen ", "मैं कब उठ गया हूँ ");
        map.put("When  have I run ", "मैं कब चला रहा हूँ ");
        map.put("When  have I said ", "मैंने कब कहा है ");
        map.put("When  have I seen ", "मैंने कब देखा है ");
        map.put("When  have I sold ", "मैंने कब बेचा है ");
        map.put("When  have I sent ", "मैंने कब भेजा है ");
        map.put("When  have I shaken ", "मैं कब हिला रहा हूँ ");
        map.put("When  have I shone ", "मैं कब चमक गया हूँ ");
        map.put("When  have I shot ", "मैंने कब गोली मार दी है ");
        map.put("When  have I shown ", "मैंने कब दिखाया है ");
        map.put("When  have I shut ", "मैंने कब बंद किया है ");
        map.put("When  have I sung ", "मैंने कब गाया है ");
        map.put("When  have I sunk ", "मैं कब डूब गया ");
        map.put("When  have I slept ", "मैं कब सोया हूँ ");
        map.put("When  have I smelt ", "मैंने कब पिघलाया है ");
        map.put("When  have I spoken ", "मैंने कब बात की है ");
        map.put("When  have I  spoiled ", "मैंने कब खराब किया है ");
        map.put("When  have I thrown ", "मैंने कब फेंका है ");
        map.put("When  have I walked ", "मैं कब चला हूँ ");
        map.put("When  have I written ", "मैंने कब लिखा है ");

        return map;
    }
    static Map<String,String> Four(){
        HashMap<String,String>map = new HashMap<>();
        map.put("When  have I been binding ", "मैं कब बाइंडिंग कर रहा हूँ ");
        map.put("When  have I been abusing ", "मैं कब गाली दे रहा हूँ ");
        map.put("When  have I been advising ", "मैं कब सलाह दे रहा हूँ ");
        map.put("When  have I been answering ", "मैं कब जवाब दे रहा हूँ ");
        map.put("When  have I been arising ", "मैं कब उठ रहा हूँ ");
        map.put("When  have I been arriving ", "मैं कब आ रहा हूँ ");
        map.put("When  have I been asking ", "मैं कब पूछ रहा था ");
        map.put("When  have I been awaking ", "मैं कब जाग रहा था ");
        map.put("When  have I been undefined", "मुझे कब अपरिभाषित किया गया है");
        map.put("When  have I been bearing ", "मैं कब असर कर रहा हूँ ");
        map.put("When  have I been beating ", "मैं कब पिटाई कर रहा हूँ ");
        map.put("When  have I been becoming ", "मैं कब बन रहा हूँ ");
        map.put("When  have I been begging ", "मैं कब भीख माँग रहा हूँ ");
        map.put("When  have I been beginning ", "मैं कब शुरू कर रहा हूँ ");
        map.put("When  have I been biting ", "मैं कब काट रहा हूँ ");
        map.put("When  have I been blessing ", "मैं कब आशीष रहा हूँ ");
        map.put("When  have I been blowing ", "मैं कब उड़ रहा हूँ ");
        map.put("When  have I been breaking ", "मैं कब तोड़ रहा हूँ ");
        map.put("When  have I been bringing ", "मैं कब ला रहा हूँ ");
        map.put("When  have I been building ", "मैं कब निर्माण कर रहा हूँ ");
        map.put("When  have I been burning ", "मैं कब जल रहा हूँ ");
        map.put("When  have I been buying ", "मैं कब खरीद रहा हूँ ");
        map.put("When  have I been calling ", "मैं कब कॉल कर रहा हूँ ");
        map.put("When  have I been carrying ", "मैं कब ले जा रहा हूँ ");
        map.put("When  have I been catching ", "मैं कब पकड़ रहा हूँ ");
        map.put("When  have I been cheating ", "मैं कब धोखा दे रहा हूँ ");
        map.put("When  have I been choosing ", "मैं कब चुन रहा हूँ ");
        map.put("When  have I been cleaning ", "मैं कब सफाई कर रहा हूँ ");
        map.put("When  have I been climbing ", "मैं कब चढ़ रहा हूँ ");
        map.put("When  have I been closing ", "मैं कब बंद कर रहा हूँ ");
        map.put("When  have I been coming ", "मैं कब आ रहा हूँ ");
        map.put("When  have I been cooking ", "मैं कब खाना बना रहा हूँ ");
        map.put("When  have I been creeping ", "मैं कब रेंग रहा हूँ ");
        map.put("When  have I been crying ", "मैं कब रो रहा था ");
        map.put("When  have I been cutting ", "मैं कब काट रहा हूँ ");
        map.put("When  have I been dancing ", "मैं कब नाच रहा हूँ ");
        map.put("When  have I been dealing ", "मैं कब काम कर रहा हूँ ");
        map.put("When  have I been dying ", "मैं कब मर रहा हूँ ");
        map.put("When  have I been digging ", "मैं कब खुदाई कर रहा हूँ ");
        map.put("When  have I been doing ", "मैं कब कर रहा हूँ ");
        map.put("When  have I been drawing ", "मैं कब आरेखण कर रहा हूँ ");
        map.put("When  have I been drinking ", "मैं कब पी रहा हूँ ");
        map.put("When  have I been driving ", "मैं कब गाड़ी चला रहा हूँ ");
        map.put("When  have I been dropping ", "मैं कब गिर रहा हूँ ");
        map.put("When  have I been drying ", "मैं कब सूख रहा हूँ ");
        map.put("When  have I been eating ", "मैं कब खा रहा हूँ ");
        map.put("When  have I been electing ", "मैं कब चुनाव कर रहा हूँ ");
        map.put("When  have I been entering ", "मैं कब प्रवेश कर रहा हूँ ");
        map.put("When  have I been falling ", "मैं कब गिर रहा हूँ ");
        map.put("When  have I been feeding ", "मैं कब खिला रहा हूँ ");
        map.put("When  have I been feeling ", "मैं कब महसूस कर रहा हूँ ");
        map.put("When  have I been fighting ", "मैं कब लड़ रहा हूँ ");
        map.put("When  have I been finding ", "मुझे कब मिल रहा है ");
        map.put("When  have I been fleeing ", "मैं कब भाग रहा हूँ ");
        map.put("When  have I been flying ", "मैं कब उड़ रहा हूँ ");
        map.put("When  have I been forgetting ", "मैं कब भूल रहा हूँ ");
        map.put("When  have I been frying ", "मैं कब तलने गया हूँ ");
        map.put("When  have I been getting ", "मुझे कब मिल रहा है ");
        map.put("When  have I been giving ", "मैं कब दे रहा हूँ ");
        map.put("When  have I been going ", "मैं कब जा रहा हूँ ");
        map.put("When  have I been growing ", "मैं कब बढ़ रहा हूँ ");
        map.put("When  have I been hanging ", "मैं कब लटक रहा हूँ ");
        map.put("When  have I been hearing ", "मैं कब सुन रहा हूँ ");
        map.put("When  have I been helping ", "मैं कब मदद कर रहा हूँ ");
        map.put("When  have I been hiding ", "मैं कब छिपा रहा हूँ ");
        map.put("When  have I been hitting ", "मैं कब मार रहा हूँ ");
        map.put("When  have I been holding ", "मैं कब पकड़ रहा हूँ ");
        map.put("When  have I been hoping ", "मैं कब उम्मीद कर रहा था ");
        map.put("When  have I been hurting ", "मैं कब चोट पहुँचा रहा हूँ ");
        map.put("When  have I been jumping ", "मैं कब कूद रहा हूँ ");
        map.put("When  have I been keeping ", "मैं कब रख रहा हूँ ");
        map.put("When  have I been killing ", "मैं कब मार रहा हूँ ");
        map.put("When  have I been knowing ", "मैं कब जान रहा हूँ ");
        map.put("When  have I been laughing ", "मैं कब हँस रहा हूँ ");
        map.put("When  have I been leading ", "मैं कब नेतृत्व कर रहा हूँ ");
        map.put("When  have I been leaping ", "मैं कब छलांग लगा रहा हूँ ");
        map.put("When  have I been learning ", "मैं कब सीख रहा हूँ ");
        map.put("When  have I been leaving ", "मैं कब जा रहा हूँ ");
        map.put("When  have I been lending ", "मैं कब उधार दे रहा हूँ ");
        map.put("When  have I been living ", "मैं कब रह रहा हूँ ");
        map.put("When  have I been looking ", "मैं कब देख रहा था ");
        map.put("When  have I been losing ", "मैं कब हार रहा हूँ ");
        map.put("When  have I been loving ", "मैं कब प्यार कर रहा हूँ ");
        map.put("When  have I been making ", "मैं कब बना रहा हूँ ");
        map.put("When  have I been marrying ", "मैं कब शादी कर रहा हूँ ");
        map.put("When  have I been meeting ", "मैं कब मिल रहा हूँ ");
        map.put("When  have I been mistaking ", "मैं कब गलत कर रहा हूँ ");
        map.put("When  have I been opening ", "मैं कब खोल रहा हूँ ");
        map.put("When  have I been paying ", "मैं कब भुगतान कर रहा हूँ ");
        map.put("When  have I been playing ", "मैं कब खेल रहा हूँ ");
        map.put("When  have I been putting ", "मैं कब लगा रहा हूँ ");
        map.put("When  have I been quarrelling ", "मैं कब झगड़ा कर रहा हूँ ");
        map.put("When  have I been raining ", "बारिश कब हो रही है ");
        map.put("When  have I been reaching ", "मैं कब पहुँच रहा हूँ ");
        map.put("When  have I been reading ", "मैं कब पढ़ रहा हूँ ");
        map.put("When  have I been remembering ", "मुझे कब याद आ रहा है ");
        map.put("When  have I been riding ", "मैं कब सवारी कर रहा हूँ ");
        map.put("When  have I been ringing ", "मैं कब बज रहा हूँ ");
        map.put("When  have I been rising ", "मैं कब उठ रहा हूँ ");
        map.put("When  have I been running ", "मैं कब दौड़ रहा हूँ ");
        map.put("When  have I been saying ", "मैं कब कह रहा हूँ ");
        map.put("When  have I been seeing ", "मैं कब देख रहा हूँ ");
        map.put("When  have I been selling ", "मैं कब बेच रहा हूँ ");
        map.put("When  have I been sending ", "मैं कब भेज रहा हूँ ");
        map.put("When  have I been shaking ", "मैं कब हिल रहा हूँ ");
        map.put("When  have I been shining ", "मैं कब चमक रहा हूँ ");
        map.put("When  have I been shooting ", "मैं कब शूटिंग कर रहा हूँ ");
        map.put("When  have I been showing ", "मैं कब दिखा रहा हूँ ");
        map.put("When  have I been shutting ", "मैं कब बंद कर रहा हूँ ");
        map.put("When  have I been singing ", "मैं कब गा रहा हूँ ");
        map.put("When  have I been sinking ", "मैं कब डूब रहा हूँ ");
        map.put("When  have I been sleeping ", "मैं कब सो रहा था ");
        map.put("When  have I been smelling ", "मुझे कब सूंघा रहा है ");
        map.put("When  have I been wanting ", "मैं कब चाह रहा था ");
        map.put("When  have I been wearing ", "मैं कब पहन रहा हूँ ");

        return map;
    }
    static Map<String,String> Five(){
        HashMap<String,String>map = new HashMap<>();
        map.put("When  did I  abuse ", "मैंने कब गाली दी ");
        map.put("When  did I  advise", "मैंने कब सलाह दी");
        map.put("When  did I  answer ", "मैंने कब जवाब दिया ");
        map.put("When  did I  arise ", "मैं कब उठ गया ");
        map.put("When  did I  arrive ", "मैं कब आया ");
        map.put("When  did I  ask ", "मैंने कब पूछा ");
        map.put("When  did I  awake ", "मैं कब जाग गया ");
        map.put("When  did I  beat ", "मैंने कब हराया ");
        map.put("When  did I  become ", "मैं कब बन गया ");
        map.put("When  did I  beg ", "मैंने कब भीख माँगी ");
        map.put("When  did I  begin ", "मैंने कब शुरू किया ");
        map.put("When  did I  bind ", "मैंने कब बाँध लिया ");
        map.put("When  did I  bite", "मैंने कब काट लिया");
        map.put("When  did I  bless", "मैंने कब आशीर्वाद दिया");
        map.put("When  did I  blow ", "मैंने कब उड़ाया ");
        map.put("When  did I  break ", "मैंने कब तोड़ा ");
        map.put("When  did I  bring ", "मैं कब लाया ");
        map.put("When  did I  build ", "मैंने कब बनाया ");
        map.put("When  did I  burn ", "मैंने कब जलाया ");
        map.put("When  did I  buy ", "मैंने कब खरीदा ");
        map.put("When  did I  call ", "मैंने कब फोन किया ");
        map.put("When  did I  carry ", "मैं कब ले गया ");
        map.put("When  did I  catch ", "मैंने कब पकड़ लिया ");
        map.put("When  did I  cheat ", "मैंने कब धोखा दिया ");
        map.put("When  did I  choose ", "मैंने कब चुना ");
        map.put("When  did I  clean ", "मैंने कब साफ किया ");
        map.put("When  did I  climb  ", "मैं कब चढ़ गया  ");
        map.put("When  did I  close ", "मैंने कब बंद किया ");
        map.put("When  did I  come ", "मैं कब आया ");
        map.put("When  did I  cook ", "मैंने कब खाना बनाया ");
        map.put("When  did I  creep ", "मैं कब रेंगना था ");
        map.put("When  did I  cut ", "मैंने कब काटा ");
        map.put("When  did I  dance ", "मैंने कब नृत्य किया ");
        map.put("When  did I  deal ", "मैंने कब सौदा किया ");
        map.put("When  did I  die ", "मैं कब मर गया ");
        map.put("When  did I  dig ", "मैंने कब खोदा ");
        map.put("When  did I  draw ", "मैंने कब ड्रॉ किया ");
        map.put("When  did I  drive ", "मैंने कब ड्राइव किया ");
        map.put("When  did I  drop ", "मैंने कब छोड़ा ");
        map.put("When  did I  dry ", "मैंने कब सुखाया ");
        map.put("When  did I  eat ", "मैंने कब खाया ");
        map.put("When  did I  elect", "मैंने कब चुना");
        map.put("When  did I  enter ", "मैंने कब प्रवेश किया ");
        map.put("When  did I  fall ", "मैं कब गिर गया ");
        map.put("When  did I  feed ", "मैंने कब खाना खाया ");
        map.put("When  did I  feel  ", "मैंने कब महसूस किया  ");
        map.put("When  did I  fight ", "मैंने कब लड़ाई लड़ी ");
        map.put("When  did I  find ", "मुझे कब मिला ");
        map.put("When  did I  flee ", "मैं कब भाग गया ");
        map.put("When  did I  fly  ", "मैंने कब उड़ान भरी  ");
        map.put("When  did I  fry ", "मैंने फ्राई कब किया ");
        map.put("When  did I  get  ", "मुझे कब मिला  ");
        map.put("When  did I  give ", "मैंने कब दिया ");
        map.put("When  did I  go ", "मैं कब गया था ");
        map.put("When  did I  grow", "मैं कब बढ़ता था");
        map.put("When  did I  hang ", "मैंने कब लटका दिया ");
        map.put("When  did I  hear ", "मैंने कब सुना ");
        map.put("When  did I  help ", "मैंने कब मदद की ");
        map.put("When  did I  hide ", "मैंने कब छिपाया ");
        map.put("When  did I  hit ", "मैंने कब मारा ");
        map.put("When  did I  hold ", "मैंने कब पकड़ लिया ");
        map.put("When  did I  hope ", "मुझे कब उम्मीद थी ");
        map.put("When  did I  hurt ", "मैंने कब चोट पहुंचाई ");
        map.put("When  did I  jump ", "मैं कब कूदता था ");
        map.put("When  did I  keep ", "मैंने कब रखा ");
        map.put("When  did I  kill ", "मैंने कब मार डाला ");
        map.put("When  did I  know ", "मुझे कब पता था ");
        map.put("When  did I  laugh ", "मैं कब हँसा ");
        map.put("When  did I  lead ", "मैंने कब नेतृत्व किया ");
        map.put("When  did I  leap ", "मैंने कब छलांग लगाई ");
        map.put("When  did I  learn ", "मैंने कब सीखा ");
        map.put("When  did I  leave ", "मैंने कब छोड़ा ");
        map.put("When  did I  live ", "मैं कब रहता था ");
        map.put("When  did I  look ", "मैंने कब देखा ");
        map.put("When  did I  lose ", "मैंने कब हारा ");
        map.put("When  did I  love ", "मैंने कब प्यार किया ");
        map.put("When  did I  make ", "मैंने कब बनाया ");
        map.put("When  did I  marry ", "मैंने शादी कब की ");
        map.put("When  did I  meet ", "मैं कब मिला ");
        map.put("When  did I  mistake ", "मैंने कब गलती की ");
        map.put("When  did I  open ", "मैंने कब खोला ");
        map.put("When  did I  pay  ", "मैंने कब भुगतान किया  ");
        map.put("When  did I  play ", "मैंने कब खेला ");
        map.put("When  did I  put ", "मैंने कब रखा ");
        map.put("When  did I  quarrel ", "मैंने झगड़ा कब किया ");
        map.put("When  did I  rain ", "बारिश कब हुई ");
        map.put("When  did I  reach ", "मैं कब पहुँचा ");
        map.put("When  did I  read", "मैंने कब पढ़ा");
        map.put("When  did I  remember  ", "मुझे कब याद आया  ");
        map.put("When  did I  ride ", "मैंने सवारी कब की ");
        map.put("When  did I  ring ", "मैंने कब रिंग किया ");
        map.put("When  did I  rise  ", "मैं कब उठ गया  ");
        map.put("When  did I  say ", "मैंने कब कहा ");
        map.put("When  did I  see ", "मैंने कब देखा ");
        map.put("When  did I  sell ", "मैंने कब बेचा था ");
        map.put("When  did I  send ", "मैंने कब भेजा ");
        map.put("When  did I  shake ", "मैंने कब हिला दिया ");
        map.put("When  did I  shine ", "मैं कब चमक गया ");
        map.put("When  did I  shoot ", "मैंने कब शूट किया ");
        map.put("When  did I  show ", "मैंने कब दिखाया ");
        map.put("When  did I  shut  ", "मैंने कब बंद किया  ");
        map.put("When  did I  sing ", "मैंने कब गाया था ");
        map.put("When  did I  sink ", "मैं कब डूब गया ");
        map.put("When  did I  sleep ", "मैं कब सोता था ");
        map.put("When  did I  smell ", "मुझे कब सूंघा था ");
        map.put("When  did I  speak ", "मैंने कब बात की ");
        map.put("When  did I  want ", "मैं कब चाहता था ");

        return map;
    }
    static Map<String,String> Six(){
        HashMap<String,String>map = new HashMap<>();
        map.put("When  was I  abusing ", "मैं कब गाली दे रहा था ");
        map.put("When  was I  advising ", "मैं कब सलाह दे रहा था ");
        map.put("When  was I  answering ", "मैं कब जवाब दे रहा था ");
        map.put("When  was I  arising ", "मैं कब उठ रहा था ");
        map.put("When  was I  arriving ", "मैं कब आ रहा था ");
        map.put("When  was I  asking ", "मैं कब पूछ रहा था ");
        map.put("When  was I  awaking ", "मैं कब जाग रहा था ");
        map.put("When  was I  undefined", "मैं कब अपरिभाषित था");
        map.put("When  was I  bearing ", "मैं कब सहन कर रहा था ");
        map.put("When  was I  beating ", "मैं कब पिटाई कर रहा था ");
        map.put("When  was I  becoming ", "मैं कब बन रहा था ");
        map.put("When  was I  begging ", "मैं कब भीख मांग रहा था ");
        map.put("When  was I  beginning ", "मैं कब शुरू कर रहा था ");
        map.put("When  was I  binding ", "मैं कब बाध्यकारी था ");
        map.put("When  was I  biting ", "मैं कब काट रहा था ");
        map.put("When  was I  blessing ", "मैं कब आशीष दे रहा था ");
        map.put("When  was I  blowing ", "मैं कब उड़ रहा था ");
        map.put("When  was I  breaking ", "मैं कब तोड़ रहा था ");
        map.put("When  was I  bringing ", "मैं कब ला रहा था ");
        map.put("When  was I  building ", "मैं कब निर्माण कर रहा था ");
        map.put("When  was I  burning ", "मैं कब जल रहा था ");
        map.put("When  was I  buying ", "मैं कब खरीद रहा था ");
        map.put("When  was I  calling ", "मैं कब बुला रहा था ");
        map.put("When  was I  carrying ", "मैं कब ले जा रहा था ");
        map.put("When  was I  catching ", "मैं कब पकड़ रहा था ");
        map.put("When  was I  cheating ", "मैं कब धोखा दे रहा था ");
        map.put("When  was I  choosing ", "मैं कब चुन रहा था ");
        map.put("When  was I  cleaning ", "मैं कब सफाई कर रहा था ");
        map.put("When  was I  climbing ", "मैं कब चढ़ रहा था ");
        map.put("When  was I  closing ", "मैं कब बंद कर रहा था ");
        map.put("When  was I  coming ", "मैं कब आ रहा था ");
        map.put("When  was I  cooking ", "मैं कब खाना बना रहा था ");
        map.put("When  was I  creeping ", "मैं कब रेंग रहा था ");
        map.put("When  was I  crying ", "मैं कब रो रहा था ");
        map.put("When  was I  cutting ", "मैं कब काट रहा था ");
        map.put("When  was I  dancing ", "मैं कब नाच रहा था ");
        map.put("When  was I  dealing ", "मैं कब काम कर रहा था ");
        map.put("When  was I  dying ", "मैं कब मर रहा था ");
        map.put("When  was I  digging ", "मैं कब खुदाई कर रहा था ");
        map.put("When  was I  drawing ", "मैं कब ड्राइंग कर रहा था ");
        map.put("When  was I  drinking ", "मैं कब पी रहा था ");
        map.put("When  was I  driving ", "मैं कब गाड़ी चला रहा था ");
        map.put("When  was I  dropping ", "मैं कब गिर रहा था ");
        map.put("When  was I  drying ", "मैं कब सूख रहा था ");
        map.put("When  was I  eating ", "मैं कब खा रहा था ");
        map.put("When  was I  electing ", "मैं कब चुनाव कर रहा था ");
        map.put("When  was I  entering ", "मैं कब प्रवेश कर रहा था ");
        map.put("When  was I  falling ", "मैं कब गिर रहा था ");
        map.put("When  was I  feeding ", "मैं कब खिला रहा था ");
        map.put("When  was I  feeling ", "मैं कब महसूस कर रहा था ");
        map.put("When  was I  fighting ", "मैं कब लड़ रहा था ");
        map.put("When  was I  finding ", "मुझे कब मिल रहा था ");
        map.put("When  was I  fleeing ", "मैं कब भाग रहा था ");
        map.put("When  was I  flying ", "मैं कब उड़ रहा था ");
        map.put("When  was I  forgetting ", "मैं कब भूल रहा था ");
        map.put("When  was I  frying ", "मैं कब फ्राइंग कर रहा था ");
        map.put("When  was I  getting ", "मुझे कब मिल रहा था ");
        map.put("When  was I  giving ", "मैं कब दे रहा था ");
        map.put("When  was I  going ", "मैं कब जा रहा था ");
        map.put("When  was I  growing ", "मैं कब बढ़ रहा था ");
        map.put("When  was I  hanging ", "मैं कब लटक रहा था ");
        map.put("When  was I  hearing ", "मैं कब सुन रहा था ");
        map.put("When  was I  helping ", "मैं कब मदद कर रहा था ");
        map.put("When  was I  hiding ", "मैं कब छिपा रहा था ");
        map.put("When  was I  hitting ", "मैं कब मार रहा था ");
        map.put("When  was I  holding ", "मैं कब पकड़ रहा था ");
        map.put("When  was I  hoping ", "मैं कब उम्मीद कर रहा था ");
        map.put("When  was I  hurting ", "मैं कब चोट पहुँचा रहा था ");
        map.put("When  was I  jumping ", "मैं कब कूद रहा था ");
        map.put("When  was I  keeping ", "मैं कब रख रहा था ");
        map.put("When  was I  killing ", "मैं कब मार रहा था ");
        map.put("When  was I  knowing ", "मैं कब जान रहा था ");
        map.put("When  was I  laughing ", "मैं कब हँस रहा था ");
        map.put("When  was I  leading ", "मैं कब नेतृत्व कर रहा था ");
        map.put("When  was I  leaping ", "मैं कब छलांग लगा रहा था ");
        map.put("When  was I  learning ", "मैं कब सीख रहा था ");
        map.put("When  was I  leaving ", "मैं कब जा रहा था ");
        map.put("When  was I  lending ", "मैं कब उधार दे रहा था ");
        map.put("When  was I  living ", "मैं कब रह रहा था ");
        map.put("When  was I  looking ", "मैं कब देख रहा था ");
        map.put("When  was I  losing ", "मैं कब हार रहा था ");
        map.put("When  was I  loving ", "मैं कब प्यार कर रहा था ");
        map.put("When  was I  making ", "मैं कब बना रहा था ");
        map.put("When  was I  marrying ", "मैं कब शादी कर रहा था ");
        map.put("When  was I  meeting ", "मैं कब मिल रहा था ");
        map.put("When  was I  mistaking ", "मैं कब गलत कर रहा था ");
        map.put("When  was I  opening ", "मैं कब खोल रहा था ");
        map.put("When  was I  paying ", "मैं कब भुगतान कर रहा था ");
        map.put("When  was I  playing ", "मैं कब खेल रहा था ");
        map.put("When  was I  putting ", "मैं कब लगा रहा था ");
        map.put("When  was I  quarrelling ", "मैं कब झगड़ा कर रहा था ");
        map.put("When  was I  raining ", "मैं बारिश कब कर रहा था ");
        map.put("When  was I  reaching ", "मैं कब पहुँच रहा था ");
        map.put("When  was I  reading ", "मैं कब पढ़ रहा था ");
        map.put("When  was I  remembering ", "मैं कब याद कर रहा था ");
        map.put("When  was I  riding ", "मैं कब सवारी कर रहा था ");
        map.put("When  was I  ringing ", "मैं कब बज रहा था ");
        map.put("When  was I  rising ", "मैं कब उठ रहा था ");
        map.put("When  was I  running ", "मैं कब दौड़ रहा था ");
        map.put("When  was I  saying ", "मैं कब कह रहा था ");
        map.put("When  was I  seeing ", "मैं कब देख रहा था ");
        map.put("When  was I  selling ", "मैं कब बेच रहा था ");
        map.put("When  was I  sending ", "मैं कब भेज रहा था ");
        map.put("When  was I  shaking ", "मैं कब हिल रहा था ");
        map.put("When  was I  shining ", "मैं कब चमक रहा था ");
        map.put("When  was I  shooting ", "मैं कब शूटिंग कर रहा था ");
        map.put("When  was I  showing ", "मैं कब दिखा रहा था ");
        map.put("When  was I  shutting ", "मैं कब बंद कर रहा था ");
        map.put("When  was I  singing ", "मैं कब गा रहा था ");
        map.put("When  was I  sinking ", "मैं कब डूब रहा था ");
        map.put("When  was I  sleeping ", "मैं कब सो रहा था ");
        map.put("When  was I  smelling ", "मैं कब सूँघ रहा था ");
        map.put("When  was I  understanding ", "मैं कब समझ रहा था ");

        return map;
    }
    static Map<String,String> Seven(){
        HashMap<String,String>map = new HashMap<>();
        map.put("When  had I  abused ", "मैंने कब गाली दी थी ");
        map.put("When  had I  advised ", "मैंने कब सलाह दी थी ");
        map.put("When  had I  answered ", "मैंने कब जवाब दिया था ");
        map.put("When  had I  arisen ", "मैं कब पैदा हुआ था ");
        map.put("When  had I  arrived ", "मैं कब आया था ");
        map.put("When  had I  asked ", "मैंने कब पूछा था ");
        map.put("When  had I  awoken ", "मैं कब जाग गया था ");
        map.put("When  had I  undefined", "मैंने कब अपरिभाषित किया था");
        map.put("When  had I  borne ", "मैंने कब जन्म लिया था ");
        map.put("When  had I  beaten ", "मैंने कब पीटा था ");
        map.put("When  had I  become ", "मैं कब बन गया था ");
        map.put("When  had I  begged ", "मैंने कब भीख माँगी थी ");
        map.put("When  had I  begun ", "मैंने कब शुरू किया था ");
        map.put("When  had I  bound ", "मैंने कब बाध्य किया था ");
        map.put("When  had I  bitten ", "मैंने कब काट लिया था ");
        map.put("When  had I  blessed ", "मैंने कब आशीर्वाद दिया था ");
        map.put("When  had I  blown ", "मैंने कब उड़ा दिया था ");
        map.put("When  had I  broken ", "मैं कब टूट गया था ");
        map.put("When  had I  brought ", "मैं कब लाया था ");
        map.put("When  had I  built ", "मैंने कब बनाया था ");
        map.put("When  had I  burnt ", "मैंने कब जलाया था ");
        map.put("When  had I  bought ", "मैंने कब खरीदा था ");
        map.put("When  had I  called ", "मैंने कब फोन किया था ");
        map.put("When  had I  carried ", "मैंने कब किया था ");
        map.put("When  had I  caught ", "मैंने कब पकड़ा था ");
        map.put("When  had I  cheated ", "मैंने कब धोखा दिया था ");
        map.put("When  had I  chosen ", "मैंने कब चुना था ");
        map.put("When  had I  cleaned ", "मैंने कब साफ किया था ");
        map.put("When  had I  climbed ", "मैं कब चढ़ गया था ");
        map.put("When  had I  closed ", "मैंने कब बंद किया था ");
        map.put("When  had I  come ", "मैं कब आया था ");
        map.put("When  had I  cooked ", "मैंने कब पकाया था ");
        map.put("When  had I  crept ", "मैंने कब क्रेप किया था ");
        map.put("When  had I  cried ", "मैं कब रोया था ");
        map.put("When  had I  cut ", "मैंने कब काटा था ");
        map.put("When  had I  danced ", "मैंने कब नृत्य किया था ");
        map.put("When  had I  dealt ", "मैंने कब निपटा था ");
        map.put("When  had I  died ", "मैं कब मर गया था ");
        map.put("When  had I  dug ", "मैंने कब खोदा था ");
        map.put("When  had I  drawn ", "मैंने कब खींचा था ");
        map.put("When  had I  drunk ", "मैंने कब पिया था ");
        map.put("When  had I  driven ", "मैंने कब चलाया था ");
        map.put("When  had I  dropped ", "मैं कब गिरा था ");
        map.put("When  had I  dried ", "मैं कब सूख गया था ");
        map.put("When  had I  eaten ", "मैंने कब खाया था ");
        map.put("When  had I  elected ", "मैंने कब चुना था ");
        map.put("When  had I  entered ", "मैंने कब प्रवेश किया था ");
        map.put("When  had I  fallen ", "मैं कब गिर गया था ");
        map.put("When  had I  fed ", "मैंने कब खिलाया था ");
        map.put("When  had I  felt ", "मैंने कब महसूस किया था ");
        map.put("When  had I  fought ", "मैंने कब लड़ा था ");
        map.put("When  had I  found ", "मुझे कब मिला था ");
        map.put("When  had I  fled ", "मैं कब भाग गया था ");
        map.put("When  had I  flown ", "मैं कब उड़ गया था ");
        map.put("When  had I  forgotten ", "मैं कब भूल गया था ");
        map.put("When  had I  fried ", "मैंने कब तला था ");
        map.put("When  had I  got ", "मुझे कब मिला था ");
        map.put("When  had I  given ", "मैंने कब दिया था ");
        map.put("When  had I  gone ", "मैं कब गया था ");
        map.put("When  had I  grown ", "मैं कब बड़ा हुआ था ");
        map.put("When  had I  hanged ", "मैंने कब फांसी दी थी ");
        map.put("When  had I  hung ", "मैंने कब लटका दिया था ");
        map.put("When  had I  heard ", "मैंने कब सुना था ");
        map.put("When  had I  helped ", "मैंने कब मदद की थी ");
        map.put("When  had I  hidden ", "मैंने कब छिपाया था ");
        map.put("When  had I  hit ", "मैंने कब मारा था ");
        map.put("When  had I  held ", "मैंने कब आयोजित किया था ");
        map.put("When  had I  hoped ", "मुझे कब उम्मीद थी ");
        map.put("When  had I  hurt ", "मुझे कब चोट लगी थी ");
        map.put("When  had I  jumped ", "मैं कब कूद गया था ");
        map.put("When  had I  kept ", "मैंने कब रखा था ");
        map.put("When  had I  killed ", "मैंने कब मारा था ");
        map.put("When  had I  known ", "मुझे कब पता था ");
        map.put("When  had I  laughed ", "मैं कब हँसा था ");
        map.put("When  had I  led ", "मैंने कब नेतृत्व किया था ");
        map.put("When  had I  leapt ", "मैंने कब छलांग लगाई थी ");
        map.put("When  had I  learnt ", "मैंने कब सीखा था ");
        map.put("When  had I  left ", "मैंने कब छोड़ा था ");
        map.put("When  had I  lent ", "मैंने कब उधार दिया था ");
        map.put("When  had I  lived ", "मैं कब रहता था ");
        map.put("When  had I  looked ", "मैंने कब देखा था ");
        map.put("When  had I  lost ", "मैं कब हार गया था ");
        map.put("When  had I  loved ", "मैंने कब प्यार किया था ");
        map.put("When  had I  made ", "मैंने कब बनाया था ");
        map.put("When  had I  married ", "मैंने शादी कब की थी ");
        map.put("When  had I  met ", "मैं कब मिला था ");
        map.put("When  had I  mistaken ", "मैंने कब गलत किया था ");
        map.put("When  had I  opened ", "मैंने कब खोला था ");
        map.put("When  had I  paid ", "मैंने कब भुगतान किया था ");
        map.put("When  had I  played ", "मैंने कब खेला था ");
        map.put("When  had I  put ", "मैंने कब रखा था ");
        map.put("When  had I  quarrelled ", "मैंने कब झगड़ा किया था ");
        map.put("When  had I  rained ", "मैंने कब बारिश की थी ");
        map.put("When  had I  reached ", "मैं कब पहुँचा था ");
        map.put("When  had I  read ", "मैंने कब पढ़ा था ");
        map.put("When  had I  remembered ", "मुझे कब याद आया था ");
        map.put("When  had I  ridden ", "मैंने कब सवारी की थी ");
        map.put("When  had I  rung ", "मैंने कब बजाया था ");
        map.put("When  had I  risen ", "मैं कब उठ गया था ");
        map.put("When  had I  run ", "मैं कब दौड़ा था ");
        map.put("When  had I  said ", "मैंने कब कहा था ");
        map.put("When  had I  seen ", "मैंने कब देखा था ");
        map.put("When  had I  sold ", "मैंने कब बेचा था ");
        map.put("When  had I  sent ", "मैंने कब भेजा था ");
        map.put("When  had I  shaken ", "मैं कब हिल गया था ");
        map.put("When  had I  shone ", "मैं कब चमक गया था ");
        map.put("When  had I  shot ", "मैंने कब गोली मारी थी ");
        map.put("When  had I  shown ", "मैंने कब दिखाया था ");
        map.put("When  had I  shut ", "मैंने कब बंद किया था ");
        map.put("When  had I  sung ", "मैंने कब गाया था ");
        map.put("When  had I  sunk ", "मैं कब डूब गया था ");
        map.put("When  had I  slept ", "मैं कब सोया था ");
        map.put("When  had I  smelt ", "मैंने कब पिघलाया था ");
        map.put("When  had I  stolen ", "मैंने कब चोरी की थी ");
        map.put("When  had I  wept ", "मैं कब रोया था ");

        return map;
    }
    static Map<String,String> Eight(){
        HashMap<String,String>map = new HashMap<>();
        map.put("When  had I been  abusing ", "मैं कब गाली दे रहा था ");
        map.put("When  had I been  advising ", "मैं कब सलाह दे रहा था ");
        map.put("When  had I been  answering ", "मैं कब जवाब दे रहा था ");
        map.put("When  had I been  arising ", "मैं कब उठ रहा था ");
        map.put("When  had I been  arriving ", "मैं कब आ रहा था ");
        map.put("When  had I been  asking ", "मैं कब पूछ रहा था ");
        map.put("When  had I been  awaking ", "मैं कब जाग रहा था ");
        map.put("When  had I been  undefined", "मैं कब अपरिभाषित हो गया था");
        map.put("When  had I been  bearing ", "मैं कब सहन कर रहा था ");
        map.put("When  had I been  beating ", "मैं कब पिटाई कर रहा था ");
        map.put("When  had I been  becoming ", "मैं कब बन रहा था ");
        map.put("When  had I been  begging ", "मैं कब भीख मांग रहा था ");
        map.put("When  had I been  beginning ", "मैं कब शुरू कर रहा था ");
        map.put("When  had I been  binding ", "मैं कब बाइंडिंग कर रहा था ");
        map.put("When  had I been  biting ", "मैं कब काट रहा था ");
        map.put("When  had I been  blessing ", "मैं कब आशीष दे रहा था ");
        map.put("When  had I been  blowing ", "मैं कब उड़ रहा था ");
        map.put("When  had I been  breaking ", "मैं कब तोड़ रहा था ");
        map.put("When  had I been  bringing ", "मैं कब ला रहा था ");
        map.put("When  had I been  building ", "मैं कब निर्माण कर रहा था ");
        map.put("When  had I been  burning ", "मैं कब जल रहा था ");
        map.put("When  had I been  buying ", "मैं कब खरीद रहा था ");
        map.put("When  had I been  calling ", "मैं कब बुला रहा था ");
        map.put("When  had I been  carrying ", "मैं कब ले जा रहा था ");
        map.put("When  had I been  catching ", "मैं कब पकड़ रहा था ");
        map.put("When  had I been  cheating ", "मैं कब धोखा दे रहा था ");
        map.put("When  had I been  choosing ", "मैं कब चुन रहा था ");
        map.put("When  had I been  cleaning ", "मैं कब सफाई कर रहा था ");
        map.put("When  had I been  climbing ", "मैं कब चढ़ रहा था ");
        map.put("When  had I been  closing ", "मैं कब बंद कर रहा था ");
        map.put("When  had I been  coming ", "मैं कब आ रहा था ");
        map.put("When  had I been  cooking ", "मैं कब खाना बना रहा था ");
        map.put("When  had I been  creeping ", "मैं कब रेंग रहा था ");
        map.put("When  had I been  crying ", "मैं कब रो रहा था ");
        map.put("When  had I been  cutting ", "मैं कब काट रहा था ");
        map.put("When  had I been  dancing ", "मैं कब नाच रहा था ");
        map.put("When  had I been  dealing ", "मैं कब काम कर रहा था ");
        map.put("When  had I been  dying ", "मैं कब मर रहा था ");
        map.put("When  had I been  digging ", "मैं कब खुदाई कर रहा था ");
        map.put("When  had I been  drawing ", "मैं कब ड्राइंग कर रहा था ");
        map.put("When  had I been  drinking ", "मैं कब पी रहा था ");
        map.put("When  had I been  driving ", "मैं कब गाड़ी चला रहा था ");
        map.put("When  had I been  dropping ", "मैं कब गिर रहा था ");
        map.put("When  had I been  drying ", "मैं कब सूख रहा था ");
        map.put("When  had I been  eating ", "मैं कब खा रहा था ");
        map.put("When  had I been  electing ", "मैं कब चुनाव कर रहा था ");
        map.put("When  had I been  entering ", "मैं कब प्रवेश कर रहा था ");
        map.put("When  had I been  falling ", "मैं कब गिर रहा था ");
        map.put("When  had I been  feeding ", "मैं कब खिला रहा था ");
        map.put("When  had I been  feeling ", "मैं कब महसूस कर रहा था ");
        map.put("When  had I been  fighting ", "मैं कब लड़ रहा था ");
        map.put("When  had I been  finding ", "मुझे कब मिल रहा था ");
        map.put("When  had I been  fleeing ", "मैं कब भाग रहा था ");
        map.put("When  had I been  flying ", "मैं कब उड़ रहा था ");
        map.put("When  had I been  forgetting ", "मैं कब भूल रहा था ");
        map.put("When  had I been  frying ", "मैं कब तलने गया था ");
        map.put("When  had I been  getting ", "मुझे कब मिल रहा था ");
        map.put("When  had I been  giving ", "मैं कब दे रहा था ");
        map.put("When  had I been  going ", "मैं कब जा रहा था ");
        map.put("When  had I been  growing ", "मैं कब बढ़ रहा था ");
        map.put("When  had I been  hanging ", "मैं कब लटक रहा था ");
        map.put("When  had I been  hearing ", "मैं कब सुन रहा था ");
        map.put("When  had I been  helping ", "मैं कब मदद कर रहा था ");
        map.put("When  had I been  hiding ", "मैं कब छिपा रहा था ");
        map.put("When  had I been  hitting ", "मैं कब मार रहा था ");
        map.put("When  had I been  holding ", "मैं कब पकड़ रहा था ");
        map.put("When  had I been  hoping ", "मैं कब उम्मीद कर रहा था ");
        map.put("When  had I been  hurting ", "मैं कब चोट पहुँचा रहा था ");
        map.put("When  had I been  jumping ", "मैं कब कूद रहा था ");
        map.put("When  had I been  keeping ", "मैं कब रख रहा था ");
        map.put("When  had I been  killing ", "मैं कब मार रहा था ");
        map.put("When  had I been  knowing ", "मैं कब जान रहा था ");
        map.put("When  had I been  laughing ", "मैं कब हँस रहा था ");
        map.put("When  had I been  leading ", "मैं कब नेतृत्व कर रहा था ");
        map.put("When  had I been  leaping ", "मैं कब छलांग लगा रहा था ");
        map.put("When  had I been  learning ", "मैं कब सीख रहा था ");
        map.put("When  had I been  leaving ", "मैं कब जा रहा था ");
        map.put("When  had I been  lending ", "मैं कब उधार दे रहा था ");
        map.put("When  had I been  living ", "मैं कब रह रहा था ");
        map.put("When  had I been  looking ", "मैं कब देख रहा था ");
        map.put("When  had I been  losing ", "मैं कब हार रहा था ");
        map.put("When  had I been  loving ", "मैं कब प्यार कर रहा था ");
        map.put("When  had I been  making ", "मैं कब बना रहा था ");
        map.put("When  had I been  marrying ", "मैं कब शादी कर रहा था ");
        map.put("When  had I been  meeting ", "मैं कब मिल रहा था ");
        map.put("When  had I been  mistaking ", "मैं कब गलत कर रहा था ");
        map.put("When  had I been  opening ", "मैं कब खोल रहा था ");
        map.put("When  had I been  paying ", "मैं कब भुगतान कर रहा था ");
        map.put("When  had I been  playing ", "मैं कब खेल रहा था ");
        map.put("When  had I been  putting ", "मैं कब लगा रहा था ");
        map.put("When  had I been  quarrelling ", "मैं कब झगड़ा कर रहा था ");
        map.put("When  had I been  raining ", "मैं बारिश कब कर रहा था ");
        map.put("When  had I been  reaching ", "मैं कब पहुँच रहा था ");
        map.put("When  had I been  reading ", "मैं कब पढ़ रहा था ");
        map.put("When  had I been  remembering ", "मैं कब याद कर रहा था ");
        map.put("When  had I been  riding ", "मैं कब सवारी कर रहा था ");
        map.put("When  had I been  ringing ", "मैं कब बज रहा था ");
        map.put("When  had I been  rising ", "मैं कब उठ रहा था ");
        map.put("When  had I been  running ", "मैं कब दौड़ रहा था ");
        map.put("When  had I been  saying ", "मैं कब कह रहा था ");
        map.put("When  had I been  seeing ", "मैं कब देख रहा था ");
        map.put("When  had I been  selling ", "मैं कब बेच रहा था ");
        map.put("When  had I been  sending ", "मैं कब भेज रहा था ");
        map.put("When  had I been  shaking ", "मैं कब हिल रहा था ");
        map.put("When  had I been  shining ", "मैं कब चमक रहा था ");
        map.put("When  had I been  shooting ", "मैं कब शूटिंग कर रहा था ");
        map.put("When  had I been  showing ", "मैं कब दिखा रहा था ");
        map.put("When  had I been  singing ", "मैं कब गा रहा था ");
        map.put("When  had I been  shutting ", "मैं कब बंद कर रहा था ");
        map.put("When  had I been  sinking ", "मैं कब डूब रहा था ");
        map.put("When  had I been  sleeping ", "मैं कब सो रहा था ");
        map.put("When  had I been  smelling ", "मैं कब सूँघ रहा था ");
        map.put("When  had I been  spending ", "मैं कब खर्च कर रहा था ");
        map.put("When  had I been  taking ", "मैं कब ले रहा था ");

        return map;
    }
    static Map<String,String> Nine(){
        HashMap<String,String>map = new HashMap<>();
        map.put("When  will I abuse ", "मैं कब गाली दूंगा ");
        map.put("When  will I advise", "मैं कब सलाह दूँगा");
        map.put("When  will I answer ", "मैं कब जवाब दूंगा ");
        map.put("When  will I arise ", "मैं कब उठूँगा ");
        map.put("When  will I arrive ", "मैं कब आऊंगा ");
        map.put("When  will I ask ", "मैं कब पूछूँगा ");
        map.put("When  will I awake ", "मैं कब जाग जाऊंगा ");
        map.put("When  will I \r", "मैं कब करूंगा \r");
        map.put("When  will I be undefined", "मैं कब अपरिभाषित हो जाऊंगा");
        map.put("When  will I bear ", "मैं कब सहन करूंगा ");
        map.put("When  will I beat ", "मैं कब हराऊंगा ");
        map.put("When  will I become ", "मैं कब बन जाऊंगा ");
        map.put("When  will I beg ", "मैं कब भीख माँगता हूँ ");
        map.put("When  will I begin ", "मैं कब शुरू करूँगा ");
        map.put("When  will I bind ", "मैं कब बाँध लूँगा ");
        map.put("When  will I bite", "मैं कब काटूंगा");
        map.put("When  will I bless", "मैं कब आशीष दूंगा");
        map.put("When  will I break ", "मैं कब टूटूंगा ");
        map.put("When  will I bring ", "मैं कब लाऊंगा ");
        map.put("When  will I build ", "मैं कब बनाऊंगा ");
        map.put("When  will I burn ", "मैं कब जलाऊंगा ");
        map.put("When  will I buy ", "मैं कब खरीदूंगा ");
        map.put("When  will I call ", "मैं कब कॉल करूंगा ");
        map.put("When  will I carry ", "मैं कब ले जाऊंगा ");
        map.put("When  will I catch ", "मैं कब पकड़ूँगा ");
        map.put("When  will I cheat ", "मैं कब धोखा दूँगा ");
        map.put("When  will I choose ", "मैं कब चुनूंगा ");
        map.put("When  will I clean ", "मैं कब साफ करूँगा ");
        map.put("When  will I climb  ", "मैं कब चढ़ूँगा  ");
        map.put("When  will I close ", "मैं कब बंद करूँगा ");
        map.put("When  will I come ", "मैं कब आऊंगा ");
        map.put("When  will I cook ", "मैं कब पकाऊंगा ");
        map.put("When  will I creep ", "मैं कब रेंगूंगा ");
        map.put("When  will I cry ", "मैं कब रोऊंगा ");
        map.put("When  will I cut ", "मैं कब काटूंगा ");
        map.put("When  will I dance ", "मैं कब नृत्य करूँगा ");
        map.put("When  will I deal ", "मैं कब सौदा करूंगा ");
        map.put("When  will I die ", "मैं कब मरूंगा ");
        map.put("When  will I dig ", "मैं कब खोदूँगा ");
        map.put("When  will I draw ", "मैं कब आकर्षित करूंगा ");
        map.put("When  will I drive ", "मैं कब चलाऊंगा ");
        map.put("When  will I drop ", "मैं कब छोड़ूँगा ");
        map.put("When  will I dry ", "मैं कब सुखाऊंगा ");
        map.put("When  will I eat ", "मैं कब खाऊंगा ");
        map.put("When  will I elect", "मैं कब चुनाव करूंगा");
        map.put("When  will I enter ", "मैं कब प्रवेश करूंगा ");
        map.put("When  will I fall ", "मैं कब गिरूंगा ");
        map.put("When  will I feed ", "मैं कब खिलाऊंगा ");
        map.put("When  will I feel  ", "मैं कब महसूस करूंगा  ");
        map.put("When  will I fight ", "मैं कब लड़ूंगा ");
        map.put("When  will I find ", "मुझे कब मिलेगा ");
        map.put("When  will I flee ", "मैं कब भाग जाऊंगा ");
        map.put("When  will I fly  ", "मैं कब उड़ूंगा  ");
        map.put("When  will I forget ", "मैं कब भूल जाऊंगा ");
        map.put("When  will I fry ", "मैं कब भूनूंगा ");
        map.put("When  will I get  ", "मुझे कब मिलेगा  ");
        map.put("When  will I give ", "मैं कब दूँगा ");
        map.put("When  will I go ", "मैं कब जाऊंगा ");
        map.put("When  will I grow", "मैं कब बढ़ूंगा");
        map.put("When  will I hang ", "मैं कब लटकाऊंगा ");
        map.put("When  will I hear ", "मैं कब सुनूंगा ");
        map.put("When  will I help ", "मैं कब मदद करूँगा ");
        map.put("When  will I hide ", "मैं कब छिपाऊंगा ");
        map.put("When  will I hit ", "मैं कब मारूंगा ");
        map.put("When  will I hold ", "मैं कब पकड़ लूंगा ");
        map.put("When  will I hope ", "मैं कब उम्मीद करूंगा ");
        map.put("When  will I hurt ", "मुझे कब चोट लगी होगी ");
        map.put("When  will I jump ", "मैं कब कूदूँगा ");
        map.put("When  will I keep ", "मैं कब रखूँगा ");
        map.put("When  will I kill ", "मैं कब मारूंगा ");
        map.put("When  will I know ", "मुझे कब पता चलेगा ");
        map.put("When  will I laugh ", "मैं कब हंसूंगा ");
        map.put("When  will I lead ", "मैं कब नेतृत्व करूंगा ");
        map.put("When  will I leap ", "मैं कब छलांग लगाऊंगा ");
        map.put("When  will I learn ", "मैं कब सीखूंगा ");
        map.put("When  will I leave ", "मैं कब छोड़ूँगा ");
        map.put("When  will I lend ", "मैं कब उधार दूँगा ");
        map.put("When  will I live ", "मैं कब रहूँगा ");
        map.put("When  will I look ", "मैं कब देखूँगा ");
        map.put("When  will I lose ", "मैं कब हारूंगा ");
        map.put("When  will I make ", "मैं कब बनाऊँगा ");
        map.put("When  will I marry ", "मैं कब शादी करूँगा ");
        map.put("When  will I meet ", "मैं कब मिलूंगा ");
        map.put("When  will I mistake ", "मैं कब गलती करूँगा ");
        map.put("When  will I open ", "मैं कब खोलूंगा ");
        map.put("When  will I pay  ", "मैं कब भुगतान करूंगा  ");
        map.put("When  will I play ", "मैं कब खेलूंगा ");
        map.put("When  will I put ", "मैं कब रखूँगा ");
        map.put("When  will I rain ", "मैं कब बारिश करूँगा ");
        map.put("When  will I quarrel ", "मैं झगड़ा कब करूंगा ");
        map.put("When  will I reach ", "मैं कब पहुँचूँगा ");
        map.put("When  will I read", "मैं कब पढ़ूंगा");
        map.put("When  will I remember  ", "मुझे कब याद होगा  ");
        map.put("When  will I ride ", "मैं कब सवारी करूँगा ");
        map.put("When  will I ring ", "मैं कब रिंग करूंगा ");
        map.put("When  will I rise  ", "मैं कब उठूंगा  ");
        map.put("When  will I run  ", "मैं कब दौड़ूंगा  ");
        map.put("When  will I say ", "मैं कब कहूँगा ");
        map.put("When  will I see ", "मैं कब देखूंगा ");
        map.put("When  will I sell ", "मैं कब बेचूंगा ");
        map.put("When  will I send ", "मैं कब भेजूंगा ");
        map.put("When  will I shake ", "मैं कब हिलाऊंगा ");
        map.put("When  will I shine ", "मैं कब चमकूंगा ");
        map.put("When  will I shoot ", "मैं कब शूट करूँगा ");
        map.put("When  will I shut  ", "मैं कब बंद करूँगा  ");
        map.put("When  will I sing ", "मैं कब गाऊंगा ");
        map.put("When  will I sink ", "मैं कब डूब जाऊंगा ");
        map.put("When  will I sleep ", "मैं कब सोऊंगा ");
        map.put("When  will I smell ", "मैं कब सूंघूँगा ");
        map.put("When  will I swim ", "मैं कब तैरूंगा ");
        map.put("When  will I think ", "मैं कब सोचूंगा ");

        return map;
    }
    static Map<String,String> Ten(){
        HashMap<String,String>map = new HashMap<>();
        map.put("When  will I be abusing ", "मैं कब गाली दे रहा हूँ ");
        map.put("When  will I be advising ", "मैं कब सलाह दूँगा ");
        map.put("When  will I be answering ", "मैं कब जवाब दूंगा ");
        map.put("When  will I be arising ", "मैं कब उठ रहा हूँ ");
        map.put("When  will I be arriving ", "मैं कब आऊंगा ");
        map.put("When  will I be asking ", "मैं कब पूछूंगा ");
        map.put("When  will I be awaking ", "मैं कब जाग जाऊंगा ");
        map.put("When  will I be bearing ", "मैं कब असर करूंगा ");
        map.put("When  will I be beating ", "मैं कब पिटाई करूँगा ");
        map.put("When  will I be becoming ", "मैं कब बन जाऊंगा ");
        map.put("When  will I be begging ", "मैं कब भीख माँगता हूँ ");
        map.put("When  will I be beginning ", "मैं कब शुरू करूँगा ");
        map.put("When  will I be binding ", "मैं कब बाध्यकारी रहूंगा ");
        map.put("When  will I be biting ", "मैं कब काटूंगा ");
        map.put("When  will I be blessing ", "मैं आशीष कब आऊंगा ");
        map.put("When  will I be blowing ", "मैं कब उड़ा रहा हूँ ");
        map.put("When  will I be breaking ", "मैं कब तोड़ रहा हूँ ");
        map.put("When  will I be bringing ", "मैं कब लाऊंगा ");
        map.put("When  will I be building ", "मैं कब निर्माण करूंगा ");
        map.put("When  will I be burning ", "मैं कब जल रहा हूँ ");
        map.put("When  will I be buying ", "मैं कब खरीदूंगा ");
        map.put("When  will I be calling ", "मैं कब कॉल करूँगा ");
        map.put("When  will I be carrying ", "मैं कब ले जाऊंगा ");
        map.put("When  will I be catching ", "मैं कब पकड़ लूंगा ");
        map.put("When  will I be cheating ", "मैं कब धोखा दे रहा हूँ ");
        map.put("When  will I be choosing ", "मैं कब चुनूंगा ");
        map.put("When  will I be cleaning ", "मैं कब सफाई करूँगा ");
        map.put("When  will I be climbing ", "मैं कब चढ़ जाऊंगा ");
        map.put("When  will I be closing ", "मैं कब बंद करूंगा ");
        map.put("When  will I be coming ", "मैं कब आऊंगा ");
        map.put("When  will I be cooking ", "मैं कब खाना बना रहा हूँ ");
        map.put("When  will I be creeping ", "मैं कब रेंगना चाहूँगा ");
        map.put("When  will I be crying ", "मैं कब रो रहा हूँ ");
        map.put("When  will I be cutting ", "मैं कब काटूंगा ");
        map.put("When  will I be dancing ", "मैं कब नाचता रहूंगा ");
        map.put("When  will I be dealing ", "मैं कब निपटूंगा ");
        map.put("When  will I be dying ", "मैं कब मर जाऊंगा ");
        map.put("When  will I be digging ", "मैं कब खुदाई करूँगा ");
        map.put("When  will I be drawing ", "मैं कब ड्राइंग करूंगा ");
        map.put("When  will I be drinking ", "मैं कब पी रहा हूँ ");
        map.put("When  will I be driving ", "मैं कब चला रहा हूँ ");
        map.put("When  will I be dropping ", "मैं कब छोड़ रहा हूँ ");
        map.put("When  will I be drying ", "मैं कब सुखाऊंगा ");
        map.put("When  will I be eating ", "मैं कब खाऊंगा ");
        map.put("When  will I be electing ", "मैं कब चुनाव करूंगा ");
        map.put("When  will I be entering ", "मैं कब प्रवेश करूंगा ");
        map.put("When  will I be falling ", "मैं कब गिर रहा हूँ ");
        map.put("When  will I be feeding ", "मैं कब खिलाऊंगा ");
        map.put("When  will I be feeling ", "मैं कब महसूस कर रहा हूँ ");
        map.put("When  will I be fighting ", "मैं कब लड़ूंगा ");
        map.put("When  will I be finding ", "मुझे कब मिल रहा होगा ");
        map.put("When  will I be fleeing ", "मैं कब भाग जाऊंगा ");
        map.put("When  will I be flying ", "मैं कब उड़ूंगा ");
        map.put("When  will I be forgetting ", "मैं कब भूलूंगा ");
        map.put("When  will I be frying ", "मैं कब तलूंगा ");
        map.put("When  will I be getting ", "मुझे कब मिलेगा ");
        map.put("When  will I be giving ", "मैं कब दे रहा हूँ ");
        map.put("When  will I be going ", "मैं कब जाऊंगा ");
        map.put("When  will I be growing ", "मैं कब बढ़ रहा हूँ ");
        map.put("When  will I be hanging ", "मैं कब लटकाऊंगा ");
        map.put("When  will I be hearing ", "मैं कब सुनूंगा ");
        map.put("When  will I be helping ", "मैं कब मदद करूंगा ");
        map.put("When  will I be hiding ", "मैं कब छिपाऊंगा ");
        map.put("When  will I be hitting ", "मैं कब मार रहा हूँ ");
        map.put("When  will I be holding ", "मैं कब पकड़ लूंगा ");
        map.put("When  will I be hoping ", "मैं कब उम्मीद कर रहा हूँ ");
        map.put("When  will I be hurting ", "मैं कब चोट पहुँचाऊंगा ");
        map.put("When  will I be jumping ", "मैं कब कूद रहा हूँ ");
        map.put("When  will I be keeping ", "मैं कब रखूंगा ");
        map.put("When  will I be killing ", "मैं कब मार रहा हूँ ");
        map.put("When  will I be knowing ", "मुझे कब पता चलेगा ");
        map.put("When  will I be laughing ", "मैं कब हँस रहा हूँ ");
        map.put("When  will I be leading ", "मैं कब अग्रणी रहूंगा ");
        map.put("When  will I be leaping ", "मैं कब छलांग लगाऊंगा ");
        map.put("When  will I be learning ", "मैं कब सीख रहा हूँ ");
        map.put("When  will I be leaving ", "मैं कब जा रहा हूँ ");
        map.put("When  will I be lending ", "मैं कब उधार दूंगा ");
        map.put("When  will I be living ", "मैं कब रहूँगा ");
        map.put("When  will I be looking ", "मैं कब देख रहा हूँ ");
        map.put("When  will I be losing ", "मैं कब हारूंगा ");
        map.put("When  will I be loving ", "मैं कब प्यार करूंगा ");
        map.put("When  will I be making ", "मैं कब बना रहा हूँ ");
        map.put("When  will I be marrying ", "मैं शादी कब करूँगा ");
        map.put("When  will I be meeting ", "मैं कब मिलूंगा ");
        map.put("When  will I be mistaking ", "मैं कब गलत हो जाऊंगा ");
        map.put("When  will I be opening ", "मैं कब खोलूंगा ");
        map.put("When  will I be paying ", "मैं कब भुगतान करूंगा ");
        map.put("When  will I be playing ", "मैं कब खेलूंगा ");
        map.put("When  will I be putting ", "मैं कब डालूंगा ");
        map.put("When  will I be quarrelling ", "मैं झगड़ा कब करूंगा ");
        map.put("When  will I be raining ", "मेरी बारिश कब होगी ");
        map.put("When  will I be reaching ", "मैं कब पहुँचूँगा ");
        map.put("When  will I be reading ", "मैं कब पढ़ूंगा ");
        map.put("When  will I be remembering ", "मुझे कब याद होगा ");
        map.put("When  will I be riding ", "मैं कब सवारी करूँगा ");
        map.put("When  will I be ringing ", "मैं कब बज रहा हूँ ");
        map.put("When  will I be rising ", "मैं कब उठ रहा हूँ ");
        map.put("When  will I be running ", "मैं कब दौड़ूंगा ");
        map.put("When  will I be saying ", "मैं कब कहूँगा ");
        map.put("When  will I be seeing ", "मैं कब देख रहा हूँ ");
        map.put("When  will I be selling ", "मैं कब बेचूंगा ");
        map.put("When  will I be sending ", "मैं कब भेजूंगा ");
        map.put("When  will I be shaking ", "मैं कब हिलाऊंगा ");
        map.put("When  will I be shining ", "मैं कब चमक रहा हूँ ");
        map.put("When  will I be shooting ", "मैं शूटिंग कब करूंगा ");
        map.put("When  will I be showing ", "मैं कब दिखाऊंगा ");
        map.put("When  will I be shutting ", "मैं कब बंद हो जाऊंगा ");
        map.put("When  will I be singing ", "मैं कब गा रहा हूँ ");
        map.put("When  will I be sinking ", "मैं कब डूब जाऊंगा ");
        map.put("When  will I be sleeping ", "मैं कब सो रहा हूँ ");
        map.put("When  will I be smelling ", "मुझे कब सूंघना होगा ");
        map.put("When  will I be stealing ", "मैं कब चोरी करूँगा ");
        map.put("When  will I be swimming ", "मैं कब तैरूंगा ");
        map.put("When  will I be studying ", "मैं कब पढ़ूँगा ");
        map.put("When  will I be talking ", "मैं कब बात कर रहा हूँ ");
        map.put("When  will I be tearing ", "मैं कब फाड़ रहा हूँ ");
        map.put("When  will I be wearing ", "मैं कब पहनूंगा ");
        map.put("When  will I be writing ", "मैं कब लिखूंगा ");

        return map;
    }
    static Map<String,String> Eleven(){
        HashMap<String,String>map = new HashMap<>();
        map.put("When  will I have abused ", "मैंने कब गाली दी होगी ");
        map.put("When  will I have advised ", "मैंने कब सलाह दी होगी ");
        map.put("When  will I have answered ", "मैंने कब जवाब दिया होगा ");
        map.put("When  will I have arisen ", "मैं कब उठ जाऊंगा ");
        map.put("When  will I have arrived ", "मैं कब आऊंगा ");
        map.put("When  will I have asked ", "मैंने कब पूछा होगा ");
        map.put("When  will I have awoken ", "मैं कब जाग जाऊंगा ");
        map.put("When  will I have undefined", "मैं कब अपरिभाषित होऊंगा");
        map.put("When  will I have borne ", "मैं कब पैदा करूंगा ");
        map.put("When  will I have beaten ", "मैंने कब पीटा होगा ");
        map.put("When  will I have become ", "मैं कब बन जाऊंगा ");
        map.put("When  will I have begged ", "मैं कब भीख माँगता हूँ ");
        map.put("When  will I have begun ", "मैं कब शुरू करूँगा ");
        map.put("When  will I have bound ", "मैं कब बाध्य होऊंगा ");
        map.put("When  will I have bitten ", "मैंने कब काट लिया होगा ");
        map.put("When  will I have blessed ", "मैं कब आशीष पाऊंगा ");
        map.put("When  will I have blown ", "मैं कब उड़ा जाऊंगा ");
        map.put("When  will I have broken ", "मैं कब टूटूंगा ");
        map.put("When  will I have brought ", "मैं कब लाऊंगा ");
        map.put("When  will I have built ", "मैंने कब बनाया होगा ");
        map.put("When  will I have burnt ", "मैं कब जला दूँगा ");
        map.put("When  will I have bought ", "मैंने कब खरीदा होगा ");
        map.put("When  will I have called ", "मैंने कब फोन किया होगा ");
        map.put("When  will I have carried ", "मैं कब ले जाऊंगा ");
        map.put("When  will I have caught ", "मैंने कब पकड़ा होगा ");
        map.put("When  will I have cheated ", "मैंने कब धोखा दिया होगा ");
        map.put("When  will I have chosen ", "मैंने कब चुना होगा ");
        map.put("When  will I have cleaned ", "मैंने कब साफ किया होगा ");
        map.put("When  will I have climbed ", "मैं कब चढ़ जाऊंगा ");
        map.put("When  will I have closed ", "मैं कब बंद करूँगा ");
        map.put("When  will I have come ", "मैं कब आऊँगा ");
        map.put("When  will I have cooked ", "मैंने कब पकाया होगा ");
        map.put("When  will I have crept ", "मेरे पास क्रेप्ट कब होगा ");
        map.put("When  will I have cried ", "मैं कब रोया होगा ");
        map.put("When  will I have cut ", "मैं कब कट जाऊंगा ");
        map.put("When  will I have danced ", "मैंने कब नृत्य किया होगा ");
        map.put("When  will I have dealt ", "मैंने कब निपटाया होगा ");
        map.put("When  will I have died ", "मैं कब मर जाऊंगा ");
        map.put("When  will I have dug ", "मैंने कब खोदा होगा ");
        map.put("When  will I have drawn ", "मैं कब ड्रॉ करूँगा ");
        map.put("When  will I have drunk ", "मैं कब नशे में हूँ ");
        map.put("When  will I have driven ", "मैं कब चलाऊंगा ");
        map.put("When  will I have dropped ", "मैं कब गिरा जाऊंगा ");
        map.put("When  will I have dried ", "मैं कब सूख जाऊंगा ");
        map.put("When  will I have eaten ", "मैंने कब खाया होगा ");
        map.put("When  will I have elected ", "मैं कब निर्वाचित होऊंगा ");
        map.put("When  will I have entered ", "मैं कब प्रवेश करूँगा ");
        map.put("When  will I have fallen ", "मैं कब गिर जाऊंगा ");
        map.put("When  will I have fed ", "मैंने कब खिलाया होगा ");
        map.put("When  will I have felt ", "मैंने कब महसूस किया होगा ");
        map.put("When  will I have fought ", "मैं कब लड़ूंगा ");
        map.put("When  will I have found ", "मुझे कब मिलेगा ");
        map.put("When  will I have fled ", "मैं कब भाग जाऊंगा ");
        map.put("When  will I have flown ", "मैं कब उड़ जाऊंगा ");
        map.put("When  will I have forgotten ", "मैं कब भूल जाऊंगा ");
        map.put("When  will I have fried ", "मैं कब फ्राई करूँगा ");
        map.put("When  will I have got ", "मुझे कब मिल गया होगा ");
        map.put("When  will I have given ", "मैंने कब दिया होगा ");
        map.put("When  will I have gone ", "मैं कब जाऊंगा ");
        map.put("When  will I have grown ", "मैं कब बड़ा हो जाऊंगा ");
        map.put("When  will I have hanged ", "मैं कब फांसी लगाऊंगा ");
        map.put("When  will I have hung ", "मैंने कब लटका दिया होगा ");
        map.put("When  will I have heard ", "मैंने कब सुना होगा ");
        map.put("When  will I have helped ", "मैंने कब मदद की होगी ");
        map.put("When  will I have hidden ", "मैं कब छिपाऊंगा ");
        map.put("When  will I have hit ", "मैं कब मारा जाऊंगा ");
        map.put("When  will I have held ", "मैं कब आयोजित करूंगा ");
        map.put("When  will I have hoped ", "मुझे कब उम्मीद होगी ");
        map.put("When  will I have hurt ", "मुझे कब चोट लगी होगी ");
        map.put("When  will I have jumped ", "मैं कब कूद जाऊंगा ");
        map.put("When  will I have kept ", "मैंने कब रखा होगा ");
        map.put("When  will I have killed ", "मैं कब मार डालूंगा ");
        map.put("When  will I have known ", "मुझे कब पता चलेगा ");
        map.put("When  will I have laughed ", "मैं कब हँसा होगा ");
        map.put("When  will I have led ", "मैंने कब नेतृत्व किया होगा ");
        map.put("When  will I have leapt ", "मैं कब छलांग लगाऊंगा ");
        map.put("When  will I have learnt ", "मैंने कब सीखा होगा ");
        map.put("When  will I have left ", "मैं कब छोड़ूँगा ");
        map.put("When  will I have lent ", "मैं कब उधार दूँगा ");
        map.put("When  will I have lived ", "मैं कब रहूँगा ");
        map.put("When  will I have looked ", "मैंने कब देखा होगा ");
        map.put("When  will I have lost ", "मैं कब हार जाऊंगा ");
        map.put("When  will I have loved ", "मैंने कब प्यार किया होगा ");
        map.put("When  will I have made ", "मैंने कब बनाया होगा ");
        map.put("When  will I have married ", "मैंने शादी कब की होगी ");
        map.put("When  will I have met ", "मैं कब मिलूंगा ");
        map.put("When  will I have mistaken ", "मेरी गलती कब होगी ");
        map.put("When  will I have opened ", "मैं कब खोलूंगा ");
        map.put("When  will I have paid ", "मैंने कब भुगतान किया होगा ");
        map.put("When  will I have played ", "मैं कब खेलूंगा ");
        map.put("When  will I have put ", "मैंने कब रखा होगा ");
        map.put("When  will I have quarrelled ", "मैं कब झगड़ा करूंगा ");
        map.put("When  will I have rained ", "मेरी बारिश कब होगी ");
        map.put("When  will I have reached ", "मैं कब पहुँचूँगा ");
        map.put("When  will I have read ", "मैंने कब पढ़ा होगा ");
        map.put("When  will I have remembered ", "मुझे कब याद होगा ");
        map.put("When  will I have ridden ", "मैं कब सवार हो जाऊंगा ");
        map.put("When  will I have rung ", "मैं कब रुंगा ");
        map.put("When  will I have risen ", "मैं कब उठ जाऊंगा ");
        map.put("When  will I have run ", "मैं कब दौड़ूंगा ");
        map.put("When  will I have said ", "मैंने कब कहा होगा ");
        map.put("When  will I have seen ", "मैंने कब देखा होगा ");
        map.put("When  will I have sold ", "मैं कब बेचूंगा ");
        map.put("When  will I have sent ", "मैंने कब भेजा होगा ");
        map.put("When  will I have shaken ", "मैं कब हिलाऊंगा ");
        map.put("When  will I have shone ", "मैं कब चमक जाऊंगा ");
        map.put("When  will I have shot ", "मैंने कब गोली मार दी होगी ");
        map.put("When  will I have shown ", "मैंने कब दिखाया होगा ");
        map.put("When  will I have shut ", "मैं कब बंद करूँगा ");
        map.put("When  will I have sung ", "मैंने कब गाया होगा ");
        map.put("When  will I have sunk ", "मैं कब डूब जाऊंगा ");
        map.put("When  will I have slept ", "मैं कब सोऊंगा ");
        map.put("When  will I have smelt ", "मुझे कब गलाना होगा ");
        map.put("When  will I have stolen ", "मैं कब चुरा लूंगा ");
        map.put("When  will I have told ", "मैंने कब बताया होगा ");
        map.put("When  will I have thanked ", "मैंने कब धन्यवाद दिया होगा ");
        map.put("When  will I have worn ", "मैंने कब पहना होगा ");

        return map;
    }
    static Map<String,String> Twelve(){
        HashMap<String,String>map = new HashMap<>();
        map.put("When  will I have been abusing ", "मैं कब गाली दे रहा हूँ ");
        map.put("When  will I have been advising ", "मैं कब सलाह दे रहा हूँ ");
        map.put("When  will I have been answering ", "मैं कब जवाब दे रहा हूँ ");
        map.put("When  will I have been arising ", "मैं कब उठ रहा हूँ ");
        map.put("When  will I have been arriving ", "मैं कब आ रहा हूँ ");
        map.put("When  will I have been asking ", "मैं कब पूछ रहा हूँ ");
        map.put("When  will I have been awaking ", "मैं कब जाग रहा हूँ ");
        map.put("When  will I have been undefined", "मैं कब अपरिभाषित हो जाऊंगा");
        map.put("When  will I have been bearing ", "मैं कब असर कर रहा हूँ ");
        map.put("When  will I have been beating ", "मैं कब पिटाई कर रहा हूँ ");
        map.put("When  will I have been becoming ", "मैं कब बन रहा हूँ ");
        map.put("When  will I have been begging ", "मैं कब भीख माँग रहा हूँ ");
        map.put("When  will I have been beginning ", "मैं कब शुरू कर रहा हूँ ");
        map.put("When  will I have been binding ", "मैं कब बाइंडिंग कर रहा हूँ ");
        map.put("When  will I have been biting ", "मैं कब काट रहा हूँ ");
        map.put("When  will I have been blessing ", "मैं कब आशीष रहा हूँ ");
        map.put("When  will I have been blowing ", "मैं कब उड़ रहा हूँ ");
        map.put("When  will I have been breaking ", "मैं कब तोड़ रहा हूँ ");
        map.put("When  will I have been bringing ", "मैं कब ला रहा हूँ ");
        map.put("When  will I have been building ", "मैं कब निर्माण कर रहा हूँ ");
        map.put("When  will I have been burning ", "मैं कब जल रहा हूँ ");
        map.put("When  will I have been buying ", "मैं कब खरीद रहा हूँ ");
        map.put("When  will I have been calling ", "मैं कब कॉल कर रहा हूँ ");
        map.put("When  will I have been carrying ", "मैं कब ले जा रहा हूँ ");
        map.put("When  will I have been catching ", "मैं कब पकड़ रहा हूँ ");
        map.put("When  will I have been cheating ", "मैं कब धोखा दे रहा हूँ ");
        map.put("When  will I have been choosing ", "मैं कब चुन रहा हूँ ");
        map.put("When  will I have been cleaning ", "मैं कब सफाई कर रहा हूँ ");
        map.put("When  will I have been climbing ", "मैं कब चढ़ रहा हूँ ");
        map.put("When  will I have been closing ", "मैं कब बंद कर रहा हूँ ");
        map.put("When  will I have been coming ", "मैं कब आ रहा हूँ ");
        map.put("When  will I have been cooking ", "मैं कब खाना बना रहा हूँ ");
        map.put("When  will I have been creeping ", "मैं कब रेंग रहा हूँ ");
        map.put("When  will I have been crying ", "मैं कब रो रहा हूँ ");
        map.put("When  will I have been cutting ", "मैं कब काट रहा हूँ ");
        map.put("When  will I have been dancing ", "मैं कब नाचता रहा हूँ ");
        map.put("When  will I have been dealing ", "मैं कब काम कर रहा हूँ ");
        map.put("When  will I have been dying ", "मैं कब मर रहा हूँ ");
        map.put("When  will I have been digging ", "मैं कब खुदाई कर रहा हूँ ");
        map.put("When  will I have been drawing ", "मैं कब ड्राइंग कर रहा हूँ ");
        map.put("When  will I have been drinking ", "मैं कब पी रहा हूँ ");
        map.put("When  will I have been driving ", "मैं कब गाड़ी चला रहा हूँ ");
        map.put("When  will I have been dropping ", "मैं कब छोड़ रहा हूँ ");
        map.put("When  will I have been drying ", "मैं कब सूख रहा हूँ ");
        map.put("When  will I have been eating ", "मैं कब खा रहा हूँ ");
        map.put("When  will I have been electing ", "मैं कब चुनाव कर रहा हूँ ");
        map.put("When  will I have been entering ", "मैं कब प्रवेश कर रहा हूँ ");
        map.put("When  will I have been falling ", "मैं कब गिर रहा हूँ ");
        map.put("When  will I have been feeding ", "मैं कब खिला रहा हूँ ");
        map.put("When  will I have been feeling ", "मैं कब महसूस कर रहा हूँ ");
        map.put("When  will I have been fighting ", "मैं कब लड़ रहा हूँ ");
        map.put("When  will I have been finding ", "मुझे कब मिल रहा होगा ");
        map.put("When  will I have been fleeing ", "मैं कब भाग रहा हूँ ");
        map.put("When  will I have been flying ", "मैं कब उड़ रहा हूँ ");
        map.put("When  will I have been forgetting ", "मैं कब भूल गया होता ");
        map.put("When  will I have been frying ", "मैं कब फ्राइंग कर रहा हूँ ");
        map.put("When  will I have been getting ", "मुझे कब मिल रहा होगा ");
        map.put("When  will I have been giving ", "मैं कब दे रहा हूँ ");
        map.put("When  will I have been going ", "मैं कब जा रहा हूँ ");
        map.put("When  will I have been growing ", "मैं कब बढ़ रहा हूँ ");
        map.put("When  will I have been hanging ", "मैं कब लटक रहा हूँ ");
        map.put("When  will I have been hearing ", "मैं कब सुन रहा हूँ ");
        map.put("When  will I have been helping ", "मैं कब मदद कर रहा हूँ ");
        map.put("When  will I have been hiding ", "मैं कब छिप रहा हूँ ");
        map.put("When  will I have been hitting ", "मैं कब मार रहा हूँ ");
        map.put("When  will I have been holding ", "मैं कब पकड़ रहा हूँ ");
        map.put("When  will I have been hoping ", "मैं कब उम्मीद कर रहा था ");
        map.put("When  will I have been hurting ", "मैं कब चोट पहुँचा रहा हूँ ");
        map.put("When  will I have been jumping ", "मैं कब कूद रहा हूँ ");
        map.put("When  will I have been keeping ", "मैं कब रख रहा हूँ ");
        map.put("When  will I have been killing ", "मैं कब मार रहा हूँ ");
        map.put("When  will I have been knowing ", "मुझे कब पता चल रहा होगा ");
        map.put("When  will I have been laughing ", "मैं कब हँस रहा हूँ ");
        map.put("When  will I have been leading ", "मैं कब नेतृत्व कर रहा हूँ ");
        map.put("When  will I have been leaping ", "मैं कब छलांग लगा रहा हूँ ");
        map.put("When  will I have been learning ", "मैं कब सीख रहा हूँ ");
        map.put("When  will I have been leaving ", "मैं कब जा रहा हूँ ");
        map.put("When  will I have been lending ", "मैं कब उधार दे रहा हूँ ");
        map.put("When  will I have been living ", "मैं कब रह रहा हूँ ");
        map.put("When  will I have been looking ", "मैं कब देख रहा हूँ ");
        map.put("When  will I have been losing ", "मैं कब हार रहा हूँ ");
        map.put("When  will I have been loving ", "मैं कब प्यार कर रहा हूँ ");
        map.put("When  will I have been making ", "मैं कब बना रहा हूँ ");
        map.put("When  will I have been marrying ", "मैं शादी कब कर रहा हूँ ");
        map.put("When  will I have been meeting ", "मैं कब मिल रहा हूँ ");
        map.put("When  will I have been mistaking ", "मैं कब गलत कर रहा हूँ ");
        map.put("When  will I have been opening ", "मैं कब खोल रहा हूँ ");
        map.put("When  will I have been paying ", "मैं कब भुगतान कर रहा हूँ ");
        map.put("When  will I have been playing ", "मैं कब खेल रहा हूँ ");
        map.put("When  will I have been putting ", "मैं कब लगा रहा हूँ ");
        map.put("When  will I have been quarrelling ", "मैं कब झगड़ा कर रहा हूँ ");
        map.put("When  will I have been raining ", "मेरी बारिश कब होगी ");
        map.put("When  will I have been reaching ", "मैं कब पहुँच रहा हूँ ");
        map.put("When  will I have been reading ", "मैं कब पढ़ रहा हूँ ");
        map.put("When  will I have been remembering ", "मुझे कब याद आ रहा होगा ");
        map.put("When  will I have been riding ", "मैं कब सवारी कर रहा हूँ ");
        map.put("When  will I have been ringing ", "मैं कब बज रहा हूँ ");
        map.put("When  will I have been rising ", "मैं कब उठ रहा हूँ ");
        map.put("When  will I have been running ", "मैं कब दौड़ रहा हूँ ");
        map.put("When  will I have been saying ", "मैं कब कह रहा हूँ ");
        map.put("When  will I have been seeing ", "मैं कब देख रहा हूँ ");
        map.put("When  will I have been selling ", "मैं कब बेच रहा हूँ ");
        map.put("When  will I have been sending ", "मैं कब भेज रहा हूँ ");
        map.put("When  will I have been shaking ", "मैं कब हिल रहा हूँ ");
        map.put("When  will I have been shining ", "मैं कब चमक रहा हूँ ");
        map.put("When  will I have been shooting ", "मैं कब शूटिंग कर रहा हूँ ");
        map.put("When  will I have been showing ", "मैं कब दिखा रहा हूँ ");
        map.put("When  will I have been shutting ", "मैं कब बंद कर रहा हूँ ");
        map.put("When  will I have been singing ", "मैं कब गा रहा हूँ ");
        map.put("When  will I have been sinking ", "मैं कब डूब रहा हूँ ");
        map.put("When  will I have been sleeping ", "मैं कब सो रहा हूँ ");
        map.put("When  will I have been smelling ", "मुझे कब सूंघना होगा ");
        map.put("When  will I have been telling ", "मैं कब बता रहा हूँ ");

        return map;
    }

}
