package com.shiviishiv7.helloenglish.QuestionSource;

import java.util.HashMap;
import java.util.Map;

public class Where {
    public static Map<String,String> Where(int state){
        switch (state){
            case 1:return One();
            case 2:return Two();
            case 3:return Three();
            case 4:return Four();
            case 5:return Five();
            case 6:return Six();
            case 7:return Seven();
            case 8:return Eight();
            case 9:return Nine();
            case 10:return Ten();
            case 11:return Eleven();
            case 12:return Twelve();

            default:return One();
        }

    }
    static Map<String,String> One(){
        HashMap<String,String>map = new HashMap<>();
        map.put("where do I abuse ", "मैं कहाँ गाली दूँ ");
        map.put("where do I advise", "मैं कहाँ सलाह दूँ");
        map.put("where do I answer ", "मैं कहां जवाब दूं ");
        map.put("where do I arise ", "मैं कहाँ उठूँ ");
        map.put("where do I arrive ", "मैं कहाँ पहुँचूँ ");
        map.put("where do I ask ", "मैं कहाँ पूछूँ ");
        map.put("where do I awake ", "मैं कहाँ जाग सकता हूँ ");

        map.put("where do I bear ", "मैं कहाँ सहन करूँ ");
        map.put("where do I beat ", "मैं कहाँ हराऊँ ");
        map.put("where do I become ", "मैं कहाँ बन सकता हूँ ");
        map.put("where do I beg ", "मैं कहाँ भीख माँगता हूँ ");
        map.put("where do I begin ", "मैं कहाँ से शुरू करूँ ");
        map.put("where do I bind ", "मैं कहाँ बाँध सकता हूँ ");
        map.put("where do I bite", "मैं कहाँ काटूँ");
        map.put("where do I bless", "मैं कहाँ आशीष देता हूँ");
        map.put("where do I blow ", "मैं कहाँ उड़ूँ ");
        map.put("where do I break ", "मैं कहाँ तोड़ूँ ");
        map.put("where do I bring ", "मैं कहाँ लाऊँ ");
        map.put("where do I build ", "मैं कहाँ बनाऊँ ");
        map.put("where do I burn ", "मैं कहाँ जलाता हूँ ");
        map.put("where do I buy ", "मैं कहाँ खरीदूँ ");
        map.put("where do I call ", "मैं कहां कॉल करूँ ");
        map.put("where do I carry ", "मैं कहाँ ले जाऊँ ");
        map.put("where do I catch ", "मैं कहाँ पकड़ूँ ");
        map.put("where do I choose ", "मैं कहां चुनूं ");
        map.put("where do I clean ", "मैं कहाँ साफ करूँ ");
        map.put("where do I climb  ", "मैं कहाँ चढ़ूँ  ");
        map.put("where do I close ", "मैं कहाँ बंद करूँ ");
        map.put("where do I come ", "मैं कहाँ आऊँ ");
        map.put("where do I cook ", "मैं कहाँ खाना बनाती हूँ ");
        map.put("where do I creep ", "मैं कहाँ रेंगता हूँ ");
        map.put("where do I cry ", "मैं कहाँ रोऊँ ");
        map.put("where do I cut ", "मैं कहाँ काटूँ ");
        map.put("where do I dance ", "मैं कहाँ नाचता हूँ ");
        map.put("where do I deal ", "मैं कहाँ सौदा करूँ ");
        map.put("where do I die ", "मैं कहाँ मरूँ ");
        map.put("where do I dig ", "मैं कहाँ खोदूँ ");
        map.put("where do I do ", "मैं कहाँ करूँ ");
        map.put("where do I draw ", "मैं कहाँ आकर्षित करूँ ");
        map.put("where do I drive ", "मैं कहाँ चलाऊँ ");
        map.put("where do I drop ", "मैं कहाँ छोड़ूँ ");
        map.put("where do I dry ", "मैं कहाँ सुखाऊँ ");
        map.put("where do I eat ", "मैं कहाँ खाऊँ ");
        map.put("where do I elect", "मैं कहाँ चुनाव करूँ");
        map.put("where do I fall ", "मैं कहाँ गिरूँ ");
        map.put("where do I feed ", "मैं कहाँ खिलाऊँ ");
        map.put("where do I feel  ", "मैं कहाँ महसूस करता हूँ  ");
        map.put("where do I fight ", "मैं कहाँ लड़ूँ ");
        map.put("where do I find ", "मैं कहाँ ढूँढ सकता हूँ ");
        map.put("where do I flee ", "मैं कहाँ भाग जाऊँ ");
        map.put("where do I fly  ", "मैं कहाँ उड़ूँ  ");
        map.put("where do I forget ", "मैं कहाँ भूलूँ ");
        map.put("where do I fry ", "मैं कहाँ भूनूँ ");
        map.put("where do I get  ", "मुझे कहाँ मिलेगा  ");
        map.put("where do I give ", "मैं कहाँ दूँ ");
        map.put("where do I go ", "मैं कहाँ जाऊँ ");
        map.put("where do I grow", "मैं कहाँ उगता हूँ");
        map.put("where do I hang ", "मैं कहाँ लटकाऊँ ");
        map.put("where do I hear ", "मैं कहाँ सुन सकता हूँ ");
        map.put("where do I help ", "मैं कहाँ मदद करूँ ");
        map.put("where do I hide ", "मैं कहाँ छिपाऊँ ");
        map.put("where do I hit ", "मैं कहाँ मारूँ ");
        map.put("where do I hold ", "मैं कहाँ पकड़ूँ ");
        map.put("where do I hope ", "मैं कहाँ आशा करता हूँ ");
        map.put("where do I hurt ", "मैं कहाँ चोट पहुँचाऊँ ");
        map.put("where do I jump ", "मैं कहाँ कूदता हूँ ");
        map.put("where do I kill ", "मैं कहाँ मारूँ ");
        map.put("where do I know ", "मुझे कहाँ पता है ");
        map.put("where do I laugh ", "मैं कहाँ हँसता हूँ ");
        map.put("where do I lead ", "मैं कहाँ ले जाऊँ ");
        map.put("where do I leap ", "मैं कहाँ छलांग लगाऊँ ");
        map.put("where do I learn ", "मैं कहाँ सीखूँ ");
        map.put("where do I leave ", "मैं कहाँ छोड़ूँ ");
        map.put("where do I lend ", "मैं कहाँ उधार दे सकता हूँ ");
        map.put("where do I live ", "मैं कहाँ रहूँ ");
        map.put("where do I look ", "मैं कहाँ देखूँ ");
        map.put("where do I lose ", "मैं कहाँ हारूँ ");
        map.put("where do I love ", "मैं कहाँ प्यार करता हूँ ");
        map.put("where do I make ", "मैं कहाँ बनाऊँ ");
        map.put("where do I marry ", "मैं कहाँ शादी करूँ ");
        map.put("where do I meet ", "मैं कहाँ मिलूँ ");
        map.put("where do I mistake ", "मैं कहाँ गलती करूँ ");
        map.put("where do I open ", "मैं कहाँ खोलूँ ");
        map.put("where do I pay  ", "मैं कहाँ भुगतान करूँ  ");
        map.put("where do I play ", "मैं कहाँ खेलूँ ");
        map.put("where do I put ", "मैं कहाँ रखूँ ");
        map.put("where do I rain ", "मैं बारिश कहाँ करूँ ");
        map.put("where do I reach ", "मैं कहाँ पहुँचूँ ");
        map.put("where do I read", "मैं कहाँ पढ़ूँ");
        map.put("where do I remember  ", "मुझे कहाँ याद है  ");
        map.put("where do I ride ", "मैं कहाँ सवारी करूँ ");
        map.put("where do I ring ", "मैं कहाँ रिंग करूँ ");
        map.put("where do I rise  ", "मैं कहाँ उठूँ  ");
        map.put("where do I run  ", "मैं कहाँ दौड़ूँ  ");
        map.put("where do I say ", "मैं कहाँ कहूँ ");
        map.put("where do I see ", "मैं कहाँ देखूँ ");
        map.put("where do I sell ", "मैं कहाँ बेचूँ ");
        map.put("where do I send ", "मैं कहाँ भेजूँ ");
        map.put("where do I shake ", "मैं कहाँ हिला सकता हूँ ");
        map.put("where do I shine ", "मैं कहाँ चमकता हूँ ");
        map.put("where do I shoot ", "मैं कहाँ शूट करूँ ");
        map.put("where do I show ", "मैं कहाँ दिखाऊँ ");
        map.put("where do I shut  ", "मैं कहाँ बंद करूँ  ");
        map.put("where do I sing ", "मैं कहाँ गाऊँ ");
        map.put("where do I sink ", "मैं कहाँ डूबता हूँ ");
        map.put("where do I sleep ", "मैं कहाँ सोता हूँ ");
        map.put("where do I talk ", "मैं कहाँ बात करूँ ");
        map.put("where do I wash ", "मैं कहाँ धोऊँ ");

        return map;
    }
    static Map<String,String> Two(){
        HashMap<String,String>map = new HashMap<>();
        map.put("where am I abusing ", "मैं कहाँ गाली दे रहा हूँ ");
        map.put("where am I advising ", "मैं कहाँ सलाह दे रहा हूँ ");
        map.put("where am I answering ", "मैं कहाँ जवाब दे रहा हूँ ");
        map.put("where am I arising ", "मैं कहाँ उठ रहा हूँ ");
        map.put("where am I arriving ", "मैं कहाँ आ रहा हूँ ");
        map.put("where am I asking ", "मैं कहाँ पूछ रहा हूँ ");
        map.put("where am I awaking ", "मैं कहाँ जाग रहा हूँ ");
        map.put("where am I undefined", "मैं अपरिभाषित कहाँ हूँ");
        map.put("where am I bearing ", "मैं कहाँ असर कर रहा हूँ ");
        map.put("where am I beating ", "मैं कहाँ पिटाई कर रहा हूँ ");
        map.put("where am I becoming ", "मैं कहाँ बन रहा हूँ ");
        map.put("where am I begging ", "मैं कहाँ भीख माँग रहा हूँ ");
        map.put("where am I beginning ", "मैं कहाँ से शुरू कर रहा हूँ ");
        map.put("where am I binding ", "मैं कहाँ बाध्यकारी हूँ ");
        map.put("where am I biting ", "मैं कहाँ काट रहा हूँ ");
        map.put("where am I blessing ", "मैं कहाँ आशीर्वाद दे रहा हूँ ");
        map.put("where am I blowing ", "मैं कहाँ उड़ रहा हूँ ");
        map.put("where am I breaking ", "मैं कहाँ तोड़ रहा हूँ ");
        map.put("where am I bringing ", "मैं कहाँ ला रहा हूँ ");
        map.put("where am I building ", "मैं कहाँ निर्माण कर रहा हूँ ");
        map.put("where am I burning ", "मैं कहाँ जल रहा हूँ ");
        map.put("where am I buying ", "मैं कहाँ खरीद रहा हूँ ");
        map.put("where am I calling ", "मैं कहां कॉल कर रहा हूँ ");
        map.put("where am I carrying ", "मैं कहाँ ले जा रहा हूँ ");
        map.put("where am I catching ", "मैं कहाँ पकड़ रहा हूँ ");
        map.put("where am I cheating ", "मैं कहाँ धोखा दे रहा हूँ ");
        map.put("where am I choosing ", "मैं कहाँ चुन रहा हूँ ");
        map.put("where am I cleaning ", "मैं कहाँ सफाई कर रहा हूँ ");
        map.put("where am I climbing ", "मैं कहाँ चढ़ रहा हूँ ");
        map.put("where am I closing ", "मैं कहाँ बंद कर रहा हूँ ");
        map.put("where am I coming ", "मैं कहाँ आ रहा हूँ ");
        map.put("where am I cooking ", "मैं कहाँ खाना बना रहा हूँ ");
        map.put("where am I creeping ", "मैं कहाँ रेंग रहा हूँ ");
        map.put("where am I crying ", "मैं कहाँ रो रहा हूँ ");
        map.put("where am I cutting ", "मैं कहाँ काट रहा हूँ ");
        map.put("where am I dancing ", "मैं कहाँ नाच रहा हूँ ");
        map.put("where am I dealing ", "मैं कहाँ काम कर रहा हूँ ");
        map.put("where am I dying ", "मैं कहाँ मर रहा हूँ ");
        map.put("where am I digging ", "मैं कहाँ खोद रहा हूँ ");
        map.put("where am I doing ", "मैं कहाँ कर रहा हूँ ");
        map.put("where am I drawing ", "मैं कहाँ ड्राइंग कर रहा हूँ ");
        map.put("where do I dream ", "मैं कहाँ सपने देखता हूँ ");
        map.put("where  have I been dreaming ", "मैं कहाँ सपना देख रहा हूँ ");
        map.put("where am I dreaming ", "मैं कहाँ सपना देख रहा हूँ ");
        map.put("where  have I dreamt ", "मैंने कहाँ सपना देखा है ");
        map.put("where  did I  dream ", "मैंने कहाँ सपना देखा था ");
        map.put("where  was I  dreaming ", "मैं कहाँ सपना देख रहा था ");
        map.put("where  had I  dreamt ", "मैंने सपना कहाँ देखा था ");
        map.put("where  will I have dreamt ", "मैंने सपना कहाँ देखा होगा ");
        map.put("where  had I been  dreaming ", "मैं कहाँ सपना देख रहा था ");
        map.put("where  will I be dreaming ", "मैं कहाँ सपना देख रहा हूँ ");
        map.put("where  will I have been dreaming ", "मैं कहाँ सपना देख रहा हूँ ");
        map.put("where am I drinking ", "मैं कहाँ पी रहा हूँ ");
        map.put("where am I driving ", "मैं कहाँ चला रहा हूँ ");
        map.put("where am I dropping ", "मैं कहाँ छोड़ रहा हूँ ");
        map.put("where am I drying ", "मैं कहाँ सूख रहा हूँ ");
        map.put("where am I eating ", "मैं कहाँ खा रहा हूँ ");
        map.put("where am I electing ", "मैं कहाँ चुनाव कर रहा हूँ ");
        map.put("where am I entering ", "मैं कहाँ प्रवेश कर रहा हूँ ");
        map.put("where am I falling ", "मैं कहाँ गिर रहा हूँ ");
        map.put("where am I feeding ", "मैं कहाँ खिला रहा हूँ ");
        map.put("where am I feeling ", "मैं कहाँ महसूस कर रहा हूँ ");
        map.put("where am I fighting ", "मैं कहाँ लड़ रहा हूँ ");
        map.put("where am I finding ", "मैं कहाँ ढूँढ रहा हूँ ");
        map.put("where am I fleeing ", "मैं कहाँ भाग रहा हूँ ");
        map.put("where am I flying ", "मैं कहाँ उड़ रहा हूँ ");
        map.put("where am I forgetting ", "मैं कहाँ भूल रहा हूँ ");
        map.put("where am I frying ", "मैं कहाँ फ्राइंग कर रहा हूँ ");
        map.put("where am I getting ", "मुझे कहाँ मिल रहा है ");
        map.put("where am I giving ", "मैं कहाँ दे रहा हूँ ");
        map.put("where am I going ", "मैं कहाँ जा रहा हूँ ");
        map.put("where am I growing ", "मैं कहाँ बढ़ रहा हूँ ");
        map.put("where am I hanging ", "मैं कहाँ लटक रहा हूँ ");
        map.put("where am I hearing ", "मैं कहाँ सुन रहा हूँ ");
        map.put("where am I helping ", "मैं कहाँ मदद कर रहा हूँ ");
        map.put("where am I hiding ", "मैं कहाँ छिपा रहा हूँ ");
        map.put("where am I hitting ", "मैं कहाँ मार रहा हूँ ");
        map.put("where am I holding ", "मैं कहाँ पकड़ रहा हूँ ");
        map.put("where am I hoping ", "मैं कहाँ उम्मीद कर रहा हूँ ");
        map.put("where am I hurting ", "मैं कहाँ चोट पहुँचा रहा हूँ ");
        map.put("where am I jumping ", "मैं कहाँ कूद रहा हूँ ");
        map.put("where am I keeping ", "मैं कहाँ रख रहा हूँ ");
        map.put("where am I killing ", "मैं कहाँ मार रहा हूँ ");
        map.put("where am I knowing ", "मैं कहाँ जान रहा हूँ ");
        map.put("where am I laughing ", "मैं कहाँ हँस रहा हूँ ");
        map.put("where am I leading ", "मैं कहाँ जा रहा हूँ ");
        map.put("where am I leaping ", "मैं कहाँ छलांग लगा रहा हूँ ");
        map.put("where am I learning ", "मैं कहाँ सीख रहा हूँ ");
        map.put("where am I leaving ", "मैं कहाँ जा रहा हूँ ");
        map.put("where am I lending ", "मैं कहाँ उधार दे रहा हूँ ");
        map.put("where am I living ", "मैं कहाँ रह रहा हूँ ");
        map.put("where am I looking ", "मैं कहाँ देख रहा हूँ ");
        map.put("where am I losing ", "मैं कहाँ हार रहा हूँ ");
        map.put("where am I loving ", "मैं कहाँ प्यार कर रहा हूँ ");
        map.put("where am I making ", "मैं कहाँ बना रहा हूँ ");
        map.put("where am I marrying ", "मैं कहाँ शादी कर रहा हूँ ");
        map.put("where am I meeting ", "मैं कहाँ मिल रहा हूँ ");
        map.put("where am I mistaking ", "मैं कहाँ गलत कर रहा हूँ ");
        map.put("where am I opening ", "मैं कहाँ खोल रहा हूँ ");
        map.put("where am I paying ", "मैं कहाँ भुगतान कर रहा हूँ ");
        map.put("where am I playing ", "मैं कहाँ खेल रहा हूँ ");
        map.put("where am I putting ", "मैं कहाँ रख रहा हूँ ");
        map.put("where am I quarrelling ", "मैं कहाँ झगड़ा कर रहा हूँ ");
        map.put("where am I raining ", "मैं कहाँ बारिश कर रहा हूँ ");
        map.put("where am I reaching ", "मैं कहाँ पहुँच रहा हूँ ");
        map.put("where am I reading ", "मैं कहाँ पढ़ रहा हूँ ");
        map.put("where am I remembering ", "मैं कहाँ याद कर रहा हूँ ");
        map.put("where am I riding ", "मैं कहाँ सवारी कर रहा हूँ ");
        map.put("where am I ringing ", "मैं कहाँ बज रहा हूँ ");
        map.put("where am I rising ", "मैं कहाँ उठ रहा हूँ ");
        map.put("where am I running ", "मैं कहाँ चल रहा हूँ ");
        map.put("where am I saying ", "मैं कहाँ कह रहा हूँ ");
        map.put("where am I seeing ", "मैं कहाँ देख रहा हूँ ");
        map.put("where am I selling ", "मैं कहाँ बेच रहा हूँ ");
        map.put("where am I sending ", "मैं कहाँ भेज रहा हूँ ");
        map.put("where am I shaking ", "मैं कहाँ हिल रहा हूँ ");
        map.put("where am I shining ", "मैं कहाँ चमक रहा हूँ ");
        map.put("where am I shooting ", "मैं कहाँ शूटिंग कर रहा हूँ ");
        map.put("where am I showing ", "मैं कहाँ दिखा रहा हूँ ");
        map.put("where am I shutting ", "मैं कहाँ बंद कर रहा हूँ ");
        map.put("where am I singing ", "मैं कहाँ गा रहा हूँ ");
        map.put("where am I sinking ", "मैं कहाँ डूब रहा हूँ ");
        map.put("where am I sleeping ", "मैं कहाँ सो रहा हूँ ");
        map.put("where am I spending ", "मैं कहाँ खर्च कर रहा हूँ ");
        map.put("where am I starting ", "मैं कहाँ से शुरू कर रहा हूँ ");
        map.put("where am I talking ", "मैं कहाँ बात कर रहा हूँ ");

        return map;
    }
    static Map<String,String> Three(){
        HashMap<String,String>map = new HashMap<>();
        map.put("where  have I abused ", "मैंने कहाँ गाली दी है ");
        map.put("where  have I advised ", "मैंने कहाँ सलाह दी है ");
        map.put("where  have I answered ", "मैंने कहाँ उत्तर दिया है ");
        map.put("where  have I arisen ", "मैं कहाँ पैदा हुआ हूँ ");
        map.put("where  have I arrived ", "मैं कहाँ पहुँचा हूँ ");
        map.put("where  have I asked ", "मैंने कहाँ पूछा है ");
        map.put("where  have I awoken ", "मैं कहाँ जाग गया हूँ ");
        map.put("where  have I undefined", "मैंने अपरिभाषित कहाँ किया है");
        map.put("where  have I borne ", "मैंने कहाँ पैदा किया है ");
        map.put("where  have I beaten ", "मैंने कहाँ पीटा है ");
        map.put("where  have I become ", "मैं कहाँ बन गया हूँ ");
        map.put("where  have I begged ", "मैंने कहाँ भीख माँगी है ");
        map.put("where  have I begun ", "मैंने कहाँ से शुरू किया है ");
        map.put("where  have I bound ", "मैंने कहाँ बाध्य किया है ");
        map.put("where  have I bitten ", "मैंने कहाँ काटा है ");
        map.put("where  have I blessed ", "मैंने कहाँ आशीष दी है ");
        map.put("where  have I blown ", "मैंने कहाँ उड़ा दिया है ");
        map.put("where  have I broken ", "मैंने कहाँ तोड़ा है ");
        map.put("where  have I brought ", "मैं कहाँ लाया हूँ ");
        map.put("where  have I built ", "मैंने कहाँ बनाया है ");
        map.put("where  have I burnt ", "मैंने कहाँ जला दिया है ");
        map.put("where  have I bought ", "मैंने कहाँ खरीदा है ");
        map.put("where  have I called ", "मैंने कहाँ बुलाया है ");
        map.put("where  have I carried ", "मैं कहाँ ले गया हूँ ");
        map.put("where  have I caught ", "मैंने कहाँ पकड़ा है ");
        map.put("where  have I cheated ", "मैंने कहाँ धोखा दिया है ");
        map.put("where  have I chosen ", "मैंने कहाँ चुना है ");
        map.put("where  have I cleaned ", "मैंने कहाँ साफ किया है ");
        map.put("where  have I climbed ", "मैं कहाँ चढ़ गया हूँ ");
        map.put("where  have I closed ", "मैंने कहाँ बंद किया है ");
        map.put("where  have I come ", "मैं कहाँ आया हूँ ");
        map.put("where  have I cooked ", "मैंने कहाँ पकाया है ");
        map.put("where  have I crept ", "मैंने कहाँ क्रेप किया है ");
        map.put("where  have I cried ", "मैं कहाँ रोया हूँ ");
        map.put("where  have I cut ", "मैंने कहाँ काटा है ");
        map.put("where  have I danced ", "मैंने कहाँ नृत्य किया है ");
        map.put("where  have I dealt ", "मैंने कहाँ से निपटा है ");
        map.put("where  have I died ", "मैं कहाँ मर गया हूँ ");
        map.put("where  have I dug ", "मैंने कहाँ खोदा है ");
        map.put("where  have I done ", "मैंने कहाँ किया है ");
        map.put("where  have I drawn ", "मैंने कहाँ खींचा है ");
        map.put("where  have I drunk ", "मैंने कहाँ पिया है ");
        map.put("where  have I driven ", "मैंने कहाँ चलाया है ");
        map.put("where  have I dropped ", "मैंने कहाँ गिरा दिया है ");
        map.put("where  have I dried ", "मैंने कहाँ सुखाया है ");
        map.put("where  have I eaten ", "मैंने कहाँ खाया है ");
        map.put("where  have I elected ", "मैंने कहाँ चुना है ");
        map.put("where  have I entered ", "मैंने कहाँ प्रवेश किया है ");
        map.put("where  have I fallen ", "मैं कहाँ गिर गया हूँ ");
        map.put("where  have I fed ", "मैंने कहाँ खिलाया है ");
        map.put("where  have I felt ", "मैंने कहाँ महसूस किया है ");
        map.put("where  have I fought ", "मैंने कहाँ लड़ा है ");
        map.put("where  have I found ", "मुझे कहाँ मिला है ");
        map.put("where  have I fled ", "मैं कहाँ भाग गया हूँ ");
        map.put("where  have I flown ", "मैं कहाँ उड़ गया हूँ ");
        map.put("where  have I forgotten ", "मैं कहाँ भूल गया हूँ ");
        map.put("where  have I fried ", "मैंने कहाँ तला हुआ है ");
        map.put("where  have I got ", "मुझे कहाँ मिला है ");
        map.put("where  have I given ", "मैंने कहाँ दिया है ");
        map.put("where  have I gone ", "मैं कहाँ गया हूँ ");
        map.put("where  have I grown ", "मैं कहाँ उगाया हूँ ");
        map.put("where  have I hanged ", "मैंने कहाँ फांसी लगाई है ");
        map.put("where  have I hung ", "मैंने कहाँ लटका दिया है ");
        map.put("where  have I heard ", "मैंने कहाँ सुना है ");
        map.put("where  have I helped ", "मैंने कहाँ मदद की है ");
        map.put("where  have I hidden ", "मैंने कहाँ छिपाया है ");
        map.put("where  have I hit ", "मैंने कहाँ मारा है ");
        map.put("where  have I held ", "मैंने कहाँ आयोजित किया है ");
        map.put("where  have I hoped ", "मैंने कहाँ आशा की है ");
        map.put("where  have I hurt ", "मुझे कहाँ चोट लगी है ");
        map.put("where  have I jumped ", "मैं कहाँ कूद गया ");
        map.put("where  have I kept ", "मैंने कहाँ रखा है ");
        map.put("where  have I killed ", "मैंने कहाँ मारा है ");
        map.put("where  have I known ", "मुझे कहाँ पता है ");
        map.put("where  have I laughed ", "मैं कहाँ हँसा हूँ ");
        map.put("where  have I led ", "मैंने कहाँ नेतृत्व किया है ");
        map.put("where  have I leapt ", "मैंने कहाँ छलांग लगाई है ");
        map.put("where  have I learnt ", "मैंने कहाँ सीखा है ");
        map.put("where  have I left ", "मैंने कहाँ छोड़ा है ");
        map.put("where  have I lent ", "मैंने कहाँ उधार दिया है ");
        map.put("where  have I lived ", "मैं कहाँ रहता हूँ ");
        map.put("where  have I looked ", "मैंने कहाँ देखा है ");
        map.put("where  have I lost ", "मैं कहाँ खो चुका हूँ ");
        map.put("where  have I loved ", "मैंने कहाँ प्यार किया है ");
        map.put("where  have I made ", "मैंने कहाँ बनाया है ");
        map.put("where  have I married ", "मैंने शादी कहाँ की है ");
        map.put("where  have I met ", "मैं कहाँ मिला हूँ ");
        map.put("where  have I mistaken ", "मैंने कहाँ गलत किया है ");
        map.put("where  have I opened ", "मैंने कहाँ खोला है ");
        map.put("where  have I paid ", "मैंने कहाँ भुगतान किया है ");
        map.put("where  have I played ", "मैंने कहाँ खेला है ");
        map.put("where  have I put ", "मैंने कहाँ रखा है ");
        map.put("where  have I quarrelled ", "मैंने कहाँ झगड़ा किया है ");
        map.put("where  have I rained ", "मैंने कहाँ बारिश की है ");
        map.put("where  have I reached ", "मैं कहाँ पहुँचा हूँ ");
        map.put("where  have I read ", "मैंने कहाँ पढ़ा है ");
        map.put("where  have I remembered ", "मुझे कहाँ याद आया ");
        map.put("where  have I ridden ", "मैंने कहाँ सवारी की है ");
        map.put("where  have I rung ", "मैंने कहाँ बजाया है ");
        map.put("where  have I risen ", "मैं कहाँ उठ गया हूँ ");
        map.put("where  have I run ", "मैं कहाँ चला रहा हूँ ");
        map.put("where  have I said ", "मैंने कहाँ कहा है ");
        map.put("where  have I seen ", "मैंने कहाँ देखा है ");
        map.put("where  have I sold ", "मैंने कहाँ बेचा है ");
        map.put("where  have I sent ", "मैंने कहाँ भेजा है ");
        map.put("where  have I shaken ", "मैं कहाँ हिल गया हूँ ");
        map.put("where  have I shone ", "मैं कहाँ चमक रहा हूँ ");
        map.put("where  have I shot ", "मैंने कहाँ गोली मारी है ");
        map.put("where  have I shown ", "मैंने कहाँ दिखाया है ");
        map.put("where  have I shut ", "मैंने कहाँ बंद किया है ");
        map.put("where  have I sung ", "मैंने कहाँ गाया है ");
        map.put("where  have I sunk ", "मैं कहाँ डूब गया हूँ ");
        map.put("where  have I slept ", "मैं कहाँ सोया हूँ ");
        map.put("where  have I spent ", "मैंने कहाँ खर्च किया है ");

        return map;
    }
    static Map<String,String> Four(){
        HashMap<String,String>map = new HashMap<>();
        map.put("where  have I been abusing ", "मैं कहाँ गाली दे रहा हूँ ");
        map.put("where  have I been advising ", "मैं कहाँ सलाह दे रहा हूँ ");
        map.put("where  have I been answering ", "मैं कहाँ जवाब दे रहा हूँ ");
        map.put("where  have I been arising ", "मैं कहाँ उठ रहा हूँ ");
        map.put("where  have I been arriving ", "मैं कहाँ आ रहा हूँ ");
        map.put("where  have I been asking ", "मैं कहाँ पूछ रहा हूँ ");
        map.put("where  have I been awaking ", "मैं कहाँ जाग रहा हूँ ");
        map.put("where  have I been undefined", "मुझे अपरिभाषित कहाँ किया गया है");
        map.put("where  have I been bearing ", "मैं कहाँ असर कर रहा हूँ ");
        map.put("where  have I been beating ", "मैं कहाँ पिटाई कर रहा हूँ ");
        map.put("where  have I been becoming ", "मैं कहाँ बन रहा हूँ ");
        map.put("where  have I been begging ", "मैं कहाँ भीख माँग रहा हूँ ");
        map.put("where  have I been beginning ", "मैं कहाँ से शुरू कर रहा हूँ ");
        map.put("where  have I been binding ", "मैं कहाँ बाध्यकारी रहा हूँ ");
        map.put("where  have I been biting ", "मैं कहाँ काट रहा हूँ ");
        map.put("where  have I been blessing ", "मैं आशीष कहाँ रहा हूँ ");
        map.put("where  have I been blowing ", "मैं कहाँ उड़ रहा हूँ ");
        map.put("where  have I been breaking ", "मैं कहाँ तोड़ रहा हूँ ");
        map.put("where  have I been bringing ", "मैं कहाँ ला रहा हूँ ");
        map.put("where  have I been building ", "मैं कहाँ बना रहा हूँ ");
        map.put("where  have I been burning ", "मैं कहाँ जल रहा हूँ ");
        map.put("where  have I been buying ", "मैं कहाँ खरीद रहा हूँ ");
        map.put("where  have I been calling ", "मैं कहाँ बुला रहा हूँ ");
        map.put("where  have I been carrying ", "मैं कहाँ ले जा रहा हूँ ");
        map.put("where  have I been catching ", "मैं कहाँ पकड़ रहा हूँ ");
        map.put("where  have I been cheating ", "मैं कहाँ धोखा दे रहा हूँ ");
        map.put("where  have I been choosing ", "मैं कहाँ चुन रहा हूँ ");
        map.put("where  have I been cleaning ", "मैं कहाँ सफाई कर रहा हूँ ");
        map.put("where  have I been climbing ", "मैं कहाँ चढ़ रहा हूँ ");
        map.put("where  have I been closing ", "मैं कहाँ बंद कर रहा हूँ ");
        map.put("where  have I been coming ", "मैं कहाँ आ रहा हूँ ");
        map.put("where  have I been cooking ", "मैं कहाँ खाना बना रहा हूँ ");
        map.put("where  have I been creeping ", "मैं कहाँ रेंग रहा हूँ ");
        map.put("where  have I been crying ", "मैं कहाँ रो रहा हूँ ");
        map.put("where  have I been cutting ", "मैं कहाँ काट रहा हूँ ");
        map.put("where  have I been dancing ", "मैं कहाँ नाच रहा हूँ ");
        map.put("where  have I been dealing ", "मैं कहाँ काम कर रहा हूँ ");
        map.put("where  have I been dying ", "मैं कहाँ मर रहा हूँ ");
        map.put("where  have I been digging ", "मैं कहाँ खोद रहा हूँ ");
        map.put("where  have I been doing ", "मैं कहाँ कर रहा हूँ ");
        map.put("where  have I been drawing ", "मैं कहाँ आरेखण कर रहा हूँ ");
        map.put("where  have I been drinking ", "मैं कहाँ पी रहा हूँ ");
        map.put("where  have I been driving ", "मैं कहाँ चला रहा हूँ ");
        map.put("where  have I been dropping ", "मैं कहाँ गिर रहा हूँ ");
        map.put("where  have I been drying ", "मैं कहाँ सूख रहा हूँ ");
        map.put("where  have I been eating ", "मैं कहाँ खा रहा हूँ ");
        map.put("where  have I been electing ", "मैं कहाँ चुनाव कर रहा हूँ ");
        map.put("where  have I been entering ", "मैं कहाँ प्रवेश कर रहा हूँ ");
        map.put("where  have I been falling ", "मैं कहाँ गिर रहा हूँ ");
        map.put("where  have I been feeding ", "मैं कहाँ खिला रहा हूँ ");
        map.put("where  have I been feeling ", "मैं कहाँ महसूस कर रहा हूँ ");
        map.put("where  have I been fighting ", "मैं कहाँ लड़ रहा हूँ ");
        map.put("where  have I been finding ", "मुझे कहाँ मिल रहा है ");
        map.put("where  have I been fleeing ", "मैं कहाँ भाग रहा हूँ ");
        map.put("where  have I been flying ", "मैं कहाँ उड़ रहा हूँ ");
        map.put("where  have I been forgetting ", "मैं कहाँ भूल रहा हूँ ");
        map.put("where  have I been frying ", "मैं कहाँ तलने गया हूँ ");
        map.put("where  have I been getting ", "मुझे कहाँ मिल रहा है ");
        map.put("where  have I been giving ", "मैं कहाँ दे रहा हूँ ");
        map.put("where  have I been going ", "मैं कहाँ जा रहा हूँ ");
        map.put("where  have I been growing ", "मैं कहाँ बढ़ रहा हूँ ");
        map.put("where  have I been hanging ", "मैं कहाँ लटक रहा हूँ ");
        map.put("where  have I been hearing ", "मैं कहाँ सुन रहा हूँ ");
        map.put("where  have I been helping ", "मैं कहाँ मदद कर रहा हूँ ");
        map.put("where  have I been hiding ", "मैं कहाँ छिपा रहा हूँ ");
        map.put("where  have I been hitting ", "मैं कहाँ मार रहा हूँ ");
        map.put("where  have I been holding ", "मैं कहाँ पकड़ रहा हूँ ");
        map.put("where  have I been hoping ", "मैं कहाँ उम्मीद कर रहा था ");
        map.put("where  have I been hurting ", "मैं कहाँ चोट पहुँचा रहा हूँ ");
        map.put("where  have I been jumping ", "मैं कहाँ कूद रहा हूँ ");
        map.put("where  have I been keeping ", "मैं कहाँ रख रहा हूँ ");
        map.put("where  have I been killing ", "मैं कहाँ मार रहा हूँ ");
        map.put("where  have I been knowing ", "मैं कहाँ जान रहा हूँ ");
        map.put("where  have I been laughing ", "मैं कहाँ हँस रहा हूँ ");
        map.put("where  have I been leading ", "मैं कहाँ अग्रणी रहा हूँ ");
        map.put("where  have I been leaping ", "मैं कहाँ छलांग लगा रहा हूँ ");
        map.put("where  have I been learning ", "मैं कहाँ सीख रहा हूँ ");
        map.put("where  have I been leaving ", "मैं कहाँ जा रहा हूँ ");
        map.put("where  have I been lending ", "मैं कहाँ उधार दे रहा हूँ ");
        map.put("where  have I been living ", "मैं कहाँ रह रहा हूँ ");
        map.put("where  have I been looking ", "मैं कहाँ देख रहा हूँ ");
        map.put("where  have I been losing ", "मैं कहाँ हार रहा हूँ ");
        map.put("where  have I been loving ", "मैं कहाँ प्यार कर रहा हूँ ");
        map.put("where  have I been making ", "मैं कहाँ बना रहा हूँ ");
        map.put("where  have I been marrying ", "मैं कहाँ से शादी कर रहा हूँ ");
        map.put("where  have I been meeting ", "मैं कहाँ मिल रहा हूँ ");
        map.put("where  have I been mistaking ", "मैं कहाँ गलत कर रहा हूँ ");
        map.put("where  have I been opening ", "मैं कहाँ खोल रहा हूँ ");
        map.put("where  have I been paying ", "मैं कहाँ भुगतान कर रहा हूँ ");
        map.put("where  have I been playing ", "मैं कहाँ खेल रहा हूँ ");
        map.put("where  have I been putting ", "मैं कहाँ रख रहा हूँ ");
        map.put("where  have I been quarrelling ", "मैं झगड़ा कहाँ कर रहा हूँ ");
        map.put("where  have I been raining ", "मैं बारिश कहाँ कर रहा हूँ ");
        map.put("where  have I been reaching ", "मैं कहाँ पहुँच रहा हूँ ");
        map.put("where  have I been reading ", "मैं कहाँ पढ़ रहा हूँ ");
        map.put("where  have I been remembering ", "मुझे कहाँ याद आ रहा है ");
        map.put("where  have I been riding ", "मैं कहाँ सवारी कर रहा हूँ ");
        map.put("where  have I been ringing ", "मैं कहाँ बज रहा हूँ ");
        map.put("where  have I been rising ", "मैं कहाँ उठ रहा हूँ ");
        map.put("where  have I been running ", "मैं कहाँ चल रहा हूँ ");
        map.put("where  have I been saying ", "मैं कहाँ कह रहा हूँ ");
        map.put("where  have I been seeing ", "मैं कहाँ देख रहा हूँ ");
        map.put("where  have I been selling ", "मैं कहाँ बेच रहा हूँ ");
        map.put("where  have I been sending ", "मैं कहाँ भेज रहा हूँ ");
        map.put("where  have I been shaking ", "मैं कहाँ हिल रहा हूँ ");
        map.put("where  have I been shining ", "मैं कहाँ चमक रहा हूँ ");
        map.put("where  have I been shooting ", "मैं कहाँ शूटिंग कर रहा हूँ ");
        map.put("where  have I been showing ", "मैं कहाँ दिखा रहा हूँ ");
        map.put("where  have I been shutting ", "मैं कहाँ बंद कर रहा हूँ ");
        map.put("where  have I been singing ", "मैं कहाँ गा रहा हूँ ");
        map.put("where  have I been sinking ", "मैं कहाँ डूब रहा हूँ ");
        map.put("where  have I been starting ", "मैं कहाँ से शुरू कर रहा हूँ ");
        map.put("where  have I been talking ", "मैं कहाँ बात कर रहा हूँ ");

        return map;
    }
    static Map<String,String> Five(){
        HashMap<String,String>map = new HashMap<>();
        map.put("where  did I  abuse ", "मैंने गाली कहाँ दी ");
        map.put("where  did I  advise", "मैंने कहाँ सलाह दी");
        map.put("where  did I  answer ", "मैंने कहाँ जवाब दिया ");
        map.put("where  did I  arise ", "मैं कहाँ उठ गया ");
        map.put("where  did I  arrive ", "मैं कहाँ पहुँचा ");
        map.put("where  did I  ask ", "मैंने कहाँ पूछा ");
        map.put("where  did I  awake ", "मैं कहाँ जाग गया ");

        map.put("where  did I  beat ", "मैंने कहाँ हराया ");
        map.put("where  did I  become ", "मैं कहाँ बन गया ");
        map.put("where  did I  beg ", "मैं कहाँ भीख माँगती हूँ ");
        map.put("where  did I  begin ", "मैंने कहाँ से शुरू किया ");
        map.put("where  did I  bind ", "मैंने कहाँ बाँध किया ");
        map.put("where  did I  bite", "मैंने कहाँ काटा");
        map.put("where  did I  bless", "मैंने कहाँ आशीर्वाद दिया");
        map.put("where  did I  blow ", "मैंने कहाँ उड़ा दिया ");
        map.put("where  did I  break ", "मैंने कहाँ तोड़ा था ");
        map.put("where  did I  bring ", "मैं कहाँ लाया था ");
        map.put("where  did I  build ", "मैंने कहाँ बनाया था ");
        map.put("where  did I  burn ", "मैंने कहाँ जलाया ");
        map.put("where  did I  buy ", "मैंने कहाँ खरीदा था ");
        map.put("where  did I  call ", "मैंने कहां फोन किया ");
        map.put("where  did I  carry ", "मैं कहाँ ले गया ");
        map.put("where  did I  catch ", "मैंने कहाँ पकड़ा ");
        map.put("where  did I  cheat ", "मैंने कहाँ धोखा दिया ");
        map.put("where  did I  choose ", "मैंने कहाँ चुना ");
        map.put("where  did I  clean ", "मैंने कहाँ साफ किया ");
        map.put("where  did I  climb  ", "मैं कहाँ चढ़ गया  ");
        map.put("where  did I  close ", "मैंने कहाँ बंद किया ");
        map.put("where  did I  come ", "मैं कहाँ आया ");
        map.put("where  did I  cook ", "मैंने कहाँ खाना बनाया ");
        map.put("where  did I  creep ", "मैं कहाँ रेंगना था ");
        map.put("where  did I  cut ", "मैंने कहाँ काटा था ");
        map.put("where  did I  dance ", "मैंने कहाँ नृत्य किया ");
        map.put("where  did I  deal ", "मैंने कहाँ सौदा किया ");
        map.put("where  did I  die ", "मैं कहाँ मर गया ");
        map.put("where  did I  dig ", "मैंने कहाँ खोदा था ");
        map.put("where  did I  draw ", "मैंने कहाँ आकर्षित किया ");
        map.put("where  did I  drive ", "मैंने कहाँ ड्राइव किया ");
        map.put("where  did I  drop ", "मैंने कहाँ गिराया ");
        map.put("where  did I  dry ", "मैंने कहाँ सुखाया ");
        map.put("where  did I  eat ", "मैंने कहाँ खाया ");
        map.put("where  did I  elect", "मैंने कहाँ का चुनाव किया");
        map.put("where  did I  enter ", "मैंने कहाँ प्रवेश किया ");
        map.put("where  did I  fall ", "मैं कहाँ गिर गया ");
        map.put("where  did I  feed ", "मैंने कहाँ खाना खाया ");
        map.put("where  did I  feel  ", "मैंने कहाँ महसूस किया  ");
        map.put("where  did I  fight ", "मैंने कहाँ लड़ाई की ");
        map.put("where  did I  find ", "मुझे कहाँ मिला ");
        map.put("where  did I  flee ", "मैं कहाँ भाग गया ");
        map.put("where  did I  fly  ", "मैं कहाँ उड़ गया  ");
        map.put("where  did I  fry ", "मैंने कहाँ भून किया ");
        map.put("where  did I  get  ", "मुझे कहाँ मिला  ");
        map.put("where  did I  give ", "मैंने कहाँ दिया ");
        map.put("where  did I  go ", "मैं कहाँ गया ");
        map.put("where  did I  grow", "मैं कहाँ उगता था");
        map.put("where  did I  hang ", "मैंने कहाँ लटका दिया ");
        map.put("where  did I  hear ", "मैंने कहाँ सुना ");
        map.put("where  did I  help ", "मैंने कहाँ मदद की ");
        map.put("where  did I  hide ", "मैंने कहाँ छिपाया था ");
        map.put("where  did I  hit ", "मैंने कहाँ मारा ");
        map.put("where  did I  hold ", "मैंने कहाँ पकड़ रखा था ");
        map.put("where  did I  hope ", "मुझे उम्मीद कहाँ थी ");
        map.put("where  did I  hurt ", "मैंने कहाँ चोट पहुंचाई ");
        map.put("where  did I  jump ", "मैं कहाँ कूद गया ");
        map.put("where  did I  keep ", "मैंने कहाँ रखा था ");
        map.put("where  did I  kill ", "मैंने कहाँ मार डाला ");
        map.put("where  did I  know ", "मुझे कहाँ पता था ");
        map.put("where  did I  laugh ", "मैं कहाँ हँसा था ");
        map.put("where  did I  lead ", "मैंने कहाँ नेतृत्व किया ");
        map.put("where  did I  leap ", "मैंने कहाँ छलांग लगाई ");
        map.put("where  did I  learn ", "मैंने कहाँ सीखा ");
        map.put("where  did I  leave ", "मैंने कहाँ छोड़ा ");
        map.put("where  did I  live ", "मैं कहाँ रहता था ");
        map.put("where  did I  look ", "मैंने कहाँ देखा ");
        map.put("where  did I  lose ", "मैं कहाँ हारा ");
        map.put("where  did I  love ", "मुझे कहाँ प्यार था ");
        map.put("where  did I  make ", "मैंने कहाँ बनाया ");
        map.put("where  did I  marry ", "मैंने शादी कहाँ की ");
        map.put("where  did I  meet ", "मैं कहाँ मिला ");
        map.put("where  did I  mistake ", "मैंने कहाँ गलती की ");
        map.put("where  did I  open ", "मैंने कहाँ खोला ");
        map.put("where  did I  pay  ", "मैंने कहाँ भुगतान किया  ");
        map.put("where  did I  play ", "मैंने कहाँ खेला ");
        map.put("where  did I  put ", "मैंने कहाँ रखा ");
        map.put("where  did I  quarrel ", "मैंने झगड़ा कहाँ किया ");
        map.put("where  did I  rain ", "मैंने बारिश कहाँ की ");
        map.put("where  did I  reach ", "मैं कहाँ पहुँचा ");
        map.put("where  did I  read", "मैंने कहाँ पढ़ा");
        map.put("where  did I  remember  ", "मुझे कहाँ याद आया  ");
        map.put("where  did I  ride ", "मैंने कहाँ सवारी की ");
        map.put("where  did I  ring ", "मैंने कहाँ रिंग किया ");
        map.put("where  did I  rise  ", "मैं कहाँ उठ गया  ");
        map.put("where  did I  say ", "मैंने कहाँ कहा ");
        map.put("where  did I  see ", "मैंने कहाँ देखा ");
        map.put("where  did I  sell ", "मैंने कहाँ बेचा ");
        map.put("where  did I  send ", "मैंने कहाँ भेजा ");
        map.put("where  did I  shake ", "मैंने कहाँ हिला दिया ");
        map.put("where  did I  shine ", "मैं कहाँ चमक गया ");
        map.put("where  did I  shoot ", "मैंने कहाँ शूट किया ");
        map.put("where  did I  show ", "मैंने कहाँ दिखाया ");
        map.put("where  did I  shut  ", "मैंने कहाँ बंद किया  ");
        map.put("where  did I  sing ", "मैंने कहाँ गाया था ");
        map.put("where  did I  sink ", "मैं कहाँ डूब गया ");
        map.put("where  did I  teach ", "मैंने कहाँ पढ़ाया ");
        map.put("where  did I  throw ", "मैंने कहाँ फेंका ");
        map.put("where  did I  want ", "मैं कहाँ चाहता था ");

        return map;
    }
    static Map<String,String> Six(){
        HashMap<String,String>map = new HashMap<>();
        map.put("where  was I  abusing ", "मैं कहाँ गाली दे रहा था ");
        map.put("where  was I  advising ", "मैं कहाँ सलाह दे रहा था ");
        map.put("where  was I  answering ", "मैं कहाँ जवाब दे रहा था ");
        map.put("where  was I  arising ", "मैं कहाँ उठ रहा था ");
        map.put("where  was I  arriving ", "मैं कहाँ आ रहा था ");
        map.put("where  was I  asking ", "मैं कहाँ पूछ रहा था ");
        map.put("where  was I  awaking ", "मैं कहाँ जाग रहा था ");
        map.put("where  was I  undefined", "मैं अपरिभाषित कहाँ था");
        map.put("where  was I  bearing ", "मैं कहाँ असर कर रहा था ");
        map.put("where  was I  beating ", "मैं कहाँ पिटाई कर रहा था ");
        map.put("where  was I  becoming ", "मैं कहाँ बन रहा था ");
        map.put("where  was I  begging ", "मैं कहाँ भीख माँग रहा था ");
        map.put("where  was I  beginning ", "मैं कहाँ से शुरू कर रहा था ");
        map.put("where  was I  binding ", "मैं कहाँ बाध्यकारी था ");
        map.put("where  was I  biting ", "मैं कहाँ काट रहा था ");
        map.put("where  was I  blessing ", "मैं कहाँ आशीष रहा था ");
        map.put("where  was I  blowing ", "मैं कहाँ उड़ रहा था ");
        map.put("where  was I  breaking ", "मैं कहाँ तोड़ रहा था ");
        map.put("where  was I  bringing ", "मैं कहाँ ला रहा था ");
        map.put("where  was I  building ", "मैं कहाँ बना रहा था ");
        map.put("where  was I  burning ", "मैं कहाँ जल रहा था ");
        map.put("where  was I  buying ", "मैं कहाँ खरीद रहा था ");
        map.put("where  was I  calling ", "मैं कहाँ बुला रहा था ");
        map.put("where  was I  carrying ", "मैं कहाँ ले जा रहा था ");
        map.put("where  was I  catching ", "मैं कहाँ पकड़ रहा था ");
        map.put("where  was I  cheating ", "मैं कहाँ धोखा दे रहा था ");
        map.put("where  was I  choosing ", "मैं कहाँ चुन रहा था ");
        map.put("where  was I  cleaning ", "मैं कहाँ सफाई कर रहा था ");
        map.put("where  was I  climbing ", "मैं कहाँ चढ़ रहा था ");
        map.put("where  was I  closing ", "मैं कहाँ बंद कर रहा था ");
        map.put("where  was I  coming ", "मैं कहाँ आ रहा था ");
        map.put("where  was I  cooking ", "मैं कहाँ खाना बना रहा था ");
        map.put("where  was I  creeping ", "मैं कहाँ रेंग रहा था ");
        map.put("where  was I  crying ", "मैं कहाँ रो रहा था ");
        map.put("where  was I  cutting ", "मैं कहाँ काट रहा था ");
        map.put("where  was I  dancing ", "मैं कहाँ नाच रहा था ");
        map.put("where  was I  dealing ", "मैं कहाँ काम कर रहा था ");
        map.put("where  was I  dying ", "मैं कहाँ मर रहा था ");
        map.put("where  was I  digging ", "मैं कहाँ खोद रहा था ");
        map.put("where  was I  drawing ", "मैं कहाँ चित्रित कर रहा था ");
        map.put("where  was I  drinking ", "मैं कहाँ पी रहा था ");
        map.put("where  was I  driving ", "मैं कहाँ चला रहा था ");
        map.put("where  was I  dropping ", "मैं कहाँ गिर रहा था ");
        map.put("where  was I  drying ", "मैं कहाँ सूख रहा था ");
        map.put("where  was I  eating ", "मैं कहाँ खा रहा था ");
        map.put("where  was I  electing ", "मैं कहाँ चुनाव कर रहा था ");
        map.put("where  was I  entering ", "मैं कहाँ प्रवेश कर रहा था ");
        map.put("where  was I  falling ", "मैं कहाँ गिर रहा था ");
        map.put("where  was I  feeding ", "मैं कहाँ खिला रहा था ");
        map.put("where  was I  feeling ", "मैं कहाँ महसूस कर रहा था ");
        map.put("where  was I  fighting ", "मैं कहाँ लड़ रहा था ");
        map.put("where  was I  finding ", "मैं कहाँ ढूँढ रहा था ");
        map.put("where  was I  fleeing ", "मैं कहाँ भाग रहा था ");
        map.put("where  was I  flying ", "मैं कहाँ उड़ रहा था ");
        map.put("where  was I  forgetting ", "मैं कहाँ भूल रहा था ");
        map.put("where  was I  frying ", "मैं कहाँ फ्राइंग कर रहा था ");
        map.put("where  was I  getting ", "मुझे कहाँ मिल रहा था ");
        map.put("where  was I  giving ", "मैं कहाँ दे रहा था ");
        map.put("where  was I  going ", "मैं कहाँ जा रहा था ");
        map.put("where  was I  growing ", "मैं कहाँ बढ़ रहा था ");
        map.put("where  was I  hanging ", "मैं कहाँ लटक रहा था ");
        map.put("where  was I  hearing ", "मैं कहाँ सुन रहा था ");
        map.put("where  was I  helping ", "मैं कहाँ मदद कर रहा था ");
        map.put("where  was I  hiding ", "मैं कहाँ छिपा रहा था ");
        map.put("where  was I  hitting ", "मैं कहाँ मार रहा था ");
        map.put("where  was I  holding ", "मैं कहाँ पकड़ रहा था ");
        map.put("where  was I  hoping ", "मैं कहाँ उम्मीद कर रहा था ");
        map.put("where  was I  hurting ", "मैं कहाँ चोट पहुँचा रहा था ");
        map.put("where  was I  jumping ", "मैं कहाँ कूद रहा था ");
        map.put("where  was I  keeping ", "मैं कहाँ रख रहा था ");
        map.put("where  was I  killing ", "मैं कहाँ मार रहा था ");
        map.put("where  was I  knowing ", "मैं कहाँ जान रहा था ");
        map.put("where  was I  laughing ", "मैं कहाँ हँस रहा था ");
        map.put("where  was I  leading ", "मैं कहाँ जा रहा था ");
        map.put("where  was I  leaping ", "मैं कहाँ छलांग लगा रहा था ");
        map.put("where  was I  learning ", "मैं कहाँ सीख रहा था ");
        map.put("where  was I  leaving ", "मैं कहाँ जा रहा था ");
        map.put("where  was I  lending ", "मैं कहाँ उधार दे रहा था ");
        map.put("where  was I  living ", "मैं कहाँ रह रहा था ");
        map.put("where  was I  looking ", "मैं कहाँ देख रहा था ");
        map.put("where  was I  losing ", "मैं कहाँ हार रहा था ");
        map.put("where  was I  loving ", "मैं कहाँ प्यार कर रहा था ");
        map.put("where  was I  making ", "मैं कहाँ बना रहा था ");
        map.put("where  was I  marrying ", "मैं कहाँ शादी कर रहा था ");
        map.put("where  was I  meeting ", "मैं कहाँ मिल रहा था ");
        map.put("where  was I  mistaking ", "मैं कहाँ गलत कर रहा था ");
        map.put("where  was I  opening ", "मैं कहाँ खोल रहा था ");
        map.put("where  was I  paying ", "मैं कहाँ भुगतान कर रहा था ");
        map.put("where  was I  playing ", "मैं कहाँ खेल रहा था ");
        map.put("where  was I  putting ", "मैं कहाँ रख रहा था ");
        map.put("where  was I  quarrelling ", "मैं झगड़ा कहाँ कर रहा था ");
        map.put("where  was I  raining ", "मैं कहाँ बारिश कर रहा था ");
        map.put("where  was I  reaching ", "मैं कहाँ पहुँच रहा था ");
        map.put("where  was I  reading ", "मैं कहाँ पढ़ रहा था ");
        map.put("where  was I  remembering ", "मैं कहाँ याद कर रहा था ");
        map.put("where  was I  riding ", "मैं कहाँ सवारी कर रहा था ");
        map.put("where  was I  ringing ", "मैं कहाँ बज रहा था ");
        map.put("where  was I  rising ", "मैं कहाँ उठ रहा था ");
        map.put("where  was I  running ", "मैं कहाँ चल रहा था ");
        map.put("where  was I  saying ", "मैं कहाँ कह रहा था ");
        map.put("where  was I  seeing ", "मैं कहाँ देख रहा था ");
        map.put("where  was I  selling ", "मैं कहाँ बेच रहा था ");
        map.put("where  was I  sending ", "मैं कहाँ भेज रहा था ");
        map.put("where  was I  shaking ", "मैं कहाँ हिल रहा था ");
        map.put("where  was I  shining ", "मैं कहाँ चमक रहा था ");
        map.put("where  was I  shooting ", "मैं कहाँ शूटिंग कर रहा था ");
        map.put("where  was I  showing ", "मैं कहाँ दिखा रहा था ");
        map.put("where  was I  shutting ", "मैं कहाँ बंद कर रहा था ");
        map.put("where  was I  singing ", "मैं कहाँ गा रहा था ");
        map.put("where  was I  sinking ", "मैं कहाँ डूब रहा था ");
        map.put("where  was I  smelling ", "मैं कहाँ सूँघ रहा था ");
        map.put("where  was I  writing ", "मैं कहाँ लिख रहा था ");

        return map;
    }
    static Map<String,String> Seven(){
        HashMap<String,String>map = new HashMap<>();
        map.put("where  had I  abused ", "मैंने कहाँ गाली दी थी ");
        map.put("where  had I  advised ", "मैंने कहाँ सलाह दी थी ");
        map.put("where  had I  answered ", "मैंने कहाँ उत्तर दिया था ");
        map.put("where  had I  arisen ", "मैं कहाँ पैदा हुआ था ");
        map.put("where  had I  arrived ", "मैं कहाँ पहुँचा था ");
        map.put("where  had I  asked ", "मैंने कहाँ पूछा था ");
        map.put("where  had I  awoken ", "मैं कहाँ जाग गया था ");
        map.put("where  had I  undefined", "मैंने अपरिभाषित कहाँ किया था");
        map.put("where  had I  borne ", "मैंने कहाँ पैदा किया था ");
        map.put("where  had I  beaten ", "मैंने कहाँ पीटा था ");
        map.put("where  had I  become ", "मैं कहाँ बन गया था ");
        map.put("where  had I  begged ", "मैंने कहाँ भीख माँगी थी ");
        map.put("where  had I  begun ", "मैंने कहाँ से शुरू किया था ");
        map.put("where  had I  bound ", "मैंने कहाँ बाध्य किया था ");
        map.put("where  had I  bitten ", "मैंने कहाँ काटा था ");
        map.put("where  had I  blessed ", "मैंने कहाँ आशीर्वाद दिया था ");
        map.put("where  had I  blown ", "मैंने कहाँ उड़ा दिया था ");
        map.put("where  had I  broken ", "मैं कहाँ टूट गया था ");
        map.put("where  had I  brought ", "मैं कहाँ लाया था ");
        map.put("where  had I  built ", "मैंने कहाँ बनाया था ");
        map.put("where  had I  burnt ", "मैंने कहाँ जलाया था ");
        map.put("where  had I  bought ", "मैंने कहाँ खरीदा था ");
        map.put("where  had I  called ", "मैंने कहाँ बुलाया था ");
        map.put("where  had I  carried ", "मैं कहाँ ले गया था ");
        map.put("where  had I  caught ", "मैंने कहाँ पकड़ा था ");
        map.put("where  had I  cheated ", "मैंने कहाँ धोखा दिया था ");
        map.put("where  had I  chosen ", "मैंने कहाँ चुना था ");
        map.put("where  had I  cleaned ", "मैंने कहाँ साफ किया था ");
        map.put("where  had I  climbed ", "मैं कहाँ चढ़ गया था ");
        map.put("where  had I  closed ", "मैंने कहाँ बंद किया था ");
        map.put("where  had I  come ", "मैं कहाँ आया था ");
        map.put("where  had I  cooked ", "मैंने कहाँ पकाया था ");
        map.put("where  had I  crept ", "मैंने कहाँ क्रेप किया था ");
        map.put("where  had I  cried ", "मैं कहाँ रोया था ");
        map.put("where  had I  cut ", "मैंने कहाँ काटा था ");
        map.put("where  had I  danced ", "मैंने कहाँ नृत्य किया था ");
        map.put("where  had I  dealt ", "मैंने कहाँ से निपटा था ");
        map.put("where  had I  died ", "मैं कहाँ मर गया था ");
        map.put("where  had I  dug ", "मैंने कहाँ खोदा था ");
        map.put("where  had I  drawn ", "मैंने कहाँ खींचा था ");
        map.put("where  had I  drunk ", "मैंने कहाँ पिया था ");
        map.put("where  had I  driven ", "मैंने कहाँ चलाया था ");
        map.put("where  had I  dropped ", "मैं कहाँ गिरा था ");
        map.put("where  had I  dried ", "मैं कहाँ सूख गया था ");
        map.put("where  had I  eaten ", "मैंने कहाँ खाया था ");
        map.put("where  had I  elected ", "मैंने कहाँ चुना था ");
        map.put("where  had I  entered ", "मैंने कहाँ प्रवेश किया था ");
        map.put("where  had I  fallen ", "मैं कहाँ गिर गया था ");
        map.put("where  had I  fed ", "मैंने कहाँ खिलाया था ");
        map.put("where  had I  felt ", "मैंने कहाँ महसूस किया था ");
        map.put("where  had I  fought ", "मैंने कहाँ लड़ा था ");
        map.put("where  had I  found ", "मुझे कहाँ मिला था ");
        map.put("where  had I  fled ", "मैं कहाँ भाग गया था ");
        map.put("where  had I  flown ", "मैं कहाँ से उड़ गया था ");
        map.put("where  had I  forgotten ", "मैं कहाँ भूल गया था ");
        map.put("where  had I  fried ", "मैंने कहाँ तला था ");
        map.put("where  had I  got ", "मुझे कहाँ मिला था ");
        map.put("where  had I  given ", "मैंने कहाँ दिया था ");
        map.put("where  had I  gone ", "मैं कहाँ गया था ");
        map.put("where  had I  grown ", "मैं कहाँ उगाया था ");
        map.put("where  had I  hanged ", "मैंने कहाँ फांसी दी थी ");
        map.put("where  had I  hung ", "मैंने कहाँ लटका दिया था ");
        map.put("where  had I  heard ", "मैंने कहाँ सुना था ");
        map.put("where  had I  helped ", "मैंने कहाँ मदद की थी ");
        map.put("where  had I  hidden ", "मैंने कहाँ छिपाया था ");
        map.put("where  had I  hit ", "मैंने कहाँ मारा था ");
        map.put("where  had I  held ", "मैंने कहाँ आयोजित किया था ");
        map.put("where  had I  hoped ", "मुझे कहाँ उम्मीद थी ");
        map.put("where  had I  hurt ", "मुझे कहाँ चोट लगी थी ");
        map.put("where  had I  jumped ", "मैं कहाँ कूद गया था ");
        map.put("where  had I  kept ", "मैंने कहाँ रखा था ");
        map.put("where  had I  killed ", "मैंने कहाँ मारा था ");
        map.put("where  had I  known ", "मुझे कहाँ पता था ");
        map.put("where  had I  laughed ", "मैं कहाँ हँसा था ");
        map.put("where  had I  led ", "मैंने कहाँ नेतृत्व किया था ");
        map.put("where  had I  leapt ", "मैंने कहाँ छलांग लगाई थी ");
        map.put("where  had I  learnt ", "मैंने कहाँ सीखा था ");
        map.put("where  had I  left ", "मैंने कहाँ छोड़ा था ");
        map.put("where  had I  lent ", "मैंने कहाँ उधार दिया था ");
        map.put("where  had I  lived ", "मैं कहाँ रहता था ");
        map.put("where  had I  looked ", "मैंने कहाँ देखा था ");
        map.put("where  had I  lost ", "मैं कहाँ खो गया था ");
        map.put("where  had I  loved ", "मैं कहाँ प्यार करता था ");
        map.put("where  had I  made ", "मैंने कहाँ बनाया था ");
        map.put("where  had I  married ", "मैंने शादी कहाँ की थी ");
        map.put("where  had I  met ", "मैं कहाँ मिला था ");
        map.put("where  had I  mistaken ", "मैंने कहाँ गलत किया था ");
        map.put("where  had I  opened ", "मैंने कहाँ खोला था ");
        map.put("where  had I  paid ", "मैंने कहाँ भुगतान किया था ");
        map.put("where  had I  played ", "मैंने कहाँ खेला था ");
        map.put("where  had I  put ", "मैंने कहाँ रखा था ");
        map.put("where  had I  quarrelled ", "मैंने कहाँ झगड़ा किया था ");
        map.put("where  had I  rained ", "मैंने कहाँ बारिश की थी ");
        map.put("where  had I  reached ", "मैं कहाँ पहुँचा था ");
        map.put("where  had I  read ", "मैंने कहाँ पढ़ा था ");
        map.put("where  had I  remembered ", "मुझे कहाँ याद आया था ");
        map.put("where  had I  ridden ", "मैंने कहाँ सवारी की थी ");
        map.put("where  had I  rung ", "मैंने कहाँ बजाया था ");
        map.put("where  had I  risen ", "मैं कहाँ उठ गया था ");
        map.put("where  had I  run ", "मैं कहाँ चला था ");
        map.put("where  had I  said ", "मैंने कहाँ कहा था ");
        map.put("where  had I  seen ", "मैंने कहाँ देखा था ");
        map.put("where  had I  sold ", "मैंने कहाँ बेचा था ");
        map.put("where  had I  sent ", "मैंने कहाँ भेजा था ");
        map.put("where  had I  shaken ", "मैं कहाँ हिल गया था ");
        map.put("where  had I  shone ", "मैं कहाँ चमक गया था ");
        map.put("where  had I  shot ", "मैंने कहाँ गोली मारी थी ");
        map.put("where  had I  shown ", "मैंने कहाँ दिखाया था ");
        map.put("where  had I  shut ", "मैंने कहाँ बंद किया था ");
        map.put("where  had I  sung ", "मैंने कहाँ गाया था ");
        map.put("where  had I  sunk ", "मैं कहाँ डूब गया था ");
        map.put("where  had I  stayed ", "मैं कहाँ रुका था ");
        map.put("where  had I  wanted ", "मैं कहाँ चाहता था ");

        return map;
    }
    static Map<String,String> Eight(){
        HashMap<String,String>map = new HashMap<>();
        map.put("where  had I been  abusing ", "मैं कहाँ गाली दे रहा था ");
        map.put("where  had I been  advising ", "मैं कहाँ सलाह दे रहा था ");
        map.put("where  had I been  answering ", "मैं कहाँ जवाब दे रहा था ");
        map.put("where  had I been  arising ", "मैं कहाँ उठ रहा था ");
        map.put("where  had I been  arriving ", "मैं कहाँ आ रहा था ");
        map.put("where  had I been  asking ", "मैं कहाँ पूछ रहा था ");
        map.put("where  had I been  awaking ", "मैं कहाँ जाग रहा था ");
        map.put("where  had I been  undefined", "मुझे अपरिभाषित कहाँ किया गया था");
        map.put("where  had I been  bearing ", "मैं कहाँ असर कर रहा था ");
        map.put("where  had I been  beating ", "मैं कहाँ पिटाई कर रहा था ");
        map.put("where  had I been  becoming ", "मैं कहाँ बन रहा था ");
        map.put("where  had I been  begging ", "मैं कहाँ भीख माँग रहा था ");
        map.put("where  had I been  beginning ", "मैं कहाँ से शुरू कर रहा था ");
        map.put("where  had I been  binding ", "मैं कहाँ बाध्यकारी था ");
        map.put("where  had I been  biting ", "मैं कहाँ काट रहा था ");
        map.put("where  had I been  blessing ", "मैं कहाँ आशीष रहा था ");
        map.put("where  had I been  blowing ", "मैं कहाँ उड़ रहा था ");
        map.put("where  had I been  breaking ", "मैं कहाँ तोड़ रहा था ");
        map.put("where  had I been  bringing ", "मैं कहाँ ला रहा था ");
        map.put("where  had I been  building ", "मैं कहाँ बना रहा था ");
        map.put("where  had I been  burning ", "मैं कहाँ जल रहा था ");
        map.put("where  had I been  buying ", "मैं कहाँ खरीद रहा था ");
        map.put("where  had I been  calling ", "मैं कहाँ बुला रहा था ");
        map.put("where  had I been  carrying ", "मैं कहाँ ले जा रहा था ");
        map.put("where  had I been  catching ", "मैं कहाँ पकड़ रहा था ");
        map.put("where  had I been  cheating ", "मैं कहाँ धोखा दे रहा था ");
        map.put("where  had I been  choosing ", "मैं कहाँ चुन रहा था ");
        map.put("where  had I been  cleaning ", "मैं कहाँ सफाई कर रहा था ");
        map.put("where  had I been  climbing ", "मैं कहाँ चढ़ रहा था ");
        map.put("where  had I been  closing ", "मैं कहाँ बंद कर रहा था ");
        map.put("where  had I been  coming ", "मैं कहाँ आ रहा था ");
        map.put("where  had I been  cooking ", "मैं कहाँ खाना बना रहा था ");
        map.put("where  had I been  creeping ", "मैं कहाँ रेंग रहा था ");
        map.put("where  had I been  crying ", "मैं कहाँ रो रहा था ");
        map.put("where  had I been  cutting ", "मैं कहाँ काट रहा था ");
        map.put("where  had I been  dancing ", "मैं कहाँ नाच रहा था ");
        map.put("where  had I been  dealing ", "मैं कहाँ काम कर रहा था ");
        map.put("where  had I been  dying ", "मैं कहाँ मर रहा था ");
        map.put("where  had I been  digging ", "मैं कहाँ खुदाई कर रहा था ");
        map.put("where  had I been  drawing ", "मैं कहाँ ड्राइंग कर रहा था ");
        map.put("where  had I been  drinking ", "मैं कहाँ पी रहा था ");
        map.put("where  had I been  driving ", "मैं कहाँ चला रहा था ");
        map.put("where  had I been  dropping ", "मैं कहाँ गिर रहा था ");
        map.put("where  had I been  drying ", "मैं कहाँ सूख रहा था ");
        map.put("where  had I been  eating ", "मैं कहाँ खा रहा था ");
        map.put("where  had I been  electing ", "मैं कहाँ चुनाव कर रहा था ");
        map.put("where  had I been  entering ", "मैं कहाँ प्रवेश कर रहा था ");
        map.put("where  had I been  falling ", "मैं कहाँ गिर रहा था ");
        map.put("where  had I been  feeding ", "मैं कहाँ खिला रहा था ");
        map.put("where  had I been  feeling ", "मैं कहाँ महसूस कर रहा था ");
        map.put("where  had I been  fighting ", "मैं कहाँ लड़ रहा था ");
        map.put("where  had I been  finding ", "मुझे कहाँ मिल रहा था ");
        map.put("where  had I been  fleeing ", "मैं कहाँ भाग रहा था ");
        map.put("where  had I been  flying ", "मैं कहाँ उड़ रहा था ");
        map.put("where  had I been  forgetting ", "मैं कहाँ भूल रहा था ");
        map.put("where  had I been  frying ", "मैं कहाँ तलने गया था ");
        map.put("where  had I been  getting ", "मुझे कहाँ मिल रहा था ");
        map.put("where  had I been  giving ", "मैं कहाँ दे रहा था ");
        map.put("where  had I been  going ", "मैं कहाँ जा रहा था ");
        map.put("where  had I been  growing ", "मैं कहाँ बढ़ रहा था ");
        map.put("where  had I been  hanging ", "मैं कहाँ लटक रहा था ");
        map.put("where  had I been  hearing ", "मैं कहाँ सुन रहा था ");
        map.put("where  had I been  helping ", "मैं कहाँ मदद कर रहा था ");
        map.put("where  had I been  hiding ", "मैं कहाँ छिपा रहा था ");
        map.put("where  had I been  hitting ", "मैं कहाँ मार रहा था ");
        map.put("where  had I been  holding ", "मैं कहाँ पकड़ रहा था ");
        map.put("where  had I been  hoping ", "मैं कहाँ उम्मीद कर रहा था ");
        map.put("where  had I been  hurting ", "मैं कहाँ चोट पहुँचा रहा था ");
        map.put("where  had I been  jumping ", "मैं कहाँ कूद रहा था ");
        map.put("where  had I been  keeping ", "मैं कहाँ रख रहा था ");
        map.put("where  had I been  killing ", "मैं कहाँ मार रहा था ");
        map.put("where  had I been  knowing ", "मैं कहाँ जान रहा था ");
        map.put("where  had I been  laughing ", "मैं कहाँ हँस रहा था ");
        map.put("where  had I been  leading ", "मैं कहाँ जा रहा था ");
        map.put("where  had I been  leaping ", "मैं कहाँ छलांग लगा रहा था ");
        map.put("where  had I been  learning ", "मैं कहाँ सीख रहा था ");
        map.put("where  had I been  leaving ", "मैं कहाँ जा रहा था ");
        map.put("where  had I been  lending ", "मैं कहाँ उधार दे रहा था ");
        map.put("where  had I been  living ", "मैं कहाँ रह रहा था ");
        map.put("where  had I been  looking ", "मैं कहाँ देख रहा था ");
        map.put("where  had I been  losing ", "मैं कहाँ हार रहा था ");
        map.put("where  had I been  loving ", "मैं कहाँ प्यार कर रहा था ");
        map.put("where  had I been  making ", "मैं कहाँ बना रहा था ");
        map.put("where  had I been  marrying ", "मैं शादी कहाँ कर रहा था ");
        map.put("where  had I been  meeting ", "मैं कहाँ मिल रहा था ");
        map.put("where  had I been  mistaking ", "मैं कहाँ गलत कर रहा था ");
        map.put("where  had I been  opening ", "मैं कहाँ खोल रहा था ");
        map.put("where  had I been  paying ", "मैं कहाँ भुगतान कर रहा था ");
        map.put("where  had I been  playing ", "मैं कहाँ खेल रहा था ");
        map.put("where  had I been  putting ", "मैं कहाँ रख रहा था ");
        map.put("where  had I been  quarrelling ", "मैं झगड़ा कहाँ कर रहा था ");
        map.put("where  had I been  raining ", "मैं बारिश कहाँ कर रहा था ");
        map.put("where  had I been  reaching ", "मैं कहाँ पहुँच रहा था ");
        map.put("where  had I been  reading ", "मैं कहाँ पढ़ रहा था ");
        map.put("where  had I been  remembering ", "मैं कहाँ याद कर रहा था ");
        map.put("where  had I been  riding ", "मैं कहाँ सवारी कर रहा था ");
        map.put("where  had I been  ringing ", "मैं कहाँ बज रहा था ");
        map.put("where  had I been  rising ", "मैं कहाँ उठ रहा था ");
        map.put("where  had I been  running ", "मैं कहाँ दौड़ रहा था ");
        map.put("where  had I been  saying ", "मैं कहाँ कह रहा था ");
        map.put("where  had I been  seeing ", "मैं कहाँ देख रहा था ");
        map.put("where  had I been  selling ", "मैं कहाँ बेच रहा था ");
        map.put("where  had I been  sending ", "मैं कहाँ भेज रहा था ");
        map.put("where  had I been  shaking ", "मैं कहाँ हिल रहा था ");
        map.put("where  had I been  shining ", "मैं कहाँ चमक रहा था ");
        map.put("where  had I been  shooting ", "मैं कहाँ शूटिंग कर रहा था ");
        map.put("where  had I been  showing ", "मैं कहाँ दिखा रहा था ");
        map.put("where  had I been  shutting ", "मैं कहाँ बंद कर रहा था ");
        map.put("where  had I been  singing ", "मैं कहाँ गा रहा था ");
        map.put("where  had I been  sinking ", "मैं कहाँ डूब रहा था ");
        map.put("where  had I been  starting ", "मैं कहाँ से शुरू कर रहा था ");

        return map;
    }
    static Map<String,String> Nine(){
        HashMap<String,String>map = new HashMap<>();
        map.put("where  will I abuse ", "मैं कहाँ गाली दूँगा ");
        map.put("where  will I advise", "मैं कहाँ सलाह दूँगा");
        map.put("where  will I answer ", "मैं कहां जवाब दूँगा ");
        map.put("where  will I arise ", "मैं कहाँ उठूँगा ");
        map.put("where  will I arrive ", "मैं कहाँ पहुँचूँगा ");
        map.put("where  will I ask ", "मैं कहाँ पूछूँगा ");
        map.put("where  will I awake ", "मैं कहाँ जाग जाऊंगा ");
        map.put("where  will I \r", "मैं कहाँ जाऊँगा \r");
        map.put("where  will I be undefined", "मैं अपरिभाषित कहाँ रहूँगा");
        map.put("where  will I bear ", "मैं कहाँ सहन करूँगा ");
        map.put("where  will I beat ", "मैं कहाँ हराऊंगा ");
        map.put("where  will I become ", "मैं कहाँ बनूँगा ");
        map.put("where  will I beg ", "मैं कहाँ भीख माँगता हूँ ");
        map.put("where  will I begin ", "मैं कहाँ से शुरू करूँगा ");
        map.put("where  will I bind ", "मैं कहाँ बाँध लूँगा ");
        map.put("where  will I bite", "मैं कहाँ काटूंगा");
        map.put("where  will I bless", "मैं कहाँ आशीष दूँगा");
        map.put("where  will I break ", "मैं कहाँ टूटूंगा ");
        map.put("where  will I bring ", "मैं कहाँ लाऊँगा ");
        map.put("where  will I build ", "मैं कहाँ बनाऊँगा ");
        map.put("where  will I burn ", "मैं कहाँ जलाऊंगा ");
        map.put("where  will I buy ", "मैं कहाँ खरीदूँगा ");
        map.put("where  will I call ", "मैं कहां कॉल करूँगा ");
        map.put("where  will I carry ", "मैं कहाँ ले जाऊंगा ");
        map.put("where  will I catch ", "मैं कहाँ पकड़ूँगा ");
        map.put("where  will I cheat ", "मैं कहाँ धोखा दूँगा ");
        map.put("where  will I choose ", "मैं कहाँ चुनूँगा ");
        map.put("where  will I clean ", "मैं कहाँ साफ करूँगा ");
        map.put("where  will I climb  ", "मैं कहाँ चढ़ूँगा  ");
        map.put("where  will I close ", "मैं कहाँ बंद करूँगा ");
        map.put("where  will I come ", "मैं कहाँ आऊँगा ");
        map.put("where  will I cook ", "मैं कहाँ पकाऊँगा ");
        map.put("where  will I creep ", "मैं कहाँ रेंगूँगा ");
        map.put("where  will I cry ", "मैं कहाँ रोऊंगा ");
        map.put("where  will I cut ", "मैं कहाँ काटूंगा ");
        map.put("where  will I dance ", "मैं कहाँ नृत्य करूँगा ");
        map.put("where  will I deal ", "मैं कहां से निपटूंगा ");
        map.put("where  will I die ", "मैं कहाँ मरूंगा ");
        map.put("where  will I dig ", "मैं कहाँ खोदूँगा ");
        map.put("where  will I draw ", "मैं कहाँ आकर्षित करूँगा ");
        map.put("where  will I drive ", "मैं कहाँ चलाऊँगा ");
        map.put("where  will I drop ", "मैं कहाँ छोड़ूँगा ");
        map.put("where  will I dry ", "मैं कहाँ सुखाऊँगा ");
        map.put("where  will I eat ", "मैं कहाँ खाऊँगा ");
        map.put("where  will I elect", "मैं कहाँ चुनाव करूँगा");
        map.put("where  will I enter ", "मैं कहाँ प्रवेश करूँगा ");
        map.put("where  will I fall ", "मैं कहाँ गिरूंगा ");
        map.put("where  will I feed ", "मैं कहाँ खिलाऊँगा ");
        map.put("where  will I feel  ", "मैं कहाँ महसूस करूँगा  ");
        map.put("where  will I fight ", "मैं कहाँ लड़ूँगा ");
        map.put("where  will I find ", "मुझे कहाँ मिलेगा ");
        map.put("where  will I flee ", "मैं कहाँ भागोगे ");
        map.put("where  will I fly  ", "मैं कहाँ उड़ूँगा  ");
        map.put("where  will I forget ", "मैं कहाँ भूल जाऊंगा ");
        map.put("where  will I fry ", "मैं कहाँ भूनूँगा ");
        map.put("where  will I get  ", "मुझे कहाँ मिलेगा  ");
        map.put("where  will I give ", "मैं कहाँ दूँगा ");
        map.put("where  will I go ", "मैं कहाँ जाऊँगा ");
        map.put("where  will I grow", "मैं कहाँ बढ़ूंगा");
        map.put("where  will I hang ", "मैं कहाँ लटकाऊंगा ");
        map.put("where  will I hear ", "मैं कहाँ सुनूँगा ");
        map.put("where  will I help ", "मैं कहाँ मदद करूँगा ");
        map.put("where  will I hide ", "मैं कहाँ छिपाऊंगा ");
        map.put("where  will I hit ", "मैं कहाँ मारूंगा ");
        map.put("where  will I hold ", "मैं कहाँ रखूँगा ");
        map.put("where  will I hope ", "मैं कहाँ आशा करूँगा ");
        map.put("where  will I hurt ", "मैं कहाँ चोट पहुँचाऊँगा ");
        map.put("where  will I jump ", "मैं कहाँ कूदूँगा ");
        map.put("where  will I keep ", "मैं कहाँ रखूँगा ");
        map.put("where  will I kill ", "मैं कहाँ मारूँगा ");
        map.put("where  will I know ", "मुझे कहाँ पता चलेगा ");
        map.put("where  will I laugh ", "मैं कहाँ हँसूँगा ");
        map.put("where  will I lead ", "मैं कहाँ नेतृत्व करूँगा ");
        map.put("where  will I leap ", "मैं कहाँ छलांग लगाऊंगा ");
        map.put("where  will I learn ", "मैं कहाँ सीखूंगा ");
        map.put("where  will I leave ", "मैं कहाँ छोड़ूँगा ");
        map.put("where  will I lend ", "मैं कहाँ उधार दूँगा ");
        map.put("where  will I live ", "मैं कहाँ रहूँगा ");
        map.put("where  will I look ", "मैं कहाँ देखूँगा ");
        map.put("where  will I lose ", "मैं कहाँ हारूंगा ");
        map.put("where  will I make ", "मैं कहाँ बनाऊँगा ");
        map.put("where  will I marry ", "मैं कहाँ शादी करूँगा ");
        map.put("where  will I meet ", "मैं कहाँ मिलूँगा ");
        map.put("where  will I mistake ", "मैं कहाँ गलती करूँगा ");
        map.put("where  will I open ", "मैं कहाँ खोलूँगा ");
        map.put("where  will I pay  ", "मैं कहाँ भुगतान करूँगा  ");
        map.put("where  will I play ", "मैं कहाँ खेलूँगा ");
        map.put("where  will I put ", "मैं कहाँ रखूँगा ");
        map.put("where  will I quarrel ", "मैं झगड़ा कहाँ करूँगा ");
        map.put("where  will I rain ", "मैं कहाँ बारिश करूँगा ");
        map.put("where  will I reach ", "मैं कहाँ पहुँचूँगा ");
        map.put("where  will I read", "मैं कहाँ पढ़ूँगा");
        map.put("where  will I remember  ", "मुझे कहाँ याद होगा  ");
        map.put("where  will I ride ", "मैं कहाँ सवारी करूँगा ");
        map.put("where  will I ring ", "मैं कहाँ रिंग करूँगा ");
        map.put("where  will I rise  ", "मैं कहाँ उठूँगा  ");
        map.put("where  will I run  ", "मैं कहाँ दौड़ूँगा  ");
        map.put("where  will I say ", "मैं कहाँ कहूँगा ");
        map.put("where  will I see ", "मैं कहाँ देखूँगा ");
        map.put("where  will I sell ", "मैं कहाँ बेचूँगा ");
        map.put("where  will I send ", "मैं कहाँ भेजूंगा ");
        map.put("where  will I shake ", "मैं कहाँ हिलाऊंगा ");
        map.put("where  will I shine ", "मैं कहाँ चमकूंगा ");
        map.put("where  will I shoot ", "मैं कहाँ शूट करूँगा ");
        map.put("where  will I shut  ", "मैं कहाँ बंद करूँगा  ");
        map.put("where  will I sing ", "मैं कहाँ गाऊंगा ");
        map.put("where  will I sink ", "मैं कहाँ डूब जाऊंगा ");
        map.put("where  will I smell ", "मैं कहाँ सूंघूँगा ");
        map.put("where  will I spend", "मैं कहाँ खर्च करूँगा");
        map.put("where  will I stay ", "मैं कहाँ रहूँगा ");
        map.put("where  will I be spoilt", "मैं कहाँ खराब हो जाऊंगा");
        map.put("where  will I tell ", "मैं कहाँ बताऊँगा ");
        map.put("where  will I win ", "मैं कहाँ जीतूंगा ");

        return map;
    }
    static Map<String,String> Ten(){
        HashMap<String,String>map = new HashMap<>();
        map.put("where  will I be abusing ", "मैं कहाँ गाली दे रहा हूँ ");
        map.put("where  will I be advising ", "मैं कहाँ सलाह दूँगा ");
        map.put("where  will I be answering ", "मैं कहाँ जवाब दूँगा ");
        map.put("where  will I be arising ", "मैं कहाँ उठूँगा ");
        map.put("where  will I be arriving ", "मैं कहाँ पहुँचूँगा ");
        map.put("where  will I be asking ", "मैं कहाँ पूछूँगा ");
        map.put("where  will I be awaking ", "मैं कहाँ जाग जाऊंगा ");
        map.put("where  will I be bearing ", "मैं कहां असर डालूंगा ");
        map.put("where  will I be beating ", "मैं कहाँ पिटाई करूँगा ");
        map.put("where  will I be becoming ", "मैं कहाँ बन जाऊंगा ");
        map.put("where  will I be begging ", "मैं कहाँ भीख माँगता हूँ ");
        map.put("where  will I be beginning ", "मैं कहाँ से शुरू करूँगा ");
        map.put("where  will I be binding ", "मैं बाध्यकारी कहाँ रहूँगा ");
        map.put("where  will I be blessing ", "मैं आशीष कहाँ रहूँगा ");
        map.put("where  will I be biting ", "मैं कहाँ काटूंगा ");
        map.put("where  will I be blowing ", "मैं कहाँ उड़ रहा हूँ ");
        map.put("where  will I be breaking ", "मैं कहाँ तोड़ूँगा ");
        map.put("where  will I be bringing ", "मैं कहाँ लाऊंगा ");
        map.put("where  will I be building ", "मैं कहाँ निर्माण करूँगा ");
        map.put("where  will I be burning ", "मैं कहाँ जल रहा हूँ ");
        map.put("where  will I be buying ", "मैं कहाँ खरीदूँगा ");
        map.put("where  will I be calling ", "मैं कहाँ कॉल करूँगा ");
        map.put("where  will I be carrying ", "मैं कहाँ ले जाऊंगा ");
        map.put("where  will I be catching ", "मैं कहाँ पकड़ रहा हूँ ");
        map.put("where  will I be cheating ", "मैं कहाँ धोखा दे रहा हूँ ");
        map.put("where  will I be choosing ", "मैं कहां चुनूंगा ");
        map.put("where  will I be cleaning ", "मैं कहाँ सफाई करूँगा ");
        map.put("where  will I be climbing ", "मैं कहाँ चढ़ जाऊंगा ");
        map.put("where  will I be closing ", "मैं कहाँ बंद करूँगा ");
        map.put("where  will I be coming ", "मैं कहाँ आऊँगा ");
        map.put("where  will I be cooking ", "मैं कहाँ खाना बनाऊँगा ");
        map.put("where  will I be creeping ", "मैं कहाँ रेंगना चाहूँगा ");
        map.put("where  will I be crying ", "मैं कहाँ रो रहा हूँ ");
        map.put("where  will I be cutting ", "मैं कहाँ काटूंगा ");
        map.put("where  will I be dancing ", "मैं कहाँ नाचता रहूँगा ");
        map.put("where  will I be dealing ", "मैं कहां से निपटूंगा ");
        map.put("where  will I be dying ", "मैं कहाँ मर जाऊंगा ");
        map.put("where  will I be digging ", "मैं कहाँ खोदूँगा ");
        map.put("where  will I be drawing ", "मैं कहाँ आरेखण करूँगा ");
        map.put("where  will I be drinking ", "मैं कहाँ पी रहा हूँ ");
        map.put("where  will I be driving ", "मैं कहाँ चला रहा हूँ ");
        map.put("where  will I be dropping ", "मैं कहाँ छोड़ूँगा ");
        map.put("where  will I be drying ", "मैं कहाँ सुखाऊंगा ");
        map.put("where  will I be eating ", "मैं कहाँ खाऊंगा ");
        map.put("where  will I be electing ", "मैं कहाँ चुनाव करूँगा ");
        map.put("where  will I be entering ", "मैं कहाँ प्रवेश करूँगा ");
        map.put("where  will I be falling ", "मैं कहाँ गिर रहा हूँ ");
        map.put("where  will I be feeding ", "मैं कहाँ खिलाऊंगा ");
        map.put("where  will I be feeling ", "मैं कहाँ महसूस कर रहा हूँ ");
        map.put("where  will I be fighting ", "मैं कहाँ लड़ूँगा ");
        map.put("where  will I be finding ", "मैं कहाँ खोजूँगा ");
        map.put("where  will I be fleeing ", "मैं कहाँ भाग जाऊंगा ");
        map.put("where  will I be flying ", "मैं कहाँ उड़ूँगा ");
        map.put("where  will I be forgetting ", "मैं कहाँ भूल जाऊंगा ");
        map.put("where  will I be frying ", "मैं कहाँ तलने जाऊंगा ");
        map.put("where  will I be getting ", "मुझे कहाँ मिल रहा होगा ");
        map.put("where  will I be giving ", "मैं कहाँ दे रहा हूँ ");
        map.put("where  will I be going ", "मैं कहाँ जाऊंगा ");
        map.put("where  will I be growing ", "मैं कहाँ बढ़ रहा हूँ ");
        map.put("where  will I be hanging ", "मैं कहाँ लटकाऊंगा ");
        map.put("where  will I be hearing ", "मैं कहाँ सुनूँगा ");
        map.put("where  will I be helping ", "मैं कहाँ मदद करूँगा ");
        map.put("where  will I be hiding ", "मैं कहाँ छिपाऊंगा ");
        map.put("where  will I be hitting ", "मैं कहाँ मार रहा हूँ ");
        map.put("where  will I be holding ", "मैं कहाँ पकड़े रहूँगा ");
        map.put("where  will I be hoping ", "मैं कहाँ उम्मीद कर रहा हूँ ");
        map.put("where  will I be hurting ", "मैं कहाँ चोट पहुँचाऊंगा ");
        map.put("where  will I be jumping ", "मैं कहाँ कूद जाऊंगा ");
        map.put("where  will I be keeping ", "मैं कहाँ रखूँगा ");
        map.put("where  will I be killing ", "मैं कहाँ मार रहा हूँ ");
        map.put("where  will I be knowing ", "मैं कहाँ जाऊँगा ");
        map.put("where  will I be laughing ", "मैं कहाँ हँस रहा हूँ ");
        map.put("where  will I be leading ", "मैं कहाँ अग्रणी रहूँगा ");
        map.put("where  will I be leaping ", "मैं कहाँ छलांग लगाऊंगा ");
        map.put("where  will I be learning ", "मैं कहाँ सीख रहा हूँ ");
        map.put("where  will I be leaving ", "मैं कहाँ जा रहा हूँ ");
        map.put("where  will I be lending ", "मैं कहाँ उधार दे रहा हूँ ");
        map.put("where  will I be living ", "मैं कहाँ रहूँगा ");
        map.put("where  will I be looking ", "मैं कहाँ देख रहा हूँ ");
        map.put("where  will I be losing ", "मैं कहाँ हारूंगा ");
        map.put("where  will I be loving ", "मैं कहाँ प्यार करूँगा ");
        map.put("where  will I be making ", "मैं कहाँ बना रहा हूँ ");
        map.put("where  will I be marrying ", "मैं शादी कहाँ करूँगा ");
        map.put("where  will I be meeting ", "मैं कहाँ मिलूँगा ");
        map.put("where  will I be mistaking ", "मैं कहाँ गलत हो जाऊंगा ");
        map.put("where  will I be opening ", "मैं कहाँ खोलूंगा ");
        map.put("where  will I be paying ", "मैं कहाँ भुगतान करूँगा ");
        map.put("where  will I be playing ", "मैं कहाँ खेलूँगा ");
        map.put("where  will I be putting ", "मैं कहाँ रखूँगा ");
        map.put("where  will I be quarrelling ", "मैं झगड़ा कहाँ करूँगा ");
        map.put("where  will I be raining ", "मेरी बारिश कहाँ होगी ");
        map.put("where  will I be reaching ", "मैं कहाँ पहुँचूँगा ");
        map.put("where  will I be reading ", "मैं कहाँ पढ़ूँगा ");
        map.put("where  will I be remembering ", "मैं कहाँ याद रखूँगा ");
        map.put("where  will I be riding ", "मैं कहाँ सवारी करूँगा ");
        map.put("where  will I be ringing ", "मैं कहाँ बज रहा हूँ ");
        map.put("where  will I be rising ", "मैं कहाँ उठ रहा हूँ ");
        map.put("where  will I be running ", "मैं कहाँ दौड़ूँगा ");
        map.put("where  will I be saying ", "मैं कहाँ कहूँगा ");
        map.put("where  will I be seeing ", "मैं कहाँ देख रहा हूँ ");
        map.put("where  will I be selling ", "मैं कहाँ बेचूंगा ");
        map.put("where  will I be sending ", "मैं कहाँ भेजूंगा ");
        map.put("where  will I be shaking ", "मैं कहाँ हिलाऊंगा ");
        map.put("where  will I be shining ", "मैं कहाँ चमक रहा हूँ ");
        map.put("where  will I be shooting ", "मैं कहाँ शूटिंग करूँगा ");
        map.put("where  will I be showing ", "मैं कहाँ दिखाऊंगा ");
        map.put("where  will I be shutting ", "मैं कहाँ बंद हो जाऊंगा ");
        map.put("where  will I be singing ", "मैं कहाँ गाऊंगा ");
        map.put("where  will I be sinking ", "मैं कहाँ डूब जाऊंगा ");
        map.put("where  will I be speaking ", "मैं कहाँ बोल रहा हूँ ");

        return map;
    }
    static Map<String,String> Eleven(){
        HashMap<String,String>map = new HashMap<>();
        map.put("where  will I have abused ", "मैं कहाँ गाली दूँगा ");
        map.put("where  will I have advised ", "मैंने कहाँ सलाह दी होगी ");
        map.put("where  will I have answered ", "मैंने कहां जवाब दिया होगा ");
        map.put("where  will I have arisen ", "मैं कहाँ उठ जाऊंगा ");
        map.put("where  will I have arrived ", "मैं कहाँ पहुँचूँगा ");
        map.put("where  will I have asked ", "मैंने कहाँ पूछा होगा ");
        map.put("where  will I have awoken ", "मैं कहाँ जाग जाऊंगा ");
        map.put("where  will I have undefined", "मैं अपरिभाषित कहां रहूंगा");
        map.put("where  will I have borne ", "मैं कहाँ पैदा करूँगा ");
        map.put("where  will I have beaten ", "मैंने कहाँ पीटा होगा ");
        map.put("where  will I have become ", "मैं कहाँ बन जाऊंगा ");
        map.put("where  will I have begged ", "मैं कहाँ भीख माँगता हूँ ");
        map.put("where  will I have begun ", "मैं कहाँ से शुरू करूँगा ");
        map.put("where  will I have bound ", "मैं कहाँ बाउंड करूँगा ");
        map.put("where  will I have blessed ", "मैं कहाँ आशीष पाऊँगा ");
        map.put("where  will I have bitten ", "मैंने कहाँ काट लिया होगा ");
        map.put("where  will I have blown ", "मैं कहाँ उड़ा जाऊंगा ");
        map.put("where  will I have broken ", "मैं कहाँ टूटूंगा ");
        map.put("where  will I have brought ", "मैं कहाँ लाऊँगा ");
        map.put("where  will I have built ", "मैंने कहाँ बनाया होगा ");
        map.put("where  will I have burnt ", "मैं कहाँ जला दूँगा ");
        map.put("where  will I have bought ", "मैंने कहाँ खरीदा होगा ");
        map.put("where  will I have called ", "मैंने कहां कॉल किया होगा ");
        map.put("where  will I have carried ", "मैं कहाँ ले जाऊंगा ");
        map.put("where  will I have caught ", "मैंने कहाँ पकड़ा होगा ");
        map.put("where  will I have cheated ", "मैंने धोखा कहाँ दिया होगा ");
        map.put("where  will I have chosen ", "मैंने कहाँ चुना होगा ");
        map.put("where  will I have cleaned ", "मैं कहाँ साफ करूँगा ");
        map.put("where  will I have climbed ", "मैं कहाँ चढ़ जाऊंगा ");
        map.put("where  will I have closed ", "मैं कहाँ बंद करूँगा ");
        map.put("where  will I have come ", "मैं कहाँ आऊँगा ");
        map.put("where  will I have cooked ", "मैं कहाँ पकाऊँगा ");
        map.put("where  will I have crept ", "मेरे पास crept कहाँ होगा ");
        map.put("where  will I have cried ", "मैं कहाँ रोया होगा ");
        map.put("where  will I have cut ", "मैं कहाँ कट जाऊंगा ");
        map.put("where  will I have danced ", "मैं कहाँ नृत्य करूँगा ");
        map.put("where  will I have dealt ", "मैं कहां से निपटा जाऊंगा ");
        map.put("where  will I have died ", "मैं कहाँ मर जाऊंगा ");
        map.put("where  will I have dug ", "मैंने कहाँ खोदा होगा ");
        map.put("where  will I have drawn ", "मैं कहाँ ड्रॉ करूँगा ");
        map.put("where  will I have drunk ", "मैं कहाँ नशे में हूँ ");
        map.put("where  will I have driven ", "मैं कहाँ चला जाऊंगा ");
        map.put("where  will I have dropped ", "मैं कहाँ गिराऊंगा ");
        map.put("where  will I have dried ", "मैं कहाँ सूख जाऊंगा ");
        map.put("where  will I have eaten ", "मैंने कहाँ खाया होगा ");
        map.put("where  will I have elected ", "मैं कहाँ चुनूँगा ");
        map.put("where  will I have entered ", "मैं कहाँ प्रवेश करूँगा ");
        map.put("where  will I have fallen ", "मैं कहाँ गिरूँगा ");
        map.put("where  will I have fed ", "मैंने कहाँ खिलाया होगा ");
        map.put("where  will I have felt ", "मैंने कहाँ महसूस किया होगा ");
        map.put("where  will I have fought ", "मैं कहाँ लड़ा होगा ");
        map.put("where  will I have found ", "मुझे कहाँ मिलेगा ");
        map.put("where  will I have fled ", "मैं कहाँ भाग जाऊँगा ");
        map.put("where  will I have flown ", "मैं कहाँ उड़ जाऊंगा ");
        map.put("where  will I have forgotten ", "मैं कहाँ भूल जाऊंगा ");
        map.put("where  will I have fried ", "मैं कहाँ फ्राई करूँगा ");
        map.put("where  will I have got ", "मुझे कहाँ मिल गया होगा ");
        map.put("where  will I have given ", "मैंने कहाँ दिया होगा ");
        map.put("where  will I have gone ", "मैं कहाँ जाऊँगा ");
        map.put("where  will I have grown ", "मैं कहाँ बड़ा हो जाऊंगा ");
        map.put("where  will I have hanged ", "मैं कहाँ फांसी लगाऊंगा ");
        map.put("where  will I have hung ", "मैंने कहाँ लटका दिया होगा ");
        map.put("where  will I have heard ", "मैंने कहाँ सुना होगा ");
        map.put("where  will I have helped ", "मैंने कहाँ मदद की होगी ");
        map.put("where  will I have hidden ", "मैं कहाँ छिपाऊंगा ");
        map.put("where  will I have hit ", "मैं कहाँ मारा जाऊँगा ");
        map.put("where  will I have held ", "मैं कहाँ आयोजित करूँगा ");
        map.put("where  will I have hoped ", "मुझे उम्मीद कहाँ होगी ");
        map.put("where  will I have hurt ", "मुझे कहाँ चोट लगी होगी ");
        map.put("where  will I have jumped ", "मैं कहाँ कूद जाऊंगा ");
        map.put("where  will I have kept ", "मैं कहाँ रखूँगा ");
        map.put("where  will I have killed ", "मैं कहाँ मार डालूँगा ");
        map.put("where  will I have known ", "मुझे कहाँ पता होगा ");
        map.put("where  will I have laughed ", "मैं कहाँ हँसा जाऊँगा ");
        map.put("where  will I have led ", "मैंने कहाँ नेतृत्व किया होगा ");
        map.put("where  will I have leapt ", "मैं कहाँ छलांग लगाऊंगा ");
        map.put("where  will I have learnt ", "मैंने कहाँ सीखा होगा ");
        map.put("where  will I have left ", "मैं कहाँ छोड़ूँगा ");
        map.put("where  will I have lent ", "मैं कहाँ उधार दूँगा ");
        map.put("where  will I have lived ", "मैं कहाँ रहूँगा ");
        map.put("where  will I have looked ", "मैंने कहाँ देखा होगा ");
        map.put("where  will I have lost ", "मैं कहाँ हार जाऊंगा ");
        map.put("where  will I have loved ", "मुझे कहां से प्यार होगा ");
        map.put("where  will I have made ", "मैंने कहाँ बनाया होगा ");
        map.put("where  will I have married ", "मैं शादी कहाँ करूँगा ");
        map.put("where  will I have met ", "मैं कहाँ मिलूँगा ");
        map.put("where  will I have mistaken ", "मेरी गलती कहाँ होगी ");
        map.put("where  will I have opened ", "मैं कहाँ खोलूँगा ");
        map.put("where  will I have paid ", "मैंने कहाँ भुगतान किया होगा ");
        map.put("where  will I have played ", "मैं कहाँ खेलूँगा ");
        map.put("where  will I have put ", "मैं कहाँ रखूँगा ");
        map.put("where  will I have quarrelled ", "मैं झगड़ा कहाँ करूँगा ");
        map.put("where  will I have rained ", "मेरी बारिश कहाँ होगी ");
        map.put("where  will I have reached ", "मैं कहाँ पहुँचूँगा ");
        map.put("where  will I have read ", "मैं कहाँ पढ़ूँगा ");
        map.put("where  will I have remembered ", "मुझे कहाँ याद होगा ");
        map.put("where  will I have ridden ", "मैं कहाँ सवार हो जाऊंगा ");
        map.put("where  will I have rung ", "मैं कहाँ रुँगा ");
        map.put("where  will I have risen ", "मैं कहाँ उठ जाऊंगा ");
        map.put("where  will I have run ", "मैं कहाँ दौड़ूँगा ");
        map.put("where  will I have said ", "मैंने कहाँ कहा होगा ");
        map.put("where  will I have seen ", "मैंने कहाँ देखा होगा ");
        map.put("where  will I have sold ", "मैं कहाँ बेचूँगा ");
        map.put("where  will I have sent ", "मैंने कहाँ भेजा होगा ");
        map.put("where  will I have shaken ", "मैं कहाँ हिल जाऊंगा ");
        map.put("where  will I have shone ", "मैं कहाँ चमक जाऊंगा ");
        map.put("where  will I have shot ", "मैंने कहाँ गोली चलाई होगी ");
        map.put("where  will I have shown ", "मैंने कहाँ दिखाया होगा ");
        map.put("where  will I have shut ", "मैं कहाँ बंद करूँगा ");
        map.put("where  will I have sung ", "मैंने कहाँ गाया होगा ");
        map.put("where  will I have sunk ", "मैं कहाँ डूब जाऊंगा ");
        map.put("where  will I have spent ", "मैंने कहाँ खर्च किया होगा ");

        return map;
    }
    static Map<String,String> Twelve(){
        HashMap<String,String>map = new HashMap<>();
        map.put("where  will I have been abusing ", "मैं कहाँ गाली दे रहा हूँ ");
        map.put("where  will I have been advising ", "मैं कहाँ सलाह दे रहा हूँ ");
        map.put("where  will I have been answering ", "मैं कहाँ जवाब दे रहा हूँ ");
        map.put("where  will I have been arising ", "मैं कहाँ उठ रहा हूँ ");
        map.put("where  will I have been arriving ", "मैं कहाँ आ रहा हूँ ");
        map.put("where  will I have been asking ", "मैं कहाँ पूछ रहा हूँ ");
        map.put("where  will I have been awaking ", "मैं कहाँ जाग रहा हूँ ");
        map.put("where  will I have been undefined", "मुझे अपरिभाषित कहाँ किया गया होगा");
        map.put("where  will I have been bearing ", "मैं कहाँ असर कर रहा हूँ ");
        map.put("where  will I have been beating ", "मैं कहाँ पिटाई कर रहा हूँ ");
        map.put("where  will I have been becoming ", "मैं कहाँ बन रहा हूँ ");
        map.put("where  will I have been begging ", "मैं कहाँ भीख माँग रहा हूँ ");
        map.put("where  will I have been beginning ", "मैं कहाँ से शुरू कर रहा हूँ ");
        map.put("where  will I have been binding ", "मैं बाध्यकारी कहाँ रहूँगा ");
        map.put("where  will I have been blessing ", "मैं कहाँ आशीष रहा हूँ ");
        map.put("where  will I have been biting ", "मैं कहाँ काट रहा हूँ ");
        map.put("where  will I have been blowing ", "मैं कहाँ उड़ रहा हूँ ");
        map.put("where  will I have been breaking ", "मैं कहाँ तोड़ रहा हूँ ");
        map.put("where  will I have been bringing ", "मैं कहाँ ला रहा हूँ ");
        map.put("where  will I have been building ", "मैं कहाँ निर्माण कर रहा हूँ ");
        map.put("where  will I have been burning ", "मैं कहाँ जल रहा हूँ ");
        map.put("where  will I have been buying ", "मैं कहाँ खरीद रहा हूँ ");
        map.put("where  will I have been calling ", "मैं कहां कॉल कर रहा हूँ ");
        map.put("where  will I have been carrying ", "मैं कहाँ ले जा रहा हूँ ");
        map.put("where  will I have been catching ", "मैं कहाँ पकड़ रहा हूँ ");
        map.put("where  will I have been cheating ", "मैं कहाँ धोखा दे रहा हूँ ");
        map.put("where  will I have been choosing ", "मैं कहाँ चुन रहा हूँ ");
        map.put("where  will I have been cleaning ", "मैं कहाँ सफाई कर रहा हूँ ");
        map.put("where  will I have been climbing ", "मैं कहाँ चढ़ रहा हूँ ");
        map.put("where  will I have been closing ", "मैं कहाँ बंद हो रहा हूँ ");
        map.put("where  will I have been coming ", "मैं कहाँ आ रहा हूँ ");
        map.put("where  will I have been cooking ", "मैं कहाँ खाना बना रहा हूँ ");
        map.put("where  will I have been creeping ", "मैं कहाँ रेंग रहा हूँ ");
        map.put("where  will I have been crying ", "मैं कहाँ रो रहा हूँ ");
        map.put("where  will I have been cutting ", "मैं कहाँ काट रहा हूँ ");
        map.put("where  will I have been dancing ", "मैं कहाँ नाचता रहा हूँ ");
        map.put("where  will I have been dealing ", "मैं कहाँ काम कर रहा हूँ ");
        map.put("where  will I have been dying ", "मैं कहाँ मर रहा हूँ ");
        map.put("where  will I have been digging ", "मैं कहाँ खोद रहा हूँ ");
        map.put("where  will I have been drawing ", "मैं कहाँ आरेखण कर रहा हूँ ");
        map.put("where  will I have been drinking ", "मैं कहाँ पी रहा हूँ ");
        map.put("where  will I have been driving ", "मैं कहाँ चला रहा हूँ ");
        map.put("where  will I have been dropping ", "मैं कहाँ छोड़ रहा हूँ ");
        map.put("where  will I have been drying ", "मैं कहाँ सूख रहा हूँ ");
        map.put("where  will I have been eating ", "मैं कहाँ खा रहा हूँ ");
        map.put("where  will I have been electing ", "मैं कहाँ चुनाव कर रहा हूँ ");
        map.put("where  will I have been entering ", "मैं कहाँ प्रवेश कर रहा हूँ ");
        map.put("where  will I have been falling ", "मैं कहाँ गिर रहा हूँ ");
        map.put("where  will I have been feeding ", "मैं कहाँ खिला रहा हूँ ");
        map.put("where  will I have been feeling ", "मैं कहाँ महसूस कर रहा हूँ ");
        map.put("where  will I have been fighting ", "मैं कहाँ लड़ूँगा ");
        map.put("where  will I have been finding ", "मुझे कहाँ मिल रहा होगा ");
        map.put("where  will I have been fleeing ", "मैं कहाँ भाग रहा हूँ ");
        map.put("where  will I have been flying ", "मैं कहाँ उड़ रहा हूँ ");
        map.put("where  will I have been forgetting ", "मैं कहाँ भूल गया होता ");
        map.put("where  will I have been frying ", "मैं कहाँ तलने गया होता ");
        map.put("where  will I have been getting ", "मुझे कहाँ मिल रहा होगा ");
        map.put("where  will I have been giving ", "मैं कहाँ दे रहा हूँ ");
        map.put("where  will I have been going ", "मैं कहाँ जा रहा हूँ ");
        map.put("where  will I have been growing ", "मैं कहाँ बढ़ रहा हूँ ");
        map.put("where  will I have been hanging ", "मैं कहाँ लटक रहा हूँ ");
        map.put("where  will I have been hearing ", "मैं कहाँ सुन रहा हूँ ");
        map.put("where  will I have been helping ", "मैं कहाँ मदद कर रहा हूँ ");
        map.put("where  will I have been hiding ", "मैं कहाँ छिप रहा हूँ ");
        map.put("where  will I have been hitting ", "मैं कहाँ मार रहा हूँ ");
        map.put("where  will I have been holding ", "मैं कहाँ पकड़ रहा हूँ ");
        map.put("where  will I have been hoping ", "मैं कहाँ उम्मीद कर रहा था ");
        map.put("where  will I have been hurting ", "मैं कहाँ चोट पहुँचा रहा हूँ ");
        map.put("where  will I have been jumping ", "मैं कहाँ कूद रहा हूँ ");
        map.put("where  will I have been keeping ", "मैं कहाँ रख रहा हूँ ");
        map.put("where  will I have been killing ", "मैं कहाँ मार रहा हूँ ");
        map.put("where  will I have been knowing ", "मुझे कहाँ पता चल रहा होगा ");
        map.put("where  will I have been laughing ", "मैं कहाँ हँस रहा हूँ ");
        map.put("where  will I have been leading ", "मैं कहाँ अग्रणी रहा हूँ ");
        map.put("where  will I have been leaping ", "मैं कहाँ छलांग लगा रहा हूँ ");
        map.put("where  will I have been learning ", "मैं कहाँ सीख रहा हूँ ");
        map.put("where  will I have been leaving ", "मैं कहाँ जा रहा हूँ ");
        map.put("where  will I have been lending ", "मैं कहाँ उधार दे रहा हूँ ");
        map.put("where  will I have been living ", "मैं कहाँ रह रहा हूँ ");
        map.put("where  will I have been looking ", "मैं कहाँ देख रहा हूँ ");
        map.put("where  will I have been losing ", "मैं कहाँ हार रहा हूँ ");
        map.put("where  will I have been loving ", "मैं कहाँ प्यार कर रहा हूँ ");
        map.put("where  will I have been making ", "मैं कहाँ बना रहा हूँ ");
        map.put("where  will I have been marrying ", "मैं शादी कहाँ कर रहा हूँ ");
        map.put("where  will I have been meeting ", "मैं कहाँ मिल रहा हूँ ");
        map.put("where  will I have been mistaking ", "मैं कहाँ गलत कर रहा हूँ ");
        map.put("where  will I have been opening ", "मैं कहाँ खोल रहा हूँ ");
        map.put("where  will I have been paying ", "मैं कहाँ भुगतान कर रहा हूँ ");
        map.put("where  will I have been playing ", "मैं कहाँ खेलूँगा ");
        map.put("where  will I have been putting ", "मैं कहाँ डाल रहा हूँ ");
        map.put("where  will I have been quarrelling ", "मैं झगड़ा कहाँ कर रहा हूँ ");
        map.put("where  will I have been raining ", "मेरी बारिश कहाँ होगी ");
        map.put("where  will I have been reaching ", "मैं कहाँ पहुँच रहा हूँ ");
        map.put("where  will I have been reading ", "मैं कहाँ पढ़ रहा हूँ ");
        map.put("where  will I have been remembering ", "मुझे कहाँ याद आ रहा होगा ");
        map.put("where  will I have been riding ", "मैं कहाँ सवारी कर रहा हूँ ");
        map.put("where  will I have been ringing ", "मैं कहाँ बज रहा हूँ ");
        map.put("where  will I have been rising ", "मैं कहाँ उठ रहा हूँ ");
        map.put("where  will I have been running ", "मैं कहाँ दौड़ रहा हूँ ");
        map.put("where  will I have been saying ", "मैं कहाँ कह रहा हूँ ");
        map.put("where  will I have been seeing ", "मैं कहाँ देख रहा हूँ ");
        map.put("where  will I have been selling ", "मैं कहाँ बेच रहा हूँ ");
        map.put("where  will I have been sending ", "मैं कहाँ भेज रहा हूँ ");
        map.put("where  will I have been shaking ", "मैं कहाँ हिल रहा हूँ ");
        map.put("where  will I have been shining ", "मैं कहाँ चमक रहा हूँ ");
        map.put("where  will I have been shooting ", "मैं कहाँ शूटिंग कर रहा हूँ ");
        map.put("where  will I have been showing ", "मैं कहाँ दिखा रहा हूँ ");
        map.put("where  will I have been shutting ", "मैं कहाँ बंद कर रहा हूँ ");
        map.put("where  will I have been singing ", "मैं कहाँ गा रहा हूँ ");
        map.put("where  will I have been sinking ", "मैं कहाँ डूब रहा हूँ ");
        map.put("where  will I have been sleeping ", "मैं कहाँ सो रहा हूँ ");
        map.put("where  will I have been smelling ", "मुझे कहां सूंघना होगा ");
        map.put("where  will I have been stealing ", "मैं कहाँ चोरी कर रहा हूँ ");
        map.put("where  will I have been wanting ", "मैं कहाँ चाहूँगा ");

        return map;
    }


}
