package com.shiviishiv7.helloenglish.QuestionSource;

import java.util.HashMap;
import java.util.Map;

public class Which {
    public static Map<String,String> Which(int state){
            switch (state){
                case 1:return One();
                case 2:return Two();
                case 3:return Three();
                case 4:return Four();
                case 5:return Five();
                case 6:return Six();
                case 7:return Seven();
                case 8:return Eight();
                case 9:return Nine();
                case 10:return Ten();
                case 11:return Eleven();
                case 12:return Twelve();

                default:return One();
            }

    }
    static Map<String,String> One(){
        HashMap<String,String>map = new HashMap<>();
        map.put("which do I abuse ", "मैं किसका दुरुपयोग करता हूँ ");
        map.put("which do I advise", "मैं किसकी सलाह दूँ");
        map.put("which do I answer ", "मैं किसका जवाब दूँ ");
        map.put("which do I arise ", "मैं कौन सा उठता हूँ ");
        map.put("which do I arrive ", "मैं किससे पहुँचूँ ");
        map.put("which do I ask ", "मैं किससे पूछूँ ");
        map.put("which do I awake ", "मैं किससे जागता हूँ ");

        map.put("which do I bear ", "मैं किसे सहन करूँ ");
        map.put("which do I beat ", "मैं किसे हराऊं ");
        map.put("which do I become ", "मैं कौन सा बन जाऊं ");
        map.put("which do I beg ", "मैं किससे विनती करता हूँ ");
        map.put("which do I begin ", "मैं किससे शुरू करूँ ");
        map.put("which do I bind ", "मैं किसको बाँध सकता हूँ ");
        map.put("which do I bite", "मैं किसे काटूं");
        map.put("which do I bless", "मैं किसे आशीर्वाद देता हूं");
        map.put("which do I blow ", "मैं किसे उड़ाऊं ");
        map.put("which do I break ", "मैं किसे तोड़ूँ ");
        map.put("which do I bring ", "मैं किसे लाऊं ");
        map.put("which do I build ", "मैं किसका निर्माण करूँ ");
        map.put("which do I burn ", "मैं किसे जलाता हूँ ");
        map.put("which do I buy ", "मैं किसे खरीदूं ");
        map.put("which do I call ", "मैं किसे कॉल करूँ ");
        map.put("which do I carry ", "मैं किसे ले जाऊं ");
        map.put("which do I catch ", "मैं किसे पकड़ूँ ");
        map.put("which do I choose ", "मैं किसे चुनूं ");
        map.put("which do I clean ", "मैं किसको साफ करूँ ");
        map.put("which do I climb  ", "मैं किस पर चढ़ूँ  ");
        map.put("which do I close ", "मैं किसे बंद करूँ ");
        map.put("which do I come ", "मैं किससे आऊं ");
        map.put("which do I cook ", "मैं किसे पकाऊं ");
        map.put("which do I creep ", "मैं किससे रेंगता हूँ ");
        map.put("which do I cry ", "मैं किसको रोता हूँ ");
        map.put("which do I cut ", "मैं किसे काटूं ");
        map.put("which do I dance ", "मैं किसे नाचता हूँ ");
        map.put("which do I deal ", "मैं किससे निपटूं ");
        map.put("which do I die ", "मैं कौन मर जाऊं ");
        map.put("which do I dig ", "मैं किसको खोदूँ ");
        map.put("which do I do ", "मैं क्या करूँ ");
        map.put("which  did I  do ", "मैंने क्या किया ");
        map.put("which  had I  done ", "मैंने जो किया था ");
        map.put("which  was I  doing ", "मैं कौन सा कर रहा था ");
        map.put("which  had I been  doing ", "जो मैं कर रहा था ");
        map.put("which  will I do ", "मैं क्या करूँगा ");
        map.put("which  will I be doing ", "मैं कौन सा कर रहा हूँ ");
        map.put("which  will I have done ", "मैंने जो किया होगा ");
        map.put("which  will I have been doing ", "मैं कौन सा कर रहा हूँ ");
        map.put("which do I draw ", "मैं किसे आकर्षित करता हूँ ");
        map.put("which do I drive ", "मैं किसे चलाऊं ");
        map.put("which do I drop ", "मैं किसे छोड़ूँ ");
        map.put("which do I dry ", "मैं किसको सुखाता हूँ ");
        map.put("which do I eat ", "मैं कौन सा खाऊं ");
        map.put("which do I elect", "मैं किसका चुनाव करूँ");
        map.put("which do I fall ", "मैं किससे गिरता हूँ ");
        map.put("which do I feed ", "मैं किसे खिलाऊं ");
        map.put("which do I feel  ", "मुझे क्या लगता है  ");
        map.put("which do I fight ", "मैं किससे लड़ूं ");
        map.put("which do I find ", "मुझे कौन सा मिल रहा है ");
        map.put("which do I flee ", "मैं किससे भागता हूँ ");
        map.put("which do I fly  ", "मैं किसे उड़ूँ  ");
        map.put("which do I forget ", "मैं किसे भूल जाऊं ");
        map.put("which do I fry ", "मैं किसे भूनूं ");
        map.put("which do I get  ", "मुझे कौन सा मिलेगा  ");
        map.put("which do I give ", "मैं कौन सा दे सकता हूँ ");
        map.put("which do I go ", "मैं किससे जाऊं ");
        map.put("which do I grow", "मैं कौन सा उगाऊं");
        map.put("which do I hang ", "मैं किसे लटकाऊं ");
        map.put("which do I hear ", "मैं क्या सुनता हूँ ");
        map.put("which do I help ", "मैं किसकी मदद करूँ ");
        map.put("which do I hide ", "मैं किसे छिपाऊं ");
        map.put("which do I hit ", "मैं किसे मारूं ");
        map.put("which do I hold ", "मैं किसे पकड़ सकता हूँ ");
        map.put("which do I hope ", "मुझे किसकी उम्मीद है ");
        map.put("which do I hurt ", "मुझे कौन सी चोट लगी है ");
        map.put("which do I jump ", "मैं किससे कूदता हूँ ");
        map.put("which do I kill ", "मैं किसे मारूं ");
        map.put("which do I know ", "मुझे क्या पता है ");
        map.put("which do I laugh ", "मैं कौन हँसता हूँ ");
        map.put("which do I lead ", "मैं किसका नेतृत्व करूँ ");
        map.put("which do I leap ", "मैं किससे छलांग लगाऊं ");
        map.put("which do I learn ", "मैं कौन सी सीखूं ");
        map.put("which do I leave ", "मैं किसे छोड़ूँ ");
        map.put("which do I lend ", "मैं किसे उधार दे सकता हूँ ");
        map.put("which do I live ", "मैं कौन सा रहता हूँ ");
        map.put("which do I look ", "मैं किसे देखूं ");
        map.put("which do I lose ", "मैं किसको खो दूँ ");
        map.put("which do I love ", "मैं किससे प्यार करता हूँ ");
        map.put("which do I make ", "मैं किसे बनाऊं ");
        map.put("which do I marry ", "मैं किससे शादी करूँ ");
        map.put("which do I meet ", "मैं किससे मिलूं ");
        map.put("which do I mistake ", "मैं किसकी गलती करता हूँ ");
        map.put("which do I open ", "मैं किसे खोलूं ");
        map.put("which do I pay  ", "मैं किसका भुगतान करूँ  ");
        map.put("which do I play ", "मैं कौन सा खेलूं ");
        map.put("which do I put ", "मैं कौन सा रखूं ");
        map.put("which do I rain ", "मैं किसकी बारिश करता हूँ ");
        map.put("which do I reach ", "मैं किसतक पहुँचूँ ");
        map.put("which do I read", "मैं किसे पढ़ूँ");
        map.put("which do I remember  ", "मुझे कौन सी याद है  ");
        map.put("which do I ride ", "मैं किसकी सवारी करूँ ");
        map.put("which do I ring ", "मैं किसकी अंगूठी करता हूँ ");
        map.put("which do I rise  ", "मैं किससे उठूँ  ");
        map.put("which do I run  ", "मैं किसे चलाऊँ  ");
        map.put("which do I say ", "मैं क्या कहूँ ");
        map.put("which do I see ", "मैं किसे देखूँ ");
        map.put("which do I sell ", "मैं किसे बेचूँ ");
        map.put("which do I send ", "मैं किसे भेजूं ");
        map.put("which do I shake ", "मैं किसे हिला सकता हूँ ");
        map.put("which do I shine ", "मैं किसको चमकता हूँ ");
        map.put("which do I shoot ", "मैं किसे शूट करूँ ");
        map.put("which do I show ", "मैं कौन सा दिखाऊं ");
        map.put("which do I shut  ", "मैं किसे बंद करूँ  ");
        map.put("which do I sing ", "मैं कौन सा गाऊं ");
        map.put("which do I sink ", "मैं किसको डूबता हूँ ");
        map.put("which do I sleep ", "मैं किसको सोता हूँ ");
        map.put("which do I spoil", "मैं किसको खराब करता हूँ");
        map.put("which do I tear ", "मैं किसको फाड़ता हूँ ");
        map.put("which do I use ", "मैं किसका उपयोग करूँ ");

        return map;
    }
    static Map<String,String> Two(){
        HashMap<String,String>map = new HashMap<>();
        map.put("which am I abusing ", "मैं किसका गाली दे रहा हूँ ");
        map.put("which am I advising ", "मैं किसकी सलाह दे रहा हूँ ");
        map.put("which am I answering ", "मैं किसका जवाब दे रहा हूँ ");
        map.put("which am I arising ", "मैं कौन सा पैदा कर रहा हूँ ");
        map.put("which am I arriving ", "मैं कौन आ रहा हूँ ");
        map.put("which am I asking ", "मैं किससे पूछ रहा हूँ ");
        map.put("which am I awaking ", "मैं कौन सा जाग रहा हूँ ");
        map.put("which am I undefined", "मैं किससे अपरिभाषित हूँ");
        map.put("which am I bearing ", "मैं किसका असर कर रहा हूँ ");
        map.put("which am I beating ", "मैं किसकी पिटाई कर रहा हूँ ");
        map.put("which am I becoming ", "मैं कौन सा बन रहा हूँ ");
        map.put("which am I begging ", "मैं किससे भीख मांग रहा हूँ ");
        map.put("which am I beginning ", "मैं कौन सी शुरुआत कर रहा हूँ ");
        map.put("which am I binding ", "मैं कौन सा बाध्यकारी हूं ");
        map.put("which am I biting ", "मैं किसे काट रहा हूँ ");
        map.put("which am I blessing ", "मैं कौन सा आशीर्वाद दे रहा हूं ");
        map.put("which am I blowing ", "मैं किसको उड़ा रहा हूँ ");
        map.put("which am I breaking ", "मैं कौन सा तोड़ रहा हूँ ");
        map.put("which am I bringing ", "मैं कौन ला रहा हूँ ");
        map.put("which am I building ", "मैं किसका निर्माण कर रहा हूँ ");
        map.put("which am I burning ", "मैं किसको जला रहा हूँ ");
        map.put("which am I buying ", "मैं कौन सा खरीद रहा हूँ ");
        map.put("which am I calling ", "मैं किसे बुला रहा हूँ ");
        map.put("which am I carrying ", "मैं किसे ले जा रहा हूँ ");
        map.put("which am I catching ", "मैं किसे पकड़ रहा हूँ ");
        map.put("which am I cheating ", "मैं किसे धोखा दे रहा हूँ ");
        map.put("which am I choosing ", "मैं किसे चुन रहा हूँ ");
        map.put("which am I cleaning ", "मैं कौन सी सफाई कर रहा हूँ ");
        map.put("which am I climbing ", "मैं किस पर चढ़ रहा हूँ ");
        map.put("which am I closing ", "मैं कौन सा बंद कर रहा हूँ ");
        map.put("which am I coming ", "मैं कौन आ रहा हूँ ");
        map.put("which am I cooking ", "मैं कौन सा खाना बना रहा हूँ ");
        map.put("which am I creeping ", "मैं कौन सा रेंग रहा हूँ ");
        map.put("which am I crying ", "मैं कौन सी रो रहा हूँ ");
        map.put("which am I cutting ", "मैं किसको काट रहा हूँ ");
        map.put("which am I dancing ", "मैं कौन सा नाच रहा हूँ ");
        map.put("which am I dealing ", "मैं किसका काम कर रहा हूँ ");
        map.put("which am I dying ", "मैं कौन मर रहा हूँ ");
        map.put("which am I digging ", "मैं कौन सी खुदाई कर रहा हूँ ");
        map.put("which am I doing ", "मैं कौन सा कर रहा हूँ ");
        map.put("which am I drawing ", "मैं किसे चित्रित कर रहा हूँ ");
        map.put("which do I dream ", "मैं किसका सपना देखता हूँ ");
        map.put("which am I dreaming ", "मैं कौन सा सपना देख रहा हूँ ");
        map.put("which  have I dreamt ", "मैंने किसका सपना देखा है ");
        map.put("which  have I been dreaming ", "जो मैं सपना देख रहा था ");
        map.put("which  did I  dream ", "मैंने किसका सपना देखा था ");
        map.put("which  was I  dreaming ", "मैं कौन सा सपना देख रहा था ");
        map.put("which  will I be dreaming ", "मैं कौन सा सपना देख रहा हूँ ");
        map.put("which  will I have dreamt ", "मैंने किसका सपना देखा होगा ");
        map.put("which  will I have been dreaming ", "मैं कौन सा सपना देख रहा हूँ ");
        map.put("which  had I  dreamt ", "मैंने किसका सपना देखा था ");
        map.put("which  had I been  dreaming ", "जो मैं सपना देख रहा था ");
        map.put("which am I drinking ", "मैं कौन पी रहा हूँ ");
        map.put("which am I driving ", "मैं कौन सी गाड़ी चला रहा हूँ ");
        map.put("which am I dropping ", "मैं किसको छोड़ रहा हूँ ");
        map.put("which am I drying ", "मैं किसे सुखा रहा हूँ ");
        map.put("which am I eating ", "मैं कौन सा खा रहा हूँ ");
        map.put("which am I electing ", "मैं किसका चुनाव कर रहा हूँ ");
        map.put("which am I entering ", "मैं किसे प्रवेश कर रहा हूँ ");
        map.put("which am I falling ", "मैं कौन सा गिर रहा हूँ ");
        map.put("which am I feeding ", "मैं किसे खिला रहा हूँ ");
        map.put("which am I feeling ", "मैं कौन सा महसूस कर रहा हूँ ");
        map.put("which am I fighting ", "मैं किससे लड़ रहा हूँ ");
        map.put("which am I finding ", "मुझे कौन सा मिल रहा है ");
        map.put("which am I fleeing ", "मैं किससे भाग रहा हूँ ");
        map.put("which am I flying ", "मैं किससे उड़ रहा हूँ ");
        map.put("which am I forgetting ", "मैं किसे भूल रहा हूँ ");
        map.put("which am I frying ", "मैं कौन सा तलने वाला हूँ ");
        map.put("which am I getting ", "मुझे कौन सा मिल रहा है ");
        map.put("which am I giving ", "मैं कौन सा दे रहा हूँ ");
        map.put("which am I going ", "मैं कौन जा रहा हूँ ");
        map.put("which am I growing ", "मैं कौन सा बढ़ रहा हूँ ");
        map.put("which am I hanging ", "मैं किसे लटक रहा हूँ ");
        map.put("which am I hearing ", "मैं कौन सुन रहा हूँ ");
        map.put("which am I helping ", "मैं कौन सी मदद कर रहा हूँ ");
        map.put("which am I hiding ", "मैं किसे छिपा रहा हूँ ");
        map.put("which am I hitting ", "मैं किसको मार रहा हूँ ");
        map.put("which am I holding ", "मैं किसे पकड़ रहा हूँ ");
        map.put("which am I hoping ", "मैं कौन सी उम्मीद कर रहा हूँ ");
        map.put("which am I hurting ", "मैं किसको चोट पहुँचा रहा हूँ ");
        map.put("which am I jumping ", "मैं कौन सा कूद रहा हूँ ");
        map.put("which am I keeping ", "मैं किसे रख रहा हूँ ");
        map.put("which am I killing ", "मैं किसको मार रहा हूँ ");
        map.put("which am I knowing ", "मैं किसे जान रहा हूँ ");
        map.put("which am I laughing ", "मैं कौन हँस रहा हूँ ");
        map.put("which am I leading ", "मैं किसका नेतृत्व कर रहा हूँ ");
        map.put("which am I leaping ", "मैं कौन सी छलांग लगा रहा हूँ ");
        map.put("which am I learning ", "मैं कौन सी सीख रहा हूँ ");
        map.put("which am I leaving ", "मैं किसे छोड़ रहा हूँ ");
        map.put("which am I lending ", "मैं कौन सा उधार दे रहा हूँ ");
        map.put("which am I living ", "मैं कौन सा रह रहा हूँ ");
        map.put("which am I looking ", "मैं किसे देख रहा हूँ ");
        map.put("which am I losing ", "मैं कौन सा खो रहा हूँ ");
        map.put("which am I loving ", "मैं किसे प्यार कर रहा हूँ ");
        map.put("which am I making ", "मैं कौन सा बना रहा हूँ ");
        map.put("which am I marrying ", "मैं किससे शादी कर रहा हूँ ");
        map.put("which am I meeting ", "मैं किससे मिल रहा हूँ ");
        map.put("which am I mistaking ", "मैं किसकी गलती कर रहा हूँ ");
        map.put("which am I opening ", "मैं किसे खोल रहा हूँ ");
        map.put("which am I paying ", "मैं किसका भुगतान कर रहा हूँ ");
        map.put("which am I playing ", "मैं कौन सा खेल रहा हूँ ");
        map.put("which am I putting ", "मैं कौन सा डाल रहा हूँ ");
        map.put("which am I quarrelling ", "मैं किससे झगड़ा कर रहा हूँ ");
        map.put("which am I raining ", "मैं किसकी बारिश कर रहा हूँ ");
        map.put("which am I reaching ", "मैं किसतक पहुँच रहा हूँ ");
        map.put("which am I reading ", "मैं किसे पढ़ रहा हूँ ");
        map.put("which am I remembering ", "मुझे कौन सी याद है ");
        map.put("which am I riding ", "मैं किस पर सवारी कर रहा हूँ ");
        map.put("which am I ringing ", "मैं किससे बज रहा हूँ ");
        map.put("which am I rising ", "मैं कौन सा उठ रहा हूँ ");
        map.put("which am I running ", "मैं कौन सी दौड़ रहा हूँ ");
        map.put("which am I saying ", "मैं कौन कह रहा हूँ ");
        map.put("which am I seeing ", "जो मैं देख रहा हूँ ");
        map.put("which am I selling ", "मैं किसे बेच रहा हूँ ");
        map.put("which am I sending ", "मैं किसे भेज रहा हूँ ");
        map.put("which am I shaking ", "मैं किसको हिला रहा हूँ ");
        map.put("which am I shining ", "मैं किसकी चमक रहा हूँ ");
        map.put("which am I shooting ", "मैं कौन सी शूटिंग कर रहा हूँ ");
        map.put("which am I showing ", "मैं कौन सा दिखा रहा हूँ ");
        map.put("which am I shutting ", "मैं किसे बंद कर रहा हूँ ");
        map.put("which am I singing ", "मैं कौन सा गा रहा हूँ ");
        map.put("which am I sinking ", "मैं कौन डूब रहा हूँ ");
        map.put("which am I sleeping ", "मैं कौन सो रहा हूँ ");
        map.put("which am I stealing ", "मैं कौन सी चोरी कर रहा हूँ ");
        map.put("which am I wearing ", "मैं किसे पहन रहा हूँ ");

        return map;
    }
    static Map<String,String> Three(){
        HashMap<String,String>map = new HashMap<>();
        map.put("which  have I abused ", "जो मैंने गाली दी है ");
        map.put("which  have I advised ", "जो मैंने सलाह दी है ");
        map.put("which  have I answered ", "जिसका मैंने उत्तर दिया है ");
        map.put("which  have I arisen ", "जो मैंने पैदा किया है ");
        map.put("which  have I arrived ", "मैं कौन आ चुका हूँ ");
        map.put("which  have I asked ", "जो मैंने पूछा है ");
        map.put("which  have I awoken ", "जो मैंने जाग लिया है ");
        map.put("which  have I undefined", "जो मैंने अपरिभाषित किया है");
        map.put("which  have I borne ", "जो मैंने पैदा किया है ");
        map.put("which  have I beaten ", "मैंने किसे पीटा है ");
        map.put("which  have I become ", "जो मैं बन गया हूँ ");
        map.put("which  have I begged ", "जो मैंने भीख माँगी है ");
        map.put("which  have I begun ", "जो मैंने शुरू किया है ");
        map.put("which  have I bound ", "जो मैंने बाध्य किया है ");
        map.put("which  have I bitten ", "जो मैंने काट लिया है ");
        map.put("which  have I blessed ", "जो मैंने आशीष दी है ");
        map.put("which  have I blown ", "जो मैंने उड़ा दिया है ");
        map.put("which  have I broken ", "जो मैंने तोड़ा है ");
        map.put("which  have I brought ", "जो मैं लाया हूँ ");
        map.put("which  have I built ", "जो मैंने बनाया है ");
        map.put("which  have I burnt ", "जो मैंने जलाया है ");
        map.put("which  have I bought ", "जो मैंने खरीदा है ");
        map.put("which  have I called ", "जिसे मैंने बुलाया है ");
        map.put("which  have I carried ", "जो मैंने किया है ");
        map.put("which  have I caught ", "जो मैंने पकड़ा है ");
        map.put("which  have I cheated ", "जिसे मैंने धोखा दिया है ");
        map.put("which  have I chosen ", "मैंने किसे चुना है ");
        map.put("which  have I cleaned ", "जिसे मैंने साफ किया है ");
        map.put("which  have I climbed ", "जो मैं चढ़ गया हूँ ");
        map.put("which  have I closed ", "जो मैंने बंद कर दिया है ");
        map.put("which  have I come ", "जो मैं आया हूँ ");
        map.put("which  have I cooked ", "मैंने किसे पकाया है ");
        map.put("which  have I crept ", "जो मैंने क्रेप किया है ");
        map.put("which  have I cried ", "जो मैंने रोया है ");
        map.put("which  have I cut ", "मैंने किसको काट दिया है ");
        map.put("which  have I danced ", "मैंने जो नृत्य किया है ");
        map.put("which  have I dealt ", "जो मैंने निपटाया है ");
        map.put("which  have I died ", "जो मैं मर चुका हूँ ");
        map.put("which  have I dug ", "जो मैंने खोदा है ");
        map.put("which  have I done ", "मैंने जो किया है ");
        map.put("which  have I drawn ", "जो मैंने खींचा है ");
        map.put("which  have I drunk ", "जो मैंने पिया है ");
        map.put("which  have I driven ", "जो मैंने चलाया है ");
        map.put("which  have I dropped ", "जो मैंने गिरा दिया है ");
        map.put("which  have I dried ", "जो मैंने सुखाया है ");
        map.put("which  have I eaten ", "मैंने जो खाया है ");
        map.put("which  have I elected ", "मैंने किसे चुना है ");
        map.put("which  have I entered ", "जो मैंने दर्ज किया है ");
        map.put("which  have I fallen ", "जो मैं गिर गया हूँ ");
        map.put("which  have I fed ", "जो मैंने खिलाया है ");
        map.put("which  have I felt ", "जो मैंने महसूस किया है ");
        map.put("which  have I fought ", "जो मैंने लड़ा है ");
        map.put("which  have I found ", "जो मैंने पाया है ");
        map.put("which  have I fled ", "जो मैं भाग गया हूँ ");
        map.put("which  have I flown ", "जो मैंने उड़ाया है ");
        map.put("which  have I forgotten ", "जो मैं भूल गया हूँ ");
        map.put("which  have I fried ", "जो मैंने फ्राई किया है ");
        map.put("which  have I got ", "जो मुझे मिला है ");
        map.put("which  have I given ", "मैंने जो दिया है ");
        map.put("which  have I gone ", "जो मैं गया हूँ ");
        map.put("which  have I grown ", "जो मैंने उगाया है ");
        map.put("which  have I hanged ", "जिसे मैंने फांसी दी है ");
        map.put("which  have I hung ", "जो मैंने लटका दिया है ");
        map.put("which  have I heard ", "जो मैंने सुना है ");
        map.put("which  have I helped ", "मैंने किसकी मदद की है ");
        map.put("which  have I hidden ", "जो मैंने छिपाया है ");
        map.put("which  have I hit ", "जो मैंने मारा है ");
        map.put("which  have I held ", "जो मैंने आयोजित किया है ");
        map.put("which  have I hoped ", "जो मैंने आशा की है ");
        map.put("which  have I hurt ", "जो मैंने चोट पहुंचाई है ");
        map.put("which  have I jumped ", "जो मैंने छलांग लगाई है ");
        map.put("which  have I kept ", "जो मैंने रखा है ");
        map.put("which  have I killed ", "मैंने किसको मार डाला है ");
        map.put("which  have I known ", "जो मैंने जाना है ");
        map.put("which  have I laughed ", "जो मैंने हँसा है ");
        map.put("which  have I led ", "मैंने किसका नेतृत्व किया है ");
        map.put("which  have I leapt ", "जो मैंने छलांग लगाई है ");
        map.put("which  have I learnt ", "जो मैंने सीखा है ");
        map.put("which  have I left ", "जो मैंने छोड़ा है ");
        map.put("which  have I lent ", "जो मैंने उधार दिया है ");
        map.put("which  have I lived ", "जो मैंने जिया है ");
        map.put("which  have I looked ", "जो मैंने देखा है ");
        map.put("which  have I lost ", "जो मैंने खो दिया है ");
        map.put("which  have I loved ", "जिसे मैंने प्यार किया है ");
        map.put("which  have I made ", "मैंने जो बनाया है ");
        map.put("which  have I married ", "मैंने किससे शादी की है ");
        map.put("which  have I met ", "मैं किससे मिला हूँ ");
        map.put("which  have I mistaken ", "जो मैंने गलत किया है ");
        map.put("which  have I opened ", "जो मैंने खोला है ");
        map.put("which  have I paid ", "मैंने जो भुगतान किया है ");
        map.put("which  have I played ", "मैंने कौन सा खेला है ");
        map.put("which  have I put ", "जो मैंने रखा है ");
        map.put("which  have I quarrelled ", "मैंने किससे झगड़ा किया ");
        map.put("which  have I rained ", "मैंने किसकी बारिश की है ");
        map.put("which  have I reached ", "जो मैं पहुँचा हूँ ");
        map.put("which  have I read ", "मैंने जो पढ़ा है ");
        map.put("which  have I remembered ", "जो मुझे याद आया ");
        map.put("which  have I ridden ", "मैंने किसकी सवारी की है ");
        map.put("which  have I rung ", "जो मैंने बजाया है ");
        map.put("which  have I risen ", "जो मैं उठ गया हूँ ");
        map.put("which  have I run ", "जो मैंने चलाया है ");
        map.put("which  have I said ", "मैंने जो कहा है ");
        map.put("which  have I seen ", "जो मैंने देखा है ");
        map.put("which  have I sold ", "जो मैंने बेचा है ");
        map.put("which  have I sent ", "जो मैंने भेजा है ");
        map.put("which  have I shaken ", "जो मैंने हिला दिया है ");
        map.put("which  have I shone ", "जो मैंने चमकाया है ");
        map.put("which  have I shot ", "जो मैंने गोली मार दी है ");
        map.put("which  have I shown ", "जो मैंने दिखाया है ");
        map.put("which  have I shut ", "जो मैंने बंद कर दिया है ");
        map.put("which  have I sung ", "मैंने जो गाया है ");
        map.put("which  have I sunk ", "जो मैं डूब गया हूँ ");
        map.put("which  have I slept ", "जो मैंने सोया है ");
        map.put("which  have I used ", "मैंने किसका उपयोग किया है ");
        map.put("which  have I worked ", "मैंने जो काम किया है ");

        return map;
    }
    static Map<String,String> Four(){
        HashMap<String,String>map = new HashMap<>();
        map.put("which  have I been abusing ", "जो मैं गाली दे रहा हूं ");
        map.put("which  have I been advising ", "जो मैं सलाह दे रहा हूं ");
        map.put("which  have I been answering ", "जिसका मैं जवाब दे रहा हूं ");
        map.put("which  have I been arising ", "जो मैं उठ रहा हूँ ");
        map.put("which  have I been arriving ", "जो मैं आ रहा हूँ ");
        map.put("which  have I been asking ", "जो मैं पूछ रहा था ");
        map.put("which  have I been awaking ", "जो मैं जाग रहा था ");
        map.put("which  have I been undefined", "जो मुझे अपरिभाषित किया गया है");
        map.put("which  have I been bearing ", "जो मैं असर कर रहा हूं ");
        map.put("which  have I been beating ", "मैं किसकी पिटाई कर रहा हूँ ");
        map.put("which  have I been becoming ", "जो मैं बन रहा हूँ ");
        map.put("which  have I been begging ", "जो मैं भीख माँग रहा हूँ ");
        map.put("which  have I been beginning ", "मैं किसकी शुरुआत कर रहा हूँ ");
        map.put("which  have I been binding ", "जो मैं बाध्यकारी रहा हूं ");
        map.put("which  have I been biting ", "जो मैं काट रहा था ");
        map.put("which  have I been blessing ", "जो मैं आशीष रहा हूँ ");
        map.put("which  have I been blowing ", "जो मैं उड़ा रहा हूँ ");
        map.put("which  have I been breaking ", "जो मैं तोड़ रहा हूँ ");
        map.put("which  have I been bringing ", "जो मैं ला रहा हूँ ");
        map.put("which  have I been building ", "मैं किसका निर्माण कर रहा हूँ ");
        map.put("which  have I been burning ", "जो मैं जल रहा हूँ ");
        map.put("which  have I been buying ", "जो मैं खरीद रहा हूं ");
        map.put("which  have I been calling ", "जिसे मैं बुला रहा था ");
        map.put("which  have I been carrying ", "जो मैं ले जा रहा हूँ ");
        map.put("which  have I been catching ", "जो मैं पकड़ रहा हूँ ");
        map.put("which  have I been cheating ", "जिसे मैं धोखा दे रहा हूं ");
        map.put("which  have I been choosing ", "जिसे मैं चुन रहा हूं ");
        map.put("which  have I been cleaning ", "मैं किसकी सफाई कर रहा हूँ ");
        map.put("which  have I been climbing ", "जो मैं चढ़ रहा था ");
        map.put("which  have I been closing ", "जो मैं बंद कर रहा हूँ ");
        map.put("which  have I been coming ", "मैं कौन आ रहा हूँ ");
        map.put("which  have I been cooking ", "जो मैं खाना बना रहा हूँ ");
        map.put("which  have I been creeping ", "जो मैं रेंग रहा हूँ ");
        map.put("which  have I been crying ", "जो मैं रो रहा था ");
        map.put("which  have I been cutting ", "जो मैं काट रहा हूं ");
        map.put("which  have I been dancing ", "मैं किससे नाच रहा हूँ ");
        map.put("which  have I been dealing ", "मैं किससे काम कर रहा हूं ");
        map.put("which  have I been dying ", "जो मैं मर रहा हूँ ");
        map.put("which  have I been digging ", "जो मैं खोद रहा हूँ ");
        map.put("which  have I been doing ", "जो मैं कर रहा हूँ ");
        map.put("which  have I been drawing ", "जो मैं चित्रित कर रहा हूं ");
        map.put("which  have I been drinking ", "जो मैं पी रहा हूँ ");
        map.put("which  have I been driving ", "जो मैं चला रहा था ");
        map.put("which  have I been dropping ", "जो मैं छोड़ रहा हूँ ");
        map.put("which  have I been drying ", "जो मैं सूख रहा था ");
        map.put("which  have I been eating ", "जो मैं खा रहा हूँ ");
        map.put("which  have I been electing ", "मैं किसका चुनाव कर रहा हूँ ");
        map.put("which  have I been entering ", "मैं किसमें प्रवेश कर रहा हूँ ");
        map.put("which  have I been falling ", "जो मैं गिर रहा था ");
        map.put("which  have I been feeding ", "जो मैं खिला रहा हूँ ");
        map.put("which  have I been feeling ", "जो मैं महसूस कर रहा था ");
        map.put("which  have I been fighting ", "मैं किससे लड़ रहा हूँ ");
        map.put("which  have I been finding ", "जो मुझे मिल रहा है ");
        map.put("which  have I been fleeing ", "मैं किससे भाग रहा हूँ ");
        map.put("which  have I been flying ", "मैं किससे उड़ रहा हूँ ");
        map.put("which  have I been forgetting ", "जो मैं भूल रहा हूँ ");
        map.put("which  have I been frying ", "जो मैं तलने गया हूँ ");
        map.put("which  have I been getting ", "जो मुझे मिल रहा है ");
        map.put("which  have I been giving ", "जो मैं दे रहा हूँ ");
        map.put("which  have I been going ", "मैं किससे जा रहा हूँ ");
        map.put("which  have I been growing ", "जो मैं बढ़ रहा हूँ ");
        map.put("which  have I been hanging ", "जो मैं लटका रहा हूँ ");
        map.put("which  have I been hearing ", "जो मैं सुन रहा हूँ ");
        map.put("which  have I been helping ", "मैं किसकी मदद कर रहा हूँ ");
        map.put("which  have I been hiding ", "जो मैं छिपा रहा हूँ ");
        map.put("which  have I been hitting ", "जो मैं मार रहा हूँ ");
        map.put("which  have I been holding ", "जो मैं पकड़ रहा हूँ ");
        map.put("which  have I been hoping ", "मैं किसकी उम्मीद कर रहा था ");
        map.put("which  have I been hurting ", "जो मैं चोट पहुँचा रहा हूँ ");
        map.put("which  have I been jumping ", "मैं किससे कूद रहा हूँ ");
        map.put("which  have I been keeping ", "जो मैं रख रहा हूँ ");
        map.put("which  have I been killing ", "मैं किसको मार रहा हूँ ");
        map.put("which  have I been knowing ", "जो मैं जानता रहा हूँ ");
        map.put("which  have I been laughing ", "जो मैं हँस रहा था ");
        map.put("which  have I been leading ", "मैं किसका नेतृत्व कर रहा हूं ");
        map.put("which  have I been leaping ", "जो मैं छलांग लगा रहा हूँ ");
        map.put("which  have I been learning ", "जो मैं सीख रहा हूँ ");
        map.put("which  have I been leaving ", "जो मैं छोड़ रहा हूँ ");
        map.put("which  have I been lending ", "जो मैं उधार दे रहा हूं ");
        map.put("which  have I been living ", "मैं किससे जी रहा हूँ ");
        map.put("which  have I been looking ", "जो मैं देख रहा था ");
        map.put("which  have I been losing ", "जो मैं खो रहा हूँ ");
        map.put("which  have I been loving ", "मैं किससे प्यार कर रहा हूँ ");
        map.put("which  have I been making ", "जो मैं बना रहा हूँ ");
        map.put("which  have I been marrying ", "मैं किससे शादी कर रहा हूँ ");
        map.put("which  have I been meeting ", "मैं किससे मिल रहा हूँ ");
        map.put("which  have I been mistaking ", "जो मैं गलत कर रहा हूँ ");
        map.put("which  have I been opening ", "जो मैं खोल रहा हूँ ");
        map.put("which  have I been paying ", "जो मैं भुगतान कर रहा हूं ");
        map.put("which  have I been playing ", "मैं कौन सा खेल रहा हूँ ");
        map.put("which  have I been putting ", "जो मैं लगा रहा हूँ ");
        map.put("which  have I been quarrelling ", "मैं किससे झगड़ा कर रहा हूँ ");
        map.put("which  have I been raining ", "मैं किसकी बारिश कर रहा हूँ ");
        map.put("which  have I been reaching ", "मैं किसतक पहुँच रहा हूँ ");
        map.put("which  have I been reading ", "जो मैं पढ़ रहा हूँ ");
        map.put("which  have I been remembering ", "जो मुझे याद आ रहा है ");
        map.put("which  have I been riding ", "मैं किसकी सवारी कर रहा हूँ ");
        map.put("which  have I been ringing ", "जो मैं बज रहा हूँ ");
        map.put("which  have I been rising ", "जो मैं उठ रहा हूँ ");
        map.put("which  have I been running ", "जो मैं चला रहा हूँ ");
        map.put("which  have I been saying ", "जो मैं कह रहा हूँ ");
        map.put("which  have I been seeing ", "जो मैं देख रहा था ");
        map.put("which  have I been selling ", "जो मैं बेच रहा हूँ ");
        map.put("which  have I been sending ", "जो मैं भेज रहा हूं ");
        map.put("which  have I been shaking ", "जो मैं हिल रहा था ");
        map.put("which  have I been shining ", "जो मैं चमक रहा हूँ ");
        map.put("which  have I been shooting ", "मैं किसकी शूटिंग कर रहा हूँ ");
        map.put("which  have I been showing ", "जो मैं दिखा रहा हूँ ");
        map.put("which  have I been shutting ", "जो मैं बंद कर रहा हूँ ");
        map.put("which  have I been singing ", "मैं कौन गा रहा हूँ ");
        map.put("which  have I been sinking ", "जो मैं डूब रहा हूँ ");
        map.put("which  have I been sleeping ", "जो मैं सो रहा था ");
        map.put("which  have I been studying ", "मैं किसका अध्ययन कर रहा हूँ ");
        map.put("which  have I been talking ", "मैं किससे बात कर रहा था ");
        map.put("which  have I been thinking ", "जो मैं सोच रहा था ");
        map.put("which  have I been trying ", "जो मैं कोशिश कर रहा था ");
        map.put("which  have I been wearing ", "जो मैंने पहन रखा है ");

        return map;

    }
    static Map<String,String> Five(){
        HashMap<String,String>map = new HashMap<>();
        map.put("which  did I  abuse ", "मैंने किसके साथ गाली दी ");
        map.put("which  did I  advise", "मैंने किसकी सलाह दी");
        map.put("which  did I  answer ", "मैंने किसका जवाब दिया ");
        map.put("which  did I  arise ", "मैं कौन सा उठ गया ");
        map.put("which  did I  arrive ", "मैं कौन आया ");
        map.put("which  did I  ask ", "मैंने किससे पूछा था ");
        map.put("which  did I  awake ", "मैंने किसको जगाया था ");
        map.put("which  did I  \r", "मैंने कौन सा किया  \r");
        map.put("which  did I  beat ", "मैंने किसे हराया ");
        map.put("which  did I  become ", "मैं कौन सा बन गया ");
        map.put("which  did I  beg ", "मैंने किससे भीख माँगी ");
        map.put("which  did I  begin ", "मैंने किससे शुरू किया ");
        map.put("which  did I  bind ", "मैंने किसको बाँध दिया था ");
        map.put("which  did I  bite", "मैंने किसे काट लिया");
        map.put("which  did I  bless", "मैंने किसको आशीर्वाद दिया");
        map.put("which  did I  blow ", "मैंने किसको उड़ा दिया ");
        map.put("which  did I  break ", "मैंने किसको तोड़ा ");
        map.put("which  did I  bring ", "जो मैंने लाया था ");
        map.put("which  did I  build ", "मैंने किसका निर्माण किया ");
        map.put("which  did I  burn ", "मैंने किसको जला दिया ");
        map.put("which  did I  buy ", "मैंने किसे खरीदा ");
        map.put("which  did I  call ", "मैंने किसे फोन किया ");
        map.put("which  did I  carry ", "मैंने कौन सा ले लिया था ");
        map.put("which  did I  catch ", "मैंने किसे पकड़ लिया ");
        map.put("which  did I  cheat ", "मैंने किसको धोखा दिया ");
        map.put("which  did I  choose ", "मैंने किसे चुना ");
        map.put("which  did I  clean ", "मैंने किसे साफ किया ");
        map.put("which  did I  climb  ", "मैं किस पर चढ़ गया  ");
        map.put("which  did I  close ", "मैंने किसे बंद किया ");
        map.put("which  did I  come ", "मैं कौन आया ");
        map.put("which  did I  cook ", "मैंने किसे खाना बनाया ");
        map.put("which  did I  creep ", "मैंने कौन सा रेंगना था ");
        map.put("which  did I  cut ", "मैंने किसको काट दिया ");
        map.put("which  did I  dance ", "मैंने कौन सा नृत्य किया ");
        map.put("which  did I  deal ", "मैंने किसका सौदा किया ");
        map.put("which  did I  die ", "मैं कौन मर गया ");
        map.put("which  did I  dig ", "जो मैंने खोदा था ");
        map.put("which  did I  draw ", "मैंने किसे आकर्षित किया ");
        map.put("which  did I  drive ", "मैंने कौन सी ड्राइव की ");
        map.put("which  did I  drop ", "मैंने किसको छोड़ दिया ");
        map.put("which  did I  dry ", "मैंने किसको सुखाया ");
        map.put("which  did I  eat ", "मैंने कौन सा खाया ");
        map.put("which  did I  elect", "मैंने किसका चुनाव किया");
        map.put("which  did I  enter ", "मैंने किसमें प्रवेश किया ");
        map.put("which  did I  fall ", "मैं किससे गिर गया ");
        map.put("which  did I  feed ", "मैंने किसे खाना खिलाया ");
        map.put("which  did I  feel  ", "जो मैंने महसूस किया  ");
        map.put("which  did I  fight ", "मैंने किससे लड़ाई की ");
        map.put("which  did I  find ", "मुझे कौन सा मिला ");
        map.put("which  did I  flee ", "मैं किससे भागा ");
        map.put("which  did I  fly  ", "मैंने किसकी उड़ान भरी  ");
        map.put("which  did I  fry ", "मैंने कौन सा फ्राई किया ");
        map.put("which  did I  get  ", "मुझे कौन सा मिला  ");
        map.put("which  did I  give ", "मैंने जो दिया ");
        map.put("which  did I  go ", "मैं किससे गया ");
        map.put("which  did I  grow", "मैं कौन सा उगाया");
        map.put("which  did I  hang ", "मैंने किसको लटका दिया ");
        map.put("which  did I  hear ", "मैंने जो सुना ");
        map.put("which  did I  help ", "मैंने किसकी मदद की ");
        map.put("which  did I  hide ", "जो मैंने छिपाया था ");
        map.put("which  did I  hit ", "मैंने किसको मारा ");
        map.put("which  did I  hold ", "मैंने कौन सी पकड़ रखी थी ");
        map.put("which  did I  hope ", "मुझे किसकी उम्मीद थी ");
        map.put("which  did I  hurt ", "मैंने किसको चोट पहुंचाई ");
        map.put("which  did I  jump ", "मैंने किससे छलांग लगाई ");
        map.put("which  did I  keep ", "मैंने किसे रखा था ");
        map.put("which  did I  kill ", "मैंने किसको मार डाला ");
        map.put("which  did I  know ", "मुझे क्या पता था ");
        map.put("which  did I  laugh ", "मैं किससे हँसा ");
        map.put("which  did I  lead ", "मैंने किसका नेतृत्व किया ");
        map.put("which  did I  leap ", "मैंने किसकी छलांग लगाई ");
        map.put("which  did I  learn ", "मैंने कौनसा सीखा ");
        map.put("which  did I  leave ", "मैंने किसे छोड़ा था ");
        map.put("which  did I  live ", "मैं किससे जीता था ");
        map.put("which  did I  look ", "मैंने कौन सा देखा ");
        map.put("which  did I  lose ", "मैंने किसको खो दिया ");
        map.put("which  did I  love ", "मुझे किससे प्यार था ");
        map.put("which  did I  make ", "मैंने कौन सा बनाया ");
        map.put("which  did I  marry ", "मैंने किससे शादी की ");
        map.put("which  did I  meet ", "मैं किससे मिला ");
        map.put("which  did I  mistake ", "मैंने किसकी गलती की ");
        map.put("which  did I  open ", "मैंने कौन सा खोला ");
        map.put("which  did I  pay  ", "मैंने किसका भुगतान किया  ");
        map.put("which  did I  play ", "मैंने कौन सा खेला था ");
        map.put("which  did I  put ", "मैंने कौन सा रखा ");
        map.put("which  did I  quarrel ", "मैंने किससे झगड़ा किया ");
        map.put("which  did I  rain ", "मैंने किसकी बारिश की ");
        map.put("which  did I  reach ", "मैं किसतक पहुँचा ");
        map.put("which  did I  read", "मैंने जो पढ़ा था");
        map.put("which  did I  remember  ", "जो मुझे याद था  ");
        map.put("which  did I  ride ", "मैंने किसकी सवारी की ");
        map.put("which  did I  ring ", "मैंने किसकी अंगूठी की ");
        map.put("which  did I  rise  ", "मैं किससे उठ गया  ");
        map.put("which  did I  say ", "मैंने जो कहा था ");
        map.put("which  did I  see ", "मैंने जो देखा ");
        map.put("which  did I  sell ", "मैंने किसे बेचा था ");
        map.put("which  did I  send ", "मैंने किसे भेजा था ");
        map.put("which  did I  shake ", "मैंने किसको हिला दिया ");
        map.put("which  did I  shine ", "मैंने किसको चमकाया ");
        map.put("which  did I  shoot ", "मैंने किसको शूट किया था ");
        map.put("which  did I  show ", "मैंने जो दिखाया था ");
        map.put("which  did I  shut  ", "मैंने किसे बंद किया  ");
        map.put("which  did I  sing ", "मैंने कौन सा गाना गाया था ");
        map.put("which  did I  sink ", "मैंने किसको डुबो दिया ");
        map.put("which  did I  sleep ", "मैं किससे सोता था ");
        map.put("which  did I  stay ", "मैं कौन रह गया ");
        map.put("which  did I  use ", "मैंने किसका उपयोग किया ");

        return map;
    }
    static Map<String,String> Six(){
        HashMap<String,String>map = new HashMap<>();
        map.put("which  was I  abusing ", "जो मैं गाली दे रहा था ");
        map.put("which  was I  advising ", "मैं किसकी सलाह दे रहा था ");
        map.put("which  was I  answering ", "मैं किसका जवाब दे रहा था ");
        map.put("which  was I  arising ", "मैं कौन सा उठ रहा था ");
        map.put("which  was I  arriving ", "मैं कौन आ रहा था ");
        map.put("which  was I  asking ", "जो मैं पूछ रहा था ");
        map.put("which  was I  awaking ", "जो मैं जाग रहा था ");
        map.put("which  was I  undefined", "मैं कौन सा अपरिभाषित था");
        map.put("which  was I  bearing ", "मैं किसका असर कर रहा था ");
        map.put("which  was I  beating ", "मैं किसकी पिटाई कर रहा था ");
        map.put("which  was I  becoming ", "मैं कौन बन रहा था ");
        map.put("which  was I  begging ", "जो मैं भीख माँग रहा था ");
        map.put("which  was I  beginning ", "मैं कौन सी शुरुआत कर रहा था ");
        map.put("which  was I  binding ", "मैं कौन सा बाध्यकारी था ");
        map.put("which  was I  biting ", "जो मैं काट रहा था ");
        map.put("which  was I  blessing ", "मैं कौन सा आशीर्वाद दे रहा था ");
        map.put("which  was I  blowing ", "जो मैं उड़ा रहा था ");
        map.put("which  was I  breaking ", "मैं कौन तोड़ रहा था ");
        map.put("which  was I  bringing ", "जो मैं ला रहा था ");
        map.put("which  was I  building ", "मैं किसका निर्माण कर रहा था ");
        map.put("which  was I  burning ", "मैं कौन सा जल रहा था ");
        map.put("which  was I  buying ", "जो मैं खरीद रहा था ");
        map.put("which  was I  calling ", "जिसे मैं बुला रहा था ");
        map.put("which  was I  carrying ", "मैं किसे ले जा रहा था ");
        map.put("which  was I  catching ", "मैं किसे पकड़ रहा था ");
        map.put("which  was I  cheating ", "जो मैं धोखा दे रहा था ");
        map.put("which  was I  choosing ", "मैं किसे चुन रहा था ");
        map.put("which  was I  cleaning ", "मैं कौन सी सफाई कर रहा था ");
        map.put("which  was I  climbing ", "मैं किस पर चढ़ रहा था ");
        map.put("which  was I  closing ", "मैं कौन सा बंद कर रहा था ");
        map.put("which  was I  coming ", "मैं कौन आ रहा था ");
        map.put("which  was I  cooking ", "मैं कौन सा खाना बना रहा था ");
        map.put("which  was I  creeping ", "मैं कौन सा रेंग रहा था ");
        map.put("which  was I  crying ", "मैं कौन रो रहा था ");
        map.put("which  was I  cutting ", "मैं किसको काट रहा था ");
        map.put("which  was I  dancing ", "मैं कौन सा नाच रहा था ");
        map.put("which  was I  dealing ", "मैं किसका काम कर रहा था ");
        map.put("which  was I  dying ", "मैं कौन मर रहा था ");
        map.put("which  was I  digging ", "जो मैं खुदाई कर रहा था ");
        map.put("which  was I  drawing ", "मैं किसे चित्रित कर रहा था ");
        map.put("which  was I  drinking ", "मैं कौन पी रहा था ");
        map.put("which  was I  driving ", "मैं कौन सी गाड़ी चला रहा था ");
        map.put("which  was I  dropping ", "मैं किसको छोड़ रहा था ");
        map.put("which  was I  drying ", "जो मैं सूख रहा था ");
        map.put("which  was I  eating ", "मैं कौन खा रहा था ");
        map.put("which  was I  electing ", "मैं किसका चुनाव कर रहा था ");
        map.put("which  was I  entering ", "मैं किस में प्रवेश कर रहा था ");
        map.put("which  was I  falling ", "मैं कौन गिर रहा था ");
        map.put("which  was I  feeding ", "जो मैं खिला रहा था ");
        map.put("which  was I  feeling ", "जो मैं महसूस कर रहा था ");
        map.put("which  was I  fighting ", "मैं किससे लड़ रहा था ");
        map.put("which  was I  finding ", "जो मुझे मिल रहा था ");
        map.put("which  was I  fleeing ", "मैं किससे भाग रहा था ");
        map.put("which  was I  flying ", "मैं कौन सा उड़ रहा था ");
        map.put("which  was I  forgetting ", "जो मैं भूल रहा था ");
        map.put("which  was I  frying ", "मैं कौन सा तलने वाला था ");
        map.put("which  was I  getting ", "जो मुझे मिल रहा था ");
        map.put("which  was I  giving ", "जो मैं दे रहा था ");
        map.put("which  was I  going ", "मैं कौन जा रहा था ");
        map.put("which  was I  growing ", "मैं कौन सा बढ़ रहा था ");
        map.put("which  was I  hanging ", "मैं कौन लटक रहा था ");
        map.put("which  was I  hearing ", "जो मैं सुन रहा था ");
        map.put("which  was I  helping ", "जो मैं मदद कर रहा था ");
        map.put("which  was I  hiding ", "जो मैं छिपा रहा था ");
        map.put("which  was I  hitting ", "जो मैं मार रहा था ");
        map.put("which  was I  holding ", "जो मैं पकड़ रहा था ");
        map.put("which  was I  hoping ", "जो मैं उम्मीद कर रहा था ");
        map.put("which  was I  hurting ", "मैं किसको चोट पहुँचा रहा था ");
        map.put("which  was I  jumping ", "मैं कौन सा कूद रहा था ");
        map.put("which  was I  keeping ", "जो मैं रख रहा था ");
        map.put("which  was I  killing ", "मैं किसको मार रहा था ");
        map.put("which  was I  knowing ", "जो मैं जान रहा था ");
        map.put("which  was I  laughing ", "मैं कौन हँस रहा था ");
        map.put("which  was I  leading ", "मैं किसका नेतृत्व कर रहा था ");
        map.put("which  was I  leaping ", "मैं कौन सी छलांग लगा रहा था ");
        map.put("which  was I  learning ", "मैं कौन सी सीख रहा था ");
        map.put("which  was I  leaving ", "मैं किसे छोड़ रहा था ");
        map.put("which  was I  lending ", "मैं कौन सा उधार दे रहा था ");
        map.put("which  was I  living ", "मैं कौन सा रह रहा था ");
        map.put("which  was I  looking ", "जो मैं देख रहा था ");
        map.put("which  was I  losing ", "मैं कौन सा हार रहा था ");
        map.put("which  was I  loving ", "मैं किसे प्यार कर रहा था ");
        map.put("which  was I  making ", "मैं कौन सा बना रहा था ");
        map.put("which  was I  marrying ", "मैं किससे शादी कर रहा था ");
        map.put("which  was I  meeting ", "मैं किससे मिल रहा था ");
        map.put("which  was I  mistaking ", "जो मैं गलत कर रहा था ");
        map.put("which  was I  opening ", "मैं कौन सा खोल रहा था ");
        map.put("which  was I  paying ", "मैं किसका भुगतान कर रहा था ");
        map.put("which  was I  playing ", "मैं कौन सा खेल रहा था ");
        map.put("which  was I  putting ", "जो मैं डाल रहा था ");
        map.put("which  was I  quarrelling ", "मैं कौन झगड़ा कर रहा था ");
        map.put("which  was I  raining ", "मैं किसकी बारिश कर रहा था ");
        map.put("which  was I  reaching ", "मैं किस तक पहुँच रहा था ");
        map.put("which  was I  reading ", "जो मैं पढ़ रहा था ");
        map.put("which  was I  remembering ", "जो मुझे याद था ");
        map.put("which  was I  riding ", "मैं किस पर सवारी कर रहा था ");
        map.put("which  was I  ringing ", "मैं कौन बज रहा था ");
        map.put("which  was I  rising ", "जो मैं उठ रहा था ");
        map.put("which  was I  running ", "मैं कौन सी दौड़ रहा था ");
        map.put("which  was I  saying ", "मैं कौन कह रहा था ");
        map.put("which  was I  seeing ", "जो मैं देख रहा था ");
        map.put("which  was I  selling ", "मैं किसे बेच रहा था ");
        map.put("which  was I  sending ", "जो मैं भेज रहा था ");
        map.put("which  was I  shaking ", "जो मैं हिल रहा था ");
        map.put("which  was I  shining ", "मैं किससे चमक रहा था ");
        map.put("which  was I  shooting ", "मैं कौन सी शूटिंग कर रहा था ");
        map.put("which  was I  showing ", "जो मैं दिखा रहा था ");
        map.put("which  was I  shutting ", "मैं किसे बंद कर रहा था ");
        map.put("which  was I  singing ", "मैं कौन गा रहा था ");
        map.put("which  was I  sinking ", "मैं कौन डूब रहा था ");
        map.put("which  was I  sleeping ", "मैं कौन सो रहा था ");
        map.put("which  was I  swimming ", "मैं कौन सा तैर रहा था ");
        map.put("which  was I  talking ", "मैं कौन सी बात कर रहा था ");
        map.put("which  was I  weeping ", "मैं कौन सी रो रही थी ");
        map.put("which  was I  working ", "मैं कौन सा काम कर रहा था ");

        return map;
    }
    static Map<String,String> Seven(){
        HashMap<String,String>map = new HashMap<>();
        map.put("which  had I  abused ", "जिसके साथ मैंने गाली दी थी ");
        map.put("which  had I  advised ", "जो मैंने सलाह दी थी ");
        map.put("which  had I  answered ", "जिसका मैंने जवाब दिया था ");
        map.put("which  had I  arisen ", "जो मैंने पैदा किया था ");
        map.put("which  had I  arrived ", "जो मैं आया था ");
        map.put("which  had I  asked ", "जो मैंने पूछा था ");
        map.put("which  had I  awoken ", "जो मैं जाग गया था ");
        map.put("which  had I  undefined", "जिसे मैंने अपरिभाषित किया था");
        map.put("which  had I  borne ", "जो मैंने पैदा किया था ");
        map.put("which  had I  beaten ", "जिसे मैंने पीटा था ");
        map.put("which  had I  become ", "जो मैं बन गया था ");
        map.put("which  had I  begged ", "जो मैंने भीख माँगी थी ");
        map.put("which  had I  begun ", "जो मैंने शुरू किया था ");
        map.put("which  had I  bound ", "जो मैंने बाध्य किया था ");
        map.put("which  had I  bitten ", "जिसे मैंने काट लिया था ");
        map.put("which  had I  blessed ", "जिसे मैंने आशीर्वाद दिया था ");
        map.put("which  had I  blown ", "जिसे मैंने उड़ा दिया था ");
        map.put("which  had I  broken ", "जो मैंने तोड़ा था ");
        map.put("which  had I  brought ", "जो मैं लाया था ");
        map.put("which  had I  built ", "जो मैंने बनाया था ");
        map.put("which  had I  burnt ", "जो मैंने जलाया था ");
        map.put("which  had I  bought ", "जो मैंने खरीदा था ");
        map.put("which  had I  called ", "जिसे मैंने फोन किया था ");
        map.put("which  had I  carried ", "जो मैंने किया था ");
        map.put("which  had I  caught ", "जिसे मैंने पकड़ा था ");
        map.put("which  had I  cheated ", "जिसे मैंने धोखा दिया था ");
        map.put("which  had I  chosen ", "जिसे मैंने चुना था ");
        map.put("which  had I  cleaned ", "जिसे मैंने साफ किया था ");
        map.put("which  had I  climbed ", "जो मैं चढ़ गया था ");
        map.put("which  had I  closed ", "जिसे मैंने बंद किया था ");
        map.put("which  had I  come ", "जो मैं आया था ");
        map.put("which  had I  cooked ", "जो मैंने पकाया था ");
        map.put("which  had I  crept ", "जो मैंने क्रेप किया था ");
        map.put("which  had I  cried ", "जो मैंने रोया था ");
        map.put("which  had I  cut ", "जो मैंने काट दिया था ");
        map.put("which  had I  danced ", "मैंने किसका नृत्य किया था ");
        map.put("which  had I  dealt ", "जो मैंने निपटाया था ");
        map.put("which  had I  died ", "जो मैं मर गया था ");
        map.put("which  had I  dug ", "जो मैंने खोदा था ");
        map.put("which  had I  drawn ", "जो मैंने खींचा था ");
        map.put("which  had I  drunk ", "जो मैंने पिया था ");
        map.put("which  had I  driven ", "जो मैंने चलाया था ");
        map.put("which  had I  dropped ", "जो मैंने गिरा दिया था ");
        map.put("which  had I  dried ", "जो मैंने सुखाया था ");
        map.put("which  had I  eaten ", "जो मैंने खाया था ");
        map.put("which  had I  elected ", "मैंने किसे चुना था ");
        map.put("which  had I  entered ", "जो मैंने प्रवेश किया था ");
        map.put("which  had I  fallen ", "जो मैं गिर गया था ");
        map.put("which  had I  fed ", "जो मैंने खिलाया था ");
        map.put("which  had I  felt ", "जो मैंने महसूस किया था ");
        map.put("which  had I  fought ", "जो मैंने लड़ा था ");
        map.put("which  had I  found ", "जो मैंने पाया था ");
        map.put("which  had I  fled ", "मैं किससे भाग गया था ");
        map.put("which  had I  flown ", "जो मैंने उड़ाया था ");
        map.put("which  had I  forgotten ", "जिसे मैं भूल गया था ");
        map.put("which  had I  fried ", "जिसे मैंने फ्राई किया था ");
        map.put("which  had I  got ", "जो मुझे मिला था ");
        map.put("which  had I  given ", "जो मैंने दिया था ");
        map.put("which  had I  gone ", "जो मैं गया था ");
        map.put("which  had I  grown ", "जो मैंने उगाया था ");
        map.put("which  had I  hanged ", "जिसे मैंने फांसी दी थी ");
        map.put("which  had I  hung ", "जो मैंने लटका दिया था ");
        map.put("which  had I  heard ", "जो मैंने सुना था ");
        map.put("which  had I  helped ", "मैंने किसकी मदद की थी ");
        map.put("which  had I  hidden ", "जो मैंने छिपाया था ");
        map.put("which  had I  hit ", "जो मैंने मारा था ");
        map.put("which  had I  held ", "जो मैंने आयोजित किया था ");
        map.put("which  had I  hoped ", "जिसकी मुझे उम्मीद थी ");
        map.put("which  had I  hurt ", "जिसे मैंने चोट पहुंचाई थी ");
        map.put("which  had I  jumped ", "जो मैंने छलांग लगाई थी ");
        map.put("which  had I  kept ", "जो मैंने रखा था ");
        map.put("which  had I  killed ", "मैंने किसको मार डाला था ");
        map.put("which  had I  known ", "जो मुझे पता था ");
        map.put("which  had I  laughed ", "जो मैं हँसा था ");
        map.put("which  had I  led ", "मैंने किसका नेतृत्व किया था ");
        map.put("which  had I  leapt ", "जो मैंने छलांग लगाई थी ");
        map.put("which  had I  learnt ", "जो मैंने सीखा था ");
        map.put("which  had I  left ", "जो मैंने छोड़ा था ");
        map.put("which  had I  lent ", "जो मैंने उधार दिया था ");
        map.put("which  had I  lived ", "जो मैं रहता था ");
        map.put("which  had I  looked ", "जो मैंने देखा था ");
        map.put("which  had I  lost ", "जो मैंने खो दिया था ");
        map.put("which  had I  loved ", "जिसे मैंने प्यार किया था ");
        map.put("which  had I  made ", "जो मैंने बनाया था ");
        map.put("which  had I  married ", "मैंने किससे शादी की थी ");
        map.put("which  had I  met ", "मैं किससे मिला था ");
        map.put("which  had I  mistaken ", "जो मैंने गलत किया था ");
        map.put("which  had I  opened ", "जो मैंने खोला था ");
        map.put("which  had I  paid ", "जो मैंने भुगतान किया था ");
        map.put("which  had I  played ", "जो मैंने खेला था ");
        map.put("which  had I  put ", "जो मैंने रखा था ");
        map.put("which  had I  quarrelled ", "जिसमें मैंने झगड़ा किया था ");
        map.put("which  had I  rained ", "मैंने किसकी बारिश की थी ");
        map.put("which  had I  reached ", "जो मैं पहुँचा था ");
        map.put("which  had I  read ", "जो मैंने पढ़ा था ");
        map.put("which  had I  remembered ", "जिसे मैंने याद किया था ");
        map.put("which  had I  ridden ", "जो मैंने सवारी की थी ");
        map.put("which  had I  rung ", "जो मैंने बजाया था ");
        map.put("which  had I  risen ", "जो मैं उठ गया था ");
        map.put("which  had I  run ", "जो मैंने चलाया था ");
        map.put("which  had I  said ", "मैंने जो कहा था ");
        map.put("which  had I  seen ", "जो मैंने देखा था ");
        map.put("which  had I  sold ", "जो मैंने बेचा था ");
        map.put("which  had I  sent ", "जो मैंने भेजा था ");
        map.put("which  had I  shaken ", "जो मैंने हिला दिया था ");
        map.put("which  had I  shone ", "जो मैंने चमकाया था ");
        map.put("which  had I  shot ", "जिसे मैंने गोली मार दी थी ");
        map.put("which  had I  shown ", "जो मैंने दिखाया था ");
        map.put("which  had I  shut ", "जो मैंने बंद किया था ");
        map.put("which  had I  sung ", "जो मैंने गाया था ");
        map.put("which  had I  sunk ", "जो मैं डूब गया था ");
        map.put("which  had I  thought ", "जो मैंने सोचा था ");

        return map;
    }
    static Map<String,String> Eight(){
        HashMap<String,String>map = new HashMap<>();
        map.put("which  had I been  abusing ", "जो मैं गाली दे रहा था ");
        map.put("which  had I been  advising ", "जो मैं सलाह दे रहा था ");
        map.put("which  had I been  answering ", "जिसका मैं जवाब दे रहा था ");
        map.put("which  had I been  arising ", "जो मैं उठ रहा था ");
        map.put("which  had I been  arriving ", "जो मैं आ रहा था ");
        map.put("which  had I been  asking ", "जो मैं पूछ रहा था ");
        map.put("which  had I been  awaking ", "जो मैं जाग रहा था ");
        map.put("which  had I been  undefined", "जो मुझे अपरिभाषित किया गया था");
        map.put("which  had I been  bearing ", "जो मैं सहन कर रहा था ");
        map.put("which  had I been  beating ", "मैं किसकी पिटाई कर रहा था ");
        map.put("which  had I been  becoming ", "जो मैं बन रहा था ");
        map.put("which  had I been  begging ", "जो मैं भीख माँग रहा था ");
        map.put("which  had I been  beginning ", "जो मैं शुरू कर रहा था ");
        map.put("which  had I been  binding ", "जो मैं बाध्यकारी था ");
        map.put("which  had I been  biting ", "जो मैं काट रहा था ");
        map.put("which  had I been  blessing ", "जो मैं आशीर्वाद दे रहा था ");
        map.put("which  had I been  blowing ", "जो मैं उड़ा रहा था ");
        map.put("which  had I been  breaking ", "जो मैं तोड़ रहा था ");
        map.put("which  had I been  bringing ", "जो मैं ला रहा था ");
        map.put("which  had I been  building ", "मैं किसका निर्माण कर रहा था ");
        map.put("which  had I been  burning ", "जो मैं जल रहा था ");
        map.put("which  had I been  buying ", "जो मैं खरीद रहा था ");
        map.put("which  had I been  calling ", "जिसे मैं बुला रहा था ");
        map.put("which  had I been  carrying ", "जो मैं ले जा रहा था ");
        map.put("which  had I been  catching ", "जो मैं पकड़ रहा था ");
        map.put("which  had I been  cheating ", "जिसे मैं धोखा दे रहा था ");
        map.put("which  had I been  choosing ", "जो मैं चुन रहा था ");
        map.put("which  had I been  cleaning ", "मैं किसकी सफाई कर रहा था ");
        map.put("which  had I been  climbing ", "मैं किस पर चढ़ रहा था ");
        map.put("which  had I been  closing ", "जो मैं बंद कर रहा था ");
        map.put("which  had I been  coming ", "मैं कौन आ रहा था ");
        map.put("which  had I been  cooking ", "जो मैं खाना बना रहा था ");
        map.put("which  had I been  creeping ", "जो मैं रेंग रहा था ");
        map.put("which  had I been  crying ", "जो मैं रो रहा था ");
        map.put("which  had I been  cutting ", "जो मैं काट रहा था ");
        map.put("which  had I been  dancing ", "मैं कौन सा नाच रहा था ");
        map.put("which  had I been  dealing ", "जो मैं काम कर रहा था ");
        map.put("which  had I been  dying ", "जो मैं मर रहा था ");
        map.put("which  had I been  digging ", "जो मैं खुदाई कर रहा था ");
        map.put("which  had I been  drawing ", "जो मैं चित्रित कर रहा था ");
        map.put("which  had I been  drinking ", "जो मैं पी रहा था ");
        map.put("which  had I been  driving ", "जो मैं चला रहा था ");
        map.put("which  had I been  dropping ", "जो मैं छोड़ रहा था ");
        map.put("which  had I been  drying ", "जो मैं सूख रहा था ");
        map.put("which  had I been  eating ", "जो मैं खा रहा था ");
        map.put("which  had I been  electing ", "मैं किसका चुनाव कर रहा था ");
        map.put("which  had I been  entering ", "जो मैं प्रवेश कर रहा था ");
        map.put("which  had I been  falling ", "जो मैं गिर रहा था ");
        map.put("which  had I been  feeding ", "जो मैं खिला रहा था ");
        map.put("which  had I been  feeling ", "जो मैं महसूस कर रहा था ");
        map.put("which  had I been  fighting ", "मैं किससे लड़ रहा था ");
        map.put("which  had I been  finding ", "जो मुझे मिल रहा था ");
        map.put("which  had I been  fleeing ", "जो मैं भाग रहा था ");
        map.put("which  had I been  flying ", "जो मैं उड़ रहा था ");
        map.put("which  had I been  forgetting ", "जिसे मैं भूल रहा था ");
        map.put("which  had I been  frying ", "जो मैं तलने गया था ");
        map.put("which  had I been  getting ", "जो मुझे मिल रहा था ");
        map.put("which  had I been  giving ", "जो मैं दे रहा था ");
        map.put("which  had I been  going ", "जो मैं जा रहा था ");
        map.put("which  had I been  growing ", "जो मैं बढ़ रहा था ");
        map.put("which  had I been  hanging ", "जो मैं लटक रहा था ");
        map.put("which  had I been  hearing ", "जो मैं सुन रहा था ");
        map.put("which  had I been  helping ", "जो मैं मदद कर रहा था ");
        map.put("which  had I been  hiding ", "जो मैं छिपा रहा था ");
        map.put("which  had I been  hitting ", "जो मैं मार रहा था ");
        map.put("which  had I been  holding ", "जो मैं पकड़ रहा था ");
        map.put("which  had I been  hoping ", "जिसकी मैं उम्मीद कर रहा था ");
        map.put("which  had I been  hurting ", "जो मैं चोट पहुँचा रहा था ");
        map.put("which  had I been  jumping ", "जो मैं कूद रहा था ");
        map.put("which  had I been  keeping ", "जो मैं रख रहा था ");
        map.put("which  had I been  killing ", "मैं किसकी हत्या कर रहा था ");
        map.put("which  had I been  knowing ", "जो मुझे पता था ");
        map.put("which  had I been  laughing ", "जो मैं हँस रहा था ");
        map.put("which  had I been  leading ", "मैं किसका नेतृत्व कर रहा था ");
        map.put("which  had I been  leaping ", "जो मैं छलांग लगा रहा था ");
        map.put("which  had I been  learning ", "जो मैं सीख रहा था ");
        map.put("which  had I been  leaving ", "जो मैं छोड़ रहा था ");
        map.put("which  had I been  lending ", "जो मैं उधार दे रहा था ");
        map.put("which  had I been  living ", "मैं कौन सा रह रहा था ");
        map.put("which  had I been  looking ", "जो मैं देख रहा था ");
        map.put("which  had I been  losing ", "जो मैं खो रहा था ");
        map.put("which  had I been  loving ", "जो मैं प्यार कर रहा था ");
        map.put("which  had I been  making ", "जो मैं बना रहा था ");
        map.put("which  had I been  marrying ", "मैं किससे शादी कर रहा था ");
        map.put("which  had I been  meeting ", "मैं किससे मिल रहा था ");
        map.put("which  had I been  mistaking ", "जो मैं गलत कर रहा था ");
        map.put("which  had I been  opening ", "जो मैं खोल रहा था ");
        map.put("which  had I been  paying ", "जो मैं भुगतान कर रहा था ");
        map.put("which  had I been  playing ", "जो मैं खेल रहा था ");
        map.put("which  had I been  putting ", "जो मैं डाल रहा था ");
        map.put("which  had I been  quarrelling ", "जो मैं झगड़ा कर रहा था ");
        map.put("which  had I been  raining ", "मैं किसकी बारिश कर रहा था ");
        map.put("which  had I been  reaching ", "जिस पर मैं पहुँच रहा था ");
        map.put("which  had I been  reading ", "जो मैं पढ़ रहा था ");
        map.put("which  had I been  remembering ", "जिसे मैं याद कर रहा था ");
        map.put("which  had I been  riding ", "मैं किसकी सवारी कर रहा था ");
        map.put("which  had I been  ringing ", "जो मैं बज रहा था ");
        map.put("which  had I been  rising ", "जो मैं उठ रहा था ");
        map.put("which  had I been  running ", "जो मैं दौड़ रहा था ");
        map.put("which  had I been  saying ", "जो मैं कह रहा था ");
        map.put("which  had I been  seeing ", "जो मैं देख रहा था ");
        map.put("which  had I been  selling ", "जो मैं बेच रहा था ");
        map.put("which  had I been  sending ", "जो मैं भेज रहा था ");
        map.put("which  had I been  shaking ", "जो मैं हिल रहा था ");
        map.put("which  had I been  shining ", "जो मैं चमक रहा था ");
        map.put("which  had I been  shooting ", "मैं किसकी शूटिंग कर रहा था ");
        map.put("which  had I been  showing ", "जो मैं दिखा रहा था ");
        map.put("which  had I been  shutting ", "जो मैं बंद कर रहा था ");
        map.put("which  had I been  singing ", "मैं कौन सा गा रहा था ");
        map.put("which  had I been  sinking ", "जो मैं डूब रहा था ");
        map.put("which  had I been  talking ", "मैं किससे बात कर रहा था ");
        map.put("which  had I been  tearing ", "जो मैं फाड़ रहा था ");

        return map;
    }
    static Map<String,String> Nine(){
        HashMap<String,String>map = new HashMap<>();
        map.put("which  will I abuse ", "मैं किसका दुरुपयोग करूँगा ");
        map.put("which  will I advise", "मैं किसकी सलाह दूंगा");
        map.put("which  will I answer ", "मैं किसका जवाब दूंगा ");
        map.put("which  will I arise ", "मैं कौन सा उठूंगा ");
        map.put("which  will I arrive ", "मैं किससे पहुँचूँगा ");
        map.put("which  will I ask ", "मैं किससे पूछूंगा ");
        map.put("which  will I awake ", "मैं किससे जाग जाऊंगा ");
        map.put("which  will I \r", "मैं कौन सा करूंगा \r");
        map.put("which  will I be undefined", "जो मैं अपरिभाषित हो जाऊंगा");
        map.put("which  will I bear ", "मैं किसे सहन करूंगा ");
        map.put("which  will I beat ", "मैं किसे हराऊंगा ");
        map.put("which  will I become ", "मैं कौन बन जाऊंगा ");
        map.put("which  will I beg ", "मैं किससे भीख मांगूँगा ");
        map.put("which  will I begin ", "मैं किससे शुरू करूंगा ");
        map.put("which  will I bind ", "मैं किसको बाँध लूँगा ");
        map.put("which  will I bite", "मैं किसे काटूंगा");
        map.put("which  will I bless", "मैं किसको आशीर्वाद दूँगा");
        map.put("which  will I break ", "मैं किसे तोड़ूंगा ");
        map.put("which  will I bring ", "मैं कौन लाऊंगा ");
        map.put("which  will I build ", "मैं किसका निर्माण करूंगा ");
        map.put("which  will I burn ", "मैं किसको जलाऊंगा ");
        map.put("which  will I buy ", "मैं किसे खरीदूंगा ");
        map.put("which  will I call ", "मैं किसे कॉल करूंगा ");
        map.put("which  will I carry ", "मैं किसे ले जाऊंगा ");
        map.put("which  will I catch ", "मैं किसे पकड़ लूंगा ");
        map.put("which  will I cheat ", "मैं किसे धोखा दूंगा ");
        map.put("which  will I choose ", "मैं किसे चुनूंगा ");
        map.put("which  will I clean ", "मैं किसको साफ करूँगा ");
        map.put("which  will I climb  ", "मैं किस पर चढ़ जाऊंगा  ");
        map.put("which  will I close ", "मैं किसे बंद करूँगा ");
        map.put("which  will I come ", "मैं कौन आऊंगा ");
        map.put("which  will I cook ", "मैं किसे पकाऊंगा ");
        map.put("which  will I creep ", "मैं किसको रेंगूंगा ");
        map.put("which  will I cry ", "मैं किसको रोऊंगा ");
        map.put("which  will I cut ", "मैं किसको काटूंगा ");
        map.put("which  will I dance ", "मैं कौन सा नृत्य करूँगा ");
        map.put("which  will I deal ", "मैं किससे निपटूंगा ");
        map.put("which  will I die ", "मैं किससे मर जाऊंगा ");
        map.put("which  will I dig ", "मैं किसको खोदूँगा ");
        map.put("which  will I draw ", "मैं किसे आकर्षित करूंगा ");
        map.put("which  will I drive ", "मैं किसको चलाऊंगा ");
        map.put("which  will I drop ", "मैं किसे छोड़ूँगा ");
        map.put("which  will I dry ", "मैं किसको सुखाऊंगा ");
        map.put("which  will I eat ", "मैं कौन खाऊंगा ");
        map.put("which  will I elect", "मैं किसका चुनाव करूंगा");
        map.put("which  will I enter ", "मैं किसमें प्रवेश करूंगा ");
        map.put("which  will I fall ", "मैं किससे गिरूंगा ");
        map.put("which  will I feed ", "मैं किसे खिलाऊंगा ");
        map.put("which  will I feel  ", "मुझे कौन सा महसूस होगा  ");
        map.put("which  will I fight ", "मैं किससे लड़ूंगा ");
        map.put("which  will I find ", "मुझे कौन सा मिलेगा ");
        map.put("which  will I flee ", "मैं किससे भाग जाऊंगा ");
        map.put("which  will I fly  ", "मैं किससे उड़ूंगा  ");
        map.put("which  will I forget ", "मैं किसे भूल जाऊंगा ");
        map.put("which  will I fry ", "मैं किसको भूनूंगा ");
        map.put("which  will I get  ", "मुझे कौन सा मिलेगा  ");
        map.put("which  will I give ", "मैं कौन दूँगा ");
        map.put("which  will I go ", "मैं कौन जाऊंगा ");
        map.put("which  will I grow", "मैं किसको उगाऊंगा");
        map.put("which  will I hang ", "मैं किसे लटकाऊंगा ");
        map.put("which  will I hear ", "मैं कौन सुनूंगा ");
        map.put("which  will I help ", "मैं किसकी मदद करूंगा ");
        map.put("which  will I hide ", "मैं किसे छिपाऊंगा ");
        map.put("which  will I hit ", "मैं किसे मारूंगा ");
        map.put("which  will I hold ", "मैं किसे रखूँगा ");
        map.put("which  will I hope ", "मैं किसकी उम्मीद करूंगा ");
        map.put("which  will I hurt ", "मैं किसको चोट पहुंचाऊंगा ");
        map.put("which  will I jump ", "मैं किससे कूदूँगा ");
        map.put("which  will I keep ", "मैं किसे रखूँगा ");
        map.put("which  will I kill ", "मैं किसे मार डालूंगा ");
        map.put("which  will I know ", "मुझे कौन सा पता चलेगा ");
        map.put("which  will I laugh ", "मैं किसको हंसूंगा ");
        map.put("which  will I lead ", "मैं किसका नेतृत्व करूंगा ");
        map.put("which  will I leap ", "मैं किसकी छलांग लगाऊंगा ");
        map.put("which  will I learn ", "मैं कौन सी सीखूंगा ");
        map.put("which  will I leave ", "मैं किसे छोड़ूँगा ");
        map.put("which  will I lend ", "मैं किसे उधार दूँगा ");
        map.put("which  will I live ", "मैं किससे रहूँगा ");
        map.put("which  will I look ", "मैं किसे देखूँगा ");
        map.put("which  will I lose ", "मैं किसे खो दूँगा ");
        map.put("which  will I make ", "मैं किसे बनाऊंगा ");
        map.put("which  will I marry ", "मैं किससे शादी करूँगा ");
        map.put("which  will I meet ", "मैं किससे मिलूंगा ");
        map.put("which  will I mistake ", "मैं किसकी गलती करूँगा ");
        map.put("which  will I open ", "मैं किसे खोलूंगा ");
        map.put("which  will I pay  ", "मैं किसका भुगतान करूंगा  ");
        map.put("which  will I play ", "मैं कौन खेलूंगा ");
        map.put("which  will I put ", "मैं कौन सा रखूँगा ");
        map.put("which  will I quarrel ", "मैं किससे झगड़ा करूंगा ");
        map.put("which  will I rain ", "मैं किसकी बारिश करूँगा ");
        map.put("which  will I reach ", "मैं किसतक पहुँचूँगा ");
        map.put("which  will I read", "मैं कौन पढ़ूंगा");
        map.put("which  will I remember  ", "जो मुझे याद होगा  ");
        map.put("which  will I ride ", "मैं किसकी सवारी करूँगा ");
        map.put("which  will I ring ", "मैं किसकी रिंग करूंगा ");
        map.put("which  will I rise  ", "मैं किससे उठूंगा  ");
        map.put("which  will I run  ", "मैं कौन से दौड़ूंगा  ");
        map.put("which  will I say ", "मैं कौन कहूँगा ");
        map.put("which  will I see ", "जो मैं देखूंगा ");
        map.put("which  will I sell ", "मैं किसे बेचूंगा ");
        map.put("which  will I send ", "मैं किसे भेजूंगा ");
        map.put("which  will I shake ", "मैं किसको हिलाऊंगा ");
        map.put("which  will I shine ", "मैं किसको चमकूंगा ");
        map.put("which  will I shoot ", "मैं किसको शूट करूँगा ");
        map.put("which  will I shut  ", "मैं किसे बंद करूँगा  ");
        map.put("which  will I sing ", "मैं कौन सा गाऊंगा ");
        map.put("which  will I sink ", "मैं किसको डुबो दूंगा ");
        map.put("which  will I speak ", "मैं किससे बोलूंगा ");
        map.put("which  will I stay ", "मैं कौन रहूँगा ");
        map.put("which  will I study ", "मैं किसका अध्ययन करूँगा ");
        map.put("which  will I win ", "मैं कौन जीतूंगा ");

        return map;
    }
    static Map<String,String> Ten(){
        HashMap<String,String>map = new HashMap<>();
        map.put("which  will I be abusing ", "जो मैं गाली दे रहा हूँ ");
        map.put("which  will I be advising ", "मैं किसकी सलाह दूंगा ");
        map.put("which  will I be answering ", "मैं किसका जवाब दूंगा ");
        map.put("which  will I be arising ", "मैं किससे उठ रहा हूँ ");
        map.put("which  will I be arriving ", "मैं किससे पहुँचूँगा ");
        map.put("which  will I be asking ", "मैं किससे पूछूंगा ");
        map.put("which  will I be awaking ", "मैं किससे जाग रहा हूँ ");
        map.put("which  will I be bearing ", "मैं किसका असर डालूंगा ");
        map.put("which  will I be beating ", "मैं किसकी पिटाई करूंगा ");
        map.put("which  will I be becoming ", "मैं कौन सा बन जाऊंगा ");
        map.put("which  will I be begging ", "जो मैं भीख माँगता हूँ ");
        map.put("which  will I be beginning ", "मैं किसकी शुरुआत करूंगा ");
        map.put("which  will I be binding ", "मैं कौन सा बाध्यकारी रहूंगा ");
        map.put("which  will I be biting ", "मैं किसे काट रहा हूँ ");
        map.put("which  will I be blessing ", "मैं कौन सा आशीष बनूंगा ");
        map.put("which  will I be blowing ", "मैं कौन सा उड़ा रहा हूँ ");
        map.put("which  will I be breaking ", "मैं किसको तोड़ रहा हूँ ");
        map.put("which  will I be bringing ", "मैं किसको लाऊंगा ");
        map.put("which  will I be building ", "मैं किसका निर्माण करूंगा ");
        map.put("which  will I be burning ", "मैं किसको जलाऊंगा ");
        map.put("which  will I be buying ", "मैं किसे खरीदूंगा ");
        map.put("which  will I be calling ", "मैं किसे कॉल कर रहा हूँ ");
        map.put("which  will I be carrying ", "मैं किसे ले जाऊंगा ");
        map.put("which  will I be catching ", "मैं किसे पकड़ रहा हूँ ");
        map.put("which  will I be cheating ", "जो मैं धोखा दे रहा हूँ ");
        map.put("which  will I be choosing ", "मैं किसे चुनूंगा ");
        map.put("which  will I be cleaning ", "मैं किसकी सफाई करूंगा ");
        map.put("which  will I be climbing ", "मैं किस पर चढ़ जाऊंगा ");
        map.put("which  will I be closing ", "मैं किसे बंद कर रहा हूँ ");
        map.put("which  will I be coming ", "मैं कौन सा आऊंगा ");
        map.put("which  will I be cooking ", "मैं किसे खाना बना रहा हूँ ");
        map.put("which  will I be creeping ", "मैं कौन सा रेंगना चाहूँगा ");
        map.put("which  will I be crying ", "मैं किससे रो रहा हूँ ");
        map.put("which  will I be cutting ", "मैं किसको काटूंगा ");
        map.put("which  will I be dancing ", "मैं कौन सा नाचता रहूँगा ");
        map.put("which  will I be dealing ", "मैं किससे निपटूंगा ");
        map.put("which  will I be dying ", "मैं कौन मर रहा हूँ ");
        map.put("which  will I be digging ", "मैं किसकी खुदाई करूँगा ");
        map.put("which  will I be drawing ", "मैं किसको चित्रित करूंगा ");
        map.put("which  will I be drinking ", "मैं किसे पी रहा हूँ ");
        map.put("which  will I be driving ", "मैं कौन सी गाड़ी चला रहा हूँ ");
        map.put("which  will I be dropping ", "मैं किसको छोड़ रहा हूँ ");
        map.put("which  will I be drying ", "मैं किसको सुखाऊंगा ");
        map.put("which  will I be eating ", "मैं कौन सा खाऊंगा ");
        map.put("which  will I be electing ", "मैं किसका चुनाव करूंगा ");
        map.put("which  will I be entering ", "मैं किसमें प्रवेश करूंगा ");
        map.put("which  will I be falling ", "मैं किससे गिर रहा हूँ ");
        map.put("which  will I be feeding ", "मैं किसे खिलाऊंगा ");
        map.put("which  will I be feeling ", "जो मैं महसूस कर रहा हूँ ");
        map.put("which  will I be fighting ", "मैं किससे लड़ूंगा ");
        map.put("which  will I be finding ", "जो मुझे मिल रहा होगा ");
        map.put("which  will I be fleeing ", "मैं किससे भाग जाऊंगा ");
        map.put("which  will I be flying ", "मैं किसकी उड़ान भरूंगा ");
        map.put("which  will I be forgetting ", "मैं किसको भूल जाऊंगा ");
        map.put("which  will I be frying ", "मैं कौन सा तलने जाऊंगा ");
        map.put("which  will I be getting ", "मुझे कौन सा मिल रहा होगा ");
        map.put("which  will I be giving ", "मैं कौन सा दे रहा हूँ ");
        map.put("which  will I be going ", "मैं कौन सा जा रहा हूँ ");
        map.put("which  will I be growing ", "मैं कौन सा बढ़ रहा हूँ ");
        map.put("which  will I be hanging ", "मैं किसको लटकाऊंगा ");
        map.put("which  will I be hearing ", "जो मैं सुन रहा हूँ ");
        map.put("which  will I be helping ", "मैं किसकी मदद करूंगा ");
        map.put("which  will I be hiding ", "जो मैं छिपाऊंगा ");
        map.put("which  will I be hitting ", "मैं किसको मार रहा हूँ ");
        map.put("which  will I be holding ", "मैं किसको पकड़ लूंगा ");
        map.put("which  will I be hoping ", "मैं किसकी उम्मीद कर रहा हूँ ");
        map.put("which  will I be hurting ", "मैं किसको चोट पहुँचाऊंगा ");
        map.put("which  will I be jumping ", "मैं कौन सा कूद रहा हूँ ");
        map.put("which  will I be keeping ", "मैं किसे रखूँगा ");
        map.put("which  will I be killing ", "मैं किसको मार रहा हूँ ");
        map.put("which  will I be knowing ", "जो मुझे पता चल जाएगा ");
        map.put("which  will I be laughing ", "मैं किससे हँस रहा हूँ ");
        map.put("which  will I be leading ", "मैं किसकी अगुवाई करूंगा ");
        map.put("which  will I be leaping ", "मैं किसकी छलांग लगाऊंगा ");
        map.put("which  will I be learning ", "मैं कौन सी सीख रहा हूँ ");
        map.put("which  will I be leaving ", "मैं किसे छोड़ूंगा ");
        map.put("which  will I be lending ", "मैं कौन सा उधार दूंगा ");
        map.put("which  will I be living ", "मैं किससे रह रहा हूँ ");
        map.put("which  will I be looking ", "मैं किसे देख रहा हूँ ");
        map.put("which  will I be losing ", "मैं किसको खो रहा हूँ ");
        map.put("which  will I be loving ", "मैं किससे प्यार करूंगा ");
        map.put("which  will I be making ", "मैं कौन सा बना रहा हूँ ");
        map.put("which  will I be marrying ", "मैं किससे शादी करूँगा ");
        map.put("which  will I be meeting ", "मैं किससे मिल रहा हूँ ");
        map.put("which  will I be mistaking ", "जो मैं गलत हो जाऊंगा ");
        map.put("which  will I be opening ", "मैं किसे खोलूंगा ");
        map.put("which  will I be paying ", "मैं किसका भुगतान करूंगा ");
        map.put("which  will I be playing ", "मैं कौन सा खेलूंगा ");
        map.put("which  will I be putting ", "मैं कौन सा डालूंगा ");
        map.put("which  will I be quarrelling ", "मैं किससे झगड़ा करूंगा ");
        map.put("which  will I be raining ", "मैं किसकी बारिश कर रहा हूँ ");
        map.put("which  will I be reaching ", "मैं किसतक पहुँचूँगा ");
        map.put("which  will I be reading ", "मैं किसे पढ़ूंगा ");
        map.put("which  will I be remembering ", "जिसे मैं याद रखूंगा ");
        map.put("which  will I be riding ", "मैं किसकी सवारी करूँगा ");
        map.put("which  will I be ringing ", "मैं किससे बज रहा हूँ ");
        map.put("which  will I be rising ", "मैं किससे उठ रहा हूँ ");
        map.put("which  will I be running ", "मैं कौन सी दौड़ रहा हूँ ");
        map.put("which  will I be saying ", "मैं कौन कह रहा हूँ ");
        map.put("which  will I be seeing ", "जो मैं देख रहा हूँ ");
        map.put("which  will I be selling ", "मैं किसे बेचूंगा ");
        map.put("which  will I be sending ", "मैं किसे भेजूंगा ");
        map.put("which  will I be shaking ", "मैं किसको हिलाऊंगा ");
        map.put("which  will I be shining ", "मैं किससे चमक रहा हूँ ");
        map.put("which  will I be shooting ", "मैं किसकी शूटिंग करूँगा ");
        map.put("which  will I be showing ", "मैं कौन सा दिखाऊंगा ");
        map.put("which  will I be shutting ", "मैं किसे बंद कर रहा हूँ ");
        map.put("which  will I be singing ", "मैं कौन सा गा रहा हूँ ");
        map.put("which  will I be sinking ", "मैं कौनसा डूब रहा हूँ ");

        return map;
    }
    static Map<String,String> Eleven(){
        HashMap<String,String>map = new HashMap<>();
        map.put("which  will I have abused ", "जो मैंने गाली दी होगी ");
        map.put("which  will I have advised ", "जो मैंने सलाह दी होगी ");
        map.put("which  will I have answered ", "जिसका मैंने जवाब दिया होगा ");
        map.put("which  will I have arisen ", "मैं कौन सा पैदा हुआ होगा ");
        map.put("which  will I have arrived ", "मैं कौन आ गया हूँ ");
        map.put("which  will I have asked ", "जो मैंने पूछा होगा ");
        map.put("which  will I have awoken ", "जो मैं जाग जाऊंगा ");
        map.put("which  will I have undefined", "जो मैंने अपरिभाषित किया होगा");
        map.put("which  will I have borne ", "जो मैंने पैदा किया होगा ");
        map.put("which  will I have beaten ", "मैंने किसे पीटा होगा ");
        map.put("which  will I have become ", "मैं कौन सा बन जाऊंगा ");
        map.put("which  will I have begged ", "मैंने किससे भीख माँगी होगी ");
        map.put("which  will I have begun ", "जो मैंने शुरू किया होगा ");
        map.put("which  will I have bound ", "मैं किससे बाध्य होऊंगा ");
        map.put("which  will I have bitten ", "जो मैंने काट लिया होगा ");
        map.put("which  will I have blessed ", "मैं किसको आशीष दूँगा ");
        map.put("which  will I have blown ", "जो मैंने उड़ा दिया होगा ");
        map.put("which  will I have broken ", "जो मैंने तोड़ा होगा ");
        map.put("which  will I have brought ", "जो मैं लाऊंगा ");
        map.put("which  will I have built ", "मैंने कौन सा निर्माण किया होगा ");
        map.put("which  will I have burnt ", "जो मैंने जला दिया होगा ");
        map.put("which  will I have bought ", "जो मैंने खरीदा होगा ");
        map.put("which  will I have called ", "जिसे मैंने बुलाया होगा ");
        map.put("which  will I have carried ", "जो मैंने किया होगा ");
        map.put("which  will I have caught ", "जो मैंने पकड़ा होगा ");
        map.put("which  will I have cheated ", "जो मैंने धोखा दिया होगा ");
        map.put("which  will I have chosen ", "मैंने किसे चुना होगा ");
        map.put("which  will I have cleaned ", "जिसे मैंने साफ किया होगा ");
        map.put("which  will I have climbed ", "मैं किस पर चढ़ जाऊंगा ");
        map.put("which  will I have closed ", "जो मैंने बंद कर दिया होगा ");
        map.put("which  will I have come ", "मैं कौन आ गया हूँ ");
        map.put("which  will I have cooked ", "मैंने किसे पकाया होगा ");
        map.put("which  will I have crept ", "मेरे पास कौन सा crept होगा ");
        map.put("which  will I have cried ", "जो मैं रोया होगा ");
        map.put("which  will I have cut ", "मैंने किसको काट दिया होगा ");
        map.put("which  will I have danced ", "मैंने कौन सा नृत्य किया होगा ");
        map.put("which  will I have dealt ", "मैंने किससे निपटा होगा ");
        map.put("which  will I have died ", "मैं किसकी मर जाऊंगा ");
        map.put("which  will I have dug ", "जो मैंने खोदा होगा ");
        map.put("which  will I have drawn ", "मैंने कौन सा ड्रॉ किया होगा ");
        map.put("which  will I have drunk ", "जो मैंने पिया होगा ");
        map.put("which  will I have driven ", "जो मैंने चलाया होगा ");
        map.put("which  will I have dropped ", "जो मैंने गिरा दिया होगा ");
        map.put("which  will I have dried ", "जो मैं सूख जाऊंगा ");
        map.put("which  will I have eaten ", "मैंने कौन सा खाया होगा ");
        map.put("which  will I have elected ", "मैंने किसे चुना होगा ");
        map.put("which  will I have entered ", "मैंने किसमें प्रवेश किया होगा ");
        map.put("which  will I have fallen ", "मैं किससे गिर जाऊंगा ");
        map.put("which  will I have fed ", "मैंने किसे खिलाया होगा ");
        map.put("which  will I have felt ", "जो मैंने महसूस किया होगा ");
        map.put("which  will I have fought ", "मैंने किससे लड़ाई लड़ी होगी ");
        map.put("which  will I have found ", "मुझे कौनसा मिल जाएगा ");
        map.put("which  will I have fled ", "मैं किससे भाग जाऊंगा ");
        map.put("which  will I have flown ", "मैं किससे उड़ जाऊंगा ");
        map.put("which  will I have forgotten ", "मैं किसे भूल जाऊंगा ");
        map.put("which  will I have fried ", "जो मैंने फ्राई किया होगा ");
        map.put("which  will I have got ", "जो मुझे मिल गया होगा ");
        map.put("which  will I have given ", "जो मैंने दिया होगा ");
        map.put("which  will I have gone ", "मैं कौन से चला जाऊंगा ");
        map.put("which  will I have grown ", "मैं कौन सा बड़ा हो जाऊंगा ");
        map.put("which  will I have hanged ", "जिसे मैंने फांसी दी होगी ");
        map.put("which  will I have hung ", "जो मैंने लटका दिया होगा ");
        map.put("which  will I have heard ", "जो मैंने सुना होगा ");
        map.put("which  will I have helped ", "मैंने किसकी मदद की होगी ");
        map.put("which  will I have hidden ", "जो मैंने छिपाया होगा ");
        map.put("which  will I have hit ", "जो मैंने मारा होगा ");
        map.put("which  will I have held ", "जो मैंने आयोजित किया होगा ");
        map.put("which  will I have hoped ", "मुझे किसकी उम्मीद होगी ");
        map.put("which  will I have hurt ", "जो मुझे चोट लगी होगी ");
        map.put("which  will I have jumped ", "मैं किससे कूद जाऊंगा ");
        map.put("which  will I have kept ", "जो मैंने रखा होगा ");
        map.put("which  will I have killed ", "मैंने किसे मार दिया होगा ");
        map.put("which  will I have known ", "जो मुझे पता होगा ");
        map.put("which  will I have laughed ", "मुझे कौन सा हँसा होगा ");
        map.put("which  will I have led ", "मैंने किसका नेतृत्व किया होगा ");
        map.put("which  will I have leapt ", "जो मैंने छलांग लगाई होगी ");
        map.put("which  will I have learnt ", "जो मैंने सीखा होगा ");
        map.put("which  will I have left ", "जो मैंने छोड़ा होगा ");
        map.put("which  will I have lent ", "जो मैंने उधार दिया होगा ");
        map.put("which  will I have lived ", "मैं किससे जीऊंगा ");
        map.put("which  will I have looked ", "जो मैंने देखा होगा ");
        map.put("which  will I have lost ", "मैं कौन सा खो जाऊंगा ");
        map.put("which  will I have loved ", "जिसे मैंने प्यार किया होगा ");
        map.put("which  will I have made ", "मैंने जो बनाया होगा ");
        map.put("which  will I have married ", "मैंने किससे शादी की होगी ");
        map.put("which  will I have met ", "मुझे किससे मुलाकात होगी ");
        map.put("which  will I have mistaken ", "जो मैंने गलत किया होगा ");
        map.put("which  will I have opened ", "जो मैंने खोला होगा ");
        map.put("which  will I have paid ", "मैंने किसका भुगतान किया होगा ");
        map.put("which  will I have played ", "मैंने कौन सा खेला होगा ");
        map.put("which  will I have put ", "जो मैंने रखा होगा ");
        map.put("which  will I have quarrelled ", "मैं किससे झगड़ा करूंगा ");
        map.put("which  will I have rained ", "मैंने किसकी बारिश की होगी ");
        map.put("which  will I have reached ", "मैं किसतक पहुँचूँगा ");
        map.put("which  will I have read ", "जो मैंने पढ़ा होगा ");
        map.put("which  will I have remembered ", "जो मुझे याद होगा ");
        map.put("which  will I have ridden ", "मैंने किसकी सवारी की होगी ");
        map.put("which  will I have rung ", "मुझे कौनसा बजाया जाएगा ");
        map.put("which  will I have risen ", "मैं किससे उठ जाऊंगा ");
        map.put("which  will I have run ", "मैं कौन सा भाग लूंगा ");
        map.put("which  will I have said ", "जो मैंने कहा होगा ");
        map.put("which  will I have seen ", "जो मैंने देखा होगा ");
        map.put("which  will I have sold ", "जो मैंने बेचा होगा ");
        map.put("which  will I have sent ", "जो मैंने भेजा होगा ");
        map.put("which  will I have shaken ", "जो मैं हिल जाऊंगा ");
        map.put("which  will I have shone ", "मैं किससे चमकूंगा ");
        map.put("which  will I have shot ", "मैंने किसको गोली मार दी होगी ");
        map.put("which  will I have shown ", "जो मैंने दिखाया होगा ");
        map.put("which  will I have shut ", "जो मैंने बंद कर दिया होगा ");
        map.put("which  will I have sung ", "मैंने कौन सा गाया होगा ");
        map.put("which  will I have sunk ", "मैं कौनसा डूब जाऊंगा ");
        map.put("which  will I have smelt ", "मुझे कौन सी गंध आएगी ");
        map.put("which  will I have spent ", "मैंने जो खर्च किया होगा ");

        return map;
    }
    static Map<String,String> Twelve(){
        HashMap<String,String>map = new HashMap<>();
        map.put("which  will I have been abusing ", "जो मैं गाली दे रहा हूँ ");
        map.put("which  will I have been advising ", "मैं किसकी सलाह दे रहा हूँ ");
        map.put("which  will I have been answering ", "मैं किसका जवाब दे रहा हूँ ");
        map.put("which  will I have been arising ", "मैं कौन सा पैदा कर रहा हूँ ");
        map.put("which  will I have been arriving ", "मैं किससे आ रहा हूँ ");
        map.put("which  will I have been asking ", "मैं किससे पूछ रहा हूँ ");
        map.put("which  will I have been awaking ", "मैं किससे जाग रहा होता ");
        map.put("which  will I have been undefined", "जो मुझे अपरिभाषित किया गया होगा");
        map.put("which  will I have been bearing ", "मैं किसका असर डालूंगा ");
        map.put("which  will I have been beating ", "मैं किसकी पिटाई कर रहा हूँ ");
        map.put("which  will I have been becoming ", "मैं कौन सा बन रहा हूँ ");
        map.put("which  will I have been begging ", "मैं किससे भीख माँगता रहा हूँ ");
        map.put("which  will I have been beginning ", "मैं किसकी शुरुआत कर रहा हूँ ");
        map.put("which  will I have been binding ", "जो मैं बाध्यकारी रहा होगा ");
        map.put("which  will I have been biting ", "मैं किसे काट रहा हूँ ");
        map.put("which  will I have been blessing ", "मैं कौन सा आशीष रहा होगा ");
        map.put("which  will I have been blowing ", "जो मैं उड़ा रहा हूँ ");
        map.put("which  will I have been breaking ", "मैं किसको तोड़ रहा हूँ ");
        map.put("which  will I have been bringing ", "जो मैं ला रहा हूँ ");
        map.put("which  will I have been building ", "मैं किसका निर्माण कर रहा हूँ ");
        map.put("which  will I have been burning ", "मैं किसको जला रहा हूँ ");
        map.put("which  will I have been buying ", "मैं कौन सा खरीद रहा हूँ ");
        map.put("which  will I have been calling ", "मैं किसे कॉल कर रहा हूँ ");
        map.put("which  will I have been carrying ", "मैं किसे ले जा रहा हूँ ");
        map.put("which  will I have been catching ", "मैं किसे पकड़ रहा हूँ ");
        map.put("which  will I have been cheating ", "जो मैं धोखा दे रहा हूँ ");
        map.put("which  will I have been choosing ", "मैं किसे चुन रहा हूँ ");
        map.put("which  will I have been cleaning ", "मैं किसकी सफाई कर रहा हूँ ");
        map.put("which  will I have been climbing ", "मैं किस पर चढ़ रहा हूँ ");
        map.put("which  will I have been closing ", "मैं किसे बंद कर रहा हूँ ");
        map.put("which  will I have been coming ", "मैं कौन आ रहा हूँ ");
        map.put("which  will I have been cooking ", "मैं किसे खाना बना रहा हूँ ");
        map.put("which  will I have been creeping ", "मैं कौन सा रेंग रहा हूँ ");
        map.put("which  will I have been crying ", "मैं किससे रो रहा होता ");
        map.put("which  will I have been cutting ", "मैं किसको काट रहा हूँ ");
        map.put("which  will I have been dancing ", "मैं किससे नाचता रहा हूँ ");
        map.put("which  will I have been dealing ", "मैं किससे निपट रहा हूँ ");
        map.put("which  will I have been dying ", "मैं किससे मर रहा हूँ ");
        map.put("which  will I have been digging ", "मैं किसकी खुदाई कर रहा हूँ ");
        map.put("which  will I have been drawing ", "मैं किसको चित्रित कर रहा हूँ ");
        map.put("which  will I have been drinking ", "मैं कौन पी रहा हूँ ");
        map.put("which  will I have been driving ", "मैं कौन सी गाड़ी चला रहा हूँ ");
        map.put("which  will I have been dropping ", "मैं किसको छोड़ रहा हूँ ");
        map.put("which  will I have been drying ", "मैं किसको सुखा रहा हूँ ");
        map.put("which  will I have been eating ", "मैं कौन सा खा रहा हूँ ");
        map.put("which  will I have been electing ", "मैं किसका चुनाव कर रहा हूँ ");
        map.put("which  will I have been entering ", "मैं किसमें प्रवेश कर रहा हूँ ");
        map.put("which  will I have been falling ", "मैं किससे गिर रहा हूँ ");
        map.put("which  will I have been feeding ", "मैं किसे खिला रहा हूँ ");
        map.put("which  will I have been feeling ", "जो मैं महसूस कर रहा था ");
        map.put("which  will I have been fighting ", "मैं किससे लड़ रहा हूँ ");
        map.put("which  will I have been finding ", "जो मुझे मिल रहा होगा ");
        map.put("which  will I have been fleeing ", "मैं किससे भाग रहा हूँ ");
        map.put("which  will I have been flying ", "मैं किससे उड़ रहा हूँ ");
        map.put("which  will I have been forgetting ", "जो मैं भूल गया होता ");
        map.put("which  will I have been frying ", "मैं कौन सा फ्राइंग कर रहा हूँ ");
        map.put("which  will I have been getting ", "जो मुझे मिल रहा होगा ");
        map.put("which  will I have been giving ", "मैं कौन सा दे रहा हूँ ");
        map.put("which  will I have been going ", "मैं कौन सा जा रहा हूँ ");
        map.put("which  will I have been growing ", "मैं किससे बढ़ रहा हूँ ");
        map.put("which  will I have been hanging ", "मैं किसको लटका रहा हूँ ");
        map.put("which  will I have been hearing ", "जो मैं सुन रहा हूँ ");
        map.put("which  will I have been helping ", "मैं किसकी मदद कर रहा हूँ ");
        map.put("which  will I have been hiding ", "जो मैं छिपा रहा हूँ ");
        map.put("which  will I have been hitting ", "मैं किसको मार रहा हूँ ");
        map.put("which  will I have been holding ", "जो मैं धारण कर रहा हूँ ");
        map.put("which  will I have been hoping ", "मैं किसकी उम्मीद कर रहा था ");
        map.put("which  will I have been hurting ", "मैं किसको चोट पहुँचा रहा हूँ ");
        map.put("which  will I have been jumping ", "मैं किससे कूद रहा हूँ ");
        map.put("which  will I have been keeping ", "जो मैं रख रहा होता ");
        map.put("which  will I have been killing ", "मैं किसको मार रहा हूँ ");
        map.put("which  will I have been knowing ", "जो मुझे पता चल गया होगा ");
        map.put("which  will I have been laughing ", "मैं किससे हँस रहा हूँ ");
        map.put("which  will I have been leading ", "मैं किसकी अगुवाई कर रहा हूँ ");
        map.put("which  will I have been leaping ", "मैं कौन सी छलांग लगा रहा हूँ ");
        map.put("which  will I have been learning ", "मैं कौन सी सीख रहा हूँ ");
        map.put("which  will I have been leaving ", "मैं किसको छोड़ रहा हूँ ");
        map.put("which  will I have been lending ", "मैं कौन सा उधार दे रहा हूँ ");
        map.put("which  will I have been living ", "मैं किससे रह रहा हूँ ");
        map.put("which  will I have been looking ", "जो मैं देख रहा था ");
        map.put("which  will I have been losing ", "मैं किसको खो रहा हूँ ");
        map.put("which  will I have been loving ", "मैं किससे प्यार कर रहा हूँ ");
        map.put("which  will I have been making ", "मैं कौन सा बना रहा हूँ ");
        map.put("which  will I have been marrying ", "मैं किससे शादी कर रहा हूँ ");
        map.put("which  will I have been meeting ", "मैं किससे मिल रहा हूँ ");
        map.put("which  will I have been mistaking ", "मैं किसकी गलती कर रहा हूँ ");
        map.put("which  will I have been opening ", "मैं कौन सा खोल रहा हूँ ");
        map.put("which  will I have been paying ", "मैं किसका भुगतान कर रहा हूँ ");
        map.put("which  will I have been playing ", "मैं कौन सा खेल रहा हूँ ");
        map.put("which  will I have been putting ", "मैं कौन सा लगा रहा हूँ ");
        map.put("which  will I have been quarrelling ", "मैं किससे झगड़ा कर रहा हूँ ");
        map.put("which  will I have been raining ", "मैं किसकी बारिश कर रहा हूँ ");
        map.put("which  will I have been reaching ", "मैं किसतक पहुँच रहा हूँ ");
        map.put("which  will I have been reading ", "जो मैं पढ़ रहा हूँ ");
        map.put("which  will I have been remembering ", "जो मुझे याद आ रहा होगा ");
        map.put("which  will I have been riding ", "मैं किसकी सवारी कर रहा हूँ ");
        map.put("which  will I have been ringing ", "मैं किससे बज रहा हूँ ");
        map.put("which  will I have been rising ", "मैं किससे उठ रहा हूँ ");
        map.put("which  will I have been running ", "मैं कौन सी दौड़ रहा हूँ ");
        map.put("which  will I have been saying ", "जो मैं कह रहा होता ");
        map.put("which  will I have been seeing ", "जो मैं देख रहा हूँ ");
        map.put("which  will I have been selling ", "मैं किसे बेच रहा हूँ ");
        map.put("which  will I have been sending ", "जो मैं भेज रहा हूँ ");
        map.put("which  will I have been shaking ", "मैं किसको हिला रहा हूँ ");
        map.put("which  will I have been shining ", "मैं किससे चमक रहा होता ");
        map.put("which  will I have been shooting ", "मैं किसकी शूटिंग कर रहा हूँ ");
        map.put("which  will I have been showing ", "जो मैं दिखा रहा हूँ ");
        map.put("which  will I have been shutting ", "मैं किसे बंद कर रहा हूँ ");
        map.put("which  will I have been singing ", "मैं कौन सा गा रहा हूँ ");
        map.put("which  will I have been sinking ", "जो मैं डूब रहा हूँ ");
        map.put("which  will I have been teaching ", "मैं किसे सिखा रहा हूँ ");

        return map;
    }


}
