package com.shiviishiv7.helloenglish.QuestionSource;


import java.util.HashMap;
import java.util.Map;

public class Who {
    public static Map<String,String> Who(int state){
        switch (state){
            case 1:return One();
            case 2:return Two();
            case 3:return Three();
            case 4:return Four();
            case 5:return Five();
            case 6:return Six();
            case 7:return Seven();
            case 8:return Eight();
            case 9:return Nine();
            case 10:return Ten();
            case 11:return Eleven();
            case 12:return Twelve();

            default:return One();
        }

    }
    static Map<String,String> One(){
        HashMap<String,String>map = new HashMap<>();
        map.put("Who do I abuse ", "मैं किसके साथ गाली दूं ");
        map.put("Who do I advise", "मैं किसको सलाह दूँ");
        map.put("Who do I answer ", "मैं किसका जवाब दूँ ");
        map.put("Who do I arise ", "मैं कौन उठता हूँ ");
        map.put("Who do I arrive ", "मैं किससे पहुँचूँ ");
        map.put("Who do I ask ", "मैं किससे पूछूँ ");
        map.put("Who do I awake ", "मैं किससे जाग सकता हूँ ");
        map.put("Who do I \r", "मैं कौन करता हूँ \r");
        map.put("Who do I bear ", "मैं किसे सहन करूँ ");
        map.put("Who do I beat ", "मैं किसे हराऊं ");
        map.put("Who do I become ", "मैं कौन बन सकता हूँ ");
        map.put("Who do I beg ", "मैं किससे भीख मांगता हूँ ");
        map.put("Who do I begin ", "मैं किससे शुरू करूँ ");
        map.put("Who do I bind ", "मैं किसको बाँधता हूँ ");
        map.put("Who do I bite", "मैं किसे काटूं");
        map.put("Who do I bless", "मैं किसे आशीर्वाद देता हूँ");
        map.put("Who do I blow ", "मैं किसे उड़ाऊं ");
        map.put("Who do I break ", "मैं किसे तोड़ूँ ");
        map.put("Who do I bring ", "मैं किसे लाऊं ");
        map.put("Who do I build ", "मैं किसका निर्माण करूँ ");
        map.put("Who do I burn ", "मैं किसे जलाता हूँ ");
        map.put("Who do I buy ", "मैं किसे खरीदूं ");
        map.put("Who do I call ", "मैं किसे कॉल करूँ ");
        map.put("Who do I carry ", "मैं किसे ले जाऊं ");
        map.put("Who do I catch ", "मैं किसे पकड़ूँ ");
        map.put("Who do I choose ", "मैं किसे चुनूं ");
        map.put("Who do I clean ", "मैं किसको साफ करूँ ");
        map.put("Who do I climb  ", "मैं किसपर चढ़ूँ  ");
        map.put("Who do I close ", "मैं किसे बंद करूँ ");
        map.put("Who do I come ", "मैं कौन आता हूँ ");
        map.put("Who do I cook ", "मैं किसे खाना बनाती हूँ ");
        map.put("Who do I creep ", "मैं किससे रेंगता हूँ ");
        map.put("Who do I cry ", "मैं किसको रोता हूँ ");
        map.put("Who do I cut ", "मैं किसे काटूं ");
        map.put("Who do I dance ", "मैं कौन नाचता हूँ ");
        map.put("Who do I deal ", "मैं किससे सौदा करता हूँ ");
        map.put("Who do I die ", "मैं कौन मर सकता हूँ ");
        map.put("Who do I dig ", "मैं किसे खोदूँ ");
        map.put("Who do I do ", "मैं कौन करता हूँ ");
        map.put("Who  did I  do ", "मैंने कौन किया ");
        map.put("Who  was I  doing ", "मैं कौन कर रहा था ");
        map.put("Who  had I  done ", "मैंने किसने किया था ");
        map.put("Who  had I been  doing ", "मैं कौन कर रहा था ");
        map.put("Who  will I be doing ", "मैं कौन कर रहा हूँ ");
        map.put("Who  will I have done ", "मैंने कौन किया होगा ");
        map.put("Who  will I have been doing ", "मैं कौन कर रहा हूँ ");
        map.put("Who do I draw ", "मैं किसे आकर्षित करता हूँ ");
        map.put("Who  will I do ", "मैं कौन करूँगा ");
        map.put("Who do I drive ", "मैं किसे चलाऊँ ");
        map.put("Who do I drop ", "मैं किसे छोड़ूँ ");
        map.put("Who do I dry ", "मैं किसे सुखाऊं ");
        map.put("Who do I eat ", "मैं कौन खाऊं ");
        map.put("Who do I elect", "मैं किसका चुनाव करूँ");
        map.put("Who do I fall ", "मैं किससे गिर सकता हूँ ");
        map.put("Who do I feed ", "मैं किसे खिलाऊं ");
        map.put("Who do I feel  ", "मैं कौन महसूस करता हूँ  ");
        map.put("Who do I fight ", "मैं किससे लड़ूं ");
        map.put("Who do I find ", "मुझे कौन मिल सकता है ");
        map.put("Who do I flee ", "मैं किससे भागता हूँ ");
        map.put("Who do I fly  ", "मैं कौन उड़ूँ  ");
        map.put("Who do I forget ", "मैं किसे भूल जाऊं ");
        map.put("Who do I fry ", "मैं किसको भूनूं ");
        map.put("Who do I get  ", "मुझे कौन मिलेगा  ");
        map.put("Who do I give ", "मैं किसे दे सकता हूँ ");
        map.put("Who do I go ", "मैं कौन जाऊँ ");
        map.put("Who do I grow", "मैं कौन उगाऊं");
        map.put("Who do I hang ", "मैं किसे लटकाऊं ");
        map.put("Who do I hear ", "मैं किसे सुनता हूँ ");
        map.put("Who do I help ", "मैं किसकी मदद करूँ ");
        map.put("Who do I hide ", "मैं किसे छिपाऊं ");
        map.put("Who do I hit ", "मैं किसे मारूँ ");
        map.put("Who do I hold ", "मैं किसे पकड़ूँ ");
        map.put("Who do I hope ", "मुझे किसकी उम्मीद है ");
        map.put("Who do I hurt ", "मैं किसे चोट पहुँचूँ ");
        map.put("Who do I jump ", "मैं किससे कूदता हूँ ");
        map.put("Who do I kill ", "मैं किसे मार सकता हूँ ");
        map.put("Who do I know ", "मैं किसे जानता हूँ ");
        map.put("Who do I laugh ", "मैं कौन हँसता हूँ ");
        map.put("Who do I lead ", "मैं किसका नेतृत्व करूँ ");
        map.put("Who do I leap ", "मैं किससे छलांग लगाऊं ");
        map.put("Who do I learn ", "मैं किसे सीखता हूँ ");
        map.put("Who do I leave ", "मैं किसे छोड़ूँ ");
        map.put("Who do I lend ", "मैं किसे उधार दे सकता हूँ ");
        map.put("Who do I live ", "मैं कौन रहता हूँ ");
        map.put("Who do I look ", "मैं किसे देखता हूँ ");
        map.put("Who do I lose ", "मैं किसको खो दूँ ");
        map.put("Who do I love ", "मैं किससे प्यार करता हूँ ");
        map.put("Who do I make ", "मैं किसे बनाऊँ ");
        map.put("Who do I marry ", "मैं किससे शादी करूँ ");
        map.put("Who do I meet ", "मैं किससे मिलूँ ");
        map.put("Who do I mistake ", "मैं किसकी गलती करता हूँ ");
        map.put("Who do I open ", "मैं किसे खोलूं ");
        map.put("Who do I pay  ", "मैं किसे भुगतान करूँ  ");
        map.put("Who do I play ", "मैं कौन खेलूँ ");
        map.put("Who do I put ", "मैं किसे रखूँ ");
        map.put("Who do I rain ", "मैं किससे बारिश करता हूँ ");
        map.put("Who do I reach ", "मैं किसतक पहुँचूँ ");
        map.put("Who do I read", "मैं कौन पढ़ूँ");
        map.put("Who do I remember  ", "मुझे किसे याद है  ");
        map.put("Who do I ride ", "मैं किसकी सवारी करूँ ");
        map.put("Who do I ring ", "मैं किसकी अंगूठी करता हूँ ");
        map.put("Who do I rise  ", "मैं किससे उठूँ  ");
        map.put("Who do I run  ", "मैं कौन दौड़ता हूँ  ");
        map.put("Who do I say ", "मैं कौन कहूँ ");
        map.put("Who do I see ", "मैं किसे देखता हूँ ");
        map.put("Who do I sell ", "मैं किसे बेचूँ ");
        map.put("Who do I send ", "मैं किसे भेजूं ");
        map.put("Who do I shake ", "मैं किसे हिला सकता हूँ ");
        map.put("Who do I shine ", "मैं किसको चमकता हूँ ");
        map.put("Who do I shoot ", "मैं किसको शूट करूँ ");
        map.put("Who do I show ", "मैं किसे दिखाऊं ");
        map.put("Who do I shut  ", "मैं किसे बंद करूँ  ");
        map.put("Who do I sing ", "मैं कौन गाऊं ");
        map.put("Who do I sink ", "मैं किसको डूबता हूँ ");
        map.put("Who do I sleep ", "मैं किसको सोता हूँ ");
        map.put("Who do I smell ", "मुझे किसकी गंध आती है ");

        return map;
    }
    static Map<String,String> Two(){
        HashMap<String,String>map = new HashMap<>();
        map.put("Who am I abusing ", "मैं किसको गाली दे रहा हूँ ");
        map.put("Who am I advising ", "मैं किसको सलाह दे रहा हूँ ");
        map.put("Who am I answering ", "मैं किसका जवाब दे रहा हूँ ");
        map.put("Who am I arising ", "मैं कौन उठ रहा हूँ ");
        map.put("Who am I arriving ", "मैं कौन आ रहा हूँ ");
        map.put("Who am I asking ", "मैं किससे पूछ रहा हूँ ");
        map.put("Who am I awaking ", "मैं कौन जाग रहा हूँ ");
        map.put("Who am I undefined", "मैं अपरिभाषित कौन हूँ");
        map.put("Who am I bearing ", "मैं किसका असर कर रहा हूँ ");
        map.put("Who am I beating ", "मैं किसकी पिटाई कर रहा हूँ ");
        map.put("Who am I becoming ", "मैं कौन बन रहा हूँ ");
        map.put("Who am I begging ", "मैं किससे भीख मांग रहा हूँ ");
        map.put("Who am I beginning ", "मैं कौन हूँ ");
        map.put("Who am I binding ", "मैं बाइंडिंग कौन हूँ ");
        map.put("Who am I biting ", "मैं किसे काट रहा हूँ ");
        map.put("Who am I blessing ", "मैं आशीष कौन हूँ ");
        map.put("Who am I blowing ", "मैं कौन उड़ा रहा हूँ ");
        map.put("Who am I breaking ", "मैं कौन तोड़ रहा हूँ ");
        map.put("Who am I bringing ", "मैं कौन ला रहा हूँ ");
        map.put("Who am I building ", "मैं किसका निर्माण कर रहा हूँ ");
        map.put("Who am I burning ", "मैं कौन जल रहा हूँ ");
        map.put("Who am I buying ", "मैं कौन खरीद रहा हूँ ");
        map.put("Who am I calling ", "मैं किसे बुला रहा हूँ ");
        map.put("Who am I carrying ", "मैं किसे ले जा रहा हूँ ");
        map.put("Who am I catching ", "मैं किसे पकड़ रहा हूँ ");
        map.put("Who am I cheating ", "मैं किसे धोखा दे रहा हूँ ");
        map.put("Who am I choosing ", "मैं किसे चुन रहा हूँ ");
        map.put("Who am I cleaning ", "मैं कौन सफाई कर रहा हूँ ");
        map.put("Who am I climbing ", "मैं कौन चढ़ रहा हूँ ");
        map.put("Who am I closing ", "मैं कौन बंद कर रहा हूँ ");
        map.put("Who am I coming ", "मैं कौन आ रहा हूँ ");
        map.put("Who am I cooking ", "मैं कौन खाना बना रहा हूँ ");
        map.put("Who am I creeping ", "मैं कौन रेंग रहा हूँ ");
        map.put("Who am I crying ", "मैं कौन रो रहा हूँ ");
        map.put("Who am I cutting ", "मैं किसको काट रहा हूँ ");
        map.put("Who am I dancing ", "मैं कौन नाच रहा हूँ ");
        map.put("Who am I dealing ", "मैं कौन काम कर रहा हूँ ");
        map.put("Who am I dying ", "मैं कौन मर रहा हूँ ");
        map.put("Who am I digging ", "मैं कौन खोद रहा हूँ ");
        map.put("Who am I doing ", "मैं कौन कर रहा हूँ ");
        map.put("Who am I drawing ", "मैं किसे आकर्षित कर रहा हूँ ");
        map.put("Who do I dream ", "मैं किसका सपना देखता हूँ ");
        map.put("Who am I dreaming ", "मैं कौन सपना देख रहा हूँ ");
        map.put("Who  have I dreamt ", "मैंने किसका सपना देखा है ");
        map.put("Who  have I been dreaming ", "मैं किसका सपना देख रहा हूँ ");
        map.put("Who  did I  dream ", "मैंने किसने सपना देखा ");
        map.put("Who  was I  dreaming ", "मैं कौन सपना देख रहा था ");
        map.put("Who  had I  dreamt ", "मैंने किसका सपना देखा था ");
        map.put("Who  had I been  dreaming ", "मैं किसका सपना देख रहा था ");
        map.put("Who  will I be dreaming ", "मैं कौन सपना देख रहा हूँ ");
        map.put("Who  will I have dreamt ", "मैंने किसका सपना देखा होगा ");
        map.put("Who  will I have been dreaming ", "मैं कौन सपना देख रहा हूँ ");
        map.put("Who am I drinking ", "मैं कौन पी रहा हूँ ");
        map.put("Who am I driving ", "मैं कौन चला रहा हूँ ");
        map.put("Who am I dropping ", "मैं कौन छोड़ रहा हूँ ");
        map.put("Who am I drying ", "मैं कौन सुखा रहा हूँ ");
        map.put("Who am I eating ", "मैं कौन खा रहा हूँ ");
        map.put("Who am I electing ", "मैं किसका चुनाव कर रहा हूँ ");
        map.put("Who am I entering ", "मैं किसका प्रवेश कर रहा हूँ ");
        map.put("Who am I falling ", "मैं कौन गिर रहा हूँ ");
        map.put("Who am I feeding ", "मैं किसे खिला रहा हूँ ");
        map.put("Who am I feeling ", "मैं कौन महसूस कर रहा हूँ ");
        map.put("Who am I fighting ", "मैं किससे लड़ रहा हूँ ");
        map.put("Who am I finding ", "मुझे कौन मिल रहा है ");
        map.put("Who am I fleeing ", "मैं किससे भाग रहा हूँ ");
        map.put("Who am I flying ", "मैं कौन उड़ रहा हूँ ");
        map.put("Who am I forgetting ", "मैं किसे भूल रहा हूँ ");
        map.put("Who am I frying ", "मैं कौन तलने वाला हूँ ");
        map.put("Who am I getting ", "मुझे कौन मिल रहा है ");
        map.put("Who am I giving ", "मैं कौन दे रहा हूँ ");
        map.put("Who am I going ", "मैं कौन जा रहा हूँ ");
        map.put("Who am I growing ", "मैं कौन बढ़ रहा हूँ ");
        map.put("Who am I hanging ", "मैं कौन लटक रहा हूँ ");
        map.put("Who am I hearing ", "मैं कौन सुन रहा हूँ ");
        map.put("Who am I helping ", "मैं कौन मदद कर रहा हूँ ");
        map.put("Who am I hiding ", "मैं कौन छिपा रहा हूँ ");
        map.put("Who am I hitting ", "मैं किसको मार रहा हूँ ");
        map.put("Who am I holding ", "मैं किसे पकड़ रहा हूँ ");
        map.put("Who am I hoping ", "मैं कौन उम्मीद कर रहा हूँ ");
        map.put("Who am I hurting ", "मैं किसको चोट पहुँचा रहा हूँ ");
        map.put("Who am I jumping ", "मैं कौन कूद रहा हूँ ");
        map.put("Who am I keeping ", "मैं कौन रख रहा हूँ ");
        map.put("Who am I killing ", "मैं किसको मार रहा हूँ ");
        map.put("Who am I knowing ", "मैं किसे जान रहा हूँ ");
        map.put("Who am I laughing ", "मैं कौन हँस रहा हूँ ");
        map.put("Who am I leading ", "मैं किसका नेतृत्व कर रहा हूँ ");
        map.put("Who am I leaping ", "मैं कौन छलांग लगा रहा हूँ ");
        map.put("Who am I learning ", "मैं कौन सीख रहा हूँ ");
        map.put("Who am I leaving ", "मैं कौन जा रहा हूँ ");
        map.put("Who am I lending ", "मैं कौन उधार दे रहा हूँ ");
        map.put("Who am I living ", "मैं कौन रह रहा हूँ ");
        map.put("Who am I looking ", "मैं कौन देख रहा हूँ ");
        map.put("Who am I losing ", "मैं कौन खो रहा हूँ ");
        map.put("Who am I loving ", "मैं कौन प्यार कर रहा हूँ ");
        map.put("Who am I making ", "मैं कौन बना रहा हूँ ");
        map.put("Who am I marrying ", "मैं किससे शादी कर रहा हूँ ");
        map.put("Who am I meeting ", "मैं किससे मिल रहा हूँ ");
        map.put("Who am I mistaking ", "मैं किसकी गलती कर रहा हूँ ");
        map.put("Who am I opening ", "मैं कौन खोल रहा हूँ ");
        map.put("Who am I paying ", "मैं किसका भुगतान कर रहा हूँ ");
        map.put("Who am I playing ", "मैं कौन खेल रहा हूँ ");
        map.put("Who am I putting ", "मैं कौन डाल रहा हूँ ");
        map.put("Who am I quarrelling ", "मैं कौन झगड़ा कर रहा हूँ ");
        map.put("Who am I raining ", "मैं बारिश कौन कर रहा हूँ ");
        map.put("Who am I reaching ", "मैं किसतक पहुँच रहा हूँ ");
        map.put("Who am I reading ", "मैं कौन पढ़ रहा हूँ ");
        map.put("Who am I remembering ", "मैं किसे याद कर रहा हूँ ");
        map.put("Who am I riding ", "मैं कौन सवारी कर रहा हूँ ");
        map.put("Who am I ringing ", "मैं कौन बज रहा हूँ ");
        map.put("Who am I rising ", "मैं कौन उठ रहा हूँ ");
        map.put("Who am I running ", "मैं कौन दौड़ रहा हूँ ");
        map.put("Who am I saying ", "मैं कौन कह रहा हूँ ");
        map.put("Who am I seeing ", "मैं किसे देख रहा हूँ ");
        map.put("Who am I selling ", "मैं किसे बेच रहा हूँ ");
        map.put("Who am I sending ", "मैं किसे भेज रहा हूँ ");
        map.put("Who am I shaking ", "मैं किसको हिला रहा हूँ ");
        map.put("Who am I shining ", "मैं कौन चमक रहा हूँ ");
        map.put("Who am I shooting ", "मैं कौन शूटिंग कर रहा हूँ ");
        map.put("Who am I showing ", "मैं कौन दिखा रहा हूँ ");
        map.put("Who am I shutting ", "मैं किसे बंद कर रहा हूँ ");
        map.put("Who am I singing ", "मैं कौन गा रहा हूँ ");
        map.put("Who am I sinking ", "मैं कौन डूब रहा हूँ ");
        map.put("Who am I sleeping ", "मैं कौन सो रहा हूँ ");
        map.put("Who am I smelling ", "मैं किससे सूँघ रहा हूँ ");

        return map;
    }
    static Map<String,String> Three(){
        HashMap<String,String>map = new HashMap<>();
        map.put("Who  have I abused ", "मैंने किसके साथ दुर्व्यवहार किया है ");
        map.put("Who  have I advised ", "मैंने किसको सलाह दी है ");
        map.put("Who  have I answered ", "मैंने किसका उत्तर दिया है ");
        map.put("Who  have I arisen ", "मैं किसने पैदा किया है ");
        map.put("Who  have I arrived ", "मैं किससे आया हूँ ");
        map.put("Who  have I asked ", "मैंने किससे पूछा है ");
        map.put("Who  have I awoken ", "मैं किससे जाग गया हूँ ");
        map.put("Who  have I undefined", "मैंने किसको अपरिभाषित किया है");
        map.put("Who  have I borne ", "मैंने किसको जन्म दिया है ");
        map.put("Who  have I beaten ", "मैंने किसको पीटा है ");
        map.put("Who  have I become ", "मैं कौन बन गया हूँ ");
        map.put("Who  have I begged ", "मैंने किससे भीख माँगी ");
        map.put("Who  have I begun ", "मैंने किसकी शुरुआत की है ");
        map.put("Who  have I bound ", "मैंने किससे बाध्य किया है ");
        map.put("Who  have I bitten ", "मैंने किसको काट लिया है ");
        map.put("Who  have I blessed ", "मैंने किसको आशीर्वाद दिया है ");
        map.put("Who  have I blown ", "मैंने किसको उड़ा दिया है ");
        map.put("Who  have I broken ", "मैंने किसको तोड़ा है ");
        map.put("Who  have I brought ", "मैं किसे लाया हूँ ");
        map.put("Who  have I built ", "मैंने किसने बनाया है ");
        map.put("Who  have I burnt ", "मैंने किसको जला दिया है ");
        map.put("Who  have I bought ", "मैंने किसे खरीदा है ");
        map.put("Who  have I called ", "मैंने किसे फोन किया है ");
        map.put("Who  have I carried ", "मैंने किसे किया है ");
        map.put("Who  have I caught ", "मैंने किसे पकड़ा है ");
        map.put("Who  have I cheated ", "मैंने किसने धोखा दिया है ");
        map.put("Who  have I chosen ", "मैंने किसे चुना है ");
        map.put("Who  have I cleaned ", "मैंने किसको साफ किया है ");
        map.put("Who  have I climbed ", "मैं कौन चढ़ गया ");
        map.put("Who  have I closed ", "मैंने किसे बंद किया है ");
        map.put("Who  have I come ", "मैं कौन आया हूँ ");
        map.put("Who  have I cooked ", "मैंने किसको पकाया है ");
        map.put("Who  have I crept ", "मैंने किसने क्रेप्ट किया है ");
        map.put("Who  have I cried ", "मैंने किसको रोया है ");
        map.put("Who  have I cut ", "मैंने किसको काट दिया है ");
        map.put("Who  have I danced ", "मैंने किसने नृत्य किया है ");
        map.put("Who  have I dealt ", "मैंने किससे निपटा है ");
        map.put("Who  have I died ", "मैं किसकी मर चुका हूँ ");
        map.put("Who  have I dug ", "मैंने किसने खोदा है ");
        map.put("Who  have I done ", "मैंने किसने किया है ");
        map.put("Who  have I drawn ", "मैंने किसने खींचा है ");
        map.put("Who  have I drunk ", "मैंने किसने पिया है ");
        map.put("Who  have I driven ", "मैंने किसको चलाया है ");
        map.put("Who  have I dropped ", "मैंने किसको गिरा दिया है ");
        map.put("Who  have I dried ", "मैंने किसको सुखाया है ");
        map.put("Who  have I eaten ", "मैंने किसने खाया है ");
        map.put("Who  have I elected ", "मैंने किसे चुना है ");
        map.put("Who  have I entered ", "मैंने किसमें प्रवेश किया है ");
        map.put("Who  have I fallen ", "मैं कौन गिर गया हूँ ");
        map.put("Who  have I fed ", "मैंने किसको खिलाया है ");
        map.put("Who  have I felt ", "मैंने किसने महसूस किया है ");
        map.put("Who  have I fought ", "मैंने किससे लड़ाई लड़ी है ");
        map.put("Who  have I found ", "मैंने किसे पाया है ");
        map.put("Who  have I fled ", "मैं किससे भाग गया ");
        map.put("Who  have I flown ", "मैंने किसको उड़ाया है ");
        map.put("Who  have I forgotten ", "मैं किसे भूल गया हूँ ");
        map.put("Who  have I fried ", "मैंने किसने फ्राई किया है ");
        map.put("Who  have I got ", "मुझे कौन मिला है ");
        map.put("Who  have I given ", "मैंने किसे दिया है ");
        map.put("Who  have I gone ", "मैं कौन गया हूँ ");
        map.put("Who  have I grown ", "मैं कौन हो गया हूँ ");
        map.put("Who  have I hanged ", "मैंने किसको फांसी दी है ");
        map.put("Who  have I hung ", "मैंने किसको लटका दिया है ");
        map.put("Who  have I heard ", "मैंने किसने सुना है ");
        map.put("Who  have I helped ", "मैंने किसकी मदद की है ");
        map.put("Who  have I hidden ", "मैंने किसको छुपाया है ");
        map.put("Who  have I hit ", "मैंने किसको मारा है ");
        map.put("Who  have I held ", "मैंने किसके पास रखा है ");
        map.put("Who  have I hoped ", "मैंने किसकी उम्मीद की है ");
        map.put("Who  have I hurt ", "मुझे किसने चोट पहुंचाई है ");
        map.put("Who  have I jumped ", "मैं किससे कूद गया हूँ ");
        map.put("Who  have I kept ", "मैंने किसे रखा है ");
        map.put("Who  have I killed ", "मैंने किसको मार डाला है ");
        map.put("Who  have I known ", "मैंने किसे जाना है ");
        map.put("Who  have I laughed ", "मैं किसने हँसा है ");
        map.put("Who  have I led ", "मैंने किसका नेतृत्व किया है ");
        map.put("Who  have I leapt ", "मैंने किसने छलांग लगाई है ");
        map.put("Who  have I learnt ", "मैंने किससे सीखा है ");
        map.put("Who  have I left ", "मैंने किसको छोड़ा है ");
        map.put("Who  have I lent ", "मैंने किसे उधार दिया है ");
        map.put("Who  have I lived ", "मैं किसके पास रहता हूँ ");
        map.put("Who  have I looked ", "मैंने किसको देखा है ");
        map.put("Who  have I lost ", "मैंने कौन खो दिया है ");
        map.put("Who  have I loved ", "मैंने किससे प्यार किया है ");
        map.put("Who  have I made ", "मैंने किसने बनाया है ");
        map.put("Who  have I married ", "मैंने किससे शादी की है ");
        map.put("Who  have I met ", "मैं किससे मिला हूँ ");
        map.put("Who  have I mistaken ", "मैंने किससे गलत किया है ");
        map.put("Who  have I opened ", "मैंने किसे खोला है ");
        map.put("Who  have I paid ", "मैंने किसका भुगतान किया है ");
        map.put("Who  have I played ", "मैंने किसने खेला है ");
        map.put("Who  have I put ", "मैंने किसने रखा है ");
        map.put("Who  have I quarrelled ", "मैंने किससे झगड़ा किया ");
        map.put("Who  have I rained ", "मैंने किसकी बारिश की ");
        map.put("Who  have I reached ", "मैं किसके पास पहुँचा हूँ ");
        map.put("Who  have I read ", "मैंने किसने पढ़ा है ");
        map.put("Who  have I remembered ", "मैंने किसे याद किया ");
        map.put("Who  have I ridden ", "मैंने किसकी सवारी की है ");
        map.put("Who  have I rung ", "मैंने किसको बजाया है ");
        map.put("Who  have I risen ", "मैं कौन उठ गया हूँ ");
        map.put("Who  have I run ", "मैंने किसको चलाया है ");
        map.put("Who  have I said ", "मैंने किसने कहा है ");
        map.put("Who  have I seen ", "मैंने किसने देखा है ");
        map.put("Who  have I sold ", "मैंने किसे बेचा है ");
        map.put("Who  have I sent ", "मैंने किसे भेजा है ");
        map.put("Who  have I shaken ", "मैंने किसको हिला दिया है ");
        map.put("Who  have I shone ", "मैंने किसको चमक दिया है ");
        map.put("Who  have I shot ", "मैंने किसने गोली मार दी है ");
        map.put("Who  have I shown ", "मैंने किसे दिखाया है ");
        map.put("Who  have I shut ", "मैंने किसको बंद किया है ");
        map.put("Who  have I sung ", "मैंने किसने गाया है ");
        map.put("Who  have I sunk ", "मैं किससे डूब गया हूँ ");
        map.put("Who  have I slept ", "मैं किससे सोया हूँ ");
        map.put("Who  have I smelt ", "मैंने किसको पिघलाया है ");
        map.put("Who  have I worn ", "मैंने किसने पहना है ");

        return map;
    }
    static Map<String,String> Four(){
        HashMap<String,String>map = new HashMap<>();
        map.put("Who  have I been abusing ", "मैं किससे गाली दे रहा हूँ ");
        map.put("Who  have I been advising ", "मैं किसको सलाह दे रहा हूँ ");
        map.put("Who  have I been answering ", "मैं किसका जवाब दे रहा हूं ");
        map.put("Who  have I been arising ", "मैं किससे उठ रहा हूँ ");
        map.put("Who  have I been arriving ", "मैं किससे आ रहा हूँ ");
        map.put("Who  have I been asking ", "मैं किससे पूछ रहा हूँ ");
        map.put("Who  have I been awaking ", "मैं किससे जाग रहा हूँ ");
        map.put("Who  have I been undefined", "मैं किससे अपरिभाषित हो गया हूँ");
        map.put("Who  have I been bearing ", "मैं किसका असर कर रहा हूँ ");
        map.put("Who  have I been beating ", "मैं किसकी पिटाई कर रहा हूँ ");
        map.put("Who  have I been becoming ", "मैं कौन बन रहा हूँ ");
        map.put("Who  have I been begging ", "मैं किससे भीख माँग रहा हूँ ");
        map.put("Who  have I been beginning ", "मैं किसकी शुरुआत कर रहा हूँ ");
        map.put("Who  have I been binding ", "मैं किससे बाध्यकारी रहा हूँ ");
        map.put("Who  have I been biting ", "मैं किसे काट रहा हूँ ");
        map.put("Who  have I been blessing ", "मैं कौन आशीष रहा हूँ ");
        map.put("Who  have I been blowing ", "मैं किससे उड़ा रहा हूँ ");
        map.put("Who  have I been breaking ", "मैं किसको तोड़ रहा हूँ ");
        map.put("Who  have I been bringing ", "मैं किसको ला रहा हूँ ");
        map.put("Who  have I been building ", "मैं किसका निर्माण कर रहा हूँ ");
        map.put("Who  have I been burning ", "मैं किससे जल रहा हूँ ");
        map.put("Who  have I been buying ", "मैं किसे खरीद रहा हूँ ");
        map.put("Who  have I been calling ", "मैं किसे बुला रहा हूँ ");
        map.put("Who  have I been carrying ", "मैं किसे ले जा रहा हूँ ");
        map.put("Who  have I been catching ", "मैं किसे पकड़ रहा हूँ ");
        map.put("Who  have I been cheating ", "मैं किसे धोखा दे रहा हूँ ");
        map.put("Who  have I been choosing ", "मैं किसे चुन रहा हूँ ");
        map.put("Who  have I been cleaning ", "मैं किसकी सफाई कर रहा हूँ ");
        map.put("Who  have I been climbing ", "मैं किसपर चढ़ रहा हूँ ");
        map.put("Who  have I been closing ", "मैं किसे बंद कर रहा हूँ ");
        map.put("Who  have I been coming ", "मैं कौन आ रहा हूँ ");
        map.put("Who  have I been cooking ", "मैं किससे खाना बना रहा हूँ ");
        map.put("Who  have I been creeping ", "मैं किससे रेंग रहा हूँ ");
        map.put("Who  have I been crying ", "मैं किससे रो रहा हूँ ");
        map.put("Who  have I been cutting ", "मैं किसको काट रहा हूँ ");
        map.put("Who  have I been dancing ", "मैं कौन नाच रहा हूँ ");
        map.put("Who  have I been dealing ", "मैं किससे काम कर रहा हूँ ");
        map.put("Who  have I been dying ", "मैं कौन मर रहा हूँ ");
        map.put("Who  have I been digging ", "मैं किसकी खुदाई कर रहा हूँ ");
        map.put("Who  have I been doing ", "मैं कौन कर रहा हूँ ");
        map.put("Who  have I been drawing ", "मैं किसको चित्रित कर रहा हूँ ");
        map.put("Who  have I been drinking ", "मैं कौन पी रहा हूँ ");
        map.put("Who  have I been driving ", "मैं कौन चला रहा हूँ ");
        map.put("Who  have I been dropping ", "मैं किसको छोड़ रहा हूँ ");
        map.put("Who  have I been drying ", "मैं किसको सुखा रहा हूँ ");
        map.put("Who  have I been eating ", "मैं कौन खा रहा हूँ ");
        map.put("Who  have I been electing ", "मैं किसका चुनाव कर रहा हूँ ");
        map.put("Who  have I been entering ", "मैं किसमें प्रवेश कर रहा हूँ ");
        map.put("Who  have I been falling ", "मैं किससे गिर रहा हूँ ");
        map.put("Who  have I been feeding ", "मैं किसे खिला रहा हूँ ");
        map.put("Who  have I been feeling ", "मैं कौन महसूस कर रहा हूँ ");
        map.put("Who  have I been fighting ", "मैं किससे लड़ रहा हूँ ");
        map.put("Who  have I been finding ", "मुझे कौन मिल रहा है ");
        map.put("Who  have I been fleeing ", "मैं किससे भाग रहा हूँ ");
        map.put("Who  have I been flying ", "मैं किससे उड़ रहा हूँ ");
        map.put("Who  have I been forgetting ", "मैं किसे भूल रहा हूँ ");
        map.put("Who  have I been frying ", "मैं कौन तलने गया हूँ ");
        map.put("Who  have I been getting ", "मुझे कौन मिल रहा है ");
        map.put("Who  have I been giving ", "मैं कौन दे रहा हूँ ");
        map.put("Who  have I been going ", "मैं कौन जा रहा हूँ ");
        map.put("Who  have I been growing ", "मैं किससे बढ़ रहा हूँ ");
        map.put("Who  have I been hanging ", "मैं किससे लटक रहा हूँ ");
        map.put("Who  have I been hearing ", "मैं किससे सुन रहा हूँ ");
        map.put("Who  have I been helping ", "मैं किसकी मदद कर रहा हूँ ");
        map.put("Who  have I been hiding ", "मैं किसको छिपा रहा हूँ ");
        map.put("Who  have I been hitting ", "मैं किसको मार रहा हूँ ");
        map.put("Who  have I been holding ", "मैं किसे पकड़ रहा हूँ ");
        map.put("Who  have I been hoping ", "मैं किसकी उम्मीद कर रहा था ");
        map.put("Who  have I been hurting ", "मैं किसको चोट पहुँचा रहा हूँ ");
        map.put("Who  have I been jumping ", "मैं किससे कूद रहा हूँ ");
        map.put("Who  have I been keeping ", "मैं किसे रख रहा हूँ ");
        map.put("Who  have I been killing ", "मैं किसको मार रहा हूँ ");
        map.put("Who  have I been knowing ", "मैं किसे जानता था ");
        map.put("Who  have I been laughing ", "मैं किससे हँस रहा हूँ ");
        map.put("Who  have I been leading ", "मैं किसका नेतृत्व कर रहा हूँ ");
        map.put("Who  have I been leaping ", "मैं किससे छलांग लगा रहा हूँ ");
        map.put("Who  have I been learning ", "मैं किससे सीख रहा हूँ ");
        map.put("Who  have I been leaving ", "मैं किससे जा रहा हूँ ");
        map.put("Who  have I been lending ", "मैं किसे उधार दे रहा हूँ ");
        map.put("Who  have I been living ", "मैं कौन रह रहा हूँ ");
        map.put("Who  have I been looking ", "मैं किसे देख रहा हूँ ");
        map.put("Who  have I been losing ", "मैं किसको खो रहा हूँ ");
        map.put("Who  have I been loving ", "मैं किससे प्यार कर रहा हूँ ");
        map.put("Who  have I been making ", "मैं कौन बना रहा हूँ ");
        map.put("Who  have I been marrying ", "मैं किससे शादी कर रहा हूँ ");
        map.put("Who  have I been meeting ", "मैं किससे मिल रहा हूँ ");
        map.put("Who  have I been mistaking ", "मैं किससे गलत कर रहा हूँ ");
        map.put("Who  have I been opening ", "मैं किसे खोल रहा हूँ ");
        map.put("Who  have I been paying ", "मैं किसका भुगतान कर रहा हूँ ");
        map.put("Who  have I been playing ", "मैं कौन खेल रहा हूँ ");
        map.put("Who  have I been putting ", "मैं किसको लगा रहा हूँ ");
        map.put("Who  have I been quarrelling ", "मैं किससे झगड़ा कर रहा हूँ ");
        map.put("Who  have I been raining ", "मैं किसकी बारिश कर रहा हूँ ");
        map.put("Who  have I been reaching ", "मैं किसतक पहुँच रहा हूँ ");
        map.put("Who  have I been reading ", "मैं किसे पढ़ रहा हूँ ");
        map.put("Who  have I been remembering ", "मैं किसे याद कर रहा हूँ ");
        map.put("Who  have I been riding ", "मैं किसकी सवारी कर रहा हूँ ");
        map.put("Who  have I been ringing ", "मैं किससे बज रहा हूँ ");
        map.put("Who  have I been rising ", "मैं किससे उठ रहा हूँ ");
        map.put("Who  have I been running ", "मैं किससे दौड़ रहा हूँ ");
        map.put("Who  have I been saying ", "मैं कौन कह रहा हूँ ");
        map.put("Who  have I been seeing ", "मैं किसे देख रहा हूँ ");
        map.put("Who  have I been selling ", "मैं किसे बेच रहा हूँ ");
        map.put("Who  have I been sending ", "मैं किसे भेज रहा हूँ ");
        map.put("Who  have I been shaking ", "मैं किसको हिला रहा हूँ ");
        map.put("Who  have I been shining ", "मैं किससे चमक रहा हूँ ");
        map.put("Who  have I been shooting ", "मैं किसकी शूटिंग कर रहा हूँ ");
        map.put("Who  have I been showing ", "मैं किसे दिखा रहा हूँ ");
        map.put("Who  have I been shutting ", "मैं किसे बंद कर रहा हूँ ");
        map.put("Who  have I been singing ", "मैं कौन गा रहा हूँ ");
        map.put("Who  have I been sinking ", "मैं किससे डूब रहा हूँ ");
        map.put("Who  have I been sleeping ", "मैं किससे सो रहा हूँ ");
        map.put("Who  have I been smelling ", "मैं किससे सूँघ रहा हूँ ");
        map.put("Who  have I been teaching ", "मैं किसे सिखा रहा हूँ ");

        return map;
    }
    static Map<String,String> Five(){
        HashMap<String,String>map = new HashMap<>();
        map.put("Who  did I  abuse ", "मैंने किसने गाली दी ");
        map.put("Who  did I  advise", "मैंने किसको सलाह दी");
        map.put("Who  did I  answer ", "मैंने किसका जवाब दिया ");
        map.put("Who  did I  arise ", "मैं कौन उठ गया ");
        map.put("Who  did I  arrive ", "मैं कौन आया ");
        map.put("Who  did I  ask ", "मैंने किससे पूछा ");
        map.put("Who  did I  awake ", "मैंने किसने जगाया ");
        map.put("Who  did I  \r", "मैंने किसने किया  \r");
        map.put("Who  did I  beat ", "मैंने किसे हराया ");
        map.put("Who  did I  become ", "मैं कौन बन गया ");
        map.put("Who  did I  beg ", "मैंने किससे भीख माँगी ");
        map.put("Who  did I  begin ", "मैंने किसने शुरू किया ");
        map.put("Who  did I  bind ", "मैंने किसने बाँध दिया ");
        map.put("Who  did I  bite", "मैंने किसको काट दिया");
        map.put("Who  did I  bless", "मैंने किसने आशीर्वाद दिया");
        map.put("Who  did I  blow ", "मैंने किसने उड़ाया ");
        map.put("Who  did I  break ", "मैंने किसने तोड़ा ");
        map.put("Who  did I  bring ", "मैं किसको ले आया ");
        map.put("Who  did I  build ", "मैंने किसका निर्माण किया ");
        map.put("Who  did I  burn ", "मैंने किसको जला दिया ");
        map.put("Who  did I  buy ", "मैंने किसे खरीदा ");
        map.put("Who  did I  call ", "मैंने किसे फोन किया ");
        map.put("Who  did I  carry ", "मैंने किसको ले जाना था ");
        map.put("Who  did I  catch ", "मैंने किसे पकड़ लिया ");
        map.put("Who  did I  cheat ", "मैंने किसने धोखा दिया ");
        map.put("Who  did I  choose ", "मैंने किसे चुना ");
        map.put("Who  did I  clean ", "मैंने किसको साफ किया ");
        map.put("Who  did I  climb  ", "मैं किसपर चढ़ गया  ");
        map.put("Who  did I  close ", "मैंने किसने बंद किया ");
        map.put("Who  did I  come ", "मैं कौन आया ");
        map.put("Who  did I  cook ", "मैंने किसने खाना बनाया ");
        map.put("Who  did I  creep ", "मैं किसने रेंगना था ");
        map.put("Who  did I  cut ", "मैंने किसको काट दिया ");
        map.put("Who  did I  dance ", "मैंने किसने नृत्य किया ");
        map.put("Who  did I  deal ", "मैंने किसने सौदा किया ");
        map.put("Who  did I  die ", "मैं कौन मर गया ");
        map.put("Who  did I  dig ", "मैंने किसने खोदा ");
        map.put("Who  did I  draw ", "मैंने किसने ड्रॉ किया ");
        map.put("Who  did I  drive ", "मैंने किसने ड्राइव किया ");
        map.put("Who  did I  drop ", "मैंने किसको छोड़ दिया ");
        map.put("Who  did I  dry ", "मैंने किसने सुखाया ");
        map.put("Who  did I  eat ", "मैंने कौन खाया ");
        map.put("Who  did I  elect", "मैंने किसका चुनाव किया");
        map.put("Who  did I  enter ", "मैंने किसमें प्रवेश किया ");
        map.put("Who  did I  fall ", "मैं कौन गिर गया ");
        map.put("Who  did I  feed ", "मैंने किसे खाना खिलाया ");
        map.put("Who  did I  feel  ", "मैंने कौन महसूस किया  ");
        map.put("Who  did I  fight ", "मैंने किससे लड़ाई की ");
        map.put("Who  did I  find ", "मुझे कौन मिला ");
        map.put("Who  did I  flee ", "मैं किससे भागा ");
        map.put("Who  did I  fly  ", "मैंने किसने उड़ाया  ");
        map.put("Who  did I  fry ", "मैंने फ्राई किसने किया ");
        map.put("Who  did I  get  ", "मुझे कौन मिला  ");
        map.put("Who  did I  give ", "मैंने किसे दिया ");
        map.put("Who  did I  go ", "मैं कौन गया ");
        map.put("Who  did I  grow", "मैं किसने उगाया");
        map.put("Who  did I  hang ", "मैंने किसने लटका दिया ");
        map.put("Who  did I  hear ", "मैंने किसने सुना ");
        map.put("Who  did I  help ", "मैंने किसकी मदद की ");
        map.put("Who  did I  hide ", "मैंने किसने छिपाया ");
        map.put("Who  did I  hit ", "मैंने किसने मारा ");
        map.put("Who  did I  hold ", "मैंने किसे पकड़ लिया था ");
        map.put("Who  did I  hope ", "मुझे किसकी उम्मीद थी ");
        map.put("Who  did I  hurt ", "मैंने किसको चोट पहुंचाई ");
        map.put("Who  did I  jump ", "मैंने किसने छलांग लगाई ");
        map.put("Who  did I  keep ", "मैंने किसे रखा ");
        map.put("Who  did I  kill ", "मैंने किसको मार डाला ");
        map.put("Who  did I  know ", "मुझे किसे पता था ");
        map.put("Who  did I  laugh ", "मैं किसने हँसा था ");
        map.put("Who  did I  lead ", "मैंने किसका नेतृत्व किया ");
        map.put("Who  did I  leap ", "मैंने किसने छलांग लगाई ");
        map.put("Who  did I  learn ", "मैंने किसने सीखा ");
        map.put("Who  did I  leave ", "मैंने किसको छोड़ा ");
        map.put("Who  did I  live ", "मैं कौन रहता था ");
        map.put("Who  did I  look ", "मैंने किसको देखा ");
        map.put("Who  did I  lose ", "मैंने किसको खो दिया ");
        map.put("Who  did I  love ", "मैंने किससे प्यार किया ");
        map.put("Who  did I  make ", "मैंने किसको बनाया ");
        map.put("Who  did I  marry ", "मैंने किससे शादी की ");
        map.put("Who  did I  meet ", "मैं किससे मिला ");
        map.put("Who  did I  mistake ", "मैंने किससे गलती की ");
        map.put("Who  did I  open ", "मैंने किसको खोल दिया ");
        map.put("Who  did I  pay  ", "मैंने किसे भुगतान किया  ");
        map.put("Who  did I  play ", "मैंने किसको बजाया ");
        map.put("Who  did I  put ", "मैंने किसने रखा ");
        map.put("Who  did I  quarrel ", "मैंने झगड़ा किसने किया ");
        map.put("Who  did I  rain ", "मैंने बारिश किसकी ");
        map.put("Who  did I  reach ", "मैं किसके पास पहुँचा ");
        map.put("Who  did I  read", "मैंने किसने पढ़ा");
        map.put("Who  did I  remember  ", "मुझे कौन याद आया  ");
        map.put("Who  did I  ride ", "मैंने किसकी सवारी की ");
        map.put("Who  did I  ring ", "मैंने किसने रिंग किया ");
        map.put("Who  did I  rise  ", "मैं किससे उठ गया  ");
        map.put("Who  did I  say ", "मैंने किसने कहा ");
        map.put("Who  did I  see ", "मैंने किसने देखा ");
        map.put("Who  did I  sell ", "मैंने किसे बेच दिया ");
        map.put("Who  did I  send ", "मैंने किसे भेजा ");
        map.put("Who  did I  shake ", "मैंने किसको हिला दिया ");
        map.put("Who  did I  shine ", "मैंने किसको चमकाया ");
        map.put("Who  did I  shoot ", "मैंने किसने शूट किया ");
        map.put("Who  did I  show ", "मैंने किसे दिखाया ");
        map.put("Who  did I  shut  ", "मैंने किसने बंद किया  ");
        map.put("Who  did I  sing ", "मैंने किसने गाया था ");
        map.put("Who  did I  sink ", "मैंने किसको डुबो दिया ");
        map.put("Who  did I  sleep ", "मैं किससे सोता था ");
        map.put("Who  did I  smell ", "मैंने किससे सूंघा ");
        map.put("Who  did I  study ", "मैंने किसका अध्ययन किया ");

        return map;
    }
    static Map<String,String> Six(){
        HashMap<String,String>map = new HashMap<>();
        map.put("Who  was I  abusing ", "मैं किसको गाली दे रहा था ");
        map.put("Who  was I  advising ", "मैं किसको सलाह दे रहा था ");
        map.put("Who  was I  answering ", "मैं किसका जवाब दे रहा था ");
        map.put("Who  was I  arising ", "मैं कौन पैदा हो रहा था ");
        map.put("Who  was I  arriving ", "मैं कौन आ रहा था ");
        map.put("Who  was I  asking ", "मैं किससे पूछ रहा था ");
        map.put("Who  was I  awaking ", "मैं कौन जाग रहा था ");
        map.put("Who  was I  undefined", "मैं अपरिभाषित कौन था");
        map.put("Who  was I  bearing ", "मैं किसका असर कर रहा था ");
        map.put("Who  was I  beating ", "मैं किसकी पिटाई कर रहा था ");
        map.put("Who  was I  becoming ", "मैं कौन बन रहा था ");
        map.put("Who  was I  begging ", "मैं किससे भीख मांग रहा था ");
        map.put("Who  was I  beginning ", "मैं कौन शुरू कर रहा था ");
        map.put("Who  was I  binding ", "मैं बाध्यकारी कौन था ");
        map.put("Who  was I  biting ", "मैं किसे काट रहा था ");
        map.put("Who  was I  blessing ", "मैं आशीर्वाद कौन था ");
        map.put("Who  was I  blowing ", "मैं कौन उड़ा रहा था ");
        map.put("Who  was I  breaking ", "मैं कौन तोड़ रहा था ");
        map.put("Who  was I  bringing ", "मैं कौन ला रहा था ");
        map.put("Who  was I  building ", "मैं किसका निर्माण कर रहा था ");
        map.put("Who  was I  burning ", "मैं कौन जल रहा था ");
        map.put("Who  was I  buying ", "मैं कौन खरीद रहा था ");
        map.put("Who  was I  calling ", "मैं किसे बुला रहा था ");
        map.put("Who  was I  carrying ", "मैं किसे ले जा रहा था ");
        map.put("Who  was I  catching ", "मैं किसे पकड़ रहा था ");
        map.put("Who  was I  cheating ", "मैं किसे धोखा दे रहा था ");
        map.put("Who  was I  choosing ", "मैं किसे चुन रहा था ");
        map.put("Who  was I  cleaning ", "मैं कौन सफाई कर रहा था ");
        map.put("Who  was I  climbing ", "मैं कौन चढ़ रहा था ");
        map.put("Who  was I  closing ", "मैं कौन बंद कर रहा था ");
        map.put("Who  was I  coming ", "मैं कौन आ रहा था ");
        map.put("Who  was I  cooking ", "मैं कौन खाना बना रहा था ");
        map.put("Who  was I  creeping ", "मैं कौन रेंग रहा था ");
        map.put("Who  was I  crying ", "मैं कौन रो रहा था ");
        map.put("Who  was I  cutting ", "मैं किसको काट रहा था ");
        map.put("Who  was I  dancing ", "मैं कौन नाच रहा था ");
        map.put("Who  was I  dealing ", "मैं कौन काम कर रहा था ");
        map.put("Who  was I  dying ", "मैं कौन मर रहा था ");
        map.put("Who  was I  digging ", "मैं किसको खोद रहा था ");
        map.put("Who  was I  drawing ", "मैं किसे आकर्षित कर रहा था ");
        map.put("Who  was I  drinking ", "मैं कौन पी रहा था ");
        map.put("Who  was I  driving ", "मैं कौन चला रहा था ");
        map.put("Who  was I  dropping ", "मैं किसको छोड़ रहा था ");
        map.put("Who  was I  drying ", "मैं कौन सूख रहा था ");
        map.put("Who  was I  eating ", "मैं कौन खा रहा था ");
        map.put("Who  was I  electing ", "मैं किसका चुनाव कर रहा था ");
        map.put("Who  was I  entering ", "मैं किसका प्रवेश कर रहा था ");
        map.put("Who  was I  falling ", "मैं कौन गिर रहा था ");
        map.put("Who  was I  feeding ", "मैं किसे खिला रहा था ");
        map.put("Who  was I  feeling ", "मैं कौन महसूस कर रहा था ");
        map.put("Who  was I  fighting ", "मैं किससे लड़ रहा था ");
        map.put("Who  was I  finding ", "मैं कौन खोज रहा था ");
        map.put("Who  was I  fleeing ", "मैं किससे भाग रहा था ");
        map.put("Who  was I  flying ", "मैं कौन उड़ रहा था ");
        map.put("Who  was I  forgetting ", "मैं कौन भूल रहा था ");
        map.put("Who  was I  frying ", "मैं कौन तलने वाला था ");
        map.put("Who  was I  getting ", "मुझे कौन मिल रहा था ");
        map.put("Who  was I  giving ", "मैं कौन दे रहा था ");
        map.put("Who  was I  going ", "मैं कौन जा रहा था ");
        map.put("Who  was I  growing ", "मैं कौन बढ़ रहा था ");
        map.put("Who  was I  hanging ", "मैं कौन लटक रहा था ");
        map.put("Who  was I  hearing ", "मैं कौन सुन रहा था ");
        map.put("Who  was I  helping ", "मैं कौन मदद कर रहा था ");
        map.put("Who  was I  hiding ", "मैं कौन छिपा रहा था ");
        map.put("Who  was I  hitting ", "मैं किसको मार रहा था ");
        map.put("Who  was I  holding ", "मैं किसे पकड़ रहा था ");
        map.put("Who  was I  hoping ", "मैं कौन उम्मीद कर रहा था ");
        map.put("Who  was I  hurting ", "मैं किसको चोट पहुँचा रहा था ");
        map.put("Who  was I  jumping ", "मैं कौन कूद रहा था ");
        map.put("Who  was I  keeping ", "मैं कौन रख रहा था ");
        map.put("Who  was I  killing ", "मैं किसको मार रहा था ");
        map.put("Who  was I  knowing ", "मैं कौन जानता था ");
        map.put("Who  was I  laughing ", "मैं कौन हँस रहा था ");
        map.put("Who  was I  leading ", "मैं किसका नेतृत्व कर रहा था ");
        map.put("Who  was I  leaping ", "मैं कौन छलांग लगा रहा था ");
        map.put("Who  was I  learning ", "मैं कौन सीख रहा था ");
        map.put("Who  was I  leaving ", "मैं कौन जा रहा था ");
        map.put("Who  was I  lending ", "मैं कौन उधार दे रहा था ");
        map.put("Who  was I  living ", "मैं कौन रह रहा था ");
        map.put("Who  was I  looking ", "मैं कौन देख रहा था ");
        map.put("Who  was I  losing ", "मैं कौन हार रहा था ");
        map.put("Who  was I  loving ", "मैं कौन प्यार कर रहा था ");
        map.put("Who  was I  making ", "मैं कौन बना रहा था ");
        map.put("Who  was I  marrying ", "मैं किससे शादी कर रहा था ");
        map.put("Who  was I  meeting ", "मैं किससे मिल रहा था ");
        map.put("Who  was I  mistaking ", "मैं किसकी गलती कर रहा था ");
        map.put("Who  was I  opening ", "मैं कौन खोल रहा था ");
        map.put("Who  was I  paying ", "मैं किसका भुगतान कर रहा था ");
        map.put("Who  was I  playing ", "मैं कौन खेल रहा था ");
        map.put("Who  was I  putting ", "मैं कौन डाल रहा था ");
        map.put("Who  was I  quarrelling ", "मैं कौन झगड़ा कर रहा था ");
        map.put("Who  was I  raining ", "मैं बारिश किससे कर रहा था ");
        map.put("Who  was I  reaching ", "मैं किसतक पहुँच रहा था ");
        map.put("Who  was I  reading ", "मैं कौन पढ़ रहा था ");
        map.put("Who  was I  remembering ", "मैं किसे याद कर रहा था ");
        map.put("Who  was I  riding ", "मैं कौन सवारी कर रहा था ");
        map.put("Who  was I  ringing ", "मैं कौन बज रहा था ");
        map.put("Who  was I  rising ", "मैं कौन उठ रहा था ");
        map.put("Who  was I  running ", "मैं कौन दौड़ रहा था ");
        map.put("Who  was I  saying ", "मैं कौन कह रहा था ");
        map.put("Who  was I  seeing ", "मैं कौन देख रहा था ");
        map.put("Who  was I  selling ", "मैं किसे बेच रहा था ");
        map.put("Who  was I  sending ", "मैं कौन भेज रहा था ");
        map.put("Who  was I  shaking ", "मैं कौन हिल रहा था ");
        map.put("Who  was I  shining ", "मैं कौन चमक रहा था ");
        map.put("Who  was I  shooting ", "मैं कौन शूटिंग कर रहा था ");
        map.put("Who  was I  showing ", "मैं कौन दिखा रहा था ");
        map.put("Who  was I  shutting ", "मैं किसे बंद कर रहा था ");
        map.put("Who  was I  singing ", "मैं कौन गा रहा था ");
        map.put("Who  was I  sinking ", "मैं कौन डूब रहा था ");
        map.put("Who  was I  sleeping ", "मैं कौन सो रहा था ");
        map.put("Who  was I  smelling ", "मैं किससे सूँघ रहा था ");

        return map;
    }
    static Map<String,String> Seven(){
        HashMap<String,String>map = new HashMap<>();
        map.put("Who  had I  abused ", "मैंने किसके साथ दुर्व्यवहार किया था ");
        map.put("Who  had I  advised ", "मैंने किसको सलाह दी थी ");
        map.put("Who  had I  answered ", "मैंने किसका उत्तर दिया था ");
        map.put("Who  had I  arisen ", "मैं कौन पैदा हुआ था ");
        map.put("Who  had I  arrived ", "मैं किसके पास आया था ");
        map.put("Who  had I  asked ", "मैंने किससे पूछा था ");
        map.put("Who  had I  awoken ", "मैं किससे जाग गया था ");
        map.put("Who  had I  undefined", "मैंने किसको अपरिभाषित किया था");
        map.put("Who  had I  borne ", "मैंने किसको जन्म दिया था ");
        map.put("Who  had I  beaten ", "मैंने किसको पीटा था ");
        map.put("Who  had I  become ", "मैं कौन बन गया था ");
        map.put("Who  had I  begged ", "मैंने किससे भीख मांगी थी ");
        map.put("Who  had I  begun ", "मैंने किसने शुरू किया था ");
        map.put("Who  had I  bound ", "मैंने किससे बाध्य किया था ");
        map.put("Who  had I  bitten ", "मैंने किसको काट लिया था ");
        map.put("Who  had I  blessed ", "मैंने किसको आशीर्वाद दिया था ");
        map.put("Who  had I  blown ", "मैंने किसको उड़ा दिया था ");
        map.put("Who  had I  broken ", "मैंने किसको तोड़ा था ");
        map.put("Who  had I  brought ", "मैं किसको लाया था ");
        map.put("Who  had I  built ", "मैंने किसने बनाया था ");
        map.put("Who  had I  burnt ", "मैंने किसको जला दिया था ");
        map.put("Who  had I  bought ", "मैंने किसे खरीदा था ");
        map.put("Who  had I  called ", "मैंने किसे फोन किया था ");
        map.put("Who  had I  carried ", "मैंने किसे किया था ");
        map.put("Who  had I  caught ", "मैंने किसे पकड़ा था ");
        map.put("Who  had I  cheated ", "मैंने किसने धोखा दिया था ");
        map.put("Who  had I  chosen ", "मैंने किसे चुना था ");
        map.put("Who  had I  cleaned ", "मैंने किसको साफ किया था ");
        map.put("Who  had I  climbed ", "मैं कौन चढ़ गया था ");
        map.put("Who  had I  closed ", "मैंने किसे बंद किया था ");
        map.put("Who  had I  come ", "मैं किसके पास आया था ");
        map.put("Who  had I  cooked ", "मैंने किसने पकाया था ");
        map.put("Who  had I  crept ", "मैंने किसने क्रेप्ट किया था ");
        map.put("Who  had I  cried ", "मैंने किससे रोया था ");
        map.put("Who  had I  cut ", "मैंने किसको काट दिया था ");
        map.put("Who  had I  danced ", "मैंने किसने नृत्य किया था ");
        map.put("Who  had I  dealt ", "मैंने किससे निपटा था ");
        map.put("Who  had I  died ", "मैं कौन मर गया था ");
        map.put("Who  had I  dug ", "मैंने किसने खोदा था ");
        map.put("Who  had I  drawn ", "मैंने किसने खींचा था ");
        map.put("Who  had I  drunk ", "मैंने किसको पिया था ");
        map.put("Who  had I  driven ", "मैंने किसको चलाया था ");
        map.put("Who  had I  dropped ", "मैंने किसको गिरा दिया था ");
        map.put("Who  had I  dried ", "मैंने किसको सुखाया था ");
        map.put("Who  had I  eaten ", "मैंने किसने खाया था ");
        map.put("Who  had I  elected ", "मैंने किसे चुना था ");
        map.put("Who  had I  entered ", "मैंने किसमें प्रवेश किया था ");
        map.put("Who  had I  fallen ", "मैं कौन गिर गया था ");
        map.put("Who  had I  fed ", "मैंने किसको खिलाया था ");
        map.put("Who  had I  felt ", "मैंने किसने महसूस किया था ");
        map.put("Who  had I  fought ", "मैंने किससे लड़ाई लड़ी थी ");
        map.put("Who  had I  found ", "मुझे कौन मिला था ");
        map.put("Who  had I  fled ", "मैं किससे भाग गया था ");
        map.put("Who  had I  flown ", "मैंने किससे उड़ाया था ");
        map.put("Who  had I  forgotten ", "मैं किसे भूल गया था ");
        map.put("Who  had I  fried ", "मैंने किसको तला था ");
        map.put("Who  had I  got ", "मुझे कौन मिला था ");
        map.put("Who  had I  given ", "मैंने किसे दिया था ");
        map.put("Who  had I  gone ", "मैं कौन गया था ");
        map.put("Who  had I  grown ", "मैं कौन हो गया था ");
        map.put("Who  had I  hanged ", "मैंने किसको फांसी दी थी ");
        map.put("Who  had I  hung ", "मैंने किसको लटका दिया था ");
        map.put("Who  had I  heard ", "मैंने किसने सुना था ");
        map.put("Who  had I  helped ", "मैंने किसकी मदद की थी ");
        map.put("Who  had I  hidden ", "मैंने किसने छिपाया था ");
        map.put("Who  had I  hit ", "मैंने किसको मारा था ");
        map.put("Who  had I  held ", "मैंने किसके पास रखा था ");
        map.put("Who  had I  hoped ", "मैंने किसकी उम्मीद की थी ");
        map.put("Who  had I  hurt ", "मुझे किससे चोट लगी थी ");
        map.put("Who  had I  jumped ", "मैं किससे कूद गया था ");
        map.put("Who  had I  kept ", "मैंने किसे रखा था ");
        map.put("Who  had I  killed ", "मैंने किसको मार डाला था ");
        map.put("Who  had I  known ", "मैं किसे जानता था ");
        map.put("Who  had I  laughed ", "मैं किसने हँसा था ");
        map.put("Who  had I  led ", "मैंने किसका नेतृत्व किया था ");
        map.put("Who  had I  leapt ", "मैंने किसने छलांग लगाई थी ");
        map.put("Who  had I  learnt ", "मैंने किसने सीखा था ");
        map.put("Who  had I  left ", "मैंने किसके पास छोड़ा था ");
        map.put("Who  had I  lent ", "मैंने किसे उधार दिया था ");
        map.put("Who  had I  lived ", "मैं किसके पास रहता था ");
        map.put("Who  had I  looked ", "मैंने किसको देखा था ");
        map.put("Who  had I  lost ", "मैंने किसको खो दिया था ");
        map.put("Who  had I  loved ", "मैंने किससे प्यार किया था ");
        map.put("Who  had I  made ", "मैंने किसने बनाया था ");
        map.put("Who  had I  married ", "मैंने किससे शादी की थी ");
        map.put("Who  had I  met ", "मैं किससे मिला था ");
        map.put("Who  had I  mistaken ", "मैंने किससे गलती की थी ");
        map.put("Who  had I  opened ", "मैंने किसने खोला था ");
        map.put("Who  had I  paid ", "मैंने किसका भुगतान किया था ");
        map.put("Who  had I  played ", "मैंने किसने खेला था ");
        map.put("Who  had I  put ", "मैंने किसने रखा था ");
        map.put("Who  had I  quarrelled ", "मैंने किसने झगड़ा किया था ");
        map.put("Who  had I  rained ", "मैंने किसकी बारिश की थी ");
        map.put("Who  had I  reached ", "मैं किसके पास पहुँचा था ");
        map.put("Who  had I  read ", "मैंने किसने पढ़ा था ");
        map.put("Who  had I  remembered ", "मैंने किसे याद किया था ");
        map.put("Who  had I  ridden ", "मैंने किसकी सवारी की थी ");
        map.put("Who  had I  rung ", "मैंने किसको बजाया था ");
        map.put("Who  had I  risen ", "मैं कौन उठ गया था ");
        map.put("Who  had I  run ", "मैंने किसको चलाया था ");
        map.put("Who  had I  said ", "मैंने किसने कहा था ");
        map.put("Who  had I  seen ", "मैंने किसने देखा था ");
        map.put("Who  had I  sold ", "मैंने किसे बेचा था ");
        map.put("Who  had I  sent ", "मैंने किसे भेजा था ");
        map.put("Who  had I  shaken ", "मैंने किसको हिला दिया था ");
        map.put("Who  had I  shone ", "मैं किससे चमका था ");
        map.put("Who  had I  shot ", "मैंने किसको गोली मारी थी ");
        map.put("Who  had I  shown ", "मैंने किसे दिखाया था ");
        map.put("Who  had I  shut ", "मैंने किसको बंद किया था ");
        map.put("Who  had I  sung ", "मैंने किसने गाया था ");
        map.put("Who  had I  sunk ", "मैं किससे डूब गया था ");
        map.put("Who  had I  slept ", "मैं किसके पास सोया था ");
        map.put("Who  had I  told ", "मैंने किसे कहा था ");

        return map;
    }
    static Map<String,String> Eight(){
        HashMap<String,String>map = new HashMap<>();
        map.put("Who  had I been  abusing ", "मैं किसके साथ गाली दे रहा था ");
        map.put("Who  had I been  advising ", "मैं किसको सलाह दे रहा था ");
        map.put("Who  had I been  answering ", "मैं किसका जवाब दे रहा था ");
        map.put("Who  had I been  arising ", "मैं कौन उठ रहा था ");
        map.put("Who  had I been  arriving ", "मैं किससे आ रहा था ");
        map.put("Who  had I been  asking ", "मैं किससे पूछ रहा था ");
        map.put("Who  had I been  awaking ", "मैं कौन जाग रहा था ");
        map.put("Who  had I been  undefined", "मैं कौन अपरिभाषित हो गया था");
        map.put("Who  had I been  bearing ", "मैं किसका असर कर रहा था ");
        map.put("Who  had I been  beating ", "मैं किसकी पिटाई कर रहा था ");
        map.put("Who  had I been  becoming ", "मैं कौन बन रहा था ");
        map.put("Who  had I been  begging ", "मैं किससे भीख माँग रहा था ");
        map.put("Who  had I been  beginning ", "मैं किसकी शुरुआत कर रहा था ");
        map.put("Who  had I been  binding ", "मैं किससे बंधन कर रहा था ");
        map.put("Who  had I been  biting ", "मैं किसका काट रहा था ");
        map.put("Who  had I been  blessing ", "मैं कौन आशीष दे रहा था ");
        map.put("Who  had I been  blowing ", "मैं किससे उड़ा रहा था ");
        map.put("Who  had I been  breaking ", "मैं कौन तोड़ रहा था ");
        map.put("Who  had I been  bringing ", "मैं कौन ला रहा था ");
        map.put("Who  had I been  building ", "मैं किसका निर्माण कर रहा था ");
        map.put("Who  had I been  burning ", "मैं कौन जल रहा था ");
        map.put("Who  had I been  buying ", "मैं कौन खरीद रहा था ");
        map.put("Who  had I been  calling ", "मैं किसे बुला रहा था ");
        map.put("Who  had I been  carrying ", "मैं किसे ले जा रहा था ");
        map.put("Who  had I been  catching ", "मैं किसे पकड़ रहा था ");
        map.put("Who  had I been  cheating ", "मैं किसे धोखा दे रहा था ");
        map.put("Who  had I been  choosing ", "मैं किसे चुन रहा था ");
        map.put("Who  had I been  cleaning ", "मैं किसकी सफाई कर रहा था ");
        map.put("Who  had I been  climbing ", "मैं किसपर चढ़ रहा था ");
        map.put("Who  had I been  closing ", "मैं किसे बंद कर रहा था ");
        map.put("Who  had I been  coming ", "मैं कौन आ रहा था ");
        map.put("Who  had I been  cooking ", "मैं किससे खाना बना रहा था ");
        map.put("Who  had I been  creeping ", "मैं कौन रेंग रहा था ");
        map.put("Who  had I been  crying ", "मैं किससे रो रहा था ");
        map.put("Who  had I been  cutting ", "मैं किसको काट रहा था ");
        map.put("Who  had I been  dancing ", "मैं कौन नाच रहा था ");
        map.put("Who  had I been  dealing ", "मैं किसका काम कर रहा था ");
        map.put("Who  had I been  dying ", "मैं कौन मर रहा था ");
        map.put("Who  had I been  digging ", "मैं किसकी खुदाई कर रहा था ");
        map.put("Who  had I been  drawing ", "मैं किसको चित्रित कर रहा था ");
        map.put("Who  had I been  drinking ", "मैं कौन पी रहा था ");
        map.put("Who  had I been  driving ", "मैं कौन चला रहा था ");
        map.put("Who  had I been  dropping ", "मैं किसको छोड़ रहा था ");
        map.put("Who  had I been  drying ", "मैं किसको सुखा रहा था ");
        map.put("Who  had I been  eating ", "मैं कौन खा रहा था ");
        map.put("Who  had I been  electing ", "मैं किसका चुनाव कर रहा था ");
        map.put("Who  had I been  entering ", "मैं किसमें प्रवेश कर रहा था ");
        map.put("Who  had I been  falling ", "मैं कौन गिर रहा था ");
        map.put("Who  had I been  feeding ", "मैं किसे खिला रहा था ");
        map.put("Who  had I been  feeling ", "मैं कौन महसूस कर रहा था ");
        map.put("Who  had I been  fighting ", "मैं किससे लड़ रहा था ");
        map.put("Who  had I been  finding ", "मैं किसे ढूंढ रहा था ");
        map.put("Who  had I been  fleeing ", "मैं किससे भाग रहा था ");
        map.put("Who  had I been  flying ", "मैं किससे उड़ रहा था ");
        map.put("Who  had I been  forgetting ", "मैं किसको भूल गया था ");
        map.put("Who  had I been  frying ", "मैं कौन तलने गया था ");
        map.put("Who  had I been  getting ", "मुझे कौन मिल रहा था ");
        map.put("Who  had I been  giving ", "मैं कौन दे रहा था ");
        map.put("Who  had I been  going ", "मैं कौन जा रहा था ");
        map.put("Who  had I been  growing ", "मैं कौन बढ़ रहा था ");
        map.put("Who  had I been  hanging ", "मैं किसके पास लटक रहा था ");
        map.put("Who  had I been  hearing ", "मैं कौन सुन रहा था ");
        map.put("Who  had I been  helping ", "मैं किसकी मदद कर रहा था ");
        map.put("Who  had I been  hiding ", "मैं कौन छिपा रहा था ");
        map.put("Who  had I been  hitting ", "मैं किसको मार रहा था ");
        map.put("Who  had I been  holding ", "मैं किसे पकड़ रहा था ");
        map.put("Who  had I been  hoping ", "मैं किसकी उम्मीद कर रहा था ");
        map.put("Who  had I been  hurting ", "मैं किसको चोट पहुँचा रहा था ");
        map.put("Who  had I been  jumping ", "मैं कौन कूद रहा था ");
        map.put("Who  had I been  keeping ", "मैं किसे रख रहा था ");
        map.put("Who  had I been  killing ", "मैं किसको मार रहा था ");
        map.put("Who  had I been  knowing ", "मैं किसे जानता था ");
        map.put("Who  had I been  laughing ", "मैं कौन हँस रहा था ");
        map.put("Who  had I been  leading ", "मैं किसका नेतृत्व कर रहा था ");
        map.put("Who  had I been  leaping ", "मैं किससे छलांग लगा रहा था ");
        map.put("Who  had I been  learning ", "मैं कौन सीख रहा था ");
        map.put("Who  had I been  leaving ", "मैं किससे जा रहा था ");
        map.put("Who  had I been  lending ", "मैं किसे उधार दे रहा था ");
        map.put("Who  had I been  living ", "मैं कौन रह रहा था ");
        map.put("Who  had I been  looking ", "मैं किसे देख रहा था ");
        map.put("Who  had I been  losing ", "मैं किसको खो रहा था ");
        map.put("Who  had I been  loving ", "मैं किससे प्यार कर रहा था ");
        map.put("Who  had I been  making ", "मैं कौन बना रहा था ");
        map.put("Who  had I been  marrying ", "मैं किससे शादी कर रहा था ");
        map.put("Who  had I been  meeting ", "मैं किससे मिल रहा था ");
        map.put("Who  had I been  mistaking ", "मैं किसकी गलती कर रहा था ");
        map.put("Who  had I been  opening ", "मैं कौन खोल रहा था ");
        map.put("Who  had I been  paying ", "मैं किसका भुगतान कर रहा था ");
        map.put("Who  had I been  playing ", "मैं कौन खेल रहा था ");
        map.put("Who  had I been  putting ", "मैं कौन डाल रहा था ");
        map.put("Who  had I been  quarrelling ", "मैं किससे झगड़ा कर रहा था ");
        map.put("Who  had I been  raining ", "मैं किससे बारिश कर रहा था ");
        map.put("Who  had I been  reaching ", "मैं किसके पास पहुँच रहा था ");
        map.put("Who  had I been  reading ", "मैं कौन पढ़ रहा था ");
        map.put("Who  had I been  remembering ", "मैं किसे याद कर रहा था ");
        map.put("Who  had I been  riding ", "मैं किसकी सवारी कर रहा था ");
        map.put("Who  had I been  ringing ", "मैं किससे बज रहा था ");
        map.put("Who  had I been  rising ", "मैं किससे उठ रहा था ");
        map.put("Who  had I been  running ", "मैं कौन दौड़ रहा था ");
        map.put("Who  had I been  saying ", "मैं कौन कह रहा था ");
        map.put("Who  had I been  seeing ", "मैं किसे देख रहा था ");
        map.put("Who  had I been  selling ", "मैं किसे बेच रहा था ");
        map.put("Who  had I been  sending ", "मैं किसे भेज रहा था ");
        map.put("Who  had I been  shaking ", "मैं किसको हिला रहा था ");
        map.put("Who  had I been  shining ", "मैं कौन चमक रहा था ");
        map.put("Who  had I been  shooting ", "मैं किसकी शूटिंग कर रहा था ");
        map.put("Who  had I been  showing ", "मैं कौन दिखा रहा था ");
        map.put("Who  had I been  shutting ", "मैं किसे बंद कर रहा था ");
        map.put("Who  had I been  singing ", "मैं कौन गा रहा था ");
        map.put("Who  had I been  sinking ", "मैं कौन डूब रहा था ");
        map.put("Who  had I been  sleeping ", "मैं कौन सो रहा था ");

        return map;
    }
    static Map<String,String> Nine(){
        HashMap<String,String>map = new HashMap<>();
        map.put("Who  will I abuse ", "मैं किसका गाली दूँगा ");
        map.put("Who  will I advise", "मैं किसको सलाह दूँगा");
        map.put("Who  will I answer ", "मैं किसे जवाब दूंगा ");
        map.put("Who  will I arise ", "मैं कौन उठ जाऊंगा ");
        map.put("Who  will I arrive ", "मैं किससे पहुँचूँगा ");
        map.put("Who  will I ask ", "मैं किससे पूछूँगा ");
        map.put("Who  will I awake ", "मैं कौन जाग जाऊंगा ");
        map.put("Who  will I \r", "मैं कौन रहूँगा \r");
        map.put("Who  will I be undefined", "मैं कौन अपरिभाषित हो जाऊंगा");
        map.put("Who  will I bear ", "मैं किसे सहन करूँगा ");
        map.put("Who  will I beat ", "मैं किसे हराऊंगा ");
        map.put("Who  will I become ", "मैं कौन बनूंगा ");
        map.put("Who  will I beg ", "मैं किससे भीख मांगूँगा ");
        map.put("Who  will I begin ", "मैं किससे शुरू करूँगा ");
        map.put("Who  will I bind ", "मैं किसको बाँध लूँगा ");
        map.put("Who  will I bite", "मैं किसे काटूंगा");
        map.put("Who  will I bless", "मैं किसको आशीर्वाद दूँगा");
        map.put("Who  will I break ", "मैं किसे तोड़ूँगा ");
        map.put("Who  will I bring ", "मैं कौन लाऊंगा ");
        map.put("Who  will I build ", "मैं किसका निर्माण करूंगा ");
        map.put("Who  will I burn ", "मैं किसे जलाऊंगा ");
        map.put("Who  will I buy ", "मैं कौन खरीदूंगा ");
        map.put("Who  will I call ", "मैं किसे कॉल करूंगा ");
        map.put("Who  will I carry ", "मैं किसे ले जाऊंगा ");
        map.put("Who  will I catch ", "मैं किसे पकड़ूँगा ");
        map.put("Who  will I cheat ", "मैं किसे धोखा दूँगा ");
        map.put("Who  will I choose ", "मैं किसे चुनूंगा ");
        map.put("Who  will I clean ", "मैं किसको साफ करूँगा ");
        map.put("Who  will I climb  ", "मैं किसपर चढ़ूँगा  ");
        map.put("Who  will I close ", "मैं किसे बंद करूँगा ");
        map.put("Who  will I come ", "मैं कौन आऊंगा ");
        map.put("Who  will I cook ", "मैं किसे खाना बनाऊँगा ");
        map.put("Who  will I creep ", "मैं किसको रेंगूँगा ");
        map.put("Who  will I cry ", "मैं किसको रोऊंगा ");
        map.put("Who  will I cut ", "मैं किसको काटूंगा ");
        map.put("Who  will I dance ", "मैं कौन नाचता हूँ ");
        map.put("Who  will I deal ", "मैं किससे निपटूंगा ");
        map.put("Who  will I die ", "मैं कौन मरूंगा ");
        map.put("Who  will I dig ", "मैं किसे खोदूँगा ");
        map.put("Who  will I draw ", "मैं किसे आकर्षित करूंगा ");
        map.put("Who  will I drive ", "मैं किसको चलाऊंगा ");
        map.put("Who  will I drop ", "मैं किसे छोड़ूँगा ");
        map.put("Who  will I dry ", "मैं किसको सुखाऊंगा ");
        map.put("Who  will I eat ", "मैं कौन खाऊंगा ");
        map.put("Who  will I elect", "मैं किसे चुनूंगा");
        map.put("Who  will I enter ", "मैं किसमें प्रवेश करूँगा ");
        map.put("Who  will I fall ", "मैं कौन गिरूंगा ");
        map.put("Who  will I feed ", "मैं किसे खिलाऊंगा ");
        map.put("Who  will I feel  ", "मैं कौन महसूस करूंगा  ");
        map.put("Who  will I fight ", "मैं किससे लड़ूंगा ");
        map.put("Who  will I find ", "मुझे कौन मिलेगा ");
        map.put("Who  will I flee ", "मैं किससे भागेगा ");
        map.put("Who  will I fly  ", "मैं कौन उड़ूंगा  ");
        map.put("Who  will I forget ", "मैं किसे भूल जाऊंगा ");
        map.put("Who  will I fry ", "मैं किसको भूनूंगा ");
        map.put("Who  will I get  ", "मुझे कौन मिलेगा  ");
        map.put("Who  will I give ", "मैं कौन दूँगा ");
        map.put("Who  will I go ", "मैं कौन जाऊंगा ");
        map.put("Who  will I grow", "मैं कौन बढ़ूंगा");
        map.put("Who  will I hang ", "मैं किसे लटकाऊंगा ");
        map.put("Who  will I hear ", "मैं कौन सुनूंगा ");
        map.put("Who  will I help ", "मैं किसकी मदद करूँगा ");
        map.put("Who  will I hide ", "मैं किसे छिपाऊंगा ");
        map.put("Who  will I hit ", "मैं किसे मारूंगा ");
        map.put("Who  will I hold ", "मैं किसे पकड़ लूंगा ");
        map.put("Who  will I hope ", "मैं किसकी उम्मीद करूंगा ");
        map.put("Who  will I hurt ", "मैं किसको चोट पहुंचाऊंगा ");
        map.put("Who  will I jump ", "मैं किससे कूदूँगा ");
        map.put("Who  will I keep ", "मैं कौन रखूँगा ");
        map.put("Who  will I kill ", "मैं किसे मार डालूंगा ");
        map.put("Who  will I know ", "मुझे किसे पता चलेगा ");
        map.put("Who  will I laugh ", "मैं किसको हंसूंगा ");
        map.put("Who  will I lead ", "मैं किसका नेतृत्व करूँगा ");
        map.put("Who  will I leap ", "मैं कौन छलांग लगाऊंगा ");
        map.put("Who  will I learn ", "मैं कौन सीखूंगा ");
        map.put("Who  will I leave ", "मैं किसे छोड़ूँगा ");
        map.put("Who  will I lend ", "मैं किसे उधार दूँगा ");
        map.put("Who  will I live ", "मैं कौन रहूँगा ");
        map.put("Who  will I look ", "मैं किसको देखूँगा ");
        map.put("Who  will I lose ", "मैं किसको खो दूँगा ");
        map.put("Who  will I make ", "मैं कौन बनाऊँगा ");
        map.put("Who  will I marry ", "मैं किससे शादी करूँगा ");
        map.put("Who  will I meet ", "मैं किससे मिलूंगा ");
        map.put("Who  will I mistake ", "मैं किसकी गलती करूँगा ");
        map.put("Who  will I open ", "मैं कौन खोलूंगा ");
        map.put("Who  will I pay  ", "मैं किसे भुगतान करूंगा  ");
        map.put("Who  will I play ", "मैं कौन खेलूंगा ");
        map.put("Who  will I put ", "मैं कौन रखूँगा ");
        map.put("Who  will I quarrel ", "मैं किससे झगड़ा करूंगा ");
        map.put("Who  will I rain ", "मैं किसकी बारिश करूँगा ");
        map.put("Who  will I reach ", "मैं किसतक पहुँचूँगा ");
        map.put("Who  will I read", "मैं कौन पढ़ूँगा");
        map.put("Who  will I remember  ", "मैं किसे याद रखूँगा  ");
        map.put("Who  will I ride ", "मैं किसकी सवारी करूँगा ");
        map.put("Who  will I ring ", "मैं किससे रिंग करूंगा ");
        map.put("Who  will I rise  ", "मैं किससे उठूंगा  ");
        map.put("Who  will I run  ", "मैं कौन दौड़ूंगा  ");
        map.put("Who  will I say ", "मैं कौन कहूँगा ");
        map.put("Who  will I see ", "मैं किसे देखूँगा ");
        map.put("Who  will I sell ", "मैं किसे बेचूंगा ");
        map.put("Who  will I send ", "मैं किसे भेजूंगा ");
        map.put("Who  will I shake ", "मैं किसको हिलाऊंगा ");
        map.put("Who  will I shine ", "मैं कौन चमकूंगा ");
        map.put("Who  will I shoot ", "मैं किसे शूट करूँगा ");
        map.put("Who  will I shut  ", "मैं किसे बंद करूँगा  ");
        map.put("Who  will I sing ", "मैं कौन गाऊंगा ");
        map.put("Who  will I sink ", "मैं किसको डुबो दूंगा ");
        map.put("Who  will I sleep ", "मैं किसको सोऊंगा ");
        map.put("Who  will I win ", "मैं कौन जीतूंगा ");

        return map;
    }
    static Map<String,String> Ten(){
        HashMap<String,String>map = new HashMap<>();
        map.put("Who  will I be abusing ", "मैं किसको गाली दे रहा हूँ ");
        map.put("Who  will I be advising ", "मैं किसको सलाह दूँगा ");
        map.put("Who  will I be answering ", "मैं किसका जवाब दूंगा ");
        map.put("Who  will I be arising ", "मैं कौन उठ रहा हूँ ");
        map.put("Who  will I be arriving ", "मैं किससे पहुँचूँगा ");
        map.put("Who  will I be asking ", "मैं किससे पूछूंगा ");
        map.put("Who  will I be awaking ", "मैं कौन जाग रहा हूँ ");
        map.put("Who  will I be bearing ", "मैं किसका असर डालूंगा ");
        map.put("Who  will I be beating ", "मैं किसकी पिटाई करूंगा ");
        map.put("Who  will I be becoming ", "मैं कौन बन जाऊंगा ");
        map.put("Who  will I be begging ", "मैं किससे भीख माँग रहा हूँ ");
        map.put("Who  will I be beginning ", "मैं किसकी शुरुआत करूँगा ");
        map.put("Who  will I be binding ", "मैं किससे बाध्यकारी रहूँगा ");
        map.put("Who  will I be biting ", "मैं किसे काट रहा हूँ ");
        map.put("Who  will I be blessing ", "मैं कौन आशीष बनूंगा ");
        map.put("Who  will I be blowing ", "मैं कौन उड़ा रहा हूँ ");
        map.put("Who  will I be breaking ", "मैं किसको तोड़ रहा हूँ ");
        map.put("Who  will I be bringing ", "मैं कौन लाऊंगा ");
        map.put("Who  will I be building ", "मैं किसका निर्माण करूंगा ");
        map.put("Who  will I be burning ", "मैं किसको जलाऊंगा ");
        map.put("Who  will I be buying ", "मैं कौन खरीदूंगा ");
        map.put("Who  will I be calling ", "मैं किसे बुला रहा हूँ ");
        map.put("Who  will I be carrying ", "मैं किसे ले जाऊंगा ");
        map.put("Who  will I be catching ", "मैं किसे पकड़ रहा हूँ ");
        map.put("Who  will I be cheating ", "मैं किसे धोखा दे रहा हूँ ");
        map.put("Who  will I be choosing ", "मैं किसे चुनूंगा ");
        map.put("Who  will I be cleaning ", "मैं किसकी सफाई करूँगा ");
        map.put("Who  will I be climbing ", "मैं किसपर चढ़ जाऊंगा ");
        map.put("Who  will I be closing ", "मैं किसे बंद करूँगा ");
        map.put("Who  will I be coming ", "मैं कौन आऊंगा ");
        map.put("Who  will I be cooking ", "मैं किसे खाना बना रहा हूँ ");
        map.put("Who  will I be creeping ", "मैं कौन रेंग रहा हूँ ");
        map.put("Who  will I be crying ", "मैं कौन रो रहा हूँ ");
        map.put("Who  will I be cutting ", "मैं किसको काटूंगा ");
        map.put("Who  will I be dancing ", "मैं कौन नाचता रहूँगा ");
        map.put("Who  will I be dealing ", "मैं किससे निपटूंगा ");
        map.put("Who  will I be dying ", "मैं कौन मर जाऊंगा ");
        map.put("Who  will I be digging ", "मैं किसकी खुदाई करूँगा ");
        map.put("Who  will I be drawing ", "मैं किसको चित्रित करूँगा ");
        map.put("Who  will I be drinking ", "मैं कौन पी रहा हूँ ");
        map.put("Who  will I be driving ", "मैं कौन चला रहा हूँ ");
        map.put("Who  will I be dropping ", "मैं किसको छोड़ रहा हूँ ");
        map.put("Who  will I be drying ", "मैं किसको सुखाऊंगा ");
        map.put("Who  will I be eating ", "मैं कौन खाऊंगा ");
        map.put("Who  will I be electing ", "मैं किसका चुनाव करूँगा ");
        map.put("Who  will I be entering ", "मैं किसमें प्रवेश करूंगा ");
        map.put("Who  will I be falling ", "मैं कौन गिर रहा हूँ ");
        map.put("Who  will I be feeding ", "मैं किसे खिलाऊंगा ");
        map.put("Who  will I be feeling ", "मैं कौन महसूस कर रहा हूँ ");
        map.put("Who  will I be fighting ", "मैं किससे लड़ूंगा ");
        map.put("Who  will I be finding ", "मैं कौन खोजूंगा ");
        map.put("Who  will I be fleeing ", "मैं किससे भाग जाऊंगा ");
        map.put("Who  will I be flying ", "मैं किससे उड़ जाऊंगा ");
        map.put("Who  will I be forgetting ", "मैं किसे भूल जाऊंगा ");
        map.put("Who  will I be frying ", "मैं किसको तलने वाला हूँ ");
        map.put("Who  will I be getting ", "मुझे कौन मिल रहा होगा ");
        map.put("Who  will I be giving ", "मैं कौन दे रहा हूँ ");
        map.put("Who  will I be going ", "मैं कौन जाऊंगा ");
        map.put("Who  will I be growing ", "मैं कौन बढ़ रहा हूँ ");
        map.put("Who  will I be hanging ", "मैं किसको लटकाऊंगा ");
        map.put("Who  will I be hearing ", "मैं किसकी सुनूंगा ");
        map.put("Who  will I be helping ", "मैं किसकी मदद करूंगा ");
        map.put("Who  will I be hiding ", "मैं किसे छिपाऊंगा ");
        map.put("Who  will I be hitting ", "मैं किसको मार रहा हूँ ");
        map.put("Who  will I be holding ", "मैं किसे पकड़ लूंगा ");
        map.put("Who  will I be hoping ", "मैं किसकी उम्मीद कर रहा हूँ ");
        map.put("Who  will I be hurting ", "मैं किसको चोट पहुँचाऊंगा ");
        map.put("Who  will I be jumping ", "मैं कौन कूद रहा हूँ ");
        map.put("Who  will I be keeping ", "मैं किसे रखूँगा ");
        map.put("Who  will I be killing ", "मैं किसको मार रहा हूँ ");
        map.put("Who  will I be knowing ", "मैं किसे जान जाऊंगा ");
        map.put("Who  will I be laughing ", "मैं कौन हँस रहा हूँ ");
        map.put("Who  will I be leading ", "मैं किसकी अगुवाई करूंगा ");
        map.put("Who  will I be leaping ", "मैं कौन छलांग लगाऊंगा ");
        map.put("Who  will I be learning ", "मैं कौन सीख रहा हूँ ");
        map.put("Who  will I be leaving ", "मैं किसे छोड़ूँगा ");
        map.put("Who  will I be lending ", "मैं किसे उधार दे रहा हूँ ");
        map.put("Who  will I be living ", "मैं कौन रहूँगा ");
        map.put("Who  will I be looking ", "मैं किसे देख रहा हूँ ");
        map.put("Who  will I be losing ", "मैं किसे हार जाऊंगा ");
        map.put("Who  will I be loving ", "मैं किससे प्यार करूंगा ");
        map.put("Who  will I be making ", "मैं कौन बना रहा हूँ ");
        map.put("Who  will I be marrying ", "मैं किससे शादी करूँगा ");
        map.put("Who  will I be meeting ", "मैं किससे मिल रहा हूँ ");
        map.put("Who  will I be mistaking ", "मैं किससे गलत हो जाऊंगा ");
        map.put("Who  will I be opening ", "मैं कौन खोलूंगा ");
        map.put("Who  will I be paying ", "मैं किसे भुगतान करूंगा ");
        map.put("Who  will I be playing ", "मैं कौन खेलूंगा ");
        map.put("Who  will I be putting ", "मैं कौन डालूंगा ");
        map.put("Who  will I be quarrelling ", "मैं किससे झगड़ा करूंगा ");
        map.put("Who  will I be raining ", "मैं किसकी बारिश कर रहा हूँ ");
        map.put("Who  will I be reaching ", "मैं किसतक पहुँचूँगा ");
        map.put("Who  will I be reading ", "मैं कौन पढ़ूंगा ");
        map.put("Who  will I be remembering ", "मैं किसे याद रखूँगा ");
        map.put("Who  will I be riding ", "मैं किसकी सवारी करूँगा ");
        map.put("Who  will I be ringing ", "मैं किससे बज रहा हूँ ");
        map.put("Who  will I be rising ", "मैं किससे उठ रहा हूँ ");
        map.put("Who  will I be running ", "मैं कौन दौड़ूंगा ");
        map.put("Who  will I be saying ", "मैं कौन कहूँगा ");
        map.put("Who  will I be seeing ", "मैं किसे देख रहा हूँ ");
        map.put("Who  will I be selling ", "मैं किसे बेचूंगा ");
        map.put("Who  will I be sending ", "मैं किसे भेजूंगा ");
        map.put("Who  will I be shaking ", "मैं किसको हिलाऊंगा ");
        map.put("Who  will I be shining ", "मैं किससे चमक रहा हूँ ");
        map.put("Who  will I be shooting ", "मैं किसकी शूटिंग करूँगा ");
        map.put("Who  will I be showing ", "मैं कौन दिखाऊंगा ");
        map.put("Who  will I be shutting ", "मैं किसे बंद कर रहा हूँ ");
        map.put("Who  will I be singing ", "मैं कौन गा रहा हूँ ");
        map.put("Who  will I be sinking ", "मैं कौन डूब रहा हूँ ");
        map.put("Who  will I be sleeping ", "मैं कौन सो रहा हूँ ");
        map.put("Who  will I be writing ", "मैं कौन लिखूँगा ");

        return map;
    }
    static Map<String,String> Eleven(){
        HashMap<String,String>map = new HashMap<>();
        map.put("Who  will I have borne ", "मैं कौन पैदा करूंगा ");
        map.put("Who  will I have abused ", "मैंने किसके साथ दुर्व्यवहार किया होगा ");
        map.put("Who  will I have advised ", "मैंने किसको सलाह दी होगी ");
        map.put("Who  will I have answered ", "मैंने किसका जवाब दिया होगा ");
        map.put("Who  will I have arisen ", "मैं कौन पैदा हुआ होगा ");
        map.put("Who  will I have arrived ", "मैं कौन आ गया हूँ ");
        map.put("Who  will I have asked ", "मैंने किससे पूछा होगा ");
        map.put("Who  will I have awoken ", "मैं कौन जाग जाऊंगा ");
        map.put("Who  will I have undefined", "मैं किसको अपरिभाषित करूंगा");
        map.put("Who  will I have beaten ", "मैंने किसे पीटा होगा ");
        map.put("Who  will I have become ", "मैं कौन बन जाऊंगा ");
        map.put("Who  will I have begged ", "मैंने किससे भीख माँगी होगी ");
        map.put("Who  will I have begun ", "मैं किससे शुरू कर दूँगा ");
        map.put("Who  will I have bound ", "मैं किससे बाध्य होऊंगा ");
        map.put("Who  will I have bitten ", "मैंने किसे काट लिया होगा ");
        map.put("Who  will I have blessed ", "मैं किसको आशीष दूँगा ");
        map.put("Who  will I have blown ", "मैंने किसे उड़ा दिया होगा ");
        map.put("Who  will I have broken ", "मैं किसको तोड़ दूँगा ");
        map.put("Who  will I have brought ", "मैं कौन लाऊंगा ");
        map.put("Who  will I have built ", "मैंने किसे बनाया होगा ");
        map.put("Who  will I have burnt ", "मैं किसको जला दूँगा ");
        map.put("Who  will I have bought ", "मैंने किसे खरीदा होगा ");
        map.put("Who  will I have called ", "मैंने किसे फोन किया होगा ");
        map.put("Who  will I have carried ", "मैं किसे ले जाऊंगा ");
        map.put("Who  will I have caught ", "मैंने किसे पकड़ा होगा ");
        map.put("Who  will I have cheated ", "मैंने किसे धोखा दिया होगा ");
        map.put("Who  will I have chosen ", "मैंने किसे चुना होगा ");
        map.put("Who  will I have cleaned ", "मैंने किसको साफ किया होगा ");
        map.put("Who  will I have climbed ", "मैं कौन चढ़ जाऊंगा ");
        map.put("Who  will I have closed ", "मैं किसे बंद कर दूँगा ");
        map.put("Who  will I have come ", "मैं कौन आऊँगा ");
        map.put("Who  will I have cooked ", "मैंने किसे पकाया होगा ");
        map.put("Who  will I have crept ", "मेरे पास क्रेप्ट कौन होगा ");
        map.put("Who  will I have cried ", "मैं किससे रोया होगा ");
        map.put("Who  will I have cut ", "मैंने किसको काट दिया होगा ");
        map.put("Who  will I have danced ", "मैंने किससे नृत्य किया होगा ");
        map.put("Who  will I have dealt ", "मैंने किससे निपटा होगा ");
        map.put("Who  will I have died ", "मैं कौन मर जाऊंगा ");
        map.put("Who  will I have dug ", "मैंने किसको खोदा होगा ");
        map.put("Who  will I have drawn ", "मैंने किसे ड्रॉ किया होगा ");
        map.put("Who  will I have drunk ", "मैं किसको नशे में डालूंगा ");
        map.put("Who  will I have driven ", "मैंने किसको चलाया होगा ");
        map.put("Who  will I have dropped ", "मैं किसको गिरा दूँगा ");
        map.put("Who  will I have dried ", "मैं किसको सुखाऊंगा ");
        map.put("Who  will I have eaten ", "मैंने कौन खाया होगा ");
        map.put("Who  will I have elected ", "मैं किसे चुनूंगा ");
        map.put("Who  will I have entered ", "मैं किसमें प्रवेश करूंगा ");
        map.put("Who  will I have fallen ", "मैं कौन गिर जाऊंगा ");
        map.put("Who  will I have fed ", "मैंने किसे खिलाया होगा ");
        map.put("Who  will I have felt ", "मैंने कौन महसूस किया होगा ");
        map.put("Who  will I have fought ", "मैं किससे लड़ जाऊंगा ");
        map.put("Who  will I have found ", "मुझे कौन मिल जाएगा ");
        map.put("Who  will I have fled ", "मैं किससे भाग जाऊंगा ");
        map.put("Who  will I have flown ", "मैं किससे उड़ जाऊंगा ");
        map.put("Who  will I have forgotten ", "मैं किसे भूल जाऊंगा ");
        map.put("Who  will I have fried ", "मैंने किसे तला हुआ होगा ");
        map.put("Who  will I have got ", "मुझे कौन मिल गया होगा ");
        map.put("Who  will I have given ", "मैंने कौन दिया होगा ");
        map.put("Who  will I have gone ", "मैं कौन गया हूँ ");
        map.put("Who  will I have grown ", "मैं कौन बड़ा हो जाऊंगा ");
        map.put("Who  will I have hanged ", "मैं किसको फांसी दे दूँगा ");
        map.put("Who  will I have hung ", "मैंने किसको लटका दिया होगा ");
        map.put("Who  will I have heard ", "मैंने किसे सुना होगा ");
        map.put("Who  will I have helped ", "मैंने किसकी मदद की होगी ");
        map.put("Who  will I have hidden ", "मैं कौन छिपाऊंगा ");
        map.put("Who  will I have hit ", "मैंने किसे मारा होगा ");
        map.put("Who  will I have held ", "मैंने किसे आयोजित किया होगा ");
        map.put("Who  will I have hoped ", "मुझे किसकी उम्मीद होगी ");
        map.put("Who  will I have hurt ", "मुझे किसको चोट लगी होगी ");
        map.put("Who  will I have jumped ", "मैं किससे कूद जाऊंगा ");
        map.put("Who  will I have kept ", "मैंने किसे रखा होगा ");
        map.put("Who  will I have killed ", "मैं किसको मार डालूंगा ");
        map.put("Who  will I have known ", "मुझे किसे पता चल जाएगा ");
        map.put("Who  will I have laughed ", "मैं किसको हँसाऊंगा ");
        map.put("Who  will I have led ", "मैंने किसका नेतृत्व किया होगा ");
        map.put("Who  will I have leapt ", "मैं किससे छलांग लगाऊंगा ");
        map.put("Who  will I have learnt ", "मैंने कौन सीखा होगा ");
        map.put("Who  will I have left ", "मैं कौन छोड़ दूँगा ");
        map.put("Who  will I have lent ", "मैंने किसे उधार दिया होगा ");
        map.put("Who  will I have lived ", "मैं कौन रहूँगा ");
        map.put("Who  will I have looked ", "मैंने किसको देखा होगा ");
        map.put("Who  will I have lost ", "मैं कौन खो जाऊंगा ");
        map.put("Who  will I have loved ", "मैंने किससे प्यार किया होगा ");
        map.put("Who  will I have made ", "मैंने कौन बनाया होगा ");
        map.put("Who  will I have married ", "मैं किससे शादी करूँगा ");
        map.put("Who  will I have met ", "मैं किससे मिला हूँ ");
        map.put("Who  will I have mistaken ", "मैंने किससे गलती की होगी ");
        map.put("Who  will I have opened ", "मैंने किसे खोला होगा ");
        map.put("Who  will I have paid ", "मैंने किसे भुगतान किया होगा ");
        map.put("Who  will I have played ", "मैं कौन खेलूंगा ");
        map.put("Who  will I have put ", "मैंने कौन रखा होगा ");
        map.put("Who  will I have quarrelled ", "मैं किससे झगड़ा करूंगा ");
        map.put("Who  will I have rained ", "मैंने किसकी बारिश की होगी ");
        map.put("Who  will I have reached ", "मैं किसतक पहुँचूँगा ");
        map.put("Who  will I have read ", "मैंने कौन पढ़ा होगा ");
        map.put("Who  will I have remembered ", "मुझे किसे याद होगा ");
        map.put("Who  will I have ridden ", "मैंने किसकी सवारी की होगी ");
        map.put("Who  will I have rung ", "मैं किससे रूंगा ");
        map.put("Who  will I have risen ", "मैं कौन उठ जाऊंगा ");
        map.put("Who  will I have run ", "मैं कौन दौड़ूंगा ");
        map.put("Who  will I have said ", "मैंने कौन कहा होगा ");
        map.put("Who  will I have seen ", "मैंने किसे देखा होगा ");
        map.put("Who  will I have sold ", "मैंने किसे बेचा होगा ");
        map.put("Who  will I have sent ", "मैंने किसे भेजा होगा ");
        map.put("Who  will I have shaken ", "मैं किसको हिलाऊंगा ");
        map.put("Who  will I have shone ", "मैं किससे चमकूंगा ");
        map.put("Who  will I have shot ", "मैंने किसको गोली मार दी होगी ");
        map.put("Who  will I have shown ", "मैंने कौन दिखाया होगा ");
        map.put("Who  will I have shut ", "मैं किसको बंद कर दूँगा ");
        map.put("Who  will I have sung ", "मैंने कौन गाया होगा ");
        map.put("Who  will I have sunk ", "मैं कौन डूब जाऊंगा ");
        map.put("Who  will I have slept ", "मैं कौन सोऊंगा ");
        map.put("Who  will I have spoken ", "मैंने किससे बात की होगी ");
        map.put("Who  will I have smelt ", "मैंने किसको पिघलाया होगा ");
        map.put("Who  will I have  spoiled ", "मैं किसको खराब कर दूँगा ");
        map.put("Who  will I have tried ", "मैंने किसकी कोशिश की होगी ");
        map.put("Who  will I have told ", "मैंने किसे कहा होगा ");

        return map;
    }
    static Map<String,String> Twelve(){
        HashMap<String,String>map = new HashMap<>();
        map.put("Who  will I have been abusing ", "मैं किसको गाली दे रहा हूँ ");
        map.put("Who  will I have been advising ", "मैं किसको सलाह दे रहा हूँ ");
        map.put("Who  will I have been answering ", "मैं किसका जवाब दे रहा हूँ ");
        map.put("Who  will I have been arising ", "मैं कौन पैदा हो रहा हूँ ");
        map.put("Who  will I have been arriving ", "मैं किससे आ रहा हूँ ");
        map.put("Who  will I have been asking ", "मैं किससे पूछ रहा हूँ ");
        map.put("Who  will I have been awaking ", "मैं कौन जाग रहा होगा ");
        map.put("Who  will I have been undefined", "मैं कौन अपरिभाषित हो गया होगा");
        map.put("Who  will I have been bearing ", "मैं किसको सहन कर रहा हूँ ");
        map.put("Who  will I have been beating ", "मैं किसकी पिटाई कर रहा हूँ ");
        map.put("Who  will I have been becoming ", "मैं कौन बन रहा हूँ ");
        map.put("Who  will I have been begging ", "मैं किससे भीख माँग रहा हूँ ");
        map.put("Who  will I have been beginning ", "मैं किसकी शुरुआत कर रहा हूँ ");
        map.put("Who  will I have been binding ", "मैं किससे बाध्यकारी रहा हूँ ");
        map.put("Who  will I have been biting ", "मैं किसको काट रहा हूँ ");
        map.put("Who  will I have been blessing ", "मैं कौन आशीष रहा हूँ ");
        map.put("Who  will I have been blowing ", "मैं किसको उड़ा रहा हूँ ");
        map.put("Who  will I have been breaking ", "मैं किसको तोड़ रहा हूँ ");
        map.put("Who  will I have been bringing ", "मैं कौन ला रहा हूँ ");
        map.put("Who  will I have been building ", "मैं किसका निर्माण कर रहा हूँ ");
        map.put("Who  will I have been burning ", "मैं कौन जल रहा हूँ ");
        map.put("Who  will I have been buying ", "मैं कौन खरीद रहा हूँ ");
        map.put("Who  will I have been calling ", "मैं किसे बुला रहा हूँ ");
        map.put("Who  will I have been carrying ", "मैं किसे ले जा रहा हूँ ");
        map.put("Who  will I have been catching ", "मैं किसे पकड़ रहा हूँ ");
        map.put("Who  will I have been cheating ", "मैं किसे धोखा दे रहा हूँ ");
        map.put("Who  will I have been choosing ", "मैं किसे चुन रहा हूँ ");
        map.put("Who  will I have been cleaning ", "मैं किसकी सफाई कर रहा हूँ ");
        map.put("Who  will I have been climbing ", "मैं किसपर चढ़ रहा हूँ ");
        map.put("Who  will I have been closing ", "मैं किसे बंद कर रहा हूँ ");
        map.put("Who  will I have been coming ", "मैं कौन आ रहा हूँ ");
        map.put("Who  will I have been cooking ", "मैं किसको खाना बना रहा हूँ ");
        map.put("Who  will I have been creeping ", "मैं कौन रेंग रहा हूँ ");
        map.put("Who  will I have been crying ", "मैं कौन रो रहा हूँ ");
        map.put("Who  will I have been cutting ", "मैं किसको काट रहा हूँ ");
        map.put("Who  will I have been dancing ", "मैं कौन नाच रहा हूँ ");
        map.put("Who  will I have been dealing ", "मैं किससे काम कर रहा हूँ ");
        map.put("Who  will I have been dying ", "मैं कौन मर रहा हूँ ");
        map.put("Who  will I have been digging ", "मैं किसकी खुदाई कर रहा हूँ ");
        map.put("Who  will I have been drawing ", "मैं किसको चित्रित कर रहा हूँ ");
        map.put("Who  will I have been drinking ", "मैं कौन पी रहा हूँ ");
        map.put("Who  will I have been driving ", "मैं कौन चला रहा हूँ ");
        map.put("Who  will I have been dropping ", "मैं किसको छोड़ रहा हूँ ");
        map.put("Who  will I have been drying ", "मैं किसको सुखा रहा हूँ ");
        map.put("Who  will I have been eating ", "मैं कौन खा रहा हूँ ");
        map.put("Who  will I have been electing ", "मैं किसका चुनाव कर रहा हूँ ");
        map.put("Who  will I have been entering ", "मैं किसमें प्रवेश कर रहा हूँ ");
        map.put("Who  will I have been falling ", "मैं कौन गिर रहा हूँ ");
        map.put("Who  will I have been feeding ", "मैं किसे खिला रहा हूँ ");
        map.put("Who  will I have been feeling ", "मैं कौन महसूस कर रहा हूँ ");
        map.put("Who  will I have been fighting ", "मैं किससे लड़ रहा हूँ ");
        map.put("Who  will I have been finding ", "मुझे कौन मिल रहा होगा ");
        map.put("Who  will I have been fleeing ", "मैं किससे भाग रहा हूँ ");
        map.put("Who  will I have been flying ", "मैं किससे उड़ रहा हूँ ");
        map.put("Who  will I have been forgetting ", "मैं किसको भूल गया होता ");
        map.put("Who  will I have been frying ", "मैं कौन फ्राइंग कर रहा हूँ ");
        map.put("Who  will I have been getting ", "मुझे कौन मिल रहा होगा ");
        map.put("Who  will I have been giving ", "मैं कौन दे रहा हूँ ");
        map.put("Who  will I have been going ", "मैं कौन जा रहा हूँ ");
        map.put("Who  will I have been growing ", "मैं कौन बढ़ रहा हूँ ");
        map.put("Who  will I have been hanging ", "मैं किसको लटका रहा हूँ ");
        map.put("Who  will I have been hearing ", "मैं कौन सुन रहा हूँ ");
        map.put("Who  will I have been helping ", "मैं किसकी मदद कर रहा हूँ ");
        map.put("Who  will I have been hiding ", "मैं कौन छिपा रहा हूँ ");
        map.put("Who  will I have been hitting ", "मैं किसको मार रहा हूँ ");
        map.put("Who  will I have been holding ", "मैं किसे पकड़ रहा हूँ ");
        map.put("Who  will I have been hoping ", "मैं किसकी उम्मीद कर रहा था ");
        map.put("Who  will I have been hurting ", "मैं किसको चोट पहुँचा रहा हूँ ");
        map.put("Who  will I have been jumping ", "मैं कौन कूद रहा हूँ ");
        map.put("Who  will I have been keeping ", "मैं कौन रख रहा हूँ ");
        map.put("Who  will I have been killing ", "मैं किसको मार रहा हूँ ");
        map.put("Who  will I have been knowing ", "मैं किसे जान रहा हूँ ");
        map.put("Who  will I have been laughing ", "मैं कौन हँस रहा होगा ");
        map.put("Who  will I have been leading ", "मैं किसकी अगुवाई कर रहा हूँ ");
        map.put("Who  will I have been leaping ", "मैं किससे छलांग लगा रहा हूँ ");
        map.put("Who  will I have been learning ", "मैं कौन सीख रहा हूँ ");
        map.put("Who  will I have been leaving ", "मैं किसे छोड़ रहा हूँ ");
        map.put("Who  will I have been lending ", "मैं किसे उधार दे रहा हूँ ");
        map.put("Who  will I have been living ", "मैं कौन रह रहा हूँ ");
        map.put("Who  will I have been looking ", "मैं किसे देख रहा हूँ ");
        map.put("Who  will I have been losing ", "मैं किसको खो रहा हूँ ");
        map.put("Who  will I have been loving ", "मैं किससे प्यार कर रहा हूँ ");
        map.put("Who  will I have been making ", "मैं कौन बना रहा हूँ ");
        map.put("Who  will I have been marrying ", "मैं किससे शादी कर रहा हूँ ");
        map.put("Who  will I have been meeting ", "मैं किससे मिल रहा हूँ ");
        map.put("Who  will I have been mistaking ", "मैं किससे गलत कर रहा हूँ ");
        map.put("Who  will I have been opening ", "मैं कौन खोल रहा हूँ ");
        map.put("Who  will I have been paying ", "मैं किसे भुगतान कर रहा हूँ ");
        map.put("Who  will I have been playing ", "मैं कौन खेलूंगा ");
        map.put("Who  will I have been putting ", "मैं कौन डाल रहा हूँ ");
        map.put("Who  will I have been quarrelling ", "मैं किससे झगड़ा कर रहा हूँ ");
        map.put("Who  will I have been raining ", "मैं किसकी बारिश कर रहा हूँ ");
        map.put("Who  will I have been reaching ", "मैं किसतक पहुँच रहा हूँ ");
        map.put("Who  will I have been reading ", "मैं कौन पढ़ रहा हूँ ");
        map.put("Who  will I have been remembering ", "मैं किसे याद कर रहा हूँ ");
        map.put("Who  will I have been riding ", "मैं किसकी सवारी कर रहा हूँ ");
        map.put("Who  will I have been ringing ", "मैं किससे बज रहा हूँ ");
        map.put("Who  will I have been rising ", "मैं किससे उठ रहा हूँ ");
        map.put("Who  will I have been running ", "मैं कौन दौड़ रहा हूँ ");
        map.put("Who  will I have been saying ", "मैं कौन कह रहा हूँ ");
        map.put("Who  will I have been seeing ", "मैं किसे देख रहा हूँ ");
        map.put("Who  will I have been selling ", "मैं किसे बेच रहा हूँ ");
        map.put("Who  will I have been sending ", "मैं किसे भेज रहा हूँ ");
        map.put("Who  will I have been shaking ", "मैं किसको हिला रहा हूँ ");
        map.put("Who  will I have been shining ", "मैं किससे चमक रहा हूँ ");
        map.put("Who  will I have been shooting ", "मैं किसकी शूटिंग कर रहा हूँ ");
        map.put("Who  will I have been showing ", "मैं कौन दिखा रहा हूँ ");
        map.put("Who  will I have been shutting ", "मैं किसे बंद कर रहा हूँ ");
        map.put("Who  will I have been singing ", "मैं कौन गा रहा हूँ ");
        map.put("Who  will I have been sinking ", "मैं कौन डूब रहा हूँ ");
        map.put("Who  will I have been sleeping ", "मैं कौन सो रहा हूँ ");
        map.put("Who  will I have been standing ", "मैं कौन खड़ा रहूँगा ");
        map.put("Who  will I have been weeping ", "मैं कौन रो रहा होगा ");

        return map;
    }


}

