package com.shiviishiv7.helloenglish.QuestionSource;

import java.util.HashMap;
import java.util.Map;

public class Whom {
    public static Map<String,String> Whom(int state){
        switch (state){
            case 1:return One();
            case 2:return Two();
            case 3:return Three();
            case 4:return Four();
            case 5:return Five();
            case 6:return Six();
            case 7:return Seven();
            case 8:return Eight();
            case 9:return Nine();
            case 10:return Ten();
            case 11:return Eleven();
            case 12:return Twelve();

            default:return One();
        }

    }
    static Map<String,String> One(){
        HashMap<String,String>map = new HashMap<>();
        map.put("Whom do I abuse ", "मैं किसके साथ गाली दूं ");
        map.put("Whom do I advise", "मैं किसको सलाह दूं");
        map.put("Whom do I answer ", "मैं किसका जवाब दूँ ");
        map.put("Whom do I arise ", "मैं किससे उठता हूँ ");
        map.put("Whom do I arrive ", "मैं किससे पहुँचूँ ");
        map.put("Whom do I ask ", "मैं किससे पूछूँ ");
        map.put("Whom do I awake ", "मैं किससे जाग सकता हूँ ");

        map.put("Whom do I bear ", "मैं किसको सहन करूँ ");
        map.put("Whom do I beat ", "मैं किसको हराऊं ");
        map.put("Whom do I become ", "मैं किससे बन सकता हूँ ");
        map.put("Whom do I beg ", "मैं किससे विनती करता हूँ ");
        map.put("Whom do I begin ", "मैं किससे शुरू करूँ ");
        map.put("Whom do I bind ", "मैं किससे बाँध सकता हूँ ");
        map.put("Whom do I bite", "मैं किसको काटूं");
        map.put("Whom do I bless", "मैं किसको आशीर्वाद देता हूँ");
        map.put("Whom do I blow ", "मैं किसको उड़ाऊं ");
        map.put("Whom do I break ", "मैं किसे तोड़ूँ ");
        map.put("Whom do I bring ", "मैं किसको लाऊं ");
        map.put("Whom do I build ", "मैं किसका निर्माण करूँ ");
        map.put("Whom do I burn ", "मैं किसको जलाऊं ");
        map.put("Whom do I buy ", "मैं किससे खरीदूं ");
        map.put("Whom do I call ", "मैं किसे कॉल करूँ ");
        map.put("Whom do I carry ", "मैं किसके साथ ले जाऊं ");
        map.put("Whom do I catch ", "मैं किसको पकड़ूं ");
        map.put("Whom do I choose ", "मैं किसे चुनूं ");
        map.put("Whom do I clean ", "मैं किसको साफ करूँ ");
        map.put("Whom do I climb  ", "मैं किसपर चढ़ूँ  ");
        map.put("Whom do I close ", "मैं किसको बंद करूँ ");
        map.put("Whom do I come ", "मैं किसके पास आऊं ");
        map.put("Whom do I cook ", "मैं किसको खाना बनाती हूँ ");
        map.put("Whom do I creep ", "मैं किससे रेंगता हूँ ");
        map.put("Whom do I cry ", "मैं किससे रोऊं ");
        map.put("Whom do I cut ", "मैं किसको काटूं ");
        map.put("Whom do I dance ", "मैं किससे नृत्य करता हूँ ");
        map.put("Whom do I deal ", "मैं किससे निपटूं ");
        map.put("Whom do I die ", "मैं किससे मरूं ");
        map.put("Whom do I dig ", "मैं किसको खोदूं ");
        map.put("Whom do I do ", "मैं किससे करता हूँ ");
        map.put("Whom  did I  do ", "मैंने किससे किया ");
        map.put("Whom  was I  doing ", "मैं किससे कर रहा था ");
        map.put("Whom  will I do ", "मैं किससे करूँगा ");
        map.put("Whom  had I been  doing ", "मैं किसका कर रहा था ");
        map.put("Whom  had I  done ", "मैंने किसका किया था ");
        map.put("Whom  will I be doing ", "मैं किससे कर रहा हूँ ");
        map.put("Whom  will I have done ", "मैंने किसका किया होगा ");
        map.put("Whom  will I have been doing ", "मैं किसका कर रहा हूँ ");
        map.put("Whom do I draw ", "मैं किसको आकर्षित करता हूँ ");
        map.put("Whom do I drive ", "मैं किससे चलाऊं ");
        map.put("Whom do I drop ", "मैं किसको छोड़ूँ ");
        map.put("Whom do I dry ", "मैं किसको सुखाता हूँ ");
        map.put("Whom do I eat ", "मैं किसको खाऊं ");
        map.put("Whom do I elect", "मैं किसका चुनाव करूँ");
        map.put("Whom do I fall ", "मैं किससे गिरता हूँ ");
        map.put("Whom do I feed ", "मैं किसको खिलाऊं ");
        map.put("Whom do I feel  ", "मैं किसे महसूस करता हूँ  ");
        map.put("Whom do I fight ", "मैं किससे लड़ूं ");
        map.put("Whom do I find ", "मैं किसको ढूंढूं ");
        map.put("Whom do I flee ", "मैं किससे भागता हूँ ");
        map.put("Whom do I fly  ", "मैं किससे उड़ सकता हूँ  ");
        map.put("Whom do I forget ", "मैं किसको भूल सकता हूँ ");
        map.put("Whom do I fry ", "मैं किससे भूनूं ");
        map.put("Whom do I get  ", "मुझे किससे मिलेगा  ");
        map.put("Whom do I give ", "मैं किसे दे सकता हूँ ");
        map.put("Whom do I go ", "मैं किससे जाऊँ ");
        map.put("Whom do I grow", "मैं किससे उगाऊं");
        map.put("Whom do I hang ", "मैं किसको लटकाऊं ");
        map.put("Whom do I hear ", "मैं किसको सुनूं ");
        map.put("Whom do I help ", "मैं किसकी मदद करूँ ");
        map.put("Whom do I hide ", "मैं किसे छिपाऊं ");
        map.put("Whom do I hit ", "मैं किससे मारूं ");
        map.put("Whom do I hold ", "मैं किसको पकड़ूँ ");
        map.put("Whom do I hope ", "मुझे किसकी उम्मीद है ");
        map.put("Whom do I hurt ", "मुझे किससे चोट लगी है ");
        map.put("Whom do I jump ", "मैं किससे कूदता हूँ ");
        map.put("Whom do I kill ", "मैं किसको मार सकता हूँ ");
        map.put("Whom do I know ", "मुझे किससे पता है ");
        map.put("Whom do I laugh ", "मैं किसे हँसता ");
        map.put("Whom do I lead ", "मैं किसका नेतृत्व करूँ ");
        map.put("Whom do I leap ", "मैं किससे छलांग लगाऊं ");
        map.put("Whom do I learn ", "मैं किससे सीखूं ");
        map.put("Whom do I leave ", "मैं किसको छोड़ूँ ");
        map.put("Whom do I lend ", "मैं किसे उधार दे सकता हूँ ");
        map.put("Whom do I live ", "मैं किसके साथ रहूँ ");
        map.put("Whom do I look ", "मैं किसको देखता हूँ ");
        map.put("Whom do I lose ", "मैं किसको खो सकता हूँ ");
        map.put("Whom do I love ", "मैं किससे प्यार करता हूँ ");
        map.put("Whom do I make ", "मैं किससे बनाऊं ");
        map.put("Whom do I marry ", "मैं किससे शादी करूँ ");
        map.put("Whom do I meet ", "मैं किससे मिलूं ");
        map.put("Whom do I mistake ", "मैं किसकी गलती करता हूँ ");
        map.put("Whom do I open ", "मैं किसको खोलूं ");
        map.put("Whom do I pay  ", "मैं किसका भुगतान करूँ  ");
        map.put("Whom do I play ", "मैं किससे खेलूं ");
        map.put("Whom do I put ", "मैं किसको रखूँ ");
        map.put("Whom do I rain ", "मैं किससे बारिश करता हूँ ");
        map.put("Whom do I reach ", "मैं किसतक पहुँचूँ ");
        map.put("Whom do I read", "मैं किसको पढ़ूँ");
        map.put("Whom do I remember  ", "मुझे किसको याद है  ");
        map.put("Whom do I ride ", "मैं किसकी सवारी करूँ ");
        map.put("Whom do I ring ", "मैं किससे रिंग करता हूँ ");
        map.put("Whom do I rise  ", "मैं किससे उठूँ  ");
        map.put("Whom do I run  ", "मैं किससे चलाऊँ  ");
        map.put("Whom do I say ", "मैं किससे कहूँ ");
        map.put("Whom do I see ", "मैं किसको देखूं ");
        map.put("Whom do I sell ", "मैं किसे बेचूँ ");
        map.put("Whom do I send ", "मैं किसे भेजूं ");
        map.put("Whom do I shake ", "मैं किसको हिलाता हूँ ");
        map.put("Whom do I shine ", "मैं किससे चमकता हूँ ");
        map.put("Whom do I shoot ", "मैं किसको शूट करूँ ");
        map.put("Whom do I show ", "मैं किसे दिखाऊं ");
        map.put("Whom do I shut  ", "मैं किससे बंद करूँ  ");
        map.put("Whom do I sing ", "मैं किसको गाऊं ");
        map.put("Whom do I sink ", "मैं किसको डूबता हूँ ");
        map.put("Whom do I sleep ", "मैं किससे सोता हूँ ");
        map.put("Whom do I smell ", "मुझे किसकी गंध आती है ");
        return map;
    }
    static Map<String,String> Two(){
        HashMap<String,String>map = new HashMap<>();
        map.put("Whom am I abusing ", "मैं किससे गाली दे रहा हूँ ");
        map.put("Whom am I advising ", "मैं किसको सलाह दे रहा हूँ ");
        map.put("Whom am I answering ", "मैं किसका जवाब दे रहा हूँ ");
        map.put("Whom am I arising ", "मैं किससे उठ रहा हूँ ");
        map.put("Whom am I arriving ", "मैं किससे आ रहा हूँ ");
        map.put("Whom am I asking ", "मैं किससे पूछ रहा हूँ ");
        map.put("Whom am I awaking ", "मैं किससे जाग रहा हूँ ");
        map.put("Whom am I undefined", "मैं किससे अपरिभाषित हूँ");
        map.put("Whom am I bearing ", "मैं किसका असर कर रहा हूँ ");
        map.put("Whom am I beating ", "मैं किसकी पिटाई कर रहा हूँ ");
        map.put("Whom am I becoming ", "मैं किससे बन रहा हूँ ");
        map.put("Whom am I begging ", "मैं किससे भीख मांग रहा हूँ ");
        map.put("Whom am I beginning ", "मैं किसके साथ शुरू कर रहा हूँ ");
        map.put("Whom am I binding ", "मैं किससे बाध्यकारी हूँ ");
        map.put("Whom am I biting ", "मैं किसको काट रहा हूँ ");
        map.put("Whom am I blessing ", "मैं किससे आशीर्वाद दे रहा हूँ ");
        map.put("Whom am I blowing ", "मैं किसको उड़ा रहा हूँ ");
        map.put("Whom am I breaking ", "मैं किसको तोड़ रहा हूँ ");
        map.put("Whom am I bringing ", "मैं किसको ला रहा हूँ ");
        map.put("Whom am I building ", "मैं किसका निर्माण कर रहा हूँ ");
        map.put("Whom am I burning ", "मैं किसको जला रहा हूँ ");
        map.put("Whom am I buying ", "मैं किसको खरीद रहा हूँ ");
        map.put("Whom am I calling ", "मैं किसको बुला रहा हूँ ");
        map.put("Whom am I carrying ", "मैं किसे ले जा रहा हूँ ");
        map.put("Whom am I catching ", "मैं किसको पकड़ रहा हूँ ");
        map.put("Whom am I cheating ", "मैं किसे धोखा दे रहा हूँ ");
        map.put("Whom am I choosing ", "मैं किसे चुन रहा हूँ ");
        map.put("Whom am I cleaning ", "मैं किसके लिए सफाई कर रहा हूँ ");
        map.put("Whom am I climbing ", "मैं किस पर चढ़ रहा हूँ ");
        map.put("Whom am I closing ", "मैं किसे बंद कर रहा हूँ ");
        map.put("Whom am I coming ", "मैं किससे आ रहा हूँ ");
        map.put("Whom am I cooking ", "मैं किसे खाना बना रहा हूँ ");
        map.put("Whom am I creeping ", "मैं किससे रेंग रहा हूँ ");
        map.put("Whom am I crying ", "मैं किससे रो रहा हूँ ");
        map.put("Whom am I cutting ", "मैं किसको काट रहा हूँ ");
        map.put("Whom am I dancing ", "मैं किसका नाच रहा हूँ ");
        map.put("Whom am I dealing ", "मैं किसका काम कर रहा हूँ ");
        map.put("Whom am I dying ", "मैं किससे मर रहा हूँ ");
        map.put("Whom am I digging ", "मैं किसकी खुदाई कर रहा हूँ ");
        map.put("Whom am I doing ", "मैं किसका कर रहा हूँ ");
        map.put("Whom am I drawing ", "मैं किसका चित्रण कर रहा हूँ ");
        map.put("Whom do I dream ", "मैं किसका सपना देखता हूँ ");
        map.put("Whom am I dreaming ", "मैं किसका सपना देख रहा हूँ ");
        map.put("Whom  have I dreamt ", "मैंने किसका सपना देखा है ");
        map.put("Whom  have I been dreaming ", "मैं किसका सपना देख रहा हूँ ");
        map.put("Whom  did I  dream ", "मैंने किसका सपना देखा था ");
        map.put("Whom  was I  dreaming ", "मैं किसका सपना देख रहा था ");
        map.put("Whom  had I  dreamt ", "मैंने किसका सपना देखा था ");
        map.put("Whom  had I been  dreaming ", "मैं किसका सपना देख रहा था ");
        map.put("Whom  will I be dreaming ", "मैं किसका सपना देख रहा हूँ ");
        map.put("Whom  will I have dreamt ", "मैंने किसका सपना देखा होगा ");
        map.put("Whom  will I have been dreaming ", "मैं किसका सपना देख रहा हूँ ");
        map.put("Whom am I drinking ", "मैं किससे पी रहा हूँ ");
        map.put("Whom am I driving ", "मैं किससे चला रहा हूँ ");
        map.put("Whom am I dropping ", "मैं किसको छोड़ रहा हूँ ");
        map.put("Whom am I drying ", "मैं किससे सूख रहा हूँ ");
        map.put("Whom am I eating ", "मैं किसको खा रहा हूँ ");
        map.put("Whom am I electing ", "मैं किसका चुनाव कर रहा हूँ ");
        map.put("Whom am I entering ", "मैं किसका प्रवेश कर रहा हूँ ");
        map.put("Whom am I falling ", "मैं किससे गिर रहा हूँ ");
        map.put("Whom am I feeding ", "मैं किसको खिला रहा हूँ ");
        map.put("Whom am I feeling ", "मैं किसका महसूस कर रहा हूँ ");
        map.put("Whom am I fighting ", "मैं किससे लड़ रहा हूँ ");
        map.put("Whom am I finding ", "मैं किसको खोज रहा हूँ ");
        map.put("Whom am I fleeing ", "मैं किससे भाग रहा हूँ ");
        map.put("Whom am I flying ", "मैं किससे उड़ रहा हूँ ");
        map.put("Whom am I forgetting ", "मैं किसको भूल रहा हूँ ");
        map.put("Whom am I frying ", "मैं किसको तलने वाला ");
        map.put("Whom am I getting ", "मुझे किससे मिल रहा है ");
        map.put("Whom am I giving ", "मैं किसे दे रहा हूँ ");
        map.put("Whom am I going ", "मैं किससे जा रहा हूँ ");
        map.put("Whom am I growing ", "मैं किससे बढ़ रहा हूँ ");
        map.put("Whom am I hanging ", "मैं किससे लटका रहा हूँ ");
        map.put("Whom am I hearing ", "मैं किससे सुन रहा हूँ ");
        map.put("Whom am I helping ", "मैं किसका मदद कर रहा हूँ ");
        map.put("Whom am I hiding ", "मैं किसको छिपा रहा हूँ ");
        map.put("Whom am I hitting ", "मैं किसको मार रहा हूँ ");
        map.put("Whom am I holding ", "मैं किसको पकड़ रहा हूँ ");
        map.put("Whom am I hoping ", "मैं किसका उम्मीद कर रहा हूँ ");
        map.put("Whom am I hurting ", "मैं किसको चोट पहुँचा रहा हूँ ");
        map.put("Whom am I jumping ", "मैं किससे कूद रहा हूँ ");
        map.put("Whom am I keeping ", "मैं किसको रख रहा हूँ ");
        map.put("Whom am I killing ", "मैं किसको मार रहा हूँ ");
        map.put("Whom am I knowing ", "मैं किसको जान रहा हूँ ");
        map.put("Whom am I laughing ", "मैं किससे हँस रहा हूँ ");
        map.put("Whom am I leading ", "मैं किसका नेतृत्व कर रहा हूँ ");
        map.put("Whom am I leaping ", "मैं किससे छलांग लगा रहा हूँ ");
        map.put("Whom am I learning ", "मैं किससे सीख रहा हूँ ");
        map.put("Whom am I leaving ", "मैं किसको छोड़ रहा हूँ ");
        map.put("Whom am I lending ", "मैं किसे उधार दे रहा हूँ ");
        map.put("Whom am I living ", "मैं किससे जी रहा हूँ ");
        map.put("Whom am I looking ", "मैं किसको देख रहा हूँ ");
        map.put("Whom am I losing ", "मैं किसको खो रहा हूँ ");
        map.put("Whom am I loving ", "मैं किससे प्यार करता हूँ ");
        map.put("Whom am I making ", "मैं किससे बना रहा हूँ ");
        map.put("Whom am I marrying ", "मैं किससे शादी कर रहा हूँ ");
        map.put("Whom am I meeting ", "मैं किससे मिल रहा हूँ ");
        map.put("Whom am I mistaking ", "मैं किसकी गलती कर रहा हूँ ");
        map.put("Whom am I opening ", "मैं किसको खोल रहा हूँ ");
        map.put("Whom am I paying ", "मैं किसका भुगतान कर रहा हूँ ");
        map.put("Whom am I playing ", "मैं किससे खेल रहा हूँ ");
        map.put("Whom am I putting ", "मैं किसको डाल रहा हूँ ");
        map.put("Whom am I quarrelling ", "मैं किससे झगड़ा कर रहा हूँ ");
        map.put("Whom am I raining ", "मैं किसकी बारिश कर रहा हूँ ");
        map.put("Whom am I reaching ", "मैं किसतक पहुँच रहा हूँ ");
        map.put("Whom am I reading ", "मैं किसको पढ़ रहा हूँ ");
        map.put("Whom am I remembering ", "मैं किसे याद कर रहा हूँ ");
        map.put("Whom am I riding ", "मैं किसके साथ सवारी कर रहा हूँ ");
        map.put("Whom am I ringing ", "मैं किससे बज रहा हूँ ");
        map.put("Whom am I rising ", "मैं किसका उठ रहा हूँ ");
        map.put("Whom am I running ", "मैं किससे भाग रहा हूँ ");
        map.put("Whom am I saying ", "मैं किससे कह रहा हूँ ");
        map.put("Whom am I seeing ", "मैं किसको देख रहा हूँ ");
        map.put("Whom am I selling ", "मैं किसे बेच रहा हूँ ");
        map.put("Whom am I sending ", "मैं किसको भेज रहा हूँ ");
        map.put("Whom am I shaking ", "मैं किसको हिला रहा हूँ ");
        map.put("Whom am I shining ", "मैं किससे चमक रहा हूँ ");
        map.put("Whom am I shooting ", "मैं किसके साथ शूटिंग कर रहा हूँ ");
        map.put("Whom am I showing ", "मैं किसे दिखा रहा हूँ ");
        map.put("Whom am I shutting ", "मैं किसको बंद कर रहा हूँ ");
        map.put("Whom am I singing ", "मैं किसको गा रहा हूँ ");
        map.put("Whom am I sinking ", "मैं किससे डूब रहा हूँ ");
        map.put("Whom am I sleeping ", "मैं किससे सो रहा हूँ ");
        map.put("Whom am I smelling ", "मैं किससे सूँघ रहा हूँ ");
        map.put("Whom am I teaching ", "मैं किसको पढ़ा रहा हूँ ");

        return map;
    }
    static Map<String,String> Three(){
        HashMap<String,String>map = new HashMap<>();
        map.put("Whom  have I abused ", "मैंने किसके साथ दुर्व्यवहार किया है ");
        map.put("Whom  have I advised ", "मैंने किसको सलाह दी है ");
        map.put("Whom  have I answered ", "मैंने किसका उत्तर दिया है ");
        map.put("Whom  have I arisen ", "मैं किससे पैदा हुआ हूँ ");
        map.put("Whom  have I arrived ", "मैं किसके पास आया हूँ ");
        map.put("Whom  have I asked ", "मैंने किससे पूछा है ");
        map.put("Whom  have I awoken ", "मैं किससे जाग गया हूँ ");
        map.put("Whom  have I undefined", "मैंने किसको अपरिभाषित किया है");
        map.put("Whom  have I borne ", "मैंने किसको जन्म दिया है ");
        map.put("Whom  have I beaten ", "मैंने किसको पीटा है ");
        map.put("Whom  have I become ", "मैं किससे बन गया हूँ ");
        map.put("Whom  have I begged ", "मैंने किससे भीख माँगी ");
        map.put("Whom  have I begun ", "मैंने किससे शुरू किया है ");
        map.put("Whom  have I bound ", "मैंने किससे बाध्य किया है ");
        map.put("Whom  have I bitten ", "मैंने किसको काट लिया है ");
        map.put("Whom  have I blessed ", "मैंने किसको आशीर्वाद दिया है ");
        map.put("Whom  have I blown ", "मैंने किसको उड़ा दिया है ");
        map.put("Whom  have I broken ", "मैंने किसको तोड़ा है ");
        map.put("Whom  have I brought ", "मैं किसके लिए लाया हूँ ");
        map.put("Whom  have I built ", "मैंने किसका निर्माण किया है ");
        map.put("Whom  have I burnt ", "मैंने किसको जला दिया है ");
        map.put("Whom  have I bought ", "मैंने किसको खरीदा है ");
        map.put("Whom  have I called ", "मैंने किसे फोन किया है ");
        map.put("Whom  have I carried ", "मैंने किसको ले लिया है ");
        map.put("Whom  have I caught ", "मैंने किसे पकड़ा है ");
        map.put("Whom  have I cheated ", "मैंने किसके साथ धोखा किया है ");
        map.put("Whom  have I chosen ", "मैंने किसे चुना है ");
        map.put("Whom  have I cleaned ", "मैंने किसको साफ किया है ");
        map.put("Whom  have I climbed ", "मैं किसके ऊपर चढ़ गया हूँ ");
        map.put("Whom  have I closed ", "मैंने किसको बंद किया है ");
        map.put("Whom  have I come ", "मैं किसके पास आया हूँ ");
        map.put("Whom  have I cooked ", "मैंने किसको पकाया है ");
        map.put("Whom  have I crept ", "मैंने किसके पास crept किया है ");
        map.put("Whom  have I cried ", "मैंने किसको रोया है ");
        map.put("Whom  have I cut ", "मैंने किसको काट दिया है ");
        map.put("Whom  have I danced ", "मैंने किसका नृत्य किया है ");
        map.put("Whom  have I dealt ", "मैंने किससे निपटा है ");
        map.put("Whom  have I died ", "मैं किसकी मर चुका हूँ ");
        map.put("Whom  have I dug ", "मैंने किसको खोदा है ");
        map.put("Whom  have I done ", "मैंने किसका किया है ");
        map.put("Whom  have I drawn ", "मैंने किसको खींचा है ");
        map.put("Whom  have I drunk ", "मैंने किसको पिया है ");
        map.put("Whom  have I driven ", "मैंने किसको चलाया है ");
        map.put("Whom  have I dropped ", "मैंने किसको गिरा दिया है ");
        map.put("Whom  have I dried ", "मैंने किसको सुखाया है ");
        map.put("Whom  have I eaten ", "मैंने किसका खाया है ");
        map.put("Whom  have I elected ", "मैंने किसे चुना है ");
        map.put("Whom  have I entered ", "मैंने किसमें प्रवेश किया है ");
        map.put("Whom  have I fallen ", "मैं किससे गिर गया हूँ ");
        map.put("Whom  have I fed ", "मैंने किसको खिलाया है ");
        map.put("Whom  have I felt ", "मैंने किसका महसूस किया है ");
        map.put("Whom  have I fought ", "मैंने किससे लड़ाई लड़ी है ");
        map.put("Whom  have I found ", "मैंने किसको पाया है ");
        map.put("Whom  have I fled ", "मैं किससे भाग गया हूँ ");
        map.put("Whom  have I flown ", "मैंने किसको उड़ाया है ");
        map.put("Whom  have I forgotten ", "मैं किसे भूल गया हूँ ");
        map.put("Whom  have I fried ", "मैंने किसको तला है ");
        map.put("Whom  have I got ", "मुझे किसके पास मिला है ");
        map.put("Whom  have I given ", "मैंने किसे दिया है ");
        map.put("Whom  have I gone ", "मैं किसके पास गया हूँ ");
        map.put("Whom  have I grown ", "मैं किससे उगाया हूँ ");
        map.put("Whom  have I hanged ", "मैंने किसको फांसी दी है ");
        map.put("Whom  have I hung ", "मैंने किसको लटका दिया है ");
        map.put("Whom  have I heard ", "मैंने किसके बारे में सुना है ");
        map.put("Whom  have I helped ", "मैंने किसकी मदद की है ");
        map.put("Whom  have I hidden ", "मैंने किसको छुपाया है ");
        map.put("Whom  have I hit ", "मैंने किसको मारा है ");
        map.put("Whom  have I held ", "मैंने किसके पास रखा है ");
        map.put("Whom  have I hoped ", "मैंने किसकी उम्मीद की है ");
        map.put("Whom  have I hurt ", "मुझे किससे चोट लगी है ");
        map.put("Whom  have I jumped ", "मैं किससे कूद गया हूँ ");
        map.put("Whom  have I kept ", "मैंने किसे रखा है ");
        map.put("Whom  have I killed ", "मैंने किसको मार डाला है ");
        map.put("Whom  have I known ", "मैं किससे जानता हूँ ");
        map.put("Whom  have I laughed ", "मैं किससे हँसा हूँ ");
        map.put("Whom  have I led ", "मैंने किसका नेतृत्व किया है ");
        map.put("Whom  have I leapt ", "मैंने किससे छलांग लगाई है ");
        map.put("Whom  have I learnt ", "मैंने किससे सीखा है ");
        map.put("Whom  have I left ", "मैंने किसको छोड़ा है ");
        map.put("Whom  have I lent ", "मैंने किसे उधार दिया है ");
        map.put("Whom  have I lived ", "मैं किससे रहता हूँ ");
        map.put("Whom  have I looked ", "मैंने किसको देखा है ");
        map.put("Whom  have I lost ", "मैंने किसको खो दिया है ");
        map.put("Whom  have I loved ", "मैंने किससे प्यार किया है ");
        map.put("Whom  have I made ", "मैंने किसे बनाया है ");
        map.put("Whom  have I married ", "मैंने किससे शादी की है ");
        map.put("Whom  have I met ", "मैं किससे मिला हूँ ");
        map.put("Whom  have I mistaken ", "मैंने किससे गलत किया है ");
        map.put("Whom  have I opened ", "मैंने किसे खोला है ");
        map.put("Whom  have I paid ", "मैंने किसका भुगतान किया है ");
        map.put("Whom  have I played ", "मैंने किसका खेला है ");
        map.put("Whom  have I put ", "मैंने किसे रखा है ");
        map.put("Whom  have I quarrelled ", "मैंने किससे झगड़ा किया है ");
        map.put("Whom  have I rained ", "मैंने किसकी बारिश की है ");
        map.put("Whom  have I reached ", "मैं किसके पास पहुँचा हूँ ");
        map.put("Whom  have I read ", "मैंने किसको पढ़ा है ");
        map.put("Whom  have I remembered ", "मुझे किसकी याद है ");
        map.put("Whom  have I ridden ", "मैंने किसकी सवारी की है ");
        map.put("Whom  have I rung ", "मैंने किसको बजाया है ");
        map.put("Whom  have I risen ", "मैं किससे उठ गया ");
        map.put("Whom  have I run ", "मैंने किसको चलाया है ");
        map.put("Whom  have I said ", "मैंने किससे कहा है ");
        map.put("Whom  have I seen ", "मैंने किसे देखा है ");
        map.put("Whom  have I sold ", "मैंने किसे बेचा है ");
        map.put("Whom  have I sent ", "मैंने किसे भेजा है ");
        map.put("Whom  have I shaken ", "मैंने किसको हिला दिया है ");
        map.put("Whom  have I shone ", "मैंने किसको चमकाया है ");
        map.put("Whom  have I shot ", "मैंने किसको गोली मारी है ");
        map.put("Whom  have I shown ", "मैंने किसे दिखाया है ");
        map.put("Whom  have I shut ", "मैंने किसको बंद किया है ");
        map.put("Whom  have I sung ", "मैंने किसको गाया है ");
        map.put("Whom  have I sunk ", "मैं किससे डूब गया हूँ ");
        map.put("Whom  have I slept ", "मैं किससे सोया हूँ ");
        map.put("Whom  have I smelt ", "मैंने किसको पिघलाया है ");

        return map;
    }
    static Map<String,String> Four(){
        HashMap<String,String>map = new HashMap<>();
        map.put("Whom  have I been abusing ", "मैं किससे गाली दे रहा हूँ ");
        map.put("Whom  have I been advising ", "मैं किसको सलाह दे रहा हूं ");
        map.put("Whom  have I been answering ", "मैं किसका जवाब दे रहा हूं ");
        map.put("Whom  have I been arising ", "मैं किससे उठ रहा हूँ ");
        map.put("Whom  have I been arriving ", "मैं किसके पास आ रहा हूँ ");
        map.put("Whom  have I been asking ", "मैं किससे पूछ रहा हूँ ");
        map.put("Whom  have I been awaking ", "मैं किससे जाग रहा हूँ ");
        map.put("Whom  have I been undefined", "मैं किससे अपरिभाषित रहा हूँ");
        map.put("Whom  have I been bearing ", "मैं किसका असर कर रहा हूँ ");
        map.put("Whom  have I been beating ", "मैं किसकी पिटाई कर रहा हूँ ");
        map.put("Whom  have I been becoming ", "मैं किससे बन रहा हूँ ");
        map.put("Whom  have I been begging ", "मैं किससे भीख माँग रहा हूँ ");
        map.put("Whom  have I been beginning ", "मैं किसकी शुरुआत कर रहा हूँ ");
        map.put("Whom  have I been binding ", "मैं किससे बाध्यकारी रहा हूँ ");
        map.put("Whom  have I been biting ", "मैं किसको काट रहा हूँ ");
        map.put("Whom  have I been blessing ", "मैं किससे आशीष रहा हूँ ");
        map.put("Whom  have I been blowing ", "मैं किससे उड़ा रहा हूँ ");
        map.put("Whom  have I been breaking ", "मैं किसको तोड़ रहा हूँ ");
        map.put("Whom  have I been bringing ", "मैं किसको ला रहा हूँ ");
        map.put("Whom  have I been building ", "मैं किसका निर्माण कर रहा हूँ ");
        map.put("Whom  have I been burning ", "मैं किससे जल रहा हूँ ");
        map.put("Whom  have I been buying ", "मैं किसको खरीद रहा हूँ ");
        map.put("Whom  have I been calling ", "मैं किसको बुला रहा हूँ ");
        map.put("Whom  have I been carrying ", "मैं किसको ले जा रहा हूँ ");
        map.put("Whom  have I been catching ", "मैं किसको पकड़ रहा हूँ ");
        map.put("Whom  have I been cheating ", "मैं किसको धोखा दे रहा हूँ ");
        map.put("Whom  have I been choosing ", "मैं किसे चुन रहा हूँ ");
        map.put("Whom  have I been cleaning ", "मैं किसकी सफाई कर रहा हूँ ");
        map.put("Whom  have I been climbing ", "मैं किसपर चढ़ रहा हूँ ");
        map.put("Whom  have I been closing ", "मैं किसको बंद कर रहा हूँ ");
        map.put("Whom  have I been coming ", "मैं किसके पास आ रहा हूँ ");
        map.put("Whom  have I been cooking ", "मैं किससे खाना बना रहा हूँ ");
        map.put("Whom  have I been creeping ", "मैं किससे रेंग रहा हूँ ");
        map.put("Whom  have I been crying ", "मैं किससे रो रहा हूँ ");
        map.put("Whom  have I been cutting ", "मैं किसको काट रहा हूँ ");
        map.put("Whom  have I been dancing ", "मैं किससे नाच रहा हूँ ");
        map.put("Whom  have I been dealing ", "मैं किससे काम कर रहा हूं ");
        map.put("Whom  have I been dying ", "मैं किससे मर रहा हूँ ");
        map.put("Whom  have I been digging ", "मैं किसकी खुदाई कर रहा हूँ ");
        map.put("Whom  have I been doing ", "मैं किसका कर रहा हूँ ");
        map.put("Whom  have I been drawing ", "मैं किसको चित्रित कर रहा हूँ ");
        map.put("Whom  have I been drinking ", "मैं किससे पी रहा हूँ ");
        map.put("Whom  have I been driving ", "मैं किससे चला रहा हूँ ");
        map.put("Whom  have I been dropping ", "मैं किसको छोड़ रहा हूँ ");
        map.put("Whom  have I been drying ", "मैं किसको सुखा रहा हूँ ");
        map.put("Whom  have I been eating ", "मैं किसका खा रहा हूँ ");
        map.put("Whom  have I been electing ", "मैं किसका चुनाव कर रहा हूँ ");
        map.put("Whom  have I been entering ", "मैं किसमें प्रवेश कर रहा हूँ ");
        map.put("Whom  have I been falling ", "मैं किससे गिर रहा हूँ ");
        map.put("Whom  have I been feeding ", "मैं किसको खिला रहा हूँ ");
        map.put("Whom  have I been feeling ", "मैं किसका महसूस कर रहा हूँ ");
        map.put("Whom  have I been fighting ", "मैं किससे लड़ रहा हूँ ");
        map.put("Whom  have I been finding ", "मैं किसको ढूंढ रहा हूं ");
        map.put("Whom  have I been fleeing ", "मैं किससे भाग रहा हूँ ");
        map.put("Whom  have I been flying ", "मैं किससे उड़ रहा हूँ ");
        map.put("Whom  have I been forgetting ", "मैं किसको भूल रहा हूँ ");
        map.put("Whom  have I been frying ", "मैं किससे तलने गया हूँ ");
        map.put("Whom  have I been getting ", "मुझे किससे मिल रहा है ");
        map.put("Whom  have I been giving ", "मैं किसे दे रहा हूँ ");
        map.put("Whom  have I been going ", "मैं किससे जा रहा हूँ ");
        map.put("Whom  have I been growing ", "मैं किसका विकास कर रहा हूँ ");
        map.put("Whom  have I been hanging ", "मैं किससे लटक रहा हूँ ");
        map.put("Whom  have I been hearing ", "मैं किससे सुन रहा हूँ ");
        map.put("Whom  have I been helping ", "मैं किसकी मदद कर रहा हूँ ");
        map.put("Whom  have I been hiding ", "मैं किसको छिपा रहा हूँ ");
        map.put("Whom  have I been hitting ", "मैं किससे मार रहा हूँ ");
        map.put("Whom  have I been holding ", "मैं किसको पकड़ रहा हूँ ");
        map.put("Whom  have I been hoping ", "मैं किसकी उम्मीद कर रहा था ");
        map.put("Whom  have I been hurting ", "मैं किसको चोट पहुँचा रहा हूँ ");
        map.put("Whom  have I been jumping ", "मैं किससे कूद रहा हूँ ");
        map.put("Whom  have I been keeping ", "मैं किसको रख रहा हूँ ");
        map.put("Whom  have I been killing ", "मैं किसको मार रहा हूँ ");
        map.put("Whom  have I been knowing ", "मैं किसको जान रहा हूँ ");
        map.put("Whom  have I been laughing ", "मैं किससे हँस रहा हूँ ");
        map.put("Whom  have I been leading ", "मैं किसका नेतृत्व कर रहा हूँ ");
        map.put("Whom  have I been leaping ", "मैं किससे छलांग लगा रहा हूँ ");
        map.put("Whom  have I been learning ", "मैं किससे सीख रहा हूँ ");
        map.put("Whom  have I been leaving ", "मैं किसको छोड़ रहा हूँ ");
        map.put("Whom  have I been lending ", "मैं किसे उधार दे रहा हूँ ");
        map.put("Whom  have I been living ", "मैं किससे रह रहा हूँ ");
        map.put("Whom  have I been looking ", "मैं किसको देख रहा हूँ ");
        map.put("Whom  have I been losing ", "मैं किसको खो रहा हूँ ");
        map.put("Whom  have I been loving ", "मैं किससे प्यार कर रहा हूँ ");
        map.put("Whom  have I been making ", "मैं किसका बना रहा हूँ ");
        map.put("Whom  have I been marrying ", "मैं किससे शादी कर रहा हूँ ");
        map.put("Whom  have I been meeting ", "मैं किससे मिल रहा हूँ ");
        map.put("Whom  have I been mistaking ", "मैं किससे गलत कर रहा हूँ ");
        map.put("Whom  have I been opening ", "मैं किसका खोल रहा हूँ ");
        map.put("Whom  have I been paying ", "मैं किसका भुगतान कर रहा हूँ ");
        map.put("Whom  have I been playing ", "मैं किसका खेल रहा हूँ ");
        map.put("Whom  have I been putting ", "मैं किसको लगा रहा हूँ ");
        map.put("Whom  have I been quarrelling ", "मैं किससे झगड़ा कर रहा हूँ ");
        map.put("Whom  have I been raining ", "मैं किससे बारिश कर रहा हूँ ");
        map.put("Whom  have I been reaching ", "मैं किसतक पहुँच रहा हूँ ");
        map.put("Whom  have I been reading ", "मैं किसको पढ़ रहा हूँ ");
        map.put("Whom  have I been remembering ", "मैं किसे याद कर रहा हूँ ");
        map.put("Whom  have I been riding ", "मैं किसकी सवारी कर रहा हूँ ");
        map.put("Whom  have I been ringing ", "मैं किससे बज रहा हूँ ");
        map.put("Whom  have I been rising ", "मैं किससे उठ रहा हूँ ");
        map.put("Whom  have I been running ", "मैं किससे भाग रहा हूँ ");
        map.put("Whom  have I been saying ", "मैं किससे कह रहा हूँ ");
        map.put("Whom  have I been seeing ", "मैं किसे देख रहा हूँ ");
        map.put("Whom  have I been selling ", "मैं किसे बेच रहा हूँ ");
        map.put("Whom  have I been sending ", "मैं किसको भेज रहा हूँ ");
        map.put("Whom  have I been shaking ", "मैं किसको हिला रहा हूँ ");
        map.put("Whom  have I been shining ", "मैं किससे चमक रहा हूँ ");
        map.put("Whom  have I been shooting ", "मैं किसकी शूटिंग कर रहा हूँ ");
        map.put("Whom  have I been showing ", "मैं किसे दिखा रहा हूँ ");
        map.put("Whom  have I been shutting ", "मैं किसको बंद कर रहा हूँ ");
        map.put("Whom  have I been singing ", "मैं किसका गा रहा हूँ ");
        map.put("Whom  have I been sinking ", "मैं किससे डूब रहा हूँ ");
        map.put("Whom  have I been sleeping ", "मैं किससे सो रहा हूँ ");
        map.put("Whom  have I been smelling ", "मैं किससे सूँघ रहा हूँ ");
        map.put("Whom  have I been stealing ", "मैं किससे चुरा रहा हूँ ");

        return map;
    }
    static Map<String,String> Five(){
        HashMap<String,String>map = new HashMap<>();
        map.put("Whom  did I  abuse ", "मैंने किसके साथ गाली दी ");
        map.put("Whom  did I  advise", "मैंने किसको सलाह दी");
        map.put("Whom  did I  answer ", "मैंने किसका जवाब दिया ");
        map.put("Whom  did I  arise ", "मैं किससे उठी ");
        map.put("Whom  did I  arrive ", "मैं किसके पास आया ");
        map.put("Whom  did I  ask ", "मैंने किससे पूछा ");
        map.put("Whom  did I  awake ", "मैंने किसको जगाया था ");
        map.put("Whom  did I  \r", "मैंने किससे किया था  \r");
        map.put("Whom  did I  beat ", "मैंने किसको हराया ");
        map.put("Whom  did I  become ", "मैं किससे बन गया ");
        map.put("Whom  did I  beg ", "मैंने किससे भीख माँगी ");
        map.put("Whom  did I  begin ", "मैंने किससे शुरू किया ");
        map.put("Whom  did I  bind ", "मैंने किसको बाँध दिया ");
        map.put("Whom  did I  bite", "मैंने किसको काट लिया");
        map.put("Whom  did I  bless", "मैंने किसको आशीर्वाद दिया");
        map.put("Whom  did I  blow ", "मैंने किसको उड़ा दिया ");
        map.put("Whom  did I  break ", "मैंने किसको तोड़ा ");
        map.put("Whom  did I  bring ", "मैं किसको लाया था ");
        map.put("Whom  did I  build ", "मैंने किसका निर्माण किया ");
        map.put("Whom  did I  burn ", "मैंने किसको जला दिया ");
        map.put("Whom  did I  buy ", "मैंने किसको खरीदा ");
        map.put("Whom  did I  call ", "मैंने किसे फोन किया ");
        map.put("Whom  did I  carry ", "मैं किसको ले गया था ");
        map.put("Whom  did I  catch ", "मैंने किसको पकड़ लिया ");
        map.put("Whom  did I  cheat ", "मैंने किसको धोखा दिया ");
        map.put("Whom  did I  choose ", "मैंने किसे चुना ");
        map.put("Whom  did I  clean ", "मैंने किसको साफ किया ");
        map.put("Whom  did I  climb  ", "मैं किसपर चढ़ गया  ");
        map.put("Whom  did I  close ", "मैंने किसको बंद किया था ");
        map.put("Whom  did I  come ", "मैं किससे आया ");
        map.put("Whom  did I  cook ", "मैंने किसको खाना बनाया ");
        map.put("Whom  did I  creep ", "मैंने किसको रेंगना था ");
        map.put("Whom  did I  cut ", "मैंने किसको काट दिया ");
        map.put("Whom  did I  dance ", "मैंने किससे नृत्य किया ");
        map.put("Whom  did I  deal ", "मैंने किसका सौदा किया ");
        map.put("Whom  did I  die ", "मैं किससे मर गया ");
        map.put("Whom  did I  dig ", "मैंने किसको खोदा ");
        map.put("Whom  did I  draw ", "मैंने किसको आकर्षित किया ");
        map.put("Whom  did I  drive ", "मैंने किससे ड्राइव किया ");
        map.put("Whom  did I  drop ", "मैंने किसको छोड़ दिया ");
        map.put("Whom  did I  dry ", "मैंने किसको सुखाया ");
        map.put("Whom  did I  eat ", "मैंने किसको खाया ");
        map.put("Whom  did I  elect", "मैंने किसका चुनाव किया");
        map.put("Whom  did I  enter ", "मैंने किसमें प्रवेश किया ");
        map.put("Whom  did I  fall ", "मैं किससे गिर गया ");
        map.put("Whom  did I  feed ", "मैंने किसको खाना खिलाया ");
        map.put("Whom  did I  feel  ", "मैंने किसका महसूस किया  ");
        map.put("Whom  did I  fight ", "मैंने किससे लड़ाई की ");
        map.put("Whom  did I  find ", "मुझे किससे मिला ");
        map.put("Whom  did I  flee ", "मैं किससे भागा ");
        map.put("Whom  did I  fly  ", "मैंने किससे उड़ान भरी  ");
        map.put("Whom  did I  fry ", "मैंने किसको फ्राई किया ");
        map.put("Whom  did I  get  ", "मुझे किससे मिला  ");
        map.put("Whom  did I  give ", "मैंने किसको दिया ");
        map.put("Whom  did I  go ", "मैं किससे गया ");
        map.put("Whom  did I  grow", "मैं किससे उगाया");
        map.put("Whom  did I  hang ", "मैंने किसको लटका दिया ");
        map.put("Whom  did I  hear ", "मैंने किसको सुना ");
        map.put("Whom  did I  help ", "मैंने किसकी मदद की ");
        map.put("Whom  did I  hide ", "मैंने किसको छुपाया ");
        map.put("Whom  did I  hit ", "मैंने किसको मारा ");
        map.put("Whom  did I  hold ", "मैंने किसको पकड़ लिया ");
        map.put("Whom  did I  hope ", "मुझे किसकी उम्मीद थी ");
        map.put("Whom  did I  hurt ", "मैंने किसको चोट पहुंचाई ");
        map.put("Whom  did I  jump ", "मैंने किससे छलांग लगाई ");
        map.put("Whom  did I  keep ", "मैंने किसको रखा ");
        map.put("Whom  did I  kill ", "मैंने किसको मार डाला ");
        map.put("Whom  did I  know ", "मुझे किससे पता था ");
        map.put("Whom  did I  laugh ", "मैं किससे हँसा ");
        map.put("Whom  did I  lead ", "मैंने किसका नेतृत्व किया ");
        map.put("Whom  did I  leap ", "मैंने किसकी छलांग लगाई ");
        map.put("Whom  did I  learn ", "मैंने किससे सीखा ");
        map.put("Whom  did I  leave ", "मैंने किसको छोड़ा था ");
        map.put("Whom  did I  live ", "मैं किससे रहता था ");
        map.put("Whom  did I  look ", "मैंने किसको देखा ");
        map.put("Whom  did I  lose ", "मैंने किसको खो दिया ");
        map.put("Whom  did I  love ", "मुझे किससे प्यार था ");
        map.put("Whom  did I  make ", "मैंने किसको बनाया ");
        map.put("Whom  did I  marry ", "मैंने किससे शादी की ");
        map.put("Whom  did I  meet ", "मैं किससे मिला था ");
        map.put("Whom  did I  mistake ", "मैंने किससे गलती की ");
        map.put("Whom  did I  open ", "मैंने किसको खोल दिया ");
        map.put("Whom  did I  pay  ", "मैंने किसका भुगतान किया  ");
        map.put("Whom  did I  play ", "मैंने किसकी भूमिका निभाई ");
        map.put("Whom  did I  put ", "मैंने किसको रखा था ");
        map.put("Whom  did I  quarrel ", "मैंने किससे झगड़ा किया ");
        map.put("Whom  did I  rain ", "मैंने किसकी बारिश की ");
        map.put("Whom  did I  reach ", "मैं किसतक पहुँचा ");
        map.put("Whom  did I  read", "मैंने किसको पढ़ा");
        map.put("Whom  did I  remember  ", "मुझे किसको याद था  ");
        map.put("Whom  did I  ride ", "मैंने किसकी सवारी की ");
        map.put("Whom  did I  ring ", "मैंने किससे रिंग की ");
        map.put("Whom  did I  rise  ", "मैं किससे उठ गया  ");
        map.put("Whom  did I  say ", "मैंने किससे कहा ");
        map.put("Whom  did I  see ", "मैंने किसको देखा ");
        map.put("Whom  did I  sell ", "मैंने किसको बेच दिया ");
        map.put("Whom  did I  send ", "मैंने किसे भेजा था ");
        map.put("Whom  did I  shake ", "मैंने किसको हिला दिया ");
        map.put("Whom  did I  shine ", "मैं किससे चमका ");
        map.put("Whom  did I  shoot ", "मैंने किसको गोली मारी ");
        map.put("Whom  did I  show ", "मैंने किसे दिखाया ");
        map.put("Whom  did I  shut  ", "मैंने किसको बंद किया  ");
        map.put("Whom  did I  sing ", "मैंने किसको गाया था ");
        map.put("Whom  did I  sink ", "मैंने किसको डुबो दिया ");
        map.put("Whom  did I  sleep ", "मैं किससे सोता था ");
        map.put("Whom  did I  smell ", "मुझे किसकी गंध आई ");
        map.put("Whom  did I  throw ", "मैंने किसको फेंक दिया ");

        return map;
    }
    static Map<String,String> Six(){
        HashMap<String,String>map = new HashMap<>();
        map.put("Whom  was I  abusing ", "मैं किससे गाली दे रहा था ");
        map.put("Whom  was I  advising ", "मैं किसको सलाह दे रहा था ");
        map.put("Whom  was I  answering ", "मैं किसका जवाब दे रहा था ");
        map.put("Whom  was I  arising ", "मैं किससे उठ रहा था ");
        map.put("Whom  was I  arriving ", "मैं किससे आ रहा था ");
        map.put("Whom  was I  asking ", "मैं किससे पूछ रहा था ");
        map.put("Whom  was I  awaking ", "मैं किससे जाग रहा था ");
        map.put("Whom  was I  undefined", "मैं किससे अपरिभाषित था");
        map.put("Whom  was I  bearing ", "मैं किसका असर कर रहा था ");
        map.put("Whom  was I  beating ", "मैं किसकी पिटाई कर रहा था ");
        map.put("Whom  was I  becoming ", "मैं किससे बन रहा था ");
        map.put("Whom  was I  begging ", "मैं किससे भीख मांग रहा था ");
        map.put("Whom  was I  beginning ", "मैं किसका शुरू कर रहा था ");
        map.put("Whom  was I  binding ", "मैं किससे बाध्यकारी था ");
        map.put("Whom  was I  biting ", "मैं किसको काट रहा था ");
        map.put("Whom  was I  blessing ", "मैं किससे आशीर्वाद दे रहा था ");
        map.put("Whom  was I  blowing ", "मैं किसको उड़ा रहा था ");
        map.put("Whom  was I  breaking ", "मैं किसको तोड़ रहा था ");
        map.put("Whom  was I  bringing ", "मैं किसको ला रहा था ");
        map.put("Whom  was I  building ", "मैं किसका निर्माण कर रहा था ");
        map.put("Whom  was I  burning ", "मैं किससे जल रहा था ");
        map.put("Whom  was I  buying ", "मैं किसको खरीद रहा था ");
        map.put("Whom  was I  calling ", "मैं किसको बुला रहा था ");
        map.put("Whom  was I  carrying ", "मैं किसे ले जा रहा था ");
        map.put("Whom  was I  catching ", "मैं किसको पकड़ रहा था ");
        map.put("Whom  was I  cheating ", "मैं किसे धोखा दे रहा था ");
        map.put("Whom  was I  choosing ", "मैं किसे चुन रहा था ");
        map.put("Whom  was I  cleaning ", "मैं किसका सफाई कर रहा था ");
        map.put("Whom  was I  climbing ", "मैं किस पर चढ़ रहा था ");
        map.put("Whom  was I  closing ", "मैं किसे बंद कर रहा था ");
        map.put("Whom  was I  coming ", "मैं किससे आ रहा था ");
        map.put("Whom  was I  cooking ", "मैं किसका खाना बना रहा था ");
        map.put("Whom  was I  creeping ", "मैं किससे रेंग रहा था ");
        map.put("Whom  was I  crying ", "मैं किससे रो रहा था ");
        map.put("Whom  was I  cutting ", "मैं किसको काट रहा था ");
        map.put("Whom  was I  dancing ", "मैं किसका नाच रहा था ");
        map.put("Whom  was I  dealing ", "मैं किसका काम कर रहा था ");
        map.put("Whom  was I  dying ", "मैं किससे मर रहा था ");
        map.put("Whom  was I  digging ", "मैं किसकी खुदाई कर रहा था ");
        map.put("Whom  was I  drawing ", "मैं किसका चित्रण कर रहा था ");
        map.put("Whom  was I  drinking ", "मैं किससे पी रहा था ");
        map.put("Whom  was I  driving ", "मैं किससे चला रहा था ");
        map.put("Whom  was I  dropping ", "मैं किसको छोड़ रहा था ");
        map.put("Whom  was I  drying ", "मैं किससे सूख रहा था ");
        map.put("Whom  was I  eating ", "मैं किससे खा रहा था ");
        map.put("Whom  was I  electing ", "मैं किसका चुनाव कर रहा था ");
        map.put("Whom  was I  entering ", "मैं किसका प्रवेश कर रहा था ");
        map.put("Whom  was I  falling ", "मैं किससे गिर रहा था ");
        map.put("Whom  was I  feeding ", "मैं किसको खिला रहा था ");
        map.put("Whom  was I  feeling ", "मैं किसका महसूस कर रहा था ");
        map.put("Whom  was I  fighting ", "मैं किससे लड़ रहा था ");
        map.put("Whom  was I  finding ", "मैं किसको खोज रहा था ");
        map.put("Whom  was I  fleeing ", "मैं किससे भाग रहा था ");
        map.put("Whom  was I  flying ", "मैं किससे उड़ रहा था ");
        map.put("Whom  was I  forgetting ", "मैं किसको भूल रहा था ");
        map.put("Whom  was I  frying ", "मैं किसको तलने वाला ");
        map.put("Whom  was I  getting ", "मुझे किससे मिल रहा था ");
        map.put("Whom  was I  giving ", "मैं किसको दे रहा था ");
        map.put("Whom  was I  going ", "मैं किससे जा रहा था ");
        map.put("Whom  was I  growing ", "मैं किससे बढ़ रहा था ");
        map.put("Whom  was I  hanging ", "मैं किससे लटका रहा था ");
        map.put("Whom  was I  hearing ", "मैं किससे सुन रहा था ");
        map.put("Whom  was I  helping ", "मैं किसका मदद कर रहा था ");
        map.put("Whom  was I  hiding ", "मैं किसको छिपा रहा था ");
        map.put("Whom  was I  hitting ", "मैं किसको मार रहा था ");
        map.put("Whom  was I  holding ", "मैं किसको पकड़ रहा था ");
        map.put("Whom  was I  hoping ", "मैं किसका उम्मीद कर रहा था ");
        map.put("Whom  was I  hurting ", "मैं किसको चोट पहुँचा रहा था ");
        map.put("Whom  was I  jumping ", "मैं किससे कूद रहा था ");
        map.put("Whom  was I  keeping ", "मैं किसको रख रहा था ");
        map.put("Whom  was I  killing ", "मैं किसको मार रहा था ");
        map.put("Whom  was I  knowing ", "मैं किसको जान रहा था ");
        map.put("Whom  was I  laughing ", "मैं किससे हंस रहा था ");
        map.put("Whom  was I  leading ", "मैं किसका नेतृत्व कर रहा था ");
        map.put("Whom  was I  leaping ", "मैं किससे छलांग लगा रहा था ");
        map.put("Whom  was I  learning ", "मैं किससे सीख रहा था ");
        map.put("Whom  was I  leaving ", "मैं किसको छोड़ रहा था ");
        map.put("Whom  was I  lending ", "मैं किसे उधार दे रहा था ");
        map.put("Whom  was I  living ", "मैं किससे रह रहा था ");
        map.put("Whom  was I  looking ", "मैं किसको देख रहा था ");
        map.put("Whom  was I  losing ", "मैं किसको खो रहा था ");
        map.put("Whom  was I  loving ", "मैं किससे प्यार करता था ");
        map.put("Whom  was I  making ", "मैं किससे बना रहा था ");
        map.put("Whom  was I  marrying ", "मैं किससे शादी कर रहा था ");
        map.put("Whom  was I  meeting ", "मैं किससे मिल रहा था ");
        map.put("Whom  was I  mistaking ", "मैं किसकी गलती कर रहा था ");
        map.put("Whom  was I  opening ", "मैं किसको खोल रहा था ");
        map.put("Whom  was I  paying ", "मैं किसका भुगतान कर रहा था ");
        map.put("Whom  was I  playing ", "मैं किससे खेल रहा था ");
        map.put("Whom  was I  putting ", "मैं किसको डाल रहा था ");
        map.put("Whom  was I  quarrelling ", "मैं किससे झगड़ा कर रहा था ");
        map.put("Whom  was I  raining ", "मैं किसकी बारिश कर रहा था ");
        map.put("Whom  was I  reaching ", "मैं किसतक पहुँच रहा था ");
        map.put("Whom  was I  reading ", "मैं किसको पढ़ रहा था ");
        map.put("Whom  was I  remembering ", "मैं किसे याद कर रहा था ");
        map.put("Whom  was I  riding ", "मैं किसके साथ सवारी कर रहा था ");
        map.put("Whom  was I  ringing ", "मैं किससे बज रहा था ");
        map.put("Whom  was I  rising ", "मैं किसका उठ रहा था ");
        map.put("Whom  was I  running ", "मैं किससे भाग रहा था ");
        map.put("Whom  was I  saying ", "मैं किससे कह रहा था ");
        map.put("Whom  was I  seeing ", "मैं किसको देख रहा था ");
        map.put("Whom  was I  selling ", "मैं किसे बेच रहा था ");
        map.put("Whom  was I  sending ", "मैं किसको भेज रहा था ");
        map.put("Whom  was I  shaking ", "मैं किसको हिला रहा था ");
        map.put("Whom  was I  shining ", "मैं किससे चमक रहा था ");
        map.put("Whom  was I  shooting ", "मैं किसका शूटिंग कर रहा था ");
        map.put("Whom  was I  showing ", "मैं किसको दिखा रहा था ");
        map.put("Whom  was I  shutting ", "मैं किसको बंद कर रहा था ");
        map.put("Whom  was I  singing ", "मैं किससे गा रहा था ");
        map.put("Whom  was I  sinking ", "मैं किससे डूब रहा था ");
        map.put("Whom  was I  sleeping ", "मैं किससे सो रहा था ");
        map.put("Whom  was I  smelling ", "मैं किससे सूँघ रहा था ");
        map.put("Whom  was I  spending ", "मैं किसका खर्च कर रहा था ");
        map.put("Whom  was I  wearing ", "मैंने किसको पहना था ");

        return map;
    }
    static Map<String,String> Seven(){
        HashMap<String,String>map = new HashMap<>();
        map.put("Whom  had I  abused ", "मैंने किसके साथ दुर्व्यवहार किया था ");
        map.put("Whom  had I  advised ", "मैंने किसको सलाह दी थी ");
        map.put("Whom  had I  answered ", "मैंने किसका उत्तर दिया था ");
        map.put("Whom  had I  arisen ", "मैं किससे पैदा हुआ था ");
        map.put("Whom  had I  arrived ", "मैं किसके पास आया था ");
        map.put("Whom  had I  asked ", "मैंने किससे पूछा था ");
        map.put("Whom  had I  awoken ", "मैं किससे जाग गया था ");
        map.put("Whom  had I  undefined", "मैंने किससे अपरिभाषित किया था");
        map.put("Whom  had I  borne ", "मैंने किसको जन्म दिया था ");
        map.put("Whom  had I  beaten ", "मैंने किसको पीटा था ");
        map.put("Whom  had I  become ", "मैं किससे बन गया था ");
        map.put("Whom  had I  begged ", "मैंने किससे विनती की थी ");
        map.put("Whom  had I  begun ", "मैंने किससे शुरू किया था ");
        map.put("Whom  had I  bound ", "मैंने किससे बाध्य किया था ");
        map.put("Whom  had I  bitten ", "मैंने किसको काट लिया था ");
        map.put("Whom  had I  blessed ", "मैंने किसको आशीर्वाद दिया था ");
        map.put("Whom  had I  blown ", "मैंने किसको उड़ा दिया था ");
        map.put("Whom  had I  broken ", "मैंने किसको तोड़ा था ");
        map.put("Whom  had I  brought ", "मैं किसको लाया था ");
        map.put("Whom  had I  built ", "मैंने किसका निर्माण किया था ");
        map.put("Whom  had I  burnt ", "मैंने किसको जला दिया था ");
        map.put("Whom  had I  bought ", "मैंने किसको खरीदा था ");
        map.put("Whom  had I  called ", "मैंने किसे फोन किया था ");
        map.put("Whom  had I  carried ", "मैंने किसको ले लिया था ");
        map.put("Whom  had I  caught ", "मैंने किसको पकड़ा था ");
        map.put("Whom  had I  cheated ", "मैंने किसके साथ धोखा किया था ");
        map.put("Whom  had I  chosen ", "मैंने किसे चुना था ");
        map.put("Whom  had I  cleaned ", "मैंने किसको साफ किया था ");
        map.put("Whom  had I  climbed ", "मैं किससे चढ़ गया था ");
        map.put("Whom  had I  closed ", "मैंने किसको बंद किया था ");
        map.put("Whom  had I  come ", "मैं किसके पास आया था ");
        map.put("Whom  had I  cooked ", "मैंने किसको पकाया था ");
        map.put("Whom  had I  crept ", "मैंने किसके पास क्रेप किया था ");
        map.put("Whom  had I  cried ", "मैंने किससे रोया था ");
        map.put("Whom  had I  cut ", "मैंने किसको काट दिया था ");
        map.put("Whom  had I  danced ", "मैंने किसका नृत्य किया था ");
        map.put("Whom  had I  dealt ", "मैंने किससे निपटा था ");
        map.put("Whom  had I  died ", "मैं किससे मर गया था ");
        map.put("Whom  had I  dug ", "मैंने किसको खोदा था ");
        map.put("Whom  had I  drawn ", "मैंने किसको खींचा था ");
        map.put("Whom  had I  drunk ", "मैंने किससे पिया था ");
        map.put("Whom  had I  driven ", "मैंने किसको चलाया था ");
        map.put("Whom  had I  dropped ", "मैंने किसको गिरा दिया था ");
        map.put("Whom  had I  dried ", "मैंने किसको सुखाया था ");
        map.put("Whom  had I  eaten ", "मैंने किसको खाया था ");
        map.put("Whom  had I  elected ", "मैंने किसे चुना था ");
        map.put("Whom  had I  entered ", "मैंने किसमें प्रवेश किया था ");
        map.put("Whom  had I  fallen ", "मैं किससे गिर गया था ");
        map.put("Whom  had I  fed ", "मैंने किसको खिलाया था ");
        map.put("Whom  had I  felt ", "मैंने किसका महसूस किया था ");
        map.put("Whom  had I  fought ", "मैंने किससे लड़ाई लड़ी थी ");
        map.put("Whom  had I  found ", "मैंने किसको पाया था ");
        map.put("Whom  had I  fled ", "मैं किससे भाग गया था ");
        map.put("Whom  had I  flown ", "मैंने किससे उड़ाया था ");
        map.put("Whom  had I  forgotten ", "मैं किसको भूल गया था ");
        map.put("Whom  had I  fried ", "मैंने किसको तला था ");
        map.put("Whom  had I  got ", "मुझे किसके पास मिला था ");
        map.put("Whom  had I  given ", "मैंने किसे दिया था ");
        map.put("Whom  had I  gone ", "मैं किसके पास गया था ");
        map.put("Whom  had I  grown ", "मैं किससे उगाया था ");
        map.put("Whom  had I  hanged ", "मैंने किसको फांसी दी थी ");
        map.put("Whom  had I  hung ", "मैंने किसको लटका दिया था ");
        map.put("Whom  had I  heard ", "मैंने किससे सुना था ");
        map.put("Whom  had I  helped ", "मैंने किसकी मदद की थी ");
        map.put("Whom  had I  hidden ", "मैंने किसको छुपाया था ");
        map.put("Whom  had I  hit ", "मैंने किसको मारा था ");
        map.put("Whom  had I  held ", "मैंने किसके पास रखा था ");
        map.put("Whom  had I  hoped ", "मैंने किसकी उम्मीद की थी ");
        map.put("Whom  had I  hurt ", "मुझे किससे चोट लगी थी ");
        map.put("Whom  had I  jumped ", "मैं किससे कूद गया था ");
        map.put("Whom  had I  kept ", "मैंने किसको रखा था ");
        map.put("Whom  had I  killed ", "मैंने किसको मार डाला था ");
        map.put("Whom  had I  known ", "मैं किससे जानता था ");
        map.put("Whom  had I  laughed ", "मैं किससे हँसा था ");
        map.put("Whom  had I  led ", "मैंने किसका नेतृत्व किया था ");
        map.put("Whom  had I  leapt ", "मैंने किससे छलांग लगाई थी ");
        map.put("Whom  had I  learnt ", "मैंने किससे सीखा था ");
        map.put("Whom  had I  left ", "मैंने किसको छोड़ा था ");
        map.put("Whom  had I  lent ", "मैंने किसको उधार दिया था ");
        map.put("Whom  had I  lived ", "मैं किसके पास रहता था ");
        map.put("Whom  had I  looked ", "मैंने किसको देखा था ");
        map.put("Whom  had I  lost ", "मैंने किसको खो दिया था ");
        map.put("Whom  had I  loved ", "मैंने किससे प्यार किया था ");
        map.put("Whom  had I  made ", "मैंने किसको बनाया था ");
        map.put("Whom  had I  married ", "मैंने किससे शादी की थी ");
        map.put("Whom  had I  met ", "मैं किससे मिला था ");
        map.put("Whom  had I  mistaken ", "मैंने किससे गलत किया था ");
        map.put("Whom  had I  opened ", "मैंने किसको खोला था ");
        map.put("Whom  had I  paid ", "मैंने किसका भुगतान किया था ");
        map.put("Whom  had I  played ", "मैंने किसका खेला था ");
        map.put("Whom  had I  put ", "मैंने किसको रखा था ");
        map.put("Whom  had I  quarrelled ", "मैंने किससे झगड़ा किया था ");
        map.put("Whom  had I  rained ", "मैंने किसकी बारिश की थी ");
        map.put("Whom  had I  reached ", "मैं किसके पास पहुँचा था ");
        map.put("Whom  had I  read ", "मैंने किसको पढ़ा था ");
        map.put("Whom  had I  remembered ", "मुझे किसकी याद थी ");
        map.put("Whom  had I  ridden ", "मैंने किसकी सवारी की थी ");
        map.put("Whom  had I  rung ", "मैंने किसको बजाया था ");
        map.put("Whom  had I  risen ", "मैं किससे उठ गया था ");
        map.put("Whom  had I  run ", "मैंने किसको चलाया था ");
        map.put("Whom  had I  said ", "मैंने किससे कहा था ");
        map.put("Whom  had I  seen ", "मैंने किसको देखा था ");
        map.put("Whom  had I  sold ", "मैंने किसे बेचा था ");
        map.put("Whom  had I  sent ", "मैंने किसे भेजा था ");
        map.put("Whom  had I  shaken ", "मैंने किसको हिलाया था ");
        map.put("Whom  had I  shone ", "मैं किससे चमका था ");
        map.put("Whom  had I  shot ", "मैंने किसको गोली मारी थी ");
        map.put("Whom  had I  shown ", "मैंने किसे दिखाया था ");
        map.put("Whom  had I  shut ", "मैंने किसको बंद किया था ");
        map.put("Whom  had I  sung ", "मैंने किसको गाया था ");
        map.put("Whom  had I  sunk ", "मैं किससे डूब गया था ");
        map.put("Whom  had I  slept ", "मैं किससे सोया था ");
        map.put("Whom  had I  smelt ", "मैंने किसको पिघलाया था ");
        map.put("Whom  had I  swum ", "मैंने किसके पास तैर लिया था ");

        return map;
    }
    static Map<String,String> Eight(){
        HashMap<String,String>map = new HashMap<>();
        map.put("Whom  had I been  beating ", "मैं किसकी पिटाई कर रहा था ");
        map.put("Whom  had I been  abusing ", "मैं किससे गाली दे रहा था ");
        map.put("Whom  had I been  advising ", "मैं किसको सलाह दे रहा था ");
        map.put("Whom  had I been  answering ", "मैं किसका जवाब दे रहा था ");
        map.put("Whom  had I been  arising ", "मैं किससे उठ रहा था ");
        map.put("Whom  had I been  arriving ", "मैं किसके पास आ रहा था ");
        map.put("Whom  had I been  asking ", "मैं किससे पूछ रहा था ");
        map.put("Whom  had I been  awaking ", "मैं किससे जाग रहा था ");
        map.put("Whom  had I been  undefined", "मैं किससे अपरिभाषित हो गया था");
        map.put("Whom  had I been  bearing ", "मैं किसका असर कर रहा था ");
        map.put("Whom  had I been  becoming ", "मैं किससे बन रहा था ");
        map.put("Whom  had I been  begging ", "मैं किससे भीख माँग रहा था ");
        map.put("Whom  had I been  beginning ", "मैं किसकी शुरुआत कर रहा था ");
        map.put("Whom  had I been  binding ", "मैं किससे बाध्यकारी था ");
        map.put("Whom  had I been  biting ", "मैं किससे काट रहा था ");
        map.put("Whom  had I been  blessing ", "मैं किससे आशीष दे रहा था ");
        map.put("Whom  had I been  blowing ", "मैं किससे उड़ा रहा था ");
        map.put("Whom  had I been  breaking ", "मैं किसको तोड़ रहा था ");
        map.put("Whom  had I been  bringing ", "मैं किसको ला रहा था ");
        map.put("Whom  had I been  building ", "मैं किसका निर्माण कर रहा था ");
        map.put("Whom  had I been  burning ", "मैं किससे जल रहा था ");
        map.put("Whom  had I been  buying ", "मैं किसको खरीद रहा था ");
        map.put("Whom  had I been  calling ", "मैं किसको बुला रहा था ");
        map.put("Whom  had I been  carrying ", "मैं किसको ले जा रहा था ");
        map.put("Whom  had I been  catching ", "मैं किसको पकड़ रहा था ");
        map.put("Whom  had I been  cheating ", "मैं किसको धोखा दे रहा था ");
        map.put("Whom  had I been  choosing ", "मैं किसका चयन कर रहा था ");
        map.put("Whom  had I been  cleaning ", "मैं किसकी सफाई कर रहा था ");
        map.put("Whom  had I been  climbing ", "मैं किसपर चढ़ रहा था ");
        map.put("Whom  had I been  closing ", "मैं किसको बंद कर रहा था ");
        map.put("Whom  had I been  coming ", "मैं किसके पास आ रहा था ");
        map.put("Whom  had I been  cooking ", "मैं किससे खाना बना रहा था ");
        map.put("Whom  had I been  creeping ", "मैं किससे रेंग रहा था ");
        map.put("Whom  had I been  crying ", "मैं किससे रो रहा था ");
        map.put("Whom  had I been  cutting ", "मैं किसको काट रहा था ");
        map.put("Whom  had I been  dancing ", "मैं किससे नाच रहा था ");
        map.put("Whom  had I been  dealing ", "मैं किससे निपट रहा था ");
        map.put("Whom  had I been  dying ", "मैं किससे मर रहा था ");
        map.put("Whom  had I been  digging ", "मैं किसकी खुदाई कर रहा था ");
        map.put("Whom  had I been  drawing ", "मैं किसको चित्रित कर रहा था ");
        map.put("Whom  had I been  drinking ", "मैं किससे पी रहा था ");
        map.put("Whom  had I been  driving ", "मैं किससे चला रहा था ");
        map.put("Whom  had I been  dropping ", "मैं किसको छोड़ रहा था ");
        map.put("Whom  had I been  drying ", "मैं किससे सूख रहा था ");
        map.put("Whom  had I been  eating ", "मैं किसका खा रहा था ");
        map.put("Whom  had I been  electing ", "मैं किसका चुनाव कर रहा था ");
        map.put("Whom  had I been  entering ", "मैं किसमें प्रवेश कर रहा था ");
        map.put("Whom  had I been  falling ", "मैं किससे गिर रहा था ");
        map.put("Whom  had I been  feeding ", "मैं किसको खिला रहा था ");
        map.put("Whom  had I been  feeling ", "मैं किसका महसूस कर रहा था ");
        map.put("Whom  had I been  fighting ", "मैं किससे लड़ रहा था ");
        map.put("Whom  had I been  finding ", "मैं किसको ढूंढ रहा था ");
        map.put("Whom  had I been  fleeing ", "मैं किससे भाग रहा था ");
        map.put("Whom  had I been  flying ", "मैं किससे उड़ रहा था ");
        map.put("Whom  had I been  forgetting ", "मैं किसको भूल गया था ");
        map.put("Whom  had I been  frying ", "मैं किससे तलने गया था ");
        map.put("Whom  had I been  getting ", "मुझे किससे मिल रहा था ");
        map.put("Whom  had I been  giving ", "मैं किसको दे रहा था ");
        map.put("Whom  had I been  going ", "मैं किसके पास जा रहा था ");
        map.put("Whom  had I been  growing ", "मैं किससे बढ़ रहा था ");
        map.put("Whom  had I been  hanging ", "मैं किससे लटक रहा था ");
        map.put("Whom  had I been  hearing ", "मैं किससे सुन रहा था ");
        map.put("Whom  had I been  helping ", "मैं किसकी मदद कर रहा था ");
        map.put("Whom  had I been  hiding ", "मैं किसको छिपा रहा था ");
        map.put("Whom  had I been  hitting ", "मैं किससे मार रहा था ");
        map.put("Whom  had I been  holding ", "मैं किसको पकड़ रहा था ");
        map.put("Whom  had I been  hoping ", "मैं किसकी उम्मीद कर रहा था ");
        map.put("Whom  had I been  hurting ", "मैं किसको चोट पहुँचा रहा था ");
        map.put("Whom  had I been  jumping ", "मैं किससे कूद रहा था ");
        map.put("Whom  had I been  keeping ", "मैं किसको रख रहा था ");
        map.put("Whom  had I been  killing ", "मैं किसकी हत्या कर रहा था ");
        map.put("Whom  had I been  knowing ", "मैं किसको जान रहा था ");
        map.put("Whom  had I been  laughing ", "मैं किससे हँस रहा था ");
        map.put("Whom  had I been  leading ", "मैं किसका नेतृत्व कर रहा था ");
        map.put("Whom  had I been  leaping ", "मैं किससे छलांग लगा रहा था ");
        map.put("Whom  had I been  learning ", "मैं किससे सीख रहा था ");
        map.put("Whom  had I been  leaving ", "मैं किससे जा रहा था ");
        map.put("Whom  had I been  lending ", "मैं किससे उधार दे रहा था ");
        map.put("Whom  had I been  living ", "मैं किससे रह रहा था ");
        map.put("Whom  had I been  looking ", "मैं किसको देख रहा था ");
        map.put("Whom  had I been  losing ", "मैं किसको खो रहा था ");
        map.put("Whom  had I been  loving ", "मैं किससे प्यार कर रहा था ");
        map.put("Whom  had I been  making ", "मैं किसका बना रहा था ");
        map.put("Whom  had I been  marrying ", "मैं किससे शादी कर रहा था ");
        map.put("Whom  had I been  meeting ", "मैं किससे मिल रहा था ");
        map.put("Whom  had I been  mistaking ", "मैं किससे गलत कर रहा था ");
        map.put("Whom  had I been  opening ", "मैं किसका खोल रहा था ");
        map.put("Whom  had I been  paying ", "मैं किसका भुगतान कर रहा था ");
        map.put("Whom  had I been  playing ", "मैं किसका खेल रहा था ");
        map.put("Whom  had I been  putting ", "मैं किसको लगा रहा था ");
        map.put("Whom  had I been  quarrelling ", "मैं किससे झगड़ा कर रहा था ");
        map.put("Whom  had I been  raining ", "मैं किसकी बारिश कर रहा था ");
        map.put("Whom  had I been  reaching ", "मैं किसतक पहुँच रहा था ");
        map.put("Whom  had I been  reading ", "मैं किसको पढ़ रहा था ");
        map.put("Whom  had I been  remembering ", "मैं किसको याद कर रहा था ");
        map.put("Whom  had I been  riding ", "मैं किसकी सवारी कर रहा था ");
        map.put("Whom  had I been  ringing ", "मैं किससे बज रहा था ");
        map.put("Whom  had I been  rising ", "मैं किससे उठ रहा था ");
        map.put("Whom  had I been  running ", "मैं किससे दौड़ रहा था ");
        map.put("Whom  had I been  saying ", "मैं किससे कह रहा था ");
        map.put("Whom  had I been  seeing ", "मैं किसको देख रहा था ");
        map.put("Whom  had I been  selling ", "मैं किसको बेच रहा था ");
        map.put("Whom  had I been  sending ", "मैं किसको भेज रहा था ");
        map.put("Whom  had I been  shaking ", "मैं किसको हिला रहा था ");
        map.put("Whom  had I been  shining ", "मैं किससे चमक रहा था ");
        map.put("Whom  had I been  shooting ", "मैं किसकी शूटिंग कर रहा था ");
        map.put("Whom  had I been  showing ", "मैं किसको दिखा रहा था ");
        map.put("Whom  had I been  shutting ", "मैं किसको बंद कर रहा था ");
        map.put("Whom  had I been  singing ", "मैं किससे गा रहा था ");
        map.put("Whom  had I been  sinking ", "मैं किससे डूब रहा था ");
        map.put("Whom  had I been  sleeping ", "मैं किससे सो रहा था ");
        map.put("Whom  had I been  smelling ", "मैं किससे सूँघ रहा था ");
        map.put("Whom  had I been  swimming ", "मैं किसके पास तैर रहा था ");

        return map;
    }
    static Map<String,String> Nine(){
        HashMap<String,String>map = new HashMap<>();
        map.put("Whom  will I beat ", "मैं किसको हराऊंगा ");
        map.put("Whom  will I abuse ", "मैं किसके साथ गाली दूँगा ");
        map.put("Whom  will I advise", "मैं किसको सलाह दूँगा");
        map.put("Whom  will I answer ", "मैं किसका जवाब दूँगा ");
        map.put("Whom  will I arise ", "मैं किससे उठूंगा ");
        map.put("Whom  will I arrive ", "मैं किससे पहुँचूँगा ");
        map.put("Whom  will I ask ", "मैं किससे पूछूंगा ");
        map.put("Whom  will I awake ", "मैं किससे जाग जाऊंगा ");
        map.put("Whom  will I \r", "मैं किससे करूँगा \r");
        map.put("Whom  will I be undefined", "मैं किससे अपरिभाषित हो जाऊंगा");
        map.put("Whom  will I bear ", "मैं किसको सहन करूंगा ");
        map.put("Whom  will I become ", "मैं किससे बनूंगा ");
        map.put("Whom  will I beg ", "मैं किससे भीख मांगूँगा ");
        map.put("Whom  will I begin ", "मैं किससे शुरू करूँगा ");
        map.put("Whom  will I bind ", "मैं किससे बाँधूँगा ");
        map.put("Whom  will I bite", "मैं किसको काटूंगा");
        map.put("Whom  will I bless", "मैं किसको आशीष दूँगा");
        map.put("Whom  will I break ", "मैं किसको तोडूंगा ");
        map.put("Whom  will I bring ", "मैं किसको लाऊंगा ");
        map.put("Whom  will I build ", "मैं किसका निर्माण करूंगा ");
        map.put("Whom  will I burn ", "मैं किसको जलाऊंगा ");
        map.put("Whom  will I buy ", "मैं किसको खरीदूंगा ");
        map.put("Whom  will I call ", "मैं किसे फोन करूंगा ");
        map.put("Whom  will I carry ", "मैं किसको ले जाऊंगा ");
        map.put("Whom  will I catch ", "मैं किसको पकड़ूँगा ");
        map.put("Whom  will I cheat ", "मैं किसको धोखा दूँगा ");
        map.put("Whom  will I choose ", "मैं किसे चुनूंगा ");
        map.put("Whom  will I clean ", "मैं किसको साफ करूँगा ");
        map.put("Whom  will I climb  ", "मैं किसपर चलूंगा  ");
        map.put("Whom  will I close ", "मैं किसको बंद करूँगा ");
        map.put("Whom  will I come ", "मैं किसके पास आऊंगा ");
        map.put("Whom  will I cook ", "मैं किसको खाना बनाऊंगा ");
        map.put("Whom  will I creep ", "मैं किससे रेंगूँगा ");
        map.put("Whom  will I cry ", "मैं किससे रोऊंगा ");
        map.put("Whom  will I cut ", "मैं किसको काटूंगा ");
        map.put("Whom  will I dance ", "मैं किससे नृत्य करूँगा ");
        map.put("Whom  will I deal ", "मैं किससे निपटूंगा ");
        map.put("Whom  will I die ", "मैं किससे मरूंगा ");
        map.put("Whom  will I dig ", "मैं किसको खोदूँगा ");
        map.put("Whom  will I draw ", "मैं किसको आकर्षित करूंगा ");
        map.put("Whom  will I drive ", "मैं किससे चलाऊंगा ");
        map.put("Whom  will I drop ", "मैं किसको छोड़ दूँगा ");
        map.put("Whom  will I dry ", "मैं किसको सुखाऊंगा ");
        map.put("Whom  will I eat ", "मैं किसको खाऊंगा ");
        map.put("Whom  will I elect", "मैं किसका चुनाव करूंगा");
        map.put("Whom  will I enter ", "मैं किसमें प्रवेश करूंगा ");
        map.put("Whom  will I fall ", "मैं किससे गिरूंगा ");
        map.put("Whom  will I feed ", "मैं किसको खिलाऊंगा ");
        map.put("Whom  will I feel  ", "मैं किसको महसूस करूँगा  ");
        map.put("Whom  will I fight ", "मैं किससे लड़ूंगा ");
        map.put("Whom  will I find ", "मुझे किसको मिलेगा ");
        map.put("Whom  will I flee ", "मैं किससे भागेगा ");
        map.put("Whom  will I fly  ", "मैं किससे उड़ूंगा  ");
        map.put("Whom  will I forget ", "मैं किसे भूल जाऊंगा ");
        map.put("Whom  will I fry ", "मैं किसको भूनूंगा ");
        map.put("Whom  will I get  ", "मुझे किससे मिलेगा  ");
        map.put("Whom  will I give ", "मैं किसको दूँगा ");
        map.put("Whom  will I go ", "मैं किससे जाऊंगा ");
        map.put("Whom  will I grow", "मैं किसको उगाऊंगा");
        map.put("Whom  will I hang ", "मैं किसको लटकाऊंगा ");
        map.put("Whom  will I hear ", "मैं किसको सुनूंगा ");
        map.put("Whom  will I help ", "मैं किसकी मदद करूँगा ");
        map.put("Whom  will I hide ", "मैं किसको छिपाऊंगा ");
        map.put("Whom  will I hit ", "मैं किससे मारूंगा ");
        map.put("Whom  will I hold ", "मैं किसको पकड़ लूंगा ");
        map.put("Whom  will I hope ", "मैं किसकी उम्मीद करूंगा ");
        map.put("Whom  will I hurt ", "मैं किसको चोट पहुंचाऊंगा ");
        map.put("Whom  will I jump ", "मैं किससे कूदूँगा ");
        map.put("Whom  will I keep ", "मैं किसको रखूँगा ");
        map.put("Whom  will I kill ", "मैं किसको मारूंगा ");
        map.put("Whom  will I know ", "मुझे किससे पता चलेगा ");
        map.put("Whom  will I laugh ", "मैं किससे हंसूंगा ");
        map.put("Whom  will I lead ", "मैं किसका नेतृत्व करूँगा ");
        map.put("Whom  will I leap ", "मैं किससे छलांग लगाऊंगा ");
        map.put("Whom  will I learn ", "मैं किससे सीखूंगा ");
        map.put("Whom  will I leave ", "मैं किससे छोड़ूँगा ");
        map.put("Whom  will I lend ", "मैं किसे उधार दूँगा ");
        map.put("Whom  will I live ", "मैं किससे रहूँगा ");
        map.put("Whom  will I look ", "मैं किसको देखूँगा ");
        map.put("Whom  will I lose ", "मैं किसको खो दूँगा ");
        map.put("Whom  will I make ", "मैं किसको बनाऊँगा ");
        map.put("Whom  will I marry ", "मैं किससे शादी करूँगा ");
        map.put("Whom  will I meet ", "मैं किससे मिलूंगा ");
        map.put("Whom  will I mistake ", "मैं किसकी गलती करूँगा ");
        map.put("Whom  will I open ", "मैं किसको खोलूंगा ");
        map.put("Whom  will I pay  ", "मैं किसका भुगतान करूंगा  ");
        map.put("Whom  will I play ", "मैं किससे खेलूंगा ");
        map.put("Whom  will I put ", "मैं किसको रखूँगा ");
        map.put("Whom  will I quarrel ", "मैं किससे झगड़ा करूंगा ");
        map.put("Whom  will I rain ", "मैं किसकी बारिश करूँगा ");
        map.put("Whom  will I reach ", "मैं किसतक पहुँचूँगा ");
        map.put("Whom  will I read", "मैं किसको पढ़ूँगा");
        map.put("Whom  will I remember  ", "मैं किसे याद रखूँगा  ");
        map.put("Whom  will I ride ", "मैं किसकी सवारी करूँगा ");
        map.put("Whom  will I ring ", "मैं किससे रिंग करूंगा ");
        map.put("Whom  will I rise  ", "मैं किससे उठूंगा  ");
        map.put("Whom  will I run  ", "मैं किससे दौड़ूंगा  ");
        map.put("Whom  will I say ", "मैं किससे कहूँगा ");
        map.put("Whom  will I see ", "मैं किसको देखूँगा ");
        map.put("Whom  will I sell ", "मैं किसे बेचूंगा ");
        map.put("Whom  will I send ", "मैं किसे भेजूंगा ");
        map.put("Whom  will I shake ", "मैं किसको हिलाऊंगा ");
        map.put("Whom  will I shine ", "मैं किससे चमकूंगा ");
        map.put("Whom  will I shoot ", "मैं किसको शूट करूँगा ");
        map.put("Whom  will I shut  ", "मैं किसको बंद करूँगा  ");
        map.put("Whom  will I sing ", "मैं किसको गाऊंगा ");
        map.put("Whom  will I sink ", "मैं किसको डुबो दूंगा ");
        map.put("Whom  will I sleep ", "मैं किससे सोऊंगा ");
        map.put("Whom  will I smell ", "मुझे किसकी गंध आएगी ");
        map.put("Whom  will I tear ", "मैं किससे फाड़ूंगा ");
        map.put("Whom  will I throw ", "मैं किसको फेंकूंगा ");

        return map;
    }
    static Map<String,String> Ten(){
        HashMap<String,String>map = new HashMap<>();
        map.put("Whom  will I be beating ", "मैं किसकी पिटाई करूंगा ");
        map.put("Whom  will I be abusing ", "मैं किससे गाली दे रहा हूँ ");
        map.put("Whom  will I be advising ", "मैं किसको सलाह दूँगा ");
        map.put("Whom  will I be answering ", "मैं किसका जवाब दूंगा ");
        map.put("Whom  will I be arising ", "मैं किससे उठ जाऊंगा ");
        map.put("Whom  will I be arriving ", "मैं किससे पहुँचूँगा ");
        map.put("Whom  will I be asking ", "मैं किससे पूछूंगा ");
        map.put("Whom  will I be awaking ", "मैं किससे जाग जाऊंगा ");
        map.put("Whom  will I be bearing ", "मैं किसका असर डालूंगा ");
        map.put("Whom  will I be becoming ", "मैं किससे बन जाऊंगा ");
        map.put("Whom  will I be begging ", "मैं किससे भीख माँग रहा हूँ ");
        map.put("Whom  will I be beginning ", "मैं किसकी शुरुआत करूंगा ");
        map.put("Whom  will I be binding ", "मैं किससे बाध्यकारी रहूँगा ");
        map.put("Whom  will I be biting ", "मैं किसको काटूंगा ");
        map.put("Whom  will I be blessing ", "मैं किससे आशीष बनूंगा ");
        map.put("Whom  will I be blowing ", "मैं किसको उड़ा रहा हूँ ");
        map.put("Whom  will I be breaking ", "मैं किसको तोड़ रहा हूँ ");
        map.put("Whom  will I be bringing ", "मैं किसको लाऊंगा ");
        map.put("Whom  will I be building ", "मैं किसका निर्माण करूंगा ");
        map.put("Whom  will I be burning ", "मैं किसको जलाऊंगा ");
        map.put("Whom  will I be buying ", "मैं किसको खरीदूंगा ");
        map.put("Whom  will I be calling ", "मैं किसको बुलाऊंगा ");
        map.put("Whom  will I be carrying ", "मैं किसको ले जाऊंगा ");
        map.put("Whom  will I be catching ", "मैं किसको पकड़ लूंगा ");
        map.put("Whom  will I be cheating ", "मैं किसको धोखा दे रहा हूँ ");
        map.put("Whom  will I be choosing ", "मैं किसे चुनूंगा ");
        map.put("Whom  will I be cleaning ", "मैं किसकी सफाई करूँगा ");
        map.put("Whom  will I be climbing ", "मैं किसपर चढ़ जाऊंगा ");
        map.put("Whom  will I be closing ", "मैं किससे बंद करूँगा ");
        map.put("Whom  will I be coming ", "मैं किसके पास आऊंगा ");
        map.put("Whom  will I be cooking ", "मैं किससे खाना बनाऊंगा ");
        map.put("Whom  will I be creeping ", "मैं किससे रेंग रहा हूँ ");
        map.put("Whom  will I be crying ", "मैं किससे रो रहा हूँ ");
        map.put("Whom  will I be cutting ", "मैं किसको काटूंगा ");
        map.put("Whom  will I be dancing ", "मैं किससे नाचता रहूंगा ");
        map.put("Whom  will I be dealing ", "मैं किससे निपटूंगा ");
        map.put("Whom  will I be dying ", "मैं किससे मर जाऊंगा ");
        map.put("Whom  will I be digging ", "मैं किसकी खुदाई करूँगा ");
        map.put("Whom  will I be drawing ", "मैं किसको चित्रित करूँगा ");
        map.put("Whom  will I be drinking ", "मैं किससे पीऊंगा ");
        map.put("Whom  will I be driving ", "मैं किसकी गाड़ी चला रहा हूँ ");
        map.put("Whom  will I be dropping ", "मैं किसको छोड़ जाऊंगा ");
        map.put("Whom  will I be drying ", "मैं किसको सुखाऊंगा ");
        map.put("Whom  will I be eating ", "मैं किसको खाऊंगा ");
        map.put("Whom  will I be electing ", "मैं किसका चुनाव करूंगा ");
        map.put("Whom  will I be entering ", "मैं किसमें प्रवेश करूंगा ");
        map.put("Whom  will I be falling ", "मैं किससे गिर रहा हूँ ");
        map.put("Whom  will I be feeding ", "मैं किसको खिलाऊंगा ");
        map.put("Whom  will I be feeling ", "मैं किसका महसूस कर रहा हूँ ");
        map.put("Whom  will I be fighting ", "मैं किससे लड़ूंगा ");
        map.put("Whom  will I be finding ", "मैं किसको खोजूंगा ");
        map.put("Whom  will I be fleeing ", "मैं किससे भाग जाऊंगा ");
        map.put("Whom  will I be flying ", "मैं किससे उड़ जाऊंगा ");
        map.put("Whom  will I be forgetting ", "मैं किसको भूल जाऊंगा ");
        map.put("Whom  will I be frying ", "मैं किसको तलने जाऊंगा ");
        map.put("Whom  will I be getting ", "मुझे किससे मिल रहा होगा ");
        map.put("Whom  will I be giving ", "मैं किसको दे रहा हूँ ");
        map.put("Whom  will I be going ", "मैं किससे जाऊंगा ");
        map.put("Whom  will I be growing ", "मैं किससे बढ़ रहा हूँ ");
        map.put("Whom  will I be hanging ", "मैं किससे लटकाऊंगा ");
        map.put("Whom  will I be hearing ", "मैं किसकी सुनूंगा ");
        map.put("Whom  will I be helping ", "मैं किसकी मदद कर रहा हूँ ");
        map.put("Whom  will I be hiding ", "मैं किसको छिपाऊंगा ");
        map.put("Whom  will I be hitting ", "मैं किसको मार रहा हूँ ");
        map.put("Whom  will I be holding ", "मैं किसको पकड़ लूंगा ");
        map.put("Whom  will I be hoping ", "मैं किसकी उम्मीद कर रहा हूँ ");
        map.put("Whom  will I be hurting ", "मैं किसको चोट पहुँचाऊंगा ");
        map.put("Whom  will I be jumping ", "मैं किससे कूद जाऊंगा ");
        map.put("Whom  will I be keeping ", "मैं किसको रखूँगा ");
        map.put("Whom  will I be killing ", "मैं किसको मार रहा हूँ ");
        map.put("Whom  will I be knowing ", "मैं किसको जानूँगा ");
        map.put("Whom  will I be laughing ", "मैं किससे हँस रहा हूँ ");
        map.put("Whom  will I be leading ", "मैं किसकी अगुवाई करूंगा ");
        map.put("Whom  will I be leaping ", "मैं किससे छलांग लगाऊंगा ");
        map.put("Whom  will I be learning ", "मैं किससे सीख रहा हूँ ");
        map.put("Whom  will I be leaving ", "मैं किससे छोड़ूँगा ");
        map.put("Whom  will I be lending ", "मैं किसको उधार दूंगा ");
        map.put("Whom  will I be living ", "मैं किससे रहूँगा ");
        map.put("Whom  will I be looking ", "मैं किसकी तलाश कर रहा हूँ ");
        map.put("Whom  will I be losing ", "मैं किसको खो रहा हूँ ");
        map.put("Whom  will I be loving ", "मैं किससे प्यार करूंगा ");
        map.put("Whom  will I be making ", "मैं किसको बना रहा हूँ ");
        map.put("Whom  will I be marrying ", "मैं किससे शादी करूँगा ");
        map.put("Whom  will I be meeting ", "मैं किससे मिलूंगा ");
        map.put("Whom  will I be mistaking ", "मैं किसकी गलती करूंगा ");
        map.put("Whom  will I be opening ", "मैं किसको खोलूंगा ");
        map.put("Whom  will I be paying ", "मैं किसका भुगतान करूंगा ");
        map.put("Whom  will I be playing ", "मैं किससे खेलूंगा ");
        map.put("Whom  will I be putting ", "मैं किसको डालूंगा ");
        map.put("Whom  will I be quarrelling ", "मैं किससे झगड़ा करूंगा ");
        map.put("Whom  will I be raining ", "मैं किसकी बारिश कर रहा हूँ ");
        map.put("Whom  will I be reaching ", "मैं किसतक पहुँचूँगा ");
        map.put("Whom  will I be reading ", "मैं किसको पढ़ूंगा ");
        map.put("Whom  will I be remembering ", "मैं किसको याद रखूँगा ");
        map.put("Whom  will I be riding ", "मैं किसकी सवारी करूँगा ");
        map.put("Whom  will I be ringing ", "मैं किससे बज रहा हूँ ");
        map.put("Whom  will I be rising ", "मैं किससे उठ रहा हूँ ");
        map.put("Whom  will I be running ", "मैं किससे दौड़ूंगा ");
        map.put("Whom  will I be saying ", "मैं किससे कहूँगा ");
        map.put("Whom  will I be seeing ", "मैं किसे देख रहा हूँ ");
        map.put("Whom  will I be selling ", "मैं किसे बेचूंगा ");
        map.put("Whom  will I be sending ", "मैं किसको भेजूंगा ");
        map.put("Whom  will I be shaking ", "मैं किसको हिलाऊंगा ");
        map.put("Whom  will I be shining ", "मैं किससे चमक रहा हूँ ");
        map.put("Whom  will I be shooting ", "मैं किसकी शूटिंग करूंगा ");
        map.put("Whom  will I be showing ", "मैं किसे दिखाऊंगा ");
        map.put("Whom  will I be shutting ", "मैं किसको बंद कर दूँगा ");
        map.put("Whom  will I be singing ", "मैं किसको गा रहा हूँ ");
        map.put("Whom  will I be sinking ", "मैं किससे डूब जाऊंगा ");
        map.put("Whom  will I be sleeping ", "मैं किससे सोऊंगा ");
        map.put("Whom  will I be smelling ", "मुझे किससे सूंघना होगा ");
        map.put("Whom  will I be understanding ", "मैं किसको समझूँगा ");

        return map;
    }
    static Map<String,String> Eleven(){
        HashMap<String,String>map = new HashMap<>();
        map.put("Whom  will I have abused ", "मैंने किसके साथ दुर्व्यवहार किया होगा ");
        map.put("Whom  will I have advised ", "मैंने किसको सलाह दी होगी ");
        map.put("Whom  will I have answered ", "मैंने किसका जवाब दिया होगा ");
        map.put("Whom  will I have arisen ", "मैं किससे पैदा हुआ हूँ ");
        map.put("Whom  will I have arrived ", "मैं किसके पास आऊंगा ");
        map.put("Whom  will I have asked ", "मैंने किससे पूछा होगा ");
        map.put("Whom  will I have awoken ", "मैं किससे जाग जाऊंगा ");
        map.put("Whom  will I have undefined", "मैं किसको अपरिभाषित करूंगा");
        map.put("Whom  will I have borne ", "मैंने किसको जन्म दिया होगा ");
        map.put("Whom  will I have beaten ", "मैंने किसको पीटा होगा ");
        map.put("Whom  will I have become ", "मैं किससे बन जाऊंगा ");
        map.put("Whom  will I have begged ", "मैंने किससे भीख माँगी होगी ");
        map.put("Whom  will I have begun ", "मैं किससे शुरू कर दूँगा ");
        map.put("Whom  will I have bound ", "मैं किससे बाध्य होऊंगा ");
        map.put("Whom  will I have bitten ", "मैंने किसको काट लिया होगा ");
        map.put("Whom  will I have blessed ", "मैं किसको आशीष दूँगा ");
        map.put("Whom  will I have blown ", "मैंने किसको उड़ा दिया होगा ");
        map.put("Whom  will I have broken ", "मैं किसको तोड़ दूँगा ");
        map.put("Whom  will I have brought ", "मैं किसको लाऊंगा ");
        map.put("Whom  will I have built ", "मैंने किसका निर्माण किया होगा ");
        map.put("Whom  will I have burnt ", "मैं किसको जला दूँगा ");
        map.put("Whom  will I have bought ", "मैंने किसको खरीदा होगा ");
        map.put("Whom  will I have called ", "मैंने किसे फोन किया होगा ");
        map.put("Whom  will I have carried ", "मैं किसको ले जाऊंगा ");
        map.put("Whom  will I have caught ", "मैंने किसे पकड़ा होगा ");
        map.put("Whom  will I have cheated ", "मैंने किसके साथ धोखा किया होगा ");
        map.put("Whom  will I have chosen ", "मैंने किसे चुना होगा ");
        map.put("Whom  will I have cleaned ", "मैंने किसको साफ किया होगा ");
        map.put("Whom  will I have climbed ", "मैं किसपर चढ़ जाऊंगा ");
        map.put("Whom  will I have closed ", "मैं किसको बंद कर दूँगा ");
        map.put("Whom  will I have come ", "मैं किसके पास आऊंगा ");
        map.put("Whom  will I have cooked ", "मैंने किसको पकाया होगा ");
        map.put("Whom  will I have crept ", "मेरे पास crept किसके पास होगा ");
        map.put("Whom  will I have cried ", "मैं किससे रोया होगा ");
        map.put("Whom  will I have cut ", "मैंने किसको काट दिया होगा ");
        map.put("Whom  will I have danced ", "मैंने किससे नृत्य किया होगा ");
        map.put("Whom  will I have dealt ", "मैंने किससे निपटा होगा ");
        map.put("Whom  will I have died ", "मैं किसकी मरूंगा ");
        map.put("Whom  will I have dug ", "मैंने किसको खोदा होगा ");
        map.put("Whom  will I have drawn ", "मैंने किसको खींचा होगा ");
        map.put("Whom  will I have drunk ", "मैं किससे नशे में हूँ ");
        map.put("Whom  will I have driven ", "मैंने किसको चलाया होगा ");
        map.put("Whom  will I have dropped ", "मैं किसको गिरा दूंगा ");
        map.put("Whom  will I have dried ", "मैं किसको सुखाऊंगा ");
        map.put("Whom  will I have eaten ", "मैंने किसको खाया होगा ");
        map.put("Whom  will I have elected ", "मैं किसे चुनूंगा ");
        map.put("Whom  will I have entered ", "मैं किसमें प्रवेश करूंगा ");
        map.put("Whom  will I have fallen ", "मैं किससे गिरूंगा ");
        map.put("Whom  will I have fed ", "मैंने किसको खिलाया होगा ");
        map.put("Whom  will I have felt ", "मैंने किसका महसूस किया होगा ");
        map.put("Whom  will I have fought ", "मैं किससे लड़ा होगा ");
        map.put("Whom  will I have found ", "मुझे कौन मिल जाएगा ");
        map.put("Whom  will I have fled ", "मैं किससे भाग जाऊंगा ");
        map.put("Whom  will I have flown ", "मैं किससे उड़ जाऊंगा ");
        map.put("Whom  will I have forgotten ", "मैं किसको भूल जाऊंगा ");
        map.put("Whom  will I have fried ", "मैंने किसको तला होगा ");
        map.put("Whom  will I have got ", "मुझे किससे मिला होगा ");
        map.put("Whom  will I have given ", "मैंने किसे दिया होगा ");
        map.put("Whom  will I have gone ", "मैं किसके पास जाऊंगा ");
        map.put("Whom  will I have grown ", "मैं किससे बड़ा हो जाऊंगा ");
        map.put("Whom  will I have hanged ", "मैं किसको फांसी दे दूँगा ");
        map.put("Whom  will I have hung ", "मैंने किसको लटका दिया होगा ");
        map.put("Whom  will I have heard ", "मैंने किसको सुना होगा ");
        map.put("Whom  will I have helped ", "मैंने किसकी मदद की होगी ");
        map.put("Whom  will I have hidden ", "मैं किसको छिपाऊंगा ");
        map.put("Whom  will I have hit ", "मैंने किसको मारा होगा ");
        map.put("Whom  will I have held ", "मैंने किसे आयोजित किया होगा ");
        map.put("Whom  will I have hoped ", "मुझे किसकी उम्मीद होगी ");
        map.put("Whom  will I have hurt ", "मुझे किससे चोट लगी होगी ");
        map.put("Whom  will I have jumped ", "मैं किससे कूद जाऊंगा ");
        map.put("Whom  will I have kept ", "मैंने किसे रखा होगा ");
        map.put("Whom  will I have killed ", "मैं किसको मार डालूंगा ");
        map.put("Whom  will I have known ", "मुझे किससे पता चल जाएगा ");
        map.put("Whom  will I have laughed ", "मैं किसको हँसाऊंगा ");
        map.put("Whom  will I have led ", "मैंने किसका नेतृत्व किया होगा ");
        map.put("Whom  will I have leapt ", "मैं किससे छलांग लगाऊंगा ");
        map.put("Whom  will I have learnt ", "मैंने किससे सीखा होगा ");
        map.put("Whom  will I have left ", "मैंने किसको छोड़ा होगा ");
        map.put("Whom  will I have lent ", "मैंने किसको उधार दिया होगा ");
        map.put("Whom  will I have lived ", "मैं किससे रह पाऊंगा ");
        map.put("Whom  will I have looked ", "मैंने किसको देखा होगा ");
        map.put("Whom  will I have lost ", "मैं किसको खो दूँगा ");
        map.put("Whom  will I have loved ", "मैंने किससे प्यार किया होगा ");
        map.put("Whom  will I have made ", "मैंने किसको बनाया होगा ");
        map.put("Whom  will I have married ", "मैंने किससे शादी की होगी ");
        map.put("Whom  will I have met ", "मैं किससे मिलूंगा ");
        map.put("Whom  will I have mistaken ", "मैं किससे गलत होऊंगा ");
        map.put("Whom  will I have opened ", "मैंने किसे खोला होगा ");
        map.put("Whom  will I have paid ", "मैंने किसका भुगतान किया होगा ");
        map.put("Whom  will I have played ", "मैं किससे खेलूंगा ");
        map.put("Whom  will I have put ", "मैंने किसे रखा होगा ");
        map.put("Whom  will I have quarrelled ", "मैं किससे झगड़ा करूंगा ");
        map.put("Whom  will I have rained ", "मैं किसकी बारिश करूंगा ");
        map.put("Whom  will I have reached ", "मैं किसके पास पहुँचूँगा ");
        map.put("Whom  will I have read ", "मैंने किसको पढ़ा होगा ");
        map.put("Whom  will I have remembered ", "मुझे किसको याद होगा ");
        map.put("Whom  will I have ridden ", "मैंने किसकी सवारी की होगी ");
        map.put("Whom  will I have rung ", "मैं किससे रूंगा ");
        map.put("Whom  will I have risen ", "मैं किससे उठ जाऊंगा ");
        map.put("Whom  will I have run ", "मैं किससे दौड़ूंगा ");
        map.put("Whom  will I have said ", "मैंने किससे कहा होगा ");
        map.put("Whom  will I have seen ", "मैंने किसे देखा होगा ");
        map.put("Whom  will I have sold ", "मैंने किसे बेचा होगा ");
        map.put("Whom  will I have sent ", "मैंने किसे भेजा होगा ");
        map.put("Whom  will I have shaken ", "मैं किसको हिलाऊंगा ");
        map.put("Whom  will I have shone ", "मैं किससे चमकूंगा ");
        map.put("Whom  will I have shot ", "मैंने किसको गोली मार दी होगी ");
        map.put("Whom  will I have shown ", "मैंने किसे दिखाया होगा ");
        map.put("Whom  will I have shut ", "मैं किसको बंद कर दूँगा ");
        map.put("Whom  will I have sung ", "मैंने किसको गाया होगा ");
        map.put("Whom  will I have sunk ", "मैं किससे डूब जाऊंगा ");
        map.put("Whom  will I have slept ", "मैं किससे सोऊंगा ");
        map.put("Whom  will I have stayed ", "मैं किससे रुकूंगा ");
        map.put("Whom  will I have understood ", "मैं किसको समझ पाऊंगा ");

        return map;
    }
    static Map<String,String> Twelve(){
        HashMap<String,String>map = new HashMap<>();
        map.put("Whom  will I have been abusing ", "मैं किससे गाली दे रहा हूँ ");
        map.put("Whom  will I have been advising ", "मैं किसको सलाह दे रहा हूँ ");
        map.put("Whom  will I have been answering ", "मैं किसका जवाब दे रहा हूँ ");
        map.put("Whom  will I have been arising ", "मैं किससे उठ रहा हूँ ");
        map.put("Whom  will I have been arriving ", "मैं किससे आ रहा हूँ ");
        map.put("Whom  will I have been asking ", "मैं किससे पूछ रहा हूँ ");
        map.put("Whom  will I have been awaking ", "मैं किससे जाग रहा हूँ ");
        map.put("Whom  will I have been undefined", "मैं किससे अपरिभाषित हो जाऊंगा");
        map.put("Whom  will I have been bearing ", "मैं किसका असर डालूंगा ");
        map.put("Whom  will I have been beating ", "मैं किसकी पिटाई कर रहा हूँ ");
        map.put("Whom  will I have been becoming ", "मैं किससे बन रहा हूँ ");
        map.put("Whom  will I have been begging ", "मैं किससे भीख माँग रहा हूँ ");
        map.put("Whom  will I have been beginning ", "मैं किसकी शुरुआत कर रहा हूँ ");
        map.put("Whom  will I have been binding ", "मैं किससे बाध्यकारी रहा हूँ ");
        map.put("Whom  will I have been biting ", "मैं किसको काट रहा हूँ ");
        map.put("Whom  will I have been blessing ", "मैं किससे आशीष रहा हूँ ");
        map.put("Whom  will I have been blowing ", "मैं किसको उड़ा रहा हूँ ");
        map.put("Whom  will I have been breaking ", "मैं किसको तोड़ रहा हूँ ");
        map.put("Whom  will I have been bringing ", "मैं किसको ला रहा हूँ ");
        map.put("Whom  will I have been building ", "मैं किसका निर्माण कर रहा हूँ ");
        map.put("Whom  will I have been burning ", "मैं किसको जला रहा हूँ ");
        map.put("Whom  will I have been buying ", "मैं किसको खरीद रहा हूँ ");
        map.put("Whom  will I have been calling ", "मैं किसको बुला रहा हूँ ");
        map.put("Whom  will I have been carrying ", "मैं किसको ले जाऊंगा ");
        map.put("Whom  will I have been catching ", "मैं किसको पकड़ रहा हूँ ");
        map.put("Whom  will I have been cheating ", "मैं किसको धोखा दे रहा हूँ ");
        map.put("Whom  will I have been choosing ", "मैं किसे चुन रहा हूँ ");
        map.put("Whom  will I have been cleaning ", "मैं किसकी सफाई कर रहा हूँ ");
        map.put("Whom  will I have been climbing ", "मैं किसपर चढ़ रहा हूँ ");
        map.put("Whom  will I have been closing ", "मैं किसको बंद कर रहा हूँ ");
        map.put("Whom  will I have been coming ", "मैं किससे आ रहा हूँ ");
        map.put("Whom  will I have been cooking ", "मैं किससे खाना बना रहा हूँ ");
        map.put("Whom  will I have been creeping ", "मैं किससे रेंग रहा हूँ ");
        map.put("Whom  will I have been crying ", "मैं किससे रो रहा हूँ ");
        map.put("Whom  will I have been cutting ", "मैं किसको काट रहा हूँ ");
        map.put("Whom  will I have been dancing ", "मैं किससे नाचता रहा हूँ ");
        map.put("Whom  will I have been dealing ", "मैं किससे निपट रहा हूँ ");
        map.put("Whom  will I have been dying ", "मैं किससे मर रहा हूँ ");
        map.put("Whom  will I have been digging ", "मैं किसकी खुदाई कर रहा हूँ ");
        map.put("Whom  will I have been drawing ", "मैं किसको चित्रित कर रहा हूँ ");
        map.put("Whom  will I have been drinking ", "मैं किससे पी रहा हूँ ");
        map.put("Whom  will I have been driving ", "मैं किसकी गाड़ी चला रहा हूँ ");
        map.put("Whom  will I have been dropping ", "मैं किसको छोड़ रहा हूँ ");
        map.put("Whom  will I have been drying ", "मैं किसको सुखा रहा हूँ ");
        map.put("Whom  will I have been eating ", "मैं किसको खा रहा हूँ ");
        map.put("Whom  will I have been electing ", "मैं किसका चुनाव कर रहा हूँ ");
        map.put("Whom  will I have been entering ", "मैं किसमें प्रवेश कर रहा हूँ ");
        map.put("Whom  will I have been falling ", "मैं किससे गिर रहा हूँ ");
        map.put("Whom  will I have been feeding ", "मैं किसको खिला रहा हूँ ");
        map.put("Whom  will I have been feeling ", "मैं किसका महसूस कर रहा हूँ ");
        map.put("Whom  will I have been fighting ", "मैं किससे लड़ रहा हूँ ");
        map.put("Whom  will I have been finding ", "मुझे किसकी खोज हो रही होगी ");
        map.put("Whom  will I have been fleeing ", "मैं किससे भाग रहा हूँ ");
        map.put("Whom  will I have been flying ", "मैं किससे उड़ रहा हूँ ");
        map.put("Whom  will I have been forgetting ", "मैं किसको भूल गया होता ");
        map.put("Whom  will I have been frying ", "मैं किससे फ्राइंग कर रहा हूँ ");
        map.put("Whom  will I have been getting ", "मुझे किससे मिल रहा होगा ");
        map.put("Whom  will I have been giving ", "मैं किसे दे रहा हूँ ");
        map.put("Whom  will I have been going ", "मैं किससे जा रहा हूँ ");
        map.put("Whom  will I have been growing ", "मैं किससे बढ़ रहा हूँ ");
        map.put("Whom  will I have been hanging ", "मैं किसको लटका रहा हूँ ");
        map.put("Whom  will I have been hearing ", "मैं किससे सुन रहा हूँ ");
        map.put("Whom  will I have been helping ", "मैं किसकी मदद कर रहा हूँ ");
        map.put("Whom  will I have been hiding ", "मैं किसको छिपा रहा हूँ ");
        map.put("Whom  will I have been hitting ", "मैं किसको मार रहा हूँ ");
        map.put("Whom  will I have been holding ", "मैं किसको पकड़ रहा हूँ ");
        map.put("Whom  will I have been hoping ", "मैं किसकी उम्मीद कर रहा था ");
        map.put("Whom  will I have been hurting ", "मैं किसको चोट पहुँचा रहा हूँ ");
        map.put("Whom  will I have been jumping ", "मैं किससे कूद रहा हूँ ");
        map.put("Whom  will I have been keeping ", "मैं किसको रख रहा हूँ ");
        map.put("Whom  will I have been killing ", "मैं किसको मार रहा हूँ ");
        map.put("Whom  will I have been knowing ", "मैं किसको जान रहा हूँ ");
        map.put("Whom  will I have been laughing ", "मैं किससे हँस रहा हूँ ");
        map.put("Whom  will I have been leading ", "मैं किसकी अगुवाई कर रहा हूँ ");
        map.put("Whom  will I have been leaping ", "मैं किससे छलांग लगा रहा हूँ ");
        map.put("Whom  will I have been learning ", "मैं किससे सीख रहा हूँ ");
        map.put("Whom  will I have been leaving ", "मैं किसको छोड़ रहा हूँ ");
        map.put("Whom  will I have been lending ", "मैं किसे उधार दे रहा हूँ ");
        map.put("Whom  will I have been living ", "मैं किससे रह रहा हूँ ");
        map.put("Whom  will I have been looking ", "मैं किसको देख रहा हूँ ");
        map.put("Whom  will I have been losing ", "मैं किसको खो रहा हूँ ");
        map.put("Whom  will I have been loving ", "मैं किससे प्यार कर रहा हूँ ");
        map.put("Whom  will I have been making ", "मैं किसको बना रहा हूँ ");
        map.put("Whom  will I have been marrying ", "मैं किससे शादी कर रहा हूँ ");
        map.put("Whom  will I have been meeting ", "मैं किससे मिल रहा हूँ ");
        map.put("Whom  will I have been mistaking ", "मैं किससे गलत कर रहा हूँ ");
        map.put("Whom  will I have been opening ", "मैं किसको खोल रहा हूँ ");
        map.put("Whom  will I have been paying ", "मैं किसका भुगतान कर रहा हूँ ");
        map.put("Whom  will I have been playing ", "मैं किससे खेलूंगा ");
        map.put("Whom  will I have been putting ", "मैं किसको लगा रहा हूँ ");
        map.put("Whom  will I have been quarrelling ", "मैं किससे झगड़ा कर रहा हूँ ");
        map.put("Whom  will I have been raining ", "मैं किसकी बारिश कर रहा हूँ ");
        map.put("Whom  will I have been reaching ", "मैं किसतक पहुँच रहा हूँ ");
        map.put("Whom  will I have been reading ", "मैं किसको पढ़ रहा हूँ ");
        map.put("Whom  will I have been remembering ", "मैं किसको याद कर रहा हूँ ");
        map.put("Whom  will I have been riding ", "मैं किसकी सवारी कर रहा हूँ ");
        map.put("Whom  will I have been ringing ", "मैं किससे बज रहा हूँ ");
        map.put("Whom  will I have been rising ", "मैं किससे उठ रहा हूँ ");
        map.put("Whom  will I have been running ", "मैं किससे दौड़ रहा हूँ ");
        map.put("Whom  will I have been saying ", "मैं किससे कह रहा हूँ ");
        map.put("Whom  will I have been seeing ", "मैं किसे देख रहा हूँ ");
        map.put("Whom  will I have been selling ", "मैं किसे बेच रहा हूँ ");
        map.put("Whom  will I have been sending ", "मैं किसको भेज रहा हूँ ");
        map.put("Whom  will I have been shaking ", "मैं किसको हिला रहा हूँ ");
        map.put("Whom  will I have been shining ", "मैं किससे चमक रहा हूँ ");
        map.put("Whom  will I have been shooting ", "मैं किसकी शूटिंग कर रहा हूँ ");
        map.put("Whom  will I have been showing ", "मैं किसे दिखा रहा हूँ ");
        map.put("Whom  will I have been shutting ", "मैं किसको बंद कर रहा हूँ ");
        map.put("Whom  will I have been singing ", "मैं किससे गा रहा हूँ ");
        map.put("Whom  will I have been sinking ", "मैं किससे डूब रहा हूँ ");
        map.put("Whom  will I have been sleeping ", "मैं किससे सो रहा हूँ ");
        map.put("Whom  will I have been spoilt", "मैं किसको खराब कर दिया गया होगा");
        map.put("Whom  will I have been using ", "मैं किसका उपयोग कर रहा हूँ ");

        return map;
    }


}
