package com.shiviishiv7.helloenglish.QuestionSource;


import java.util.HashMap;
import java.util.Map;

public class Whose {
    public static Map<String,String> Whose(int state){
        switch (state){
            case 1:return One();
            case 2:return Two();
            case 3:return Three();
            case 4:return Four();
            case 5:return Five();
            case 6:return Six();
            case 7:return Seven();
            case 8:return Eight();
            case 9:return Nine();
            case 10:return Ten();
            case 11:return Eleven();
            case 12:return Twelve();

            default:return One();
        }

    }
    static Map<String,String> One(){
        HashMap<String,String>map = new HashMap<>();
        map.put("Whose do I abuse ", "मैं किसके साथ गाली दूं ");
        map.put("Whose do I advise", "मैं किसकी सलाह देता हूँ");
        map.put("Whose do I answer ", "मैं किसका जवाब दूँ ");
        map.put("Whose do I arise ", "मैं किसका उठता हूँ ");
        map.put("Whose do I arrive ", "मैं किसके पास आता हूँ ");
        map.put("Whose do I ask ", "मैं किससे पूछूँ ");
        map.put("Whose do I awake ", "मैं किसका जागता हूँ ");

        map.put("Whose do I bear ", "मैं किसका सहन करता हूँ ");
        map.put("Whose do I beat ", "मैं किसका हराऊं ");
        map.put("Whose do I become ", "मैं किसका बन जाऊं ");
        map.put("Whose do I beg ", "मैं किसकी भीख मांगता हूँ ");
        map.put("Whose do I begin ", "मैं किससे शुरू करूँ ");
        map.put("Whose do I bind ", "मैं किसका बाँधता हूँ ");
        map.put("Whose do I bite", "मैं किसका काटता हूँ");
        map.put("Whose do I bless", "मैं किसका आशीर्वाद देता हूँ");
        map.put("Whose do I blow ", "मैं किसका उड़ाता हूँ ");
        map.put("Whose do I break ", "मैं किसका तोड़ता हूँ ");
        map.put("Whose do I bring ", "मैं किसका लाऊं ");
        map.put("Whose do I build ", "मैं किसका निर्माण करूँ ");
        map.put("Whose do I burn ", "मैं किसका जलाता हूँ ");
        map.put("Whose do I buy ", "मैं किसका खरीदूँ ");
        map.put("Whose do I call ", "मैं किसका फोन करता हूँ ");
        map.put("Whose do I carry ", "मैं किसका ले जाऊं ");
        map.put("Whose do I catch ", "मैं किसको पकड़ता हूँ ");
        map.put("Whose do I choose ", "मैं किसका चुनूं ");
        map.put("Whose do I clean ", "मैं किसकी सफाई करता हूँ ");
        map.put("Whose do I climb  ", "मैं किसकी चढ़ाई करूँ  ");
        map.put("Whose do I close ", "मैं किसका बंद करता हूँ ");
        map.put("Whose do I come ", "मैं किसका आता हूँ ");
        map.put("Whose do I cook ", "मैं किसका खाना बनाती हूँ ");
        map.put("Whose do I creep ", "मैं किसका रेंगता हूँ ");
        map.put("Whose do I cry ", "मैं किसका रोता हूँ ");
        map.put("Whose do I cut ", "मैं किसका काटूं ");
        map.put("Whose do I dance ", "मैं किसका नृत्य करता हूँ ");
        map.put("Whose do I deal ", "मैं किसका सौदा करता हूँ ");
        map.put("Whose do I die ", "मैं किसका मर जाऊँ ");
        map.put("Whose do I dig ", "मैं किसका खोदूँ ");
        map.put("Whose do I do ", "मैं किसका करता हूँ ");
        map.put("Whose  did I  do ", "मैंने किसका किया ");
        map.put("Whose  was I  doing ", "मैं किसका कर रहा था ");
        map.put("Whose  had I  done ", "मैंने किसका किया था ");
        map.put("Whose  had I been  doing ", "मैं किसका कर रहा था ");
        map.put("Whose  will I do ", "मैं किसका करूँगा ");
        map.put("Whose  will I be doing ", "मैं किसका कर रहा हूँ ");
        map.put("Whose  will I have done ", "मैंने किसका किया होगा ");
        map.put("Whose  will I have been doing ", "मैं किसका कर रहा हूँ ");
        map.put("Whose do I draw ", "मैं किसका आकर्षित करता हूँ ");
        map.put("Whose do I drive ", "मैं किसका ड्राइव करूँ ");
        map.put("Whose do I drop ", "मैं किसका छोड़ दूँ ");
        map.put("Whose do I dry ", "मैं किसका सूखता हूँ ");
        map.put("Whose do I eat ", "मैं किसका खाऊं ");
        map.put("Whose do I elect", "मैं किसका चुनाव करता हूँ");
        map.put("Whose do I fall ", "मैं किसका गिरता हूँ ");
        map.put("Whose do I feed ", "मैं किसका खिलाऊं ");
        map.put("Whose do I feel  ", "मैं किसका महसूस करता हूँ  ");
        map.put("Whose do I fight ", "मैं किससे लड़ता हूँ ");
        map.put("Whose do I find ", "मुझे किसका पता है ");
        map.put("Whose do I flee ", "मैं किससे भागता हूँ ");
        map.put("Whose do I fly  ", "मैं किसका उड़ूँ  ");
        map.put("Whose do I forget ", "मैं किसका भूल जाऊं ");
        map.put("Whose do I fry ", "मैं किसका फ्राई करता हूँ ");
        map.put("Whose do I get  ", "मुझे किसका मिलेगा  ");
        map.put("Whose do I give ", "मैं किसका देता हूँ ");
        map.put("Whose do I go ", "मैं किसका जाऊँ ");
        map.put("Whose do I grow", "मैं किसका उगता हूँ");
        map.put("Whose do I hang ", "मैं किसका लटकाऊं ");
        map.put("Whose do I hear ", "मैं किसका सुनता हूँ ");
        map.put("Whose do I help ", "मैं किसकी मदद करूँ ");
        map.put("Whose do I hide ", "मैं किसका छिपाऊं ");
        map.put("Whose do I hit ", "मैं किसका हिट करता हूँ ");
        map.put("Whose do I hold ", "मैं किसका धारण करता हूँ ");
        map.put("Whose do I hope ", "मुझे किसकी उम्मीद है ");
        map.put("Whose do I hurt ", "मुझे किसकी चोट लगी है ");
        map.put("Whose do I jump ", "मैं किसका कूदता हूँ ");
        map.put("Whose do I kill ", "मैं किसका मारूँ ");
        map.put("Whose do I know ", "मुझे किसका पता है ");
        map.put("Whose do I laugh ", "मैं किसके हँसता हूँ ");
        map.put("Whose do I lead ", "मैं किसका नेतृत्व करता हूँ ");
        map.put("Whose do I leap ", "मैं किसकी छलांग लगाता हूँ ");
        map.put("Whose do I learn ", "मैं किसका सीखता हूँ ");
        map.put("Whose do I leave ", "मैं किसकी छोड़ूँ ");
        map.put("Whose do I lend ", "मैं किसका उधार देता हूँ ");
        map.put("Whose do I live ", "मैं किसका रहता हूँ ");
        map.put("Whose do I look ", "मैं किसका दिखता हूँ ");
        map.put("Whose do I lose ", "मैं किसका हारता हूँ ");
        map.put("Whose do I love ", "मैं किससे प्यार करता हूँ ");
        map.put("Whose do I make ", "मैं किसका बनाऊँ ");
        map.put("Whose do I marry ", "मैं किससे शादी करूँ ");
        map.put("Whose do I meet ", "मैं किससे मिलता हूँ ");
        map.put("Whose do I mistake ", "मैं किसकी गलती करता हूँ ");
        map.put("Whose do I open ", "मैं किसका खोल सकता हूँ ");
        map.put("Whose do I pay  ", "मैं किसका भुगतान करता हूँ  ");
        map.put("Whose do I play ", "मैं किसका खेलूँ ");
        map.put("Whose do I put ", "मैं किसका रखूँ ");
        map.put("Whose do I rain ", "मैं किसकी बारिश करता हूँ ");
        map.put("Whose do I reach ", "मैं किसतक पहुँचूँ ");
        map.put("Whose do I read", "मैं किसका पढ़ूँ");
        map.put("Whose do I remember  ", "मुझे किसका याद है  ");
        map.put("Whose do I ride ", "मैं किसकी सवारी करूँ ");
        map.put("Whose do I ring ", "मैं किसकी अंगूठी करता हूँ ");
        map.put("Whose do I rise  ", "मैं किसका उठ सकता हूँ  ");
        map.put("Whose do I run  ", "मैं किसका दौड़ता हूँ  ");
        map.put("Whose do I say ", "मैं किसका कहता हूँ ");
        map.put("Whose do I see ", "मैं किसका देखता हूँ ");
        map.put("Whose do I sell ", "मैं किसका बेचूँ ");
        map.put("Whose do I send ", "मैं किसका भेजूं ");
        map.put("Whose do I shake ", "मैं किसका हिलाता हूँ ");
        map.put("Whose do I shine ", "मैं किसका चमकता हूँ ");
        map.put("Whose do I shoot ", "मैं किसका शूट करूँ ");
        map.put("Whose do I show ", "मैं किसका दिखाऊँ ");
        map.put("Whose do I shut  ", "मैं किसका बंद करूँ  ");
        map.put("Whose do I sing ", "मैं किसका गाऊं ");
        map.put("Whose do I steal ", "मैं किसकी चोरी करता हूँ ");
        map.put("Whose do I wash ", "मैं किसका धोता हूँ ");

        return map;
    }
    static Map<String,String> Two(){
        HashMap<String,String>map = new HashMap<>();
        map.put("Whose am I abusing ", "मैं किसका गाली दे रहा हूँ ");
        map.put("Whose am I advising ", "मैं किसकी सलाह दे रहा हूँ ");
        map.put("Whose am I answering ", "मैं किसका जवाब दे रहा हूँ ");
        map.put("Whose am I arising ", "मैं किसका उठ रहा हूँ ");
        map.put("Whose am I arriving ", "मैं किसका आ रहा हूँ ");
        map.put("Whose am I asking ", "मैं किससे पूछ रहा हूँ ");
        map.put("Whose am I awaking ", "मैं किसका जाग रहा हूँ ");
        map.put("Whose am I undefined", "मैं किसका अपरिभाषित हूँ");
        map.put("Whose am I bearing ", "मैं किसका असर कर रहा हूँ ");
        map.put("Whose am I beating ", "मैं किसकी पिटाई कर रहा हूँ ");
        map.put("Whose am I becoming ", "मैं किसका बन रहा हूँ ");
        map.put("Whose am I begging ", "मैं किसकी भीख मांग रहा हूँ ");
        map.put("Whose am I beginning ", "मैं किसका शुरू कर रहा हूँ ");
        map.put("Whose am I binding ", "मैं किसका बाध्यकारी हूँ ");
        map.put("Whose am I biting ", "मैं किसका काट रहा हूँ ");
        map.put("Whose am I blessing ", "मैं किसका आशीर्वाद दे रहा हूँ ");
        map.put("Whose am I blowing ", "मैं किसका उड़ा रहा हूँ ");
        map.put("Whose am I breaking ", "मैं किसका तोड़ रहा हूँ ");
        map.put("Whose am I bringing ", "मैं किसका ला रहा हूँ ");
        map.put("Whose am I building ", "मैं किसका निर्माण कर रहा हूँ ");
        map.put("Whose am I burning ", "मैं किसका जल रहा हूँ ");
        map.put("Whose am I buying ", "मैं किसका खरीद रहा हूँ ");
        map.put("Whose am I calling ", "मैं किसका फोन कर रहा हूँ ");
        map.put("Whose am I carrying ", "मैं किसका ले जा रहा हूँ ");
        map.put("Whose am I catching ", "मैं किसका पकड़ रहा हूँ ");
        map.put("Whose am I cheating ", "मैं किसका धोखा दे रहा हूँ ");
        map.put("Whose am I choosing ", "मैं किसका चयन कर रहा हूँ ");
        map.put("Whose am I cleaning ", "मैं किसका सफाई कर रहा हूँ ");
        map.put("Whose am I climbing ", "मैं किसका चढ़ रहा हूँ ");
        map.put("Whose am I closing ", "मैं किसका बंद कर रहा हूँ ");
        map.put("Whose am I coming ", "मैं किसका आ रहा हूँ ");
        map.put("Whose am I cooking ", "मैं किसका खाना बना रहा हूँ ");
        map.put("Whose am I creeping ", "मैं किसका रेंग रहा हूँ ");
        map.put("Whose am I crying ", "मैं किसका रो रहा हूँ ");
        map.put("Whose am I cutting ", "मैं किसका काट रहा हूँ ");
        map.put("Whose am I dancing ", "मैं किसका नाच रहा हूँ ");
        map.put("Whose am I dealing ", "मैं किसका काम कर रहा हूँ ");
        map.put("Whose am I dying ", "मैं किसका मर रहा हूँ ");
        map.put("Whose am I digging ", "मैं किसकी खुदाई कर रहा हूँ ");
        map.put("Whose am I doing ", "मैं किसका कर रहा हूँ ");
        map.put("Whose am I drawing ", "मैं किसका चित्र बना रहा हूँ ");
        map.put("Whose do I dream ", "मैं किसका सपना देखता हूँ ");
        map.put("Whose am I dreaming ", "मैं किसका सपना देख रहा हूँ ");
        map.put("Whose  have I been dreaming ", "मैं किसका सपना देख रहा हूँ ");
        map.put("Whose  did I  dream ", "मैंने किसका सपना देखा था ");
        map.put("Whose  have I dreamt ", "मैंने किसका सपना देखा है ");
        map.put("Whose  was I  dreaming ", "मैं किसका सपना देख रहा था ");
        map.put("Whose  had I  dreamt ", "मैंने किसका सपना देखा था ");
        map.put("Whose  had I been  dreaming ", "मैं किसका सपना देख रहा था ");
        map.put("Whose  will I have dreamt ", "मैंने किसका सपना देखा होगा ");
        map.put("Whose  will I be dreaming ", "मैं किसका सपना देख रहा हूँ ");
        map.put("Whose  will I have been dreaming ", "मैं किसका सपना देख रहा हूँ ");
        map.put("Whose am I drinking ", "मैं किसका पी रहा हूँ ");
        map.put("Whose am I driving ", "मैं किसका गाड़ी चला रहा हूँ ");
        map.put("Whose am I dropping ", "मैं किसका छोड़ रहा हूँ ");
        map.put("Whose am I drying ", "मैं किसका सुखा रहा हूँ ");
        map.put("Whose am I eating ", "मैं किसका खा रहा हूँ ");
        map.put("Whose am I electing ", "मैं किसका चुनाव कर रहा हूँ ");
        map.put("Whose am I entering ", "मैं किसका प्रवेश कर रहा हूँ ");
        map.put("Whose am I falling ", "मैं किसका गिर रहा हूँ ");
        map.put("Whose am I feeding ", "मैं किसका खिला रहा हूँ ");
        map.put("Whose am I feeling ", "मैं किसका महसूस कर रहा हूँ ");
        map.put("Whose am I fighting ", "मैं किससे लड़ रहा हूँ ");
        map.put("Whose am I finding ", "मैं किसका खोज रहा हूँ ");
        map.put("Whose am I fleeing ", "मैं किससे भाग रहा हूँ ");
        map.put("Whose am I flying ", "मैं किसका उड़ रहा हूँ ");
        map.put("Whose am I forgetting ", "मैं किसकी भूल रहा हूँ ");
        map.put("Whose am I frying ", "मैं किसका फ्राइंग कर रहा हूँ ");
        map.put("Whose am I getting ", "मुझे किसका मिल रहा है ");
        map.put("Whose am I giving ", "मैं किसका दे रहा हूँ ");
        map.put("Whose am I going ", "मैं किसका जा रहा हूँ ");
        map.put("Whose am I growing ", "मैं किसका बढ़ रहा हूँ ");
        map.put("Whose am I hanging ", "मैं किसका लटक रहा हूँ ");
        map.put("Whose am I hearing ", "मैं किसका सुन रहा हूँ ");
        map.put("Whose am I helping ", "मैं किसका मदद कर रहा हूँ ");
        map.put("Whose am I hiding ", "मैं किसका छिपा रहा हूँ ");
        map.put("Whose am I hitting ", "मैं किसका मार रहा हूँ ");
        map.put("Whose am I holding ", "मैं किसका पकड़ रहा हूँ ");
        map.put("Whose am I hoping ", "मैं किसका उम्मीद कर रहा हूँ ");
        map.put("Whose am I hurting ", "मैं किसका चोट पहुँचा रहा हूँ ");
        map.put("Whose am I jumping ", "मैं किसका कूद रहा हूँ ");
        map.put("Whose am I keeping ", "मैं किसका रख रहा हूँ ");
        map.put("Whose am I killing ", "मैं किसका मार रहा हूँ ");
        map.put("Whose am I knowing ", "मैं किसका जान रहा हूँ ");
        map.put("Whose am I laughing ", "मैं किसका हँस रहा हूँ ");
        map.put("Whose am I leading ", "मैं किसका नेतृत्व कर रहा हूँ ");
        map.put("Whose am I leaping ", "मैं किसकी छलांग लगा रहा हूँ ");
        map.put("Whose am I learning ", "मैं किसका सीख रहा हूँ ");
        map.put("Whose am I leaving ", "मैं किसका छोड़ रहा हूँ ");
        map.put("Whose am I lending ", "मैं किसका उधार दे रहा हूँ ");
        map.put("Whose am I living ", "मैं किसका जी रहा हूँ ");
        map.put("Whose am I looking ", "मैं किसका देख रहा हूँ ");
        map.put("Whose am I losing ", "मैं किसका हार रहा हूँ ");
        map.put("Whose am I loving ", "मैं किसका प्यार कर रहा हूँ ");
        map.put("Whose am I making ", "मैं किसका बना रहा हूँ ");
        map.put("Whose am I marrying ", "मैं किससे शादी कर रहा हूँ ");
        map.put("Whose am I meeting ", "मैं किससे मिल रहा हूँ ");
        map.put("Whose am I mistaking ", "मैं किसकी गलती कर रहा हूँ ");
        map.put("Whose am I opening ", "मैं किसका खोल रहा हूँ ");
        map.put("Whose am I paying ", "मैं किसका भुगतान कर रहा हूँ ");
        map.put("Whose am I playing ", "मैं किसका खेल रहा हूँ ");
        map.put("Whose am I putting ", "मैं किसका लगा रहा हूँ ");
        map.put("Whose am I quarrelling ", "मैं किसका झगड़ा कर रहा हूँ ");
        map.put("Whose am I raining ", "मैं किसकी बारिश कर रहा हूँ ");
        map.put("Whose am I reaching ", "मैं किसके पास पहुँच रहा हूँ ");
        map.put("Whose am I reading ", "मैं किसका पढ़ रहा हूँ ");
        map.put("Whose am I remembering ", "मैं किसका याद कर रहा हूँ ");
        map.put("Whose am I riding ", "मैं किसका सवारी कर रहा हूँ ");
        map.put("Whose am I ringing ", "मैं किसका बज रहा हूँ ");
        map.put("Whose am I rising ", "मैं किसका उठ रहा हूँ ");
        map.put("Whose am I running ", "मैं किसका भाग रहा हूँ ");
        map.put("Whose am I saying ", "मैं किसका कह रहा हूँ ");
        map.put("Whose am I seeing ", "मैं किसका देख रहा हूँ ");
        map.put("Whose am I selling ", "मैं किसका बेच रहा हूँ ");
        map.put("Whose am I sending ", "मैं किसका भेज रहा हूँ ");
        map.put("Whose am I shaking ", "मैं किसका हिला रहा हूँ ");
        map.put("Whose am I shining ", "मैं किसका चमक रहा हूँ ");
        map.put("Whose am I shooting ", "मैं किसका शूटिंग कर रहा हूँ ");
        map.put("Whose am I showing ", "मैं किसका दिखा रहा हूँ ");

        return map;
    }
    static Map<String,String> Three(){
        HashMap<String,String>map = new HashMap<>();
        map.put("Whose  have I abused ", "मैंने किसके साथ गाली दी है ");
        map.put("Whose  have I advised ", "मैंने किसकी सलाह दी है ");
        map.put("Whose  have I answered ", "मैंने किसका उत्तर दिया है ");
        map.put("Whose  have I arisen ", "मैं किसका पैदा हुआ हूँ ");
        map.put("Whose  have I arrived ", "मैं किसके पास आया हूँ ");
        map.put("Whose  have I asked ", "मैंने किससे पूछा है ");
        map.put("Whose  have I awoken ", "मैं किसका जाग गया हूँ ");
        map.put("Whose  have I undefined", "किसका मैंने अपरिभाषित किया है");
        map.put("Whose  have I borne ", "मैंने किसका जन्म लिया है ");
        map.put("Whose  have I beaten ", "मैंने किसका पीटा है ");
        map.put("Whose  have I become ", "मैं किसका बन गया हूँ ");
        map.put("Whose  have I begged ", "मैंने किसकी भीख मांगी है ");
        map.put("Whose  have I begun ", "मैंने किसकी शुरुआत की है ");
        map.put("Whose  have I bound ", "मैंने किसका बाध्य किया है ");
        map.put("Whose  have I bitten ", "मैंने किसका काटा है ");
        map.put("Whose  have I blessed ", "मैंने किसका आशीर्वाद दिया है ");
        map.put("Whose  have I blown ", "मैंने किसका उड़ा दिया है ");
        map.put("Whose  have I broken ", "मैंने किसका तोड़ा है ");
        map.put("Whose  have I brought ", "मैं किसका लाया हूँ ");
        map.put("Whose  have I built ", "मैंने किसका निर्माण किया है ");
        map.put("Whose  have I burnt ", "मैंने किसका जलाया है ");
        map.put("Whose  have I bought ", "मैंने किसका खरीदा है ");
        map.put("Whose  have I called ", "मैंने किसका फोन किया है ");
        map.put("Whose  have I carried ", "मैंने किसका किया है ");
        map.put("Whose  have I caught ", "मैंने किसका पकड़ा है ");
        map.put("Whose  have I cheated ", "मैंने किसके साथ धोखा दिया है ");
        map.put("Whose  have I chosen ", "मैंने किसका चुना है ");
        map.put("Whose  have I cleaned ", "मैंने किसकी सफाई की है ");
        map.put("Whose  have I climbed ", "मैं किसके ऊपर चढ़ गया हूँ ");
        map.put("Whose  have I closed ", "मैंने किसका बंद किया है ");
        map.put("Whose  have I come ", "मैं किसके पास आया हूँ ");
        map.put("Whose  have I cooked ", "मैंने किसका खाना बनाया है ");
        map.put("Whose  have I crept ", "जिनके पास मैंने क्रेप्ट किया है ");
        map.put("Whose  have I cried ", "मैंने किसका रोया है ");
        map.put("Whose  have I cut ", "मैंने किसका काटा है ");
        map.put("Whose  have I danced ", "मैंने किसका नृत्य किया है ");
        map.put("Whose  have I dealt ", "मैंने किसका निपटा है ");
        map.put("Whose  have I died ", "मैं किसका मर चुका हूँ ");
        map.put("Whose  have I dug ", "मैंने किसका खोदा है ");
        map.put("Whose  have I done ", "मैंने किसका किया है ");
        map.put("Whose  have I drawn ", "मैंने किसका खींचा है ");
        map.put("Whose  have I drunk ", "मैंने किसका पिया है ");
        map.put("Whose  have I driven ", "मैंने किसका चलाया है ");
        map.put("Whose  have I dropped ", "मैंने किसका गिरा दिया है ");
        map.put("Whose  have I dried ", "मैंने किसका सुखाया है ");
        map.put("Whose  have I eaten ", "मैंने किसका खाया है ");
        map.put("Whose  have I elected ", "मैंने किसका चुना है ");
        map.put("Whose  have I entered ", "मैंने किसका प्रवेश किया है ");
        map.put("Whose  have I fallen ", "मैं किसका गिर गया हूँ ");
        map.put("Whose  have I fed ", "मैंने किसका खिलाया है ");
        map.put("Whose  have I felt ", "मैंने किसका महसूस किया है ");
        map.put("Whose  have I fought ", "मैंने किसकी लड़ाई लड़ी है ");
        map.put("Whose  have I found ", "मैंने किसका पाया है ");
        map.put("Whose  have I fled ", "मैं किसका भाग गया हूँ ");
        map.put("Whose  have I flown ", "मैंने किसका उड़ाया है ");
        map.put("Whose  have I forgotten ", "मैं किसका भूल गया हूँ ");
        map.put("Whose  have I fried ", "मैंने किसके तले हैं ");
        map.put("Whose  have I got ", "मुझे किसका मिला है ");
        map.put("Whose  have I given ", "मैंने किसका दिया है ");
        map.put("Whose  have I gone ", "मैं किसके पास गया हूँ ");
        map.put("Whose  have I grown ", "मैं किसका उगाया हूँ ");
        map.put("Whose  have I hanged ", "मैंने किसको फांसी दी है ");
        map.put("Whose  have I hung ", "मैंने किसके पास लटका दिया है ");
        map.put("Whose  have I heard ", "मैंने किसके बारे में सुना है ");
        map.put("Whose  have I helped ", "मैंने किसकी मदद की है ");
        map.put("Whose  have I hidden ", "मैंने किसका छिपा दिया है ");
        map.put("Whose  have I hit ", "मैंने किसका मारा है ");
        map.put("Whose  have I held ", "मैंने किसके पास रखा है ");
        map.put("Whose  have I hoped ", "मैंने किसकी उम्मीद की है ");
        map.put("Whose  have I hurt ", "किसकी मुझे चोट लगी है ");
        map.put("Whose  have I jumped ", "मैं किसका कूद गया हूँ ");
        map.put("Whose  have I kept ", "मैंने किसका रखा है ");
        map.put("Whose  have I killed ", "मैंने किसका मारा है ");
        map.put("Whose  have I known ", "मुझे किसका पता है ");
        map.put("Whose  have I laughed ", "मैं किसका हँसा है ");
        map.put("Whose  have I led ", "मैंने किसका नेतृत्व किया है ");
        map.put("Whose  have I leapt ", "मैंने किसका छलांग लगाई है ");
        map.put("Whose  have I learnt ", "मैंने किसका सीखा है ");
        map.put("Whose  have I left ", "मैंने किसका छोड़ा है ");
        map.put("Whose  have I lent ", "मैंने किसका उधार दिया है ");
        map.put("Whose  have I lived ", "मैं किसके पास रहता हूँ ");
        map.put("Whose  have I looked ", "मैंने किसका देखा है ");
        map.put("Whose  have I lost ", "मैंने किसका खो दिया है ");
        map.put("Whose  have I loved ", "मैंने किससे प्यार किया है ");
        map.put("Whose  have I made ", "मैंने किसका बनाया है ");
        map.put("Whose  have I married ", "मैंने किसकी शादी की है ");
        map.put("Whose  have I met ", "मैं किससे मिला हूँ ");
        map.put("Whose  have I mistaken ", "मैंने किसकी गलती की है ");
        map.put("Whose  have I opened ", "मैंने किसका खोला है ");
        map.put("Whose  have I paid ", "मैंने किसका भुगतान किया है ");
        map.put("Whose  have I played ", "मैंने किसका खेला है ");
        map.put("Whose  have I put ", "मैंने किसके पास रखा है ");
        map.put("Whose  have I quarrelled ", "मैंने किसके साथ झगड़ा किया है ");
        map.put("Whose  have I rained ", "मैंने किसकी बारिश की है ");
        map.put("Whose  have I reached ", "मैं किसके पास पहुँचा हूँ ");
        map.put("Whose  have I read ", "मैंने किसका पढ़ा है ");
        map.put("Whose  have I remembered ", "मुझे किसका याद है ");
        map.put("Whose  have I rung ", "किसका मैंने बजाया है ");
        map.put("Whose  have I ridden ", "मैंने किसकी सवारी की है ");
        map.put("Whose  have I risen ", "मैं किसका उठ गया हूँ ");
        map.put("Whose  have I run ", "किसका मैं चला रहा हूँ ");
        map.put("Whose  have I said ", "मैंने किसका कहा है ");
        map.put("Whose  have I seen ", "मैंने किसका देखा है ");
        map.put("Whose  have I sold ", "मैंने किसका बेचा है ");
        map.put("Whose  have I sent ", "मैंने किसका भेजा है ");
        map.put("Whose  have I shaken ", "मैंने किसका हिला दिया है ");
        map.put("Whose  have I shone ", "मैं किसका चमक रहा हूँ ");
        map.put("Whose  have I shot ", "किसका मैंने गोली मार दी है ");
        map.put("Whose  have I shown ", "मैंने किसका दिखाया है ");
        map.put("Whose  have I  spoiled ", "मैंने किसका बिगाड़ा है ");

        return map;
    }
    static Map<String,String> Four(){
        HashMap<String,String>map = new HashMap<>();
        map.put("Whose  have I been abusing ", "मैं किसका गाली दे रहा हूं ");
        map.put("Whose  have I been advising ", "मैं किसकी सलाह दे रहा हूं ");
        map.put("Whose  have I been answering ", "मैं किसका जवाब दे रहा हूं ");
        map.put("Whose  have I been arising ", "मैं किसका उठ रहा हूँ ");
        map.put("Whose  have I been arriving ", "मैं किसका आ रहा हूँ ");
        map.put("Whose  have I been asking ", "मैं किससे पूछ रहा हूँ ");
        map.put("Whose  have I been awaking ", "मैं किसका जाग रहा हूँ ");
        map.put("Whose  have I been undefined", "किसका मुझे अपरिभाषित किया गया है");
        map.put("Whose  have I been bearing ", "मैं किसका असर कर रहा हूँ ");
        map.put("Whose  have I been beating ", "मैं किसकी पिटाई कर रहा हूँ ");
        map.put("Whose  have I been becoming ", "मैं किसका बन रहा हूँ ");
        map.put("Whose  have I been begging ", "मैं किसकी भीख माँग रहा हूँ ");
        map.put("Whose  have I been beginning ", "मैं किसकी शुरुआत कर रहा हूँ ");
        map.put("Whose  have I been binding ", "मैं किसका बाध्यकारी रहा हूँ ");
        map.put("Whose  have I been biting ", "मैं किसका काट रहा हूँ ");
        map.put("Whose  have I been blessing ", "मैं किसका आशीष रहा हूँ ");
        map.put("Whose  have I been blowing ", "मैं किसका उड़ा रहा हूँ ");
        map.put("Whose  have I been breaking ", "मैं किसका तोड़ रहा हूँ ");
        map.put("Whose  have I been bringing ", "मैं किसका ला रहा हूँ ");
        map.put("Whose  have I been building ", "मैं किसका निर्माण कर रहा हूँ ");
        map.put("Whose  have I been burning ", "मैं किसका जल रहा हूँ ");
        map.put("Whose  have I been buying ", "मैं किसका खरीद रहा हूँ ");
        map.put("Whose  have I been calling ", "मैं किसका फोन कर रहा हूं ");
        map.put("Whose  have I been carrying ", "मैं किसका ले जा रहा हूँ ");
        map.put("Whose  have I been catching ", "मैं किसका पकड़ रहा हूँ ");
        map.put("Whose  have I been cheating ", "मैं किसके साथ धोखा दे रहा हूँ ");
        map.put("Whose  have I been choosing ", "मैं किसका चयन कर रहा हूं ");
        map.put("Whose  have I been cleaning ", "मैं किसकी सफाई कर रहा हूँ ");
        map.put("Whose  have I been climbing ", "मैं किसका चढ़ रहा हूँ ");
        map.put("Whose  have I been closing ", "मैं किसका बंद कर रहा हूँ ");
        map.put("Whose  have I been coming ", "मैं किसका आ रहा हूँ ");
        map.put("Whose  have I been cooking ", "मैं किसका खाना बना रहा हूँ ");
        map.put("Whose  have I been creeping ", "मैं किसका रेंग रहा हूँ ");
        map.put("Whose  have I been crying ", "मैं किसका रो रहा हूँ ");
        map.put("Whose  have I been cutting ", "मैं किसका काट रहा हूँ ");
        map.put("Whose  have I been dancing ", "मैं किसका नाच रहा हूँ ");
        map.put("Whose  have I been dealing ", "मैं किसका काम कर रहा हूं ");
        map.put("Whose  have I been dying ", "मैं किसका मर रहा हूँ ");
        map.put("Whose  have I been digging ", "मैं किसकी खुदाई कर रहा हूँ ");
        map.put("Whose  have I been doing ", "मैं किसका कर रहा हूँ ");
        map.put("Whose  have I been drawing ", "मैं किसका चित्र बना रहा हूँ ");
        map.put("Whose  have I been drinking ", "मैं किसका पी रहा हूँ ");
        map.put("Whose  have I been driving ", "मैं किसका गाड़ी चला रहा हूँ ");
        map.put("Whose  have I been dropping ", "मैं किसका छोड़ रहा हूँ ");
        map.put("Whose  have I been drying ", "मैं किसका सुखा रहा हूँ ");
        map.put("Whose  have I been eating ", "मैं किसका खा रहा हूँ ");
        map.put("Whose  have I been electing ", "मैं किसका चुनाव कर रहा हूँ ");
        map.put("Whose  have I been entering ", "मैं किसका प्रवेश कर रहा हूँ ");
        map.put("Whose  have I been falling ", "मैं किसका गिर रहा हूँ ");
        map.put("Whose  have I been feeding ", "मैं किसका खिला रहा हूँ ");
        map.put("Whose  have I been feeling ", "मैं किसका महसूस कर रहा हूँ ");
        map.put("Whose  have I been fighting ", "मैं किससे लड़ रहा हूँ ");
        map.put("Whose  have I been finding ", "मुझे किसका मिल रहा है ");
        map.put("Whose  have I been fleeing ", "मैं किसका भाग रहा हूँ ");
        map.put("Whose  have I been flying ", "मैं किसका उड़ रहा हूँ ");
        map.put("Whose  have I been forgetting ", "मैं किसका भूल रहा हूँ ");
        map.put("Whose  have I been frying ", "मैं किसका फ्राइंग कर रहा हूँ ");
        map.put("Whose  have I been getting ", "मुझे किसका मिल रहा है ");
        map.put("Whose  have I been giving ", "मैं किसका दे रहा हूँ ");
        map.put("Whose  have I been going ", "मैं किसका जा रहा हूँ ");
        map.put("Whose  have I been growing ", "मैं किसका बढ़ रहा हूँ ");
        map.put("Whose  have I been hanging ", "मैं किसका लटक रहा हूँ ");
        map.put("Whose  have I been hearing ", "मैं किसका सुन रहा हूँ ");
        map.put("Whose  have I been helping ", "मैं किसकी मदद कर रहा हूँ ");
        map.put("Whose  have I been hiding ", "मैं किसका छिपा रहा हूँ ");
        map.put("Whose  have I been hitting ", "मैं किसका मार रहा हूँ ");
        map.put("Whose  have I been holding ", "मैं किसका पकड़ रहा हूँ ");
        map.put("Whose  have I been hoping ", "मैं किसकी उम्मीद कर रहा था ");
        map.put("Whose  have I been hurting ", "किसका मैं चोट पहुँचा रहा हूँ ");
        map.put("Whose  have I been jumping ", "मैं किसका कूद रहा हूँ ");
        map.put("Whose  have I been keeping ", "मैं किसका रख रहा हूँ ");
        map.put("Whose  have I been killing ", "मैं किसका मार रहा हूँ ");
        map.put("Whose  have I been knowing ", "मैं किसका जान रहा हूँ ");
        map.put("Whose  have I been laughing ", "मैं किसके हँस रहा हूँ ");
        map.put("Whose  have I been leading ", "मैं किसका नेतृत्व कर रहा हूं ");
        map.put("Whose  have I been leaping ", "मैं किसकी छलांग लगा रहा हूँ ");
        map.put("Whose  have I been learning ", "मैं किसका सीख रहा हूँ ");
        map.put("Whose  have I been leaving ", "मैं किसका जा रहा हूँ ");
        map.put("Whose  have I been lending ", "मैं किसका उधार दे रहा हूँ ");
        map.put("Whose  have I been living ", "मैं किसका जी रहा हूँ ");
        map.put("Whose  have I been looking ", "मैं किसका देख रहा हूँ ");
        map.put("Whose  have I been losing ", "मैं किसका हार रहा हूँ ");
        map.put("Whose  have I been loving ", "मैं किससे प्यार कर रहा हूँ ");
        map.put("Whose  have I been making ", "मैं किसका बना रहा हूँ ");
        map.put("Whose  have I been marrying ", "मैं किसकी शादी कर रहा हूँ ");
        map.put("Whose  have I been meeting ", "मैं किससे मिल रहा हूँ ");
        map.put("Whose  have I been mistaking ", "मैं किसकी गलती कर रहा हूँ ");
        map.put("Whose  have I been opening ", "मैं किसका खोल रहा हूँ ");
        map.put("Whose  have I been paying ", "मैं किसका भुगतान कर रहा हूं ");
        map.put("Whose  have I been playing ", "मैं किसका खेल रहा हूँ ");
        map.put("Whose  have I been putting ", "मैं किसका लगा रहा हूँ ");
        map.put("Whose  have I been quarrelling ", "मैं किसका झगड़ा कर रहा हूँ ");
        map.put("Whose  have I been raining ", "किसकी बारिश हो रही है ");
        map.put("Whose  have I been reaching ", "मैं किसके पास पहुँच रहा हूँ ");
        map.put("Whose  have I been reading ", "मैं किसका पढ़ रहा हूँ ");
        map.put("Whose  have I been remembering ", "मुझे किसका याद आ रहा है ");
        map.put("Whose  have I been riding ", "मैं किसकी सवारी कर रहा हूँ ");
        map.put("Whose  have I been ringing ", "मैं किसका बज रहा हूँ ");
        map.put("Whose  have I been rising ", "मैं किसका उठ रहा हूँ ");
        map.put("Whose  have I been running ", "मैं किसका भाग रहा हूँ ");
        map.put("Whose  have I been saying ", "मैं किसका कह रहा हूँ ");
        map.put("Whose  have I been seeing ", "मैं किसका देख रहा हूँ ");
        map.put("Whose  have I been selling ", "मैं किसका बेच रहा हूँ ");
        map.put("Whose  have I been sending ", "मैं किसका भेज रहा हूँ ");
        map.put("Whose  have I been shaking ", "मैं किसका हिला रहा हूँ ");
        map.put("Whose  have I been shining ", "मैं किसका चमक रहा हूँ ");
        map.put("Whose  have I been shooting ", "मैं किसकी शूटिंग कर रहा हूँ ");
        map.put("Whose  have I been showing ", "मैं किसका दिखा रहा हूँ ");
        map.put("Whose  have I been sleeping ", "मैं किसका सो रहा था ");
        map.put("Whose  have I been standing ", "मैं किसका खड़ा रहा हूँ ");
        map.put("Whose  have I been stealing ", "मैं किसकी चोरी कर रहा हूँ ");
        map.put("Whose  have I been throwing ", "मैं किसका फेंक रहा हूँ ");

        return map;
    }
    static Map<String,String> Five(){
        HashMap<String,String>map = new HashMap<>();
        map.put("Whose  did I  abuse ", "मैंने किसके साथ गाली दी ");
        map.put("Whose  did I  advise", "मैंने किसकी सलाह दी");
        map.put("Whose  did I  answer ", "मैंने किसका जवाब दिया ");
        map.put("Whose  did I  arise ", "मैं किसका उठ गया ");
        map.put("Whose  did I  arrive ", "मैं किसके पास आया ");
        map.put("Whose  did I  ask ", "मैंने किससे पूछा था ");
        map.put("Whose  did I  awake ", "मैं किसका जाग गया ");

        map.put("Whose  did I  beat ", "मैंने किसका हराया ");
        map.put("Whose  did I  become ", "मैं किसका बन गया ");
        map.put("Whose  did I  beg ", "मैंने किसकी भीख माँगी ");
        map.put("Whose  did I  begin ", "मैंने किसकी शुरुआत की ");
        map.put("Whose  did I  bind ", "मैंने किसका बाँध किया ");
        map.put("Whose  did I  bite", "मैंने किसका काट लिया");
        map.put("Whose  did I  bless", "मैंने किसका आशीर्वाद दिया");
        map.put("Whose  did I  blow ", "मैंने किसका उड़ाया ");
        map.put("Whose  did I  break ", "मैंने किसका तोड़ा ");
        map.put("Whose  did I  bring ", "मैं किसका लाया था ");
        map.put("Whose  did I  build ", "मैंने किसका निर्माण किया ");
        map.put("Whose  did I  burn ", "मैंने किसका जलाया था ");
        map.put("Whose  did I  buy ", "मैंने किसका खरीदा ");
        map.put("Whose  did I  call ", "मैंने किसका फोन किया ");
        map.put("Whose  did I  carry ", "मैं किसका ले गया ");
        map.put("Whose  did I  catch ", "मैंने किसका पकड़ लिया था ");
        map.put("Whose  did I  cheat ", "मैंने किसके साथ धोखा दिया ");
        map.put("Whose  did I  choose ", "मैंने किसका चयन किया ");
        map.put("Whose  did I  clean ", "मैंने किसकी सफाई की ");
        map.put("Whose  did I  climb  ", "मैं किसका चढ़ गया  ");
        map.put("Whose  did I  close ", "मैंने किसका बंद किया ");
        map.put("Whose  did I  come ", "मैं किसका आया ");
        map.put("Whose  did I  cook ", "मैंने किसका खाना बनाया ");
        map.put("Whose  did I  creep ", "मैं किसका रेंगना था ");
        map.put("Whose  did I  cut ", "मैंने किसका काटा ");
        map.put("Whose  did I  dance ", "मैंने किसका नृत्य किया ");
        map.put("Whose  did I  deal ", "मैंने किसका सौदा किया ");
        map.put("Whose  did I  die ", "मैं किसका मर गया ");
        map.put("Whose  did I  dig ", "मैंने किसका खोदा था ");
        map.put("Whose  did I  draw ", "मैंने किसका ड्रा किया ");
        map.put("Whose  did I  drive ", "मैंने किसका ड्राइव किया था ");
        map.put("Whose  did I  drop ", "मैंने किसका छोड़ा था ");
        map.put("Whose  did I  dry ", "मैंने किसका सुखाया ");
        map.put("Whose  did I  eat ", "मैंने किसका खाया ");
        map.put("Whose  did I  elect", "मैंने किसका चुनाव किया");
        map.put("Whose  did I  enter ", "मैंने किसका प्रवेश किया ");
        map.put("Whose  did I  fall ", "मैं किसका गिर गया ");
        map.put("Whose  did I  feed ", "मैंने किसका खाना खिलाया था ");
        map.put("Whose  did I  feel  ", "मुझे किसका महसूस हुआ  ");
        map.put("Whose  did I  fight ", "मैंने किसकी लड़ाई लड़ी ");
        map.put("Whose  did I  find ", "मुझे किसका मिला ");
        map.put("Whose  did I  flee ", "मैं किसका भाग गया ");
        map.put("Whose  did I  fly  ", "मैंने किसकी उड़ान भरी  ");
        map.put("Whose  did I  fry ", "मैंने किसका फ्राई किया ");
        map.put("Whose  did I  get  ", "मुझे किसका मिला  ");
        map.put("Whose  did I  give ", "मैंने किसका दिया ");
        map.put("Whose  did I  go ", "मैं किसका गया ");
        map.put("Whose  did I  grow", "मैं किसका उगाया था");
        map.put("Whose  did I  hang ", "मैंने किसका लटका दिया ");
        map.put("Whose  did I  hear ", "मैंने किसका सुना ");
        map.put("Whose  did I  help ", "मैंने किसकी मदद की ");
        map.put("Whose  did I  hide ", "मैंने किसका छिपाया था ");
        map.put("Whose  did I  hit ", "मैंने किसका मारा ");
        map.put("Whose  did I  hold ", "मैंने किसके पास रखा था ");
        map.put("Whose  did I  hope ", "मुझे किसकी उम्मीद थी ");
        map.put("Whose  did I  hurt ", "मैंने किसकी चोट पहुंचाई ");
        map.put("Whose  did I  jump ", "मैं किसका कूदता था ");
        map.put("Whose  did I  keep ", "मैंने किसका रखा ");
        map.put("Whose  did I  kill ", "मैंने किसकी हत्या की ");
        map.put("Whose  did I  know ", "मुझे किसका पता था ");
        map.put("Whose  did I  laugh ", "मैं किसका हँसा था ");
        map.put("Whose  did I  lead ", "मैंने किसका नेतृत्व किया ");
        map.put("Whose  did I  leap ", "मैंने किसकी छलांग लगाई ");
        map.put("Whose  did I  learn ", "मैंने किसका सीखा ");
        map.put("Whose  did I  leave ", "मैंने किसका छोड़ा ");
        map.put("Whose  did I  live ", "मैं किसका रहता था ");
        map.put("Whose  did I  look ", "मैंने किसका देखा ");
        map.put("Whose  did I  lose ", "मैंने किसका हारा ");
        map.put("Whose  did I  love ", "मुझे किससे प्यार था ");
        map.put("Whose  did I  make ", "मैंने किसका बनाया ");
        map.put("Whose  did I  marry ", "मैंने किससे शादी की ");
        map.put("Whose  did I  meet ", "मैं किससे मिला था ");
        map.put("Whose  did I  mistake ", "मैंने किसकी गलती की ");
        map.put("Whose  did I  open ", "मैंने किसका खोला था ");
        map.put("Whose  did I  pay  ", "मैंने किसका भुगतान किया  ");
        map.put("Whose  did I  play ", "मैं किसका खेलता था ");
        map.put("Whose  did I  put ", "मैंने किसका रखा था ");
        map.put("Whose  did I  quarrel ", "मैंने किसका झगड़ा किया ");
        map.put("Whose  did I  rain ", "मैंने किसकी बारिश की ");
        map.put("Whose  did I  reach ", "मैं किसके पास पहुँचा था ");
        map.put("Whose  did I  read", "मैंने किसका पढ़ा");
        map.put("Whose  did I  remember  ", "मुझे किसका याद था  ");
        map.put("Whose  did I  ride ", "मैंने किसकी सवारी की थी ");
        map.put("Whose  did I  ring ", "मैंने किसका रिंग किया था ");
        map.put("Whose  did I  rise  ", "मैं किसका उठ गया  ");
        map.put("Whose  did I  say ", "मैंने किसका कहा ");
        map.put("Whose  did I  see ", "मैंने किसका देखा ");
        map.put("Whose  did I  sell ", "मैंने किसका बेचा ");
        map.put("Whose  did I  send ", "मैंने किसका भेजा था ");
        map.put("Whose  did I  shake ", "मैंने किसका हिला दिया ");
        map.put("Whose  did I  shine ", "मैं किसका चमक रहा था ");
        map.put("Whose  did I  shoot ", "मैंने किसकी शूटिंग की ");
        map.put("Whose  did I  show ", "मैंने किसका दिखाया ");
        map.put("Whose  did I  spoil", "मैंने किसका बिगाड़ा");

        return map;
    }
    static Map<String,String> Six(){
        HashMap<String,String>map = new HashMap<>();
        map.put("Whose  was I  abusing ", "मैं किसका गाली दे रहा था ");
        map.put("Whose  was I  advising ", "मैं किसकी सलाह दे रहा था ");
        map.put("Whose  was I  answering ", "मैं किसका जवाब दे रहा था ");
        map.put("Whose  was I  arising ", "मैं किसका उठ रहा था ");
        map.put("Whose  was I  arriving ", "मैं किसका आ रहा था ");
        map.put("Whose  was I  asking ", "मैं किससे पूछ रहा था ");
        map.put("Whose  was I  awaking ", "मैं किसका जाग रहा था ");
        map.put("Whose  was I  undefined", "मैं किसका अपरिभाषित था");
        map.put("Whose  was I  bearing ", "मैं किसका असर कर रहा था ");
        map.put("Whose  was I  beating ", "मैं किसकी पिटाई कर रहा था ");
        map.put("Whose  was I  becoming ", "मैं किसका बन रहा था ");
        map.put("Whose  was I  begging ", "मैं किसकी भीख मांग रहा था ");
        map.put("Whose  was I  beginning ", "मैं किसका शुरू कर रहा था ");
        map.put("Whose  was I  binding ", "मैं किसका बाध्यकारी था ");
        map.put("Whose  was I  biting ", "मैं किसका काट रहा था ");
        map.put("Whose  was I  blessing ", "मैं आशीष किसका था ");
        map.put("Whose  was I  blowing ", "मैं किसका उड़ रहा था ");
        map.put("Whose  was I  breaking ", "मैं किसका तोड़ रहा था ");
        map.put("Whose  was I  bringing ", "मैं किसका ला रहा था ");
        map.put("Whose  was I  building ", "मैं किसका निर्माण कर रहा था ");
        map.put("Whose  was I  burning ", "मैं किसका जल रहा था ");
        map.put("Whose  was I  buying ", "मैं किसका खरीद रहा था ");
        map.put("Whose  was I  calling ", "मैं किसका फोन कर रहा था ");
        map.put("Whose  was I  carrying ", "मैं किसका ले जा रहा था ");
        map.put("Whose  was I  catching ", "मैं किसका पकड़ रहा था ");
        map.put("Whose  was I  cheating ", "मैं किसका धोखा दे रहा था ");
        map.put("Whose  was I  choosing ", "मैं किसका चयन कर रहा था ");
        map.put("Whose  was I  cleaning ", "मैं किसका सफाई कर रहा था ");
        map.put("Whose  was I  climbing ", "मैं किसका चढ़ रहा था ");
        map.put("Whose  was I  closing ", "मैं किसका बंद कर रहा था ");
        map.put("Whose  was I  coming ", "मैं किसका आ रहा था ");
        map.put("Whose  was I  cooking ", "मैं किसका खाना बना रहा था ");
        map.put("Whose  was I  creeping ", "मैं किसका रेंग रहा था ");
        map.put("Whose  was I  crying ", "मैं किसका रो रहा था ");
        map.put("Whose  was I  cutting ", "मैं किसका काट रहा था ");
        map.put("Whose  was I  dancing ", "मैं किसका नाच रहा था ");
        map.put("Whose  was I  dealing ", "मैं किसका काम कर रहा था ");
        map.put("Whose  was I  dying ", "मैं किसका मर रहा था ");
        map.put("Whose  was I  digging ", "मैं किसकी खुदाई कर रहा था ");
        map.put("Whose  was I  drawing ", "मैं किसका चित्रण कर रहा था ");
        map.put("Whose  was I  drinking ", "मैं किसका पी रहा था ");
        map.put("Whose  was I  driving ", "मैं किसका गाड़ी चला रहा था ");
        map.put("Whose  was I  dropping ", "मैं किसका छोड़ रहा था ");
        map.put("Whose  was I  drying ", "मैं किसका सुखा रहा था ");
        map.put("Whose  was I  eating ", "मैं किसका खा रहा था ");
        map.put("Whose  was I  electing ", "मैं किसका चुनाव कर रहा था ");
        map.put("Whose  was I  entering ", "मैं किसका प्रवेश कर रहा था ");
        map.put("Whose  was I  falling ", "मैं किसका गिर रहा था ");
        map.put("Whose  was I  feeding ", "मैं किसका खिला रहा था ");
        map.put("Whose  was I  feeling ", "मैं किसका महसूस कर रहा था ");
        map.put("Whose  was I  fighting ", "मैं किससे लड़ रहा था ");
        map.put("Whose  was I  finding ", "मैं किसका खोज रहा था ");
        map.put("Whose  was I  fleeing ", "मैं किससे भाग रहा था ");
        map.put("Whose  was I  flying ", "मैं किसका उड़ रहा था ");
        map.put("Whose  was I  forgetting ", "मैं किसका भूल रहा था ");
        map.put("Whose  was I  frying ", "मैं किसका फ्राइंग कर रहा था ");
        map.put("Whose  was I  getting ", "मुझे किसका मिल रहा था ");
        map.put("Whose  was I  giving ", "मैं किसका दे रहा था ");
        map.put("Whose  was I  going ", "मैं किसका जा रहा था ");
        map.put("Whose  was I  growing ", "मैं किसका बढ़ रहा था ");
        map.put("Whose  was I  hanging ", "मैं किसका लटक रहा था ");
        map.put("Whose  was I  hearing ", "मैं किसका सुन रहा था ");
        map.put("Whose  was I  helping ", "मैं किसका मदद कर रहा था ");
        map.put("Whose  was I  hiding ", "मैं किसका छिपा रहा था ");
        map.put("Whose  was I  hitting ", "मैं किसका मार रहा था ");
        map.put("Whose  was I  holding ", "मैं किसका पकड़ रहा था ");
        map.put("Whose  was I  hoping ", "मैं किसका उम्मीद कर रहा था ");
        map.put("Whose  was I  hurting ", "मैं किसका दर्द कर रहा था ");
        map.put("Whose  was I  jumping ", "मैं किसका कूद रहा था ");
        map.put("Whose  was I  keeping ", "मैं किसका रख रहा था ");
        map.put("Whose  was I  killing ", "मैं किसका मार रहा था ");
        map.put("Whose  was I  knowing ", "मैं किसका जान रहा था ");
        map.put("Whose  was I  laughing ", "मैं किसकी हँस रहा था ");
        map.put("Whose  was I  leading ", "मैं किसका नेतृत्व कर रहा था ");
        map.put("Whose  was I  leaping ", "मैं किसकी छलांग लगा रहा था ");
        map.put("Whose  was I  learning ", "मैं किसका सीख रहा था ");
        map.put("Whose  was I  leaving ", "मैं किसका जा रहा था ");
        map.put("Whose  was I  lending ", "मैं किसका उधार दे रहा था ");
        map.put("Whose  was I  living ", "मैं किसका रह रहा था ");
        map.put("Whose  was I  looking ", "मैं किसका देख रहा था ");
        map.put("Whose  was I  losing ", "मैं किसका हार रहा था ");
        map.put("Whose  was I  loving ", "मैं किसका प्यार कर रहा था ");
        map.put("Whose  was I  making ", "मैं किसका बना रहा था ");
        map.put("Whose  was I  marrying ", "मैं किससे शादी कर रहा था ");
        map.put("Whose  was I  meeting ", "मैं किससे मिल रहा था ");
        map.put("Whose  was I  mistaking ", "मैं किसकी गलती कर रहा था ");
        map.put("Whose  was I  opening ", "मैं किसका खोल रहा था ");
        map.put("Whose  was I  paying ", "मैं किसका भुगतान कर रहा था ");
        map.put("Whose  was I  playing ", "मैं किसका खेल रहा था ");
        map.put("Whose  was I  putting ", "मैं किसका लगा रहा था ");
        map.put("Whose  was I  quarrelling ", "मैं किसका झगड़ा कर रहा था ");
        map.put("Whose  was I  raining ", "मैं किसकी बारिश कर रहा था ");
        map.put("Whose  was I  reaching ", "मैं किसतक पहुँच रहा था ");
        map.put("Whose  was I  reading ", "मैं किसका पढ़ रहा था ");
        map.put("Whose  was I  remembering ", "मैं किसका याद कर रहा था ");
        map.put("Whose  was I  riding ", "मैं किसका सवारी कर रहा था ");
        map.put("Whose  was I  ringing ", "मैं किसका बज रहा था ");
        map.put("Whose  was I  rising ", "मैं किसका उठ रहा था ");
        map.put("Whose  was I  running ", "मैं किसका भाग रहा था ");
        map.put("Whose  was I  saying ", "मैं किसका कह रहा था ");
        map.put("Whose  was I  seeing ", "मैं किसका देख रहा था ");
        map.put("Whose  was I  selling ", "मैं किसका बेच रहा था ");
        map.put("Whose  was I  sending ", "मैं किसका भेज रहा था ");
        map.put("Whose  was I  shaking ", "मैं किसका हिला रहा था ");
        map.put("Whose  was I  shining ", "मैं किसका चमक रहा था ");
        map.put("Whose  was I  shooting ", "मैं किसका शूटिंग कर रहा था ");
        map.put("Whose  was I  showing ", "मैं किसका दिखा रहा था ");

        return map;
    }
    static Map<String,String> Seven(){
        HashMap<String,String>map = new HashMap<>();
        map.put("Whose  had I  abused ", "मैंने किसके साथ गाली दी थी ");
        map.put("Whose  had I  advised ", "मैंने किसकी सलाह दी थी ");
        map.put("Whose  had I  answered ", "मैंने किसका उत्तर दिया था ");
        map.put("Whose  had I  arisen ", "मैं किसका पैदा हुआ था ");
        map.put("Whose  had I  arrived ", "मैं किसके पास आया था ");
        map.put("Whose  had I  asked ", "मैंने किससे पूछा था ");
        map.put("Whose  had I  awoken ", "मैं किसका जाग गया था ");
        map.put("Whose  had I  undefined", "किसका मैंने अपरिभाषित किया था");
        map.put("Whose  had I  borne ", "मैंने किसका जन्म लिया था ");
        map.put("Whose  had I  beaten ", "मैंने किसका पीटा था ");
        map.put("Whose  had I  become ", "मैं किसका बन गया था ");
        map.put("Whose  had I  begged ", "मैंने किसकी भीख मांगी थी ");
        map.put("Whose  had I  begun ", "मैंने किसकी शुरुआत की थी ");
        map.put("Whose  had I  bound ", "मैंने किसका बाउंड किया था ");
        map.put("Whose  had I  bitten ", "मैंने किसका काटा था ");
        map.put("Whose  had I  blessed ", "मैंने किसका आशीर्वाद दिया था ");
        map.put("Whose  had I  blown ", "मैंने किसका उड़ा दिया था ");
        map.put("Whose  had I  broken ", "मैंने किसका तोड़ा था ");
        map.put("Whose  had I  brought ", "मैं किसके लिए लाया था ");
        map.put("Whose  had I  built ", "मैंने किसका बनाया था ");
        map.put("Whose  had I  burnt ", "मैंने किसका जलाया था ");
        map.put("Whose  had I  bought ", "मैंने किसका खरीदा था ");
        map.put("Whose  had I  called ", "मैंने किसका फोन किया था ");
        map.put("Whose  had I  carried ", "मैंने किसका किया था ");
        map.put("Whose  had I  caught ", "मैंने किसका पकड़ा था ");
        map.put("Whose  had I  cheated ", "मैंने किसके साथ धोखा दिया था ");
        map.put("Whose  had I  chosen ", "मैंने किसका चुना था ");
        map.put("Whose  had I  cleaned ", "मैंने किसकी सफाई की थी ");
        map.put("Whose  had I  climbed ", "मैं किसके ऊपर चढ़ गया था ");
        map.put("Whose  had I  closed ", "मैंने किसका बंद किया था ");
        map.put("Whose  had I  come ", "मैं किसके पास आया था ");
        map.put("Whose  had I  cooked ", "मैंने किसका खाना बनाया था ");
        map.put("Whose  had I  crept ", "किसका था मैंने क्रेप किया था ");
        map.put("Whose  had I  cried ", "मैं किसका रोया था ");
        map.put("Whose  had I  cut ", "मैंने किसका काटा था ");
        map.put("Whose  had I  danced ", "मैंने किसका नृत्य किया था ");
        map.put("Whose  had I  dealt ", "मैंने किसका निपटा था ");
        map.put("Whose  had I  died ", "मैं किसका मर गया था ");
        map.put("Whose  had I  dug ", "मैंने किसका खोदा था ");
        map.put("Whose  had I  drawn ", "मैंने किसका खींचा था ");
        map.put("Whose  had I  drunk ", "मैंने किसका पिया था ");
        map.put("Whose  had I  driven ", "मैंने किसका चलाया था ");
        map.put("Whose  had I  dropped ", "मैंने किसका गिरा दिया था ");
        map.put("Whose  had I  dried ", "मैंने किसका सुखाया था ");
        map.put("Whose  had I  eaten ", "मैंने किसका खाया था ");
        map.put("Whose  had I  elected ", "मैंने किसका चुना था ");
        map.put("Whose  had I  entered ", "मैंने किसका प्रवेश किया था ");
        map.put("Whose  had I  fallen ", "मैं किसका गिर गया था ");
        map.put("Whose  had I  fed ", "मैंने किसका खिलाया था ");
        map.put("Whose  had I  felt ", "मैंने किसका महसूस किया था ");
        map.put("Whose  had I  fought ", "मैंने किसकी लड़ाई लड़ी थी ");
        map.put("Whose  had I  found ", "मुझे किसका मिला था ");
        map.put("Whose  had I  fled ", "मैं किसका भाग गया था ");
        map.put("Whose  had I  flown ", "मैंने किसका उड़ाया था ");
        map.put("Whose  had I  forgotten ", "मैं किसका भूल गया था ");
        map.put("Whose  had I  fried ", "मैंने किसके तले किया था ");
        map.put("Whose  had I  got ", "मुझे किसका मिला था ");
        map.put("Whose  had I  given ", "मैंने किसका दिया था ");
        map.put("Whose  had I  gone ", "मैं किसके पास गया था ");
        map.put("Whose  had I  grown ", "मैं किसका उगाया था ");
        map.put("Whose  had I  hanged ", "मैंने किसको फांसी दी थी ");
        map.put("Whose  had I  hung ", "मैंने किसके पास लटका दिया था ");
        map.put("Whose  had I  heard ", "मैंने किसके बारे में सुना था ");
        map.put("Whose  had I  helped ", "मैंने किसकी मदद की थी ");
        map.put("Whose  had I  hidden ", "मैंने किसका छिपाया था ");
        map.put("Whose  had I  hit ", "मैंने किसका मारा था ");
        map.put("Whose  had I  held ", "मैंने किसके पास रखा था ");
        map.put("Whose  had I  hoped ", "मुझे किसकी उम्मीद थी ");
        map.put("Whose  had I  hurt ", "मुझे किसकी चोट लगी थी ");
        map.put("Whose  had I  jumped ", "मैं किसके पास कूद गया था ");
        map.put("Whose  had I  kept ", "मैंने किसके पास रखा था ");
        map.put("Whose  had I  killed ", "मैंने किसका मारा था ");
        map.put("Whose  had I  known ", "मुझे किसका पता था ");
        map.put("Whose  had I  laughed ", "मैं किसका हँसा था ");
        map.put("Whose  had I  led ", "मैंने किसका नेतृत्व किया था ");
        map.put("Whose  had I  leapt ", "मैंने किसके पास छलांग लगाई थी ");
        map.put("Whose  had I  learnt ", "मैंने किसका सीखा था ");
        map.put("Whose  had I  left ", "मैंने किसके पास छोड़ा था ");
        map.put("Whose  had I  lent ", "मैंने किसका उधार दिया था ");
        map.put("Whose  had I  lived ", "मैं किसके पास रहता था ");
        map.put("Whose  had I  looked ", "मैंने किसका देखा था ");
        map.put("Whose  had I  lost ", "मैंने किसका खो दिया था ");
        map.put("Whose  had I  loved ", "मैं किसका प्यार करता था ");
        map.put("Whose  had I  made ", "मैंने किसका बनाया था ");
        map.put("Whose  had I  married ", "मैंने किसकी शादी की थी ");
        map.put("Whose  had I  met ", "मैं किससे मिला था ");
        map.put("Whose  had I  mistaken ", "मैंने किसकी गलती की थी ");
        map.put("Whose  had I  opened ", "मैंने किसका खोला था ");
        map.put("Whose  had I  paid ", "मैंने किसका भुगतान किया था ");
        map.put("Whose  had I  played ", "मैंने किसका खेला था ");
        map.put("Whose  had I  put ", "मैंने किसके पास रखा था ");
        map.put("Whose  had I  quarrelled ", "मैंने किसके साथ झगड़ा किया था ");
        map.put("Whose  had I  rained ", "मैंने किसकी बारिश की थी ");
        map.put("Whose  had I  reached ", "मैं किसके पास पहुँचा था ");
        map.put("Whose  had I  read ", "मैंने किसका पढ़ा था ");
        map.put("Whose  had I  remembered ", "मुझे किसका याद था ");
        map.put("Whose  had I  ridden ", "मैंने किसकी सवारी की थी ");
        map.put("Whose  had I  rung ", "मैंने किसका बजाया था ");
        map.put("Whose  had I  risen ", "मैं किसका उठ गया था ");
        map.put("Whose  had I  run ", "मैं किसका दौड़ा था ");
        map.put("Whose  had I  said ", "मैंने किसका कहा था ");
        map.put("Whose  had I  seen ", "मैंने किसका देखा था ");
        map.put("Whose  had I  sold ", "मैंने किसका बेचा था ");
        map.put("Whose  had I  sent ", "मैंने किसका भेजा था ");
        map.put("Whose  had I  shaken ", "मैंने किसका हिलाया था ");
        map.put("Whose  had I  shone ", "मैं किसके पास चमक गया था ");
        map.put("Whose  had I  shot ", "मैंने किसका शॉट किया था ");
        map.put("Whose  had I  shown ", "मैंने किसका दिखाया था ");
        map.put("Whose  had I  written ", "मैंने किसका लिखा था ");

        return map;
    }
    static Map<String,String> Eight(){
        HashMap<String,String>map = new HashMap<>();
        map.put("Whose  had I been  abusing ", "मैं किसके साथ गाली दे रहा था ");
        map.put("Whose  had I been  advising ", "मैं किसकी सलाह दे रहा था ");
        map.put("Whose  had I been  answering ", "मैं किसका जवाब दे रहा था ");
        map.put("Whose  had I been  arising ", "मैं किसका उठ रहा था ");
        map.put("Whose  had I been  arriving ", "मैं किसके पास आ रहा था ");
        map.put("Whose  had I been  asking ", "मैं किसका पूछ रहा था ");
        map.put("Whose  had I been  awaking ", "मैं किसके जाग रहा था ");
        map.put("Whose  had I been  undefined", "किसका मैं अपरिभाषित हो गया था");
        map.put("Whose  had I been  bearing ", "मैं किसका असर कर रहा था ");
        map.put("Whose  had I been  beating ", "मैं किसकी पिटाई कर रहा था ");
        map.put("Whose  had I been  becoming ", "मैं किसका बन रहा था ");
        map.put("Whose  had I been  begging ", "मैं किसकी भीख मांग रहा था ");
        map.put("Whose  had I been  beginning ", "मैं किसकी शुरुआत कर रहा था ");
        map.put("Whose  had I been  binding ", "मैं किसका बंधन कर रहा था ");
        map.put("Whose  had I been  biting ", "मैं किसका काट रहा था ");
        map.put("Whose  had I been  blessing ", "मैं किसका आशीर्वाद दे रहा था ");
        map.put("Whose  had I been  blowing ", "मैं किसका उड़ रहा था ");
        map.put("Whose  had I been  breaking ", "मैं किसका तोड़ रहा था ");
        map.put("Whose  had I been  bringing ", "मैं किसका ला रहा था ");
        map.put("Whose  had I been  building ", "मैं किसका निर्माण कर रहा था ");
        map.put("Whose  had I been  burning ", "मैं किसका जल रहा था ");
        map.put("Whose  had I been  buying ", "मैं किसका खरीद रहा था ");
        map.put("Whose  had I been  calling ", "मैं किसका फोन कर रहा था ");
        map.put("Whose  had I been  carrying ", "मैं किसका ले जा रहा था ");
        map.put("Whose  had I been  catching ", "मैं किसका पकड़ रहा था ");
        map.put("Whose  had I been  cheating ", "मैं किसके साथ धोखा दे रहा था ");
        map.put("Whose  had I been  choosing ", "मैं किसका चयन कर रहा था ");
        map.put("Whose  had I been  cleaning ", "मैं किसकी सफाई कर रहा था ");
        map.put("Whose  had I been  climbing ", "मैं किसका चढ़ रहा था ");
        map.put("Whose  had I been  closing ", "मैं किसका बंद कर रहा था ");
        map.put("Whose  had I been  coming ", "मैं किसके पास आ रहा था ");
        map.put("Whose  had I been  cooking ", "मैं किसका खाना बना रहा था ");
        map.put("Whose  had I been  creeping ", "मैं किसका रेंग रहा था ");
        map.put("Whose  had I been  crying ", "मैं किसका रो रहा था ");
        map.put("Whose  had I been  cutting ", "मैं किसका काट रहा था ");
        map.put("Whose  had I been  dancing ", "मैं किसके नाच रहा था ");
        map.put("Whose  had I been  dealing ", "मैं किसका काम कर रहा था ");
        map.put("Whose  had I been  dying ", "मैं किसका मर रहा था ");
        map.put("Whose  had I been  digging ", "मैं किसकी खुदाई कर रहा था ");
        map.put("Whose  had I been  drawing ", "मैं किसका चित्र बना रहा था ");
        map.put("Whose  had I been  drinking ", "मैं किसका पी रहा था ");
        map.put("Whose  had I been  driving ", "मैं किसका गाड़ी चला रहा था ");
        map.put("Whose  had I been  dropping ", "मैं किसका छोड़ रहा था ");
        map.put("Whose  had I been  drying ", "मैं किसका सूख रहा था ");
        map.put("Whose  had I been  eating ", "मैं किसका खा रहा था ");
        map.put("Whose  had I been  electing ", "मैं किसका चुनाव कर रहा था ");
        map.put("Whose  had I been  entering ", "मैं किसका प्रवेश कर रहा था ");
        map.put("Whose  had I been  falling ", "मैं किसका गिर रहा था ");
        map.put("Whose  had I been  feeding ", "मैं किसका भोजन कर रहा था ");
        map.put("Whose  had I been  feeling ", "मैं किसका महसूस कर रहा था ");
        map.put("Whose  had I been  fighting ", "मैं किसका लड़ रहा था ");
        map.put("Whose  had I been  finding ", "मुझे किसका मिल रहा था ");
        map.put("Whose  had I been  fleeing ", "मैं किसका भाग रहा था ");
        map.put("Whose  had I been  flying ", "मैं किसका उड़ रहा था ");
        map.put("Whose  had I been  forgetting ", "मैं किसका भूल रहा था ");
        map.put("Whose  had I been  frying ", "मैं किसका तलने गया था ");
        map.put("Whose  had I been  getting ", "मुझे किसका मिल रहा था ");
        map.put("Whose  had I been  giving ", "मैं किसका दे रहा था ");
        map.put("Whose  had I been  going ", "मैं किसके पास जा रहा था ");
        map.put("Whose  had I been  growing ", "मैं किसका बढ़ रहा था ");
        map.put("Whose  had I been  hanging ", "मैं किसके पास लटक रहा था ");
        map.put("Whose  had I been  hearing ", "मैं किसका सुन रहा था ");
        map.put("Whose  had I been  helping ", "मैं किसकी मदद कर रहा था ");
        map.put("Whose  had I been  hiding ", "मैं किसका छिपा रहा था ");
        map.put("Whose  had I been  hitting ", "मैं किसका मार रहा था ");
        map.put("Whose  had I been  holding ", "मैं किसका पकड़ रहा था ");
        map.put("Whose  had I been  hoping ", "मैं किसकी उम्मीद कर रहा था ");
        map.put("Whose  had I been  hurting ", "मैं किसका दर्द कर रहा था ");
        map.put("Whose  had I been  jumping ", "मैं किसका कूद रहा था ");
        map.put("Whose  had I been  keeping ", "मैं किसका रख रहा था ");
        map.put("Whose  had I been  killing ", "मैं किसका मार रहा था ");
        map.put("Whose  had I been  knowing ", "मैं किसके बारे में जान रहा था ");
        map.put("Whose  had I been  laughing ", "मैं किसके हँस रहा था ");
        map.put("Whose  had I been  leading ", "मैं किसका नेतृत्व कर रहा था ");
        map.put("Whose  had I been  leaping ", "मैं किसकी छलांग लगा रहा था ");
        map.put("Whose  had I been  learning ", "मैं किसका सीख रहा था ");
        map.put("Whose  had I been  leaving ", "मैं किसका जा रहा था ");
        map.put("Whose  had I been  lending ", "मैं किसका उधार दे रहा था ");
        map.put("Whose  had I been  living ", "मैं किसके साथ रह रहा था ");
        map.put("Whose  had I been  looking ", "मैं किसका देख रहा था ");
        map.put("Whose  had I been  losing ", "मैं किसका हार रहा था ");
        map.put("Whose  had I been  loving ", "मैं किसका प्यार कर रहा था ");
        map.put("Whose  had I been  making ", "मैं किसका बना रहा था ");
        map.put("Whose  had I been  marrying ", "मैं किसकी शादी कर रहा था ");
        map.put("Whose  had I been  meeting ", "मैं किससे मिल रहा था ");
        map.put("Whose  had I been  mistaking ", "मैं किसकी गलती कर रहा था ");
        map.put("Whose  had I been  opening ", "मैं किसका खोल रहा था ");
        map.put("Whose  had I been  paying ", "मैं किसका भुगतान कर रहा था ");
        map.put("Whose  had I been  playing ", "मैं किसका खेल रहा था ");
        map.put("Whose  had I been  putting ", "मैं किसका लगा रहा था ");
        map.put("Whose  had I been  quarrelling ", "मैं किसका झगड़ा कर रहा था ");
        map.put("Whose  had I been  raining ", "मैं किसकी बारिश कर रहा था ");
        map.put("Whose  had I been  reaching ", "मैं किसके पास पहुँच रहा था ");
        map.put("Whose  had I been  reading ", "मैं किसका पढ़ रहा था ");
        map.put("Whose  had I been  remembering ", "मैं किसका याद कर रहा था ");
        map.put("Whose  had I been  riding ", "मैं किसकी सवारी कर रहा था ");
        map.put("Whose  had I been  ringing ", "मैं किसका बज रहा था ");
        map.put("Whose  had I been  rising ", "मैं किसका उठ रहा था ");
        map.put("Whose  had I been  running ", "मैं किसका भाग रहा था ");
        map.put("Whose  had I been  saying ", "मैं किसका कह रहा था ");
        map.put("Whose  had I been  seeing ", "मैं किसका देख रहा था ");
        map.put("Whose  had I been  selling ", "मैं किसका बेच रहा था ");
        map.put("Whose  had I been  sending ", "मैं किसका भेज रहा था ");
        map.put("Whose  had I been  shaking ", "मैं किसका हिल रहा था ");
        map.put("Whose  had I been  shining ", "मैं किसका चमक रहा था ");
        map.put("Whose  had I been  shooting ", "मैं किसकी शूटिंग कर रहा था ");
        map.put("Whose  had I been  showing ", "मैं किसका दिखा रहा था ");
        map.put("Whose  had I been  taking ", "मैं किसका ले रहा था ");

        return map;
    }
    static Map<String,String> Nine(){
        HashMap<String,String>map = new HashMap<>();
        map.put("Whose  will I abuse ", "मैं किसका गाली दूँगा ");
        map.put("Whose  will I advise", "मैं किसकी सलाह दूंगा");
        map.put("Whose  will I answer ", "मैं किसका जवाब दूँगा ");
        map.put("Whose  will I arise ", "मैं किसका उठूंगा ");
        map.put("Whose  will I arrive ", "मैं किसका आऊंगा ");
        map.put("Whose  will I ask ", "मैं किससे पूछूंगा ");
        map.put("Whose  will I awake ", "मैं किसका जाग जाऊंगा ");

        map.put("Whose  will I be undefined", "मैं किसका अपरिभाषित हो जाऊंगा");
        map.put("Whose  will I bear ", "मैं किसका सहन करूंगा ");
        map.put("Whose  will I beat ", "मैं किसको हराऊंगा ");
        map.put("Whose  will I become ", "मैं किसका बन जाऊंगा ");
        map.put("Whose  will I beg ", "मैं किसकी भीख मांगूँगा ");
        map.put("Whose  will I begin ", "मैं किससे शुरू करूंगा ");
        map.put("Whose  will I bind ", "मैं किससे बाँधूँगा ");
        map.put("Whose  will I bite", "मैं किसका काटूंगा");
        map.put("Whose  will I bless", "मैं किसका आशीर्वाद दूँगा");
        map.put("Whose  will I break ", "मैं किसका तोड़ूंगा ");
        map.put("Whose  will I bring ", "मैं किसका लाऊंगा ");
        map.put("Whose  will I build ", "मैं किसका निर्माण करूंगा ");
        map.put("Whose  will I burn ", "मैं किसका जलाऊंगा ");
        map.put("Whose  will I buy ", "मैं किसका खरीदूंगा ");
        map.put("Whose  will I call ", "मैं किससे फोन करूंगा ");
        map.put("Whose  will I carry ", "मैं किसका ले जाऊंगा ");
        map.put("Whose  will I catch ", "मैं किसको पकड़ूँगा ");
        map.put("Whose  will I cheat ", "मैं किसको धोखा दूंगा ");
        map.put("Whose  will I choose ", "मैं किसका चुनूंगा ");
        map.put("Whose  will I clean ", "मैं किसकी सफाई करूँगा ");
        map.put("Whose  will I climb  ", "मैं किसकी चढ़ाई करूंगा  ");
        map.put("Whose  will I close ", "मैं किसका बंद करूंगा ");
        map.put("Whose  will I come ", "मैं किसका आऊंगा ");
        map.put("Whose  will I cook ", "मैं किसका खाना बनाऊँगा ");
        map.put("Whose  will I creep ", "मैं किसका रेंगना चाहूँगा ");
        map.put("Whose  will I cry ", "मैं किसका रोऊंगा ");
        map.put("Whose  will I cut ", "मैं किसका काटूंगा ");
        map.put("Whose  will I dance ", "मैं किसका नृत्य करूँगा ");
        map.put("Whose  will I deal ", "मैं किसका सौदा करूंगा ");
        map.put("Whose  will I die ", "मैं किसकी मरूंगा ");
        map.put("Whose  will I dig ", "मैं किसकी खुदाई करूंगा ");
        map.put("Whose  will I draw ", "मैं किसका आकर्षित करूंगा ");
        map.put("Whose  will I drive ", "मैं किसकी ड्राइव करूँगा ");
        map.put("Whose  will I drop ", "मैं किसका छोड़ दूँगा ");
        map.put("Whose  will I dry ", "मैं किसका सुखाऊंगा ");
        map.put("Whose  will I eat ", "मैं किसका खाऊंगा ");
        map.put("Whose  will I elect", "मैं किसका चुनाव करूंगा");
        map.put("Whose  will I enter ", "मैं किसका प्रवेश करूंगा ");
        map.put("Whose  will I fall ", "मैं किसका गिरूंगा ");
        map.put("Whose  will I feed ", "मैं किसको खिलाऊंगा ");
        map.put("Whose  will I feel  ", "मैं किसका महसूस करूंगा  ");
        map.put("Whose  will I fight ", "मैं किससे लड़ूंगा ");
        map.put("Whose  will I find ", "मुझे किसका मिलेगा ");
        map.put("Whose  will I flee ", "मैं किससे भागेगा ");
        map.put("Whose  will I fly  ", "मैं किसका उड़ूंगा  ");
        map.put("Whose  will I forget ", "मैं किसको भूल जाऊंगा ");
        map.put("Whose  will I fry ", "मैं किसका भूनूंगा ");
        map.put("Whose  will I get  ", "मुझे किसका मिलेगा  ");
        map.put("Whose  will I give ", "मैं किसका दूंगा ");
        map.put("Whose  will I go ", "मैं किसका जाऊंगा ");
        map.put("Whose  will I grow", "मैं किसका उगाऊंगा");
        map.put("Whose  will I hang ", "मैं किसका लटकाऊंगा ");
        map.put("Whose  will I hear ", "मैं किसका सुनूंगा ");
        map.put("Whose  will I help ", "मैं किसकी मदद करूंगा ");
        map.put("Whose  will I hide ", "मैं किसका छिपाऊंगा ");
        map.put("Whose  will I hit ", "मैं किसका मारूंगा ");
        map.put("Whose  will I hold ", "मैं किसका रखूँगा ");
        map.put("Whose  will I hope ", "मैं किसकी उम्मीद करूंगा ");
        map.put("Whose  will I hurt ", "मैं किसकी चोट पहुंचाऊंगा ");
        map.put("Whose  will I jump ", "मैं किसकी कूदूँगा ");
        map.put("Whose  will I keep ", "मैं किसका रखूँगा ");
        map.put("Whose  will I kill ", "मैं किसका मारूंगा ");
        map.put("Whose  will I know ", "मुझे किसका पता चलेगा ");
        map.put("Whose  will I laugh ", "मैं किसका हंसूंगा ");
        map.put("Whose  will I lead ", "मैं किसका नेतृत्व करूंगा ");
        map.put("Whose  will I leap ", "मैं किसकी छलांग लगाऊंगा ");
        map.put("Whose  will I learn ", "मैं किसका सीखूंगा ");
        map.put("Whose  will I leave ", "मैं किसका छोड़ूँगा ");
        map.put("Whose  will I lend ", "मैं किसका उधार दूंगा ");
        map.put("Whose  will I live ", "मैं किसका रहूँगा ");
        map.put("Whose  will I look ", "मैं किसकी देखूँगा ");
        map.put("Whose  will I lose ", "मैं किसका हारूंगा ");
        map.put("Whose  will I make ", "मैं किसका बनाऊँगा ");
        map.put("Whose  will I marry ", "मैं किससे शादी करूँगा ");
        map.put("Whose  will I meet ", "मैं किससे मिलूंगा ");
        map.put("Whose  will I mistake ", "मैं किसकी गलती करूँगा ");
        map.put("Whose  will I open ", "मैं किसका खोलूंगा ");
        map.put("Whose  will I pay  ", "मैं किसका भुगतान करूंगा  ");
        map.put("Whose  will I play ", "मैं किसका खेलूंगा ");
        map.put("Whose  will I put ", "मैं किसका रखूंगा ");
        map.put("Whose  will I quarrel ", "मैं किसका झगड़ा करूंगा ");
        map.put("Whose  will I rain ", "मैं किसकी बारिश करूँगा ");
        map.put("Whose  will I reach ", "मैं किसतक पहुँचूँगा ");
        map.put("Whose  will I read", "मैं किसका पढ़ूँगा");
        map.put("Whose  will I remember  ", "मुझे किसका याद होगा  ");
        map.put("Whose  will I ride ", "मैं किसकी सवारी करूँगा ");
        map.put("Whose  will I ring ", "मैं किसकी रिंग करूंगा ");
        map.put("Whose  will I rise  ", "मैं किसका उठूंगा  ");
        map.put("Whose  will I run  ", "मैं किसका दौड़ूंगा  ");
        map.put("Whose  will I say ", "मैं किसका कहूँगा ");
        map.put("Whose  will I see ", "मैं किसका देखूंगा ");
        map.put("Whose  will I sell ", "मैं किसका बेचूंगा ");
        map.put("Whose  will I send ", "मैं किसका भेजूंगा ");
        map.put("Whose  will I shake ", "मैं किसका हिलाऊंगा ");
        map.put("Whose  will I shine ", "मैं किसका चमकूंगा ");
        map.put("Whose  will I shoot ", "मैं किसकी शूटिंग करूंगा ");
        map.put("Whose  will I think ", "मैं किसका सोचूंगा ");
        map.put("Whose  will I tell ", "मैं किसका बताऊंगा ");

        return map;
    }
    static Map<String,String> Ten(){
        HashMap<String,String>map = new HashMap<>();
        map.put("Whose  will I be abusing ", "मैं किसका गाली दे रहा हूँ ");
        map.put("Whose  will I be advising ", "मैं किसकी सलाह दूंगा ");
        map.put("Whose  will I be answering ", "मैं किसका जवाब दे रहा हूँ ");
        map.put("Whose  will I be arising ", "मैं किसका उठूंगा ");
        map.put("Whose  will I be arriving ", "मैं किसके पास आऊंगा ");
        map.put("Whose  will I be asking ", "मैं किससे पूछूंगा ");
        map.put("Whose  will I be awaking ", "मैं किसका जाग रहा हूँ ");
        map.put("Whose  will I be bearing ", "मैं किसका असर डालूंगा ");
        map.put("Whose  will I be beating ", "मैं किसकी पिटाई करूंगा ");
        map.put("Whose  will I be becoming ", "मैं किसका बन जाऊंगा ");
        map.put("Whose  will I be begging ", "मैं किसकी भीख माँग रहा हूँ ");
        map.put("Whose  will I be beginning ", "मैं किसकी शुरुआत करूंगा ");
        map.put("Whose  will I be binding ", "मैं किसका बाध्यकारी रहूंगा ");
        map.put("Whose  will I be biting ", "मैं किसका काट रहा हूँ ");
        map.put("Whose  will I be blessing ", "मैं किसकी आशीष बनूंगा ");
        map.put("Whose  will I be blowing ", "मैं किसका उड़ा रहा हूँ ");
        map.put("Whose  will I be breaking ", "मैं किसका तोड़ रहा हूँ ");
        map.put("Whose  will I be bringing ", "मैं किसका लाऊंगा ");
        map.put("Whose  will I be building ", "मैं किसका निर्माण करूंगा ");
        map.put("Whose  will I be burning ", "मैं किसका जल रहा हूँ ");
        map.put("Whose  will I be buying ", "मैं किसका खरीदूंगा ");
        map.put("Whose  will I be calling ", "मैं किसका फोन करूंगा ");
        map.put("Whose  will I be carrying ", "मैं किसका ले जाऊंगा ");
        map.put("Whose  will I be catching ", "मैं किसका पकड़ रहा हूँ ");
        map.put("Whose  will I be cheating ", "मैं किसकी धोखा दे रहा हूँ ");
        map.put("Whose  will I be choosing ", "मैं किसका चयन करूँगा ");
        map.put("Whose  will I be cleaning ", "मैं किसकी सफाई करूँगा ");
        map.put("Whose  will I be climbing ", "मैं किसकी चढ़ जाऊंगा ");
        map.put("Whose  will I be closing ", "मैं किसका बंद करूंगा ");
        map.put("Whose  will I be coming ", "मैं किसका आऊंगा ");
        map.put("Whose  will I be cooking ", "मैं किसका खाना बना रहा हूँ ");
        map.put("Whose  will I be creeping ", "मैं किसका रेंगना चाहूँगा ");
        map.put("Whose  will I be crying ", "मैं किसका रो रहा हूँ ");
        map.put("Whose  will I be cutting ", "मैं किसका काटूंगा ");
        map.put("Whose  will I be dancing ", "मैं किसका नाचता रहूँगा ");
        map.put("Whose  will I be dealing ", "मैं किसका काम करूंगा ");
        map.put("Whose  will I be dying ", "मैं किसका मर रहा हूँ ");
        map.put("Whose  will I be digging ", "मैं किसकी खुदाई करूँगा ");
        map.put("Whose  will I be drawing ", "मैं किसकी ड्राइंग करूँगा ");
        map.put("Whose  will I be drinking ", "मैं किसका पी रहा हूँ ");
        map.put("Whose  will I be driving ", "मैं किसकी गाड़ी चला रहा हूँ ");
        map.put("Whose  will I be dropping ", "मैं किसका छोड़ रहा हूँ ");
        map.put("Whose  will I be drying ", "मैं किसका सुखाऊंगा ");
        map.put("Whose  will I be eating ", "मैं किसका खाऊंगा ");
        map.put("Whose  will I be electing ", "मैं किसका चुनाव करूंगा ");
        map.put("Whose  will I be entering ", "मैं किसका प्रवेश करूँगा ");
        map.put("Whose  will I be falling ", "मैं किसका गिर रहा हूँ ");
        map.put("Whose  will I be feeding ", "मैं किसका खिलाऊंगा ");
        map.put("Whose  will I be feeling ", "मैं किसका महसूस कर रहा हूँ ");
        map.put("Whose  will I be fighting ", "मैं किससे लड़ूंगा ");
        map.put("Whose  will I be finding ", "मैं किसका खोज रहा हूँ ");
        map.put("Whose  will I be fleeing ", "मैं किससे भाग जाऊंगा ");
        map.put("Whose  will I be flying ", "मैं किसकी उड़ान भरूंगा ");
        map.put("Whose  will I be forgetting ", "मैं किसकी भूल जाऊंगा ");
        map.put("Whose  will I be frying ", "मैं किसका फ्राइंग करूँगा ");
        map.put("Whose  will I be getting ", "मुझे किसका मिलेगा ");
        map.put("Whose  will I be giving ", "मैं किसका दे रहा हूँ ");
        map.put("Whose  will I be going ", "मैं किसका जाऊंगा ");
        map.put("Whose  will I be growing ", "मैं किसका बढ़ रहा हूँ ");
        map.put("Whose  will I be hanging ", "मैं किसका लटकाऊंगा ");
        map.put("Whose  will I be hearing ", "मैं किसकी सुनूंगा ");
        map.put("Whose  will I be helping ", "मैं किसकी मदद करूंगा ");
        map.put("Whose  will I be hiding ", "मैं किसका छिपाऊंगा ");
        map.put("Whose  will I be hitting ", "मैं किसका मार रहा हूँ ");
        map.put("Whose  will I be holding ", "मैं किसकी पकड़ रखूँगा ");
        map.put("Whose  will I be hoping ", "मैं किसकी उम्मीद कर रहा हूँ ");
        map.put("Whose  will I be hurting ", "मैं किसकी चोट पहुँचाऊंगा ");
        map.put("Whose  will I be jumping ", "मैं किसका कूद रहा हूँ ");
        map.put("Whose  will I be keeping ", "मैं किसका रखूँगा ");
        map.put("Whose  will I be killing ", "मैं किसकी हत्या कर रहा हूँ ");
        map.put("Whose  will I be knowing ", "मुझे किसका पता चल जाएगा ");
        map.put("Whose  will I be laughing ", "मैं किसकी हँस रहा हूँ ");
        map.put("Whose  will I be leading ", "मैं किसका नेतृत्व करूंगा ");
        map.put("Whose  will I be leaping ", "मैं किसकी छलांग लगाऊंगा ");
        map.put("Whose  will I be learning ", "मैं किसका सीख रहा हूँ ");
        map.put("Whose  will I be leaving ", "मैं किसका छोड़ूँगा ");
        map.put("Whose  will I be lending ", "मैं किसका उधार दूंगा ");
        map.put("Whose  will I be living ", "मैं किसका रहूँगा ");
        map.put("Whose  will I be looking ", "मैं किसका देख रहा हूँ ");
        map.put("Whose  will I be losing ", "मैं किसका हारूंगा ");
        map.put("Whose  will I be loving ", "मैं किससे प्यार करूंगा ");
        map.put("Whose  will I be making ", "मैं किसका बना रहा हूँ ");
        map.put("Whose  will I be marrying ", "मैं किसकी शादी करूँगा ");
        map.put("Whose  will I be meeting ", "मैं किससे मिल रहा हूँ ");
        map.put("Whose  will I be mistaking ", "मैं किसकी गलती करूंगा ");
        map.put("Whose  will I be opening ", "मैं किसका खोलूंगा ");
        map.put("Whose  will I be paying ", "मैं किसका भुगतान करूंगा ");
        map.put("Whose  will I be playing ", "मैं किसका खेलूंगा ");
        map.put("Whose  will I be putting ", "मैं किसका डालूंगा ");
        map.put("Whose  will I be quarrelling ", "मैं किसका झगड़ा करूंगा ");
        map.put("Whose  will I be raining ", "मेरी बारिश किसकी होगी ");
        map.put("Whose  will I be reaching ", "मैं किसतक पहुँचूँगा ");
        map.put("Whose  will I be reading ", "मैं किसका पढ़ूँगा ");
        map.put("Whose  will I be remembering ", "मैं किसकी याद रखूँगा ");
        map.put("Whose  will I be riding ", "मैं किसकी सवारी करूँगा ");
        map.put("Whose  will I be ringing ", "मैं किसका बज रहा हूँ ");
        map.put("Whose  will I be rising ", "मैं किसका उठ रहा हूँ ");
        map.put("Whose  will I be running ", "मैं किसका दौड़ूंगा ");
        map.put("Whose  will I be saying ", "मैं किसका कहूँगा ");
        map.put("Whose  will I be seeing ", "मैं किसका देख रहा हूँ ");
        map.put("Whose  will I be selling ", "मैं किसका बेचूंगा ");
        map.put("Whose  will I be sending ", "मैं किसका भेजूंगा ");
        map.put("Whose  will I be shaking ", "मैं किसका हिलाऊंगा ");
        map.put("Whose  will I be shining ", "मैं किसका चमक रहा हूँ ");
        map.put("Whose  will I be shooting ", "मैं किसकी शूटिंग करूंगा ");
        map.put("Whose  will I be showing ", "मैं किसका दिखाऊंगा ");
        map.put("Whose  will I be thinking ", "मैं किसकी सोच रहा हूँ ");

        return map;
    }
    static Map<String,String> Eleven(){
        HashMap<String,String>map = new HashMap<>();
        map.put("Whose  will I have abused ", "मैंने किसके साथ गाली दी होगी ");
        map.put("Whose  will I have advised ", "मैंने किसकी सलाह दी होगी ");
        map.put("Whose  will I have answered ", "मैंने किसका जवाब दिया होगा ");
        map.put("Whose  will I have arisen ", "मैं किसका पैदा हुआ हूँ ");
        map.put("Whose  will I have arrived ", "मैं किसका आ गया हूँ ");
        map.put("Whose  will I have asked ", "मैंने किससे पूछा होगा ");
        map.put("Whose  will I have awoken ", "मैं किसकी जाग जाऊंगा ");
        map.put("Whose  will I have undefined", "मैं किसका अपरिभाषित होगा");
        map.put("Whose  will I have borne ", "मैं किसका वहन करूंगा ");
        map.put("Whose  will I have beaten ", "मैंने किसका पीटा होगा ");
        map.put("Whose  will I have become ", "मैं किसका बन गया हूँ ");
        map.put("Whose  will I have begged ", "मैंने किसकी भीख माँगी होगी ");
        map.put("Whose  will I have begun ", "मैंने किसकी शुरुआत की होगी ");
        map.put("Whose  will I have bound ", "मैं किसकी बाउंड करूंगा ");
        map.put("Whose  will I have bitten ", "मैंने किसका काट लिया होगा ");
        map.put("Whose  will I have blessed ", "मैं किसकी आशीष पाऊंगा ");
        map.put("Whose  will I have blown ", "मैंने किसका उड़ा दिया होगा ");
        map.put("Whose  will I have broken ", "मैं किसका तोड़ा जाऊंगा ");
        map.put("Whose  will I have brought ", "मैं किसका लाऊंगा ");
        map.put("Whose  will I have built ", "मैंने किसका निर्माण किया होगा ");
        map.put("Whose  will I have burnt ", "मैं किसका जला दूंगा ");
        map.put("Whose  will I have bought ", "मैंने किसका खरीदा होगा ");
        map.put("Whose  will I have called ", "मैंने किसका फोन किया होगा ");
        map.put("Whose  will I have carried ", "मैं किसका ले जाऊंगा ");
        map.put("Whose  will I have caught ", "मैंने किसका पकड़ा होगा ");
        map.put("Whose  will I have cheated ", "मैंने किसके साथ धोखा दिया होगा ");
        map.put("Whose  will I have chosen ", "मैंने किसका चुना होगा ");
        map.put("Whose  will I have cleaned ", "मैंने किसकी सफाई की होगी ");
        map.put("Whose  will I have climbed ", "मैं किसका चढ़ गया हूँ ");
        map.put("Whose  will I have closed ", "मैं किसका बंद कर दूँगा ");
        map.put("Whose  will I have come ", "मैं किसका आऊंगा ");
        map.put("Whose  will I have cooked ", "मैंने किसका खाना बनाया होगा ");
        map.put("Whose  will I have crept ", "मेरे पास क्रेप किसका होगा ");
        map.put("Whose  will I have cried ", "मैं किसका रोया होगा ");
        map.put("Whose  will I have cut ", "मैंने किसका काटा होगा ");
        map.put("Whose  will I have danced ", "मैंने किसका नृत्य किया होगा ");
        map.put("Whose  will I have dealt ", "मैंने किसका निपटाया होगा ");
        map.put("Whose  will I have died ", "मैं किसकी मर जाऊंगा ");
        map.put("Whose  will I have dug ", "मैंने किसका खोदा होगा ");
        map.put("Whose  will I have drawn ", "मैंने किसका ड्रा किया होगा ");
        map.put("Whose  will I have drunk ", "मैंने किसका पिया होगा ");
        map.put("Whose  will I have driven ", "मैं किसका चलाऊंगा ");
        map.put("Whose  will I have dropped ", "मैं किसका गिरा दूंगा ");
        map.put("Whose  will I have dried ", "मैं किसकी सूख जाऊंगा ");
        map.put("Whose  will I have eaten ", "मैंने किसका खाया होगा ");
        map.put("Whose  will I have elected ", "मैं किसका चुनाव करूँगा ");
        map.put("Whose  will I have entered ", "मैं किसका प्रवेश करूँगा ");
        map.put("Whose  will I have fallen ", "मैं किसका गिरूंगा ");
        map.put("Whose  will I have fed ", "मैंने किसका खिलाया होगा ");
        map.put("Whose  will I have felt ", "मैंने किसका महसूस किया होगा ");
        map.put("Whose  will I have fought ", "मैं किसकी लड़ाई लड़ी होगी ");
        map.put("Whose  will I have found ", "मुझे किसका मिलेगा ");
        map.put("Whose  will I have fled ", "मैं किससे भाग जाऊंगा ");
        map.put("Whose  will I have flown ", "मैं किसकी उड़ान भरेगा ");
        map.put("Whose  will I have forgotten ", "मैं किसकी भूल जाऊंगा ");
        map.put("Whose  will I have fried ", "मैं किसकी फ्राई करूँगा ");
        map.put("Whose  will I have got ", "मुझे किसका मिलेगा ");
        map.put("Whose  will I have given ", "मैंने किसका दिया होगा ");
        map.put("Whose  will I have gone ", "मैं किसके पास जाऊंगा ");
        map.put("Whose  will I have grown ", "मैं किसका उगाऊंगा ");
        map.put("Whose  will I have hanged ", "मैं किसकी फांसी लगाऊंगा ");
        map.put("Whose  will I have hung ", "मैंने किसका लटका दिया होगा ");
        map.put("Whose  will I have heard ", "मैंने किसका सुना होगा ");
        map.put("Whose  will I have helped ", "मैंने किसकी मदद की होगी ");
        map.put("Whose  will I have hidden ", "मैं किसका छिपाऊंगा ");
        map.put("Whose  will I have hit ", "मैंने किसका मारा होगा ");
        map.put("Whose  will I have held ", "मैंने किसका आयोजन किया होगा ");
        map.put("Whose  will I have hoped ", "मुझे किसकी उम्मीद होगी ");
        map.put("Whose  will I have hurt ", "मुझे किसकी चोट लगी होगी ");
        map.put("Whose  will I have jumped ", "मैं किसकी छलांग लगाऊंगा ");
        map.put("Whose  will I have kept ", "मैंने किसका रखा होगा ");
        map.put("Whose  will I have killed ", "मैं किसका मार डालूंगा ");
        map.put("Whose  will I have known ", "मुझे किसका पता चल जाएगा ");
        map.put("Whose  will I have laughed ", "मैं किसका हँसा होगा ");
        map.put("Whose  will I have led ", "मैंने किसका नेतृत्व किया होगा ");
        map.put("Whose  will I have leapt ", "मैं किसकी छलांग लगाऊंगा ");
        map.put("Whose  will I have learnt ", "मैंने किसका सीखा होगा ");
        map.put("Whose  will I have left ", "मैं किसका छोड़ दूँगा ");
        map.put("Whose  will I have lent ", "मैंने किसका उधार दिया होगा ");
        map.put("Whose  will I have lived ", "मैं किसकी रहूँगा ");
        map.put("Whose  will I have looked ", "मैंने किसका देखा होगा ");
        map.put("Whose  will I have lost ", "मैं किसका हार जाऊंगा ");
        map.put("Whose  will I have loved ", "मैं किससे प्यार करता हूँ ");
        map.put("Whose  will I have made ", "मैंने किसका बनाया होगा ");
        map.put("Whose  will I have married ", "मैंने किसकी शादी की होगी ");
        map.put("Whose  will I have met ", "मैं किससे मिला हूँ ");
        map.put("Whose  will I have mistaken ", "मेरी गलती किसकी होगी ");
        map.put("Whose  will I have opened ", "मैंने किसका खोला होगा ");
        map.put("Whose  will I have paid ", "मैंने किसका भुगतान किया होगा ");
        map.put("Whose  will I have played ", "मैंने किसका खेला होगा ");
        map.put("Whose  will I have put ", "मैंने किसका रखा होगा ");
        map.put("Whose  will I have quarrelled ", "मैं किसका झगड़ा करूंगा ");
        map.put("Whose  will I have rained ", "मेरी बारिश किसकी होगी ");
        map.put("Whose  will I have reached ", "मैं किसके पास पहुँचूँगा ");
        map.put("Whose  will I have read ", "मैंने किसका पढ़ा होगा ");
        map.put("Whose  will I have remembered ", "मुझे किसका याद होगा ");
        map.put("Whose  will I have ridden ", "मैंने किसकी सवारी की होगी ");
        map.put("Whose  will I have rung ", "मैं किसकी अंगूठी करूँगा ");
        map.put("Whose  will I have risen ", "मैं किसका उठ गया हूँ ");
        map.put("Whose  will I have run ", "मैं किसका दौड़ूंगा ");
        map.put("Whose  will I have said ", "मैंने किसका कहा होगा ");
        map.put("Whose  will I have seen ", "मैंने किसका देखा होगा ");
        map.put("Whose  will I have sold ", "मैंने किसका बेचा होगा ");
        map.put("Whose  will I have sent ", "मैंने किसका भेजा होगा ");
        map.put("Whose  will I have shaken ", "मैं किसका हिलाऊंगा ");
        map.put("Whose  will I have shone ", "मैं किसकी चमक जाऊंगा ");
        map.put("Whose  will I have shot ", "मैंने किसकी शूटिंग की होगी ");
        map.put("Whose  will I have shown ", "मैंने किसका दिखाया होगा ");
        map.put("Whose  will I have sung ", "मैंने किसका गाया होगा ");
        map.put("Whose  will I have sunk ", "मैं किसका डूब जाऊंगा ");
        map.put("Whose  will I have slept ", "मैं किसकी सोऊंगा ");
        map.put("Whose  will I have taught ", "मैंने किसका सिखाया होगा ");
        map.put("Whose  will I have wept ", "मैं किसकी रोऊंगा ");

        return map;
    }
    static Map<String,String> Twelve(){
        HashMap<String,String>map = new HashMap<>();
        map.put("Whose  will I have been abusing ", "मैं किसका गाली दे रहा हूँ ");
        map.put("Whose  will I have been advising ", "मैं किसकी सलाह दे रहा हूँ ");
        map.put("Whose  will I have been answering ", "मैं किसका जवाब दे रहा हूँ ");
        map.put("Whose  will I have been arising ", "मैं किसकी इच्छा पैदा कर रहा हूँ ");
        map.put("Whose  will I have been arriving ", "मैं किसका आ रहा हूँ ");
        map.put("Whose  will I have been asking ", "मैं किससे पूछ रहा हूँ ");
        map.put("Whose  will I have been awaking ", "मैं किसका जाग रहा हूँ ");
        map.put("Whose  will I have been undefined", "किसका होगा मैं अपरिभाषित हो गया");
        map.put("Whose  will I have been bearing ", "मैं किसका असर कर रहा हूँ ");
        map.put("Whose  will I have been beating ", "मैं किसकी पिटाई कर रहा हूँ ");
        map.put("Whose  will I have been becoming ", "मैं किसका बन रहा हूँ ");
        map.put("Whose  will I have been begging ", "मैं किसकी भीख माँग रहा हूँ ");
        map.put("Whose  will I have been beginning ", "मैं किसकी शुरुआत कर रहा हूँ ");
        map.put("Whose  will I have been binding ", "मैं किसका बाध्यकारी रहा हूँ ");
        map.put("Whose  will I have been biting ", "मैं किसका काट रहा हूँ ");
        map.put("Whose  will I have been blessing ", "मैं किसकी आशीष रहा हूँ ");
        map.put("Whose  will I have been blowing ", "मैं किसका उड़ा रहा हूँ ");
        map.put("Whose  will I have been breaking ", "मैं किसका तोड़ रहा हूँ ");
        map.put("Whose  will I have been bringing ", "मैं किसका ला रहा हूँ ");
        map.put("Whose  will I have been building ", "मैं किसका निर्माण कर रहा हूँ ");
        map.put("Whose  will I have been burning ", "मैं किसका जल रहा हूँ ");
        map.put("Whose  will I have been buying ", "मैं किसका खरीद रहा हूँ ");
        map.put("Whose  will I have been calling ", "मैं किसका फोन कर रहा हूँ ");
        map.put("Whose  will I have been carrying ", "मैं किसका ले जा रहा हूँ ");
        map.put("Whose  will I have been catching ", "मैं किसका पकड़ रहा हूँ ");
        map.put("Whose  will I have been cheating ", "मैं किसके साथ धोखा दे रहा हूँ ");
        map.put("Whose  will I have been choosing ", "मैं किसका चयन कर रहा हूँ ");
        map.put("Whose  will I have been cleaning ", "मैं किसकी सफाई कर रहा हूँ ");
        map.put("Whose  will I have been climbing ", "मैं किसकी चढ़ रहा हूँ ");
        map.put("Whose  will I have been closing ", "मैं किसका बंद कर रहा हूँ ");
        map.put("Whose  will I have been coming ", "मैं किसका आ रहा हूँ ");
        map.put("Whose  will I have been cooking ", "मैं किसका खाना बना रहा हूँ ");
        map.put("Whose  will I have been creeping ", "मैं किसका रेंग रहा हूँ ");
        map.put("Whose  will I have been crying ", "मैं किसका रो रहा हूँ ");
        map.put("Whose  will I have been cutting ", "मैं किसका काट रहा हूँ ");
        map.put("Whose  will I have been dancing ", "मैं किसका नाच रहा हूँ ");
        map.put("Whose  will I have been dealing ", "मैं किसका काम कर रहा हूँ ");
        map.put("Whose  will I have been dying ", "मैं किसका मर रहा हूँ ");
        map.put("Whose  will I have been digging ", "मैं किसकी खुदाई कर रहा हूँ ");
        map.put("Whose  will I have been drawing ", "मैं किसकी ड्राइंग कर रहा हूँ ");
        map.put("Whose  will I have been drinking ", "मैं किसका पी रहा हूँ ");
        map.put("Whose  will I have been driving ", "मैं किसकी गाड़ी चला रहा हूँ ");
        map.put("Whose  will I have been dropping ", "मैं किसका छोड़ रहा हूँ ");
        map.put("Whose  will I have been drying ", "मैं किसका सुखा रहा हूँ ");
        map.put("Whose  will I have been eating ", "मैं किसका खा रहा हूँ ");
        map.put("Whose  will I have been electing ", "मैं किसका चुनाव कर रहा हूँ ");
        map.put("Whose  will I have been entering ", "मैं किसका प्रवेश कर रहा हूँ ");
        map.put("Whose  will I have been falling ", "मैं किसका गिर रहा हूँ ");
        map.put("Whose  will I have been feeding ", "मैं किसका भोजन कर रहा हूँ ");
        map.put("Whose  will I have been feeling ", "मैं किसका महसूस कर रहा हूँ ");
        map.put("Whose  will I have been fighting ", "मैं किससे लड़ रहा हूँ ");
        map.put("Whose  will I have been finding ", "मुझे किसका मिल रहा होगा ");
        map.put("Whose  will I have been fleeing ", "मैं किससे भाग रहा हूँ ");
        map.put("Whose  will I have been flying ", "मैं किसकी उड़ान भर रहा हूँ ");
        map.put("Whose  will I have been forgetting ", "मैं किसकी भूल गया हूँ ");
        map.put("Whose  will I have been frying ", "मैं किसका फ्राइंग कर रहा हूँ ");
        map.put("Whose  will I have been getting ", "मुझे किसका मिल रहा होगा ");
        map.put("Whose  will I have been giving ", "मैं किसका दे रहा हूँ ");
        map.put("Whose  will I have been going ", "मैं किसका जा रहा हूँ ");
        map.put("Whose  will I have been growing ", "मैं किसका विकास कर रहा हूँ ");
        map.put("Whose  will I have been hanging ", "मैं किसकी लटक रहा हूँ ");
        map.put("Whose  will I have been hearing ", "मैं किसकी सुन रहा हूँ ");
        map.put("Whose  will I have been helping ", "मैं किसकी मदद कर रहा हूँ ");
        map.put("Whose  will I have been hiding ", "मैं किसका छिपा रहा हूँ ");
        map.put("Whose  will I have been hitting ", "मैं किसका मार रहा हूँ ");
        map.put("Whose  will I have been holding ", "मैं किसका धारण कर रहा हूँ ");
        map.put("Whose  will I have been hoping ", "मैं किसकी उम्मीद कर रहा था ");
        map.put("Whose  will I have been hurting ", "मैं किसका दर्द कर रहा हूँ ");
        map.put("Whose  will I have been jumping ", "मैं किसका कूद रहा हूँ ");
        map.put("Whose  will I have been keeping ", "मैं किसका रख रहा हूँ ");
        map.put("Whose  will I have been killing ", "मैं किसकी हत्या कर रहा हूँ ");
        map.put("Whose  will I have been knowing ", "मुझे किसका पता चल गया होगा ");
        map.put("Whose  will I have been laughing ", "मैं किसकी हँस रहा हूँ ");
        map.put("Whose  will I have been leading ", "मैं किसका नेतृत्व कर रहा हूँ ");
        map.put("Whose  will I have been leaping ", "मैं किसकी छलांग लगा रहा हूँ ");
        map.put("Whose  will I have been learning ", "मैं किसका सीख रहा हूँ ");
        map.put("Whose  will I have been leaving ", "मैं किसका छोड़ रहा हूँ ");
        map.put("Whose  will I have been lending ", "मैं किसका उधार दे रहा हूँ ");
        map.put("Whose  will I have been living ", "मैं किसका जी रहा हूँ ");
        map.put("Whose  will I have been looking ", "मैं किसका देख रहा हूँ ");
        map.put("Whose  will I have been losing ", "मैं किसका हार रहा हूँ ");
        map.put("Whose  will I have been loving ", "मैं किससे प्यार कर रहा हूँ ");
        map.put("Whose  will I have been making ", "मैं किसका बना रहा हूँ ");
        map.put("Whose  will I have been marrying ", "मैं किसकी शादी कर रहा हूँ ");
        map.put("Whose  will I have been meeting ", "मैं किससे मिल रहा हूँ ");
        map.put("Whose  will I have been mistaking ", "मैं किसकी गलती कर रहा हूँ ");
        map.put("Whose  will I have been opening ", "मैं किसका खोल रहा हूँ ");
        map.put("Whose  will I have been paying ", "मैं किसका भुगतान कर रहा हूँ ");
        map.put("Whose  will I have been playing ", "मैं किसका खेल रहा हूँ ");
        map.put("Whose  will I have been putting ", "मैं किसका लगा रहा हूँ ");
        map.put("Whose  will I have been quarrelling ", "मैं किसका झगड़ा कर रहा हूँ ");
        map.put("Whose  will I have been raining ", "मैं किसकी बारिश कर रहा हूँ ");
        map.put("Whose  will I have been reaching ", "मैं किसके पास पहुँच रहा हूँ ");
        map.put("Whose  will I have been reading ", "मैं किसका पढ़ रहा हूँ ");
        map.put("Whose  will I have been remembering ", "मुझे किसकी याद आ रही होगी ");
        map.put("Whose  will I have been riding ", "मैं किसकी सवारी कर रहा हूँ ");
        map.put("Whose  will I have been ringing ", "मैं किसका बज रहा हूँ ");
        map.put("Whose  will I have been rising ", "मैं किसका उठ रहा हूँ ");
        map.put("Whose  will I have been running ", "मैं किसकी दौड़ रहा हूँ ");
        map.put("Whose  will I have been saying ", "मैं किसका कह रहा हूँ ");
        map.put("Whose  will I have been seeing ", "मैं किसका देख रहा हूँ ");
        map.put("Whose  will I have been selling ", "मैं किसका बेच रहा हूँ ");
        map.put("Whose  will I have been sending ", "मैं किसका भेज रहा हूँ ");
        map.put("Whose  will I have been shaking ", "मैं किसका हिला रहा हूँ ");
        map.put("Whose  will I have been shining ", "मैं किसका चमक रहा हूँ ");
        map.put("Whose  will I have been shooting ", "मैं किसकी शूटिंग कर रहा हूँ ");
        map.put("Whose  will I have been showing ", "मैं किसका दिखा रहा हूँ ");
        map.put("Whose  will I have been stealing ", "मैं किसकी चोरी कर रहा हूँ ");

        return map;
    }


}

