package com.shiviishiv7.helloenglish;

import java.util.HashMap;
import java.util.Map;

public class AnswerData {
    static Map<String,String> getData(int state){
        switch (state){
            case 1:return One();
            case 2:return Two();
            case 3:return Three();
            case 4:return Four();
            case 5:return Five();
            case 6:return Six();
            case 7:return Seven();
            case 8:return Eight();
            case 9:return Nine();
            case 10:return Ten();
            case 11:return Eleven();
            case 12:return Twelve();

            default:return One();
        }

    }
    private static Map<String, String> Twelve() {
        HashMap<String,String>map = new HashMap<>();
        map.put("I will have been abusing ", "मैं गाली दे रहा होता ");
        map.put("I will have been advising ", "मैं सलाह दे रहा हूँ ");
        map.put("I will have been answering ", "मैं जवाब दे रहा होता ");
        map.put("I will have been arising ", "मैं उठ रहा होगा ");
        map.put("I will have been arriving ", "मैं आ रहा हूँ ");
        map.put("I will have been asking ", "मैं पूछ रहा होता ");
        map.put("I will have been beating ", "मैं पिटाई कर रहा होगा ");
        map.put("I will have been becoming ", "मैं बन गया होता जा रहा हूँ ");
        map.put("I will have been undefined", "मैं अपरिभाषित हो गया होगा");
        map.put("I will have been bearing ", "मैं असर कर रहा होगा ");
        map.put("I will have been begging ", "मैं भीख माँग रहा होता ");
        map.put("I will have been awaking ", "मैं जाग रहा होता ");
        map.put("I will have been beginning ", "मैं शुरुआत कर रहा हूँ ");
        map.put("I will have been biting ", "मैं काट रहा होगा ");
        map.put("I will have been binding ", "मैं बाध्यकारी रहा होगा ");
        map.put("I will have been breaking ", "मैं टूट रहा होगा ");
        map.put("I will have been blowing ", "मैं उड़ रहा होगा ");
        map.put("I will have been building ", "मैं निर्माण कर रहा होता ");
        map.put("I will have been buying ", "मैं खरीद रहा होता ");
        map.put("I will have been burning ", "मैं जल रहा होगा ");
        map.put("I will have been blessing ", "मैं आशीष रहा होगा ");
        map.put("I will have been calling ", "मैं कॉल कर रहा होता ");
        map.put("I will have been bringing ", "मैं ला रहा होता ");
        map.put("I will have been carrying ", "मैं ले जा रहा होता ");
        map.put("I will have been catching ", "मैं पकड़ रहा होगा ");
        map.put("I will have been cheating ", "मैं धोखा दे रहा होगा ");
        map.put("I will have been choosing ", "मैं चुन रहा होता ");
        map.put("I will have been cleaning ", "मैं सफाई कर रहा होता ");
        map.put("I will have been climbing ", "मैं चढ़ रहा होता ");
        map.put("I will have been closing ", "मैं बंद हो गया होता ");
        map.put("I will have been creeping ", "मैं रेंग रहा होता ");
        map.put("I will have been cooking ", "मैं खाना बना रहा होता ");
        map.put("I will have been crying ", "मैं रो रहा होता ");
        map.put("I will have been coming ", "मैं आ रहा होता ");
        map.put("I will have been cutting ", "मैं काट रहा होगा ");
        map.put("I will have been dancing ", "मैं नाचता रहा होगा ");
        map.put("I will have been dying ", "मैं मर रहा होगा ");
        map.put("I will have been dealing ", "मैं काम कर रहा होगा ");
        map.put("I will have been digging ", "मैं खुदाई कर रहा हूँ ");
        map.put("I will have been doing ", "मैं कर रहा होता ");
        map.put("I will have been drawing ", "मैं ड्राइंग कर रहा हूँ ");
        map.put("I will have been dreaming ", "मैं सपना देख रहा होगा ");
        map.put("I will have been drinking ", "मैं पी रहा होता ");
        map.put("I will have been driving ", "मैं गाड़ी चला रहा होता ");
        map.put("I will have been dropping ", "मैं गिर रहा होगा ");
        map.put("I will have been drying ", "मैं सूख रहा होगा ");
        map.put("I will have been eating ", "मैं खा रहा होता ");
        map.put("I will have been electing ", "मैं चुनाव कर रहा होता ");
        map.put("I will have been entering ", "मैं प्रवेश कर रहा हूँ ");
        map.put("I will have been falling ", "मैं गिर रहा होगा ");
        map.put("I will have been feeding ", "मैं खिला रहा होता ");
        map.put("I will have been feeling ", "मैं महसूस कर रहा होगा ");
        map.put("I will have been finding ", "मुझे मिल रहा होगा ");
        map.put("I will have been fighting ", "मैं लड़ता रहूंगा ");
        map.put("I will have been fleeing ", "मैं भाग गया होता ");
        map.put("I will have been flying ", "मैं उड़ रहा होता ");
        map.put("I will have been forgetting ", "मैं भूल गया होता ");
        map.put("I will have been frying ", "मैं तलने गया होता ");
        map.put("I will have been giving ", "मैं दे रहा होता ");
        map.put("I will have been getting ", "मुझे मिल रहा होगा ");
        map.put("I will have been going ", "मैं जा रहा होता ");
        map.put("I will have been growing ", "मैं बढ़ रहा होता ");
        map.put("I will have been hanging ", "मैं लटक गया होता ");
        map.put("I will have been hearing ", "मैं सुन रहा होता ");
        map.put("I will have been helping ", "मैं मदद कर रहा होता ");
        map.put("I will have been hitting ", "मैं मार रहा होगा ");
        map.put("I will have been hiding ", "मैं छिप गया होता ");
        map.put("I will have been hoping ", "मैं उम्मीद कर रहा होता ");
        map.put("I will have been holding ", "मैं पकड़ रहा होगा ");
        map.put("I will have been hurting ", "मैं दर्द कर रहा होगा ");
        map.put("I will have been jumping ", "मैं कूद रहा होगा ");
        map.put("I will have been killing ", "मैं मार रहा होगा ");
        map.put("I will have been keeping ", "मैं रख रहा होता ");
        map.put("I will have been leading ", "मैं अग्रणी रहा होगा ");
        map.put("I will have been leaping ", "मैं छलांग लगा रहा होगा ");
        map.put("I will have been learning ", "मैं सीख रहा होता ");
        map.put("I will have been leaving ", "मैं जा रहा होता ");
        map.put("I will have been lending ", "मैं उधार दे रहा होता ");
        map.put("I will have been knowing ", "मुझे पता चल गया होगा ");
        map.put("I will have been laughing ", "मैं हँस रहा होगा ");
        map.put("I will have been looking ", "मैं देख रहा होता ");
        map.put("I will have been living ", "मैं रह रहा हूँ ");
        map.put("I will have been losing ", "मैं हार गया होता ");
        map.put("I will have been making ", "मैं बना रहा होता ");
        map.put("I will have been loving ", "मैं प्यार करता रहा होगा ");
        map.put("I will have been marrying ", "मैं शादी कर रहा होगा ");
        map.put("I will have been meeting ", "मैं मिल रहा होगा ");
        map.put("I will have been opening ", "मैं खुल रहा होगा ");
        map.put("I will have been paying ", "मैं भुगतान कर रहा हूँ ");
        map.put("I will have been playing ", "मैं खेल रहा होता ");
        map.put("I will have been putting ", "मैं डाल रहा होता ");
        map.put("I will have been quarrelling ", "मैं झगड़ा कर रहा होगा ");
        map.put("I will have been mistaking ", "मैं गलती कर रहा होगा ");
        map.put("I will have been reaching ", "मैं पहुँच रहा हूँ ");
        map.put("I will have been reading ", "मैं पढ़ रहा होता ");
        map.put("I will have been remembering ", "मुझे याद आ रहा होगा ");
        map.put("I will have been ringing ", "मैं बज रहा होगा ");
        map.put("I will have been raining ", "बारिश हो रही होगी ");
        map.put("I will have been running ", "मैं दौड़ रहा होता ");
        map.put("I will have been riding ", "मैं सवारी कर रहा होगा ");
        map.put("I will have been rising ", "मैं उठ रहा होगा ");
        map.put("I will have been saying ", "मैं कह रहा होता ");
        map.put("I will have been sending ", "मैं भेज रहा हूँ ");
        map.put("I will have been selling ", "मैं बेच रहा होता ");
        map.put("I will have been shaking ", "मैं हिल रहा होगा ");
        map.put("I will have been seeing ", "मैं देख रहा होता ");
        map.put("I will have been shooting ", "मैं शूटिंग कर रहा होगा ");
        map.put("I will have been shining ", "मैं चमक रहा होगा ");
        map.put("I will have been showing ", "मैं दिखा रहा होता ");
        map.put("I will have been shutting ", "मैं बंद हो गया होता ");
        map.put("I will have been singing ", "मैं गा रहा होता ");
        map.put("I will have been sinking ", "मैं डूब गया होता ");
        map.put("I will have been smelling ", "मुझे महक आ रही होगी ");
        map.put("I will have been sleeping ", "मैं सो गया होता ");
        map.put("I will have been speaking ", "मैं बोल रहा होता ");
        map.put("I will have been spending ", "मैं खर्च कर रहा होता ");
        map.put("I will have been standing ", "मैं खड़ा हो गया होता ");
        map.put("I will have been spoilt", "मैं खराब हो गया होता");
        map.put("I will have been starting ", "मैं शुरू कर रहा हूँ ");
        map.put("I will have been stealing ", "मैं चोरी कर रहा होता ");
        map.put("I will have been staying ", "मैं रहूंगा ");
        map.put("I will have been swimming ", "मैं तैर रहा होता ");
        map.put("I will have been studying ", "मैं पढ़ाई कर रहा होता ");
        map.put("I will have been taking ", "मैं ले रहा हूँ ");
        map.put("I will have been talking ", "मैं बात कर रहा होता ");
        map.put("I will have been tearing ", "मैं फाड़ रहा होगा ");
        map.put("I will have been teaching ", "मैं पढ़ा रहा होगा ");
        map.put("I will have been telling ", "मैं बता रहा होता ");
        map.put("I will have been thanking ", "मैं शुक्रिया अदा करता रहा होगा ");
        map.put("I will have been thinking ", "मैं सोच रहा होता ");
        map.put("I will have been throwing ", "मैं फेंक रहा होगा ");
        map.put("I will have been trying ", "मैं कोशिश कर रहा होता ");
        map.put("I will have been understanding ", "मैं समझ रहा होगा ");
        map.put("I will have been using ", "मैं उपयोग कर रहा हूँ ");
        map.put("I will have been walking ", "मैं चल रहा होता ");
        map.put("I will have been wanting ", "मैं चाहूँगा ");
        map.put("I will have been washing ", "मैं धो रहा होता ");
        map.put("I will have been wearing ", "मैं पहन रहा होगा ");
        map.put("I will have been weeping ", "मैं रो रहा होता ");
        map.put("I will have been winning ", "मैं जीत रहा होता ");
        map.put("I will have been working ", "मैं काम कर रहा होता ");
        map.put("I will have been writing ", "मैं लिख रहा होता ");
        return map;
    }
    private static Map<String, String> Eleven() {
        HashMap<String,String>map = new HashMap<>();
        map.put("I will have abused ", "मैंने गाली दी होगी ");
        map.put("I will have advised ", "मैंने सलाह दी होगी ");
        map.put("I will have answered ", "मैंने जवाब दिया होगा ");
        map.put("I will have arisen ", "मैं उठ जाऊंगा ");
        map.put("I will have arrived ", "मैं आ गया हूँ ");
        map.put("I will have asked ", "मैंने पूछा होगा ");
        map.put("I will have awoken ", "मैं जाग जाऊंगा ");
        map.put("I will have undefined", "मैं अपरिभाषित हो जाऊंगा");
        map.put("I will have beaten ", "मैंने पीटा होगा ");
        map.put("I will have begged ", "मैं भीख माँगता हूँ ");
        map.put("I will have borne ", "मैं पैदा हो जाऊंगा ");
        map.put("I will have become ", "मैं बन जाऊंगा ");
        map.put("I will have begun ", "मैं शुरू कर दूँगा ");
        map.put("I will have bound ", "मैं बाध्य हो जाऊंगा ");
        map.put("I will have bitten ", "मैंने काट लिया होगा ");
        map.put("I will have blessed ", "मैं आशीष पाऊंगा ");
        map.put("I will have blown ", "मैं उड़ जाऊंगा ");
        map.put("I will have broken ", "मैं टूट जाऊंगा ");
        map.put("I will have brought ", "मैं लाऊंगा ");
        map.put("I will have built ", "मैंने बनाया होगा ");
        map.put("I will have bought ", "मैंने खरीदा होगा ");
        map.put("I will have carried ", "मैं ले जाऊंगा ");
        map.put("I will have called ", "मैंने फोन किया होगा ");
        map.put("I will have burnt ", "मैं जल जाऊंगा ");
        map.put("I will have caught ", "मैंने पकड़ लिया होगा ");
        map.put("I will have cheated ", "मैंने धोखा दिया होगा ");
        map.put("I will have chosen ", "मैंने चुना होगा ");
        map.put("I will have cleaned ", "मैंने साफ कर लिया होगा ");
        map.put("I will have climbed ", "मैं चढ़ जाऊंगा ");
        map.put("I will have closed ", "मैं बंद हो जाऊंगा ");
        map.put("I will have cooked ", "मैंने खाना बनाया होगा ");
        map.put("I will have come ", "मैं आ गया हूँ ");
        map.put("I will have cried ", "मैं रोया होता ");
        map.put("I will have cut ", "मैं कट जाऊंगा ");
        map.put("I will have crept ", "मेरे पास क्रेप्ट होगा ");
        map.put("I will have danced ", "मैंने नृत्य किया होगा ");
        map.put("I will have dealt ", "मैंने निपटा लिया होगा ");
        map.put("I will have died ", "मैं मर जाऊंगा ");
        map.put("I will have dug ", "मैंने खोदा होगा ");
        map.put("I will have drawn ", "मैंने ड्रॉ किया होगा ");
        map.put("I will have done ", "मैंने किया होगा ");
        map.put("I will have drunk ", "मैं नशे में हो जाऊंगा ");
        map.put("I will have dreamt ", "मैंने सपना देखा होगा ");
        map.put("I will have driven ", "मैंने ड्राइव किया होगा ");
        map.put("I will have dropped ", "मैं गिरा जाऊंगा ");
        map.put("I will have dried ", "मैं सूख जाऊंगा ");
        map.put("I will have eaten ", "मैंने खा लिया होगा ");
        map.put("I will have elected ", "मैं निर्वाचित हो जाऊंगा ");
        map.put("I will have entered ", "मैं प्रवेश कर जाऊंगा ");
        map.put("I will have fed ", "मैंने खिलाया होगा ");
        map.put("I will have felt ", "मैंने महसूस किया होगा ");
        map.put("I will have found ", "मुझे मिल गया होगा ");
        map.put("I will have fallen ", "मैं गिर गया होगा ");
        map.put("I will have fled ", "मैं भाग जाऊंगा ");
        map.put("I will have flown ", "मैं उड़ जाऊंगा ");
        map.put("I will have fought ", "मैं लड़ी होगी ");
        map.put("I will have forgotten ", "मैं भूल जाऊंगा ");
        map.put("I will have fried ", "मैंने फ्राई किया होगा ");
        map.put("I will have got ", "मुझे मिल गया होगा ");
        map.put("I will have gone ", "मैं चला गया होता ");
        map.put("I will have grown ", "मैं बड़ा हो जाऊंगा ");
        map.put("I will have hanged ", "मैं फांसी लगा लूंगा ");
        map.put("I will have hung ", "मैंने लटका दिया होगा ");
        map.put("I will have given ", "मैंने दिया होगा ");
        map.put("I will have helped ", "मैंने मदद की होगी ");
        map.put("I will have heard ", "मैंने सुना होगा ");
        map.put("I will have hidden ", "मैं छिप जाऊंगा ");
        map.put("I will have hit ", "मैं हिट करूंगा ");
        map.put("I will have held ", "मैंने आयोजित किया होगा ");
        map.put("I will have hoped ", "मुझे उम्मीद होगी ");
        map.put("I will have hurt ", "मुझे चोट लगी होगी ");
        map.put("I will have jumped ", "मैं कूद गया होगा ");
        map.put("I will have kept ", "मैंने रखा होगा ");
        map.put("I will have killed ", "मैं मार डालूंगा ");
        map.put("I will have known ", "मुझे पता चल जाएगा ");
        map.put("I will have laughed ", "मैं हँसा होगा ");
        map.put("I will have led ", "मैंने नेतृत्व किया होगा ");
        map.put("I will have learnt ", "मैंने सीखा होगा ");
        map.put("I will have leapt ", "मैं छलांग लगाऊंगा ");
        map.put("I will have left ", "मैंने छोड़ दिया होगा ");
        map.put("I will have lent ", "मैंने लेंट किया होगा ");
        map.put("I will have lived ", "मैं जीवित रहूंगा ");
        map.put("I will have looked ", "मैंने देखा होगा ");
        map.put("I will have loved ", "मैंने प्यार किया होगा ");
        map.put("I will have made ", "मैंने बनाया होगा ");
        map.put("I will have lost ", "मैं हार जाऊंगा ");
        map.put("I will have married ", "मैंने शादी कर ली होगी ");
        map.put("I will have met ", "मैं मिल जाऊंगा ");
        map.put("I will have mistaken ", "मैं गलत हो जाऊंगा ");
        map.put("I will have opened ", "मैं खुल जाऊंगा ");
        map.put("I will have played ", "मैं खेलूंगा ");
        map.put("I will have put ", "मैंने रखा होगा ");
        map.put("I will have paid ", "मैंने भुगतान किया होगा ");
        map.put("I will have quarrelled ", "मैं झगड़ा करूंगा ");
        map.put("I will have rained ", "मेरी बारिश होगी ");
        map.put("I will have reached ", "मैं पहुँच जाऊंगा ");
        map.put("I will have read ", "मैंने पढ़ा होगा ");
        map.put("I will have remembered ", "मुझे याद होगा ");
        map.put("I will have ridden ", "मैंने सवारी की होगी ");
        map.put("I will have rung ", "मेरे पास रूंग होगा ");
        map.put("I will have risen ", "मैं उठ जाऊंगा ");
        map.put("I will have seen ", "मैंने देखा होगा ");
        map.put("I will have run ", "मैं दौड़ूंगा ");
        map.put("I will have said ", "मैंने कहा होगा ");
        map.put("I will have sent ", "मैंने भेजा होगा ");
        map.put("I will have shaken ", "मैं हिल जाऊंगा ");
        map.put("I will have shot ", "मैंने गोली मार दी होगी ");
        map.put("I will have shone ", "मैं चमक जाऊंगा ");
        map.put("I will have shown ", "मैंने दिखाया होगा ");
        map.put("I will have shut ", "मैं बंद हो जाऊंगा ");
        map.put("I will have sold ", "मैंने बेचा होगा ");
        map.put("I will have slept ", "मैं सो जाऊंगा ");
        map.put("I will have sunk ", "मैं डूब जाऊंगा ");
        map.put("I will have sung ", "मैंने गाया होगा ");
        map.put("I will have smelt ", "मैं स्मेल्ट कर लूंगा ");
        map.put("I will have spoken ", "मैंने बात की होगी ");
        map.put("I will have spent ", "मैंने खर्च किया होगा ");
        map.put("I will have  spoiled ", "मैं खराब हो जाऊंगा ");
        map.put("I will have stood ", "मैं खड़ा हो जाऊंगा ");
        map.put("I will have started ", "मैंने शुरू कर दिया होगा ");
        map.put("I will have stayed ", "मैं रुका रहूंगा ");
        map.put("I will have studied ", "मैंने पढ़ाई की होगी ");
        map.put("I will have stolen ", "मैं चोरी कर लूंगा ");
        map.put("I will have swum ", "मेरे पास तैरना होगा ");
        map.put("I will have taken ", "मैंने ले लिया होगा ");
        map.put("I will have talked ", "मैंने बात की होगी ");
        map.put("I will have taught ", "मैंने पढ़ाया होगा ");
        map.put("I will have torn ", "मैं फटा हुआ हूँ ");
        map.put("I will have told ", "मैंने बताया होगा ");
        map.put("I will have thanked ", "मैंने धन्यवाद दिया होगा ");
        map.put("I will have thought ", "मैंने सोचा होगा ");
        map.put("I will have thrown ", "मैंने फेंक दिया होगा ");
        map.put("I will have tried ", "मैंने कोशिश की होगी ");
        map.put("I will have understood ", "मैं समझ गया होगा ");
        map.put("I will have used ", "मैंने इस्तेमाल किया होगा ");
        map.put("I will have walked ", "मैं चला जाऊंगा ");
        map.put("I will have wanted ", "मैं चाहूँगा ");
        map.put("I will have washed ", "मैंने धोया होगा ");
        map.put("I will have worn ", "मैंने पहना होगा ");
        map.put("I will have wept ", "मैं रोया होता ");
        map.put("I will have won ", "मैं जीत जाऊंगा ");
        map.put("I will have worked ", "मैंने काम किया होगा ");
        map.put("I will have written ", "मैंने लिखा होगा ");
        return map;
    }
    private static Map<String, String> Ten() {
        HashMap<String,String>map = new HashMap<>();
        map.put("I will be abusing ", "मैं गाली दे रहा हूँ ");
        map.put("I will be advising ", "मैं सलाह दूंगा ");
        map.put("I will be answering ", "मैं जवाब दूंगा ");
        map.put("I will be arising ", "मैं उठ रहा हूँ ");
        map.put("I will be arriving ", "मैं पहुंच जाऊंगा ");
        map.put("I will be asking ", "मैं पूछ रहा हूँ ");
        map.put("I will be awaking ", "मैं जाग जाऊंगा ");
        map.put("I will be undefined", "मैं अपरिभाषित हो जाऊंगा");
        map.put("I will be bearing ", "मैं असर करूंगा ");
        map.put("I will be beating ", "मैं धड़कता रहूंगा ");
        map.put("I will be becoming ", "मैं बन जाऊंगा ");
        map.put("I will be begging ", "मैं भीख माँगता हूँ ");
        map.put("I will be beginning ", "मैं शुरुआत करूंगा ");
        map.put("I will be biting ", "मैं काट रहा हूँ ");
        map.put("I will be binding ", "मैं बाध्यकारी रहूंगा ");
        map.put("I will be blessing ", "मैं आशीष बनूंगा ");
        map.put("I will be blowing ", "मैं उड़ रहा हूँ ");
        map.put("I will be breaking ", "मैं टूट जाऊंगा ");
        map.put("I will be bringing ", "मैं लाऊंगा ");
        map.put("I will be building ", "मैं निर्माण करूंगा ");
        map.put("I will be burning ", "मैं जल रहा हूँ ");
        map.put("I will be calling ", "मैं कॉल कर रहा हूँ ");
        map.put("I will be catching ", "मैं पकड़ रहा हूँ ");
        map.put("I will be carrying ", "मैं ले जाऊंगा ");
        map.put("I will be buying ", "मैं खरीदूंगा ");
        map.put("I will be cheating ", "मैं धोखा दे रहा हूँ ");
        map.put("I will be choosing ", "मैं चुनूंगा ");
        map.put("I will be cleaning ", "मैं सफाई करूंगा ");
        map.put("I will be climbing ", "मैं चढ़ जाऊंगा ");
        map.put("I will be closing ", "मैं बंद हो जाऊंगा ");
        map.put("I will be coming ", "मैं आ रहा हूँ ");
        map.put("I will be creeping ", "मैं रेंग रहा हूँ ");
        map.put("I will be crying ", "मैं रो रहा हूँ ");
        map.put("I will be cutting ", "मैं काटूंगा ");
        map.put("I will be dealing ", "मैं डीलिंग करूंगा ");
        map.put("I will be dancing ", "मैं नाचता रहूँगा ");
        map.put("I will be cooking ", "मैं खाना बना रहा हूँ ");
        map.put("I will be digging ", "मैं खुदाई करूंगा ");
        map.put("I will be dying ", "मैं मर जाऊंगा ");
        map.put("I will be doing ", "मैं कर रहा हूँ ");
        map.put("I will be drawing ", "मैं ड्राइंग करूंगा ");
        map.put("I will be dreaming ", "मैं सपना देख रहा हूँ ");
        map.put("I will be drinking ", "मैं पी रहा हूँ ");
        map.put("I will be driving ", "मैं गाड़ी चला रहा हूँ ");
        map.put("I will be dropping ", "मैं गिर जाऊंगा ");
        map.put("I will be drying ", "मैं सूख जाऊंगा ");
        map.put("I will be eating ", "मैं खा रहा हूँ ");
        map.put("I will be electing ", "मैं चुनाव करूंगा ");
        map.put("I will be entering ", "मैं प्रवेश करूंगा ");
        map.put("I will be falling ", "मैं गिर रहा हूँ ");
        map.put("I will be feeding ", "मैं खिलाऊंगा ");
        map.put("I will be feeling ", "मैं महसूस कर रहा हूँ ");
        map.put("I will be fighting ", "मैं लड़ूंगा ");
        map.put("I will be finding ", "मुझे मिल जाएगा ");
        map.put("I will be fleeing ", "मैं भाग जाऊंगा ");
        map.put("I will be forgetting ", "मैं भूल जाऊंगा ");
        map.put("I will be flying ", "मैं उड़ जाऊंगा ");
        map.put("I will be frying ", "मैं तलने जाऊंगा ");
        map.put("I will be getting ", "मुझे मिल रहा होगा ");
        map.put("I will be going ", "मैं जा रहा हूँ ");
        map.put("I will be giving ", "मैं दे रहा हूँ ");
        map.put("I will be growing ", "मैं बढ़ रहा हूँ ");
        map.put("I will be hanging ", "मैं लटक जाऊंगा ");
        map.put("I will be hearing ", "मैं सुन रहा हूँ ");
        map.put("I will be helping ", "मैं मदद करूंगा ");
        map.put("I will be hiding ", "मैं छिप जाऊंगा ");
        map.put("I will be hitting ", "मैं मार रहा हूँ ");
        map.put("I will be holding ", "मैं पकड़ लूंगा ");
        map.put("I will be hoping ", "मैं उम्मीद कर रहा हूँ ");
        map.put("I will be hurting ", "मैं चोट पहुँचाऊंगा ");
        map.put("I will be keeping ", "मैं रखूंगा ");
        map.put("I will be knowing ", "मुझे पता चल जाएगा ");
        map.put("I will be killing ", "मैं मार रहा हूँ ");
        map.put("I will be laughing ", "मैं हँस रहा हूँ ");
        map.put("I will be leading ", "मैं अग्रणी रहूंगा ");
        map.put("I will be jumping ", "मैं कूद रहा हूँ ");
        map.put("I will be learning ", "मैं सीख रहा हूँ ");
        map.put("I will be leaping ", "मैं छलांग लगाऊंगा ");
        map.put("I will be leaving ", "मैं जा रहा हूँ ");
        map.put("I will be lending ", "मैं उधार दूंगा ");
        map.put("I will be living ", "मैं जीवित रहूंगा ");
        map.put("I will be looking ", "मैं देख रहा हूँ ");
        map.put("I will be loving ", "मैं प्यार करूंगा ");
        map.put("I will be making ", "मैं बना रहा हूँ ");
        map.put("I will be marrying ", "मैं शादी करूंगा ");
        map.put("I will be meeting ", "मैं मिल जाऊंगा ");
        map.put("I will be mistaking ", "मैं गलत हो जाऊंगा ");
        map.put("I will be opening ", "मैं खुल जाऊंगा ");
        map.put("I will be paying ", "मैं भुगतान कर रहा हूँ ");
        map.put("I will be losing ", "मैं हार जाऊंगा ");
        map.put("I will be playing ", "मैं खेलूंगा ");
        map.put("I will be putting ", "मैं डालूंगा ");
        map.put("I will be quarrelling ", "मैं झगड़ा करूंगा ");
        map.put("I will be remembering ", "मुझे याद रहेगा ");
        map.put("I will be reaching ", "मैं पहुंच जाऊंगा ");
        map.put("I will be raining ", "मेरी बारिश होगी ");
        map.put("I will be reading ", "मैं पढ़ूंगा ");
        map.put("I will be riding ", "मैं सवारी कर रहा हूँ ");
        map.put("I will be ringing ", "मैं बज रहा हूँ ");
        map.put("I will be rising ", "मैं उठ रहा हूँ ");
        map.put("I will be running ", "मैं दौड़ता रहूँगा ");
        map.put("I will be saying ", "मैं कह रहा हूँ ");
        map.put("I will be selling ", "मैं बेचूंगा ");
        map.put("I will be seeing ", "मैं देख रहा हूँ ");
        map.put("I will be sending ", "मैं भेजूंगा ");
        map.put("I will be shaking ", "मैं हिल जाऊंगा ");
        map.put("I will be shining ", "मैं चमक रहा हूँ ");
        map.put("I will be shooting ", "मैं शूटिंग करूंगा ");
        map.put("I will be showing ", "मैं दिखाऊंगा ");
        map.put("I will be shutting ", "मैं बंद हो जाऊंगा ");
        map.put("I will be singing ", "मैं गा रहा हूँ ");
        map.put("I will be sinking ", "मैं डूब जाऊंगा ");
        map.put("I will be sleeping ", "मैं सो रहा हूँ ");
        map.put("I will be smelling ", "मुझे महक आ रही होगी ");
        map.put("I will be speaking ", "मैं बोल रहा हूँ ");
        map.put("I will be spending ", "मैं खर्च करूंगा ");
        map.put("I will be spoilt", "मैं खराब हो जाऊंगा");
        map.put("I will be standing ", "मैं खड़ा रहूंगा ");
        map.put("I will be stealing ", "मैं चोरी कर रहा हूँ ");
        map.put("I will be starting ", "मैं शुरू करूंगा ");
        map.put("I will be staying ", "मैं रहूँगा ");
        map.put("I will be studying ", "मैं पढ़ाई करूंगा ");
        map.put("I will be taking ", "मैं ले जाऊंगा ");
        map.put("I will be swimming ", "मैं तैराकी करूंगा ");
        map.put("I will be talking ", "मैं बात कर रहा हूँ ");
        map.put("I will be teaching ", "मैं पढ़ाता रहूँगा ");
        map.put("I will be tearing ", "मैं फाड़ रहा हूँ ");
        map.put("I will be telling ", "मैं बता रहा हूँ ");
        map.put("I will be thanking ", "मैं शुक्रिया अदा करूंगा ");
        map.put("I will be thinking ", "मैं सोच रहा हूँ ");
        map.put("I will be throwing ", "मैं फेंक रहा हूँ ");
        map.put("I will be trying ", "मैं कोशिश कर रहा हूँ ");
        map.put("I will be understanding ", "मैं समझ जाऊंगा ");
        map.put("I will be using ", "मैं उपयोग करूँगा ");
        map.put("I will be walking ", "मैं चलूंगा ");
        map.put("I will be wanting ", "मैं चाहूँगा ");
        map.put("I will be washing ", "मैं धो रहा हूँ ");
        map.put("I will be weeping ", "मैं रो रहा हूँ ");
        map.put("I will be wearing ", "मैं पहनूंगा ");
        map.put("I will be winning ", "मैं जीतूंगा ");
        map.put("I will be working ", "मैं काम करूंगा ");
        map.put("I will be writing ", "मैं लिखूंगा ");

        return map;
    }
    private static Map<String, String> Nine() {
        HashMap<String,String>map = new HashMap<>();
        map.put(" I will abuse ", "मैं गाली दूंगा ");
        map.put(" I will advise", "मैं सलाह दूंगा");
        map.put(" I will ansI wer ", "मैं जवाब दूंगा ");
        map.put(" I will arise ", "मैं उठूंगा ");
        map.put(" I will arrive ", "मैं आऊंगा ");
        map.put(" I will ask ", "मैं पूछूंगा ");
        map.put(" I will aI wake ", "मैं जाग जाऊंगा ");
        map.put(" I will become ", "मैं बन जाऊंगा ");
        map.put(" I will beat ", "मैं हरा दूंगा ");
        map.put(" I will bear ", "मैं सहन करूंगा ");
        map.put(" I will beg ", "मैं भीख माँगूँगा ");
        map.put(" I will begin ", "मैं शुरू करूंगा ");
        map.put(" I will bite", "मैं काटूंगा");
        map.put(" I will bind ", "मैं बाँध लूँगा ");
        map.put(" I will bless", "मैं आशीष दूंगा");
        map.put(" I will break ", "मैं टूट जाऊंगा ");
        map.put(" I will bloI w ", "मैं उड़ जाऊंगा ");
        map.put(" I will bring ", "मैं लाऊंगा ");
        map.put(" I will build ", "मैं निर्माण करूंगा ");
        map.put(" I will burn ", "मैं जलाऊंगा ");
        map.put(" I will buy ", "मैं खरीदूंगा ");
        map.put(" I will call ", "मैं कॉल करूंगा ");
        map.put(" I will carry ", "मैं ले जाऊंगा ");
        map.put(" I will catch ", "मैं पकड़ लूंगा ");
        map.put(" I will cheat ", "मैं धोखा दूंगा ");
        map.put(" I will choose ", "मैं चुनूंगा ");
        map.put(" I will clean ", "मैं साफ करूँगा ");
        map.put(" I will close ", "मैं बंद कर दूँगा ");
        map.put(" I will climb  ", "मैं चढ़ जाऊंगा  ");
        map.put(" I will cook ", "मैं खाना बनाउंगा ");
        map.put(" I will come ", "मैं आऊंगा ");
        map.put(" I will creep ", "मैं रेंगूंगा ");
        map.put(" I will cry ", "मैं रोऊंगा ");
        map.put(" I will cut ", "मैं कट जाऊंगा ");
        map.put(" I will deal ", "मैं सौदा करूंगा ");
        map.put(" I will die ", "मैं मर जाऊंगा ");
        map.put(" I will dance ", "मैं नाचता हूँ ");
        map.put(" I will draI w ", "मैं ड्रॉ करूंगा ");
        map.put(" I will dig ", "मैं खुदाई करूंगा ");
        map.put(" I will do ", "मैं करूँगा ");
        map.put(" I will dream ", "मैं सपना देखूंगा ");
        map.put(" I will drive ", "मैं ड्राइव करूंगा ");
        map.put(" I will drop ", "मैं छोड़ दूँगा ");
        map.put(" I will dry ", "मैं सूख जाऊंगा ");
        map.put(" I will eat ", "मैं खाऊंगा ");
        map.put(" I will elect", "मैं चुनाव करूंगा");
        map.put(" I will fall ", "मैं गिर जाऊंगा ");
        map.put(" I will enter ", "मैं प्रवेश करूंगा ");
        map.put(" I will feed ", "मैं खिलाऊंगा ");
        map.put(" I will feel  ", "मैं महसूस करूंगा  ");
        map.put(" I will fight ", "मैं लड़ूंगा ");
        map.put(" I will find ", "मुझे मिल जाएगा ");
        map.put(" I will flee ", "मैं भाग जाऊंगा ");
        map.put(" I will fly  ", "मैं उड़ जाऊंगा  ");
        map.put(" I will forget ", "मैं भूल जाऊंगा ");
        map.put(" I will fry ", "मैं भूनूंगा ");
        map.put(" I will get  ", "मुझे मिल जाएगा  ");
        map.put(" I will give ", "मैं दूँगा ");
        map.put(" I will go ", "मैं जाऊंगा ");
        map.put(" I will groI w", "मैं बढ़ूंगा");
        map.put(" I will hang ", "मैं लटक जाऊंगा ");
        map.put(" I will hear ", "मैं सुनूंगा ");
        map.put(" I will help ", "मैं मदद करूंगा ");
        map.put(" I will hide ", "मैं छिपाऊंगा ");
        map.put(" I will hit ", "मैं मारूंगा ");
        map.put(" I will hold ", "मैं पकड़ लूंगा ");
        map.put(" I will hope ", "मैं आशा करता हूँ ");
        map.put(" I will hurt ", "मैं चोट पहुँचाऊंगा ");
        map.put(" I will jump ", "मैं कूदूंगा ");
        map.put(" I will keep ", "मैं रखूंगा ");
        map.put(" I will kill ", "मैं मार डालूंगा ");
        map.put(" I will knoI w ", "मुझे पता चल जाएगा ");
        map.put(" I will laugh ", "मैं हंसूंगा ");
        map.put(" I will lead ", "मैं नेतृत्व करूंगा ");
        map.put(" I will leap ", "मैं छलांग लगाऊंगा ");
        map.put(" I will learn ", "मैं सीखूंगा ");
        map.put(" I will leave ", "मैं छोड़ दूँगा ");
        map.put(" I will lend ", "मैं उधार दूंगा ");
        map.put(" I will live ", "मैं जीवित रहूँगा ");
        map.put(" I will look ", "मैं देखूंगा ");
        map.put(" I will lose ", "मैं हार जाऊंगा ");
        map.put(" I will love ", "मैं प्यार करूंगा ");
        map.put(" I will make ", "मैं बनाउंगा ");
        map.put(" I will marry ", "मैं शादी करूंगा ");
        map.put(" I will meet ", "मैं मिलूंगा ");
        map.put(" I will mistake ", "मैं गलती करूँगा ");
        map.put(" I will open ", "मैं खुलूंगा ");
        map.put(" I will pay  ", "मैं भुगतान करूंगा  ");
        map.put(" I will play ", "मैं खेलूंगा ");
        map.put(" I will put ", "मैं रखूंगा ");
        map.put(" I will quarrel ", "मैं झगड़ा करूंगा ");
        map.put(" I will rain ", "मैं बारिश करूँगा ");
        map.put(" I will reach ", "मैं पहुंच जाऊंगा ");
        map.put(" I will read", "मैं पढ़ूंगा");
        map.put(" I will ride ", "मैं सवारी करूंगा ");
        map.put(" I will ring ", "मैं रिंग करूंगा ");
        map.put(" I will remember  ", "मुझे याद होगा  ");
        map.put(" I will run  ", "मैं दौड़ूंगा  ");
        map.put(" I will rise  ", "मैं उठूंगा  ");
        map.put(" I will see ", "मैं देखूंगा ");
        map.put(" I will say ", "मैं कहूँगा ");
        map.put(" I will sell ", "मैं बेचूंगा ");
        map.put(" I will send ", "मैं भेजूंगा ");
        map.put(" I will shine ", "मैं चमकेगा ");
        map.put(" I will shake ", "मैं हिलाऊंगा ");
        map.put(" I will shoI w ", "मैं दिखाऊंगा ");
        map.put(" I will shoot ", "मैं शूट करूंगा ");
        map.put(" I will shut  ", "मैं बंद कर दूँगा  ");
        map.put(" I will sing ", "मैं गाऊंगा ");
        map.put(" I will sink ", "मैं डूब जाऊंगा ");
        map.put(" I will sleep ", "मैं सो जाऊंगा ");
        map.put(" I will smell ", "मैं सूंघूँगा ");
        map.put(" I will speak ", "मैं बोलूंगा ");
        map.put(" I will spend", "मैं खर्च करूंगा");
        map.put(" I will spoil", "मैं खराब करूंगा");
        map.put(" I will stand", "मैं खड़ा रहूँगा");
        map.put(" I will start ", "मैं शुरू करूँगा ");
        map.put(" I will stay ", "मैं रहूँगा ");
        map.put(" I will sI wim ", "मैं तैर जाऊंगा ");
        map.put(" I will steal ", "मैं चोरी करूंगा ");
        map.put(" I will study ", "मैं पढ़ूंगा ");
        map.put(" I will take ", "मैं लूंगा ");
        map.put(" I will talk ", "मैं बात करूंगा ");
        map.put(" I will teach ", "मैं सिखाऊंगा ");
        map.put(" I will tear ", "मैं आंसू बहाऊंगा ");
        map.put(" I will throI w ", "मैं फेंक दूँगा ");
        map.put(" I will tell ", "मैं बताऊंगा ");
        map.put(" I will thank", "मैं शुक्रिया अदा करूंगा");
        map.put(" I will try ", "मैं कोशिश करूंगा ");
        map.put(" I will think ", "मैं सोचूंगा ");
        map.put(" I will understand ", "मैं समझ जाऊंगा ");
        map.put(" I will use ", "मैं उपयोग करूँगा ");
        map.put(" I will I walk", "मैं चलूंगा");
        map.put(" I will I want ", "मैं चाहूँगा ");
        map.put(" I will I wash ", "मैं धोऊंगा ");
        map.put(" I will I wear ", "मैं पहनूंगा ");
        map.put(" I will I weep", "मैं रोऊंगा");
        map.put(" I will I win ", "मैं जीतूंगा ");
        map.put(" I will I write ", "मैं लिखूंगा ");
        map.put(" I will I work ", "मैं काम करूंगा ");
        return map;
    }
    private static Map<String, String> Eight() {
        HashMap<String,String>map = new HashMap<>();
        map.put("I had been abusing ", "मैं गाली दे रहा था ");
        map.put("I had been advising ", "मैं सलाह दे रहा था ");
        map.put("I had been answering ", "मैं जवाब दे रहा था ");
        map.put("I had been arising ", "मैं उठ रहा था ");
        map.put("I had been arriving ", "मैं आ रहा था ");
        map.put("I had been asking ", "मैं पूछ रहा था ");
        map.put("I had been awaking ", "मैं जाग रहा था ");
        map.put("I had been bearing ", "मैं सहन कर रहा था ");
        map.put("I had been beating ", "मैं पिटाई कर रहा था ");
        map.put("I had been undefined", "मैं अपरिभाषित हो गया था");
        map.put("I had been becoming ", "मैं बन रहा था ");
        map.put("I had been begging ", "मैं भीख माँग रहा था ");
        map.put("I had been beginning ", "मैं शुरुआत कर रहा था ");
        map.put("I had been binding ", "मैं बाध्यकारी था ");
        map.put("I had been biting ", "मैं काट रहा था ");
        map.put("I had been blessing ", "मैं आशीष रहा था ");
        map.put("I had been blowing ", "मैं उड़ रहा था ");
        map.put("I had been breaking ", "मैं तोड़ रहा था ");
        map.put("I had been bringing ", "मैं ला रहा था ");
        map.put("I had been building ", "मैं निर्माण कर रहा था ");
        map.put("I had been buying ", "मैं खरीद रहा था ");
        map.put("I had been burning ", "मैं जल रहा था ");
        map.put("I had been calling ", "मैं फोन कर रहा था ");
        map.put("I had been carrying ", "मैं ले जा रहा था ");
        map.put("I had been catching ", "मैं पकड़ रहा था ");
        map.put("I had been choosing ", "मैं चुन रहा था ");
        map.put("I had been climbing ", "मैं चढ़ रहा था ");
        map.put("I had been cheating ", "मैं धोखा दे रहा था ");
        map.put("I had been cleaning ", "मैं सफाई कर रहा था ");
        map.put("I had been closing ", "मैं बंद हो रहा था ");
        map.put("I had been coming ", "मैं आ रहा था ");
        map.put("I had been cooking ", "मैं खाना बना रहा था ");
        map.put("I had been crying ", "मैं रो रहा था ");
        map.put("I had been creeping ", "मैं रेंग रहा था ");
        map.put("I had been cutting ", "मैं काट रहा था ");
        map.put("I had been dancing ", "मैं नाच रहा था ");
        map.put("I had been dealing ", "मैं काम कर रहा था ");
        map.put("I had been digging ", "मैं खुदाई कर रहा था ");
        map.put("I had been doing ", "मैं कर रहा था ");
        map.put("I had been dying ", "मैं मर रहा था ");
        map.put("I had been drawing ", "मैं ड्राइंग कर रहा था ");
        map.put("I had been dreaming ", "मैं सपना देख रहा था ");
        map.put("I had been drinking ", "मैं शराब पी रहा था ");
        map.put("I had been dropping ", "मैं गिर रहा था ");
        map.put("I had been drying ", "मैं सूख रहा था ");
        map.put("I had been driving ", "मैं गाड़ी चला रहा था ");
        map.put("I had been eating ", "मैं खा रहा था ");
        map.put("I had been electing ", "मैं चुनाव कर रहा था ");
        map.put("I had been entering ", "मैं प्रवेश कर रहा था ");
        map.put("I had been falling ", "मैं गिर रहा था ");
        map.put("I had been feeding ", "मैं दूध पिला रहा था ");
        map.put("I had been fighting ", "मैं लड़ रहा था ");
        map.put("I had been feeling ", "मैं महसूस कर रहा था ");
        map.put("I had been finding ", "मैं खोज रहा था ");
        map.put("I had been fleeing ", "मैं भाग रहा था ");
        map.put("I had been flying ", "मैं उड़ रहा था ");
        map.put("I had been forgetting ", "मैं भूल गया था ");
        map.put("I had been frying ", "मैं तलने गया था ");
        map.put("I had been giving ", "मैं दे रहा था ");
        map.put("I had been getting ", "मैं मिल रहा था ");
        map.put("I had been going ", "मैं जा रहा था ");
        map.put("I had been growing ", "मैं बढ़ रहा था ");
        map.put("I had been hanging ", "मैं लटक रहा था ");
        map.put("I had been hearing ", "मैं सुन रहा था ");
        map.put("I had been helping ", "मैं मदद कर रहा था ");
        map.put("I had been hiding ", "मैं छिप रहा था ");
        map.put("I had been hitting ", "मैं मार रहा था ");
        map.put("I had been hoping ", "मैं उम्मीद कर रहा था ");
        map.put("I had been holding ", "मैं पकड़ रहा था ");
        map.put("I had been hurting ", "मैं चोट पहुँचा रहा था ");
        map.put("I had been jumping ", "मैं कूद रहा था ");
        map.put("I had been keeping ", "मैं कीपिंग कर रहा था ");
        map.put("I had been killing ", "मैं मार रहा था ");
        map.put("I had been knowing ", "मैं जान रहा था ");
        map.put("I had been laughing ", "मैं हँस रहा था ");
        map.put("I had been leading ", "मैं अगुवाई कर रहा था ");
        map.put("I had been learning ", "मैं सीख रहा था ");
        map.put("I had been leaving ", "मैं जा रहा था ");
        map.put("I had been lending ", "मैं उधार दे रहा था ");
        map.put("I had been leaping ", "मैं छलांग लगा रहा था ");
        map.put("I had been living ", "मैं जी रहा था ");
        map.put("I had been looking ", "मैं देख रहा था ");
        map.put("I had been losing ", "मैं हार गया था ");
        map.put("I had been loving ", "मैं प्यार कर रहा था ");
        map.put("I had been making ", "मैं बना रहा था ");
        map.put("I had been marrying ", "मैं शादी कर रहा था ");
        map.put("I had been meeting ", "मैं मिल रहा था ");
        map.put("I had been mistaking ", "मैं गलती कर रहा था ");
        map.put("I had been opening ", "मैं खोल रहा था ");
        map.put("I had been playing ", "मैं खेल रहा था ");
        map.put("I had been paying ", "मैं भुगतान कर रहा था ");
        map.put("I had been putting ", "मैं डाल रहा था ");
        map.put("I had been quarrelling ", "मैं झगड़ा कर रहा था ");
        map.put("I had been reaching ", "मैं पहुंच रहा था ");
        map.put("I had been raining ", "बारिश हो रही थी ");
        map.put("I had been reading ", "मैं पढ़ रहा था ");
        map.put("I had been remembering ", "मुझे याद आ रहा था ");
        map.put("I had been riding ", "मैं सवारी कर रहा था ");
        map.put("I had been ringing ", "मैं बज रहा था ");
        map.put("I had been rising ", "मैं उठ रहा था ");
        map.put("I had been running ", "मैं दौड़ रहा था ");
        map.put("I had been saying ", "मैं कह रहा था ");
        map.put("I had been seeing ", "मैं देख रहा था ");
        map.put("I had been selling ", "मैं बेच रहा था ");
        map.put("I had been sending ", "मैं भेज रहा था ");
        map.put("I had been shaking ", "मैं हिल रहा था ");
        map.put("I had been shooting ", "मैं शूटिंग कर रहा था ");
        map.put("I had been showing ", "मैं दिखा रहा था ");
        map.put("I had been shining ", "मैं चमक रहा था ");
        map.put("I had been shutting ", "मैं बंद कर रहा था ");
        map.put("I had been singing ", "मैं गा रहा था ");
        map.put("I had been speaking ", "मैं बोल रहा था ");
        map.put("I had been sinking ", "मैं डूब रहा था ");
        map.put("I had been spending ", "मैं खर्च कर रहा था ");
        map.put("I had been sleeping ", "मैं सो रहा था ");
        map.put("I had been spoilt", "मैं खराब हो गया था");
        map.put("I had been smelling ", "मुझे महक आ रही थी ");
        map.put("I had been standing ", "मैं खड़ा था ");
        map.put("I had been starting ", "मैं शुरू कर रहा था ");
        map.put("I had been staying ", "मैं ठहर गया था ");
        map.put("I had been stealing ", "मैं चोरी कर रहा था ");
        map.put("I had been studying ", "मैं पढ़ाई कर रहा था ");
        map.put("I had been swimming ", "मैं तैर रहा था ");
        map.put("I had been taking ", "मैं ले रहा था ");
        map.put("I had been talking ", "मैं बात कर रहा था ");
        map.put("I had been teaching ", "मैं पढ़ा रहा था ");
        map.put("I had been tearing ", "मैं फाड़ रहा था ");
        map.put("I had been thinking ", "मैं सोच रहा था ");
        map.put("I had been thanking ", "मैं शुक्रिया अदा कर रहा था ");
        map.put("I had been telling ", "मैं बता रहा था ");
        map.put("I had been throwing ", "मैं फेंक रहा था ");
        map.put("I had been trying ", "मैं कोशिश कर रहा था ");
        map.put("I had been understanding ", "मैं समझ रहा था ");
        map.put("I had been using ", "मैं उपयोग कर रहा था ");
        map.put("I had been walking ", "मैं चल रहा था ");
        map.put("I had been wanting ", "मैं चाह रहा था ");
        map.put("I had been washing ", "मैं धो रहा था ");
        map.put("I had been weeping ", "मैं रो रहा था ");
        map.put("I had been wearing ", "मैंने पहना था ");
        map.put("I had been winning ", "मैं जीत रहा था ");
        map.put("I had been writing ", "मैं लिख रहा था ");
        map.put("I had been working ", "मैं काम कर रहा था ");

        return map;
    }
    private static Map<String, String> Seven() {
        HashMap<String,String>map = new HashMap<>();
        map.put("I had abused ", "मैंने गाली दी थी ");
        map.put("I had advised ", "मैंने सलाह दी थी ");
        map.put("I had answered ", "मैंने जवाब दिया था ");
        map.put("I had arisen ", "मैं पैदा हुआ था ");
        map.put("I had arrived ", "मैं आ गया था ");
        map.put("I had asked ", "मैंने पूछा था ");
        map.put("I had awoken ", "मैं जाग गया था ");
        map.put("I had beaten ", "मैंने पीटा था ");
        map.put("I had borne ", "मैंने जन्म लिया था ");
        map.put("I had undefined", "मैंने अपरिभाषित किया था");
        map.put("I had begged ", "मैंने भीख माँगी थी ");
        map.put("I had become ", "मैं बन गया था ");
        map.put("I had begun ", "मैंने शुरू किया था ");
        map.put("I had bound ", "मैंने बाउंड किया था ");
        map.put("I had bitten ", "मैंने काट लिया था ");
        map.put("I had blessed ", "मैंने आशीर्वाद दिया था ");
        map.put("I had blown ", "मैंने उड़ा दिया था ");
        map.put("I had broken ", "मैं टूट गया था ");
        map.put("I had brought ", "मैं लाया था ");
        map.put("I had built ", "मैंने बनाया था ");
        map.put("I had burnt ", "मैंने जला दिया था ");
        map.put("I had bought ", "मैंने ख़रीदा था ");
        map.put("I had carried ", "मैंने किया था ");
        map.put("I had called ", "मैंने फोन किया था ");
        map.put("I had caught ", "मैंने पकड़ लिया था ");
        map.put("I had cheated ", "मैंने धोखा दिया था ");
        map.put("I had chosen ", "मैंने चुना था ");
        map.put("I had climbed ", "मैं चढ़ गया था ");
        map.put("I had cleaned ", "मैंने सफाई की थी ");
        map.put("I had closed ", "मैंने बंद कर दिया था ");
        map.put("I had come ", "मैं आया था ");
        map.put("I had cooked ", "मैंने खाना बनाया था ");
        map.put("I had crept ", "मैंने क्रेप किया था ");
        map.put("I had cried ", "मैं रोया था ");
        map.put("I had cut ", "मैंने कट किया था ");
        map.put("I had danced ", "मैंने नृत्य किया था ");
        map.put("I had dealt ", "मैंने निपटाया था ");
        map.put("I had died ", "मैं मर गया था ");
        map.put("I had dug ", "मैंने खोदा था ");
        map.put("I had done ", "मैंने किया था ");
        map.put("I had drawn ", "मैंने ड्रॉ किया था ");
        map.put("I had dreamt ", "मैंने सपना देखा था ");
        map.put("I had driven ", "मैंने ड्राइव किया था ");
        map.put("I had drunk ", "मैंने पिया था ");
        map.put("I had dropped ", "मैंने गिरा दिया था ");
        map.put("I had dried ", "मैं सूख गया था ");
        map.put("I had eaten ", "मैंने खाया था ");
        map.put("I had elected ", "मैंने निर्वाचित किया था ");
        map.put("I had entered ", "मैंने प्रवेश किया था ");
        map.put("I had fed ", "मैंने खिलाया था ");
        map.put("I had felt ", "मैंने महसूस किया था ");
        map.put("I had fallen ", "मैं गिर गया था ");
        map.put("I had fought ", "मैंने लड़ाई लड़ी थी ");
        map.put("I had found ", "मुझे मिल गया था ");
        map.put("I had forgotten ", "मैं भूल गया था ");
        map.put("I had fled ", "मैं भाग गया था ");
        map.put("I had fried ", "मैंने फ्राई किया था ");
        map.put("I had flown ", "मैं उड़ गया था ");
        map.put("I had got ", "मुझे मिल गया था ");
        map.put("I had gone ", "मैं गया था ");
        map.put("I had given ", "मैंने दिया था ");
        map.put("I had hanged ", "मैंने फांसी लगा ली थी ");
        map.put("I had grown ", "मैं बड़ा हो गया था ");
        map.put("I had hung ", "मैंने लटका दिया था ");
        map.put("I had heard ", "मैंने सुना था ");
        map.put("I had helped ", "मैंने मदद की थी ");
        map.put("I had hidden ", "मैंने छिपाया था ");
        map.put("I had hit ", "मैंने मारा था ");
        map.put("I had hoped ", "मुझे उम्मीद थी ");
        map.put("I had held ", "मैंने आयोजित किया था ");
        map.put("I had kept ", "मैंने रखा था ");
        map.put("I had hurt ", "मुझे चोट लगी थी ");
        map.put("I had jumped ", "मैं कूद गया था ");
        map.put("I had known ", "मुझे पता था ");
        map.put("I had killed ", "मैंने मार डाला था ");
        map.put("I had laughed ", "मैं हँसा था ");
        map.put("I had led ", "मैंने नेतृत्व किया था ");
        map.put("I had learnt ", "मैंने सीखा था ");
        map.put("I had leapt ", "मैंने छलांग लगाई थी ");
        map.put("I had left ", "मैंने छोड़ा था ");
        map.put("I had lent ", "मैंने लेंट किया था ");
        map.put("I had lived ", "मैं रहता था ");
        map.put("I had lost ", "मैं हार गया था ");
        map.put("I had made ", "मैंने बनाया था ");
        map.put("I had loved ", "मैंने प्यार किया था ");
        map.put("I had looked ", "मैंने देखा था ");
        map.put("I had met ", "मैं मिला था ");
        map.put("I had married ", "मैंने शादी कर ली थी ");
        map.put("I had mistaken ", "मैंने गलती की थी ");
        map.put("I had opened ", "मैंने खोला था ");
        map.put("I had paid ", "मैंने भुगतान किया था ");
        map.put("I had put ", "मैंने रखा था ");
        map.put("I had quarrelled ", "मैंने झगड़ा किया था ");
        map.put("I had rained ", "मैंने बारिश की थी ");
        map.put("I had reached ", "मैं पहुँच गया था ");
        map.put("I had played ", "मैंने खेला था ");
        map.put("I had read ", "मैंने पढ़ा था ");
        map.put("I had remembered ", "मुझे याद आया था ");
        map.put("I had ridden ", "मैंने सवारी की थी ");
        map.put("I had rung ", "मैंने बजाया था ");
        map.put("I had risen ", "मैं उठ गया था ");
        map.put("I had run ", "मैं भाग गया था ");
        map.put("I had said ", "मैंने कहा था ");
        map.put("I had seen ", "मैंने देखा था ");
        map.put("I had sold ", "मैंने बेचा था ");
        map.put("I had shaken ", "मैं हिल गया था ");
        map.put("I had shone ", "मैं चमक गया था ");
        map.put("I had shot ", "मैंने गोली मार दी थी ");
        map.put("I had shut ", "मैंने बंद कर दिया था ");
        map.put("I had sent ", "मैंने भेजा था ");
        map.put("I had sung ", "मैंने गाया था ");
        map.put("I had shown ", "मैंने दिखाया था ");
        map.put("I had sunk ", "मैं डूब गया था ");
        map.put("I had slept ", "मैं सो गया था ");
        map.put("I had spoken ", "मैंने बात की थी ");
        map.put("I had spent ", "मैंने खर्च किया था ");
        map.put("I had  spoiled ", "मैं खराब हो गया था ");
        map.put("I had stood ", "मैं खड़ा था ");
        map.put("I had started ", "मैंने शुरू किया था ");
        map.put("I had stayed ", "मैं रुका था ");
        map.put("I had stolen ", "मैंने चोरी की थी ");
        map.put("I had studied ", "मैंने पढ़ाई की थी ");
        map.put("I had swum ", "मैंने तैर लिया था ");
        map.put("I had taken ", "मैंने लिया था ");
        map.put("I had talked ", "मैंने बात की थी ");
        map.put("I had taught ", "मैंने पढ़ाया था ");
        map.put("I had torn ", "मैंने फाड़ा था ");
        map.put("I had told ", "मैंने बताया था ");
        map.put("I had thanked ", "मैंने धन्यवाद दिया था ");
        map.put("I had smelt ", "मैंने गलाया था ");
        map.put("I had thrown ", "मैंने फेंक दिया था ");
        map.put("I had understood ", "मैं समझ गया था ");
        map.put("I had thought ", "मैंने सोचा था ");
        map.put("I had tried ", "मैंने कोशिश की थी ");
        map.put("I had used ", "मैंने इस्तेमाल किया था ");
        map.put("I had wanted ", "मैं चाहता था ");
        map.put("I had washed ", "मैंने धोया था ");
        map.put("I had worn ", "मैंने पहना था ");
        map.put("I had wept ", "मैं रोया था ");
        map.put("I had won ", "मैं जीता था ");
        map.put("I had written ", "मैंने लिखा था ");
        map.put("I had worked ", "मैंने काम किया था ");
        map.put("I had walked ", "मैं चला गया था ");
        return map;
    }
    private static Map<String, String> Six() {
        HashMap<String,String>map = new HashMap<>();
        map.put("I was abusing ", "मैं गाली दे रहा था ");
        map.put("I was advising ", "मैं सलाह दे रहा था ");
        map.put("I was answering ", "मैं जवाब दे रहा था ");
        map.put("I was arising ", "मैं पैदा हो रहा था ");
        map.put("I was arriving ", "मैं आ रहा था ");
        map.put("I was asking ", "मैं पूछ रहा था ");
        map.put("I was awaking ", "मैं जाग रहा था ");
        map.put("I was beating ", "मैं पिटाई कर रहा था ");
        map.put("I was undefined", "मैं अपरिभाषित था");
        map.put("I was bearing ", "मैं सहन कर रहा था ");
        map.put("I was becoming ", "मैं बन रहा था ");
        map.put("I was begging ", "मैं भीख मांग रहा था ");
        map.put("I was beginning ", "मैं शुरुआत कर रहा था ");
        map.put("I was biting ", "मैं काट रहा था ");
        map.put("I was binding ", "मैं बाध्यकारी था ");
        map.put("I was blessing ", "मैं आशीष दे रहा था ");
        map.put("I was blowing ", "मैं उड़ रहा था ");
        map.put("I was breaking ", "मैं टूट रहा था ");
        map.put("I was bringing ", "मैं ला रहा था ");
        map.put("I was building ", "मैं निर्माण कर रहा था ");
        map.put("I was buying ", "मैं खरीद रहा था ");
        map.put("I was burning ", "मैं जल रहा था ");
        map.put("I was calling ", "मैं बुला रहा था ");
        map.put("I was carrying ", "मैं ले जा रहा था ");
        map.put("I was catching ", "मैं पकड़ रहा था ");
        map.put("I was cheating ", "मैं धोखा दे रहा था ");
        map.put("I was choosing ", "मैं चुन रहा था ");
        map.put("I was cleaning ", "मैं सफाई कर रहा था ");
        map.put("I was climbing ", "मैं चढ़ रहा था ");
        map.put("I was closing ", "मैं बंद हो रहा था ");
        map.put("I was cooking ", "मैं खाना बना रहा था ");
        map.put("I was creeping ", "मैं रेंग रहा था ");
        map.put("I was coming ", "मैं आ रहा था ");
        map.put("I was crying ", "मैं रो रहा था ");
        map.put("I was cutting ", "मैं काट रहा था ");
        map.put("I was dancing ", "मैं नाच रहा था ");
        map.put("I was dealing ", "मैं काम कर रहा था ");
        map.put("I was digging ", "मैं खुदाई कर रहा था ");
        map.put("I was dying ", "मैं मर रहा था ");
        map.put("I was drawing ", "मैं ड्राइंग कर रहा था ");
        map.put("I was doing ", "मैं कर रहा था ");
        map.put("I was drinking ", "मैं पी रहा था ");
        map.put("I was dreaming ", "मैं सपना देख रहा था ");
        map.put("I was driving ", "मैं गाड़ी चला रहा था ");
        map.put("I was dropping ", "मैं गिर रहा था ");
        map.put("I was drying ", "मैं सूख रहा था ");
        map.put("I was eating ", "मैं खा रहा था ");
        map.put("I was electing ", "मैं चयन कर रहा था ");
        map.put("I was entering ", "मैं प्रवेश कर रहा था ");
        map.put("I was falling ", "मैं गिर रहा था ");
        map.put("I was feeding ", "मैं खिला रहा था ");
        map.put("I was feeling ", "मैं महसूस कर रहा था ");
        map.put("I was fighting ", "मैं लड़ रहा था ");
        map.put("I was finding ", "मुझे मिल रहा था ");
        map.put("I was flying ", "मैं उड़ रहा था ");
        map.put("I was fleeing ", "मैं भाग रहा था ");
        map.put("I was forgetting ", "मैं भूल रहा था ");
        map.put("I was frying ", "मैं तलने लगा था ");
        map.put("I was getting ", "मुझे मिल रहा था ");
        map.put("I was going ", "मैं जा रहा था ");
        map.put("I was growing ", "मैं बढ़ रहा था ");
        map.put("I was giving ", "मैं दे रहा था ");
        map.put("I was hanging ", "मैं लटक रहा था ");
        map.put("I was hearing ", "मैं सुन रहा था ");
        map.put("I was helping ", "मैं मदद कर रहा था ");
        map.put("I was hiding ", "मैं छिपा रहा था ");
        map.put("I was hitting ", "मैं सिट रहा था ");
        map.put("I was hoping ", "मैं उम्मीद कर रहा था ");
        map.put("I was holding ", "मैं पकड़ रहा था ");
        map.put("I was hurting ", "मुझे चोट लगी थी ");
        map.put("I was jumping ", "मैं कूद रहा था ");
        map.put("I was keeping ", "मैं रख रहा था ");
        map.put("I was killing ", "मैं मार रहा था ");
        map.put("I was knowing ", "मैं जान रहा था ");
        map.put("I was laughing ", "मैं हँस रहा था ");
        map.put("I was leaping ", "मैं छलांग लगा रहा था ");
        map.put("I was learning ", "मैं सीख रहा था ");
        map.put("I was leading ", "मैं अग्रणी था ");
        map.put("I was leaving ", "मैं जा रहा था ");
        map.put("I was lending ", "मैं उधार दे रहा था ");
        map.put("I was living ", "मैं जी रहा था ");
        map.put("I was looking ", "मैं देख रहा था ");
        map.put("I was loving ", "मैं प्यार कर रहा था ");
        map.put("I was losing ", "मैं हार रहा था ");
        map.put("I was making ", "मैं बना रहा था ");
        map.put("I was marrying ", "मैं शादी कर रहा था ");
        map.put("I was meeting ", "मैं मिल रहा था ");
        map.put("I was mistaking ", "मैं गलती कर रहा था ");
        map.put("I was opening ", "मैं खोल रहा था ");
        map.put("I was paying ", "मैं भुगतान कर रहा था ");
        map.put("I was playing ", "मैं खेल रहा था ");
        map.put("I was putting ", "मैं लगा रहा था ");
        map.put("I was quarrelling ", "मैं झगड़ा कर रहा था ");
        map.put("I was raining ", "मैं बारिश कर रहा था ");
        map.put("I was reaching ", "मैं पहुँच रहा था ");
        map.put("I was reading ", "मैं पढ़ रहा था ");
        map.put("I was remembering ", "मैं याद कर रहा था ");
        map.put("I was rising ", "मैं उठ रहा था ");
        map.put("I was running ", "मैं दौड़ रहा था ");
        map.put("I was saying ", "मैं कह रहा था ");
        map.put("I was ringing ", "मैं बज रहा था ");
        map.put("I was riding ", "मैं सवारी कर रहा था ");
        map.put("I was seeing ", "मैं देख रहा था ");
        map.put("I was sending ", "मैं भेज रहा था ");
        map.put("I was selling ", "मैं बेच रहा था ");
        map.put("I was shining ", "मैं चमक रहा था ");
        map.put("I was shaking ", "मैं हिल रहा था ");
        map.put("I was shooting ", "मैं शूटिंग कर रहा था ");
        map.put("I was showing ", "मैं दिखा रहा था ");
        map.put("I was shutting ", "मैं बंद कर रहा था ");
        map.put("I was sinking ", "मैं डूब रहा था ");
        map.put("I was singing ", "मैं गा रहा था ");
        map.put("I was smelling ", "मैं सूँघ रहा था ");
        map.put("I was sleeping ", "मैं सो रहा था ");
        map.put("I was speaking ", "मैं बोल रहा था ");
        map.put("I was spending ", "मैं खर्च कर रहा था ");
        map.put("I was spoilt", "मैं खराब हो गया था");
        map.put("I was standing ", "मैं खड़ा था ");
        map.put("I was staying ", "मैं रह रहा था ");
        map.put("I was starting ", "मैं शुरू कर रहा था ");
        map.put("I was stealing ", "मैं चोरी कर रहा था ");
        map.put("I was studying ", "मैं पढ़ रहा था ");
        map.put("I was swimming ", "मैं तैर रहा था ");
        map.put("I was taking ", "मैं ले रहा था ");
        map.put("I was talking ", "मैं बात कर रहा था ");
        map.put("I was teaching ", "मैं सिखा रहा था ");
        map.put("I was tearing ", "मैं बर्बाद कर रहा हूँ ");
        map.put("I was telling ", "मैं बर्बाद कर रहा हूँ ");
        map.put("I was thanking ", "मैं धन्यवाद कर रहा था ");
        map.put("I was thinking ", "मैं सोच रहा था ");
        map.put("I was throwing ", "मैं फेंक रहा था ");
        map.put("I was trying ", "मैं कोशिश कर रहा था ");
        map.put("I was understanding ", "मैं समझ रहा था ");
        map.put("I was using ", "मैं इस्तेमाल कर रहा था ");
        map.put("I was walking ", "मैं चल रहा था ");
        map.put("I was wanting ", "मैं चाह रहा था ");
        map.put("I was was hing ", "मैं धो रहा था ");
        map.put("I was weeping ", "मैं रो रहा था ");
        map.put("I was working ", "मैं काम कर रहा था ");
        map.put("I was winning ", "मैं जीत रहा था ");
        map.put("I was writing ", "मैं लिख रहा था ");
        map.put("I was wearing ", "मैंने पहन रखा था ");
        return map;
    }
    private static Map<String, String> Five() {
        HashMap<String,String>map = new HashMap<>();
        map.put("I abused ", "मैंने गाली दी ");
        map.put("I advised ", "मैंने सलाह दी ");
        map.put("I answered ", "मैंने जवाब दिया ");
        map.put("I arose ", "मैं उठ गया ");
        map.put("I arrived ", "मैं आ गया ");
        map.put("I asked ", "मैंने पूछा ");
        map.put("I undefined", "मैं अपरिभाषित");
        map.put("I awoke ", "मैं जाग गया ");
        map.put("I bore ", "मैंने बोर किया ");
        map.put("I beat ", "मैंने हराया ");
        map.put("I became ", "मैं बन गया ");
        map.put("I begged ", "मैंने भीख माँगी ");
        map.put("I began ", "मैंने शुरू किया ");
        map.put("I bound ", "मैं बाध्य हूँ ");
        map.put("I bit ", "मैं थोड़ा ");
        map.put("I blessed ", "मैंने आशीर्वाद दिया ");
        map.put("I broke ", "मैंने तोड़ दिया ");
        map.put("I blew ", "मैंने विस्फोट से उड़ा दिया ");
        map.put("I brought ", "मैं लाया ");
        map.put("I built ", "मैंने बनाया ");
        map.put("I burnt ", "मैंने जला दिया ");
        map.put("I bought ", "मैंने खरीदा ");
        map.put("I called ", "मैंने फोन किया ");
        map.put("I carried ", "मैंने किया ");
        map.put("I caught ", "मैंने पकड़ा ");
        map.put("I cheated ", "मैंने धोखा दिया ");
        map.put("I chose ", "मैंने चुना ");
        map.put("I cleaned ", "मैंने सफाई की ");
        map.put("I closed ", "मैंने बंद कर दिया ");
        map.put("I climbed ", "मैं चढ़ गया ");
        map.put("I came ", "मैं आया ");
        map.put("I cooked ", "मैंने पकाया ");
        map.put("I crept ", "मैं crept ");
        map.put("I cut ", "मैंने काट दिया ");
        map.put("I cried ", "मैं रोया ");
        map.put("I danced ", "मैंने नृत्य किया ");
        map.put("I dealt ", "मैंने निपटाया ");
        map.put("I died ", "मैं मर गया ");
        map.put("I did ", "मैंने किया ");
        map.put("I dug ", "मैंने खोदा ");
        map.put("I drew ", "मैंने आकर्षित किया ");
        map.put("I dreamt ", "मैंने सपना देखा ");
        map.put("I drank ", "मैंने पिया ");
        map.put("I drove ", "मैंने चलाई ");
        map.put("I dropped ", "मैंने गिरा दिया ");
        map.put("I ate ", "मैंने खा लिया ");
        map.put("I dried ", "मैं सूख गया ");
        map.put("I elected ", "मैंने निर्वाचित किया ");
        map.put("I entered ", "मैंने प्रवेश किया ");
        map.put("I fell ", "मैं गिर गया ");
        map.put("I felt ", "मुझे लगा ");
        map.put("I found ", "मैंने पाया ");
        map.put("I fed ", "मैंने खिलाया ");
        map.put("I fought ", "मैंने लड़ाई लड़ी ");
        map.put("I fled ", "मैं भाग गया ");
        map.put("I forgot ", "मैं भूल गया ");
        map.put("I fried ", "मैंने तला ");
        map.put("I got ", "मुझे मिल गया ");
        map.put("I gave ", "मैंने दिया ");
        map.put("I went ", "मैं गया ");
        map.put("I hanged ", "मैंने फांसी लगा ली ");
        map.put("I hung ", "मैंने लटका दिया ");
        map.put("I flew ", "मैंने उड़ान भरी ");
        map.put("I grew ", "मैं बड़ा हुआ ");
        map.put("I heard ", "मैंने सुना ");
        map.put("I helped ", "मैंने मदद की ");
        map.put("I hid ", "मैंने छुपाया ");
        map.put("I hit ", "मैंने मारा ");
        map.put("I held ", "मैंने आयोजित किया ");
        map.put("I hoped ", "मुझे आशा थी ");
        map.put("I hurt ", "मैंने चोट पहुंचाई ");
        map.put("I jumped ", "मैं कूद गया ");
        map.put("I kept ", "मैंने रखा ");
        map.put("I knew ", "मुझे पता था ");
        map.put("I killed ", "मैंने मार डाला ");
        map.put("I laughed ", "मैं हँसा ");
        map.put("I led ", "मैंने नेतृत्व किया ");
        map.put("I learnt ", "मैंने सीखा ");
        map.put("I leapt ", "मैंने छलांग लगाई ");
        map.put("I lent ", "मैंने उधार दिया ");
        map.put("I left ", "मैंने छोड़ा ");
        map.put("I looked ", "मैंने देखा ");
        map.put("I lost ", "मैं हार गया ");
        map.put("I loved ", "मैं प्यार करता था ");
        map.put("I made ", "मैंने बनाया ");
        map.put("I married ", "मैंने शादी की ");
        map.put("I met ", "मैं मिला ");
        map.put("I opened ", "मैंने खोला ");
        map.put("I paid ", "मैंने भुगतान किया ");
        map.put("I mistook ", "मैंने समझ लिया ");
        map.put("I played ", "मैंने खेला ");
        map.put("I put ", "मैंने रखा ");
        map.put("I quarrelled ", "मैंने झगड़ा किया ");
        map.put("I rained ", "मैंने बारिश की ");
        map.put("I reached ", "मैं पहुँच गया ");
        map.put("I read ", "मैंने पढ़ा ");
        map.put("I lived ", "मैं रहता था ");
        map.put("I remembered ", "मुझे याद आया ");
        map.put("I rode ", "मैं सवार हुआ ");
        map.put("I rang ", "मैंने बजाया ");
        map.put("I rose ", "मैं उठ गया ");
        map.put("I ran ", "मैं भागा ");
        map.put("I said ", "मैंने कहा ");
        map.put("I saw ", "मैंने देखा ");
        map.put("I sold ", "मैंने बेचा ");
        map.put("I sent ", "मैंने भेजा ");
        map.put("I shook ", "मैंने हिला दिया ");
        map.put("I shone ", "मैं चमक गया ");
        map.put("I shut ", "मैंने बंद कर दिया ");
        map.put("I showed ", "मैंने दिखाया ");
        map.put("I sang ", "मैंने गाया ");
        map.put("I sank ", "मैं डूब गया ");
        map.put("I smelt ", "मैं गलाता हूँ ");
        map.put("I shot ", "मैंने गोली मारी ");
        map.put("I slept ", "मैं सो गया ");
        map.put("I spoke ", "मैंने बोला ");
        map.put("I spent ", "मैंने खर्च किया ");
        map.put("I spoilt", "मैं खराब हो गया");
        map.put("I started ", "मैंने शुरू किया ");
        map.put("I stayed ", "मैं रुका ");
        map.put("I stole ", "मैंने चुरा लिया ");
        map.put("I stood ", "मैं खड़ा था ");
        map.put("I studied ", "मैंने पढ़ाई की ");
        map.put("I swam ", "मैं तैर गया ");
        map.put("I talked ", "मैंने बात की ");
        map.put("I took ", "मैंने लिया ");
        map.put("I taught ", "मैंने पढ़ाया ");
        map.put("I tore ", "मैंने फाड़ दिया ");
        map.put("I told ", "मैंने बताया ");
        map.put("I thanked ", "मैंने धन्यवाद दिया ");
        map.put("I thought ", "मैंने सोचा ");
        map.put("I threw ", "मैंने फेंक दिया ");
        map.put("I tried ", "मैंने कोशिश की ");
        map.put("I understood ", "मैं समझ गया ");
        map.put("I used ", "मैंने इस्तेमाल किया ");
        map.put("I walked ", "मैं चला ");
        map.put("I wanted ", "मैं चाहता था ");
        map.put("I washed ", "मैंने धोया ");
        map.put("I wore ", "मैंने पहनी थी ");
        map.put("I wept ", "मैं रोया ");
        map.put("I won ", "मैं जीता ");
        map.put("I worked ", "मैंने काम किया ");
        map.put("I wrote ", "मैंने लिखा ");

        return map;
    }
    private static Map<String, String> Four() {
        HashMap<String,String>map = new HashMap<>();
        map.put("I have been advising ", "मैं सलाह दे रहा हूं ");
        map.put("I have been abusing ", "मैं गाली दे रहा हूं ");
        map.put("I have been asking ", "मैं पूछ रहा हूँ ");
        map.put("I have been arriving ", "मैं आ रहा हूँ ");
        map.put("I have been arising ", "मैं उठ रहा हूँ ");
        map.put("I have been answering ", "मैं जवाब दे रहा हूँ ");
        map.put("I have been bearing ", "मैं सहन कर रहा हूँ ");
        map.put("I have been undefined", "मैं अपरिभाषित हो गया हूँ");
        map.put("I have been becoming ", "मैं बन रहा हूँ ");
        map.put("I have been beating ", "मैं पिटाई कर रहा हूँ ");
        map.put("I have been awaking ", "मैं जाग रहा हूँ ");
        map.put("I have been begging ", "मैं भीख माँग रहा हूँ ");
        map.put("I have been binding ", "मैं बाध्यकारी रहा हूँ ");
        map.put("I have been biting ", "मैं काट रहा हूँ ");
        map.put("I have been blessing ", "मैं आशीष रहा हूँ ");
        map.put("I have been blowing ", "मैं उड़ रहा हूँ ");
        map.put("I have been breaking ", "मैं टूट रहा हूँ ");
        map.put("I have been beginning ", "मैं शुरुआत कर रहा हूँ ");
        map.put("I have been bringing ", "मैं ला रहा हूँ ");
        map.put("I have been buying ", "मैं खरीद रहा हूँ ");
        map.put("I have been building ", "मैं निर्माण कर रहा हूँ ");
        map.put("I have been carrying ", "मैं ले जा रहा हूँ ");
        map.put("I have been catching ", "मैं पकड़ रहा हूँ ");
        map.put("I have been cleaning ", "मैं सफाई कर रहा हूँ ");
        map.put("I have been cheating ", "मैं धोखा दे रहा हूँ ");
        map.put("I have been calling ", "मैं कॉल कर रहा हूँ ");
        map.put("I have been burning ", "मैं जल रहा हूँ ");
        map.put("I have been choosing ", "मैं चुन रहा हूँ ");
        map.put("I have been climbing ", "मैं चढ़ रहा हूँ ");
        map.put("I have been closing ", "मैं बंद हो रहा हूँ ");
        map.put("I have been coming ", "मैं आ रहा हूँ ");
        map.put("I have been crying ", "मैं रो रहा हूँ ");
        map.put("I have been cooking ", "मैं खाना बना रहा हूँ ");
        map.put("I have been creeping ", "मैं रेंग रहा हूँ ");
        map.put("I have been cutting ", "मैं काट रहा हूँ ");
        map.put("I have been dancing ", "मैं नाच रहा हूँ ");
        map.put("I have been dealing ", "मैं काम कर रहा हूँ ");
        map.put("I have been dying ", "मैं मर रहा हूँ ");
        map.put("I have been digging ", "मैं खुदाई कर रहा हूं ");
        map.put("I have been doing ", "मैं कर रहा हूँ ");
        map.put("I have been dreaming ", "मैं सपना देख रहा हूँ ");
        map.put("I have been drawing ", "मैं आरेखण कर रहा हूँ ");
        map.put("I have been dropping ", "मैं गिर रहा हूँ ");
        map.put("I have been drying ", "मैं सूख रहा हूँ ");
        map.put("I have been driving ", "मैं गाड़ी चला रहा हूँ ");
        map.put("I have been drinking ", "मैं पी रहा हूँ ");
        map.put("I have been eating ", "मैं खा रहा हूँ ");
        map.put("I have been electing ", "मैं चुनाव कर रहा हूँ ");
        map.put("I have been falling ", "मैं गिर रहा हूँ ");
        map.put("I have been entering ", "मैं प्रवेश कर रहा हूँ ");
        map.put("I have been feeling ", "मैं महसूस कर रहा हूँ ");
        map.put("I have been fighting ", "मैं लड़ रहा हूँ ");
        map.put("I have been feeding ", "मैं दूध पिला रहा हूँ ");
        map.put("I have been fleeing ", "मैं भाग रहा हूँ ");
        map.put("I have been flying ", "मैं उड़ रहा हूँ ");
        map.put("I have been finding ", "मैं खोज रहा हूँ ");
        map.put("I have been forgetting ", "मैं भूल गया हूँ ");
        map.put("I have been getting ", "मुझे मिल रहा है ");
        map.put("I have been frying ", "मैं तलने गया हूँ ");
        map.put("I have been giving ", "मैं दे रहा हूँ ");
        map.put("I have been going ", "मैं जा रहा हूँ ");
        map.put("I have been growing ", "मैं बढ़ रहा हूँ ");
        map.put("I have been hanging ", "मैं लटक रहा हूँ ");
        map.put("I have been hearing ", "मैं सुन रहा हूँ ");
        map.put("I have been helping ", "मैं मदद कर रहा हूँ ");
        map.put("I have been hiding ", "मैं छिप रहा हूँ ");
        map.put("I have been hitting ", "मैं मार रहा हूँ ");
        map.put("I have been holding ", "मैं पकड़ रहा हूँ ");
        map.put("I have been hoping ", "मैं उम्मीद कर रहा हूँ ");
        map.put("I have been hurting ", "मैं चोट पहुँचा रहा हूँ ");
        map.put("I have been jumping ", "मैं कूद रहा हूँ ");
        map.put("I have been killing ", "मैं मार रहा हूँ ");
        map.put("I have been keeping ", "मैं बीनकीपिंग कर रहा हूं ");
        map.put("I have been leading ", "मैं अग्रणी रहा हूँ ");
        map.put("I have been laughing ", "मैं हँस रहा हूँ ");
        map.put("I have been knowing ", "मैं जानती रही हूँ ");
        map.put("I have been leaping ", "मैं छलांग लगा रहा हूँ ");
        map.put("I have been learning ", "मैं सीख रहा हूँ ");
        map.put("I have been leaving ", "मैं जा रहा हूँ ");
        map.put("I have been lending ", "मैं उधार दे रहा हूँ ");
        map.put("I have been living ", "मैं जी रहा हूँ ");
        map.put("I have been looking ", "मैं देख रहा हूँ ");
        map.put("I have been losing ", "मैं हार रहा हूँ ");
        map.put("I have been loving ", "मैं प्यार करता रहा हूँ ");
        map.put("I have been making ", "मैं बना रहा हूँ ");
        map.put("I have been marrying ", "मैं शादी कर रहा हूँ ");
        map.put("I have been meeting ", "मैं मिल रहा हूँ ");
        map.put("I have been opening ", "मैं खोल रहा हूँ ");
        map.put("I have been mistaking ", "मैं गलती कर रहा हूँ ");
        map.put("I have been paying ", "मैं भुगतान कर रहा हूँ ");
        map.put("I have been putting ", "मैं डाल रहा हूँ ");
        map.put("I have been playing ", "मैं खेल रहा हूँ ");
        map.put("I have been quarrelling ", "मैं झगड़ा कर रहा हूँ ");
        map.put("I have been raining ", "बारिश हो रही है ");
        map.put("I have been reading ", "मैं पढ़ रहा हूँ ");
        map.put("I have been remembering ", "मुझे याद आ रहा है ");
        map.put("I have been riding ", "मैं सवारी कर रहा हूँ ");
        map.put("I have been reaching ", "मैं पहुँच रहा हूँ ");
        map.put("I have been ringing ", "मैं बज रहा हूँ ");
        map.put("I have been rising ", "मैं उठ रहा हूँ ");
        map.put("I have been running ", "मैं दौड़ रहा हूँ ");
        map.put("I have been saying ", "मैं कह रहा हूँ ");
        map.put("I have been seeing ", "मैं देख रहा हूँ ");
        map.put("I have been selling ", "मैं बेच रहा हूँ ");
        map.put("I have been sending ", "मैं भेज रहा हूँ ");
        map.put("I have been shining ", "मैं चमक रहा हूँ ");
        map.put("I have been shaking ", "मैं हिल रहा हूँ ");
        map.put("I have been showing ", "मैं दिखा रहा हूँ ");
        map.put("I have been shooting ", "मैं शूटिंग कर रहा हूँ ");
        map.put("I have been shutting ", "मैं बंद कर रहा हूँ ");
        map.put("I have been singing ", "मैं गा रहा हूँ ");
        map.put("I have been sinking ", "मैं डूब रहा हूँ ");
        map.put("I have been sleeping ", "मैं सो रहा हूँ ");
        map.put("I have been smelling ", "मुझे महक आ रही है ");
        map.put("I have been speaking ", "मैं बोल रहा हूँ ");
        map.put("I have been spoilt", "मैं खराब हो गया हूँ");
        map.put("I have been standing ", "मैं खड़ा रहा हूँ ");
        map.put("I have been spending ", "मैं खर्च कर रहा हूँ ");
        map.put("I have been starting ", "मैं शुरू कर रहा हूँ ");
        map.put("I have been stealing ", "मैं चोरी कर रहा हूँ ");
        map.put("I have been staying ", "मैं रह रहा हूँ ");
        map.put("I have been studying ", "मैं पढ़ाई कर रहा हूँ ");
        map.put("I have been taking ", "मैं ले रहा हूँ ");
        map.put("I have been swimming ", "मैं तैर रहा हूँ ");
        map.put("I have been talking ", "मैं बात कर रहा हूँ ");
        map.put("I have been teaching ", "मैं पढ़ा रहा हूँ ");
        map.put("I have been telling ", "मैं बता रहा हूँ ");
        map.put("I have been tearing ", "मैं फाड़ रहा हूँ ");
        map.put("I have been thanking ", "मैं शुक्रिया अदा कर रहा हूँ ");
        map.put("I have been thinking ", "मैं सोच रहा हूँ ");
        map.put("I have been throwing ", "मैं फेंक रहा हूँ ");
        map.put("I have been understanding ", "मैं समझ रहा हूँ ");
        map.put("I have been trying ", "मैं कोशिश कर रहा हूँ ");
        map.put("I have been using ", "मैं उपयोग कर रहा हूँ ");
        map.put("I have been walking ", "मैं चल रहा हूँ ");
        map.put("I have been wanting ", "मैं चाह रहा हूँ ");
        map.put("I have been washing ", "मैं धोता रहा हूँ ");
        map.put("I have been wearing ", "मैंने पहन रखा है ");
        map.put("I have been weeping ", "मैं रो रहा हूँ ");
        map.put("I have been winning ", "मैं जीत रहा हूँ ");
        map.put("I have been writing ", "मैं लिख रहा हूँ ");
        map.put("I have been working ", "मैं काम कर रहा हूँ");

        return map;
    }
    private static Map<String, String> Three() {
        HashMap<String,String>map = new HashMap<>();
        map.put("I have abused ", "मैंने गाली दी है ");
        map.put("I have advised ", "मैंने सलाह दी है ");
        map.put("I have answered ", "मैंने जवाब दिया है ");
        map.put("I have arisen ", "मैं पैदा हुआ हूँ ");
        map.put("I have arrived ", "मैं आ चुका हूँ ");
        map.put("I have asked ", "मैंने पूछा है ");
        map.put("I have borne ", "मैंने जन्म लिया है ");
        map.put("I have undefined", "मैंने अपरिभाषित किया है");
        map.put("I have beaten ", "मैंने पीटा है ");
        map.put("I have become ", "मैं बन गया हूँ ");
        map.put("I have awoken ", "मैं जाग गया हूँ ");
        map.put("I have begged ", "मैंने भीख माँगी है ");
        map.put("I have begun ", "मैंने शुरू कर दिया है ");
        map.put("I have bound ", "मैंने बाउंड किया है ");
        map.put("I have bitten ", "मैंने काट लिया है ");
        map.put("I have blown ", "मैंने उड़ा दिया है ");
        map.put("I have broken ", "मैं टूट गया हूँ ");
        map.put("I have brought ", "मैं लाया हूँ ");
        map.put("I have built ", "मैंने बनाया है ");
        map.put("I have burnt ", "मैंने जला दिया है ");
        map.put("I have blessed ", "मैंने आशीर्वाद दिया है ");
        map.put("I have bought ", "मैंने ख़रीदा है ");
        map.put("I have called ", "मैंने फोन किया है ");
        map.put("I have caught ", "मैंने पकड़ लिया है ");
        map.put("I have carried ", "मैंने किया है ");
        map.put("I have chosen ", "मैंने चुना है ");
        map.put("I have cheated ", "मैंने धोखा दिया है ");
        map.put("I have climbed ", "मैं चढ़ गया हूँ ");
        map.put("I have cleaned ", "मैंने साफ कर लिया है ");
        map.put("I have cooked ", "मैंने खाना बनाया है ");
        map.put("I have come ", "मैं आया हूँ ");
        map.put("I have closed ", "मैंने बंद कर दिया है ");
        map.put("I have crept ", "मेरे पास क्रेप्ट है ");
        map.put("I have cut ", "मैंने कट किया है ");
        map.put("I have dealt ", "मैंने निपटाया है ");
        map.put("I have danced ", "मैंने नृत्य किया है ");
        map.put("I have dug ", "मैंने खोदा है ");
        map.put("I have died ", "मैं मर चुका हूँ ");
        map.put("I have cried ", "मैं रोया हूँ ");
        map.put("I have done ", "मैंने किया है ");
        map.put("I have drawn ", "मैंने ड्रॉ किया है ");
        map.put("I have dreamt ", "मैंने सपना देखा है ");
        map.put("I have driven ", "मैंने ड्राइव किया है ");
        map.put("I have drunk ", "मैंने शराब पी ली है ");
        map.put("I have dried ", "मैं सूख चुका हूँ ");
        map.put("I have eaten ", "मैंने खा लिया है ");
        map.put("I have dropped ", "मैंने गिरा दिया है ");
        map.put("I have elected ", "मैंने चुना है ");
        map.put("I have entered ", "मैंने प्रवेश किया है ");
        map.put("I have fallen ", "मैं गिर गया हूँ ");
        map.put("I have fed ", "मैंने खिलाया है ");
        map.put("I have fought ", "मैंने लड़ाई लड़ी है ");
        map.put("I have felt ", "मैंने महसूस किया है ");
        map.put("I have found ", "मैंने पाया है ");
        map.put("I have fled ", "मैं भाग गया हूँ ");
        map.put("I have flown ", "मैंने उड़ान भरी है ");
        map.put("I have forgotten ", "मैं भूल गया ");
        map.put("I have fried ", "मैंने फ्राई किया है ");
        map.put("I have got ", "मुझे मिल गया है ");
        map.put("I have given ", "मैंने दे दिया है ");
        map.put("I have gone ", "मैं गया हूँ ");
        map.put("I have grown ", "मैं बड़ा हो गया हूँ ");
        map.put("I have hanged ", "मैंने फांसी लगा ली है ");
        map.put("I have hung ", "मैंने लटका दिया है ");
        map.put("I have heard ", "मैंने सुना है ");
        map.put("I have helped ", "मैंने मदद की है ");
        map.put("I have hidden ", "मैंने छुपाया है ");
        map.put("I have hit ", "मैंने मारा है ");
        map.put("I have hoped ", "मुझे उम्मीद है ");
        map.put("I have held ", "मैंने आयोजित किया है ");
        map.put("I have kept ", "मैंने रखा है ");
        map.put("I have jumped ", "मैं कूद गया हूँ ");
        map.put("I have hurt ", "मुझे चोट लगी है ");
        map.put("I have killed ", "मैंने मार डाला है ");
        map.put("I have laughed ", "मैं हँसा हूँ ");
        map.put("I have known ", "मुझे पता है ");
        map.put("I have led ", "मैंने नेतृत्व किया है ");
        map.put("I have left ", "मैंने छोड़ दिया है ");
        map.put("I have learnt ", "मैंने सीखा है ");
        map.put("I have leapt ", "मैंने छलांग लगाई है ");
        map.put("I have lent ", "मैंने लेंट किया है ");
        map.put("I have lived ", "मैं रह चुका हूँ ");
        map.put("I have looked ", "मैंने देखा है ");
        map.put("I have lost ", "मैं हार गया ");
        map.put("I have made ", "मैंने बनाया है ");
        map.put("I have loved ", "मैंने प्यार किया है ");
        map.put("I have married ", "मैंने शादी कर ली है ");
        map.put("I have met ", "मैं मिला हूँ ");
        map.put("I have mistaken ", "मैंने गलती की है ");
        map.put("I have opened ", "मैंने खोल दिया है ");
        map.put("I have paid ", "मैंने भुगतान किया है ");
        map.put("I have played ", "मैंने खेला है ");
        map.put("I have quarrelled ", "मैंने झगड़ा किया है ");
        map.put("I have put ", "मैंने डाल दिया है ");
        map.put("I have rained ", "मैंने बारिश की है ");
        map.put("I have reached ", "मैं पहुँच गया हूँ ");
        map.put("I have remembered ", "मुझे याद आया ");
        map.put("I have read ", "मैंने पढ़ा है ");
        map.put("I have ridden ", "मैंने सवारी की है ");
        map.put("I have rung ", "मैंने रिंग की है ");
        map.put("I have run ", "मैंने भाग लिया है ");
        map.put("I have risen ", "मैं उठ गया हूँ ");
        map.put("I have said ", "मैंने कहा है ");
        map.put("I have seen ", "मैंने देखा है ");
        map.put("I have sold ", "मैंने बेच दिया है ");
        map.put("I have sent ", "मैंने भेजा है ");
        map.put("I have shone ", "मैं चमक गया हूँ ");
        map.put("I have shaken ", "मैं हिल गया ");
        map.put("I have shot ", "मैंने गोली मार दी है ");
        map.put("I have shown ", "मैंने दिखाया है ");
        map.put("I have shut ", "मैंने बंद कर दिया है ");
        map.put("I have sung ", "मैंने गाया है ");
        map.put("I have slept ", "मैं सो गया हूँ ");
        map.put("I have smelt ", "मैंने स्मेल्ट किया है ");
        map.put("I have sunk ", "मैं डूब गया हूँ ");
        map.put("I have spoken ", "मैंने बात की है ");
        map.put("I have spent ", "मैंने खर्च किया है ");
        map.put("I have  spoiled ", "मैंने खराब कर दिया है ");
        map.put("I have stood ", "मैं खड़ा हुआ हूँ ");
        map.put("I have started ", "मैंने शुरू कर दिया है ");
        map.put("I have stayed ", "मैं ठहर गया हूँ ");
        map.put("I have studied ", "मैंने पढ़ाई की है ");
        map.put("I have swum ", "मैंने तैर लिया है ");
        map.put("I have stolen ", "मैंने चोरी कर ली है ");
        map.put("I have talked ", "मैंने बात की है ");
        map.put("I have taken ", "मैंने ले लिया है ");
        map.put("I have taught ", "मैंने पढ़ाया है ");
        map.put("I have torn ", "मैंने फाड़ा है ");
        map.put("I have told ", "मैंने कहा है ");
        map.put("I have thanked ", "मैंने धन्यवाद दिया है ");
        map.put("I have thought ", "मैंने सोचा है ");
        map.put("I have thrown ", "मैंने फेंक दिया है ");
        map.put("I have tried ", "मैंने कोशिश की है ");
        map.put("I have walked ", "मैं चल चुका हूँ ");
        map.put("I have understood ", "मैं समझ गया हूँ ");
        map.put("I have used ", "मैंने इस्तेमाल किया है ");
        map.put("I have wanted ", "मैं चाहता था ");
        map.put("I have worn ", "मैंने पहना है ");
        map.put("I have wept ", "मैं रोया हूँ ");
        map.put("I have won ", "मैं जीता हूँ ");
        map.put("I have worked ", "मैंने काम किया है ");
        map.put("I have written ", "मैंने लिखा है ");
        map.put("I have washed ", "मैंने धोया है ");
        return map;
    }
    private static Map<String, String> Two() {
        HashMap<String,String>map = new HashMap<>();
        map.put("I am abusing ", "मैं गाली दे रहा हूँ ");
        map.put("I am answering ", "मैं जवाब दे रहा हूँ ");
        map.put("I am arising ", "मैं उठ रहा हूँ ");
        map.put("I am arriving ", "मैं आ रहा हूँ ");
        map.put("I am asking ", "मैं पूछ रहा हूँ ");
        map.put("I am advising ", "मैं सलाह दे रहा हूँ ");
        map.put("I am awaking ", "मैं जाग रहा हूँ ");
        map.put("I am beating ", "मैं धड़क रहा हूँ ");
        map.put("I am bearing ", "मैं असर कर रहा हूँ ");
        map.put("I am undefined", "मैं अपरिभाषित हूँ");
        map.put("I am becoming ", "मैं बन रहा हूँ ");
        map.put("I am begging ", "मैं भीख माँग रहा हूँ ");
        map.put("I am beginning ", "मैं शुरुआत कर रहा हूँ ");
        map.put("I am binding ", "मैं बाध्यकारी हूँ ");
        map.put("I am biting ", "मैं काट रहा हूँ ");
        map.put("I am blessing ", "मैं आशीष हूँ ");
        map.put("I am blowing ", "मैं उड़ रहा हूँ ");
        map.put("I am breaking ", "मैं तोड़ रहा हूँ ");
        map.put("I am bringing ", "मैं ला रहा हूँ ");
        map.put("I am building ", "मैं निर्माण कर रहा हूँ ");
        map.put("I am burning ", "मैं जल रहा हूँ ");
        map.put("I am buying ", "मैं खरीद रहा हूँ ");
        map.put("I am calling ", "मैं कॉल कर रहा हूँ ");
        map.put("I am carrying ", "मैं ले जा रहा हूँ ");
        map.put("I am catching ", "मैं पकड़ रहा हूँ ");
        map.put("I am cheating ", "मैं धोखा दे रहा हूँ ");
        map.put("I am choosing ", "मैं चुन रहा हूँ ");
        map.put("I am cleaning ", "मैं सफाई कर रहा हूँ ");
        map.put("I am climbing ", "मैं चढ़ रहा हूँ ");
        map.put("I am coming ", "मैं आ रहा हूँ ");
        map.put("I am closing ", "मैं बंद कर रहा हूँ ");
        map.put("I am cooking ", "मैं खाना बना रहा हूँ ");
        map.put("I am creeping ", "मैं रेंग रहा हूँ ");
        map.put("I am crying ", "मैं रो रहा हूँ ");
        map.put("I am cutting ", "मैं काट रहा हूँ ");
        map.put("I am dancing ", "मैं नाच रहा हूँ ");
        map.put("I am dealing ", "मैं काम कर रहा हूँ ");
        map.put("I am dying ", "मैं मर रहा हूँ ");
        map.put("I am digging ", "मैं खुदाई कर रहा हूँ ");
        map.put("I am doing ", "मैं कर रहा हूँ ");
        map.put("I am drinking ", "मैं पी रहा हूँ ");
        map.put("I am dreaming ", "मैं सपना देख रहा हूँ ");
        map.put("I am drawing ", "मैं ड्राइंग कर रहा हूँ ");
        map.put("I am driving ", "मैं गाड़ी चला रहा हूँ ");
        map.put("I am drying ", "मैं सूख रहा हूँ ");
        map.put("I am dropping ", "मैं गिर रहा हूँ ");
        map.put("I am eating ", "मैं खा रहा हूँ ");
        map.put("I am falling ", "मैं गिर रहा हूँ ");
        map.put("I am entering ", "मैं प्रवेश कर रहा हूँ ");
        map.put("I am feeding ", "मैं खिला रहा हूँ ");
        map.put("I am electing ", "मैं चुनाव कर रहा हूँ ");
        map.put("I am fighting ", "मैं लड़ रहा हूँ ");
        map.put("I am feeling ", "मैं महसूस कर रहा हूँ ");
        map.put("I am fleeing ", "मैं भाग रहा हूँ ");
        map.put("I am finding ", "मुझे मिल रहा है ");
        map.put("I am flying ", "मैं उड़ रहा हूँ ");
        map.put("I am forgetting ", "मैं भूल रहा हूँ ");
        map.put("I am frying ", "मैं तलने वाला हूँ ");
        map.put("I am getting ", "मुझे मिल रहा है ");
        map.put("I am going ", "मैं जा रहा हूँ ");
        map.put("I am giving ", "मैं दे रहा हूँ ");
        map.put("I am growing ", "मैं बढ़ रहा हूँ ");
        map.put("I am hanging ", "मैं लटक रहा हूँ ");
        map.put("I am hearing ", "मैं सुन रहा हूँ ");
        map.put("I am helping ", "मैं मदद कर रहा हूँ ");
        map.put("I am hiding ", "मैं छिपा रहा हूँ ");
        map.put("I am hitting ", "मैं मार रहा हूँ ");
        map.put("I am holding ", "मैं पकड़ रहा हूँ ");
        map.put("I am hoping ", "मैं उम्मीद कर रहा हूँ ");
        map.put("I am jumping ", "मैं कूद रहा हूँ ");
        map.put("I am hurting ", "मैं चोट पहुँचा रहा हूँ ");
        map.put("I am keeping ", "मैं रख रहा हूँ ");
        map.put("I am knowing ", "मैं जान रहा हूँ ");
        map.put("I am killing ", "मैं मार रहा हूँ ");
        map.put("I am laughing ", "मैं हँस रहा हूँ ");
        map.put("I am leading ", "मैं अग्रणी हूँ ");
        map.put("I am leaping ", "मैं छलांग लगा रहा हूँ ");
        map.put("I am learning ", "मैं सीख रहा हूँ ");
        map.put("I am lending ", "मैं उधार दे रहा हूँ ");
        map.put("I am leaving ", "मैं जा रहा हूँ ");
        map.put("I am living ", "मैं जी रहा हूँ ");
        map.put("I am looking ", "मैं देख रहा हूँ ");
        map.put("I am loving ", "मैं प्यार कर रहा हूँ ");
        map.put("I am losing ", "मैं हार रहा हूँ ");
        map.put("I am making ", "मैं बना रहा हूँ ");
        map.put("I am marrying ", "मैं शादी कर रहा हूँ ");
        map.put("I am meeting ", "मैं मिल रहा हूँ ");
        map.put("I am opening ", "मैं खोल रहा हूँ ");
        map.put("I am mistaking ", "मैं गलती कर रहा हूँ ");
        map.put("I am playing ", "मैं खेल रहा हूँ ");
        map.put("I am paying ", "मैं भुगतान कर रहा हूँ ");
        map.put("I am putting ", "मैं डाल रहा हूँ ");
        map.put("I am quarrelling ", "मैं झगड़ा कर रहा हूँ ");
        map.put("I am reaching ", "मैं पहुँच रहा हूँ ");
        map.put("I am raining ", "बारिश हो रही है ");
        map.put("I am reading ", "मैं पढ़ रहा हूँ ");
        map.put("I am remembering ", "मुझे याद आ रहा है ");
        map.put("I am riding ", "मैं सवारी कर रहा हूँ ");
        map.put("I am ringing ", "मैं बज रहा हूँ ");
        map.put("I am rising ", "मैं उठ रहा हूँ ");
        map.put("I am running ", "मैं दौड़ रहा हूँ ");
        map.put("I am saying ", "मैं कह रहा हूँ ");
        map.put("I am seeing ", "मैं देख रहा हूँ ");
        map.put("I am selling ", "मैं बेच रहा हूँ ");
        map.put("I am sending ", "मैं भेज रहा हूँ ");
        map.put("I am shaking ", "मैं हिल रहा हूँ ");
        map.put("I am shining ", "मैं चमक रहा हूँ ");
        map.put("I am showing ", "मैं दिखा रहा हूँ ");
        map.put("I am shutting ", "मैं बंद कर रहा हूँ ");
        map.put("I am shooting ", "मैं शूटिंग कर रहा हूँ ");
        map.put("I am singing ", "मैं गा रहा हूँ ");
        map.put("I am sleeping ", "मैं सो रहा हूँ ");
        map.put("I am sinking ", "मैं डूब रहा हूँ ");
        map.put("I am smelling ", "मुझे महक आ रही है ");
        map.put("I am speaking ", "मैं बोल रहा हूँ ");
        map.put("I am spending ", "मैं खर्च कर रहा हूँ ");
        map.put("I am spoilt", "मैं खराब हो गया हूँ");
        map.put("I am standing ", "मैं खड़ा हूँ ");
        map.put("I am staying ", "मैं रह रहा हूँ ");
        map.put("I am starting ", "मैं शुरू कर रहा हूँ ");
        map.put("I am stealing ", "मैं चोरी कर रहा हूँ ");
        map.put("I am taking ", "मैं ले रहा हूँ ");
        map.put("I am swimming ", "मैं तैर रहा हूँ ");
        map.put("I am studying ", "मैं पढ़ रहा हूँ ");
        map.put("I am teaching ", "मैं पढ़ा रहा हूँ ");
        map.put("I am talking ", "मैं बात कर रहा हूँ ");
        map.put("I am tearing ", "मैं फाड़ रहा हूँ ");
        map.put("I am thinking ", "मैं सोच रहा हूँ ");
        map.put("I am thanking ", "मैं धन्यवाद कर रहा हूँ ");
        map.put("I am throwing ", "मैं फेंक रहा हूँ ");
        map.put("I am trying ", "मैं कोशिश कर रहा हूँ ");
        map.put("I am understanding ", "मैं समझ रहा हूँ ");
        map.put("I am using ", "मैं उपयोग कर रहा हूँ ");
        map.put("I am telling ", "मैं बता रहा हूँ ");
        map.put("I am walking ", "मैं चल रहा हूँ ");
        map.put("I am wanting ", "मैं चाह रहा हूँ ");
        map.put("I am washing ", "मैं धो रहा हूँ ");
        map.put("I am wearing ", "मैं पहन रहा हूँ ");
        map.put("I am weeping ", "मैं रो रहा हूँ ");
        map.put("I am winning ", "मैं जीत रहा हूँ ");
        map.put("I am working ", "मैं काम कर रहा हूँ ");
        map.put("I am writing ", "मैं लिख रहा हूँ ");

        return map;
    }

    private static Map<String, String> One() {
        HashMap<String,String>map = new HashMap<>();
        map.put("I  abuse ", "मैंने गाली दी ");
        map.put("I  advise", "मैं सलाह देता हूँ");
        map.put("I  answer ", "मैं जवाब देता हूँ ");
        map.put("I  arise ", "मैं उठता हूँ ");
        map.put("I  arrive ", "मैं पहुँचता हूँ ");
        map.put("I  ask ", "मैं पूछता हूँ ");
        map.put("I  awake ", "मैं जाग गया ");
        map.put("I  beat ", "मैंने हराया ");
        map.put("I  become ", "मैं बन गया ");
        map.put("I  bear ", "मैं सहन करता हूँ ");
        map.put("I  beg ", "मैं विनती करता हूँ ");
        map.put("I  begin ", "मैं शुरू करता हूँ ");
        map.put("I  bless", "मैं आशीर्वाद देता हूं");
        map.put("I  bite", "मैं काटता हूँ");
        map.put("I  bind ", "मैं बाँधता हूँ ");
        map.put("I  break ", "मैं तोड़ता हूँ ");
        map.put("I  bring ", "मैं लाता हूँ ");
        map.put("I  build ", "मैं निर्माण करता हूँ ");
        map.put("I  blow ", "मैं उड़ता हूँ ");
        map.put("I  burn ", "मैं जलता हूँ ");
        map.put("I  call ", "मैं कॉल करता हूँ ");
        map.put("I  buy ", "मैं खरीदता हूँ ");
        map.put("I  carry ", "मैं ले जाता हूँ ");
        map.put("I  catch ", "मैं पकड़ता हूँ ");
        map.put("I  cheat ", "मैं धोखा देता हूँ ");
        map.put("I  choose ", "मैं चुनता हूँ ");
        map.put("I  climb  ", "मैं चढ़ता हूँ  ");
        map.put("I  clean ", "मैं साफ करता हूँ ");
        map.put("I  close ", "मैं बंद करता हूँ ");
        map.put("I  come ", "मैं आता हूँ ");
        map.put("I  cook ", "मैं खाना बनाती हूँ ");
        map.put("I  cry ", "मैं रोता हूँ ");
        map.put("I  creep ", "मैं रेंगता हूँ ");
        map.put("I  cut ", "मैंने काट दिया ");
        map.put("I  dance ", "मैं नृत्य करता हूँ ");
        map.put("I  deal ", "मैं सौदा करता हूँ ");
        map.put("I  die ", "मैं मर जाता हूँ ");
        map.put("I  do ", "मैं करता हूँ ");
        map.put("I  dream ", "मैं सपना देखता हूँ ");
        map.put("I  dig ", "मैं खुदाई करता हूँ ");
        map.put("I  draw ", "मैं आकर्षित करता हूँ ");
        map.put("I  drive ", "मैं ड्राइव करता हूँ ");
        map.put("I  drop ", "मैं छोड़ देता हूँ ");
        map.put("I  dry ", "मैं सूखता हूँ ");
        map.put("I  eat ", "मैं खाता हूँ ");
        map.put("I  elect", "मैं चुनाव करता हूँ");
        map.put("I  enter ", "मैं प्रवेश करता हूँ ");
        map.put("I  feed ", "मैं खिलाता हूँ ");
        map.put("I  fall ", "मैं गिरता हूँ ");
        map.put("I  fight ", "मैं लड़ता हूँ ");
        map.put("I  feel  ", "मुझे लगता है  ");
        map.put("I  find ", "मुझे लगता है ");
        map.put("I  flee ", "मैं भागता हूँ ");
        map.put("I  fly  ", "मैं उड़ता हूँ  ");
        map.put("I  forget ", "मैं भूल जाता हूँ ");
        map.put("I  get  ", "मुझे मिल रहा है  ");
        map.put("I  fry ", "मैं भूनता हूँ ");
        map.put("I  give ", "मैं देता हूँ ");
        map.put("I  go ", "मैं जाता हूँ ");
        map.put("I  grow", "मैं बढ़ता हूँ");
        map.put("I  hang ", "मैं लटकता हूँ ");
        map.put("I  hear ", "मैं सुनता हूँ ");
        map.put("I  help ", "मैं मदद करता हूँ ");
        map.put("I  hide ", "मैं छिपाता हूँ ");
        map.put("I  hold ", "मैं पकड़ता हूँ ");
        map.put("I  hit ", "मैंने मारा ");
        map.put("I  hope ", "मुझे उम्मीद है ");
        map.put("I  hurt ", "मैंने चोट पहुंचाई ");
        map.put("I  jump ", "मैं कूदता हूँ ");
        map.put("I  keep ", "मैं रखता हूँ ");
        map.put("I  kill ", "मैं मारता हूँ ");
        map.put("I  know ", "मुझे पता है ");
        map.put("I  laugh ", "मैं हंसता ");
        map.put("I  lead ", "मैं नेतृत्व करता हूँ ");
        map.put("I  leap ", "मैं छलांग लगाता हूँ ");
        map.put("I  leave ", "मैं छोड़ता हूँ ");
        map.put("I  lend ", "मैं उधार देता हूँ ");
        map.put("I  live ", "मैं रहता हूँ ");
        map.put("I  learn ", "मैं सीखता हूँ ");
        map.put("I  look ", "मैं देखता हूँ ");
        map.put("I  lose ", "मैं हार जाता हूँ ");
        map.put("I  make ", "मैं बनाता हूँ ");
        map.put("I  marry ", "मैं शादी करता हूँ ");
        map.put("I  meet ", "मैं मिलता हूँ ");
        map.put("I  open ", "मैं खोलता हूँ ");
        map.put("I  mistake ", "मैं गलती करता हूँ ");
        map.put("I  pay  ", "मैं भुगतान करता हूँ  ");
        map.put("I  play ", "मैं खेलता हूँ ");
        map.put("I  put ", "मैंने रखा ");
        map.put("I  rain ", "मैं बारिश करता हूँ ");
        map.put("I  love ", "मैं प्यार करता हूँ ");
        map.put("I  quarrel ", "मैं झगड़ा करता हूँ ");
        map.put("I  reach ", "मैं पहुँचता हूँ ");
        map.put("I  read", "मैंने पढ़ा");
        map.put("I  remember  ", "मुझे याद है  ");
        map.put("I  ride ", "मैं सवारी करता हूँ ");
        map.put("I  say ", "मैं कहता हूँ ");
        map.put("I  see ", "मैं देख रहा हूँ ");
        map.put("I  ring ", "मैं रिंग करता हूँ ");
        map.put("I  send ", "मैं भेजता हूँ ");
        map.put("I  shake ", "मैं हिलाता हूँ ");
        map.put("I  rise  ", "मैं उठता हूँ  ");
        map.put("I  run  ", "मैं दौड़ता हूँ  ");
        map.put("I  sell ", "मैं बेचता हूँ ");
        map.put("I  shine ", "मैं चमकता हूँ ");
        map.put("I  shoot ", "मैं गोली मारता हूँ ");
        map.put("I  show ", "मैं दिखाता हूँ ");
        map.put("I  shut  ", "मैंने बंद कर दिया  ");
        map.put("I  sing ", "मैं गाता हूँ ");
        map.put("I  sink ", "मैं डूबता हूँ ");
        map.put("I  sleep ", "मैं सोता हूँ ");
        map.put("I  smell ", "मुझे गंध आती है ");
        map.put("I  speak ", "मैं बोलता हूँ ");
        map.put("I  spend", "मैं खर्च करता हूँ");
        map.put("I  spoil", "मैं खराब करता हूँ");
        map.put("I  stand", "मैं खड़ा हूँ");
        map.put("I  start ", "मैं शुरू करता हूँ ");
        map.put("I  stay ", "मैं रहता हूँ ");
        map.put("I  steal ", "मैं चोरी करता हूँ ");
        map.put("I  swim ", "मैं तैरता हूँ ");
        map.put("I  take ", "मैं लेता हूँ ");
        map.put("I  study ", "मैं पढ़ता हूँ ");
        map.put("I  talk ", "मैं बात करता हूँ ");
        map.put("I  teach ", "मैं सिखाता हूँ ");
        map.put("I  tear ", "मैंने फाड़ दिया ");
        map.put("I  tell ", "मैं बताता हूँ ");
        map.put("I  thank", "मैं धन्यवाद करता हूँ");
        map.put("I  think ", "मुझे लगता है ");
        map.put("I  throw ", "मैं फेंकता हूँ ");
        map.put("I  understand ", "मैं समझता हूँ ");
        map.put("I  try ", "मैं कोशिश करता हूँ ");
        map.put("I  use ", "मैं उपयोग करता हूँ ");
        map.put("I  walk", "मैं चलता हूँ");
        map.put("I  want ", "मैं चाहता हूँ ");
        map.put("I  wash ", "मैं धोता हूँ ");
        map.put("I  wear ", "मैं पहनता हूँ ");
        map.put("I  weep", "मैं रोता हूँ");
        map.put("I  work ", "मैं काम करता हूँ ");
        map.put("I  win ", "मैं जीतता हूँ ");
        map.put("I  write ", "मैं लिखता हूँ ");
        return map;
    }
}
